window.LANSA.addSrc("evef",function(d,c,a,b){d.Db("PRIM_EVP");d.Db("PRIM_EDIT");c.IYb=function(b){p.H.call(this,b);this.Qm|=a.V8a.uvb;this.uf|=268435456;this.Aa=new c.HYb(this);this.Aa.Oa(this);this.Aa.ta(this,a.w.ph,this.xB)};var p=c.q(c.IYb,c.j6);p.nb=function(){b.$(this.Aa);this.Aa=null;p.j.nb.call(this)};p.zca=function(){return this.Aa};p.Rq=function(b){this.Aa.lo()!=b&&(this.Aa.Rq(b),this.ea(a.g.h))};p.lo=function(){return this.Aa.lo()};p.Tu=function(b){this.Aa.Tr()!=b&&(this.Aa.Tu(b),this.ea(a.g.h))};
p.Tr=function(){return this.Aa.Tr()};p.fC=function(b){this.Aa.Lw()!=b&&(this.Aa.fC(b),this.ea(a.g.h))};p.Lw=function(){return this.Aa.Lw()};p.Jw=function(){return this.Hn()!=this.gq()};p.gq=function(){return this.Aa.gq()};p.sr=function(a){this.Aa.sr(a)};p.Hn=function(){return this.Aa.Hn()};p.rr=function(a){this.Aa.rr(a)};p.gc=function(){return this.Aa.gc()};p.Hv=function(){return this.Aa.ca};p.oO=function(a){1==a?this.Ep(268435456):this.Ep(0)};p.NJ=function(){var a=0;268435456==this.Uj()&&(a=1);return a};
p.Ep=function(b){this.Uj()!=b&&(this.uf=this.uf&~a.pi.cla|b,this.Ch(),this.k(a.g.h))};p.Uj=function(){return this.uf&a.pi.cla};p.kPa=function(){return this.fK()?!0:!1};p.fK=function(){return 0<this.Uj()};p.WFa=function(){this.Pe()&&this.Pe().Qb(this.Aua);this.Aa&&this.Aa.Qb(this.fua)};p.tAa=function(){this.Aa.Pg(this.hb());this.Aa.by(!0);this.Aa.Xv(!0);this.Aa.k7(this.HV());this.Aa.lh(this.Ve());this.Aa.bL(this.lk());this.Aa.z7(this.hM);this.Aa.to(this.Fm());this.Aa.vm(this.Hj());this.Aa.Xu(this.Jx());
this.Aa.qk(this.Fi());this.Aa.pk(this.Vh());this.Aa.Pn(this.Ml());this.hb().iPa()&&this.Aa.$t("*")};p.z_=function(a){this.tAa();p.j.z_.call(this,a)};p.Cj=function(){this.tAa();p.j.Cj.call(this)};p.gf=function(a){if(this.Aa){var c=this.Ue(),d,k,h;this.Md()?(k=this.Tg,h=this.Ug,d=c.aa()-(this.Tg+this.Yi),c=c.ba()-(this.Ug+this.Xi)):(k=this.Qe(),h=this.He(),d=c.aa()-(this.Qe()+this.Pf()),c=c.ba()-(this.He()+this.Zf()));this.Aa.kb(b.Bh(k,h,d,c))}p.j.gf.call(this,a)};p.Ala=function(){var a;this.Aa&&(a=
this.Aa.Kk());return a};p.lG=function(a,b){a&&a.Ba(this,this.io);b&&b.Fa(this,this.io);this.Aa.Pg(b)};p.kr=function(){this.Aa.df()};p.ag=function(a){null!=this.Aa&&this.Aa.bL(this.lk());p.j.ag.call(this,a);this.Aa&&(this.Aa.ms(null),this.Aa.by(!0),this.Aa.Xv(!0),this.Xz&&this.Aa.ms(this.Xz))};p.gvb=function(){this.Aa&&this.Aa.ahc()};p.G0=function(a,b){this.Aa&&this.Aa.G0(a,b)};p.gZ=function(){this.Aa&&this.Aa.gZ()};p.yM=function(a){this.Aa&&this.Aa.yM(a)};p.iO=function(a){this.Aa&&this.Aa.iO(a)};
p.xB=function(){this.qc()};p.io=function(){};p.fLa=p[a.Z.mda]=function(){this.Aa&&this.K7(this.i_())};p.OM=p[a.Z.Pw]=function(){this.Aa.df()};p.PM=p[a.Z.uK]=function(){this.Aa.df()};d.wd(c.IYb,"PRIM_EVEF",{kO:a.ux.Baa,Pa:{ComponentVersion:{a:p.NJ,f:function(a){this.oO(d.v(a))}},AutoTab:{a:p.HV,f:function(a){this.k7(d.wa(a))}},AutoSelect:{a:p.Fm,f:function(a){this.to(d.wa(a))}},WordWrap:{a:p.Sd,f:function(a){this.Se(d.wa(a))}},ShowSelection:{a:p.Hj,f:function(a){this.vm(d.wa(a))}},ShowSelectionHilight:{a:p.Jx,
f:function(a){this.Xu(d.wa(a))}},ShowPrompter:{a:p.E5,f:function(a){this.Hqa(d.wa(a))}},PrompterImage:{a:p.GNa,f:p.H7},PrompterTabStop:{a:p.hza,f:function(a){this.Gpb(d.wa(a))}},UsePicklist:{a:p.oOa,f:function(a){this.e1(d.wa(a))}},EditAlignment:{a:function(){return d.sa(this.Fi(),a.dm.u)},f:function(b){this.qk(d.qa(b,a.dm.u))}},DisplayAlignment:{a:function(){return d.sa(this.Vh(),a.oi.u)},f:function(b){this.pk(d.qa(b,a.oi.u))}},Text:{a:p.zla},SelectionEnd:{a:p.Hn,f:function(a){this.rr(d.v(a))}},
SelectionStart:{a:p.gq,f:function(a){this.sr(d.v(a))}},VisualStyleEdit:{a:p.Ibb,f:p.AEa},NumericEditStyle:{a:function(){return d.sa(this.Ml(),a.Nn.u)},f:function(b){this.Pn(d.qa(b,a.Nn.u))}},HasSelection:{a:p.Jw},EditStyle:{a:p.c5,f:p.cfa},EditStyles:{a:p.Jla},EditMouseOverStyle:{a:p.QMa,f:p.dUa},EditMouseOverStyles:{a:p.RMa},EditFocusedStyle:{a:p.OMa,f:p.cUa},EditFocusedStyles:{a:p.PMa},LabelStyle:{a:p.l5,f:p.gfa},LabelStyles:{a:p.fNa},LabelMouseOverStyle:{a:p.dNa,f:p.tUa},LabelMouseOverStyles:{a:p.eNa},
InputType:{a:function(){return d.sa(this.lo(),a.Re.u)},f:function(b){this.Rq(d.qa(b,a.Re.u))}},InputTypePattern:{a:p.Tr,f:function(a){this.Tu(d.ka(a))}},SpellCheck:{a:p.Lw,f:function(a){this.fC(d.wa(a))}},Value:{a:function(){return this.Da()},f:function(a){this.Wa(a)}}},pc:{SelectText:function(a,b){this.G0(d.v(a)-1,d.v(b))}},Bg:{wg:"Value"}});c.HYb=function(a){u.H.call(this);this.Ijc=a};var u=c.q(c.HYb,c.KW);u.jW=function(){return this.Ijc.Os()||this.Ijc.iM?!1:u.j.jW.call(this)}},{rp:["PRIM_EVP",
"PRIM_EDIT"]});
