window.LANSA.addSrc("wrtn",function(d,c,a,b,p){function u(a){return null===a?d.dd:"object"==typeof a?a.mimetype&&a.data&&a.filename?new c.XH(a):"":a}function t(a){if(a===d.dd)return null;switch(typeof a){case "object":if(a instanceof c.Jj)return a.toString();if(c.lq&&a instanceof c.lq)return a.cfc();if(a instanceof c.XH)return a.uua}return a}function r(b,c,d){var e=document.createElement("form");e.setAttribute("method","post");e.setAttribute("action",b);d==a.MX.Hdc&&e.setAttribute("target","_blank");
for(var g in c)c.hasOwnProperty(g)&&(b=document.createElement("input"),b.setAttribute("type","hidden"),b.setAttribute("name",g),b.setAttribute("value",c[g]),e.appendChild(b));document.body.appendChild(e);e.submit()}function n(a){return(a=a.sm)&&"M"==a}function k(a,b){q&&b.append("_SESSIONKEY",q);var e=a.FLD;if(e!==p)for(var g in e){var f=e[g];if(f===d.dd)return!1;f instanceof c.XH?b.append(g,f.Sla(),f.Yg()):b.append(g,t(f))}e=a.LIST;if(e!==p)for(var h in e){for(var k=e[h],n=k.Kp={},r=k.entryCount(),
v=1;v<=r;v++)for(g in k.getEntry(v),1==v&&b.append(h+"..",1),n){f=v.toString();4>f.length&&(f="000"+f,f=f.substr(f.length-4));var u=h+"."+f+"."+g,f=n[g];if(f===d.dd)return delete k.Kp,!1;f instanceof c.XH?b.append(u,f.Sla(),f.Yg()):b.append(u,t(f))}delete k.Kp}return!0}function h(a,b){var c=b.webroutine={},d=c.context={};q&&(d["session-key"]=q);g&&(d["session-key-name"]=g);B&&(d["session-key-method"]=B);d=a.FLD;if(d!==p){var e=c.fields={},f;for(f in d)(e[f]={}).value=t(d[f])}d=a.LIST;if(d!==p){var c=
c.lists={},h;for(h in d){for(var k=c[h]={},e=k.header=[],k=k.entries=[],n=d[h],r=n.Kp={},v=n.entryCount(),u=1;u<=v;u++){n.getEntry(u);if(1==u)for(f in r){var F={};e.push(F);F.name=f}F=[];k.push(F);for(f in r)F.push(t(r[f]))}delete n.Kp}}}function f(a){if(a=a.context)q=a["session-key"],g=a["session-key-name"],B=a["session-key-method"]}function e(a,b,c){function e(a){if(a!=p){var b=a.FLD;g(a.LIST);g(b)}}function g(b){if(b!=p)for(var c in b)if(null===b[c])throw d.mZc(c,a.nva,a.kva);}e(b);e(c)}var q=
p,g=p,B=p;a.MX={isb:0,Hdc:1};a.MX.u={CURRENT:a.MX.isb,NEW:a.MX.Hdc};d.wd(function(){},"PRIM_WRTN",{});c.fCa=function(a,b){v.H.call(this);this.nva=a;this.kva=b;this.Pzb=this.Uyb=""};var v=c.q(c.fCa,c.Hd);v.Nxd=function(){return this.Uyb};v.eQd=function(a){this.Uyb=a};v.Szd=function(){return this.Pzb};v.AQd=function(a){this.Pzb=a};v.OHc=function(){return this.nva};v.CHc=function(){return this.kva};v.JB=function(){return b.Vrc(this.Uyb,b.HMa(),this.nva,this.kva,this.oHc())};v.oHc=function(){var a=this.Pzb;
""==a&&(a=b.GMa());return a};d.mb(c.fCa,"PRIM_WEB","ServerRequest",{Pa:{ServerModule:{a:v.OHc},Routine:{a:v.CHc}}});c.qoa=function(a,b){F.H.call(this,a,b)};var F=c.q(c.qoa,c.fCa);F.EV=function(a,b){this.ULb(a,b,!1,null)};F.cba=function(a,c){this.ULb(a,c,!0,b.bT())};F.ULb=function(c,r,v,t){function F(c){var e=null;try{e=JSON.parse(c)}catch(h){e=null}if(e){if(c=e.webroutine)if(c=c.messages)for(var k=d.oGc(),n=0;n<c.length;n++)k.Jh(c[n],null);if(c=e["vlweb-error"]){var A=a.qT.bMa;switch(c["message-id"]){case "HM42":case "HM43":A=
a.qT.WMb;B=g=q=p;break;case "HM05":A=a.qT.VMb}A=R.Wxa(A);if(!A&&c.message!==p)throw d.enb(R.nva,R.kva,c.message);}else{k=r;if(e=e.webroutine){n=k.FLD;if(n!==p){var v=e.fields;if(v)for(var C in n)c=v[C],c!==p&&(c=u(c.value),n[C].set(c))}C=k.LIST;if(C!==p&&(k=e.lists))for(A in C)if(n=C[A],n.Dk(),c=k[A])for(var v=c.header,x=c.entries,z=0;z<x.length;z++){for(var da=n.Kp={},ra=x[z],D=0;D<ra.length;D++)c=u(ra[D]),da[v[D].name]=c;n.Wg();delete n.Kp}f(e)}R.yZ()}}else if(A=R.Wxa(a.qT.bMa),!A)throw d.enb(R.nva,
R.kva,"Invalid JSON");b.lz(t)}function C(c){if(!R.Wxa(a.qT.bMa))throw d.enb(R.nva,R.kva,"response code "+c);b.lz(t)}function x(a){a.lengthComputable&&R.rAc(a.loaded,a.total,d.v(a.loaded/a.total*100))}function z(a){if(a.lengthComputable){var b=a.loaded/a.total*100;R.yMb(a.loaded,a.total,d.v(b))}else R.yMb(a.loaded,-1,-1)}var R=this;e(R,c,r);if(n(c)){var fa=new FormData;if(k(c,fa)){b.eWc(this.JB(),fa,F,C,x,z,v);return}}fa={};h(c,fa);b.K7b(this.JB(),fa,F,C,x,z,v)};F.Wxa=function(c){var e=!1,e=d.Yb();
e.EQ("REASON",c,a.qT.u);e.Gf("HANDLED",!1);this.Ca(a.w.xZ,e);(e=e.zg("HANDLED"))||(e=b.oq().kAc(this,c));return e};F.yZ=function(){this.Ca(a.w.l4)};F.rAc=function(b,c,e){var g=d.Yb();g.SC("LOADED",b);g.SC("TOTAL",c);g.SC("PROGRESS",e);this.Ca(a.w.Hhd,g)};F.yMb=function(b,c,e){var g=d.Yb();g.SC("LOADED",b);g.SC("TOTAL",c);g.SC("PROGRESS",e);this.Ca(a.w.Pxc,g)};d.mb(c.qoa,"PRIM_WEB","DataRequest",{pc:{Execute:F.EV,ExecuteAsync:F.cba}});c.Moa=function(b,c){C.H.call(this,b,c);this.zm=a.MX.isb};var C=
c.q(c.Moa,c.fCa);C.AIc=function(){return this.zm};C.Xpb=function(a){this.zm=a};C.EV=function(a,b){e(this,a,b);var c={};q&&(c._SESSIONKEY=q);var d=a.FLD;if(d!==p)for(var g in d)c[g]=t(d[g]);d=a.LIST;if(d!==p)for(var f in d){for(var h=d[f],k=h.Kp={},n=h.entryCount(),v=1;v<=n;v++)for(g in h.getEntry(v),1==v&&(c[f+".."]=1),k){var u=v.toString();4>u.length&&(u="000"+u,u=u.substr(u.length-4));c[f+"."+u+"."+g]=t(k[g])}delete h.Kp}r(this.JB(),c,this.zm)};d.mb(c.Moa,"PRIM_WEB","WebPageRequest",{Pa:{Target:{a:function(){return d.sa(this.zm,
a.MX.u)},f:function(b){this.Xpb(d.qa(b,a.MX.u))}}},pc:{Execute:C.EV}});c.Foa=function(b,c){R.H.call(this,b,c);this.zm=a.MX.isb};var R=c.q(c.Foa,c.fCa);R.AIc=function(){return this.zm};R.Xpb=function(a){this.zm=a};R.EV=function(a,b){e(this,a,b);var c={};q&&(c._SESSIONKEY=q);var d=a.FLD;if(d!==p)for(var g in d)c[g]=t(d[g]);d=a.LIST;if(d!==p)for(var f in d){for(var h=d[f],k=h.Kp={},n=h.entryCount(),v=1;v<=n;v++)for(g in h.getEntry(v),1==v&&(c[f+".."]=1),k){var u=v.toString();4>u.length&&(u="000"+u,u=
u.substr(u.length-4));c[f+"."+u+"."+g]=t(k[g])}delete h.Kp}r(this.JB(),c,this.zm)};d.mb(c.Foa,"PRIM_WEB","ResourceRequest",{Pa:{Target:{a:function(){return d.sa(this.zm,a.MX.u)},f:function(b){this.Xpb(d.qa(b,a.MX.u))}}},pc:{Execute:R.EV}});b.gzc=function(b,c){var d=c.webroutine;if(d){var e=b.WA.Qya(),g=d.fields;if(g){var f=b.ADa(e),h;for(h in g){var k=null,q=b.Yk[h];q&&(k=q.WU());if(!k&&f)for(var n in f)if(q=f[n],q.zh()==h){k=q;break}k&&(q=u(g[h].value),k.set(q))}}if(d=d.lists){var e=b.w_c(e),r;for(r in d){g=
null;if(q=b.Yk[r])switch(q.sya()){case a.ux.Zhc:case a.ux.QXa:case a.ux.N4a:g=q}!g&&e&&(g=e[r]);if(g)for(q=d[r],f=q.header,h=q.entries,k=0;k<h.length;k++){n=g.Kp={};for(var v=h[k],p=0;p<v.length;p++)q=u(v[p]),n[f[p].name]=q;g.Wg();delete g.Kp}}}}};b.fzc=function(a){(a=a.webroutine)&&f(a)}});
