window.LANSA.addSrc("gpbx",function(d,c,a,b){a.Fyc={KVd:0,JVd:9,kjd:6,LVd:5,MVd:10};a.DJc={LAc:0};c.n1b=function(){p.H.call(this);this.myb=a.Fyc.kjd;this.aJ=a.DJc.LAc;this.sM=new c.fa;new c.fa;this.Vc=this.Vc|a.cc.kda|a.cc.NAa|a.cc.Kfb|a.cc.DF|a.cc.DW|a.cc.CF;this.Jg=this.Jg|a.qh.mS|a.qh.L_;this.Ke(!1)};var p=c.q(c.n1b,c.xK);p.hh=function(){return c.I4b};p.QPd=function(b){this.myb!=b&&(this.myb=b,this.k(a.g.h),this.Nw())};p.Vwd=function(){return this.myb};p.lr=function(a){p.j.lr.call(this,a);this.hVc()};
p.Gub=function(){if(this.Ub()){var a=this.re(),a=Math.abs(a.Ia()),d=this.Ue();this.Md();this.Md();d.Va(d.O()+a);new c.fa;""==this.eb()?(d.Ra(d.O()),d.Ga(a)):(this.eb(),d.Ra(d.O()+this.ER()),d.Ga(this.ula()),d.Ra(d.va+a));b.Ln(this.sM,d)||(this.sM=d,this.ob());this.lr(!0)}};p.gf=function(a){a.Ta(a.M()+this.sM.ba());a.Va(a.O()+4);a.Ra(a.va-4);a.Ga(a.ua-4);p.j.gf.call(this,a)};p.aYc=function(a,b,c){a.Ta(a.M()+this.sM.ba());a.Va(a.O()+4);a.Ra(a.va-4);a.Ga(a.ua-4);p.j.aYc.call(this,a,b,c)};p.Cj=function(){p.j.Cj.call(this);
this.Gd(a.Z.OB)};p.ad=function(){var b=this.EN()||this.Ol()&&(this.K_()||this.kS());this.pJ(a.cc.IN,b);p.j.ad.call(this)};p.PF=function(a){var b=!1,b=a.Dd().TSa(this,this.ca.Kh,this.K_(),this.kS(),a);!1==b&&p.j.PF.call(this,a)};p.UW=function(a){var b=!1;null!=a.Dd()&&a.ga().Ol()&&(b=a.Dd().USa(this,this.ca.Kh,a,this.K_(),this.kS()));!1==b&&p.j.UW.call(this,a)};p.ve=function(b){""==b[1]&&(b[1]=a.pWb);p.j.ve.call(this,b)};p.hVc=function(){var a=this.Ue(),a=this.YC(a,null),c=this.Ue();c.Ta(c.M()+this.sM.ba()/
2+1);c.Va(c.O()+2);c.Ra(c.va-2);c.Ga(c.ua-2);var d=this.Sa().fb(),k=this.eb();b.Yd[d].nh(k,c,this.sM);b.$(a)};p.Jt=p[a.Z.VH]=function(a){this.Gub();p.j.Jt.call(this,a)};p.zv=p[a.Z.UH]=function(){p.j.zv.call(this);this.Gub()};p.QM=p[a.Z.OB]=function(){this.Gub();this.Nw()};p.owc=p[a.Z.ogb]=function(){this.Ch()};d.wd(c.n1b,"PRIM_GPBX",{Pa:{Caption:{a:p.eb,f:function(a){this.ub(d.ka(a))}},ThemeStyle:{a:function(){return d.sa(this.wN(),a.dw.u)},f:function(b){this.wEa(d.qa(b,a.dw.u))}}}});c.I4b=function(a){u.H.call(this,
a);this.qb=this.tYa=this.qGa=this.pe=this.Qc=null};var u=c.q(c.I4b,c.d0);u.cf=function(a,b){var c=null;u.j.cf.call(this,a,b);this.tYa=4;this.Qc=document.createElement("div");this.pe=document.createElement("div");this.qGa=document.createElement("div");this.qb=document.createElement("span");this.G.appendChild(this.Qc);this.G.appendChild(this.pe);this.G.appendChild(this.qGa);this.G.appendChild(this.qb);this.Ddb(this.Qc,this.tYa);this.Ddb(this.pe,0);this.Ddb(this.qGa,0);c=this.Qc.style;c.borderTopWidth=
"0px";c=this.pe.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.qGa.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.qb.style;c.position="absolute";c.whiteSpace="nowrap";c.cursor="inherit";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";return this.G};u.Ddb=function(a,b){var c=a.style;c.position="absolute";c.overflowX="hidden";c.overflowY=
"hidden";c.whiteSpace="nowrap";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";c.borderStyle="solid";c.outline="none";c.background="rgba(0,0,0,0)";c.borderTopWidth="1px";c.borderBottomWidth="1px";c.borderLeftWidth="1px";c.borderRightWidth="1px";c.borderTopLeftRadius=b+"px";c.webkitBorderTopLeftRadius=b+"px";c.borderTopRightRadius=b+"px";c.webkitBorderTopRightRadius=b+"px";c.borderBottomLeftRadius=b+"px";c.webkitBorderBottomLeftRadius=b+"px";c.borderBottomRightRadius=
b+"px";c.webkitBorderBottomRightRadius=b+"px"};u.nh=function(a,b,c){var d=this.Qc.style;d.left=b.O()+"px";d.top=b.M()+"px";d.width=b.aa()+"px";d.height=b.ba()+"px";d.borderColor=this.lm();d=this.pe.style;d.left=b.O()+this.tYa-1+"px";d.top=b.M()+"px";d.width=c.O()-b.O()+"px";d.height="1px";d.borderColor=this.lm();d=this.qGa.style;d.left=c.va+2+"px";d.top=b.M()+"px";d.width=b.va-this.tYa-c.va+"px";d.height="1px";d.borderColor=this.lm();d=this.qb.style;d.left=c.O()+7+"px";d.top=c.M()+2+"px";d.height=
c.ba()+"px";d.width=c.aa()+"px";this.qb.textContent=a}});
