window.LANSA.addSrc("labl",function(d,c,a,b){a.Gvb={DVd:0,Kvb:16};a.R_={cSc:1,Kgb:1,Jgb:2,bXb:240};a.Hgb={pRa:0,u5b:1};c.St=function(){p.H.call(this);this.Ke(!1);this.Bqa(!1)};var p=c.q(c.St,c.Qt);p.tt=a.kp.$aa;p.fU=a.R_.cSc;p.via=a.Hgb.pRa;p.OC=0;p.AC=0;p.DC=0;p.tC=0;p.ml=null;p.uP=a.Pk.IS;p.Ka=null;p.tw=0;p.jY=a.Rd.FI;p.d3=new c.TN(0,0,0,0);p.sM=new c.TN(0,0,0,0);p.Vc=p.Vc|a.cc.kda|a.cc.NAa|a.cc.Kfb|a.cc.DF|a.cc.DW|a.cc.Lfb|a.cc.CF;p.Jg=p.Jg|a.qh.Pna|a.qh.mS|a.qh.L_;p.R=function(){this.ml&&(this.ml.Ba(this,
this.k7a),this.ml=null);p.j.R.call(this);this.od(null)};p.hh=function(){return c.Tjb};p.aC=function(c){this.ml!=c&&(this.ml&&this.ml.Ba(this,this.k7a),this.ml=c,null==this.ml?this.Bqa(!1):(this.Bqa(!0),this.ml.Fa(this,this.k7a)),this.k(a.g.h),b.gb().Jd(this,!1))};p.dF=function(){return this.ml};p.Sd=function(){return 0!=(this.fU&a.R_.Kgb)?!0:!1};p.Ix=function(){return!this.po()&&this.Sd()};p.Se=function(c){c=this.fU&~a.R_.Kgb|(c?a.R_.Kgb:0);this.fU!=c&&(this.fU=c,this.yd(),b.gb().Jd(this,!1),this.ea(a.g.h))};
p.SNa=function(){return 0!=(this.fU&a.R_.Jgb)?!0:!1};p.Gbc=function(b){b=this.fU&~a.R_.Jgb|(b?a.R_.Jgb:0);this.fU!=b&&(this.fU=b,this.Ch(),this.ea(a.g.h))};p.RRd=function(c){this.rOa()!=c&&(this.fU=this.fU&~a.R_.bXb|c,this.yd(),b.gb().Jd(this,!1),this.ea(a.g.h))};p.rOa=function(){return this.fU&a.R_.bXb};p.Uf=function(c){this.tt!=c&&(this.tt=c,b.gb().Jd(this,!1),this.ea(a.g.h))};p.$e=function(){return this.tt};p.He=function(){return this.OC};p.td=function(c){this.OC!=c&&(this.OC=c,this.yd(),b.gb().Jd(this,
!1),this.ea(a.g.h))};p.Qe=function(){return this.AC};p.$d=function(c){this.AC!=c&&(this.AC=c,this.yd(),b.gb().Jd(this,!1),this.ea(a.g.h))};p.Pf=function(){return this.DC};p.Ed=function(c){this.DC!=c&&(this.DC=c,this.yd(),b.gb().Jd(this,!1),this.ea(a.g.h))};p.Zf=function(){return this.tC};p.Be=function(c){this.tC!=c&&(this.tC=c,this.yd(),b.gb().Jd(this,!1),this.ea(a.g.h))};p.Zs=function(c){this.uP!=c&&(this.uP=c,b.gb().Jd(this),this.k(a.g.h))};p.Oc=function(){return this.Ka};p.od=function(c){this.Ka!=
c&&(null!=this.Ka&&(this.Ka.Ba(this,this.En),this.Ka.Cb()),this.Ka=c,null!=this.Ka&&(this.Ka.Ha(),this.Ka.Fa(this,this.En)),this.yd(),b.gb().Jd(this),this.k(a.g.h))};p.Iv=function(){return this.uP};p.Lt=function(){return this.tw};p.gs=function(c){c!=this.tw&&(this.tw=c,this.yd(),this.ea(a.g.h),b.gb().Jd(this))};p.lD=function(){return this.jY};p.dC=function(b){this.jY!=b&&(this.jY=b,this.yd(),this.k(a.g.h))};p.$m=function(){var b=a.ce.GD;switch(this.hg()){case a.fh.mB:switch(this.iW()){case a.dh.Wq:b=
a.ce.GD;break;case a.dh.PO:b=a.ce.cSa;break;default:b=a.ce.eSa}break;case a.fh.uJ:switch(this.iW()){case a.dh.Wq:b=a.ce.dSa;break;case a.dh.PO:b=a.ce.f7b;break;default:b=a.ce.h7b}break;default:switch(this.iW()){case a.dh.Wq:b=a.ce.p0;break;case a.dh.PO:b=a.ce.e7b;break;default:b=a.ce.FS}}return b};p.xD=function(){return 0!=(this.via&a.Hgb.u5b)};p.LFd=function(a){this.via|=a};p.$Oc=function(a){this.via&=~a};p.MFd=function(a,b){this.via=this.via&~a|(b?a:0)};p.Qd=function(a,b,c){p.j.Qd.call(this,a,b,
c);this.lr(!1)};p.X6=function(a){p.j.X6.call(this,a);this.lr(a)};p.lr=function(a){p.j.lr.call(this,a);a=this.Ue();this.sJb(a,!1)};p.Cj=function(){p.j.Cj.call(this);this.Gd(a.Z.OB);this.Gd(a.Z.VAa)};p.ad=function(){this.pJ(a.cc.IN,this.EN());p.j.ad.call(this)};p.kr=function(a){null!=this.ml?this.ml.df():p.j.kr.call(this,a)};p.ag=function(){this.s0();b.gb().XC(this)};p.ID=function(){this.VU()};p.PF=function(a){var b=!1,b=a.Dd().WSa(this,this.ca.Kh,this.jfb(),this.lfb(),this.kfb(),a);!1==b&&p.j.PF.call(this,
a)};p.ve=function(b){""==b[1]&&(b[1]=a.rWb);p.j.ve.call(this,b)};p.sJb=function(a,d){var n=b.uc(a),k=b.uc(n),h=null,f=0<this.tw?this.tw:-1;this.Ka&&(h=this.Ka.GEb(n.ba()-4,n.ba()-4));n.Ta(n.M()+this.OC);n.Va(n.O()+this.AC);n.Ra(n.va-this.DC);n.Ga(n.ua-this.tC);var e=this.eb(),q=new c.fa,g=new c.fa,B=[],v="";B[0]=q;B[1]=k;B[2]=g;B[3]=f;B[4]=f;B[5]=0;this.wDa(null,h,e,this.re(),n,B);q=B[0];k=B[1];n=B[5];this.Ka&&this.Ka instanceof c.ON&&(v=this.Ka.Yg());this.d3=q;this.sM=k;d||(h=this.Sa().fb(),f=this.Ix(),
b.Yd[h].nh(h,k,v,q,f,this.SNa(),n))};p.wDa=function(d,r,n,k,h,f){d=f[0];var e=f[1],q=f[2],g=f[3],B=f[4],v=f[5],e=b.uc(h);if(null!=r&&this.Md()){var p=a.cg.SEa;this.dF()||(p|=a.cg.$Va);v=p;if(this.Ix())switch(this.rOa()){case a.Gvb.Kvb:p|=a.cg.gC;break;default:p|=a.cg.gC,v|=a.cg.gC}else v|=this.tt;switch(this.hg()){case a.fh.mB:v|=a.cg.Jfa;break;case a.fh.uJ:v|=a.cg.UEa;break;default:v|=a.cg.usb}b.doa(r,n,k,h,0,this.$m(),this.$m(),this.Iv(),d,e,q,0,this.Md()?0:2,g,B,p)}else if(v=this.KDb(e),0<n.length){e.aa()>
h.aa()&&(this.Ix()?this.rOa()==a.Gvb.Kvb&&(e=new c.fa(0,0,h.aa(),e.ba())):e=new c.fa(0,0,h.aa(),e.ba()));switch(this.hg()){case a.fh.mB:e=new c.fa(h.O()+(h.aa()-e.aa())/2,1,e.aa(),e.ba());v|=a.cg.Jfa;break;case a.fh.uJ:e=new c.fa(h.va-e.aa(),1,e.aa(),e.ba());v|=a.cg.UEa;break;default:e=new c.fa(h.O(),1,e.aa()+1,e.ba()),v|=a.cg.usb}switch(this.iW()){case a.dh.Wq:e=new c.fa(e.O(),h.M()+(h.ba()-e.ba())/2,e.aa(),e.ba());break;case a.dh.PO:e=new c.fa(e.O(),h.ua-1-e.ba(),e.aa(),e.ba())}}f[0]=d;f[1]=e;f[2]=
q;f[3]=g;f[4]=B;f[5]=v};p.KDb=function(c){var d=this.re(),n=a.cg.SEa,k=this.eb();if(0<k.length)if(this.dF()||(n|=a.cg.$Va),this.PA=b.cO(k,d,this.Ix(),c.aa(),c.ba()),this.Ix())switch(this.rOa()){case a.Gvb.Kvb:b.CD(k,c,n|a.cg.gC,d);break;default:b.CD(k,c,n|a.cg.gC,d),n|=a.cg.gC}else b.CD(k,c,n,d),n|=this.tt;return n};p.fqc=function(){var a=b.sS();this.$j(!1,!0);this.KDb(a);this.Wb(a.aa())};p.JD=function(c){if(this.SNa())switch(b.bs(c)){case a.W.CTa:case a.W.p$b:case a.W.w$b:case a.W.A0:case a.W.x$b:case a.W.$_c:case a.W.E1c:case a.W.s$b:case a.W.L1c:case a.W.ETa:c.Cl(!0);
return}p.j.JD.call(this)};p.BA=function(a){var b=this.po(),c=this.iq();(b||c)&&this.k8b(a,b,c)};p.k8b=function(a,d,n){var k=new c.fa,h=new c.fa(0,0,1E4,1E4);this.Ix()&&h.Ra(h.O()+a.aa()-(this.ca.pj()+this.ca.Fk()));this.sJb(h,!0);""==this.eb()&&this.d3.qg()||(""==this.eb()?k=this.d3:(k=b.uc(this.sM),k.Ga(k.ua+(0<this.sM.ba()?1:0)),k=k.W1(this.d3)));d&&a.Ra(a.O()+this.ca.pj()+this.AC+k.aa()+this.DC+this.ca.Fk());n&&a.Ga(a.M()+this.ca.Gk()+this.OC+k.ba()+this.tC+this.ca.em())};p.sea=function(a,b,c){p.j.sea(a,
b,c);c[0]&&this.SNa()&&(c[0]=!1)};p.Nf=function(a){b.Cib();return p.j.Nf.call(this,a)};p.En=function(c,d){switch(d.$a){case a.g.wb:case a.g.Tb:d.$i==this.Ka&&this.od(null);break;case a.g.h:d.$i==this.Ka&&(b.gb().Jd(this),this.yd())}};p.k7a=function(b,c){c.$a==a.g.Tb&&this.aC(null)};p.zv=p[a.Z.UH]=function(a){p.j.zv.call(this,a);b.gb().Jd(this,!1)};p.opd=p[a.Z.VAa]=function(){b.gb().Jd(this,!1)};p.QM=p[a.Z.OB]=function(){b.gb().Jd(this,!1)};p.Ska=p[a.Z.eBa]=function(a){this.Sy()?this.Ke(!1):p.j.Ska.call(this,
a)};p.PM=p[a.Z.uK]=function(){this.ml&&this.ml.df()};p.xx=p[a.Z.$y]=function(b){this.xD()&&(this.qq(),this.$Oc(a.Hgb.u5b));p.j.xx.call(this,b)};d.wd(c.St,"PRIM_LABL",{Pa:{Ellipses:{a:function(){return d.sa(this.$e(),a.kp.u)},f:function(b){this.Uf(d.qa(b,a.kp.u))}},Caption:{a:p.eb,f:function(a){this.ub(d.ka(a))}},Alignment:{a:function(){return d.sa(this.hg(),a.fh.u)},f:function(b){this.rb(d.qa(b,a.fh.u))}},VerticalAlignment:{a:function(){return d.sa(this.iW(),a.dh.u)},f:function(b){this.rn(d.qa(b,
a.dh.u))}},FocusControl:{a:p.dF,f:p.aC},WordWrap:{a:p.Sd,f:function(a){this.Se(d.wa(a))}},Selectable:{a:p.SNa,f:function(a){this.Gbc(d.wa(a))}},MarginLeft:{a:p.Qe,f:function(a){this.$d(d.v(a))}},MarginTop:{a:p.He,f:function(a){this.td(d.v(a))}},MarginBottom:{a:p.Zf,f:function(a){this.Be(d.v(a))}},MarginRight:{a:p.Pf,f:function(a){this.Ed(d.v(a))}},Image:{a:p.Oc,f:p.od},ImagePosition:{a:function(){return d.sa(this.Iv(),a.Pk.u)},f:function(b){this.Zs(d.qa(b,a.Pk.u))}},ImageHeight:{a:p.Lt,f:function(a){this.gs(d.v(a))}},
ImageSizing:{a:function(){return d.sa(this.lD(),a.Rd.u)},f:function(b){this.dC(d.qa(b,a.Rd.u))}}},Bg:{wg:"Caption"}});c.Tjb=function(a){u.H.call(this,a);this.qZa=this.tw=this.DHa=this.Xyb=this.Wyb=this.Ka=this.bH=this.tja=this.CE=this.wBb=this.vBb=this.uBb=this.qb=null};var u=c.q(c.Tjb,c.mn);u.eb=function(){return this.qb.textContent};u.ub=function(a){this.qb.textContent=a};u.k5=function(){return this.qb};u.iN=function(){return this.qb};u.nh=function(b,c,n,k,h,f,e){null==this.Ka.parentElement&&this.G.appendChild(this.Ka);
if(null==this.qZa||this.qZa!=f)this.qZa=f,this.qb.spellcheck=!1,this.qb.setAttribute("contenteditable",f);this.Ka.style.backgroundImage=d.yv(n);switch(this.pa.lD()){case a.Rd.FI:this.Ka.style.backgroundSize="contain";break;case a.Rd.KEa:this.Ka.style.backgroundSize="cover";break;case a.Rd.eg:this.Ka.style.backgroundSize="100% 100%";break;case a.Rd.Xd:this.Ka.style.backgroundSize="auto"}if(null==this.bH||this.bH!=h)this.bH=h,this.qb.style.whiteSpace=h?"pre-wrap":"pre";if(null==this.tja||this.tja!=
e)this.tja=e,this.qb.style.textAlign=0!=(e&a.cg.UEa)?"right":0!=(e&a.cg.Jfa)?"center":"",0!=(e&a.cg.REa)||0!=(e&a.cg.TEa)||0!=(e&a.cg.VEa)?(this.qb.style.textOverflow="ellipsis",this.qb.style.overflow="hidden"):(this.qb.style.textOverflow="clip",this.qb.style.overflow="visible");if(null==this.uBb||this.uBb!=c.O())this.uBb=c.O(),this.qb.style.left=c.O()+"px";if(null==this.vBb||this.vBb!=c.M())this.vBb=c.M(),this.qb.style.top=c.M()+"px";if(null==this.CE||this.CE!=c.ba())this.CE=c.ba(),this.qb.style.height=
c.ba()+"px";if(null==this.wBb||this.wBb!=c.aa())this.wBb=c.aa(),this.qb.style.width=c.aa()+"px";if(null==this.Wyb||this.Wyb!=k.O())this.Wyb=k.O(),this.Ka.style.left=k.O()+"px";if(null==this.Xyb||this.Xyb!=k.M())this.Xyb=k.M(),this.Ka.style.top=k.M()+"px";if(null==this.tw||this.tw!=k.ba())this.tw=k.ba(),this.Ka.style.height=k.ba()+"px";if(null==this.DHa||this.DHa!=k.aa())this.DHa=k.aa(),this.Ka.style.width=k.aa()+"px"};u.cf=function(a,b){this.G=document.createElement("div");this.G.setAttribute("LANSAHandle",
this.jc);this.qb=document.createElement("div");var c=this.qb.style;c.position="absolute";c.outline="none";c.overflowX="hidden";c.overflowY="hidden";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";c.borderStyle="solid";c.borderLeftWidth="0px";c.borderTopWidth="0px";c.borderRightWidth="0px";c.borderBottomWidth="0px";c.cursor="inherit";c.textDecoration="inherit";this.Ka=document.createElement("div");c=this.Ka.style;c.position="absolute";c.backgroundSize="contain";
c.backgroundPosition="center center";c.backgroundRepeat="no-repeat";this.G.appendChild(this.qb);this.G.appendChild(this.Ka);return u.j.cf.call(this,a,b)};u.dZ=function(){var a=this;this.c4();a.qb.addEventListener("paste",function(b){a.oea(b);b.preventDefault()},!1)};u.Vub=function(){var a="";u.j.Vub.call(this);"rgba(0,0,0,0)"==this.rYa&&""!=this.G.style.boxShadow&&(a=this.G.style.boxShadow);this.qb.style.textShadow=a};u.dO=function(a){u.j.dO.call(this,a);return!this.qZa};u.oea=function(){}});
