window.LANSA.addSrc("imag",function(d,c,a,b){c.Rt=function(){p.H.call(this);this.ut="";this.fc=this.ib=this.zz=this.wZa=this.HT=this.Oe=this.nf=null;this.jY=a.Rd.LEa;this.tC=this.DC=this.AC=this.OC=0;this.Vc|=a.cc.LAa;this.lia=new c.so;this.lia.Ke(!1);this.lia.Oa(this);this.Oe=new c.xS;this.nf=new c.pb;this.nf.jd(this.Oe);this.lia.mfa(this.nf);this.Ke(!1)};var p=c.q(c.Rt,c.so);p.nb=function(){b.$(this.lia);this.lia=null;b.$(this.Oe);this.Oe=null;b.$(this.nf);this.nf=null;p.j.nb.call(this)};p.R=function(){p.j.R.call(this);
this.tqa(null);this.wZa=null;this.Si(null);this.$o(null)};p.Yg=function(){return this.ut};p.Xs=function(c){b.zA(this.ut,c)||(this.ut=c,this.tqa(b.Goa(this.ut)),this.k(a.g.h))};p.gvd=function(){return this.HT};p.tqa=function(b){this.HT!=b&&(this.Si(null),null!=this.HT&&this.HT.Ba(this,this.jHb),this.HT=b,null!=this.HT&&this.HT.Fa(this,this.jHb),this.uL(),this.ob(),this.k(a.g.h))};p.FZ=function(){return this.zz};p.Si=function(b){this.zz!=b&&(this.tqa(null),null!=this.zz&&(this.zz.Ba(this,this.En),this.zz.Cb()),
this.zz=b,null!=this.zz&&(this.zz.Ha(),this.zz.Fa(this,this.En)),this.uL(),this.ob(),this.yd(),this.k(a.g.h))};p.HR=function(){return this.Oe.vl()};p.uO=function(b){this.Oe.vl()!=b&&(this.Oe.bg(b),this.k(a.g.h))};p.QJ=function(){return this.Oe.Pd()};p.fL=function(b){this.Oe.Pd()!=b&&(this.Oe.Va(b),this.k(a.g.h))};p.SJ=function(){return this.Oe.ie()};p.gL=function(b){this.Oe.ie()!=b&&(this.Oe.Ta(b),this.k(a.g.h))};p.CH=function(){return this.Oe.Qa()};p.OD=function(b){this.Oe.Qa()!=b&&(this.Oe.Wb(b),
this.k(a.g.h))};p.Lt=function(){return this.Oe.Ia()};p.gs=function(b){this.Oe.Ia()!=b&&(this.Oe.lc(b),this.k(a.g.h))};p.lD=function(){return this.jY};p.dC=function(b){this.jY!=b&&(this.jY=b,this.Oe.Bb(b),this.ob(),this.yd(),this.k(a.g.h))};p.RJ=function(){return this.Oe.dW()};p.dG=function(b){this.Oe.dW()!=b&&(this.Oe.O7(b),this.k(a.g.h))};p.TJ=function(){return this.Oe.gj()};p.hL=function(b){this.Oe.gj()!=b&&(this.Oe.rk(b),this.k(a.g.h))};p.oA=function(){return this.Oe.hg()};p.kz=function(b){this.Oe.hg()!=
b&&(this.Oe.rb(b),this.k(a.g.h))};p.Pg=function(b){this.ib!=b&&(this.$o(b),this.k(a.g.h))};p.hb=function(){var a=null;return a=this.ib};p.gc=function(){return this.fc};p.He=function(){return this.OC};p.td=function(c){this.OC!=c&&(this.OC=c,this.ob(),this.yd(),b.gb().Jd(this,!1),this.ea(a.g.h))};p.Qe=function(){return this.AC};p.$d=function(c){this.AC!=c&&(this.AC=c,this.ob(),this.yd(),b.gb().Jd(this,!1),this.ea(a.g.h))};p.Pf=function(){return this.DC};p.Ed=function(c){this.DC!=c&&(this.DC=c,this.ob(),
this.yd(),b.gb().Jd(this,!1),this.ea(a.g.h))};p.Zf=function(){return this.tC};p.Be=function(c){this.tC!=c&&(this.tC=c,this.ob(),this.yd(),b.gb().Jd(this,!1),this.ea(a.g.h))};p.Cm=function(a,b,c,d,k){return k};p.AM=function(){var a=this.fc.Ij();""!=a?this.HT&&this.HT.Yg()==a||this.tqa(b.Goa(a)):this.tqa(this.fc.Wma());this.ib.yV(this.gc())};p.$o=function(a){var c=null;a&&(c=a.Gy(),this.ib==a?c.Xm(this.fc):a.dA(c));this.ib&&(this.ib.Ba(this),this.fc.Ba(this),b.$(this.fc),this.fc=null);if(this.ib=a)this.ib.Fa(this,
this.io),this.fc=c,this.fc.Fa(this,this.Gw);this.Ch()};p.uL=function(){null==this.zz?this.Oe.od(this.HT):this.wZa&&0<this.wZa.Yg().length?this.Oe.od(this.wZa):this.Oe.od(this.zz)};p.gf=function(b){var d=new c.fa(0,0,b.aa(),b.ba());p.j.gf.call(this,b);d.Ta(d.M()+this.OC);d.Va(d.O()+this.AC);d.Ra(d.va-this.DC);d.Ga(d.ua-this.tC);this.lia.tb(this);this.lia.kb(d);this.lD()==a.Rd.LEa&&this.Oe.Oc()&&(this.Oe.Oc().Ia()>d.ba()||this.Oe.Oc().Qa()>d.aa()?this.Oe.Bb(a.Rd.FI):this.Oe.Bb(a.Rd.Xd))};p.BA=function(b){var d=
this.po(),r=this.iq();if(0!=this.SJ()||0!=this.QJ()||100!=this.CH()||100!=this.Lt()||this.RJ()!=a.Jr.d8||this.TJ()!=a.Cw.u8||this.Oe.rh()==a.Rd.KEa)r=d=!1;if(d||r){var n=new c.fa;if(this.Oe.Oc())switch(n.Ra(this.Oe.Oc().Qa()),n.Ga(this.Oe.Oc().Ia()),this.Oe.rh()){case a.Rd.FI:if(r&&!d&&0<b.aa()&&0<n.aa()){var k=b.aa()/n.aa();n.Ga(n.M()+n.ba()*k)}}d&&b.Ra(b.O()+this.ca.pj()+this.AC+n.aa()+this.DC+this.ca.Fk());r&&b.Ga(b.M()+this.ca.Gk()+this.OC+n.ba()+this.tC+this.ca.em())}};p.Nf=function(a){b.Cib();
return p.j.Nf.call(this,a)};p.En=function(b,c){switch(c.$a){case a.g.wb:case a.g.Tb:this.Si(null);break;case a.g.h:this.ob(),this.yd()}};p.jHb=function(b,c){switch(c.$a){case a.g.wb:case a.g.Tb:this.tqa(null);break;case a.g.h:this.ob()}};p.io=function(b,c){c.$a==a.g.h?c.yt==a.Je.Ox?this.ib.dA(this.gc()):this.$o(this.ib):c.$a==a.g.wb&&this.Pg(null)};p.Gw=function(b,c){c.$a==a.g.h&&c.yt==a.Je.Ox&&this.AM()};d.wd(c.Rt,"PRIM_IMAG",{Pa:{FileName:{a:p.Yg,f:function(a){this.Xs(d.ka(a))}},Image:{a:p.FZ,f:function(a){this.Si(a)}},
ImageTile:{a:function(){return d.sa(this.RJ(),a.Jr.u)},f:function(b){this.dG(d.qa(b,a.Jr.u))}},ImageUnits:{a:function(){return d.sa(this.TJ(),a.Cw.u)},f:function(b){this.hL(d.qa(b,a.Cw.u))}},ImageSizing:{a:function(){return d.sa(this.lD(),a.Rd.u)},f:function(b){this.dC(d.qa(b,a.Rd.u))}},ImageOpacity:{a:p.HR,f:function(a){this.uO(d.v(a))}},ImageLeft:{a:p.QJ,f:function(a){this.fL(d.v(a))}},ImageTop:{a:p.SJ,f:function(a){this.gL(d.v(a))}},ImageWidth:{a:p.CH,f:function(a){this.OD(d.v(a))}},ImageHeight:{a:p.Lt,
f:function(a){this.gs(d.v(a))}},ImageAlignment:{a:function(){return d.sa(this.oA(),a.ce.u)},f:function(b){this.kz(d.qa(b,a.ce.u))}},DataClass:{a:p.hb,f:p.Pg},MarginLeft:{a:p.Qe,f:function(a){this.$d(d.v(a))}},MarginTop:{a:p.He,f:function(a){this.td(d.v(a))}},MarginBottom:{a:p.Zf,f:function(a){this.Be(d.v(a))}},MarginRight:{a:p.Pf,f:function(a){this.Ed(d.v(a))}}}})});
