window.LANSA.addSrc("tile",function(d,c,a,b,n){d.Ob("PRIM_UDC");c.Asb=function(){t.L.call(this);this.Mb=b.Hf(10,10,280,120);this.Ij=new c.x$b(this);this.Sj=new c.m$b(this);this.Op(this.Sj);this.FL(!0);this.m1(!0);this.Wya(a.Cp.sz);this.Hg().gBb();var d=new c.EJa,d=new c.y$b(this,d);this.FVa(d)};var t=c.q(c.Asb,c.lwa);t.Q=function(){t.j.Q.call(this);b.fa(this.Sj);this.Sj=null};t.dlb=function(){return this.Sj};t.P2b=function(){return this.pw()};t.$Q=function(){return this.Sj.$Q()};t.GO=function(b){this.Sj.$Q()!=
b&&(this.Sj.GO(b),this.na(a.g.i))};t.dHa=function(){return this.Sj.dHa()};t.G3a=function(b){this.Sj.dHa()!=b&&(this.Sj.G3a(b),this.na(a.g.i))};t.hba=function(){return this.Sj.hba()};t.SBb=function(b){this.Sj.hba()!=b&&(this.Sj.SBb(b),this.na(a.g.i))};t.aHa=function(){return this.Sj.aHa()};t.x3a=function(b){this.Sj.aHa()!=b&&(this.Sj.x3a(b),this.l(a.g.i))};t.E4=function(){return this.Sj.E4()};t.y3a=function(b){this.Sj.E4()!=b&&(this.Sj.y3a(b),this.l(a.g.i))};t.G4=function(){return this.Sj.G4()};t.z3a=
function(b){this.Sj.G4()!=b&&(this.Sj.z3a(b),this.l(a.g.i))};t.Aua=function(){return this.Sj.Aua()};t.q4a=function(b){this.Sj.Aua()!=b&&(this.Sj.q4a(b),this.l(a.g.i))};t.Bua=function(){return this.Sj.Bua()};t.r4a=function(b){this.Sj.Bua()!=b&&(this.Sj.r4a(b),this.l(a.g.i))};t.PHa=function(){return this.Sj.PHa()};t.s4a=function(b){this.Sj.PHa()!=b&&(this.Sj.s4a(b),this.na(a.g.i))};t.QHa=function(){return this.Sj.QHa()};t.t4a=function(b){this.Sj.QHa()!=b&&(this.Sj.t4a(b),this.na(a.g.i))};t.oHa=function(){return this.Sj.oHa()};
t.T3a=function(b){this.Sj.oHa()!=b&&(this.Sj.T3a(b),this.na(a.g.i))};t.lHa=function(){return this.Sj.lHa()};t.O3a=function(b){this.Sj.lHa()!=b&&(this.Sj.O3a(b),this.na(a.g.i))};t.nHa=function(){return this.Sj.nHa()};t.S3a=function(b){this.Sj.nHa()!=b&&(this.Sj.S3a(b),this.na(a.g.i))};t.kHa=function(){return this.Sj.kHa()};t.N3a=function(b){this.Sj.kHa()!=b&&(this.Sj.N3a(b),this.na(a.g.i))};t.t_=function(){return"PRIM_TILE<"+this.ZQ()+">"};t.w2c=function(){return!0};t.D4b=function(){return!0};t.j4=
function(b){0==(this.Lq()&a.kp.Cw)&&this.Ck(!0);if(this.Dv(a.O.SN)&&(this.ld(b),!this.Nd())){var c=d.fc();c.hc("ITEM",b);this.Fa(a.O.SN,c);c.Kc()}};t.k4=function(b){0==(this.Lq()&a.kp.Cw)&&this.Ck(!0);if(this.Dv(a.O.UN)&&(this.ld(b),!this.Nd())){var c=d.fc();c.hc("ITEM",b);this.Fa(a.O.UN,c);c.Kc()}};t.oaa=function(b){0==(this.Lq()&a.kp.Cw)&&this.Ck(!0);if(this.Dv(a.O.TN)&&(this.ld(b),!this.Nd())){var c=d.fc();c.hc("ITEM",b);this.Fa(a.O.TN,c);c.Kc()}};t.WD=function(b,c){this.ld(b);c=b.WD(c);if(!c&&
!this.Nd()){var f=d.fc();f.hc("ITEM",b);f.mg("CONTINUE",!0);this.Fa(a.O.RN,f);c=!f.ah("CONTINUE");f.Kc()}return c};t.Qha=function(b,c){this.ld(b);if(!c&&!this.Nd()){var f=d.fc();f.hc("ITEM",b);f.mg("CONTINUE",!0);this.Fa(a.O.Iba,f);c=!f.ah("CONTINUE");f.Kc()}return c};t.JH=function(b){var c=this.Dv(a.O.iG);c&&this.ld(b);b.JH();c&&!this.Nd()&&(c=d.fc(),c.hc("ITEM",b),this.Fa(a.O.iG,c),c.Kc())};t.GH=function(b){0==(this.Lq()&a.kp.Cw)&&this.Ck(!0);this.ld(b);b.GH();if(!this.Nd()){var c=d.fc();c.hc("ITEM",
b);this.Fa(a.O.sI,c);c.Kc()}};t.IH=function(b){0==(this.Lq()&a.kp.Cw)&&this.Ck(!0);this.ld(b);b.IH();if(!this.Nd()){var c=d.fc();c.hc("ITEM",b);this.Fa(a.O.LR,c);c.Kc()}};t.qV=function(b){0==(this.Lq()&a.kp.Xka)&&this.Ck(!0);this.ld(b);b.qV();if(!this.Nd()){var c=d.fc();c.hc("ITEM",b);this.Fa(a.O.q0,c);c.Kc()}};t.sV=function(b){0==(this.Lq()&a.kp.Xka)&&this.Ck(!0);this.ld(b);b.sV();if(!this.Nd()){var c=d.fc();c.hc("ITEM",b);this.Fa(a.O.r0,c);c.Kc()}};t.ni=function(a){var b=null;return b=this.Ij.Pg(a,
!0,-1,!1)};t.Pg=function(){this.Ij.Pg(this.ZQ(),!0,-1,!0)};t.xh=function(a){return this.Ij.xh(!1,a)?"OK":"NR"};t.ap=function(){return this.Ij.DWa()};t.Jj=function(){this.Ij.Jj()};t.Fm=function(a){this.Ij.Fm(a==n?!0:!1,a)};t.ml=function(){this.Ij.ml()};t.dn=function(a,b,c){return this.Ij.dn(a,b,c)};t.Nq=function(a){this.Jj();for(var b=0;b<a;b++)this.Pg()};t.Wxa=function(a){this.j4(a)};t.Yxa=function(a){this.k4(a)};t.Xxa=function(a){this.oaa(a)};t.Sxa=function(a,b){return this.WD(a,b)};t.Txa=function(a,
b){return this.Qha(a,b)};t.Fla=function(a){this.JH(a)};t.Dla=function(a){this.GH(a)};t.Vxa=function(a){this.IH(a)};t.Uxa=function(a){this.qV(a)};t.pLa=function(a){this.sV(a)};t.x6=function(a){t.j.x6.call(this,a);a.lY.Pf(a.Pca());a.lY.sg(a.wya());a.lY.Jf(a.H2a());a.lY.we(a.rzb())};t.eMa=function(b){null!=b&&null!=b.uc&&(this.u7a(b.uc,a.hA.x8),this.xva(b.uc,a.pI.yba))};t.Me=function(b){""==b[1]&&(b[1]=a.N8b);t.j.Me.call(this,b)};d.Kd(c.Asb,"PRIM_TILE",{uS:a.oy.r7a,jC:"PRIM_CPST",Ba:{CurrentItem:{a:t.kd},
SelectionStyle:{a:function(){return d.wa(this.Bv(),a.Gi.Zsc)},f:function(b){this.PBb(d.va(b,a.Gi.Zsc))}},Direction:{a:function(){return d.wa(this.$Q(),a.ds.G)},f:function(b){this.GO(d.va(b,a.ds.G))}},ItemsPerDivision:{a:t.dHa,f:function(a){this.G3a(d.K(a))}},ShowPartialItem:{a:t.hba,f:function(a){this.SBb(d.Aa(a))}},Spacing:{a:t.PHa,f:function(a){this.s4a(d.K(a))}},SpacingItems:{a:t.QHa,f:function(a){this.t4a(d.K(a))}},FlowOperation:{a:function(){return d.wa(this.aHa(),a.oh.G)},f:function(b){this.x3a(d.va(b,
a.oh.G))}},FlowOperationVer:{a:function(){return d.wa(this.G4(),a.oh.G)},f:function(b){this.z3a(d.va(b,a.oh.G))}},FlowOperationHor:{a:function(){return d.wa(this.E4(),a.oh.G)},f:function(b){this.y3a(d.va(b,a.oh.G))}},SizingRuleVer:{a:function(){return d.wa(this.Bua(),a.dJ.G)},f:function(b){this.r4a(d.va(b,a.dJ.G))}},SizingRuleHor:{a:function(){return d.wa(this.Aua(),a.dJ.G)},f:function(b){this.q4a(d.va(b,a.dJ.G))}},MinRows:{a:t.oHa,f:function(a){this.T3a(d.K(a))}},MaxRows:{a:t.lHa,f:function(a){this.O3a(d.K(a))}},
MinColumns:{a:t.nHa,f:function(a){this.S3a(d.K(a))}},MaxColumns:{a:t.kHa,f:function(a){this.N3a(d.K(a))}},FocusItem:{a:t.bd}},nc:{Add:t.ni,Sort:t.Dda,FindItem:t.Gg,DeleteAll:t.DF,FindReference:t.pV},Oz:{Pg:t.Pg,xh:function(a){return this.xh(d.K(a)-1)},Nq:t.Nq,Jj:t.Jj,ap:t.ap,Fm:function(a){this.Fm(a?d.K(a)-1:n)},ml:t.ml,dn:t.dn,ss:t.ss}});c.y$b=function(a,b){q.L.call(this,a,b)};var q=c.q(c.y$b,c.GJa);q.Q=function(){q.j.Q.call(this)};q.NXd=function(){return this.Hs.Ea()};q.RZ=function(a,b){var c=null,
f=null,g=null,k=null;null!=a&&(f=k=d.Bc(a),null!=f&&(f.zb(!1),g=f,null!=g&&(c=d.Bc("PRIM_TILE","TileItem"),c.za())));b[0]=k;b[1]=c;b[2]=f;b[3]=g};q.HM=function(a,b,c,d){this.RZ(a,b);null!=b[1]&&this.Cy(b[1],b[2],d)};q.hya=function(a){return a};c.x$b=function(a){r.L.call(this,a)};var r=c.q(c.x$b,c.FJa);r.Pg=function(b,c,d,f){var g=this.Ea(),k=null,k=null,k=[];c?g.P2b().HM(b,k,-1,f):g.P2b().HM(b,k,d,f);k=k[1];g.TU(!0);g.pd(a.Ab.kf);return k};c.w$b=function(){p.L.call(this);this.yLb=a.O8b};var p=c.q(c.w$b,
c.nwa);p.Q=function(){p.j.Q.call(this)};p.Na=function(a){this.U()!=a&&this.kg()&&(null==a||a.kg()&&a.Ea()==this.Ea())&&this!=a&&(a=null!=a?a:null,this.U()!=a&&this.i7a(a,-1))};p.WD=function(c){if(!this.Nd()){var f=d.fc();f.hc("ITEM",this);f.mg("CONTINUE",!0);this.Fa(a.O.RN,f);c=!f.ah("CONTINUE");f.Kc()}f=this.It();null!=f&&b.gn(f,this,"ONITEMCLICK");return c};p.JH=function(){if(!this.Nd()){var c=d.fc();c.hc("ITEM",this);this.Fa(a.O.iG,c);c.Kc()}c=this.It();null!=c&&b.gn(c,this,"ONITEMREALIZING")};
p.GH=function(){if(!this.Nd()){var c=d.fc();c.hc("ITEM",this);this.Fa(a.O.sI,c);c.Kc()}c=this.It();null!=c&&(b.gn(c,this,"ONITEMGOTFOCUS"),null!=this.uc&&this.uc.ga.Zya(!0))};p.IH=function(){if(!this.Nd()){var c=d.fc();c.hc("ITEM",this);this.Fa(a.O.LR,c);c.Kc()}c=this.It();null!=c&&(b.gn(c,this,"ONITEMLOSTFOCUS"),null!=this.uc&&this.uc.ga.Zya(!1))};p.qV=function(){if(!this.Nd()){var c=d.fc();c.hc("ITEM",this);this.Fa(a.O.q0,c);c.Kc()}c=this.It();null!=c&&(b.gn(c,this,"ONITEMGOTSELECTION"),null!=this.uc&&
this.uc.ga.Xt(!0))};p.sV=function(){if(!this.Nd()){var c=d.fc();c.hc("ITEM",this);this.Fa(a.O.r0,c);c.Kc()}c=this.It();null!=c&&(b.gn(c,this,"ONITEMLOSTSELECTION"),null!=this.uc&&this.uc.ga.Xt(!1))};d.Ta(c.w$b,"PRIM_TILE","TileItem",{Ba:{Design:{a:p.HWa},Tile:{a:p.Ea},Focus:{a:p.jg,f:p.Of},Selected:{a:p.xk,f:function(a){this.Xt(d.Aa(a))}},Expanded:{a:p.mj,f:function(a){this.zL(d.Aa(a))}},Position:{a:p.ija},Entry:{a:p.xh},Visible:{a:p.yb,f:function(a){this.zb(d.Aa(a))}},RelatedReference:{a:p.V4,f:p.jX},
MarginTop:{a:p.Tf,f:function(a){this.Pf(d.K(a))}},MarginBottom:{a:p.bh,f:function(a){this.sg(d.K(a))}},MarginLeft:{a:p.Yf,f:function(a){this.Jf(d.K(a))}},MarginRight:{a:p.Xg,f:function(a){this.we(d.K(a))}},Style:{a:p.yh,f:p.Ib},ParentItem:{a:p.U,f:p.Na},MouseOverStyle:{a:p.ep,f:p.np},SelectedStyle:{a:p.DC,f:p.EL},FocusedStyle:{a:p.MA,f:p.xG},SelectedInactiveStyle:{a:p.UF,f:p.PS},FocusedInactiveStyle:{a:p.NF,f:p.BS},Styles:{a:p.Pl},MouseOverStyles:{a:p.xy},SelectedStyles:{a:p.G_},FocusedStyles:{a:p.Kaa},
SelectedInactiveStyles:{a:p.fba},FocusedInactiveStyles:{a:p.Iaa},ItemCount:{a:p.Jc},Items:{a:p.wy},ParentItems:{a:p.Mlb}},nc:{Add:p.ni,Expand:p.f_,Delete:p.Is,Collapse:p.faa,DeleteAll:p.DF}});c.v$b=function(){k.L.call(this)};var k=c.q(c.v$b,c.Asb);k.kxa=function(a){a.fjc(this.U())};k.Ska=function(a){a.f6(this.U());k.j.Ska.call(this,a)};c.u$b=function(){g.L.call(this);this.Mb=b.Hf(10,10,280,400);this.Bm=null;this.AAc=!1;this.pc=this.Bm=new c.v$b;this.Bm.za();this.Bm.Hb(this);this.Bm.udcDesign="PRIM_TILE_DESIGN";
this.Bm.Ne(!1);this.Bm.ya(this,a.O.vh,this.MNc);this.Bm.ya(this,a.O.ZW,this.XNc);this.Bm.ya(this,a.O.SN,this.TNc);this.Bm.ya(this,a.O.UN,this.VNc);this.Bm.ya(this,a.O.TN,this.UNc);this.Bm.ya(this,a.O.RN,this.NNc);this.Bm.ya(this,a.O.Iba,this.ONc);this.Bm.ya(this,a.O.iG,this.WNc);this.Bm.ya(this,a.O.sI,this.PNc);this.Bm.ya(this,a.O.LR,this.RNc);this.Bm.ya(this,a.O.q0,this.QNc);this.Bm.ya(this,a.O.r0,this.SNc)};var g=c.q(c.u$b,c.lE);g.Q=function(){g.j.Q.call(this)};g.kd=function(){return this.Bm.kd()};
g.bd=function(){return this.Bm.bd()};g.wy=function(){return this.Bm.wy()};b.X2d=function(a){var b=null;a&&a.uc&&a.uc instanceof c.Bsb&&(b=a.uc);return b};g.KEa=function(a){a.rb(new c.pa(a.te(),a.Qe(),this.qPa,this.kv))};g.Cx=function(a,b){g.j.Cx.call(this,a,b);this.AAc!=this.Bm.Jja()&&(this.AAc=this.Bm.Jja(),this.wb())};g.hf=function(a){g.j.hf.call(this,a)};g.ss=function(){return this.Bm.ss()};g.Pg=function(){var a=this.Bm.Pg();this.KEa(a.uc)};g.xh=function(a){return this.Bm.xh(a)};g.ap=function(){return this.Bm.ap()};
g.Jj=function(){this.Bm.Jj()};g.Fm=function(a){this.Bm.Fm(a)};g.ml=function(){this.Bm.ml()};g.dn=function(a,b,d){var f=this.Bm;if(f)for(var g=0;g<f.yq.length;g++){var k=f.rI(g);if(k&&(k=k.uc)){for(var p={},n=null,q=this.zs,r=0;r<q.length&&null!=(n=q[r]);r++){var t=null,J=null,ba=null,U=null;n instanceof c.fca?t=n:n instanceof c.dca?J=n:n instanceof c.hca||n instanceof c.cca||n instanceof c.eca||n instanceof c.gca||(n instanceof c.bca?ba=n:n instanceof c.ica&&(U=n));if(J||t||ba||U)J=k.Ec[n],t=n.Ue,
J&&(J=J.zc.lc().jb(),t&&(t=t.lw())&&(p[t.Fh()]=J))}if(a(p))return a=f.sya(),null!=b&&b.set(g+1),a&&(d&&a.xh(!1,g),a.tq=f.rI(g)),"OK"}}return"NR"};g.Nq=function(a){this.Bm.Nq(a)};g.MNc=function(b,c){this.Fa(a.O.vh,c)};g.XNc=function(b,c){this.Fa(a.O.ZW,c)};g.TNc=function(b,c){this.Fa(a.O.SN,c)};g.VNc=function(b,c){this.Fa(a.O.UN,c)};g.UNc=function(b,c){this.Fa(a.O.TN,c)};g.NNc=function(b,c){this.Fa(a.O.RN,c)};g.ONc=function(b,c){this.Fa(a.O.Iba,c)};g.WNc=function(b,c){this.Fa(a.O.iG,c)};g.PNc=function(b,
c){this.Fa(a.O.sI,c)};g.RNc=function(b,c){this.Fa(a.O.LR,c)};g.QNc=function(b,c){this.Fa(a.O.q0,c)};g.SNc=function(b,c){this.Fa(a.O.r0,c)};d.Ta(c.u$b,"PRIM_MD","Tile",{jC:"PRIM_CPST",Ba:{CurrentItem:{a:g.kd},FocusItem:{a:g.bd},Items:{a:g.wy},RowHeight:{a:g.dba,f:function(a){this.PO(d.K(a))}},ColWidth:{a:g.LTc,f:function(a){this.Imd(d.K(a))}},LogicalHeight:{a:function(){return this.Bm.f1b()}},LogicalWidth:{a:function(){return this.Bm.Dlb()}},ViewportHeight:{a:function(){return this.Bm.c3b()}},ViewportWidth:{a:function(){return this.Bm.d3b()}},
VerticalScrollPos:{a:function(){return this.Bm.Cm},f:function(a){this.Bm.CG(d.K(a))}},HorizontalScrollPos:{a:function(){return this.Bm.Vm},f:function(a){this.Bm.vMa(d.K(a))}}},nc:{DeleteAll:g.DF,FindReference:g.pV},Oz:{Pg:g.Pg,xh:function(a){return this.xh(d.K(a)-1)},Nq:g.Nq,Jj:g.Jj,ap:g.ap,Fm:function(a){this.Fm(a?d.K(a)-1:n)},ml:g.ml,dn:g.dn,ss:g.ss}});c.Bsb=function(){f.L.call(this);this.uBb();this.Pb(a.Rrb)};var f=c.q(c.Bsb,c.mwa);f.Q=function(){f.j.Q.call(this)};f.OXd=function(){return this.$B};
f.OEa=function(a){f.j.OEa.call(this,a)};f.Me=function(a){""==a[0]&&(a[0]="");f.j.Me.call(this,a)};d.Kd(c.Bsb,"PRIM_TILE_DESIGN",{Ba:{},nc:{}})},{rp:["PRIM_UDC"]});
