window.LANSA.addSrc("web",function(d,c,a,b,n){d.Ob("PRIM_LABL");var t=localStorage,q=sessionStorage;a.xO={Dzb:0,aoc:1,boc:2,$nc:3};a.xO.G={INLINE:a.xO.Dzb,LEFT:a.xO.aoc,RIGHT:a.xO.boc,CENTER:a.xO.$nc};a.zI={zVa:0,VXb:1,ZXb:2,$Xb:3,bYb:4,vib:5};a.zI.G={NONE:a.zI.zVa,NOTLOADED:a.zI.VXb,PERMISSIONDENIED:a.zI.ZXb,POSITIONUNAVAILABLE:a.zI.$Xb,TIMEOUT:a.zI.bYb,UNKNOWNERROR:a.zI.vib};a.PZ={VQb:0,TQb:1,WQb:2,UQb:4};a.PZ.G={NONE:a.PZ.VQb,ERROR:a.PZ.TQb,WARNING:a.PZ.WQb,INFORMATION:a.PZ.UQb};c.$ub=function(){r.L.call(this);
this.kb=[]};var r=c.q(c.$ub,c.Ad);r.Q=function(){r.j.Q.call(this)};r.Jc=function(){return this.kb.length};r.se=function(a){return this.kb[a-1]};r.WH=function(a){for(var c=null,d=0;d<this.kb.length;d++){var e=this.kb[d];if(b.Qz(e.Yp,a)){c=e;break}}return c};d.Ta(c.$ub,"PRIM_WEB","URLParameters",{Ba:{Item:{a:function(a){return this.WH(d.ja(a))},rz:"na"},ItemCount:{a:r.Jc}},cf:{af:"Item"},ls:{Jr:function(a){return this.se(d.K(a))},Ey:r.Jc}});b.oad=function(a,b,d){a.kb.push(new c.p0a(b,d))};b.nad=function(a,
d){b.zl().U2b().kb.unshift(new c.p0a(a,d))};c.p0a=function(a,b){p.L.call(this);this.Yp=a;this.hb=b};var p=c.q(c.p0a,c.Ad);p.Fh=function(){return this.Yp.toUpperCase()};p.jb=function(){return this.hb};d.Ta(c.p0a,"PRIM_WEB","URLParameter",{Ba:{Name:{a:p.Fh},Value:{a:p.jb}}});c.Yub=function(){k.L.call(this);this.yq=null;this.L8=n};var k=c.q(c.Yub,c.Ad);k.Q=function(){k.j.Q.call(this)};k.mta=function(){if(this.L8===n&&(this.L8=!1,t))try{var a,c=b.zl().p2b();t.setItem(c,c);a=t.getItem(c)==c;t.removeItem(c);
a&&(this.L8=!0)}catch(d){}return this.L8};k.Jc=function(){return this.JV().length};k.se=function(a){return this.JV()[a-1]};k.WH=function(a){for(var b=null,c=this.JV(),d=0;d<c.length;d++){var e=c[d];if(e.Yp==a){b=e;break}}return b};k.JV=function(){if(null==this.yq&&(this.yq=[],t))for(var a=0;a<t.length;a++){var b=t.key(a);""!=b&&t[b]!=n&&this.yq.push(new c.n0a(b))}return this.yq};k.OLa=function(){this.yq=null};k.ni=function(a,b){var d=this.JV(),e=this.WH(a);null==e&&(e=new c.n0a(a),d.push(e));e.nb(b)||
d.splice(d.indexOf(e),1)};k.Hu=function(c){var d=this.JV(),e=this.WH(c);null!=e&&(t.removeItem(c),d.splice(d.indexOf(e),1),b.zl().Uha(a.eJ.wza))};k.Ll=function(){t&&(t.clear(),this.OLa(),b.zl().Uha(a.eJ.wza))};d.Ta(c.Yub,"PRIM_WEB","LocalStorage",{Ba:{Available:{a:k.mta},Item:{a:function(a){return this.WH(d.ja(a))},rz:"na"},ItemCount:{a:k.Jc}},nc:{Add:k.ni,Remove:k.Hu,Clear:k.Ll},cf:{af:"Item"},ls:{Jr:function(a){return this.se(d.K(a))},Ey:k.Jc}});c.n0a=function(a){g.L.call(this);this.Yp=a};var g=
c.q(c.n0a,c.Ad);g.Fh=function(){return this.Yp};g.jb=function(){var a="";t&&(a=t[this.Yp],a===n&&(a=""));return a};g.nb=function(c){var d=!0;try{t[this.Yp]=c,b.zl().Uha(a.eJ.wza)}catch(e){b.zl().JZb(a.eJ.wza),d=!1}return d};d.Ta(c.n0a,"PRIM_WEB","LocalStorageItem",{Ba:{Name:{a:g.Fh},Value:{a:g.jb,f:function(a){this.nb(d.ja(a))}}},cf:{af:"Value"}});c.Zub=function(){f.L.call(this);this.yq=null;this.L8=n};var f=c.q(c.Zub,c.Ad);f.Q=function(){f.j.Q.call(this)};f.mta=function(){if(this.L8===n&&(this.L8=
!1,q))try{var a,c=b.zl().p2b();q.setItem(c,c);a=q.getItem(c)==c;q.removeItem(c);a&&(this.L8=!0)}catch(d){}return this.L8};f.Jc=function(){return this.JV().length};f.se=function(a){return this.JV()[a-1]};f.WH=function(a){for(var b=null,c=this.JV(),d=0;d<c.length;d++){var e=c[d];if(e.Yp==a){b=e;break}}return b};f.JV=function(){if(null==this.yq&&(this.yq=[],q))for(var a=0;a<q.length;a++){var b=q.key(a);""!=b&&q[b]!=n&&this.yq.push(new c.o0a(b))}return this.yq};f.OLa=function(){this.yq=null};f.ni=function(a,
b){var d=this.JV(),e=this.WH(a);null==e&&(e=new c.o0a(a),d.push(e));return e.nb(b)?!0:(d.splice(d.indexOf(e),1),!1)};f.Hu=function(c){var d=this.JV(),e=this.WH(c);null!=e&&(q.removeItem(c),d.splice(d.indexOf(e),1),b.zl().Uha(a.eJ.xza))};f.Ll=function(){q&&(q.clear(),this.OLa(),b.zl().Uha(a.eJ.xza))};d.Ta(c.Zub,"PRIM_WEB","SessionStorage",{Ba:{Available:{a:f.mta},Item:{a:function(a){return this.WH(d.ja(a))},rz:"na"},ItemCount:{a:f.Jc}},nc:{Add:f.ni,Remove:f.Hu,Clear:f.Ll},cf:{af:"Item"},ls:{Jr:function(a){return this.se(d.K(a))},
Ey:f.Jc}});c.o0a=function(a){e.L.call(this);this.Yp=a};var e=c.q(c.o0a,c.Ad);e.Fh=function(){return this.Yp};e.jb=function(){var a="";q&&(a=q[this.Yp],a===n&&(a=""));return a};e.nb=function(c){var d=!0;try{q[this.Yp]=c,b.zl().Uha(a.eJ.xza)}catch(e){b.zl().JZb(a.eJ.xza),d=!1}return d};d.Ta(c.o0a,"PRIM_WEB","SessionStorageItem",{Ba:{Name:{a:e.Fh},Value:{a:e.jb,f:function(a){this.nb(d.ja(a))}}},cf:{af:"Value"}});c.Xub=function(){x.L.call(this)};var x=c.q(c.Xub,c.Ad);x.Q=function(){x.j.Q.call(this)};
x.E0c=function(a){0<a&&window.history.go(0-a)};x.F0c=function(a){0<a&&window.history.go(a)};x.ni=function(a,c){var d=window.location.protocol+"//"+window.location.host+window.location.pathname;0<a.length&&(d+="?"+a);window.history.pushState(null,"",d);b.zl().izb();c&&b.zl().SVa()};x.Vyb=function(a,c){var d=window.location.protocol+"//"+window.location.host+window.location.pathname;0<a.length&&(d+="?"+a);window.history.replaceState(null,"",d);b.zl().izb();c&&b.zl().SVa()};d.Ta(c.Xub,"PRIM_WEB","History",
{nc:{Add:function(a,b){this.ni(d.ja(a),b===n?!0:d.Aa(b))},Replace:function(a,b){this.Vyb(d.ja(a),b===n?!0:d.Aa(b))},GoBack:function(a){this.E0c(a===n?1:d.K(a))},GoForward:function(a){this.F0c(a===n?1:d.K(a))}}});c.wgc=function(){C.L.call(this);this.Mb=b.Hf(0,0,400,400);this.f9=this.Ue="";this.Rc&=~a.Vd.MR;this.Rc&=~a.Vd.s0};var C=c.q(c.wgc,c.Ql);C.ze=function(){return c.ihc};C.RA=function(){return this.Ue};C.ll=function(b){this.Ue!=b&&(this.Ue=b,this.na(a.g.i))};C.uC=function(){return this.f9};C.kma=
function(a){this.f9=a};C.Hc=function(a,c,d){C.j.Hc.call(this,a,c,d);a=this.Ra().Za();b.ke[a].ll(this.Ue)};C.tRc=function(){this.Fa(a.O.z9b)};d.Ta(c.wgc,"PRIM_WEB","Page",{Ba:{Source:{a:C.RA,f:function(a){this.ll(d.ja(a))}},Description:{a:C.uC,f:function(a){this.kma(d.ja(a))}}}});c.bxa=function(){m.L.call(this)};var m=c.q(c.bxa,c.Ql);m.jmb=function(){for(var a=null,b=this;b;){if(b instanceof c.evb){a=b;break}b=b.cc}return a};m.w6=function(){m.j.w6.call(this);var a=this.jmb();a&&a.j4(this)};m.PW=function(){m.j.PW.call(this);
var a=this.jmb();a&&a.k4(this)};m.of=function(a){m.j.of.call(this,a);var b=this.jmb();b==this&&b.WD(a,!1)};d.Ta(c.bxa,"PRIM_WEB","RichTextItem",{});c.ivb=function(){s.L.call(this)};var s=c.q(c.ivb,c.bxa);s.ze=function(){return c.ric};d.Ta(c.ivb,"PRIM_WEB","RichTextLine",{});c.fvb=function(){D.L.call(this)};var D=c.q(c.fvb,c.bxa);D.ze=function(){return c.pic};d.Ta(c.fvb,"PRIM_WEB","RichTextBreak",{});c.gvb=function(){B.L.call(this);this.T2=null;this.LRa=a.xO.Dzb;this.nbb=this.obb=0};var B=c.q(c.gvb,
c.bxa);B.Q=function(){B.j.Q.call(this);this.i4a(null)};B.ze=function(){return c.qic};B.sZc=function(){return this.T2};B.i4a=function(b){this.T2!=b&&(null!=this.T2&&(this.T2.Ga(this,this.qVb),this.T2.ub()),this.T2=b,null!=this.T2&&(this.T2.za(),this.T2.Ha(this,this.qVb)),this.na(a.g.i))};B.nWd=function(){return this.LRa};B.sqc=function(b){this.LRa!=b&&(this.LRa=b,this.na(a.g.i))};B.tZc=function(){return this.obb};B.uqc=function(b){this.obb!=b&&(this.obb=b,this.na(a.g.i))};B.rZc=function(){return this.nbb};
B.tqc=function(b){this.nbb!=b&&(this.nbb=b,this.na(a.g.i))};B.Hc=function(a,c,d){B.j.Hc.call(this,a,c,d);a=this.Ra().Za();b.ke[a].Zh(this.LRa,this.obb,this.nbb)};B.Uyb=function(){var a=this.T2,c=this.Ra().Za(),a=a?a.Ug():"";b.ke[c].yd(a)};B.qVb=function(b,c){switch(c.bb){case a.g.Bb:case a.g.Ub:this.i4a(null);break;case a.g.i:this.na(a.g.i)}};d.Ta(c.gvb,"PRIM_WEB","RichTextImage",{Ba:{Image:{a:B.sZc,f:function(a){this.i4a(a)}},Width:{a:B.tZc,f:function(a){this.uqc(d.K(a))}},Height:{a:B.rZc,f:function(a){this.tqc(d.K(a))}},
Alignment:{a:function(){return d.wa(this.LRa,a.xO.G)},f:function(b){this.sqc(d.va(b,a.xO.G))}}}});c.q0a=function(){y.L.call(this);this.oA=null};var y=c.q(c.q0a,c.bxa);y.ze=function(){return c.sic};y.wy=function(){null==this.oA&&(this.oA=new c.hvb(this));return this.oA};d.Ta(c.q0a,"PRIM_WEB","RichTextParagraph",{Ba:{Items:{a:y.wy}}});c.evb=function(){K.L.call(this);this.Mb=b.Hf(0,0,100,100)};var K=c.q(c.evb,c.q0a);K.ze=function(){return c.oic};K.j4=function(b){if(!this.Nd()){var c=d.fc();c.hc("ITEM",
b);this.Fa(a.O.SN,c);c.Kc()}};K.k4=function(b){if(!this.Nd()){var c=d.fc();c.hc("ITEM",b);this.Fa(a.O.UN,c);c.Kc()}};K.oaa=function(b){if(!this.Nd()){var c=d.fc();c.hc("ITEM",b);this.Fa(a.O.TN,c);c.Kc()}};K.WD=function(b,c){if(!c&&!this.Nd()){var e=d.fc();e.hc("ITEM",b);e.mg("CONTINUE",!0);this.Fa(a.O.RN,e);c=!e.ah("CONTINUE");e.Kc()}return c};d.Ta(c.evb,"PRIM_WEB","RichText",{});c.hvb=function(a){H.L.call(this);this.kb=[];this.HD=a};var H=c.q(c.hvb,c.Ad);H.Q=function(){H.j.Q.call(this)};H.Jc=function(){return this.kb.length};
H.se=function(a){return this.kb[a-1]};H.ni=function(b,d,e,f){var m=new c.ivb;m.za();m.sb(b);d!=n&&m.Ib(d);e!=n&&m.np(e);f!=n&&m.ar(f);m.Na(this.HD);this.kb[this.kb.length]=m;this.HD.na(a.g.i);this.HD.Wb()&&this.HD.fh();return m};H.IBc=function(){var b=new c.fvb;b.za();b.Na(this.HD);this.kb[this.kb.length]=b;this.HD.na(a.g.i);this.HD.Wb()&&this.HD.fh();return b};H.RBc=function(b,d,e,f,m,g,k){var p=new c.gvb;p.za();p.i4a(b);d!=n&&p.sqc(d);e!=n&&p.uqc(e);f!=n&&p.tqc(f);m!=n&&p.Ib(m);g!=n&&p.np(g);k!=
n&&p.ar(k);p.Na(this.HD);this.kb[this.kb.length]=p;this.HD.na(a.g.i);this.HD.Wb()&&this.HD.fh();return p};H.WBc=function(b,d,e,f){var m=new c.q0a;m.za();b!=n&&m.sb(b);d!=n&&m.Ib(d);e!=n&&m.np(e);f!=n&&m.ar(f);m.Na(this.HD);this.kb[this.kb.length]=m;this.HD.na(a.g.i);this.HD.Wb()&&this.HD.fh();return m};H.Hu=function(b){this.kb.splice(this.kb.indexOf(b),1);b.Na(null);b.ub();this.HD.na(a.g.i)};H.Al=function(){for(;0<this.kb.length;)this.Hu(this.kb[0]);this.HD.na(a.g.i)};d.Ta(c.hvb,"PRIM_WEB","RichTextItems",
{Ba:{Item:{a:function(a){return this.se(d.K(a))},rz:"na"},ItemCount:{a:H.Jc}},nc:{Add:H.ni,AddBreak:H.IBc,AddImage:function(b,c,e,f,m,g,k){return this.RBc(b,d.va(c,a.xO.G),e,f,m,g,k)},AddParagraph:H.WBc,Remove:H.Hu,RemoveAll:H.Al},cf:{af:"Item"},ls:{Jr:function(a){return this.se(d.K(a))},Ey:H.Jc}});c.Egc=function(){E.L.call(this);this.Mb=b.Hf(0,0,100,100)};var E=c.q(c.Egc,c.Ql);E.ze=function(){return c.Chc};E.Hc=function(a,b,c){E.j.Hc.call(this,a,b,c)};E.fg=function(a){this.uG();a&&this.lLa();b.pb().yF(this)};
E.sG=function(){this.ga.t3()};d.Ta(c.Egc,"PRIM_WEB","Camera",{});c.dhc=function(){J.L.call(this);this.Mb=b.Hf(0,0,100,100);this.mJ=null;this.XTa("")};var J=c.q(c.dhc,c.Ql);J.Q=function(){this.mJ=null;J.j.Q.call(this)};J.ze=function(){return c.tic};J.DGa=function(){this.Ra()&&this.XTa(this.Ra().QSc());return this.mJ};J.XTa=function(a){this.mJ=new c.AI({data:a,mimetype:"image/png",filename:"signature.png"})};J.Ll=function(){if(this.Ra()){var a=this.Ra().Za();b.ke[a].Ll();this.Ce()}};J.Hc=function(a,
b,c){J.j.Hc.call(this,a,b,c)};J.fg=function(a){this.uG();a&&this.lLa();b.pb().yF(this)};J.sG=function(){this.ga.t3()};J.Ce=function(){this.Fa(a.O.vh)};d.Ta(c.dhc,"PRIM_WEB","Signature",{Ba:{Blob:{a:J.DGa}},nc:{Clear:J.Ll}});c.Qgc=function(){ba.L.call(this);this.hNb=this.iLb=this.uIb=this.tIb=this.oIb=this.lab=this.SLb=0;this.lfa=a.zI.VXb};var ba=c.q(c.Qgc,c.Ad);ba.LXc=function(){return this.SLb};ba.YWc=function(){return this.lab};ba.hSc=function(){return this.oIb};ba.vSc=function(){return this.tIb};
ba.wSc=function(){return this.uIb};ba.lWc=function(){return this.iLb};ba.c_c=function(){return this.hNb};ba.xSd=function(){return this.lfa};ba.Jfd=function(){var b=this;navigator.geolocation&&navigator.geolocation.getCurrentPosition(function(d){b.SLb=d.coords.longitude;b.lab=d.coords.latitude;b.oIb=d.coords.accuracy;b.tIb=d.coords.altitude?d.coords.altitude:0;b.uIb=d.coords.altitudeAccuracy?d.coords.altitudeAccuracy:0;b.iLb=d.coords.heading?d.coords.heading:0;b.hNb=d.coords.speed?d.coords.speed:0;
b.lfa=a.zI.zVa;b.Fa(a.O.Lmc,new c.zwa)},function(d){b.SLb=0;b.lab=0;b.oIb=0;b.tIb=0;b.uIb=0;b.iLb=0;b.hNb=0;b.lfa=a.zI.vib;switch(d.code){case d.PERMISSION_DENIED:b.lfa=a.zI.ZXb;break;case d.POSITION_UNAVAILABLE:b.lfa=a.zI.$Xb;break;case d.TIMEOUT:b.lfa=a.zI.bYb;break;case d.UNKNOWN_ERROR:b.lfa=a.zI.vib}b.Fa(a.O.Lmc,new c.zwa)});return this.lab};d.Ta(c.Qgc,"PRIM_WEB","Geolocation",{Ba:{Longitude:{a:ba.LXc},Latitude:{a:ba.YWc},Accuracy:{a:ba.hSc},Altitude:{a:ba.vSc},AltitudeAccuracy:{a:ba.wSc},Heading:{a:ba.lWc},
Speed:{a:ba.c_c},ErrorCode:{a:function(){return d.wa(this.lfa,a.zI.G)}}},nc:{Refresh:ba.Jfd}});c.Mgc=function(){U.L.call(this)};var U=c.q(c.Mgc,c.Ad);U.g$c=function(b,c){if("undefined"!==typeof console)switch(c){case a.PZ.TQb:console.error(b);break;case a.PZ.WQb:console.warn(b);break;case a.PZ.UQb:console.info(b);break;default:console.log(b)}};d.Ta(c.Mgc,"PRIM_WEB","Console",{Ba:{},nc:{Log:function(b,c){return this.g$c(d.ja(b),c?d.va(c,a.PZ.G):a.PZ.VQb)}}});c.Pgc=function(){w.L.call(this);this.vc=
this.ob=null;this.gM=this.jr="";this.jqa=!1};var w=c.q(c.Pgc,c.zw);w.Q=function(){w.j.Q.call(this);this.pq(null)};w.ze=function(){return c.Lhc};w.Ug=function(){return this.jr};w.Zkb=function(){return this.gM};w.Bh=function(b){this.ob!=b&&(this.pq(b),this.l(a.g.i))};w.qb=function(){var a=null;return a=this.ob};w.lc=function(){return this.vc};w.bja=function(){return this.jqa};w.U3a=function(b){this.jqa!=b&&(this.jqa=b,this.na(a.g.i))};w.Ce=function(){this.Fa(a.O.vh)};w.Zsa=function(b,c){var e=d.fc();
e.hc("FILE",b);e.hc("FILES",c);this.Fa(a.O.ajb,e);e.Kc()};w.tQ=function(){this.bY=b.Uwa(this.vc.ek());this.ob.d_(this.lc())};w.pq=function(a){var c=null;a&&(c=a.qz(),this.ob==a?c.Bn(this.vc):a.mC(c));this.ob&&(this.ob.Ga(this),this.vc.Ga(this),b.fa(this.vc),this.vc=null);if(this.ob=a)this.ob.Ha(this,this.Dp),this.vc=c,this.vc.Ha(this,this.qy);this.Vh()};w.qBd=function(){};w.Dp=function(b,c){c.bb==a.g.i?c.ku==a.Ie.Mz?this.ob.mC(this.lc()):this.pq(this.ob):c.bb==a.g.Bb&&this.Bh(null)};w.qy=function(b,
c){c.bb==a.g.i&&c.ku==a.Ie.Mz&&this.tQ()};d.Ta(c.Pgc,"PRIM_WEB","FilePicker",{Ba:{MultiSelect:{a:w.bja,f:function(a){this.U3a(d.Aa(a))}}}});c.xKa=function(a){V.L.call(this);this.gab=a;this.XT=this.mJ=null};var V=c.q(c.xKa,c.Ad);V.Q=function(){null!=this.mJ&&(this.mJ=null);null!=this.XT&&(b.MSb(this.XT),this.XT=null);V.j.Q.call(this)};V.Fh=function(){return this.gab.name};V.DGa=function(){null==this.mJ&&(this.mJ=new c.bcc(this.gab));return this.mJ};V.vmb=function(){return this.gab.size};V.aYc=function(){return this.gab.type};
d.Ta(c.xKa,"PRIM_WEB","File",{Ba:{Name:{a:V.Fh},Blob:{a:V.DGa},FileSize:{a:V.vmb},MimeType:{a:V.aYc}}});c.Wub=function(){z.L.call(this);this.kb=[]};var z=c.q(c.Wub,c.Ad);z.Q=function(){for(var a=0;a<this.kb.length;a++)this.kb[a].ub();this.kb=[];z.j.Q.call(this)};z.Jc=function(){return this.kb.length};z.se=function(a){return this.kb[a-1]};z.hs=function(a){this.kb.push(a);a.za()};d.Ta(c.Wub,"PRIM_WEB","Files",{Ba:{Item:{a:function(a){return this.se(d.K(a))},rz:"na"},ItemCount:{a:z.Jc}},cf:{af:"Item"},
ls:{Jr:function(a){return this.se(d.K(a))},Ey:z.Jc}});c.Lgc=function(){ea.L.call(this)};var ea=c.q(c.Lgc,c.Ad);ea.Hyb=function(a){var d=this;if(window.FileReader&&a instanceof c.AI){if(a=a.Rta()){var e=b.rX(),f=new FileReader;f.onload=function(a){d.f4(a.target.result);b.mB(e)};f.readAsText(a)}}else d.f4("")};ea.f4=function(b){var c=d.fc();c.JD("DATA",b);this.Fa(a.O.K$,c)};d.Ta(c.Lgc,"PRIM_WEB","ClobReader",{nc:{Read:ea.Hyb}});c.zgc=function(){ca.L.call(this)};var ca=c.q(c.zgc,c.Ad);ca.Hyb=function(a){var d=
this;if(window.FileReader&&a instanceof c.AI){if(a=a.Rta()){var e=b.rX(),f=new FileReader;f.onload=function(a){d.f4(b.WYb(a.target.result));b.mB(e)};f.readAsDataURL(a)}}else d.f4("","")};ca.f4=function(b){var c=d.fc();c.JD("DATA",b);this.Fa(a.O.K$,c)};d.Ta(c.zgc,"PRIM_WEB","BlobReader",{nc:{Read:ca.Hyb}});c.oic=function(a){O.L.call(this,a)};var O=c.q(c.oic,c.ao);O.sb=function(a){this.u.textContent=a};O.oz=function(){O.j.oz.call(this);this.u.style.whiteSpace="normal";this.u.style.overflowX="auto";
this.u.style.overflowY="auto"};O.Fd=function(a,b){this.u=document.createElement("div");this.u.setAttribute("id",a+this.gc);this.u.setAttribute("LANSAHandle",this.gc);return O.j.Fd.call(this,a,b)};c.sic=function(a){S.L.call(this,a)};var S=c.q(c.sic,c.ao);S.sb=function(a){this.u.textContent=a};S.hIa=function(){return!1};S.aoa=function(){};S.oz=function(){};S.Fd=function(a,b){this.u=document.createElement("p");this.u.setAttribute("id",a+this.gc);this.u.setAttribute("LANSAHandle",this.gc);return S.j.Fd.call(this,
a,b)};c.pic=function(a){F.L.call(this,a)};var F=c.q(c.pic,c.ao);F.hIa=function(){return!1};F.aoa=function(){};F.oz=function(){};F.Fd=function(a,b){this.u=document.createElement("br");this.u.setAttribute("id",a+this.gc);this.u.setAttribute("LANSAHandle",this.gc);return F.j.Fd.call(this,a,b)};c.qic=function(a){G.L.call(this,a)};var G=c.q(c.qic,c.ao);G.yd=function(a){this.u.src=a};G.hIa=function(){return!1};G.Zh=function(b,c,d){this.u.style.width=0==c?"auto":c+"px";this.u.style.height=0==d?"auto":d+
"px";switch(b){case a.xO.Dzb:this.u.style.marginLeft="initial";this.u.style.marginRight="initial";this.u.style.display="inline";this.u.style.cssFloat="none";break;case a.xO.aoc:this.u.style.marginLeft="initial";this.u.style.marginRight="initial";this.u.style.display="inline";this.u.style.cssFloat="left";break;case a.xO.boc:this.u.style.marginLeft="initial";this.u.style.marginRight="initial";this.u.style.display="inline";this.u.style.cssFloat="right";break;case a.xO.$nc:this.u.style.marginLeft="auto",
this.u.style.marginRight="auto",this.u.style.display="block",this.u.style.cssFloat="none"}};G.aoa=function(){};G.oz=function(){this.u.style.borderStyle="solid"};G.Fd=function(a,b){this.u=document.createElement("img");this.u.setAttribute("id",a+this.gc);this.u.setAttribute("LANSAHandle",this.gc);return G.j.Fd.call(this,a,b)};c.ric=function(a){Z.L.call(this,a)};var Z=c.q(c.ric,c.ao);Z.sb=function(a){this.u.textContent=a};Z.hIa=function(){return!1};Z.aoa=function(){};Z.oz=function(){};Z.Fd=function(a,
b){this.u=document.createElement("span");this.u.setAttribute("id",a+this.gc);this.u.setAttribute("LANSAHandle",this.gc);return Z.j.Fd.call(this,a,b)};c.Chc=function(a){pa.L.call(this,a)};var pa=c.q(c.Chc,c.ao);pa.Fd=function(a,b){this.u=document.createElement("div");this.u.setAttribute("id",a+this.gc);this.u.setAttribute("LANSAHandle",this.gc);return pa.j.Fd.call(this,a,b)};c.tic=function(a){ia.L.call(this,a);this.Wu=this.vp=null;this.syc=this.wOb=!1;this.rLb=null};var ia=c.q(c.tic,c.ao);ia.C4b=function(){return!0};
ia.Fd=function(a,b){this.u=document.createElement("div");this.u.setAttribute("id",a+this.gc);this.u.setAttribute("LANSAHandle",this.gc);this.u.style.msTouchAction="none";this.Wu=document.createElement("canvas");this.Wu.style.touchAction="none";this.u.appendChild(this.Wu);this.vp=this.Wu.getContext("2d");this.JSb();return ia.j.Fd.call(this,a,b)};ia.kq=function(a,b,c,d){ia.j.kq.call(this,a,b,c,d);if(c>this.Wu.width||d>this.Wu.height)a=this.vp.getImageData(0,0,this.Wu.width-1,this.Wu.height-1),this.Wu.width=
this.Hd,this.Wu.height=this.Od,this.vp.putImageData(a,0,0)};ia.jS=function(a){this.FCb(a);return!0};ia.nwb=function(a){this.zrc(a);return!0};ia.H0a=function(a){this.ECb(a);return!0};ia.lG=function(a){a.buttons&&this.FCb(a);return ia.j.lG.call(this,a)};ia.mG=function(a){this.ECb(a);return ia.j.mG.call(this,a)};ia.WAa=function(a){this.FCb(a);return!0};ia.Ox=function(a){this.zrc(a);return!0};ia.Vna=function(a){this.ECb(a);return!0};ia.u5b=function(a){this.u.onpointerdown===n&&a.touches!==n?(a.gIb=a.touches[0].pageX-
this.J.Mt(),a.hIb=a.touches[0].pageY-this.J.Nt()):(a.gIb=a.clientX-this.J.Mt(),a.hIb=a.clientY-this.J.Nt());this.J.Ce()};ia.JSb=function(){this.Jeb(!0);this.rLb=new Image;this.rLb.onload=function(){throw 0;};this.rLb.src=null};ia.Jeb=function(a){(this.syc||a)&&this.vp.clearRect(0,0,this.vp.canvas.width,this.vp.canvas.height);this.syc=!1};ia.QSc=function(){var a=this.Wu.toDataURL("image/png");return b.WYb(a)};ia.Ll=function(){this.JSb()};ia.FCb=function(a){a.preventDefault();this.Jeb(!1);this.vp.beginPath();
this.u5b(a);this.vp.moveTo(a.gIb,a.hIb);this.wOb=!0};ia.ECb=function(a){a.preventDefault();this.wOb=!1};ia.Pbe=function(a){this.Ox(a)};ia.zrc=function(a){this.wOb&&(a.preventDefault(),this.Jeb(!1),this.vp.strokeStyle="rgb(0,0,0)",this.vp.lineWidth=1,this.u5b(a),this.vp.lineTo(a.gIb,a.hIb),this.vp.stroke())};c.ihc=function(a){ka.L.call(this,a);this.xra=this.eb=null};var ka=c.q(c.ihc,c.ao);ka.ll=function(a){this.xra.src=a};ka.Fd=function(a,b){this.u=document.createElement("div");this.u.setAttribute("id",
a+this.gc);this.u.setAttribute("LANSAHandle",this.gc);this.xra=document.createElement("iframe");this.yZ(this.xra);this.xra.style.width="100%";this.xra.style.height="100%";this.u.appendChild(this.xra);return ka.j.Fd.call(this,a,b)};ka.ly=function(){var a=this;ka.j.ly.call(this);a.xra.addEventListener("load",function(){a.J&&a.J.tRc()},!1)};ka.yZ=function(a){ka.j.yZ.call(this,a);this.u.style.overflowX="auto";this.u.style.overflowY="auto"};c.Lhc=function(a){va.L.call(this,a);this.kr=null};var va=c.q(c.Lhc,
c.rvb);va.Fd=function(a,b){var c=va.j.Fd.call(this,a,b);this.kr=document.createElement("input");this.kr.type="File";this.kr.title="";var d=this.kr.style;this.cb.style.zIndex=1;d.opacity=0;d.position="absolute";d.zIndex=99998;d.background="rgb( 255, 0, 0 )";c.appendChild(this.kr);return c};va.Hc=function(){va.j.Hc.call(this);this.GOa()};va.kq=function(a,b,c,d){va.j.kq.call(this,a,b,c,d);this.kr.style.left="0px";this.kr.style.top="0px";this.kr.style.width=c+"px";this.kr.style.height=d+"px"};va.ly=function(){var a=
this;this.EZ();a.kr.addEventListener("change",function(b){a.J&&(a.XEa(b),a.kr.value="")},!1)};va.GOa=function(){this.kr.multiple=this.J.bja()};va.XEa=function(a){a=a.target.files||a.dataTransfer.files;for(var b=null,d=new c.Wub,e=0,f;f=a[e];e++)f=new c.xKa(f),null==b&&(b=f),d.hs(f);b&&this.J.Zsa(b,d)}},{rp:["PRIM_LABL"]});
