window.LANSA.addSrc("hint",function(d,c,a,b,n){function t(b){this.$x=b;this.xDa=b.Tp;this.bFd=a.kh.Tcd;this.CEd=!1;this.Qyc=new c.pa(0,0,0,0)}function q(a){this.$x=a;this.oga=this.cb="";this.Fc=null}d.Ob("PRIM_PPNL");d.Kd(function(){},"PRIM_HINT",{});c.hhc=function(a){r.L.call(this);this.$x=a;this.vQa=this.KY=this.qfa=this.Tr=this.Sr=this.oM=null;a=b.qka();d.Ob("PRIM_PANL");d.Ob("PRIM_LABL");this.oM=new c.Ql;this.oM.Na(this);this.oM.rb(new c.pa(0,0,0,0));this.Sr=new c.zw;this.Tr=new c.zw;this.Sr.Na(this.oM);
this.Tr.Na(this.oM);this.vQa=new c.xb;this.vQa.UI(!0);this.qfa=new c.xb;this.KY=new c.xb;this.KY.Jd(b.aa().I8);this.KY.Yq(0);this.KY.lq(0);this.KY.Bo(0);this.KY.Co(0);this.KY.Jv(a);this.oM.Jn(this.KY);this.Tr.Jn(this.vQa)};var r=c.q(c.hhc,c.yx);r.H0b=function(){b.Cka().Hh()?(this.oM.bo(this.KY),this.Tr.bo(this.vQa),this.qfa.Oj(b.R(114,114,114)),this.qfa.qi(a.m.wm),this.qfa.Nr(null),this.qfa.Mr(2),this.qfa.Us(0),this.Jn(this.qfa)):(this.oM.Jn(this.KY),this.Tr.Jn(this.vQa),this.bo(this.qfa),this.KY.Jd(b.aa().I8));
this.oM.Wb()||this.oM.hk(!0,!0);return this.oM.ve()};r.F4a=function(c,d,f){var e=b.Cka();c.$();c.Z();this.oM.oc(c.ha());this.oM.wc(c.ka());this.Tr.oc(c.ha());this.Tr.wc(c.ka());this.Sr.oc(c.ha());this.Sr.wc(c.ka());this.Tr.sb(this.$x.qY);this.Sr.sb(this.$x.Sr);e.Hh()?(this.oc(c.ha()),this.wc(c.ka()),0==this.Tr.$a().length?(this.Sr.Wa(0),this.Sr.Ya(6),this.Tr.oc(c.ha()-10),this.Sr.oc(c.ha()-10),this.Sr.Eo(a.$g.qq)):(this.Tr.Wa(4),this.Tr.Ya(6),this.Sr.Wa(d.ka()),this.Sr.Ya(12),this.Sr.Eo(a.$g.GX))):
(this.oc(c.ha()+4),this.wc(c.ka()+4),0==this.Tr.$a().length?(this.Sr.Wa(1),this.Sr.Ya(4),this.Sr.Eo(a.$g.qq)):(this.Tr.Wa(2),this.Tr.Ya(4),this.Sr.Wa(d.ka()),this.Sr.Ya(10),this.Sr.Eo(a.$g.GX)));this.Xnd(f.CEd);this.Bda(c.$(),c.Z(),n,n,null)};r.Ica=function(a){this.oM.Lg(100);return r.j.Ica.call(this,a)};c.Kdc=function(){this.zbb=7;this.V2=this.ofa=0;this.Tp=this.DBa=this.EBa=null;this.bMb=3;this.$X=this.e9=this.pfa=null;this.FT=0;this.R7a=b.xka(-1,-1);this.e9=new c.hhc(this);b.fS().iva().ya(this,
a.O.N7,this.yha)};var p=c.q(c.Kdc,c.tm);p.mb=function(){b.fS().iva().Mp(this,a.O.N7);p.j.mb.call(this)};p.Q=function(){this.DBa=this.EBa=null;this.eda(null);this.bzb();b.fa(this.e9);this.e9=null;p.j.Q.call(this)};p.$mb=function(a){this.FT|=a};p.pba=function(a){this.FT&=~a};p.ZYd=function(a,b){this.FT=this.FT&~a|(b?a:0)};p.TPd=function(){return this.$X};p.eda=function(c){if(this.$X!=c){this.$X&&(b.aa().tu(this.$X,!1),this.$X.Ga(this,this.$Tb));if(this.$X=c)this.$X.Ha(this,this.$Tb),this.$X.yG(!0);
this.l(a.g.i)}};p.xNd=function(){return this.Tp};p.zNd=function(){return this.EBa};p.vNd=function(){return this.DBa};p.fTd=function(){null==this.pfa&&(this.pfa=[]);return this.pfa};p.UPd=function(){return this.Sr};p.VPd=function(){return this.qY};p.Vta=function(){return b.kn().GBa/200};p.uOd=function(){return 1};p.aXd=function(){return 2};p.vOd=function(){return 1};p.bXd=function(){return 1};p.Q2b=function(){var a=6,c=b.Cka();c&&c.Hh()&&(a+=8);return a};p.S2b=function(){var a=4,c=b.Cka();c&&c.Hh()&&
(a+=4);return a};p.H1c=function(){return 0!=(this.FT&1)};p.Xd=function(){return 0!=(this.FT&8)};p.d6b=function(){return 0!=(this.FT&16)};p.w5b=function(){return 0!=(this.FT&32)};p.c6b=function(a){var c=!1;a=b.aa().vE(a);null!=a&&a.Wpb()&&(c=!0);return c};p.bzb=function(){if(this.pfa){for(;0<this.pfa.dm();){var a=this.pfa.ns(0);b.fa(a)}delete this.pfa;this.pfa=null}};p.Wra=function(b){this.c6b(b)||(this.zlc(b),this.Tp==b&&null==this.EBa&&null==this.DBa)||(this.G4b(),this.Tp=b,this.DBa=this.EBa=null,
this.qY=this.Sr="",this.V2=0,this.ofa=a.z8?this.Vta():0,this.$lc(),null!=this.Tp&&null!=this.Tp.Za()&&this.Tp.gs(),this.COa())};p.jId=function(b,c,d,e){this.c6b(b)||(this.zlc(b),this.Tp==b&&this.EBa==c&&this.DBa==e)||(this.Tp=b,this.EBa=c,this.DBa=e,this.qY=this.Sr="",this.V2=0,this.ofa=a.z8?this.Vta():0,this.$lc(),this.COa())};p.zlc=function(a){this.Tp!=a&&(null!=this.Tp&&this.Tp.Ga(this,this.ETb),null!=a&&a.Ha(this,this.ETb))};p.eHb=function(a){this.Tp==a&&this.COa()};p.$Qb=function(c){var d,f=
null;d=b.Ln();var e=b.K$c(d),n=b.aa().wxb(d);if(null==n||n!=this.$X)null==e||e.D5c()||(e=null),null!=e&&(f=e.ue()),null!=e&&e.Xd()&&null!=f&&(null==this.Tp||this.Tp.ue()!=f)&&(f=e.ue().FHc(d,a.fGa.$Yb))&&(f.Ed(a.ca.uJa),this.Tp==f&&(e=f)),this.Tp!=e&&this.Wra(null),this.d6b()?b.ztb(this.R7a,d)?++this.ofa>=this.Vta()&&(this.ofa=this.Vta(),this.eda(null),this.pba(16),this.V2=0,this.qY=this.Sr=""):(this.R7a=d,this.ofa=0,this.Tp&&this.Tp.G1b()&&(this.qY=this.Sr="",this.V2=0,this.eda(null),this.pba(16))):
(null!=this.Tp&&(e=!1,b.ztb(this.R7a,d)||(this.R7a=d,this.Tp&&this.Tp.G1b()&&(this.ofa=this.V2=0),e=!1,this.V2<this.zbb&&this.ofa<this.Vta()?this.V2=0:c=!1),++this.V2>=this.zbb&&!e&&(this.V2=this.zbb,this.ofa<this.Vta()?this.F4a():c=!1)),c&&3<=++this.bMb&&(this.bMb=3)),null==b.bO()&&this.bzb()};p.pJd=function(){return!1};p.mJd=function(){return!1};p.sde=function(){};p.R5d=function(){};p.ded=function(){this.H1c()||this.bzb();this.pba(1);this.Wra(null)};p.ced=function(a){b.aa().Rva()||(this.$mb(32),
this.eHb(a),this.pba(32))};p.eed=function(){(0>b.Bj(a.Qa.POa)||0>b.Bj(a.Qa.nBa)||0>b.Bj(a.Qa.s7a))&&this.Wra(null)};p.Mbe=function(){};p.COa=function(){null!=this.Tp?this.d6b()?this.F4a():this.w5b()&&(this.V2=this.zbb,this.$Qb(!1)):(this.eda(null),this.pba(16))};p.F4a=function(){var b,c,d=new t(this),e=null;this.Tp&&(c=new q(this),this.Tp.Ed(a.ca.vJa,c,null),e=c.Fc,b=c.cb,c=c.oga,this.Tp.Ed(a.ca.Orb,this.Tp,d));0==b.length&&null===e?(this.Sr=b,this.qY=c,this.eda(null),this.pba(16)):(this.Frd(e,b,
c,d),this.bMb=0)};p.G4b=function(){this.eda(null);this.pba(16)};p.Frd=function(a,d,f,e){null==a&&(a=this.e9);if(a!=this.e9||this.w5b()||0<d.length&&this.Sr!=d){var p=b.Pz(0,0),q=b.Pz(0,0),m=new c.pa(0,0,0,0);this.Sr=d;this.qY=f;this.pba(2);q=this.Brc(this.Sr);this.Xd()&&0<this.qY.length&&(p=this.Brc(this.qY),0==p.ka()&&(p=this.Crc(this.qY)));0==q.ka()&&(q=this.Crc(this.Sr),0<this.qY.length&&q.oc(q.ha()+10));m=b.Cka();d=b.xka(e.Qyc.$(),e.Qyc.Z());m&&m.Hh()&&null!=e.xDa?(m=this.u_b(d,q,p),d.mn(parseInt(e.xDa.Mt(),
10)),d.Qm(parseInt(e.xDa.Nt()+e.xDa.Ma()+14,10)),d.mn(parseInt(d.Nb()+(e.xDa.Sa()-m.ha())/2,10))):b.ztb(d,b.xka(0,0))&&(d=b.Ln(),d.Qm(d.Tb()+15));m=this.u_b(d,q,p);this.Xd()&&(this.eda(a),a==this.e9?this.e9.F4a(m,p,e):(e=b.xka(m.$(),m.Z()),a==this.$X&&a.Gh()&&a.Ica(e),a.Bda(e.Nb(),e.Tb(),n,n,null)));this.$mb(16)}};p.Crc=function(a){var d=b.Pz(0,0),f=this.e9.H0b(),e=new c.pa(0,0,0,0);b.jG(a,e,0,f);d.oc(e.ha()+this.Q2b());d.wc(e.ka()+this.S2b());return d};p.Brc=function(a){for(var d=b.Pz(0,0),f=String.fromCharCode(13),
e=this.e9.H0b(),n=a.indexOf(f),p=0;;)if(0<=n){var m;0!=n&&(m=a.substr(0,n));a=a.substr(n+1);0<m.length&&(n=new c.pa(0,0,0,0),b.jG(m,n,0,e),d.oc(Math.max(d.ha(),n.ha())));p++;n=a.indexOf(f)}else{0<a.length&&(n=new c.pa(0,0,0,0),b.jG(a,n,0,e),d.oc(Math.max(d.ha(),n.ha())),p++);break}1<p&&(this.$mb(2),n=new c.pa(0,0,0,0),b.jG("W",n,0,e),d.oc(d.ha()+this.Q2b()),d.wc(n.ka()*p+this.S2b()));return d};p.u_b=function(a,d,f){var e=b.qE(),n=new c.pa(0,0,0,0),p=e.ha()-1,m=e.ka()-1,e=new c.pa(e.$()+1,e.Z()+1,
p,m),m=e.k0(e),e=m.ha();m.ka();if(d.ha()<e){var s=a.Nb();s+d.ha()>e&&a.mn(m.Ja()-d.ha());n.Qb(a.Nb(),a.Tb());n.Nh(d.ha(),d.ka());0<f.ka()&&n.o7(0,f.ka());f.ha()>n.ha()&&n.o7(f.ha()-n.ha(),0);0<f.ha()&&d.ha()+10>f.ha()&&n.o7(10,0);return n}if(d.ha()<p)return s=a.Nb(),s+d.ha()>p&&(s=p-d.ha()),n.Qb(s,a.Tb()),n.Nh(d.ha(),d.ka()),n.o7(0,f.ka()),n;n=this.SSc(d,m,a);n.o7(0,f.ka());return n};p.SSc=function(a,d,f){var e=b.qE(),n=e.ha()-2,p=e.ka()-2,p=new c.pa(e.$()+1,e.Z()+1,n,p),e=[b.XR(),b.XR(),b.XR(),b.XR()],
n=[];n.push(3);n.push(2);n.push(1);n.push(0);var m,s,q,r,p=d.k0(p);p.ha();p.ka();d=a.ha()*a.ka();m=p.$();s=p.Z();e[0].Qb(m,s);e[0].Nh(f.Nb()-m,f.Tb()-s);e[1].Qb(f.Nb(),s);e[1].Nh(p.Ja()-f.Nb(),f.Tb()-s);e[2].Qb(m,f.Tb());e[2].Nh(f.Nb()-m,p.Da()-f.Tb());e[3].Qb(f.Nb(),f.Tb());e[3].Nh(p.Ja()-f.Nb(),p.Da()-f.Tb());for(s=p=q=0;4>s;s++){m=n[s];r=e[m].ha()*e[m].ka();q=Math.max(q,r);if(d<r){p=m;break}q==r&&(p=m)}e=e[p];n=a.ka();a=Math.min(a.ha(),e.ha());d=(d/a+n-1)/n*n;switch(p){case 0:e.Qb(f.Nb()-a,f.Tb()-
d);e.Nh(a,d);break;case 1:e.Qb(f.Nb(),f.Tb()-d);e.Nh(a,d);break;case 2:e.Qb(f.Nb()-a,f.Tb());e.Nh(a,d);break;case 3:e.Qb(f.Nb(),f.Tb()),e.Nh(a,d)}return e};p.$lc=function(){this.Xd();var a=null!=this.Tp&&null!=this.Tp.Ra()&&this.Tp.Ra().LN()&&this.Tp.Xd();this.FT=this.FT&-9|(a?8:0)};p.$Tb=function(b,c){switch(c.bb){case a.g.Bb:case a.g.Ub:this.eda(null)}};p.yha=function(){b.aa().XYa()||b.aa().Rva()||this.$Qb(!0)};p.ETb=function(b,c){switch(c.bb){case a.g.Bb:case a.g.Ub:this.Wra(null)}}},{rp:["PRIM_PPNL"]});
