window.LANSA.addSrc("wdgt",function(d,c,a,b,n){var t={};c.Eic=function(a){q.L.call(this);this.pQa=a;this.W8a=function(){};this.KT=this.RLb=!1;this.qMb=[];this.pMb=[];this.lMb=[];this.kMb=[];this.nMb=[]};var q=c.q(c.Eic,c.gf);q.qW=function(){return this.RLb};q.Fh=function(){return this.pQa.nm};q.CZc=function(){return this.pQa.js||[]};q.q_c=function(){return this.pQa.st||[]};q.OUc=function(){return this.pQa.fn};q.JVc=function(){return this.pQa.fe};q.u4=function(){return this.W8a};q.Vfd=function(){function a(){if(n<
p.length){var c=p[n],e=document.createElement("script");e.type="text/javascript";e.onload=function(){e.onload=null;e.onerror=null;n++;a()};e.onerror=function(){e.onload=null;e.onerror=null;throw"Error defining Widget "+d+", failed to load script: "+c;};document.body.appendChild(e);e.src=c}else b()}function b(){function a(){if(!c.RLb){for(c.RLb=!0;0<c.kMb.length;){var b=c.kMb.shift();c.gpb(b)}for(;0<c.pMb.length;)b=c.pMb.shift(),c.ipb(b.kIb,b.wFd,b.value);for(;0<c.nMb.length;)b=c.nMb.shift(),c.v5b(b.kIb,
b.parent);for(;0<c.qMb.length;)b=c.qMb.shift(),c.jpb(b);for(;0<c.lMb.length;)b=c.lMb.shift(),c.hpb(b)}}var d=c.OUc(),f=c.W8a.prototype;e&&e(f);var m={Loading:{},Completed:{},Finalize:function(){a()}};d(f,m)!==m.Loading&&a()}var c=this,d=c.Fh(),e=c.JVc();t[d]=c;for(var f=c.q_c(),m=0;m<f.length;m++){var g=f[m],k=document.createElement("link");k.type="text/css";k.rel="stylesheet";k.href=g;document.body.appendChild(k)}var n=0,p=c.CZc();a()};q.ipb=function(a,b,c){if(this.qW()){var e=a["set"+b];if(!e)throw d.Kgd("set"+
b);e&&e.call(a,c)}else this.pMb.push({kIb:a,wFd:b,value:c})};q.hpb=function(a){this.qW()?a.QVa():this.lMb.push(a)};q.gpb=function(a){if(this.qW()){var b=a.onCreateInstance;b&&b.call(a)}else this.kMb.push(a)};q.v5b=function(a,b){if(this.qW()){var c=a.onRealizeControl;if(!c)throw d.Jgd();c.call(a,b)}else this.nMb.push({kIb:a,parent:b})};q.jpb=function(a){if(this.qW()){var b=a.onSizeChanged;b&&b.call(a)}else this.qMb.push(a)};c.g0a=function(){r.L.call(this)};var r=c.q(c.g0a,c.Ql);r.Rc|=a.Vd.bJa;r.xz=
function(){return this.Ra()&&this.Ra().f2c()?this:null};r[a.ca.Fy]=function(b){var c=!1;this.Ra()&&(c=b.Zc!==n?b.Zc:a.ea.AO,c=c==a.ea.AO||c==a.ea.Tz||c==a.ea.AE?this.Ra().MZb(null):this.Ra().NZb(null));c||r.j.LQ.call(this,b)};r[a.ca.pJa]=function(b){var c=!1;this.Ra()&&(c=(b.Zc!==n?b.Zc:a.ea.AO)==a.ea.AO?this.Ra().MZb(document.activeElement):this.Ra().NZb(document.activeElement));c||r.j.lhb.call(this,b)};c.ehc=function(){p.L.call(this)};var p=c.q(c.ehc,c.Ad);d.Kd(c.ehc,"PRIM_WDGT",{});c.ghc=function(){k.L.call(this);
var a=this.AWa(),a=this.tZ=t[a],b=this.kM=new (a.u4());b.LANSA_Component=this;b.LANSA_Class=a;a.gpb(b)};var k=c.q(c.ghc,c.Ad);k.fpb=function(a,b){if(this.tZ.qW()){var c=this.kM[a];if(!c)throw d.fnc(a);return c.apply(this.kM,b)}throw d.t2a();};k.zHa=function(a){if(this.tZ.qW()){var b=this.kM["get"+a];if(!b)throw d.enc("get"+a);return b.call(this.kM)}throw d.t2a();};k.GMa=function(a,b){this.tZ.ipb(this.kM,a,b)};k.g0=function(){var a=this;setTimeout(function(){a.tZ.hpb(a)},5)};k.QVa=function(){this.Fa(a.O.Aba)};
d.Ta(c.ghc,"PRIM_WDGT","Object",{});var g=k;g.get=g.zHa;g.set=g.GMa;g.invoke=g.fpb;c.fhc=function(){f.L.call(this);var b=this.AWa(),b=this.tZ=t[b],c=this.kM=new (b.u4());c.LANSA_Component=this;c.LANSA_Class=b;b.gpb(c);this.Rc&=~a.Vd.MR;this.Rc&=~a.Vd.s0};var f=c.q(c.fhc,c.g0a);f.ze=function(){return c.Dic};f.Hc=function(a,c,d){f.j.Hc.call(this,a,c,d);a=this.Ra().Za();b.ke[a].X9c(this.kM)};f.fpb=function(a,b){if(this.tZ.qW()){var c=this.kM[a];if(!c)throw d.fnc(a);return c.apply(this.kM,b)}throw d.t2a();
};f.zHa=function(a){if(this.tZ.qW()){var b=this.kM["get"+a];if(!b)throw d.enc("get"+a);return b.call(this.kM)}throw d.t2a();};f.GMa=function(a,b){this.tZ.ipb(this.kM,a,b)};f.f5d=function(){this.QVa()};f[a.ca.hka]=function(){this.tZ.hpb(this)};f[a.ca.xI]=function(){this.Wb()&&this.tZ.jpb(this.kM)};f.Lla=function(){f.j.Lla.call(this);this.Wb()&&this.tZ.jpb(this.kM)};d.Ta(c.fhc,"PRIM_WDGT","Control",{});g=f;g.get=g.zHa;g.set=g.GMa;g.invoke=g.fpb;c.Rgc=function(){e.L.call(this);this.Mb=b.Hf(0,0,100,100);
this.f9=this.xQa=""};var e=c.q(c.Rgc,c.g0a);e.ze=function(){return c.Nhc};e.AWc=function(){return this.xQa};e.$nd=function(b){this.xQa!=b&&(this.xQa=b,this.na(a.g.i),this.Gd())};e.uC=function(){return this.f9};e.kma=function(a){this.f9=a};e.OC=function(a){var d=this.zo(),e=this.gq();if(d||e){var f=new c.pa;new c.pa(0,0,1E4,1E4);var m=[];m[0]=d;m[1]=e;m[2]=a;m[3]=0;m[4]=0;var g=this.Za();m[3]=0;m[4]=0;null!=g&&b.ke[g].fwc(m);f.Ua(m[3]);f.Ia(m[4]);d&&a.Ua(a.$()+this.ga.Xi()+f.ha()+this.ga.Yj());e&&
a.Ia(a.Z()+this.ga.Zj()+f.ka()+this.ga.wl())}};d.Ta(c.Rgc,"PRIM_WEB","HtmlContainer",{Ba:{Html:{a:e.AWc,f:function(a){this.$nd(d.ja(a))}},Description:{a:e.uC,f:function(a){this.kma(d.ja(a))}}},cf:{af:"Html"}});c.r0a=function(a){x.L.call(this,a)};var x=c.q(c.r0a,c.ao);x.mIa=function(){return!1};x.f2c=function(){return 0<this.ofb().length};x.jS=function(a){x.j.jS.call(this,a);return!1};x.MZb=function(a){var b=this.ofb();for(a=a?b.indexOf(a)+1:0;0<=a&&a<b.length;){var c=b[a];if(c&&(c.focus(),c==document.activeElement))return!0;
a++}return!1};x.NZb=function(a){var b=this.ofb();for(a=a?b.indexOf(a)-1:b.length-1;0<=a;){var c=b[a];if(c&&(c.focus(),c==document.activeElement))return!0;a--}return!1};x.ofb=function(){var a=[],b=[];this.glc(this.u,b);for(var c=1;c<b.length;c++)a=a.concat(b[c]||[]);return a=a.concat(b[0]||[])};x.glc=function(a,b){var c=a.tabIndex;0<=c&&(b[c]===n&&(b[c]=[]),b[c].push(a));for(var c=a.childNodes,d=0;d<c.length;d++)a=c[d],this.glc(a,b)};x.iaa=x[a.Qa.gT]=function(b){b.Qf=a.Qa.iha|a.Qa.mUa};c.Dic=function(a){C.L.call(this,
a);this.eb=null};var C=c.q(c.Dic,c.r0a);C.Fd=function(a,b){this.u=document.createElement("div");this.u.setAttribute("id",a+this.gc);this.u.setAttribute("LANSAHandle",this.gc);return C.j.Fd.call(this,a,b)};C.X9c=function(a){null==this.eb&&(this.eb=document.createElement("div"),this.eb.style.left="0px",this.eb.style.top="0px",this.eb.style.width="100%",this.eb.style.height="100%",a.LANSA_Class.v5b(a,this.eb),this.u.appendChild(this.eb))};c.Nhc=function(a){m.L.call(this,a);this.eb=null};var m=c.q(c.Nhc,
c.r0a);m.oz=function(){m.j.oz.call(this);this.u.style.whiteSpace="normal"};m.Fd=function(a,b){this.u=document.createElement("div");this.u.setAttribute("id",a+this.gc);this.u.setAttribute("LANSAHandle",this.gc);this.eb=document.createElement("div");this.eb.style.left="0px";this.eb.style.top="0px";this.eb.style.width="100%";this.eb.style.height="100%";this.eb.innerHTML=this.J.xQa;this.u.appendChild(this.eb);return m.j.Fd.call(this,a,b)};m.vBd=function(){var a=this.J.zo(),b=this.J.gq();this.eb.style.width=
a?"":"100%";this.eb.style.height=b?"":"100%";this.eb.innerHTML=this.J.xQa};m.Hc=function(){m.j.Hc.call(this);this.vBd()};m.fwc=function(a){var b=a[0],c=a[2],d=this.eb.style.width;a[1]&&!b&&(this.eb.style.width=c.ha()+"px");a[3]=this.eb.clientWidth;a[4]=this.eb.clientHeight;this.eb.style.width=d}});
