window.LANSA.addSrc("evef",function(d,c,a,b){d.Ob("PRIM_EVP");d.Ob("PRIM_EDIT");c.X$b=function(b){n.L.call(this,b);this.ko|=a.Rib.AHb;this.eg|=268435456;this.Pa=new c.W$b(this);this.Pa.Na(this);this.Pa.ya(this,a.O.vh,this.UD)};var n=c.q(c.X$b,c.Qba);n.mb=function(){b.fa(this.Pa);this.Pa=null;n.j.mb.call(this)};n.mja=function(){return this.Pa};n.FE=function(b){this.Pa.yy()!=b&&(this.Pa.FE(b),this.na(a.g.i))};n.yy=function(){return this.Pa.yy()};n.px=function(){return this.fp()!=this.Hr()};n.Hr=function(){return this.Pa.Hr()};
n.Xs=function(a){this.Pa.Xs(a)};n.fp=function(){return this.Pa.fp()};n.Ws=function(a){this.Pa.Ws(a)};n.lc=function(){return this.Pa.lc()};n.ox=function(){return this.Pa.ga};n.yS=function(a){1==a?this.Zq(268435456):this.Zq(0)};n.ZM=function(){var a=0;268435456==this.cl()&&(a=1);return a};n.Zq=function(b){this.cl()!=b&&(this.eg=this.eg&~a.kj.Usa|b,this.Vh(),this.l(a.g.i))};n.cl=function(){return this.eg&a.kj.Usa};n.fZa=function(){return this.DN()?!0:!1};n.DN=function(){return 0<this.cl()};n.FOa=function(){this.ff()&&
this.ff().Pb(this.TCa);this.Pa&&this.Pa.Pb(this.FCa)};n.IIa=function(){this.Pa.Bh(this.qb());this.Pa.Yz(!0);this.Pa.Gx(!0);this.Pa.bda(this.o_());this.Pa.Wh(this.yf());this.Pa.HO(this.vk());this.Pa.oda(this.VP);this.Pa.eo(this.fm());this.Pa.Pm(this.Nj());this.Pa.Mu(this.tx());this.Pa.Rk(this.Yi());this.Pa.Fj(this.Qg());this.Pa.fo(this.hm());this.qb().UIa()&&this.Pa.Ku("*")};n.t5=function(a){this.IIa();n.j.t5.call(this,a)};n.Lk=function(){this.IIa();n.j.Lk.call(this)};n.hf=function(a){if(this.Pa){var c=
this.uf(),d,k,g;this.Xd()?(k=this.ji,g=this.ki,d=c.ha()-(this.ji+this.Zk),c=c.ka()-(this.ki+this.Yk)):(k=this.Yf(),g=this.Tf(),d=c.ha()-(this.Yf()+this.Xg()),c=c.ka()-(this.Tf()+this.bh()));this.Pa.rb(b.Ni(k,g,d,c))}n.j.hf.call(this,a)};n.xta=function(){var a;this.Pa&&(a=this.Pa.Ml());return a};n.gJ=function(a,b){a&&a.Ga(this,this.Dp);b&&b.Ha(this,this.Dp);this.Pa.Bh(b)};n.Ss=function(){this.Pa.Of()};n.fg=function(a){null!=this.Pa&&this.Pa.HO(this.vk());n.j.fg.call(this,a);this.Pa&&(this.Pa.$t(null),
this.Pa.Yz(!0),this.Pa.Gx(!0),this.dC&&this.Pa.$t(this.dC))};n.kHb=function(){this.Pa&&this.Pa.awc()};n.N6=function(a,b){this.Pa&&this.Pa.N6(a,b)};n.H3=function(){this.Pa&&this.Pa.H3()};n.sQ=function(a){this.Pa&&this.Pa.sQ(a)};n.qS=function(a){this.Pa&&this.Pa.qS(a)};n.UD=function(){this.Ce()};n.Dp=function(){};n.YUa=n[a.ca.gka]=function(){this.Pa&&this.xda(this.Z4())};n.LQ=n[a.ca.Fy]=function(){this.Pa.Of()};n.MQ=n[a.ca.WN]=function(){this.Pa.Of()};d.Kd(c.X$b,"PRIM_EVEF",{uS:a.oy.aaa,Ba:{ComponentVersion:{a:n.ZM,
f:function(a){this.yS(d.K(a))}},AutoTab:{a:n.o_,f:function(a){this.bda(d.Aa(a))}},AutoSelect:{a:n.fm,f:function(a){this.eo(d.Aa(a))}},WordWrap:{a:n.qd,f:function(a){this.Bf(d.Aa(a))}},ShowSelection:{a:n.Nj,f:function(a){this.Pm(d.Aa(a))}},ShowSelectionHilight:{a:n.tx,f:function(a){this.Mu(d.Aa(a))}},ShowPrompter:{a:n.iba,f:function(a){this.oza(d.Aa(a))}},PrompterImage:{a:n.CXa,f:n.tda},PrompterTabStop:{a:n.yHa,f:function(a){this.JBb(d.Aa(a))}},UsePicklist:{a:n.jYa,f:function(a){this.m7(d.Aa(a))}},
EditAlignment:{a:function(){return d.wa(this.Yi(),a.Gn.G)},f:function(b){this.Rk(d.va(b,a.Gn.G))}},DisplayAlignment:{a:function(){return d.wa(this.Qg(),a.ag.G)},f:function(b){this.Fj(d.va(b,a.ag.G))}},Text:{a:n.wta},SelectionEnd:{a:n.fp,f:function(a){this.Ws(d.K(a))}},SelectionStart:{a:n.Hr,f:function(a){this.Xs(d.K(a))}},VisualStyleEdit:{a:n.Tmb,f:n.$Ma},NumericEditStyle:{a:function(){return d.wa(this.hm(),a.lp.G)},f:function(b){this.fo(d.va(b,a.lp.G))}},HasSelection:{a:n.px},EditStyle:{a:n.Eaa,
f:n.qma},EditStyles:{a:n.Eta},EditMouseOverStyle:{a:n.MWa,f:n.s3a},EditMouseOverStyles:{a:n.NWa},EditFocusedStyle:{a:n.KWa,f:n.r3a},EditFocusedStyles:{a:n.LWa},LabelStyle:{a:n.Qaa,f:n.uma},LabelStyles:{a:n.aXa},LabelMouseOverStyle:{a:n.ZWa,f:n.K3a},LabelMouseOverStyles:{a:n.$Wa},SpellCheck:{a:n.yy,f:function(a){this.FE(d.Aa(a))}},Value:{a:function(){return this.jb()},f:function(a){this.nb(a)}}},nc:{SelectText:function(a,b){this.N6(d.K(a)-1,d.K(b))}},cf:{af:"Value"}});c.W$b=function(a){t.L.call(this);
this.Iyc=a};var t=c.q(c.W$b,c.EI);t.wN=function(){return this.Iyc.mw()||this.Iyc.XY?!1:t.j.wN.call(this)}},{rp:["PRIM_EVP","PRIM_EDIT"]});
