window.LANSA.addSrc("sound",function(d,c,a,b,n){var t,q;t={ALL:0,METADATA:1,NONE:2};q={auto:0,metadata:1,none:2};c.q_a=function(a){r.L.call(this);this.v9=this.jr="";this.Boa=a};var r=c.q(c.q_a,c.Ad);r.Q=function(){r.j.Q.call(this)};r.Ug=function(){return this.jr};r.Iu=function(a){this.jr=a};r.D4=function(){return this.v9==n?"":this.v9};r.S6=function(a){this.v9=a};r.Is=function(){for(var a=0;a<this.Boa.Jc();a++)this.Boa.Jt(a)===this&&this.Boa.ns(a)};d.Ta(c.q_a,"PRIM_SOND","File",{Ba:{FileName:{a:r.Ug,
f:function(a){this.Iu(d.ja(a))}},FileExtension:{a:r.D4,f:function(a){this.S6(d.ja(a))}}},nc:{Delete:r.Is},cf:{af:"FileExtension"}});c.Dtb=function(a){p.L.call(this);this.Kzc=a;this.kb=[]};var p=c.q(c.Dtb,c.Ad);p.Jc=function(){return this.kb.length};p.se=function(a){return this.Jt(a)};p.Jt=function(a){if(0>a||a>=this.kb.length)throw d.QI(a,this.kb.length);return this.kb[a]};p.ni=function(a,b){var d=new c.q_a(this);d.Iu(a);d.S6(b);this.kb.push(d);(d=this.Kzc.Ra())&&d.du()};p.XGa=function(){0==this.Jc()&&
this.kb.push(new c.q_a(this));return this.Jt(0)};p.Al=function(){this.kb=[];var a=this.Kzc.Ra();a&&a.du()};p.ns=function(a){if(null==this.Jt(a))throw d.QI(a,this.kb.length);this.kb.splice(a,1)};p.bgd=function(a){for(var b=!1,c=0;c<this.Jc()&&!(b=this.Jt(c).Ug()==a);c++);b&&this.ns(c)};d.Ta(c.Dtb,"PRIM_SOND","Files",{Ba:{Item:{a:function(a){return this.Jt(d.K(a)-1)}}},nc:{Add:p.ni,RemoveAll:p.Al,Remove:function(a){return this.ns(d.K(a)-1)}},ls:{Jr:function(a){return this.Jt(d.K(a)-1)},Ey:function(){return this.Jc()}},
cf:{af:"Item"}});c.tfc=function(){k.L.call(this);this.Y8=0;this.K8=this.i$=!0;this.ZY=1;this.bz=new c.Dtb(this);this.Si=-1;this.Wpa=this.Ypa=this.xY=!1;this.qF=50};var k=c.q(c.tfc,c.xx);k.ze=function(){return c.uic};k.Q=function(){k.j.Q.call(this)};k.Ug=function(){return 0<this.bz.Jc()?this.bz.Jt(0).Ug():""};k.Iu=function(b){this.bz.Al();var c=this.bz.XGa();c.Ug()!=b&&(c.Iu(b),(b=this.Ra())&&b.du(),this.l(a.g.i))};k.D4=function(){return 0<this.bz.Jc()?this.bz.Jt(0).D4():""};k.S6=function(b){var c=
this.bz.XGa();c.D4()!=b&&(c.S6(b),(b=this.Ra())&&b.du(),this.l(a.g.i))};k.SVc=function(){return this.bz};k.Bkb=function(){return this.Y8};k.xAb=function(b){this.Y8!=b&&(this.Y8=b,(b=this.Ra())&&b.du(),this.l(a.g.i))};k.nlb=function(){return this.xY};k.qmb=function(){return this.i$};k.QBb=function(b){this.i$!=b&&(this.i$=b,(b=this.Ra())&&b.du(),this.l(a.g.i))};k.Sjb=function(){return this.K8};k.Yzb=function(b){this.K8!=b&&(this.K8=b,(b=this.Ra())&&b.du(),this.l(a.g.i))};k.Daa=function(){return this.Si};
k.olb=function(){return this.Ypa};k.mlb=function(){return this.Wpa};k.Umb=function(){return this.qF};k.aNa=function(c){c=b.Gf(c,0,100);this.qF!=c&&(this.qF=c,this.xY=0==this.qF,(c=this.Ra())&&c.du(),this.l(a.g.i))};k.KYc=function(){return this.ZY};k.HBb=function(b){this.ZY!=b&&(this.ZY=b,(b=this.Ra())&&b.du(),this.l(a.g.i))};k.Play=function(){this.Ra()&&this.Ra().Play()};k.gi=function(){this.Ra()&&this.Ra().gi()};k.Hwb=function(){this.aNa(0)};d.Kd(c.tfc,"PRIM_SOND",{Ba:{FileName:{a:k.Ug,f:function(a){this.Iu(d.ja(a))}},
CycleToStart:{a:k.Bkb,f:function(a){this.xAb(d.Aa(a))}},ShowControls:{a:k.qmb,f:function(a){this.QBb(d.Aa(a))}},Autoplay:{a:k.Sjb,f:function(a){this.Yzb(d.Aa(a))}},Preload:{a:function(){return d.wa(this.ZY,t)},f:function(a){this.HBb(d.va(a,t))}},Duration:{a:k.Daa},IsMuted:{a:k.nlb},IsPlaying:{a:k.olb},IsEnded:{a:k.mlb},Volume:{a:k.Umb,f:function(a){this.aNa(d.K(a))}}},nc:{Play:k.Play,Stop:k.gi,Mute:k.Hwb}});c.uic=function(a){g.L.call(this,a)};var g=c.q(c.uic,c.ao);g.Fd=function(b,c){this.u=document.createElement("audio");
this.u.setAttribute("LANSAHandle",this.gc);this.u.style.position="absolute";this.u.style.overflow="hidden";this.u.style.whiteSpace="nowrap";this.du();var d=this.u,k=this;d.addEventListener("loadedmetadata",function(){k.J&&(k.J.Si=d.duration,k.J.Fa(a.O.B9b))},!1);d.addEventListener("loadeddata",function(){k.J&&k.J.Fa(a.O.A9b)},!1);d.addEventListener("play",function(){k.J&&(k.J.Ypa=!0,k.J.Wpa=!1,k.J.Fa(a.O.Skc))},!1);d.addEventListener("pause",function(){k.J&&(k.J.Ypa=!1,k.J.Fa(a.O.Mrc))},!1);d.addEventListener("ended",
function(){k.J&&(k.u.pause(),k.u.paused=!0,k.J.Wpa=!0,k.J.Fa(a.O.sy))},!1);d.addEventListener("volumechange",function(){k.J&&(d.muted||0==d.volume?(k.u.muted=!0,k.J.xY=!0,k.J.qF=0,k.J.Fa(a.O.Gjc)):(k.J.xY=!1,k.J.qF=Math.round(100*d.volume)))},!1);return g.j.Fd.call(this,b,c)};g.du=function(){this.Rya("controls",this.J.i$);this.Rya("autoplay",this.J.K8);this.Rya("loop",this.J.Y8);this.u.setAttribute("preload",d.wa(this.J.ZY,q));this.u.volume=0<this.J.qF?this.J.qF/100:0;this.u.muted=this.J.xY;this.cHb()};
g.cHb=function(){this.Tyb();var a=this.J.bz.Jc();if(0!=a)for(var b=0;b<a;b++){var c=this.J.bz.Jt(b);this.aCc(this.u,c.jr,c.v9)}};g.aCc=function(a,b,c){var d=document.createElement("source");d.src=b;c&&(d.type="audio/"+c);a.appendChild(d)};g.Tyb=function(){var a=this.u;if(a&&(a=a.childNodes)){var b,c,d=[];for(c=0;c<a.length;c++)b=a[c],"SOURCE"==b.nodeName&&d.push(b);for(c=0;c<d.length;c++)b=d[c],b.parentNode.removeChild(b)}};g.jS=function(){return!1};g.H0a=function(){};g.Play=function(){this.u.play!==
n&&this.u.play()};g.gi=function(){this.u.pause!==n&&this.u.pause()}});
