window.LANSA.addSrc("json",function(e,c,a,b,m){function p(a,b,d){var f=null;if(null===d)f=e.Rt(new c.Zya(a,b));else switch(typeof d){case "object":f=Array.isArray(d)?e.Rt(new c.xma(a,b)):e.Rt(new c.yma(a,b));f.FAb(d);break;case "number":f=e.Rt(new c.$ya(a,b,d));break;case "string":f=e.Rt(new c.aza(a,b,d));break;case "boolean":f=e.Rt(new c.Yya(a,b,d))}return f}e.Gb("PRIM_PCOL");a.qE={U4a:0,OHb:1,LHb:2,PHb:3,NHb:4,MHb:5};a.qE.v={NULL:a.qE.U4a,OBJECT:a.qE.OHb,ARRAY:a.qE.LHb,STRING:a.qE.PHb,NUMBER:a.qE.NHb,
BOOLEAN:a.qE.MHb};c.H_b=function(){l.w.call(this);this.Mg="";this.FFa=null;this.$xb=!1};var l=c.u(c.H_b,c.wd);l.U=function(){this.QRa(null);l.j.U.call(this)};l.ICc=function(){return this.FFa};l.QRa=function(a){this.FFa=a};l.yEc=function(){return this.$xb};l.eSa=function(a){this.$xb=a};l.Bq=function(){return this.$xb?JSON.stringify(this.FFa.EL()):this.Mg};l.$M=function(a){this.Mg=a;var b=null,c=null;try{b=JSON.parse(a)}catch(d){}b?(c=p(this,null,b),this.eSa(!0)):this.eSa(!1);this.QRa(c)};l.jnc=function(){this.QRa(e.Rt(new c.xma(this,
null)));this.eSa(!0);return this.FFa};l.knc=function(){this.QRa(e.Rt(new c.yma(this,null)));this.eSa(!0);return this.FFa};e.jb(c.H_b,"PRIM_WEB","Json",{Oa:{Text:{a:l.Bq,g:function(a){this.$M(e.ma(a))}},IsValid:{a:l.yEc},RootItem:{a:l.ICc}},jc:{CreateRootArray:l.jnc,CreateRootObject:l.knc},lg:{hg:"Text"}});c.X4=function(a,b){s.w.call(this);this.qF=a;this.hA=b};var s=c.u(c.X4,c.wd);s.waa=function(){return a.qE.U4a};s.EL=function(){return null};s.mc=function(){return 0};s.Td=function(){return null};
s.Jw=function(){return null};s.krd=function(){return this.qF};s.B7a=function(){return this.hA};s.dka=function(){return this.hA?this.hA.BKb(this):""};s.BKb=function(){return""};s.fj=function(){return this.hA?this.hA.d7a(this):-1};s.d7a=function(){return-1};s.q9=function(){throw e.eUc(JSON.stringify(this.EL()));};s.R_a=function(){throw e.jAa(JSON.stringify(this.EL()));};s.H_a=function(){throw e.pjb(JSON.stringify(this.EL()));};s.Ys=function(){return null};s.bk=function(){};e.jb(c.X4,"PRIM_WEB","JsonElement",
{Oa:{Key:{a:s.dka},Index:{a:function(){return this.fj()+1}},Type:{a:function(){return e.ta(this.waa(),a.qE.v)}},Item:{a:function(a){return this.Td(e.ma(a))}},ItemAt:{a:function(a){return this.Jw(e.K(a)-1)}},ItemCount:{a:function(){return this.mc()}},ParentItem:{a:s.B7a}},jc:{AsString:function(){return this.q9()},AsNumber:function(){return e.mq(this.R_a())},AsBoolean:function(){return this.H_a()},Remove:function(a){return this.Ys(e.ma(a))},RemoveAt:function(a){return this.yr(e.K(a)-1)},RemoveAll:function(){this.bk()}},
lg:{hg:"Item"},gq:{Cp:function(a){return this.Jw(e.K(a)-1)},Qv:function(){return this.mc()}}});c.xma=function(a,b){g.w.call(this,a,b);this.ab=[]};var g=c.u(c.xma,c.X4);g.waa=function(){return a.qE.LHb};g.EL=function(){for(var a=[],b=0;b<this.ab.length;b++)a.push(this.ab[b].EL());return a};g.Jw=function(a){return 0<=a&&a<this.ab.length?this.ab[a]:null};g.mc=function(){return this.ab.length};g.d7a=function(a){for(var b=0;b<this.ab.length;b++)if(this.ab[b]===a)return b;return-1};g.FAb=function(a){for(var b=
0;b<a.length;b++){var c=p(this.qF,this,a[b]);c&&this.ab.push(c)}};g.T$a=function(){var a=e.Rt(new c.xma(this.qF,this));this.ab.push(a);return a};g.aab=function(){var a=e.Rt(new c.yma(this.qF,this));this.ab.push(a);return a};g.eab=function(a){a=e.Rt(new c.aza(this.qF,this,a));this.ab.push(a);return a};g.$$a=function(a){a=e.Rt(new c.$ya(this.qF,this,a));this.ab.push(a);return a};g.W$a=function(a){a=e.Rt(new c.Yya(this.qF,this,a));this.ab.push(a);return a};g.Z$a=function(){var a=e.Rt(new c.Zya(this.qF,
this));this.ab.push(a);return a};g.yr=function(a){var b=null;0<=a&&a<this.ab.length&&(b=this.ab[a],this.ab.splice(a,1));return b};g.bk=function(){this.ab=[]};e.jb(c.xma,"PRIM_WEB","JsonArray",{jc:{InsertArray:g.T$a,InsertObject:g.aab,InsertNumber:function(a){return this.$$a(e.hv(a))},InsertString:function(a){return this.eab(e.ma(a))},InsertBoolean:function(a){return this.W$a(e.ya(a))},InsertNull:g.Z$a}});c.yma=function(a,b){q.w.call(this,a,b);this.ab={}};var q=c.u(c.yma,c.X4);q.waa=function(){return a.qE.OHb};
q.EL=function(){var a={},b;for(b in this.ab)a[b]=this.ab[b].EL();return a};q.Td=function(a){a=this.ab[a];return a===m?null:a};q.Jw=function(a){var b=this.qca();return 0<=a&&a<b.length?this.ab[b[a]]:null};q.mc=function(){return this.qca().length};q.BKb=function(a){for(var b in this.ab)if(this.ab[b]===a)return b};q.d7a=function(a){var b=-1,c;for(c in this.ab)if(b++,this.ab[c]===a)break;return b};q.FAb=function(a){for(var b in a){var c=p(this.qF,this,a[b]);c&&(this.ab[b]=c)}this.SG()};q.SG=function(){delete this.vF};
q.qca=function(){if(this.vF===m){this.vF=[];for(var a in this.ab)this.vF.push(a)}return this.vF};q.T$a=function(a){var b=e.Rt(new c.xma(this.qF,this));this.ab[a]=b;this.SG();return b};q.aab=function(a){var b=e.Rt(new c.yma(this.qF,this));this.ab[a]=b;this.SG();return b};q.eab=function(a,b){var d=e.Rt(new c.aza(this.qF,this,b));this.ab[a]=d;this.SG();return d};q.W$a=function(a,b){var d=e.Rt(new c.Yya(this.qF,this,b));this.ab[a]=d;this.SG();return d};q.Z$a=function(a){var b=e.Rt(new c.Zya(this.qF,this));
this.ab[a]=b;this.SG();return b};q.$$a=function(a,b){var d=e.Rt(new c.$ya(this.qF,this,b));this.ab[a]=d;this.SG();return d};q.Ys=function(a){var b=null;this.ab[a]!==m&&(b=this.ab[a],delete this.ab[a],this.SG());return b};q.yr=function(a){var b=this.qca();return 0<=a&&a<b.length?this.Ys(b[a]):null};q.bk=function(){this.ab={};this.SG()};e.jb(c.yma,"PRIM_WEB","JsonObject",{jc:{InsertArray:function(a){return this.T$a(e.ma(a))},InsertObject:function(a){return this.aab(e.ma(a))},InsertNumber:function(a,
b){return this.$$a(e.ma(a),e.hv(b))},InsertString:function(a,b){return this.eab(e.ma(a),e.ma(b))},InsertBoolean:function(a,b){return this.W$a(e.ma(a),e.ya(b))},InsertNull:function(a){return this.Z$a(e.ma(a))}}});c.$ya=function(a,b,c){f.w.call(this,a,b);this.bb=c};var f=c.u(c.$ya,c.X4);f.waa=function(){return a.qE.NHb};f.EL=function(){return this.bb};f.R_a=function(){return this.bb};f.q9=function(){return this.bb.toString()};e.jb(c.$ya,"PRIM_WEB","JsonNumber",{});c.aza=function(a,b,c){k.w.call(this,
a,b);this.bb=c};var k=c.u(c.aza,c.X4);k.waa=function(){return a.qE.PHb};k.EL=function(){return this.bb};k.q9=function(){return this.bb};k.R_a=function(){if(isNaN(Number(this.bb)))throw e.jAa(this.bb);return new c.uj(this.bb)};k.H_a=function(){if("TRUE"==this.bb.toUpperCase())return!0;if("FALSE"==this.bb.toUpperCase())return!1;throw e.pjb(this.bb);};e.jb(c.aza,"PRIM_WEB","JsonString",{});c.Yya=function(a,b,c){d.w.call(this,a,b);this.bb=c};var d=c.u(c.Yya,c.X4);d.waa=function(){return a.qE.MHb};d.EL=
function(){return this.bb};d.H_a=function(){return this.bb};d.q9=function(){return this.bb?"true":"false"};e.jb(c.Yya,"PRIM_WEB","JsonBoolean",{});c.Zya=function(a,b){h.w.call(this,a,b)};var h=c.u(c.Zya,c.X4);h.waa=function(){return a.qE.U4a};h.EL=function(){return null};e.jb(c.Zya,"PRIM_WEB","JsonNull",{})},{rp:["PRIM_PCOL"]});
