window.LANSA.addSrc("sound",function(e,c,a,b,m){var p,l;p={ALL:0,METADATA:1,NONE:2};l={auto:0,metadata:1,none:2};c.yNa=function(a){s.w.call(this);this.x1=this.Ds="";this.Dfa=a};var s=c.u(c.yNa,c.wd);s.U=function(){s.j.U.call(this)};s.yh=function(){return this.Ds};s.fw=function(a){this.Ds=a};s.lY=function(){return this.x1==m?"":this.x1};s.k_=function(a){this.x1=a};s.er=function(){for(var a=0;a<this.Dfa.mc();a++)this.Dfa.lr(a)===this&&this.Dfa.yr(a)};e.jb(c.yNa,"PRIM_SOND","File",{Oa:{FileName:{a:s.yh,
g:function(a){this.fw(e.ma(a))}},FileExtension:{a:s.lY,g:function(a){this.k_(e.ma(a))}}},jc:{Delete:s.er},lg:{hg:"FileExtension"}});c.oeb=function(a){g.w.call(this);this.Ufc=a;this.ab=[]};var g=c.u(c.oeb,c.wd);g.mc=function(){return this.ab.length};g.Td=function(a){return this.lr(a)};g.lr=function(a){if(0>a||a>=this.ab.length)throw e.DE(a,this.ab.length);return this.ab[a]};g.oh=function(a,b){var e=new c.yNa(this);e.fw(a);e.k_(b);this.ab.push(e);(e=this.Ufc.Pa())&&e.Ir()};g.Hva=function(){0==this.mc()&&
this.ab.push(new c.yNa(this));return this.lr(0)};g.bk=function(){this.ab=[];var a=this.Ufc.Pa();a&&a.Ir()};g.yr=function(a){if(null==this.lr(a))throw e.DE(a,this.ab.length);this.ab.splice(a,1)};g.yTc=function(a){for(var b=!1,c=0;c<this.mc()&&!(b=this.lr(c).yh()==a);c++);b&&this.yr(c)};e.jb(c.oeb,"PRIM_SOND","Files",{Oa:{Item:{a:function(a){return this.lr(e.K(a)-1)}}},jc:{Add:g.oh,RemoveAll:g.bk,Remove:function(a){return this.yr(e.K(a)-1)}},gq:{Cp:function(a){return this.lr(e.K(a)-1)},Qv:function(){return this.mc()}},
lg:{hg:"Item"}});c.tZb=function(){q.w.call(this);this.Y0=0;this.L0=this.j2=!0;this.HS=1;this.sw=new c.oeb(this);this.Nh=-1;this.Gga=this.Iga=this.mS=!1;this.GB=50};var q=c.u(c.tZb,c.Us);q.eh=function(){return c.H0b};q.U=function(){q.j.U.call(this)};q.yh=function(){return 0<this.sw.mc()?this.sw.lr(0).yh():""};q.fw=function(b){this.sw.bk();var c=this.sw.Hva();c.yh()!=b&&(c.fw(b),(b=this.Pa())&&b.Ir(),this.l(a.f.h))};q.lY=function(){return 0<this.sw.mc()?this.sw.lr(0).lY():""};q.k_=function(b){var c=
this.sw.Hva();c.lY()!=b&&(c.k_(b),(b=this.Pa())&&b.Ir(),this.l(a.f.h))};q.pzc=function(){return this.sw};q.A6a=function(){return this.Y0};q.Ckb=function(b){this.Y0!=b&&(this.Y0=b,(b=this.Pa())&&b.Ir(),this.l(a.f.h))};q.g7a=function(){return this.mS};q.X7a=function(){return this.j2};q.Xlb=function(b){this.j2!=b&&(this.j2=b,(b=this.Pa())&&b.Ir(),this.l(a.f.h))};q.U5a=function(){return this.L0};q.gkb=function(b){this.L0!=b&&(this.L0=b,(b=this.Pa())&&b.Ir(),this.l(a.f.h))};q.G3=function(){return this.Nh};
q.h7a=function(){return this.Iga};q.f7a=function(){return this.Gga};q.X8a=function(){return this.GB};q.uBa=function(c){c=b.Pg(c,0,100);this.GB!=c&&(this.GB=c,this.mS=0==this.GB,(c=this.Pa())&&c.Ir(),this.l(a.f.h))};q.bCc=function(){return this.HS};q.Olb=function(b){this.HS!=b&&(this.HS=b,(b=this.Pa())&&b.Ir(),this.l(a.f.h))};q.Play=function(){this.Pa()&&this.Pa().Play()};q.Wh=function(){this.Pa()&&this.Pa().Wh()};q.rhb=function(){this.uBa(0)};e.kd(c.tZb,"PRIM_SOND",{Oa:{FileName:{a:q.yh,g:function(a){this.fw(e.ma(a))}},
CycleToStart:{a:q.A6a,g:function(a){this.Ckb(e.ya(a))}},ShowControls:{a:q.X7a,g:function(a){this.Xlb(e.ya(a))}},Autoplay:{a:q.U5a,g:function(a){this.gkb(e.ya(a))}},Preload:{a:function(){return e.ta(this.HS,p)},g:function(a){this.Olb(e.ra(a,p))}},Duration:{a:q.G3},IsMuted:{a:q.g7a},IsPlaying:{a:q.h7a},IsEnded:{a:q.f7a},Volume:{a:q.X8a,g:function(a){this.uBa(e.K(a))}}},jc:{Play:q.Play,Stop:q.Wh,Mute:q.rhb}});c.H0b=function(a){f.w.call(this,a)};var f=c.u(c.H0b,c.jn);f.lf=function(b,c){this.H=document.createElement("audio");
this.zDa=b+this.gc;this.H.setAttribute("id",this.zDa);this.H.setAttribute("LANSAHandle",this.gc);this.H.style.position="absolute";this.H.style.overflow="hidden";this.H.style.whiteSpace="nowrap";this.Ir();var e=this.H,g=this;e.addEventListener("loadedmetadata",function(){g.pa.Nh=e.duration;g.pa.Ha(a.J.SSb)},!1);e.addEventListener("loadeddata",function(){g.pa.Ha(a.J.RSb)},!1);e.addEventListener("play",function(){g.pa.Iga=!0;g.pa.Gga=!1;g.pa.Ha(a.J.Q2b)},!1);e.addEventListener("pause",function(){g.pa.Iga=
!1;g.pa.Ha(a.J.g9b)},!1);e.addEventListener("ended",function(){g.H.pause();g.H.paused=!0;g.pa.Gga=!0;g.pa.Ha(a.J.AA)},!1);e.addEventListener("volumechange",function(){e.muted||0==e.volume?(g.H.muted=!0,g.pa.mS=!0,g.pa.GB=0,g.pa.Ha(a.J.P1b)):(g.pa.mS=!1,g.pa.GB=Math.round(100*e.volume))},!1);return f.j.lf.call(this,b,c)};f.Ir=function(){this.Yna("controls",this.pa.j2);this.Yna("autoplay",this.pa.L0);this.Yna("loop",this.pa.Y0);this.H.setAttribute("preload",e.ta(this.pa.HS,l));this.H.volume=0<this.pa.GB?
this.pa.GB/100:0;this.H.muted=this.pa.mS;this.erb()};f.erb=function(){this.mjb();var a=this.pa.sw.mc();if(0!=a)for(var b=0;b<a;b++){var c=this.pa.sw.lr(b);this.cic(this.H,c.Ds,c.x1)}};f.cic=function(a,b,c){var e=document.createElement("source");e.src=b;c&&(e.type="audio/"+c);a.appendChild(e)};f.mjb=function(){var a=document.getElementById(this.zDa);if(a&&(a=a.childNodes)){var b,c,e=[];for(c=0;c<a.length;c++)b=a[c],"SOURCE"==b.nodeName&&e.push(b);for(c=0;c<e.length;c++)b=e[c],b.parentNode.removeChild(b)}};
f.zM=function(){return!1};f.EOa=function(){};f.Play=function(){this.H.play!==m&&this.H.play()};f.Wh=function(){this.H.pause!==m&&this.H.pause()}});
