window.LANSA.addSrc("http",function(e,c,a,b,m){c.dgb=function(){p.w.call(this);this.bb=this.mvb=""};var p=c.u(c.dgb,c.wd);p.U=function(){p.j.U.call(this)};p.dka=function(){return this.mvb};p.m7b=function(a){this.mvb=a};p.Ja=function(){return this.bb};p.Wa=function(a){this.bb=a};e.jb(c.dgb,"PRIM_WEB","HttpHeader",{Oa:{Key:{a:p.dka,g:function(a){this.m7b(e.ma(a))}},Value:{a:p.Ja,g:function(a){this.Wa(e.ma(a))}}}});c.lOa=function(){l.w.call(this);this.ab=[]};var l=c.u(c.lOa,c.wd);l.mc=function(){return this.ab.length};
l.Td=function(a){for(var c=0;c<this.mc();c++){var d=this.lr(c);if(b.zC(d.dka(),a))return d}return null};l.lr=function(a){if(0>a||a>=this.ab.length)throw e.DE(a,this.ab.length);return this.ab[a]};l.oh=function(a,b){var d=new c.dgb;d.m7b(a);d.Wa(b);this.ab.push(d)};l.bk=function(){this.ab=[]};l.Ys=function(a){for(var b=!1,c=0;c<this.mc()&&!(b=this.lr(c).dka()==a);c++);b&&this.ab.splice(c,1)};e.jb(c.lOa,"PRIM_WEB","HttpHeaders",{Oa:{Item:{a:function(a){return this.Td(a)}},ItemCount:{a:l.mc}},jc:{Add:l.oh,
Remove:l.Ys,RemoveAll:l.bk},lg:{hg:"Item"},gq:{Cp:function(a){return this.lr(e.K(a-1))},Qv:l.mc}});a.AG={a:1,rGc:2,$Qc:3,MSc:4,er:5,Zad:6,$Pc:7,imc:8,mQc:9};a.AG.v={GET:a.AG.a,HEAD:a.AG.rGc,POST:a.AG.$Qc,PUT:a.AG.MSc,DELETE:a.AG.er,TRACE:a.AG.Zad,OPTIONS:a.AG.$Pc,CONNECT:a.AG.imc,PATCH:a.AG.mQc};a.qJ={U1b:1,j4b:2,Q2:3,XX:4,Kzb:5};a.qJ.v={NOTEXECUTED:a.qJ.U1b,PROCESSING:a.qJ.j4b,COMPLETED:a.qJ.Q2,FAILED:a.qJ.XX,CANCELLED:a.qJ.Kzb};c.r0b=function(){s.w.call(this);this.d_a="";this.C1=null;this.qYa=a.AG.a;
this.qsa=null;this.rK=new c.lOa;this.Eha=a.qJ.U1b;this.Bxb=0;this.rfc=!1;this.Mh=null};var s=c.u(c.r0b,c.wd);s.U=function(){this.C1=null;this.Qlb(null);this.Mh&&(this.Mh.xb(),this.Mh=null);s.j.U.call(this)};s.rb=function(){null==this.Mh&&(this.Mh=e.Rt(new c.sOa("")),this.Mh.Ba());return this.Mh};s.IA=function(){return this.d_a};s.V2c=function(a){this.d_a=a};s.Ftd=function(){return this.qYa};s.L0c=function(a){this.qYa=a};s.Z6a=function(){return this.rK};s.CCc=function(){return this.qsa};s.Qlb=function(a){null!=
this.qsa&&this.qsa.xb();this.qsa=a;null!=this.qsa&&this.qsa.Ba()};s.jwd=function(){return this.Eha};s.aEc=function(){return this.Bxb};s.F2c=function(a){this.Bxb=a};s.Hsd=function(){return this.rfc};s.SKd=function(a){this.rfc=a};s.i9b=function(f,k){var d=this;d.Qlb(null);var h=d.C1=new XMLHttpRequest,g=e.ta(d.qYa,a.AG.v),l=d.IA();h.onreadystatechange=function(){4==h.readyState?(d.Qlb(e.Rt(new c.egb(h))),0!==h.status&&(d.Eha=a.qJ.Q2,d.Ha(a.J.Q2),b.wy(k))):d.Eha=a.qJ.j4b};h.onerror=function(){d.Eha=
a.qJ.XX;d.Ha(a.J.XX);b.wy(k)};h.ontimeout=function(){d.Eha=a.qJ.XX;d.Ha(a.J.XX);b.wy(k)};h.open(g,l,f);f&&(h.timeout=this.Bxb);this.Thc(h);g="";null!=this.Mh&&(g=this.Mh.Bq());h.send(g)};s.zta=function(){this.C1!==m&&(this.C1.abort(),this.Eha=a.qJ.Kzb)};s.QT=function(){this.i9b(!1,null)};s.s$=function(){this.i9b(!0,b.lR())};s.Thc=function(a){var b=this.rK.mc();if(0!=b)for(var c=0;c<b;c++){var e=this.rK.lr(c);a.setRequestHeader(e.dka(),e.Ja())}};e.jb(c.r0b,"PRIM_WEB","HttpRequest",{Oa:{Url:{a:s.IA,
g:function(a){this.V2c(e.ma(a))}},Method:{a:function(){return e.ta(this.qYa,a.AG.v)},g:function(b){this.L0c(e.ra(b,a.AG.v))}},Content:{a:s.rb},Response:{a:s.CCc},Headers:{a:s.Z6a},Status:{a:function(){return e.ta(this.Eha,a.qJ.v)}},Timeout:{a:s.aEc,g:function(a){this.F2c(e.K(a))}}},jc:{Cancel:s.zta,Execute:s.QT,ExecuteAsync:s.s$}});c.egb=function(a){g.w.call(this);this.C1=a;this.rK=new c.lOa;this.Mh=null;this.nNc(a.getAllResponseHeaders())};var g=c.u(c.egb,c.wd);g.U=function(){this.C1=null;this.Mh&&
(this.Mh.xb(),this.Mh=null);g.j.U.call(this)};g.rb=function(){null==this.Mh&&(this.Mh=e.Rt(new c.sOa(this.C1.responseText)),this.Mh.Ba());return this.Mh};g.uDc=function(){return this.C1.status};g.vDc=function(){return this.C1.statusText};g.Z6a=function(){return this.rK};g.nNc=function(a){for(var b=0,c="",e="";""!=a;){b=a.indexOf(":");if(-1==b)break;c=a.substring(0,b);a=a.slice(b+2);b=a.indexOf("\r\n");e=a.substring(0,b);a=a.slice(b+2);this.rK.oh(c,e)}};e.jb(c.egb,"PRIM_WEB","HttpResponse",{Oa:{Content:{a:g.rb},
StatusCode:{a:g.uDc},StatusText:{a:g.vDc},Headers:{a:g.Z6a}}});c.sOa=function(a){q.w.call(this);this.Mg=a};var q=c.u(c.sOa,c.wd);q.Bq=function(){return this.Mg};q.$M=function(a){this.Mg=a};e.jb(c.sOa,"PRIM_WEB","HttpContent",{Oa:{Text:{a:q.Bq,g:function(a){this.$M(e.ma(a))}}},lg:{hg:"Text"}})});
