window.LANSA.addSrc("imag",function(e,c,a,b){c.Yt=function(){m.w.call(this);this.Ds="";this.Xb=this.gb=this.lv=this.UVa=this.TR=this.xe=this.bf=null;this.IW=a.je.ASa;this.mB=this.yB=this.uB=this.FB=0;this.Qc|=a.$b.CMa;this.EEa=new c.hn;this.EEa.Ef(!1);this.EEa.Na(this);this.xe=new c.CQ;this.bf=new c.pb;this.bf.xd(this.xe);this.EEa.Dda(this.bf);this.Ef(!1)};var m=c.u(c.Yt,c.hn);m.vb=function(){b.la(this.xe);this.xe=null;b.la(this.bf);this.bf=null;m.j.vb.call(this)};m.U=function(){m.j.U.call(this);
this.coa(null);this.UVa=null;this.vj(null);this.lo(null)};m.yh=function(){return this.Ds};m.fw=function(c){b.zC(this.Ds,c)||(this.Ds=c,this.coa(b.tma(this.Ds)),this.l(a.f.h))};m.Upd=function(){return this.TR};m.coa=function(b){this.TR!=b&&(this.vj(null),null!=this.TR&&this.TR.Ca(this,this.hDb),this.TR=b,null!=this.TR&&this.TR.Ea(this,this.hDb),this.UJ(),this.nb(),this.l(a.f.h))};m.f6a=function(){return this.lv};m.vj=function(b){this.lv!=b&&(this.coa(null),null!=this.lv&&(this.lv.Ca(this,this.Rm),
this.lv.xb()),this.lv=b,null!=this.lv&&(this.lv.Ba(),this.lv.Ea(this,this.Rm)),this.UJ(),this.nb(),this.Kd(),this.l(a.f.h))};m.M3=function(){return this.xe.Pk()};m.r_=function(b){this.xe.Pk()!=b&&(this.xe.tg(b),this.l(a.f.h))};m.sY=function(){return this.xe.Vd()};m.q_=function(b){this.xe.Vd()!=b&&(this.xe.Ta(b),this.l(a.f.h))};m.uY=function(){return this.xe.ve()};m.s_=function(b){this.xe.ve()!=b&&(this.xe.Ua(b),this.l(a.f.h))};m.dU=function(){return this.xe.Xa()};m.UM=function(b){this.xe.Xa()!=b&&
(this.xe.ac(b),this.l(a.f.h))};m.Iw=function(){return this.xe.Qa()};m.Wu=function(b){this.xe.Qa()!=b&&(this.xe.yc(b),this.l(a.f.h))};m.AL=function(){return this.IW};m.FJ=function(b){this.IW!=b&&(this.IW=b,this.xe.Qb(b),this.nb(),this.Kd(),this.l(a.f.h))};m.tY=function(){return this.xe.qU()};m.YQ=function(b){this.xe.qU()!=b&&(this.xe.r6(b),this.l(a.f.h))};m.vY=function(){return this.xe.Oi()};m.t_=function(b){this.xe.Oi()!=b&&(this.xe.Sl(b),this.l(a.f.h))};m.lG=function(){return this.xe.Rf()};m.OE=
function(b){this.xe.Rf()!=b&&(this.xe.yb(b),this.l(a.f.h))};m.Bg=function(b){this.gb!=b&&(this.lo(b),this.l(a.f.h))};m.hb=function(){var a=null;return a=this.gb};m.cc=function(){return this.Xb};m.Xe=function(){return this.FB};m.Ge=function(c){this.FB!=c&&(this.FB=c,this.nb(),this.Kd(),b.cb().Bd(this,!1),this.ca(a.f.h))};m.cf=function(){return this.uB};m.re=function(c){this.uB!=c&&(this.uB=c,this.nb(),this.Kd(),b.cb().Bd(this,!1),this.ca(a.f.h))};m.Sf=function(){return this.yB};m.Ud=function(c){this.yB!=
c&&(this.yB=c,this.nb(),this.Kd(),b.cb().Bd(this,!1),this.ca(a.f.h))};m.kg=function(){return this.mB};m.Se=function(c){this.mB!=c&&(this.mB=c,this.nb(),this.Kd(),b.cb().Bd(this,!1),this.ca(a.f.h))};m.Xl=function(a,b,c,e,q){return q};m.VK=function(){var a=this.Xb.Wj();""!=a?this.TR&&this.TR.yh()==a||this.coa(b.tma(a)):this.coa(this.Xb.Jka());this.gb.HT(this.cc())};m.lo=function(a){var c=null;a&&(c=a.Ox(),this.gb==a?c.xn(this.Xb):a.iz(c));this.gb&&(this.gb.Ca(this),this.Xb.Ca(this),b.la(this.Xb),this.Xb=
null);if(this.gb=a)this.gb.Ea(this,this.Wn),this.Xb=c,this.Xb.Ea(this,this.Hv);this.hh()};m.UJ=function(){null==this.lv?this.xe.$c(this.TR):this.UVa&&0<this.UVa.yh().length?this.xe.$c(this.UVa):this.xe.$c(this.lv)};m.Ze=function(b){var e=new c.ga(0,0,b.aa(),b.ba());m.j.Ze.call(this,b);e.Ua(e.O()+this.FB);e.Ta(e.Q()+this.uB);e.Ra(e.va-this.yB);e.Ga(e.ua-this.mB);this.EEa.oc(this);this.EEa.kb(e);this.AL()==a.je.ASa&&this.xe.Hc()&&(this.xe.Hc().Qa()>e.ba()||this.xe.Hc().Xa()>e.aa()?this.xe.Qb(a.je.hH):
this.xe.Qb(a.je.Xd))};m.GC=function(b){var e=this.Bp(),m=this.sr();if(0!=this.uY()||0!=this.sY()||100!=this.dU()||100!=this.Iw()||this.tY()!=a.Dt.gea||this.vY()!=a.gz.ffa||this.xe.Yg()==a.je.CBa)m=e=!1;if(e||m){var g=new c.ga;if(this.xe.Hc())switch(g.Ra(this.xe.Hc().Xa()),g.Ga(this.xe.Hc().Qa()),this.xe.Yg()){case a.je.hH:if(m&&!e&&0<b.aa()&&0<g.aa()){var q=b.aa()/g.aa();g.Ga(g.O()+g.ba()*q)}}e&&b.Ra(b.Q()+this.ea.nj()+this.uB+g.aa()+this.yB+this.ea.Jk());m&&b.Ga(b.O()+this.ea.Kk()+this.FB+g.ba()+
this.mB+this.ea.vm())}};m.Bf=function(a){b.Peb();return m.j.Bf.call(this,a)};m.Rm=function(b,c){switch(c.Ya){case a.f.sb:case a.f.Ob:this.vj(null);break;case a.f.h:this.nb(),this.Kd()}};m.hDb=function(b,c){switch(c.Ya){case a.f.sb:case a.f.Ob:this.coa(null);break;case a.f.h:this.nb()}};m.Wn=function(b,c){c.Ya==a.f.h?c.Vr==a.we.Vw?this.gb.iz(this.cc()):this.lo(this.gb):c.Ya==a.f.sb&&this.Bg(null)};m.Hv=function(b,c){c.Ya==a.f.h&&c.Vr==a.we.Vw&&this.VK()};e.kd(c.Yt,"PRIM_IMAG",{Oa:{FileName:{a:m.yh,
g:function(a){this.fw(e.ma(a))}},Image:{a:m.f6a,g:function(a){this.vj(a)}},ImageTile:{a:function(){return e.ta(this.tY(),a.Dt.v)},g:function(b){this.YQ(e.ra(b,a.Dt.v))}},ImageUnits:{a:function(){return e.ta(this.vY(),a.gz.v)},g:function(b){this.t_(e.ra(b,a.gz.v))}},ImageSizing:{a:function(){return e.ta(this.AL(),a.je.v)},g:function(b){this.FJ(e.ra(b,a.je.v))}},ImageOpacity:{a:m.M3,g:function(a){this.r_(e.K(a))}},ImageLeft:{a:m.sY,g:function(a){this.q_(e.K(a))}},ImageTop:{a:m.uY,g:function(a){this.s_(e.K(a))}},
ImageWidth:{a:m.dU,g:function(a){this.UM(e.K(a))}},ImageHeight:{a:m.Iw,g:function(a){this.Wu(e.K(a))}},ImageAlignment:{a:function(){return e.ta(this.lG(),a.ie.v)},g:function(b){this.OE(e.ra(b,a.ie.v))}},DataClass:{a:m.hb,g:m.Bg},MarginLeft:{a:m.cf,g:function(a){this.re(e.K(a))}},MarginTop:{a:m.Xe,g:function(a){this.Ge(e.K(a))}},MarginBottom:{a:m.kg,g:function(a){this.Se(e.K(a))}},MarginRight:{a:m.Sf,g:function(a){this.Ud(e.K(a))}}}})});
