window.LANSA.addSrc("coll",function(e,c,a,b,n){a.vMa={Plc:0,Y4a:1};var q=0;c.Pla=function(){m.w.call(this)};var m=c.u(c.Pla,c.wd);m.Dyb=function(){return!1};m.LPb=function(){return!1};m.lc=function(){return 0};m.Zf=function(){return 0==this.lc()};m.yX=function(a){a&&(a.Ba(),a.Lhc(this))};m.NX=function(a){a&&(a.xb(),a.xTc(this))};m.LZ=function(a,b){this.uPa(b);null!=this.rS&&this.rS.LZ(a,b)};m.n5=function(a,b){this.vPa(b);null!=this.rS&&this.rS.n5(a,b)};e.kd(c.Pla,"PRIM_COLL",{Oa:{AllowsDuplicates:{a:function(){return this.Dyb()}},
IsEmpty:{a:function(){return this.Zf()}},IsOrdered:{a:function(){return this.LPb()}},ItemCount:{a:function(){return this.lc()}}}});c.tNa=function(){s.w.call(this);this.ab=[];this.rS=null};var s=c.u(c.tNa,c.Pla);s.U=function(){this.Yj();s.j.U.call(this)};s.Dyb=function(){return!0};s.LPb=function(){return!0};s.lc=function(){return this.ab.length};s.Td=function(a){if(0>a||a>=this.ab.length)throw e.yE(a,this.ab.length);return this.ab[a]};s.jl=function(a,b){if(0>a||a>this.ab.length)throw e.yE(a,this.ab.length);
a==this.ab.length?this.gs(b):this.ljb(b,a)};s.Y6a=function(a,b){return b===n?this.ab.indexOf(a):this.ab.indexOf(a,b)};s.EKb=function(a){return this.ab.lastIndexOf(a)+1};s.Q6a=function(){return 0<this.ab.length?this.ab[0]:null};s.j7a=function(){return 0<this.ab.length?this.ab[this.ab.length-1]:null};s.Fod=function(){return this.xfa};s.a_=function(a){this.xfa=a};s.JGa=function(a){this.a_(a.n4b())};s.oe=function(a){return-1!=this.ab.indexOf(a)};s.gs=s.JOb=function(a){this.yX(a);this.ab.push(a);this.LZ(a,
this.lc()-1)};s.IOb=function(a){this.yX(a);this.ab.unshift(a);this.LZ(a,0)};s.HOb=function(a,b){if(0>b||b>=this.ab.length)throw e.yE(b,this.ab.length);this.yX(a);this.ab.splice(b+1,0,a);this.LZ(a,b+1)};s.R$a=function(a,b){if(0>b||b>=this.ab.length)throw e.yE(b,this.ab.length);this.yX(a);this.ab.splice(b,0,a);this.LZ(a,b)};s.Xs=function(a){a=this.ab.indexOf(a);if(-1==a)throw e.XTc();return this.ur(a)};s.ur=function(a){if(0>a||a>=this.ab.length)throw e.yE(a,this.ab.length);var b=this.ab[a];this.ab.splice(a,
1);e.mia(b);this.NX(b);this.n5(b,a);return b};s.fjb=function(){return this.ur(0)};s.hjb=function(){return this.ur(this.ab.length-1)};s.Yj=function(){for(var a=0;a<this.ab.length;a++)this.NX(this.ab[a]);this.ab=[];this.Cca()};s.vhb=function(a){for(var b=0,c=0;c<this.ab.length;c++)this.ab[c]===a&&b++;return b};s.ljb=function(a,b){if(0>b||b>=this.ab.length)throw e.yE(b,this.ab.length);var c=this.ab[b];e.mia(c);this.NX(c);this.ab[b]=a;this.yX(a);return c};s.Dg=function(){var a=e.A2a(this.xfa);if(a=e.Xc(a.cPa,
a.Cqb))this.Cma(a),this.gs(a)};s.Qj=function(){this.Yj()};s.Oh=function(a){if(0<=a&&a<this.lc()){var b=this.Td(a);b&&this.Zba(b);this.ol=a;return"OK"}this.ol=-1;return"NR"};s.wo=function(){return this.lc()};s.Pm=function(a){a===n&&(a=this.ol);0<=a&&a<this.lc()&&this.ur(a)};s.ml=function(){var a=this.ol;0<=a&&a<this.lc()&&(a=this.Td(a))&&this.Cma(a)};s.Dn=function(a,b,c){for(var d=0;d<this.lc();d++){var e=this.Td(d);if(e&&(e=e.KY())){var f={},h;for(h in e)f[h]=e[h].get();if(a(f))return null!=b&&b.set(d+
1),c&&this.Oh(d),this.ol=d,"OK"}}return"NR"};s.Aq=function(a){this.Yj();for(var b=0;b<a;b++)this.Dg()};s.ms=function(){return new c.qeb(this)};s.nAa=function(){null==this.rS&&(this.rS=new c.FWb);return this.rS};c.FWb=function(){g.w.call(this)};var g=c.u(c.FWb,c.reb);c.AWb=function(){k.w.call(this);this.ol=-1};var k=c.u(c.AWb,c.tNa);k.ST=function(){return"PRIM_LCOL<"+this.xfa+">"};k.qic=function(a){for(var b=0;b<a.lc();b++)this.gs(a.Td(b))};k.bmc=function(a){for(var b=e.Xc("PRIM_LCOL"),c=0;c<this.lc();c++)b.gs(this.Td(c));
for(c=0;c<a.lc();c++)b.gs(a.Td(c));e.mia(b);return b};e.kd(c.AWb,"PRIM_LCOL",{nJ:a.Cv.L0a,Oa:{First:{a:function(){return this.Q6a()}},Last:{a:function(){return this.j7a()}},Item:{a:function(a){return this.Td(e.J(a)-1)},g:function(a,b){this.jl(e.J(a)-1,b)}},IndexOf:{a:function(a,b){return this.Y6a(a,b===n?n:e.J(b)-1)+1}},LastIndexOf:{a:k.EKb},Collects:{g:k.a_}},jc:{Append:k.qic,Concatenate:k.bmc,Contains:k.oe,Insert:k.gs,InsertFirst:k.IOb,InsertLast:k.JOb,InsertAfter:function(a,b){return this.HOb(a,
e.J(b)-1)},InsertBefore:function(a,b){return this.R$a(a,e.J(b)-1)},Remove:k.Xs,RemoveAt:function(a){return this.ur(e.J(a)-1)},RemoveFirst:k.fjb,RemoveLast:k.hjb,RemoveAll:k.Yj,OccurrencesOf:k.vhb,ReplaceAt:function(a,b){return this.ljb(a,e.J(b)-1)}},ig:{eg:"Item"},fq:{vba:function(a){var b=e.Xc("PRIM_NMBR");b.set(a);return b},Ap:function(a){return this.Td(e.J(a)-1)},Ov:function(){return this.lc()}},jy:{Dg:k.Dg,Oh:function(a){return this.Oh(e.J(a)-1)},Aq:k.Aq,Qj:k.Qj,wo:k.wo,Pm:function(a){return this.Pm(a?
e.J(a)-1:n)},ml:k.ml,Dn:k.Dn,ms:k.ms}});c.RSb=function(){f.w.call(this)};var f=c.u(c.RSb,c.tNa);f.ST=function(){return"PRIM_ACOL<"+this.xfa+">"};e.kd(c.RSb,"PRIM_ACOL",{nJ:a.Cv.L0a,Oa:{First:{a:function(){return this.Q6a()}},Last:{a:function(){return this.j7a()}},Item:{a:function(a){return this.Td(e.J(a)-1)},g:function(a,b){this.jl(e.J(a)-1,b)}},IndexOf:{a:function(a,b){return this.Y6a(a,b===n?n:e.J(b)-1)+1}},LastIndexOf:{a:f.EKb},Collects:{g:f.a_}},jc:{Contains:f.oe,Insert:f.gs,InsertFirst:f.IOb,
InsertLast:f.JOb,InsertAfter:function(a,b){return this.HOb(a,e.J(b)-1)},InsertBefore:function(a,b){return this.R$a(a,e.J(b)-1)},Remove:f.Xs,RemoveAt:function(a){return this.ur(e.J(a)-1)},RemoveFirst:f.fjb,RemoveLast:f.hjb,RemoveAll:f.Yj,OccurrencesOf:f.vhb,ReplaceAt:function(a,b){return this.ljb(a,e.J(b)-1)}},ig:{eg:"Item"},fq:{vba:function(a){var b=e.Xc("PRIM_NMBR");b.set(a);return b},Ap:function(a){return this.Td(e.J(a)-1)},Ov:function(){return this.lc()}},jy:{Dg:f.Dg,Oh:function(a){return this.Oh(e.J(a)-
1)},Aq:f.Aq,Qj:f.Qj,wo:f.wo,Pm:function(a){return this.Pm(a?e.J(a)-1:n)},ml:f.ml,Dn:f.Dn,ms:f.ms}});c.MWb=function(){l.w.call(this)};var l=c.u(c.MWb,c.tNa);l.gs=function(b){this.yX(b);for(var c=0,d=this.ab.length-1;c<=d;){var e=Math.floor((c+d)/2);this.Nuc(b,this.ab[e])==a.Nc.Vk?d=e-1:c=e+1}this.ab.splice(c,0,b)};l.Nuc=function(b,c){var d=a.Nc.hk,f=e.Tb();f.Wb("SUBJECT",b);f.Wb("OBJECT",c);f.PO("RESULT",d,a.Nc.v);this.Ha(a.K.jHa,f);d=f.N6a("RESULT",a.Nc.v);f.qc();return d};e.kd(c.MWb,"PRIM_SACO",
{Oa:{First:{a:function(){return this.Q6a()}},Last:{a:function(){return this.j7a()}},Item:{a:function(a){return this.Td(e.J(a)-1)},g:function(a,b){this.jl(e.J(a)-1,b)}},IndexOf:{a:function(a,b){return this.Y6a(a,b===n?n:e.J(b)-1)+1}},Collects:{g:l.a_}},jc:{Remove:l.Xs,RemoveAt:function(a){return this.ur(e.J(a)-1)},RemoveAll:l.Yj,RemoveLast:l.hjb,RemoveFirst:l.fjb,Contains:l.oe,OccurrencesOf:l.vhb,Insert:l.gs},ig:{eg:"Item"},fq:{vba:function(a){var b=e.Xc("PRIM_NMBR");b.set(a);return b},Ap:function(a){return this.Td(e.J(a)-
1)},Ov:function(){return this.lc()}}});c.qZ=function(a){d.w.call(this);this.Ifc=a};var d=c.u(c.qZ,c.Pla);d.Td=function(a){if(0>a||a>=this.lc())throw e.yE(a,this.lc());return this.Hw(a)};d.lc=function(){return this.Ifc.lc()};d.Hw=function(a){return this.Ifc.Hw(a)};e.kd(c.qZ,"PRIM_PCOL",{Oa:{Item:{a:function(a){return this.Td(e.J(a)-1)},g:function(a,b){this.jl(e.J(a)-1,b)}}},ig:{eg:"Item"},fq:{Ap:function(a){return this.Hw(e.J(a)-1)},Ov:function(){return this.lc()}}});c.zWb=function(){h.w.call(this);
this.ab={};this.lS=null;this.$e=a.vMa.Y4a};var h=c.u(c.zWb,c.Pla);h.U=function(){this.Yj();h.j.U.call(this)};h.ST=function(){return"PRIM_KCOL<"+this.zVa+" "+this.$zc()+">"};h.og=function(){return this.$e};h.tb=function(a){this.$e=a};h.lc=function(){return this.jca().length};h.Td=function(b){b=this.g1a(b);if(this.ab[b]===n&&this.$e==a.vMa.Y4a){var c=null;this.ptb?c=new this.ptb:this.zVa&&(c=e.A2a(this.zVa),c=e.Xc(c.cPa,c.Cqb));c&&(this.ab[b]=c,this.yX(c),this.NG())}return this.ab[b]};h.jl=function(a,
b){a=this.g1a(a);var c=a.toString();this.ab[c]===n?this.NG():this.NX(this.ab[c]);this.yX(b);this.ab[c]=b};h.Hw=function(a){a=this.jca()[a];return this.ab[a]};h.f7a=function(a){a=this.jca()[a];this.lS.set(a);return this.lS};h.g7a=function(a){for(var b in this.ab)if(this.ab[b]===a)return this.j1a(b);return this.lS.DBc()};h.a_=function(a,b){"string"!==typeof a?this.ptb=a:(this.zVa=a,this.ptb=b)};h.oRa=function(a){this.lS=new a;this.lS.Ba()};h.God=function(){return this.zVa};h.$zc=function(){var a="";
this.lS&&(a=this.lS.rva());return a};h.JGa=function(a){this.a_(a.n4b(),a.mAb(0));this.oRa(a.mAb(1))};h.g1a=function(a){this.lS.set(a);a=this.lS.get();return a.toString()};h.j1a=function(a){this.lS.set(a);return this.lS.get()};h.Xs=function(a){a=this.g1a(a);var b=null;this.ab[a]!==n&&(b=this.ab[a],e.mia(b),this.NX(b),delete this.ab[a],this.NG(),this.n5(b,0));return b};h.Yj=function(){for(var a in this.ab)this.NX(this.ab[a]);this.ab={};this.NG();this.Cca()};h.NG=function(){delete this.pF};h.jca=function(){var a=
this;if(this.pF===n){this.pF=[];for(var b in this.ab)this.pF.push(b);this.pF.sort(function(b,c){b=a.j1a(b);c=a.j1a(c);return e.cmp(b,c)})}return this.pF};var y={COLLECTION:a.vMa.Plc,FACTORY:a.vMa.Y4a};e.kd(c.zWb,"PRIM_KCOL",{Oa:{Style:{a:function(){return e.ta(this.og(),y)},g:function(a){this.tb(e.qa(a,y))}},Item:{a:function(a){return this.Td(a)},g:function(a,b){this.jl(a,b)},Bw:"na"},Collects:{g:h.a_},KeyedBy:{g:h.oRa},KeyOf:{a:function(a){return this.g7a(a)},Bw:"na"}},jc:{Remove:h.Xs,RemoveAll:h.Yj},
ig:{eg:"Item"},fq:{vba:function(a){return this.f7a(e.J(a)-1)},Ap:function(a){return this.Hw(e.J(a)-1)},Ov:function(){return this.lc()}}});c.RVb=function(){C.w.call(this);this.eS=(q++).toString();this.EH=[];this.xfa=this.rfc=""};var C=c.u(c.RVb,c.Pla);C.ST=function(){return"PRIM_DCOL<"+this.xfa+" "+this.rfc+">"};C.lc=function(){return this.EH.length};C.Hw=function(a){return this.EH[a].mH[this.eS]};C.Td=function(a){return a.mH===n||a.mH[this.eS]===n?null:a.mH[this.eS]};C.jl=function(a,b){a.mH===n&&
(a.mH={});var c=a.mH[this.eS];c===n?(this.EH.push(a),a.Ba()):this.NX(c);a.mH[this.eS]=b;this.yX(b)};C.f7a=function(a){return this.EH[a]};C.a_=function(a){this.xfa=a};C.oRa=function(a){this.rfc=a};C.g7a=function(a,b){for(var c=b;c<this.EH.length;c++){var d=this.EH[c];if(d.mH[this.eS]===a)return d}return null};C.uuc=function(a){return this.Td(a)};C.oe=function(a){return-1!=this.EH.indexOf(a)};C.gmc=function(a){for(var b=0;b<this.EH.length;b++)if(this.EH[b].mH[this.eS]===a)return!0;return!1};C.gs=function(a,
b){var c=this.Td(b);this.jl(b,a);return c};C.Xs=function(a){if(a.mH!==n){var b=a.mH[this.eS];if(b!==n)return delete a.mH[this.eS],this.EH.splice(this.EH.indexOf(a),1),e.mia(b),this.NX(b),a.xb(),this.n5(b,0),b}return null};C.Yj=function(){for(var a=0;a<this.EH.length;a++){var b=this.EH[a],c=b.mH[this.eS];c!==n&&(delete b.mH[this.eS],this.NX(c))}this.EH=[];this.Cca()};e.kd(c.RVb,"PRIM_DCOL",{Oa:{Item:{a:function(a){return this.Td(a)},g:function(a,b){this.jl(a,b)},Bw:"na"},Collects:{g:C.a_,Bw:"na"},
KeyedBy:{g:C.oRa,Bw:"na"},KeyOf:{a:function(a,b){return this.g7a(a,b!==n?e.J(b)-1:0)},Bw:"na"}},jc:{Contains:C.oe,ContainsItem:C.gmc,Insert:C.gs,Remove:C.Xs,RemoveAll:C.Yj,Find:C.uuc},ig:{eg:"Item"},fq:{vba:function(a){return this.f7a(e.J(a)-1)},Ap:function(a){return this.Hw(e.J(a)-1)},Ov:function(){return this.lc()}}})});
