window.LANSA.addSrc("msg",function(e,c,a,b,n){e.Gb("PRIM_PPNL");a.Jma={X4:0,TOc:1,VOc:2,QOc:4,ROc:8};a.Jma.v={NONE:a.Jma.X4,TEXT:a.Jma.TOc,WARNING:a.Jma.VOc,ERROR:a.Jma.QOc,FATAL:a.Jma.ROc};a.AZ={p1b:1,r1b:2,q1b:4};a.AZ.v={ERROR:a.AZ.p1b,QUESTION:a.AZ.r1b,INFORMATION:a.AZ.q1b};a.lp={Egd:16,h0a:1,TGa:16,QGa:32,VGa:64,SGa:128,UGa:256,RGa:512};a.lp.v={NONE:a.lp.h0a,OK:a.lp.TGa,CANCEL:a.lp.QGa,YES:a.lp.VGa,NO:a.lp.SGa,RETRY:a.lp.UGa,IGNORE:a.lp.RGa};a.EG={Fgb:16,t1b:48,u1b:192,v1b:224,s1b:768};a.EG.v=
{OK:a.EG.Fgb,OKCANCEL:a.EG.t1b,YESNO:a.EG.u1b,YESNOCANCEL:a.EG.v1b,IGNORERETRY:a.EG.s1b};c.CWb=function(){q.w.call(this)};var q=c.u(c.CWb,c.wd);e.kd(c.CWb,"PRIM_MSG",{});c.wdb=function(){m.w.call(this);this.kD=[]};var m=c.u(c.wdb,c.wd);m.nBc=function(){e.Gb("PRIM_PCOL");var a=new c.GUb(this);return new c.qZ(a)};m.nh=function(a,b){var e=new c.xdb(this,a);this.kD.push(e);e.Ti(b);this.Xuc(e);return e};m.np=function(a){if(a)for(var b=0;b<this.kD.length;b++){var c=this.kD[b];c.ha()==a&&(this.BIb(c),this.kD.splice(b--,
1),c.eCb())}};m.Clc=function(){for(;0<this.kD.length;){var a=this.kD.shift();this.BIb(a);a.eCb()}};m.Xuc=function(b){var c=e.Tb();c.Wb("MESSAGE",b);this.Ha(a.K.AOc,c);c.qc()};m.BIb=function(b){var c=e.Tb();c.Wb("MESSAGE",b);this.Ha(a.K.BOc,c);c.qc()};e.kd(c.wdb,"PRIM_MSGQ",{Oa:{Messages:{a:m.nBc}},jc:{Add:function(a,b){return this.nh(e.ma(a),b===n?null:b)},Clear:function(a){return this.np(a===n?null:a)},ClearAll:function(){return this.Clc()}}});c.GUb=function(a){s.w.call(this);this.aFa=a};var s=c.u(c.GUb,
c.Mba);s.lc=function(){return this.aFa.kD.length};s.Hw=function(a){return this.aFa.kD[a]};c.xdb=function(a,b){g.w.call(this);this.aFa=a;this.Ig=b;this.eb=null};var g=c.u(c.xdb,c.wd);g.zq=function(){return this.Ig};g.ha=function(){return this.eb};g.Ti=function(a){this.pg()&&this.eb!=a&&(null!=this.eb&&(this.eb.AM(this),this.eb.Ca(this,this.Ms)),this.eb=a)&&(a.MK(this),a.Da(this,this.Ms))};g.pg=function(){return null!==this.aFa};g.eCb=function(){this.Ti(null);this.Ig="";this.aFa=null};g.Ms=function(b,
c){switch(c.Ya){case a.f.sb:this.Ti(null)}};e.jb(c.xdb,"PRIM_MSGQ","Message",{Oa:{Text:{a:g.zq},Control:{a:g.ha,g:g.Ti}}});c.G_b=function(){k.w.call(this);this.Mqa=[]};var k=c.u(c.G_b,c.wd);k.U=function(){this.Yj();k.j.U.call(this)};k.Td=function(a){return this.Mqa[a]};k.lc=function(){return this.Mqa.length};k.nh=function(b){this.Mqa.push(b);this.l(a.f.h)};k.Yj=function(){this.Mqa=[];this.l(a.f.h)};k.SAc=function(){for(var a="",b=0;b<this.Mqa.length;b++){var c=this.Mqa[b];c.length>a.length&&(a=c)}return a};
e.jb(c.G_b,"PRIM_WEB","MessageBoxCaptions",{jc:{Add:k.nh,RemoveAll:k.Yj}});c.F_b=function(){f.w.call(this);e.Gb("PRIM_PHBN");e.Gb("PRIM_LABL");this.LFa=this.N8=this.Vha=null;this.$Ea=a.AZ.q1b;this.jB=a.EG.Fgb;this.Se=a.lp.h0a;this.sVa=[];this.OR=null;this.NZa=new c.Us;this.MZa=new c.zQ;this.sD=new c.dn;this.uH=e.Xc("PRIM_WEB","MessageBoxCaptions");this.uH.Ba();this.uH.Da(this,this.PCb);this.Mf=new c.Xeb;this.oN=new c.zQ;this.GH=new c.zQ;this.KK=new c.zQ;this.WN=new c.zQ;this.fO=new c.zQ;this.nK=new c.zQ;
this.GH.za(this,a.K.bc,this.zqc);this.oN.za(this,a.K.bc,this.Loc);this.KK.za(this,a.K.bc,this.qsc);this.WN.za(this,a.K.bc,this.xqc);this.fO.za(this,a.K.bc,this.drc);this.nK.za(this,a.K.bc,this.Zpc);this.sD.Na(this);this.Mf.Na(this);this.oN.Na(this);this.GH.Na(this);this.KK.Na(this);this.WN.Na(this);this.fO.Na(this);this.nK.Na(this);this.N8=new c.pb;this.LFa=new c.wg;this.N8.xd(this.LFa);this.LFa.Ed(a.m.jR);this.LFa.qg(9);this.b8b(this.N8);this.N8.Ba();this.LFa.Ba();this.sD.Ta(90);this.sD.Cf(!1);this.sD.Ua(57);
this.sD.Ib(!0);this.sD.gR(!0);this.sD.j_(!0);this.Mf.bf(6);this.Mf.JE(a.Ug.oq);this.Mf.Ta(20);this.Mf.Ua(57);this.Mf.Uu(64);this.Mf.OM(64);this.Mf.wc(64);this.Mf.ac(64);this.Mf.Cf(!1);this.GH.Cb(b.Ao().ok||"OK");this.WN.Cb(b.Ao().no||"No");this.KK.Cb(b.Ao().yes||"Yes");this.fO.Cb(b.Ao().retry||"Retry");this.oN.Cb(b.Ao().cancel||"Cancel");this.nK.Cb(b.Ao().ignore||"Ignore");this.w6b(this.jB);this.GQa(!1);this.gmb(!0)};var f=c.u(c.F_b,c.Vw);f.U=function(){this.uH.Ca(this,this.PCb);this.uH.xb();this.uH=
null;this.yBb();f.j.U.call(this)};f.gZc=function(a){this.NZa.tb(a)};f.zwc=function(){return this.NZa.og()};f.Awc=function(){return this.NZa.Tj()};f.zja=function(){return this.MZa.og()};f.RG=function(a){this.MZa.tb(a)};f.twc=function(){return this.MZa.Tj()};f.mBa=function(b){b!=this.mU()&&(this.Cb(b),this.zUa(),this.l(a.f.h))};f.mU=function(){return this.ob()};f.A0c=function(b){this.uH.Yj();b!=this.SKb()&&(this.uH.nh(b),this.l(a.f.h))};f.Cwc=function(){return this.uH};f.SKb=function(){return 0<this.uH.lc()?
this.uH.Td(0):""};f.M6b=function(b){this.OR!==b&&(null!=this.OR&&(this.OR.Ca(this,this.dDb),this.OR.xb()),this.OR=b,null!==this.OR&&(this.OR.Ba(),this.OR.Da(this,this.dDb)),this.zUa(),this.l(a.f.h))};f.yxc=function(){return this.OR};f.B0c=function(b){this.$Ea!=b&&(this.$Ea=b,this.zUa(),this.l(a.f.h))};f.utd=function(){return this.$Ea};f.w6b=function(b){this.jB=b;this.GH.Ib(0!=(this.jB&a.lp.TGa));this.oN.Ib(0!=(this.jB&a.lp.QGa));this.KK.Ib(0!=(this.jB&a.lp.VGa));this.WN.Ib(0!=(this.jB&a.lp.SGa));
this.nK.Ib(0!=(this.jB&a.lp.RGa));this.fO.Ib(0!=(this.jB&a.lp.UGa))};f.dod=function(){return this.jB};f.jLd=function(a){this.Se=a};f.fvd=function(){return this.Se};f.$mc=function(b,e,f){var g=new c.Us;g.Na(this.sD);g.Ta(0);g.Cf(!1);g.Ua(e);g.Kn(a.Ug.oq);g.ac(f.Xa());g.wc(f.Qa());g.Qe(!1);g.Cb(b);return g};f.U8b=function(a,e){var f=b.Uw(0,0),g=new c.ga(0,0,0,0);b.tC(a,g,0,e);f.ac(g.aa()+2);f.wc(g.ba()+2);return f};f.kCc=function(){if(null!=this.OR)return this.OR;var d="";switch(this.$Ea){case a.AZ.p1b:d=
"lansa_error.png";break;case a.AZ.r1b:d="lansa_question.png";break;default:d="lansa_information.png"}var e=new c.bM;e.cw(b.sc(d));return e};f.wic=function(){var a=this.MZa.Tj().$a.ZD(),b=null;this.GH.Tj().Yj();this.oN.Tj().Yj();this.KK.Tj().Yj();this.WN.Tj().Yj();this.fO.Tj().Yj();this.nK.Tj().Yj();for(var c=0;null!=a&&c<a.length&&null!=(b=a[c]);c++)this.GH.Tj().nh(b),this.oN.Tj().nh(b),this.KK.Tj().nh(b),this.WN.Tj().nh(b),this.fO.Tj().nh(b),this.nK.Tj().nh(b);this.GH.Wj(!1,!0);this.oN.Wj(!1,!0);
this.KK.Wj(!1,!0);this.WN.Wj(!1,!0);this.fO.Wj(!1,!0);this.nK.Wj(!1,!0)};f.Cic=function(){var a=this.NZa.Tj().$a.ZD(),b=null;this.sD.Tj().Yj();for(var c=0;null!=a&&c<a.length&&null!=(b=a[c]);c++)this.sD.Tj().nh(b);this.sD.Wj(!1,!0)};f.roa=function(){this.Vha=b.hR();this.Se=a.lp.h0a;this.EAb();var c=b.wm();this.Ez(a.Si.k5,null,c,null);this.e_c()};f.zUa=function(){this.SL()&&(this.EAb(),this.fh())};f.EAb=function(){var a;this.yBb();this.Mf.$c(this.kCc());this.wic();this.Cic();a=this.zyb();this.yQc(a)};
f.iAa=function(){this.zyb();f.j.iAa.call(this)};f.zyb=function(){var a=this.oA(),b=this.Ykc(),c=this.dlc(),c=this.clc(c),e=this.$kc(a),f=this.Zkc(b),g=this.flc(c,e,f);this.NUc(g,b,e);this.dic(b,c,f,g);return a};f.NUc=function(a,b,c){this.ac(a.Xa());this.wc(a.Qa());a=b.Xa();b=b.Qa();this.oN.ac(a);this.GH.ac(a);this.KK.ac(a);this.WN.ac(a);this.fO.ac(a);this.nK.ac(a);this.oN.wc(b);this.GH.wc(b);this.KK.wc(b);this.WN.wc(b);this.fO.wc(b);this.nK.wc(b);this.sD.ac(c.Xa());this.sD.wc(c.Qa())};f.dic=function(a,
b,c,e){this.eZc(a);a=e.Qa()-c.Qa();this.oN.Ua(a);this.GH.Ua(a);this.KK.Ua(a);this.WN.Ua(a);this.fO.Ua(a);this.nK.Ua(a);this.Mf.Ta(20);this.Mf.Ua(this.Zq.Qa()+20);this.sD.Ta(40+b.Xa());this.sD.Ua(this.Zq.Qa()+20)};f.flc=function(a,c,e){var f=b.qE(),g=b.Uw(0,0);a=this.blc(a,c);c=this.gA.kLa(this.gA.ob(),this.gA.xn().length)+10;g.ac(Math.max(a.Xa(),c,e.Xa())+60);g.wc(this.Zq.Qa()+a.Qa()+e.Qa()+40);g.ac(Math.min(f.aa()-40,g.Xa()));g.wc(Math.min(f.ba()-40,g.Qa()));return g};f.cka=function(a,b){var c=a;
b.length>a.length&&(c=b);return c};f.RAc=function(){var a="",a=this.cka(this.GH.ob(),a),a=this.cka(this.oN.ob(),a),a=this.cka(this.KK.ob(),a),a=this.cka(this.WN.ob(),a),a=this.cka(this.fO.ob(),a),a=this.cka(this.nK.ob(),a);return" "+a+" "};f.Ykc=function(){var a=this.RAc(),c=b.Uw(0,0),c=this.GH.ke();return c=this.U8b(a,c)};f.oA=function(){var a=this.uH.SAc(),c=b.Uw(0,0),c=this.sD.ke();return c=this.U8b(a,c)};f.dlc=function(){var a=b.Uw(0,0);a.ac(this.Mf.Xa());a.wc(this.Mf.Qa());return a};f.$kc=function(a){var c=
b.Uw(0,0),e=a.Xa()+4;a=this.uH.lc()*(a.Qa()+4);e+=20;a+=20;e=170>e?170:e;a=70>a?70:a;a=630<a?630:a;c.ac(630<e?630:e);c.wc(a);return c};f.clc=function(a){var c=b.Uw(0,0);c.wc(a.Qa()+16);c.ac(a.Xa()+8);return c};f.blc=function(a,c){var e=b.Uw(0,0);e.wc(Math.max(a.Qa(),c.Qa()));e.ac(2+a.Xa()+2+c.Xa()+2);return e};f.Zkc=function(a){var c=b.Uw(0,0),e=66>a.Xa()?66:a.Xa(),f=25>a.Qa()?25:a.Qa();a.ac(e);a.wc(f);c.wc(a.Qa()+24);c.ac(3*a.Xa()+8);return c};f.eZc=function(b){b=b.Xa()+20;var c=1;this.jB&a.lp.UGa&&
(this.fO.Ta(this.Xa()-c*b),++c);this.jB&a.lp.RGa&&(this.nK.Ta(this.Xa()-c*b),++c);this.jB&a.lp.QGa&&(this.oN.Ta(this.Xa()-c*b),++c);this.jB&a.lp.TGa&&(this.GH.Ta(this.Xa()-c*b),++c);this.jB&a.lp.SGa&&(this.WN.Ta(this.Xa()-c*b),++c);this.jB&a.lp.VGa&&this.KK.Ta(this.Xa()-c*b)};f.yQc=function(a){for(var b=0,c=a.Qa(),e=0;e<this.uH.lc();e++)this.sVa.push(this.$mc(this.uH.Td(e),b,a)),b+=c};f.e_c=function(){switch(this.jB){case a.EG.Fgb:case a.EG.t1b:this.GH.Ye(!0,!0);break;case a.EG.u1b:case a.EG.v1b:this.KK.Ye(!0,
!0);break;case a.EG.s1b:this.nK.Ye(!0,!0)}};f.Ika=function(a){this.Se=a;this.Nm();b.ty(this.Vha);this.Vha=null};f.yBb=function(){for(var a=0;a<this.sVa.length;++a)this.sVa[a].Na(null);this.sVa=[]};f.PCb=function(){this.zUa()};f.zqc=function(){this.Ika(a.lp.TGa)};f.Loc=function(){this.Ika(a.lp.QGa)};f.qsc=function(){this.Ika(a.lp.VGa)};f.xqc=function(){this.Ika(a.lp.SGa)};f.drc=function(){this.Ika(a.lp.UGa)};f.Zpc=function(){this.Ika(a.lp.RGa)};f.dDb=function(b,c){switch(c.Ya){case a.f.sb:case a.f.Ob:this.M6b(null);
break;case a.f.h:this.l(a.f.h)}};e.jb(c.F_b,"PRIM_WEB","MessageBox",{Oa:{Title:{a:f.mU,g:function(a){this.mBa(e.ma(a))}},Caption:{a:f.SKb,g:function(a){this.A0c(e.ma(a))}},Text:{a:f.zq,g:function(a){this.VM(e.ma(a))}},Captions:{a:f.Cwc},Image:{a:function(){return e.ta(this.$Ea,a.AZ.v)},g:function(b){this.B0c(e.qa(b,a.AZ.v))}},CustomImage:{a:f.yxc,g:function(a){this.M6b(a)}},Result:{a:function(){return e.ta(this.Se,a.lp.v)}},Buttons:{a:function(){return e.ta(this.jB,a.EG.v)},g:function(b){this.w6b(e.qa(b,
a.EG.v))}},CaptionStyle:{a:f.zwc,g:function(a){this.gZc(a)}},CaptionStyles:{a:f.Awc},ButtonStyle:{a:f.zja,g:function(a){this.RG(a)}},ButtonStyles:{a:f.twc}},jc:{Show:f.roa}});c.Keb=function(b){l.w.call(this);this.XXa=[];this.kD=[];this.eb=b;this.Pc=new c.Vw;this.Pc.za(this,a.K.Xv,this.V9);this.Pc.za(this,a.K.bP,this.l3a);this.dha=new c.dn;this.dha.kb(new c.ga(0,0,100,25));this.dha.Na(this.Pc);this.dha.Cf(!1);this.dha.$b(a.kSb)};var l=c.u(c.Keb,c.rk);l.bs=function(){return this.Pc};l.Zf=function(){return 0==
this.kD.length};l.MK=function(a){this.kD.push(a)};l.AM=function(a){this.kD.splice(this.kD.indexOf(a),1);this.Zf()&&this.Pc.Nm()};l.V9=function(){e.Gb("PRIM_LABL");for(var b=0,f=6,g=100;b<this.kD.length;b++){var l=this.XXa[b],k=this.kD[b];l||(l=new c.Us,l.Ta(5),l.Cf(!1),l.Ua(f),l.Kn(a.Ug.oq),l.ac(320),l.wc(20),l.Qe(!1),this.XXa.push(l));l.Na(this.dha);l.Cb(k.zq());l.vlc();g<l.Xa()+15&&(g=l.Xa()+15);f+=25}for(;b<this.XXa.length;b++)l=this.XXa[b],l.Na(null);this.dha.wc(f+6);this.dha.ac(g);this.Pc.wc(f+
6);this.Pc.ac(g)};l.l3a=function(){this.eb.Wj(!0)}},{rp:["PRIM_PPNL"]});
