window.LANSA.addSrc("wdgt",function(e,c,a,b,n){var q={};c.O0b=function(a){m.w.call(this);this.tEa=a;this.IVa=function(){};this.EW=this.Dvb=!1;this.Zvb=[];this.Yvb=[];this.Uvb=[];this.Tvb=[];this.Wvb=[]};var m=c.u(c.O0b,c.ye);m.lQ=function(){return this.Dvb};m.oh=function(){return this.tEa.nm};m.ECc=function(){return this.tEa.js||[]};m.oDc=function(){return this.tEa.st||[]};m.ayc=function(){return this.tEa.fn};m.Uyc=function(){return this.tEa.fe};m.bY=function(){return this.IVa};m.iTc=function(){function a(){if(k<
m.length){var c=m[k],e=document.createElement("script");e.type="text/javascript";e.onload=function(){e.onload=null;e.onerror=null;k++;a()};e.onerror=function(){e.onload=null;e.onerror=null;throw"Error defining Widget "+d+", failed to load script: "+c;};document.body.appendChild(e);e.src=c}else b()}function b(){function a(){if(!c.Dvb){for(c.Dvb=!0;0<c.Tvb.length;){var b=c.Tvb.shift();c.eab(b)}for(;0<c.Yvb.length;)b=c.Yvb.shift(),c.gab(b.csb,b.qfd,b.value);for(;0<c.Wvb.length;)b=c.Wvb.shift(),c.POb(b.csb,
b.parent);for(;0<c.Zvb.length;)b=c.Zvb.shift(),c.hab(b);for(;0<c.Uvb.length;)b=c.Uvb.shift(),c.fab(b)}}var d=c.ayc(),f=c.IVa.prototype;e&&e(f);var h={Loading:{},Completed:{},Finalize:function(){a()}};d(f,h)!==h.Loading&&a()}var c=this,d=c.oh(),e=c.Uyc();q[d]=c;for(var f=c.oDc(),h=0;h<f.length;h++){var g=f[h],l=document.createElement("link");l.type="text/css";l.rel="stylesheet";l.href=g;document.body.appendChild(l)}var k=0,m=c.ECc();a()};m.gab=function(a,b,c){if(this.lQ()){var d=a["set"+b];if(!d)throw e.ZTc("set"+
b);d&&d.call(a,c)}else this.Yvb.push({csb:a,qfd:b,value:c})};m.fab=function(a){this.lQ()?a.kJa():this.Uvb.push(a)};m.eab=function(a){if(this.lQ()){var b=a.onCreateInstance;b&&b.call(a)}else this.Tvb.push(a)};m.POb=function(a,b){if(this.lQ()){var c=a.onRealizeControl;if(!c)throw e.YTc();c.call(a,b)}else this.Wvb.push({csb:a,parent:b})};m.hab=function(a){if(this.lQ()){var b=a.onSizeChanged;b&&b.call(a)}else this.Zvb.push(a)};c.Ffb=function(){s.w.call(this)};var s=c.u(c.Ffb,c.dn);s.Ox=function(){return this.Pa()&&
this.Pa().NFc()?this:null};s[a.$.hy]=function(b){var c=!1;this.Pa()&&(c=b.Mc!==n?b.Mc:a.Z.oJ,c=c==a.Z.oJ||c==a.Z.Zw||c==a.Z.FC?this.Pa().IIb(null):this.Pa().JIb(null));c||s.j.GT.call(this,b)};s[a.$.Uxa]=function(b){var c=!1;this.Pa()&&(c=(b.Mc!==n?b.Mc:a.Z.oJ)==a.Z.oJ?this.Pa().IIb(document.activeElement):this.Pa().JIb(document.activeElement));c||s.j.o3a.call(this,b)};c.I_b=function(){g.w.call(this)};var g=c.u(c.I_b,c.wd);e.kd(c.I_b,"PRIM_WDGT",{});c.K_b=function(){k.w.call(this);var a=this.OJa(),
a=this.XS=q[a],b=this.DH=new (a.bY());b.LANSA_Component=this;b.LANSA_Class=a;a.eab(b)};var k=c.u(c.K_b,c.wd);k.dab=function(a,b){if(this.XS.lQ()){var c=this.DH[a];if(!c)throw e.N4b(a);return c.apply(this.DH,b)}throw e.gQa();};k.gwa=function(a){if(this.XS.lQ()){var b=this.DH["get"+a];if(!b)throw e.M4b("get"+a);return b.call(this.DH)}throw e.gQa();};k.ZAa=function(a,b){this.XS.gab(this.DH,a,b)};k.m4=function(){l.j.m4.call();var a=this;setTimeout(function(){a.XS.fab(a)},5)};k.kJa=function(){this.Ha(a.K.VY)};
e.jb(c.K_b,"PRIM_WDGT","Object",{});var f=k;f.get=f.gwa;f.set=f.ZAa;f.invoke=f.dab;c.J_b=function(){l.w.call(this);var b=this.OJa(),b=this.XS=q[b],c=this.DH=new (b.bY());c.LANSA_Component=this;c.LANSA_Class=b;b.eab(c);this.rg&=~a.Wg.qQ;this.rg&=~a.Wg.dZ};var l=c.u(c.J_b,c.Ffb);l.eh=function(){return c.N0b};l.Ld=function(a,c,d){l.j.Ld.call(this,a,c,d);a=this.Pa().hb();b.Rd[a].aNc(this.DH)};l.dab=function(a,b){if(this.XS.lQ()){var c=this.DH[a];if(!c)throw e.N4b(a);return c.apply(this.DH,b)}throw e.gQa();
};l.gwa=function(a){if(this.XS.lQ()){var b=this.DH["get"+a];if(!b)throw e.M4b("get"+a);return b.call(this.DH)}throw e.gQa();};l.ZAa=function(a,b){this.XS.gab(this.DH,a,b)};l.vEd=function(){this.kJa()};l[a.$.zba]=function(){this.XS.fab(this)};l[a.$.xG]=function(){this.Pb()&&this.XS.hab(this.DH)};l.Mca=function(){l.j.Mca.call(this);this.Pb()&&this.XS.hab(this.DH)};e.jb(c.J_b,"PRIM_WDGT","Control",{});f=l;f.get=f.gwa;f.set=f.ZAa;f.invoke=f.dab;c.D_b=function(){d.w.call(this);this.nd=b.zd(0,0,100,100);
this.VDa=this.yEa=""};var d=c.u(c.D_b,c.Ffb);d.eh=function(){return c.n0b};d.Jzc=function(){return this.yEa};d.T_c=function(b){this.yEa!=b&&(this.yEa=b,this.ca(a.f.h),this.Jd())};d.VT=function(){return this.VDa};d.Ckb=function(a){this.VDa=a};d.CC=function(a){var d=this.zp(),e=this.nr();if(d||e){var f=new c.ga,h=[];h[0]=d;h[1]=e;h[2]=a;h[3]=0;h[4]=0;var g=this.hb();h[3]=0;h[4]=0;null!=g&&b.Rd[g].Pbd(h);f.Ra(h[3]);f.Ga(h[4]);d&&a.Ra(a.Q()+this.ea.lj()+f.aa()+this.ea.Fk());e&&a.Ga(a.O()+this.ea.Gk()+
f.ba()+this.ea.pm())}};e.jb(c.D_b,"PRIM_WEB","HtmlContainer",{Oa:{Html:{a:d.Jzc,g:function(a){this.T_c(e.ma(a))}},Description:{a:d.VT,g:function(a){this.Ckb(e.ma(a))}}},ig:{eg:"Html"}});c.Ufb=function(a){h.w.call(this,a)};var h=c.u(c.Ufb,c.gn);h.HLa=function(){return!1};h.KLa=function(){return this.pa.bs()||this.pa.yK?!1:!0};h.NFc=function(){return 0<this.n1a().length};h.tM=function(a){h.j.tM.call(this,a);return!1};h.IIb=function(a){var b=this.n1a();for(a=a?b.indexOf(a)+1:0;0<=a&&a<b.length;){var c=
b[a];if(c&&(c.focus(),c==document.activeElement))return!0;a++}return!1};h.JIb=function(a){var b=this.n1a();for(a=a?b.indexOf(a)-1:b.length-1;0<=a;){var c=b[a];if(c&&(c.focus(),c==document.activeElement))return!0;a--}return!1};h.n1a=function(){var a=[],b=[];this.Y2b(this.G,b);for(var c=1;c<b.length;c++)a=a.concat(b[c]||[]);return a=a.concat(b[0]||[])};h.Y2b=function(a,b){var c=a.tabIndex;0<=c&&(b[c]===n&&(b[c]=[]),b[c].push(a));for(var c=a.childNodes,d=0;d<c.length;d++)a=c[d],this.Y2b(a,b)};h.f3=h[a.La.hN]=
function(b){b.Se=a.La.Kia|a.La.GHa};c.N0b=function(a){y.w.call(this,a);this.eb=null};var y=c.u(c.N0b,c.Ufb);y.lf=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.fc);this.G.setAttribute("LANSAHandle",this.fc);return y.j.lf.call(this,a,b)};y.aNc=function(a){null==this.eb&&(this.eb=document.createElement("div"),this.eb.style.left="0px",this.eb.style.top="0px",this.eb.style.width="100%",this.eb.style.height="100%",a.LANSA_Class.POb(a,this.eb),this.G.appendChild(this.eb))};
c.n0b=function(a){C.w.call(this,a);this.eb=null};var C=c.u(c.n0b,c.Ufb);C.bz=function(){C.j.bz.call(this);this.G.style.whiteSpace="normal"};C.lf=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.fc);this.G.setAttribute("LANSAHandle",this.fc);this.eb=document.createElement("div");this.eb.style.left="0px";this.eb.style.top="0px";this.eb.style.width="100%";this.eb.style.height="100%";this.eb.innerHTML=this.pa.yEa;this.G.appendChild(this.eb);return C.j.lf.call(this,a,
b)};C.Cbd=function(){var a=this.pa.zp(),b=this.pa.nr();this.eb.style.width=a?"":"100%";this.eb.style.height=b?"":"100%";this.eb.innerHTML=this.pa.yEa};C.Ld=function(){C.j.Ld.call(this);this.Cbd()};C.Pbd=function(a){var b=a[0],c=a[2],d=this.eb.style.width;a[1]&&!b&&(this.eb.style.width=c.aa()+"px");a[3]=this.eb.clientWidth;a[4]=this.eb.clientHeight;this.eb.style.width=d}});
