window.LANSA.addSrc("labl",function(e,c,a,b){a.Krb={bQd:0,Orb:16};a.jZ={WMc:1,Tcb:1,Scb:2,ISb:240};a.Pcb={qOa:0,Y0b:1};c.Us=function(){n.w.call(this);this.As=a.uo.j$;this.mS=a.jZ.WMc;this.Fga=a.Pcb.qOa;this.iB=this.uB=this.pB=this.BB=0;this.yk=null;this.JN=a.Xj.JQ;this.Ja=null;this.tv=0;this.DW=a.ie.bH;this.y1=new c.ga;this.QH=new c.ga;this.Qc=this.Qc|a.Xb.wba|a.Xb.Ixa|a.Xb.Rbb|a.Xb.nE|a.Xb.IU|a.Xb.Sbb|a.Xb.mE;this.rg=this.rg|a.Wg.Ala|a.Wg.qQ|a.Wg.dZ;this.Cf(!1);this.goa(!1)};var n=c.u(c.Us,c.Ts);
n.U=function(){this.yk&&(this.yk.Ca(this,this.h3a),this.yk=null);n.j.U.call(this);this.$c(null)};n.eh=function(){return c.cgb};n.RA=function(c){this.yk!=c&&(this.yk&&this.yk.Ca(this,this.h3a),this.yk=c,null==this.yk?this.goa(!1):(this.goa(!0),this.yk.Da(this,this.h3a)),this.l(a.f.h),b.cb().Bd(this,!1))};n.QD=function(){return this.yk};n.Od=function(){return 0!=(this.mS&a.jZ.Tcb)?!0:!1};n.Mw=function(){return!this.zp()&&this.Od()};n.Qe=function(c){c=this.mS&~a.jZ.Tcb|(c?a.jZ.Tcb:0);this.mS!=c&&(this.mS=
c,this.Jd(),b.cb().Bd(this,!1),this.ca(a.f.h))};n.XKa=function(){return 0!=(this.mS&a.jZ.Scb)?!0:!1};n.Y7b=function(b){b=this.mS&~a.jZ.Scb|(b?a.jZ.Scb:0);this.mS!=b&&(this.mS=b,this.gh(),this.ca(a.f.h))};n.rMd=function(c){this.wLa()!=c&&(this.mS=this.mS&~a.jZ.ISb|c,this.Jd(),b.cb().Bd(this,!1),this.ca(a.f.h))};n.wLa=function(){return this.mS&a.jZ.ISb};n.Gf=function(c){this.As!=c&&(this.As=c,b.cb().Bd(this,!1),this.ca(a.f.h))};n.Ue=function(){return this.As};n.Ve=function(){return this.BB};n.Be=function(c){this.BB!=
c&&(this.BB=c,this.Jd(),b.cb().Bd(this,!1),this.ca(a.f.h))};n.af=function(){return this.pB};n.He=function(c){this.pB!=c&&(this.pB=c,this.Jd(),b.cb().Bd(this,!1),this.ca(a.f.h))};n.Qf=function(){return this.uB};n.re=function(c){this.uB!=c&&(this.uB=c,this.Jd(),b.cb().Bd(this,!1),this.ca(a.f.h))};n.hg=function(){return this.iB};n.yf=function(c){this.iB!=c&&(this.iB=c,this.Jd(),b.cb().Bd(this,!1),this.ca(a.f.h))};n.ns=function(c){this.JN!=c&&(this.JN=c,b.cb().Bd(this),this.l(a.f.h))};n.Fc=function(){return this.Ja};
n.$c=function(c){this.Ja!=c&&(null!=this.Ja&&(this.Ja.Ca(this,this.Qm),this.Ja.xb()),this.Ja=c,null!=this.Ja&&(this.Ja.Ba(),this.Ja.Da(this,this.Qm)),this.Jd(),b.cb().Bd(this),this.l(a.f.h))};n.Ju=function(){return this.JN};n.Gw=function(){return this.tv};n.Uu=function(c){c!=this.tv&&(this.tv=c,this.Jd(),this.ca(a.f.h),b.cb().Bd(this))};n.uL=function(){return this.DW};n.zJ=function(b){this.DW!=b&&(this.DW=b,this.Jd(),this.l(a.f.h))};n.tm=function(){var b=a.he.uE;switch(this.Pf()){case a.Jg.mA:switch(this.pU()){case a.Ug.oq:b=
a.he.uE;break;case a.Ug.dN:b=a.he.ePa;break;default:b=a.he.gPa}break;case a.Jg.WH:switch(this.pU()){case a.Ug.oq:b=a.he.fPa;break;case a.Ug.dN:b=a.he.H2b;break;default:b=a.he.J2b}break;default:switch(this.pU()){case a.Ug.oq:b=a.he.HZ;break;case a.Ug.dN:b=a.he.G2b;break;default:b=a.he.GQ}}return b};n.oC=function(){return 0!=(this.Fga&a.Pcb.Y0b)};n.gAd=function(a){this.Fga|=a};n.$Jc=function(a){this.Fga&=~a};n.hAd=function(a,b){this.Fga=this.Fga&~a|(b?a:0)};n.Ld=function(a,b,c){n.j.Ld.call(this,a,b,
c);this.Fq(!1)};n.w5=function(a){n.j.w5.call(this,a);this.Fq(a)};n.Fq=function(a){n.j.Fq.call(this,a);a=this.Ne();this.oFb(a,!1)};n.Cj=function(){n.j.Cj.call(this);this.Dd(a.$.yz);this.Dd(a.$.Rxa)};n.Zc=function(){this.TH(a.Xb.VL,this.RL());n.j.Zc.call(this)};n.Dq=function(a){null!=this.yk?this.yk.Ye():n.j.Dq.call(this,a)};n.xg=function(){this.KZ();b.cb().IB(this)};n.AC=function(){this.bT()};n.wE=function(a){var b=!1,b=a.ee().UPa(this,this.ea.Vh,this.rbb(),this.tbb(),this.sbb(),a);!1==b&&n.j.wE.call(this,
a)};n.qe=function(b){""==b[1]&&(b[1]=a.WRb);n.j.qe.call(this,b)};n.oFb=function(a,e){var g=b.Dc(a),k=b.Dc(g),f=null,l=0<this.tv?this.tv:-1;this.Ja&&(f=this.Ja.CAb(g.ba()-4,g.ba()-4));g.Ua(g.O()+this.BB);g.Ta(g.Q()+this.pB);g.Ra(g.va-this.uB);g.Ga(g.ua-this.iB);var d=this.ob(),h=new c.ga,y=new c.ga,n=[],t="";n[0]=h;n[1]=k;n[2]=y;n[3]=l;n[4]=l;n[5]=0;this.mAa(null,f,d,this.ke(),g,n);h=n[0];k=n[1];g=n[5];this.Ja&&this.Ja instanceof c.bM&&(t=this.Ja.vh());this.y1=h;this.QH=k;e||(f=this.Pa().hb(),l=this.Mw(),
b.Rd[f].Tg(f,k,t,h,l,this.XKa(),g))};n.mAa=function(e,n,g,k,f,l){e=l[0];var d=l[1],h=l[2],y=l[3],C=l[4],t=l[5],d=b.Dc(f);if(null!=n&&this.Cd()){var w=a.If.GBa;this.QD()||(w|=a.If.SSa);t=w;if(this.Mw())switch(this.wLa()){case a.Krb.Orb:w|=a.If.VA;break;default:w|=a.If.VA,t|=a.If.VA}else t|=this.As;switch(this.Pf()){case a.Jg.mA:t|=a.If.Tda;break;case a.Jg.WH:t|=a.If.IBa;break;default:t|=a.If.Bob}b.Ola(n,g,k,f,0,this.tm(),this.tm(),this.Ju(),e,d,h,0,this.Cd()?0:2,y,C,w)}else if(t=this.Hzb(d),0<g.length){d.aa()>
f.aa()&&(this.Mw()?this.wLa()==a.Krb.Orb&&(d=new c.ga(0,0,f.aa(),d.ba())):d=new c.ga(0,0,f.aa(),d.ba()));switch(this.Pf()){case a.Jg.mA:d=new c.ga(f.Q()+(f.aa()-d.aa())/2,1,d.aa(),d.ba());t|=a.If.Tda;break;case a.Jg.WH:d=new c.ga(f.va-d.aa(),1,d.aa(),d.ba());t|=a.If.IBa;break;default:d=new c.ga(f.Q(),1,d.aa()+1,d.ba()),t|=a.If.Bob}switch(this.pU()){case a.Ug.oq:d=new c.ga(d.Q(),f.O()+(f.ba()-d.ba())/2,d.aa(),d.ba());break;case a.Ug.dN:d=new c.ga(d.Q(),f.ua-1-d.ba(),d.aa(),d.ba())}}l[0]=e;l[1]=d;l[2]=
h;l[3]=y;l[4]=C;l[5]=t};n.Hzb=function(c){var e=this.ke(),g=a.If.GBa,k=this.ob();if(0<k.length)if(this.QD()||(g|=a.If.SSa),this.Oz=b.sM(k,e,this.Mw(),c.aa(),c.ba()),this.Mw())switch(this.wLa()){case a.Krb.Orb:b.tC(k,c,g|a.If.VA,e);break;default:b.tC(k,c,g|a.If.VA,e),g|=a.If.VA}else b.tC(k,c,g,e),g|=this.As;return g};n.vlc=function(){var a=b.vQ();this.Wj(!1,!0);this.Hzb(a);this.ac(a.aa())};n.BC=function(c){if(this.XKa())switch(b.sr(c)){case a.Z.zQa:case a.Z.J5b:case a.Z.Q5b:case a.Z.Vca:case a.Z.R5b:case a.Z.MVc:case a.Z.qXc:case a.Z.M5b:case a.Z.xXc:case a.Z.BQa:c.gl(!0);
return}n.j.BC.call(this)};n.CC=function(a){var b=this.zp(),c=this.nr();(b||c)&&this.I3b(a,b,c)};n.I3b=function(a,e,g){var k=new c.ga,f=new c.ga(0,0,1E4,1E4);this.Mw()&&f.Ra(f.Q()+a.aa()-(this.ea.lj()+this.ea.Fk()));this.oFb(f,!0);""==this.ob()&&this.y1.Zf()||(""==this.ob()?k=this.y1:(k=b.Dc(this.QH),k.Ga(k.ua+(0<this.QH.ba()?1:0)),k=k.s0(this.y1)));e&&a.Ra(a.Q()+this.ea.lj()+this.pB+k.aa()+this.uB+this.ea.Fk());g&&a.Ga(a.O()+this.ea.Gk()+this.BB+k.ba()+this.iB+this.ea.pm())};n.Bca=function(a,b,c){n.j.Bca(a,
b,c);c[0]&&this.XKa()&&(c[0]=!1)};n.zf=function(a){b.Meb();return n.j.zf.call(this,a)};n.Qm=function(c,e){switch(e.Ya){case a.f.sb:case a.f.Ob:e.Fi==this.Ja&&this.$c(null);break;case a.f.h:e.Fi==this.Ja&&(b.cb().Bd(this),this.Jd())}};n.h3a=function(b,c){c.Ya==a.f.Ob&&this.RA(null)};n.Eu=n[a.$.xG]=function(a){n.j.Eu.call(this,a);b.cb().Bd(this,!1)};n.Vjd=n[a.$.Rxa]=function(){b.cb().Bd(this,!1)};n.YF=n[a.$.yz]=function(){b.cb().Bd(this,!1)};n.cja=n[a.$.aya]=function(a){this.uz()?this.Cf(!1):n.j.cja.call(this,
a)};n.cL=n[a.$.YL]=function(){this.yk&&this.yk.Ye()};n.hz=n[a.$.JA]=function(b){this.oC()&&(this.No(),this.$Jc(a.Pcb.Y0b));n.j.hz.call(this,b)};e.kd(c.Us,"PRIM_LABL",{Oa:{Ellipses:{a:function(){return e.ta(this.Ue(),a.uo.v)},g:function(b){this.Gf(e.qa(b,a.uo.v))}},Caption:{a:n.ob,g:function(a){this.Cb(e.ma(a))}},Alignment:{a:function(){return e.ta(this.Pf(),a.Jg.v)},g:function(b){this.Ab(e.qa(b,a.Jg.v))}},VerticalAlignment:{a:function(){return e.ta(this.pU(),a.Ug.v)},g:function(b){this.Kn(e.qa(b,
a.Ug.v))}},FocusControl:{a:n.QD,g:n.RA},WordWrap:{a:n.Od,g:function(a){this.Qe(e.xa(a))}},Selectable:{a:n.XKa,g:function(a){this.Y7b(e.xa(a))}},MarginLeft:{a:n.af,g:function(a){this.He(e.J(a))}},MarginTop:{a:n.Ve,g:function(a){this.Be(e.J(a))}},MarginBottom:{a:n.hg,g:function(a){this.yf(e.J(a))}},MarginRight:{a:n.Qf,g:function(a){this.re(e.J(a))}},Image:{a:n.Fc,g:n.$c},ImagePosition:{a:function(){return e.ta(this.Ju(),a.Xj.v)},g:function(b){this.ns(e.qa(b,a.Xj.v))}},ImageHeight:{a:n.Gw,g:function(a){this.Uu(e.J(a))}},
ImageSizing:{a:function(){return e.ta(this.uL(),a.ie.v)},g:function(b){this.zJ(e.qa(b,a.ie.v))}}},ig:{eg:"Caption"}});c.cgb=function(a){q.w.call(this,a);this.JVa=this.tv=this.CEa=this.Zub=this.Yub=this.Ja=this.FF=this.Fha=this.rD=this.uxb=this.txb=this.sxb=this.mb=null};var q=c.u(c.cgb,c.gn);q.ob=function(){return this.mb.textContent};q.Cb=function(a){this.mb.textContent=a};q.H3=function(){return this.mb};q.sL=function(){return this.mb};q.Tg=function(b,c,g,k,f,l,d){null==this.Ja.parentElement&&this.G.appendChild(this.Ja);
if(null==this.JVa||this.JVa!=l)this.JVa=l,this.mb.spellcheck=!1,this.mb.setAttribute("contenteditable",l);this.Ja.style.backgroundImage=e.Du(g);switch(this.pa.uL()){case a.ie.bH:this.Ja.style.backgroundSize="contain";break;case a.ie.yBa:this.Ja.style.backgroundSize="cover";break;case a.ie.Hf:this.Ja.style.backgroundSize="100% 100%";break;case a.ie.Ud:this.Ja.style.backgroundSize="auto"}if(null==this.FF||this.FF!=f)this.FF=f,this.mb.style.whiteSpace=f?"pre-wrap":"pre";if(null==this.Fha||this.Fha!=
d)this.Fha=d,this.mb.style.textAlign=0!=(d&a.If.IBa)?"right":0!=(d&a.If.Tda)?"center":"",0!=(d&a.If.FBa)||0!=(d&a.If.HBa)||0!=(d&a.If.JBa)?(this.mb.style.textOverflow="ellipsis",this.mb.style.overflow="hidden"):(this.mb.style.textOverflow="clip",this.mb.style.overflow="visible");if(null==this.sxb||this.sxb!=c.Q())this.sxb=c.Q(),this.mb.style.left=c.Q()+"px";if(null==this.txb||this.txb!=c.O())this.txb=c.O(),this.mb.style.top=c.O()+"px";if(null==this.rD||this.rD!=c.ba())this.rD=c.ba(),this.mb.style.height=
c.ba()+"px";if(null==this.uxb||this.uxb!=c.aa())this.uxb=c.aa(),this.mb.style.width=c.aa()+"px";if(null==this.Yub||this.Yub!=k.Q())this.Yub=k.Q(),this.Ja.style.left=k.Q()+"px";if(null==this.Zub||this.Zub!=k.O())this.Zub=k.O(),this.Ja.style.top=k.O()+"px";if(null==this.tv||this.tv!=k.ba())this.tv=k.ba(),this.Ja.style.height=k.ba()+"px";if(null==this.CEa||this.CEa!=k.aa())this.CEa=k.aa(),this.Ja.style.width=k.aa()+"px"};q.lf=function(a,b){this.G=document.createElement("div");this.G.setAttribute("LANSAHandle",
this.fc);this.mb=document.createElement("div");var c=this.mb.style;c.position="absolute";c.outline="none";c.overflowX="hidden";c.overflowY="hidden";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";c.borderStyle="solid";c.borderLeftWidth="0px";c.borderTopWidth="0px";c.borderRightWidth="0px";c.borderBottomWidth="0px";c.cursor="inherit";c.textDecoration="inherit";this.Ja=document.createElement("div");c=this.Ja.style;c.position="absolute";c.backgroundSize="contain";
c.backgroundPosition="center center";c.backgroundRepeat="no-repeat";this.G.appendChild(this.mb);this.G.appendChild(this.Ja);return q.j.lf.call(this,a,b)};q.zX=function(){var a=this;this.y2();a.mb.addEventListener("paste",function(b){a.xca(b);b.preventDefault()},!1)};q.Vqb=function(){var a="";q.j.Vqb.call(this);"rgba(0,0,0,0)"==this.jVa&&""!=this.G.style.boxShadow&&(a=this.G.style.boxShadow);this.mb.style.textShadow=a};q.tM=function(a){q.j.tM.call(this,a);return!this.JVa};q.xca=function(){}});
