window.LANSA.addSrc("evef",function(e,c,a,b){e.Gb("PRIM_EVP");e.Gb("PRIM_EDIT");c.oUb=function(b){n.w.call(this,b);this.em|=a.P4a.wrb;this.ff|=268435456;this.Ea=new c.nUb(this);this.Ea.Na(this);this.Ea.za(this,a.K.ah,this.vA)};var n=c.u(c.oUb,c.H4);n.vb=function(){b.la(this.Ea);this.Ea=null;n.j.vb.call(this)};n.Laa=function(){return this.Ea};n.jq=function(b){this.Ea.yn()!=b&&(this.Ea.jq(b),this.ca(a.f.h))};n.yn=function(){return this.Ea.yn()};n.bu=function(b){this.Ea.hr()!=b&&(this.Ea.bu(b),this.ca(a.f.h))};
n.hr=function(){return this.Ea.hr()};n.UA=function(b){this.Ea.Lv()!=b&&(this.Ea.UA(b),this.ca(a.f.h))};n.Lv=function(){return this.Ea.Lv()};n.Jv=function(){return this.Ym()!=this.vp()};n.vp=function(){return this.Ea.vp()};n.Lq=function(a){this.Ea.Lq(a)};n.Ym=function(){return this.Ea.Ym()};n.Kq=function(a){this.Ea.Kq(a)};n.hc=function(){return this.Ea.hc()};n.Hu=function(){return this.Ea.ea};n.HM=function(a){1==a?this.So(268435456):this.So(0)};n.pI=function(){var a=0;268435456==this.nj()&&(a=1);return a};
n.So=function(b){this.nj()!=b&&(this.ff=this.ff&~a.ci.nja|b,this.gh(),this.l(a.f.h))};n.nj=function(){return this.ff&a.ci.nja};n.pMa=function(){return this.HI()?!0:!1};n.HI=function(){return 0<this.nj()};n.JCa=function(){this.Oe()&&this.Oe().$b(this.Jra);this.Ea&&this.Ea.$b(this.tra)};n.pxa=function(){this.Ea.zg(this.ib());this.Ea.dx(!0);this.Ea.Wu(!0);this.Ea.J5(this.NT());this.Ea.Qg(this.Fe());this.Ea.uJ(this.Dj());this.Ea.X5(this.xK);this.Ea.ym(this.om());this.Ea.Ll(this.dj());this.Ea.eu(this.Nw());
this.Ea.Fj(this.pi());this.Ea.Ej(this.Eh());this.Ea.Dm(this.Kk());this.ib().oMa()&&this.Ea.os("*")};n.WY=function(a){this.pxa();n.j.WY.call(this,a)};n.Cj=function(){this.pxa();n.j.Cj.call(this)};n.Xe=function(a){if(this.Ea){var c=this.Ne(),e,k,f;this.Cd()?(k=this.rh,f=this.sh,e=c.aa()-(this.rh+this.Mj),c=c.ba()-(this.sh+this.Lj)):(k=this.af(),f=this.Ve(),e=c.aa()-(this.af()+this.Qf()),c=c.ba()-(this.Ve()+this.hg()));this.Ea.kb(b.zd(k,f,e,c))}n.j.Xe.call(this,a)};n.Hja=function(){var a;this.Ea&&(a=
this.Ea.$k());return a};n.RE=function(a,b){a&&a.Ca(this,this.Vn);b&&b.Da(this,this.Vn);this.Ea.zg(b)};n.Dq=function(){this.Ea.Ye()};n.xg=function(a){null!=this.Ea&&this.Ea.uJ(this.Dj());n.j.xg.call(this,a);this.Ea&&(this.Ea.Cr(null),this.Ea.dx(!0),this.Ea.Wu(!0),this.Zy&&this.Ea.Cr(this.Zy))};n.irb=function(){this.Ea&&this.Ea.bcc()};n.YZ=function(a,b){this.Ea&&this.Ea.YZ(a,b)};n.CX=function(){this.Ea&&this.Ea.CX()};n.MK=function(a){this.Ea&&this.Ea.MK(a)};n.AM=function(a){this.Ea&&this.Ea.AM(a)};
n.vA=function(){this.pc()};n.Vn=function(){};n.tIa=n[a.$.yba]=function(){this.Ea&&this.i6(this.DY())};n.GT=n[a.$.hy]=function(){this.Ea.Ye()};n.cL=n[a.$.YL]=function(){this.Ea.Ye()};e.kd(c.oUb,"PRIM_EVEF",{nJ:a.Cv.M9,Oa:{ComponentVersion:{a:n.pI,g:function(a){this.HM(e.J(a))}},AutoTab:{a:n.NT,g:function(a){this.J5(e.xa(a))}},AutoSelect:{a:n.om,g:function(a){this.ym(e.xa(a))}},WordWrap:{a:n.Od,g:function(a){this.Qe(e.xa(a))}},ShowSelection:{a:n.dj,g:function(a){this.Ll(e.xa(a))}},ShowSelectionHilight:{a:n.Nw,
g:function(a){this.eu(e.xa(a))}},ShowPrompter:{a:n.b4,g:function(a){this.moa(e.xa(a))}},PrompterImage:{a:n.LKa,g:n.f6},PrompterTabStop:{a:n.fwa,g:function(a){this.Mlb(e.xa(a))}},UsePicklist:{a:n.tLa,g:function(a){this.fR(e.xa(a))}},EditAlignment:{a:function(){return e.ta(this.pi(),a.Al.v)},g:function(b){this.Fj(e.qa(b,a.Al.v))}},DisplayAlignment:{a:function(){return e.ta(this.Eh(),a.bi.v)},g:function(b){this.Ej(e.qa(b,a.bi.v))}},Text:{a:n.Gja},SelectionEnd:{a:n.Ym,g:function(a){this.Kq(e.J(a))}},
SelectionStart:{a:n.vp,g:function(a){this.Lq(e.J(a))}},VisualStyleEdit:{a:n.S8a,g:n.pBa},NumericEditStyle:{a:function(){return e.ta(this.Kk(),a.jn.v)},g:function(b){this.Dm(e.qa(b,a.jn.v))}},HasSelection:{a:n.Jv},EditStyle:{a:n.z3,g:n.mda},EditStyles:{a:n.Pja},EditMouseOverStyle:{a:n.bKa,g:n.bRa},EditMouseOverStyles:{a:n.cKa},EditFocusedStyle:{a:n.$Ja,g:n.aRa},EditFocusedStyles:{a:n.aKa},LabelStyle:{a:n.I3,g:n.qda},LabelStyles:{a:n.oKa},LabelMouseOverStyle:{a:n.mKa,g:n.pRa},LabelMouseOverStyles:{a:n.nKa},
InputType:{a:function(){return e.ta(this.yn(),a.De.v)},g:function(b){this.jq(e.qa(b,a.De.v))}},InputTypePattern:{a:n.hr,g:function(a){this.bu(e.ma(a))}},SpellCheck:{a:n.Lv,g:function(a){this.UA(e.xa(a))}},Value:{a:function(){return this.Ia()},g:function(a){this.Wa(a)}}},jc:{SelectText:function(a,b){this.YZ(e.J(a)-1,e.J(b))}},ig:{eg:"Value"}});c.nUb=function(a){q.w.call(this);this.bfc=a};var q=c.u(c.nUb,c.mM);q.qU=function(){return this.bfc.bs()||this.bfc.yK?!1:q.j.qU.call(this)}},{rp:["PRIM_EVP",
"PRIM_EDIT"]});
