window.LANSA.addSrc("gpbx",function(e,c,a,b){a.Dtc={iQd:0,hQd:9,Ndd:6,jQd:5,kQd:10};a.CEc={Fvc:0};c.WXb=function(){n.w.call(this);this.mub=a.Dtc.Ndd;this.zH=a.CEc.Fvc;this.QH=new c.ga;this.Qc=this.Qc|a.Xb.wba|a.Xb.Ixa|a.Xb.Rbb|a.Xb.nE|a.Xb.IU|a.Xb.mE;this.rg=this.rg|a.Wg.qQ|a.Wg.dZ;this.Cf(!1)};var n=c.u(c.WXb,c.kM);n.eh=function(){return c.m0b};n.mKd=function(b){this.mub!=b&&(this.mub=b,this.l(a.f.h),this.Nv())};n.yrd=function(){return this.mub};n.Fq=function(a){n.j.Fq.call(this,a);this.YPc()};n.Gqb=
function(){if(this.Pb()){var a=this.ke(),a=Math.abs(a.Qa()),c=this.Ne();this.Cd();this.Cd();c.Ta(c.Q()+a);""==this.ob()?(c.Ra(c.Q()),c.Ga(a)):(this.ob(),c.Ra(c.Q()+this.RT()),c.Ga(this.Aja()),c.Ra(c.va+a));b.Zn(this.QH,c)||(this.QH=c,this.nb());this.Fq(!0)}};n.Xe=function(a){a.Ua(a.O()+this.QH.ba());a.Ta(a.Q()+4);a.Ra(a.va-4);a.Ga(a.ua-4);n.j.Xe.call(this,a)};n.QSc=function(a,b,c){a.Ua(a.O()+this.QH.ba());a.Ta(a.Q()+4);a.Ra(a.va-4);a.Ga(a.ua-4);n.j.QSc.call(this,a,b,c)};n.Cj=function(){n.j.Cj.call(this);
this.Dd(a.$.yz)};n.Zc=function(){var b=this.RL()||this.el()&&(this.cZ()||this.oQ());this.TH(a.Xb.VL,b);n.j.Zc.call(this)};n.wE=function(a){var b=!1,b=a.ee().RPa(this,this.ea.Vh,this.cZ(),this.oQ(),a);!1==b&&n.j.wE.call(this,a)};n.dV=function(a){var b=!1;null!=a.ee()&&a.ha().el()&&(b=a.ee().SPa(this,this.ea.Vh,a,this.cZ(),this.oQ()));!1==b&&n.j.dV.call(this,a)};n.qe=function(b){""==b[1]&&(b[1]=a.URb);n.j.qe.call(this,b)};n.YPc=function(){var a=this.Ne(),a=this.JB(a,null),c=this.Ne();c.Ua(c.O()+this.QH.ba()/
2+1);c.Ta(c.Q()+2);c.Ra(c.va-2);c.Ga(c.ua-2);var e=this.Pa().hb(),k=this.ob();b.Rd[e].Tg(k,c,this.QH);b.la(a)};n.$r=n[a.$.yG]=function(a){this.Gqb();n.j.$r.call(this,a)};n.Eu=n[a.$.xG]=function(){n.j.Eu.call(this);this.Gqb()};n.YF=n[a.$.yz]=function(){this.Gqb();this.Nv()};n.mrc=n[a.$.vcb]=function(){this.gh()};e.kd(c.WXb,"PRIM_GPBX",{Oa:{Caption:{a:n.ob,g:function(a){this.Cb(e.ma(a))}},ThemeStyle:{a:function(){return e.ta(this.IL(),a.cv.v)},g:function(b){this.lBa(e.qa(b,a.cv.v))}}}});c.m0b=function(a){q.w.call(this,
a);this.mb=this.mVa=this.gDa=this.ae=this.Ic=null};var q=c.u(c.m0b,c.S4);q.lf=function(a,b){var c=null;q.j.lf.call(this,a,b);this.mVa=4;this.Ic=document.createElement("div");this.ae=document.createElement("div");this.gDa=document.createElement("div");this.mb=document.createElement("span");this.G.appendChild(this.Ic);this.G.appendChild(this.ae);this.G.appendChild(this.gDa);this.G.appendChild(this.mb);this.M$a(this.Ic,this.mVa);this.M$a(this.ae,0);this.M$a(this.gDa,0);c=this.Ic.style;c.borderTopWidth=
"0px";c=this.ae.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.gDa.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.mb.style;c.position="absolute";c.whiteSpace="nowrap";c.cursor="inherit";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";return this.G};q.M$a=function(a,b){var c=a.style;c.position="absolute";c.overflowX="hidden";c.overflowY=
"hidden";c.whiteSpace="nowrap";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";c.borderStyle="solid";c.outline="none";c.background="rgba(0,0,0,0)";c.borderTopWidth="1px";c.borderBottomWidth="1px";c.borderLeftWidth="1px";c.borderRightWidth="1px";c.borderTopLeftRadius=b+"px";c.webkitBorderTopLeftRadius=b+"px";c.borderTopRightRadius=b+"px";c.webkitBorderTopRightRadius=b+"px";c.borderBottomLeftRadius=b+"px";c.webkitBorderBottomLeftRadius=b+"px";c.borderBottomRightRadius=
b+"px";c.webkitBorderBottomRightRadius=b+"px"};q.Tg=function(a,b,c){var e=this.Ic.style;e.left=b.Q()+"px";e.top=b.O()+"px";e.width=b.aa()+"px";e.height=b.ba()+"px";e.borderColor=this.Cl();e=this.ae.style;e.left=b.Q()+this.mVa-1+"px";e.top=b.O()+"px";e.width=c.Q()-b.Q()+"px";e.height="1px";e.borderColor=this.Cl();e=this.gDa.style;e.left=c.va+2+"px";e.top=b.O()+"px";e.width=b.va-this.mVa-c.va+"px";e.height="1px";e.borderColor=this.Cl();e=this.mb.style;e.left=c.Q()+7+"px";e.top=c.O()+2+"px";e.height=
c.ba()+"px";e.width=c.aa()+"px";this.mb.textContent=a}});
