window.LANSA.addSrc("imag",function(e,c,a,b){c.Zt=function(){m.w.call(this);this.Es="";this.Xb=this.gb=this.lv=this.eWa=this.ZR=this.xe=this.af=null;this.NW=a.je.KSa;this.pB=this.BB=this.xB=this.IB=0;this.Qc|=a.ac.JMa;this.JEa=new c.jn;this.JEa.Df(!1);this.JEa.Na(this);this.xe=new c.IQ;this.af=new c.pb;this.af.yd(this.xe);this.JEa.Ida(this.af);this.Df(!1)};var m=c.u(c.Zt,c.jn);m.vb=function(){b.la(this.xe);this.xe=null;b.la(this.af);this.af=null;m.j.vb.call(this)};m.U=function(){m.j.U.call(this);
this.goa(null);this.eWa=null;this.xj(null);this.mo(null)};m.zh=function(){return this.Es};m.gw=function(c){b.Fz(this.Es,c)||(this.Es=c,this.goa(b.xma(this.Es)),this.l(a.f.h))};m.qqd=function(){return this.ZR};m.goa=function(b){this.ZR!=b&&(this.xj(null),null!=this.ZR&&this.ZR.Da(this,this.wDb),this.ZR=b,null!=this.ZR&&this.ZR.Ea(this,this.wDb),this.WJ(),this.ob(),this.l(a.f.h))};m.p6a=function(){return this.lv};m.xj=function(b){this.lv!=b&&(this.goa(null),null!=this.lv&&(this.lv.Da(this,this.Tm),
this.lv.xb()),this.lv=b,null!=this.lv&&(this.lv.Ca(),this.lv.Ea(this,this.Tm)),this.WJ(),this.ob(),this.Jd(),this.l(a.f.h))};m.P3=function(){return this.xe.Ok()};m.u_=function(b){this.xe.Ok()!=b&&(this.xe.tg(b),this.l(a.f.h))};m.wY=function(){return this.xe.Td()};m.t_=function(b){this.xe.Td()!=b&&(this.xe.Ta(b),this.l(a.f.h))};m.yY=function(){return this.xe.se()};m.v_=function(b){this.xe.se()!=b&&(this.xe.Ua(b),this.l(a.f.h))};m.iU=function(){return this.xe.Wa()};m.XM=function(b){this.xe.Wa()!=b&&
(this.xe.Yb(b),this.l(a.f.h))};m.Lw=function(){return this.xe.Pa()};m.Wu=function(b){this.xe.Pa()!=b&&(this.xe.xc(b),this.l(a.f.h))};m.HL=function(){return this.NW};m.HJ=function(b){this.NW!=b&&(this.NW=b,this.xe.Pb(b),this.ob(),this.Jd(),this.l(a.f.h))};m.xY=function(){return this.xe.vU()};m.hR=function(b){this.xe.vU()!=b&&(this.xe.s6(b),this.l(a.f.h))};m.zY=function(){return this.xe.Oi()};m.w_=function(b){this.xe.Oi()!=b&&(this.xe.Rl(b),this.l(a.f.h))};m.qG=function(){return this.xe.Rf()};m.UE=
function(b){this.xe.Rf()!=b&&(this.xe.yb(b),this.l(a.f.h))};m.Bg=function(b){this.gb!=b&&(this.mo(b),this.l(a.f.h))};m.hb=function(){var a=null;return a=this.gb};m.cc=function(){return this.Xb};m.Xe=function(){return this.IB};m.Ge=function(c){this.IB!=c&&(this.IB=c,this.ob(),this.Jd(),b.cb().Cd(this,!1),this.ca(a.f.h))};m.bf=function(){return this.xB};m.re=function(c){this.xB!=c&&(this.xB=c,this.ob(),this.Jd(),b.cb().Cd(this,!1),this.ca(a.f.h))};m.Sf=function(){return this.BB};m.Ud=function(c){this.BB!=
c&&(this.BB=c,this.ob(),this.Jd(),b.cb().Cd(this,!1),this.ca(a.f.h))};m.kg=function(){return this.pB};m.Se=function(c){this.pB!=c&&(this.pB=c,this.ob(),this.Jd(),b.cb().Cd(this,!1),this.ca(a.f.h))};m.Wl=function(a,b,c,e,m){return m};m.WK=function(){var a=this.Xb.hj();""!=a?this.ZR&&this.ZR.zh()==a||this.goa(b.xma(a)):this.goa(this.Xb.Nka());this.gb.OT(this.cc())};m.mo=function(a){var c=null;a&&(c=a.Rx(),this.gb==a?c.yn(this.Xb):a.lz(c));this.gb&&(this.gb.Da(this),this.Xb.Da(this),b.la(this.Xb),this.Xb=
null);if(this.gb=a)this.gb.Ea(this,this.Xn),this.Xb=c,this.Xb.Ea(this,this.Hv);this.ih()};m.WJ=function(){null==this.lv?this.xe.$c(this.ZR):this.eWa&&0<this.eWa.zh().length?this.xe.$c(this.eWa):this.xe.$c(this.lv)};m.Ze=function(b){var e=new c.ga(0,0,b.aa(),b.ba());m.j.Ze.call(this,b);e.Ua(e.O()+this.IB);e.Ta(e.Q()+this.xB);e.Ra(e.va-this.BB);e.Ha(e.ua-this.pB);this.JEa.oc(this);this.JEa.mb(e);this.HL()==a.je.KSa&&this.xe.Hc()&&(this.xe.Hc().Pa()>e.ba()||this.xe.Hc().Wa()>e.aa()?this.xe.Pb(a.je.lH):
this.xe.Pb(a.je.Wd))};m.KC=function(b){var e=this.Ap(),m=this.tr();if(0!=this.yY()||0!=this.wY()||100!=this.iU()||100!=this.Lw()||this.xY()!=a.Et.kea||this.zY()!=a.jz.jfa||this.xe.Yg()==a.je.HBa)m=e=!1;if(e||m){var k=new c.ga;if(this.xe.Hc())switch(k.Ra(this.xe.Hc().Wa()),k.Ha(this.xe.Hc().Pa()),this.xe.Yg()){case a.je.lH:if(m&&!e&&0<b.aa()&&0<k.aa()){var s=b.aa()/k.aa();k.Ha(k.O()+k.ba()*s)}}e&&b.Ra(b.Q()+this.ea.oj()+this.xB+k.aa()+this.BB+this.ea.Ik());m&&b.Ha(b.O()+this.ea.Jk()+this.IB+k.ba()+
this.pB+this.ea.wm())}};m.Af=function(a){b.dfb();return m.j.Af.call(this,a)};m.Tm=function(b,c){switch(c.Ya){case a.f.sb:case a.f.Ob:this.xj(null);break;case a.f.h:this.ob(),this.Jd()}};m.wDb=function(b,c){switch(c.Ya){case a.f.sb:case a.f.Ob:this.goa(null);break;case a.f.h:this.ob()}};m.Xn=function(b,c){c.Ya==a.f.h?c.Wr==a.we.Zw?this.gb.lz(this.cc()):this.mo(this.gb):c.Ya==a.f.sb&&this.Bg(null)};m.Hv=function(b,c){c.Ya==a.f.h&&c.Wr==a.we.Zw&&this.WK()};e.kd(c.Zt,"PRIM_IMAG",{Oa:{FileName:{a:m.zh,
g:function(a){this.gw(e.ma(a))}},Image:{a:m.p6a,g:function(a){this.xj(a)}},ImageTile:{a:function(){return e.ta(this.xY(),a.Et.v)},g:function(b){this.hR(e.ra(b,a.Et.v))}},ImageUnits:{a:function(){return e.ta(this.zY(),a.jz.v)},g:function(b){this.w_(e.ra(b,a.jz.v))}},ImageSizing:{a:function(){return e.ta(this.HL(),a.je.v)},g:function(b){this.HJ(e.ra(b,a.je.v))}},ImageOpacity:{a:m.P3,g:function(a){this.u_(e.K(a))}},ImageLeft:{a:m.wY,g:function(a){this.t_(e.K(a))}},ImageTop:{a:m.yY,g:function(a){this.v_(e.K(a))}},
ImageWidth:{a:m.iU,g:function(a){this.XM(e.K(a))}},ImageHeight:{a:m.Lw,g:function(a){this.Wu(e.K(a))}},ImageAlignment:{a:function(){return e.ta(this.qG(),a.he.v)},g:function(b){this.UE(e.ra(b,a.he.v))}},DataClass:{a:m.hb,g:m.Bg},MarginLeft:{a:m.bf,g:function(a){this.re(e.K(a))}},MarginTop:{a:m.Xe,g:function(a){this.Ge(e.K(a))}},MarginBottom:{a:m.kg,g:function(a){this.Se(e.K(a))}},MarginRight:{a:m.Sf,g:function(a){this.Ud(e.K(a))}}}})});
