window.LANSA.addSrc("evef",function(e,c,a,b){e.Gb("PRIM_EVP");e.Gb("PRIM_EDIT");c.JUb=function(b){m.w.call(this,b);this.lm|=a.e5a.Nrb;this.gf|=268435456;this.Ba=new c.IUb(this);this.Ba.Na(this);this.Ba.wa(this,a.G.ah,this.BA)};var m=c.u(c.JUb,c.P4);m.vb=function(){b.la(this.Ba);this.Ba=null;m.j.vb.call(this)};m.Vaa=function(){return this.Ba};m.lq=function(b){this.Ba.Bn()!=b&&(this.Ba.lq(b),this.ca(a.f.h))};m.Bn=function(){return this.Ba.Bn()};m.du=function(b){this.Ba.lr()!=b&&(this.Ba.du(b),this.ca(a.f.h))};
m.lr=function(){return this.Ba.lr()};m.bB=function(b){this.Ba.Nv()!=b&&(this.Ba.bB(b),this.ca(a.f.h))};m.Nv=function(){return this.Ba.Nv()};m.Lv=function(){return this.bn()!=this.wp()};m.wp=function(){return this.Ba.wp()};m.Qq=function(a){this.Ba.Qq(a)};m.bn=function(){return this.Ba.bn()};m.Pq=function(a){this.Ba.Pq(a)};m.cc=function(){return this.Ba.cc()};m.Ju=function(){return this.Ba.ea};m.QM=function(a){1==a?this.Uo(268435456):this.Uo(0)};m.yI=function(){var a=0;268435456==this.qj()&&(a=1);return a};
m.Uo=function(b){this.qj()!=b&&(this.gf=this.gf&~a.hi.vja|b,this.ih(),this.l(a.f.h))};m.qj=function(){return this.gf&a.hi.vja};m.AMa=function(){return this.QI()?!0:!1};m.QI=function(){return 0<this.qj()};m.SCa=function(){this.Pe()&&this.Pe().Wb(this.Sra);this.Ba&&this.Ba.Wb(this.Cra)};m.Axa=function(){this.Ba.Bg(this.hb());this.Ba.lx(!0);this.Ba.Yu(!0);this.Ba.Q5(this.XT());this.Ba.Sg(this.He());this.Ba.CJ(this.Gj());this.Ba.e6(this.FK);this.Ba.Hn(this.Zl());this.Ba.Ol(this.gj());this.Ba.hu(this.Sw());
this.Ba.Ij(this.ui());this.Ba.Hj(this.Hh());this.Ba.Im(this.Nk());this.hb().zMa()&&this.Ba.ss("*")};m.dZ=function(a){this.Axa();m.j.dZ.call(this,a)};m.Fj=function(){this.Axa();m.j.Fj.call(this)};m.Ze=function(a){if(this.Ba){var c=this.Oe(),e,s,f;this.Dd()?(s=this.vh,f=this.wh,e=c.aa()-(this.vh+this.Pj),c=c.ba()-(this.wh+this.Oj)):(s=this.bf(),f=this.Xe(),e=c.aa()-(this.bf()+this.Sf()),c=c.ba()-(this.Xe()+this.kg()));this.Ba.mb(b.Ad(s,f,e,c))}m.j.Ze.call(this,a)};m.Oja=function(){var a;this.Ba&&(a=
this.Ba.bl());return a};m.dF=function(a,b){a&&a.Da(this,this.Xn);b&&b.Ea(this,this.Xn);this.Ba.Bg(b)};m.Hq=function(){this.Ba.ef()};m.zg=function(a){null!=this.Ba&&this.Ba.CJ(this.Gj());m.j.zg.call(this,a);this.Ba&&(this.Ba.Fr(null),this.Ba.lx(!0),this.Ba.Yu(!0),this.dz&&this.Ba.Fr(this.dz))};m.zrb=function(){this.Ba&&this.Ba.vcc()};m.g_=function(a,b){this.Ba&&this.Ba.g_(a,b)};m.LX=function(){this.Ba&&this.Ba.LX()};m.VK=function(a){this.Ba&&this.Ba.VK(a)};m.KM=function(a){this.Ba&&this.Ba.KM(a)};
m.BA=function(){this.kc()};m.Xn=function(){};m.CIa=m[a.$.Iba]=function(){this.Ba&&this.p6(this.LY())};m.kL=m[a.$.Rv]=function(){this.Ba.ef()};m.lL=m[a.$.cJ]=function(){this.Ba.ef()};e.kd(c.JUb,"PRIM_EVEF",{vJ:a.Ev.W9,Oa:{ComponentVersion:{a:m.yI,g:function(a){this.QM(e.K(a))}},AutoTab:{a:m.XT,g:function(a){this.Q5(e.za(a))}},AutoSelect:{a:m.Zl,g:function(a){this.Hn(e.za(a))}},WordWrap:{a:m.Nd,g:function(a){this.Re(e.za(a))}},ShowSelection:{a:m.gj,g:function(a){this.Ol(e.za(a))}},ShowSelectionHilight:{a:m.Sw,
g:function(a){this.hu(e.za(a))}},ShowPrompter:{a:m.l4,g:function(a){this.toa(e.za(a))}},PrompterImage:{a:m.WKa,g:m.m6},PrompterTabStop:{a:m.nwa,g:function(a){this.emb(e.za(a))}},UsePicklist:{a:m.ELa,g:function(a){this.K_(e.za(a))}},EditAlignment:{a:function(){return e.ta(this.ui(),a.Cl.v)},g:function(b){this.Ij(e.ra(b,a.Cl.v))}},DisplayAlignment:{a:function(){return e.ta(this.Hh(),a.gi.v)},g:function(b){this.Hj(e.ra(b,a.gi.v))}},Text:{a:m.Nja},SelectionEnd:{a:m.bn,g:function(a){this.Pq(e.K(a))}},
SelectionStart:{a:m.wp,g:function(a){this.Qq(e.K(a))}},VisualStyleEdit:{a:m.j9a,g:m.yBa},NumericEditStyle:{a:function(){return e.ta(this.Nk(),a.nn.v)},g:function(b){this.Im(e.ra(b,a.nn.v))}},HasSelection:{a:m.Lv},EditStyle:{a:m.K3,g:m.yda},EditStyles:{a:m.Xja},EditMouseOverStyle:{a:m.lKa,g:m.oRa},EditMouseOverStyles:{a:m.mKa},EditFocusedStyle:{a:m.jKa,g:m.nRa},EditFocusedStyles:{a:m.kKa},LabelStyle:{a:m.S3,g:m.Cda},LabelStyles:{a:m.yKa},LabelMouseOverStyle:{a:m.wKa,g:m.DRa},LabelMouseOverStyles:{a:m.xKa},
InputType:{a:function(){return e.ta(this.Bn(),a.Ee.v)},g:function(b){this.lq(e.ra(b,a.Ee.v))}},InputTypePattern:{a:m.lr,g:function(a){this.du(e.ma(a))}},SpellCheck:{a:m.Nv,g:function(a){this.bB(e.za(a))}},Value:{a:function(){return this.Ka()},g:function(a){this.Xa(a)}}},jc:{SelectText:function(a,b){this.g_(e.K(a)-1,e.K(b))}},lg:{gg:"Value"}});c.IUb=function(a){p.w.call(this);this.wfc=a};var p=c.u(c.IUb,c.wM);p.AU=function(){return this.wfc.fs()||this.wfc.GK?!1:p.j.AU.call(this)}},{rp:["PRIM_EVP",
"PRIM_EDIT"]});
