window.LANSA.addSrc("http",function(e,c,a,b,m){c.tgb=function(){p.w.call(this);this.bb=this.Avb=""};var p=c.u(c.tgb,c.wd);p.U=function(){p.j.U.call(this)};p.hka=function(){return this.Avb};p.B7b=function(a){this.Avb=a};p.Ka=function(){return this.bb};p.Xa=function(a){this.bb=a};e.jb(c.tgb,"PRIM_WEB","HttpHeader",{Oa:{Key:{a:p.hka,g:function(a){this.B7b(e.ma(a))}},Value:{a:p.Ka,g:function(a){this.Xa(e.ma(a))}}}});c.sOa=function(){h.w.call(this);this.ab=[]};var h=c.u(c.sOa,c.wd);h.mc=function(){return this.ab.length};
h.Sd=function(a){for(var c=0;c<this.mc();c++){var d=this.mr(c);if(b.Fz(d.hka(),a))return d}return null};h.mr=function(a){if(0>a||a>=this.ab.length)throw e.IE(a,this.ab.length);return this.ab[a]};h.ph=function(a,b){var d=new c.tgb;d.B7b(a);d.Xa(b);this.ab.push(d)};h.bk=function(){this.ab=[]};h.Zs=function(a){for(var b=!1,c=0;c<this.mc()&&!(b=this.mr(c).hka()==a);c++);b&&this.ab.splice(c,1)};e.jb(c.sOa,"PRIM_WEB","HttpHeaders",{Oa:{Item:{a:function(a){return this.Sd(a)}},ItemCount:{a:h.mc}},jc:{Add:h.ph,
Remove:h.Zs,RemoveAll:h.bk},lg:{gg:"Item"},gq:{Bp:function(a){return this.mr(e.K(a-1))},Qv:h.mc}});a.FG={a:1,JGc:2,sRc:3,dTc:4,fr:5,ubd:6,rQc:7,Amc:8,EQc:9};a.FG.v={GET:a.FG.a,HEAD:a.FG.JGc,POST:a.FG.sRc,PUT:a.FG.dTc,DELETE:a.FG.fr,TRACE:a.FG.ubd,OPTIONS:a.FG.rQc,CONNECT:a.FG.Amc,PATCH:a.FG.EQc};a.sJ={j2b:1,A4b:2,U2:3,aY:4,Zzb:5};a.sJ.v={NOTEXECUTED:a.sJ.j2b,PROCESSING:a.sJ.A4b,COMPLETED:a.sJ.U2,FAILED:a.sJ.aY,CANCELLED:a.sJ.Zzb};c.G0b=function(){r.w.call(this);this.o_a="";this.G1=null;this.CYa=a.FG.a;
this.wsa=null;this.tK=new c.sOa;this.Gha=a.sJ.j2b;this.Qxb=0;this.Hfc=!1;this.Oh=null};var r=c.u(c.G0b,c.wd);r.U=function(){this.G1=null;this.fmb(null);this.Oh&&(this.Oh.xb(),this.Oh=null);r.j.U.call(this)};r.rb=function(){null==this.Oh&&(this.Oh=e.St(new c.zOa("")),this.Oh.Ca());return this.Oh};r.JA=function(){return this.o_a};r.o3c=function(a){this.o_a=a};r.bud=function(){return this.CYa};r.e1c=function(a){this.CYa=a};r.k7a=function(){return this.tK};r.UCc=function(){return this.wsa};r.fmb=function(a){null!=
this.wsa&&this.wsa.xb();this.wsa=a;null!=this.wsa&&this.wsa.Ca()};r.Gwd=function(){return this.Gha};r.sEc=function(){return this.Qxb};r.Z2c=function(a){this.Qxb=a};r.dtd=function(){return this.Hfc};r.pLd=function(a){this.Hfc=a};r.w9b=function(f,g){var d=this;d.fmb(null);var l=d.G1=new XMLHttpRequest,h=e.ta(d.CYa,a.FG.v),k=d.JA();l.onreadystatechange=function(){4==l.readyState?(d.fmb(e.St(new c.ugb(l))),0!==l.status&&(d.Gha=a.sJ.U2,d.Ga(a.G.U2),b.zy(g))):d.Gha=a.sJ.A4b};l.onerror=function(){d.Gha=
a.sJ.aY;d.Ga(a.G.aY);b.zy(g)};l.ontimeout=function(){d.Gha=a.sJ.aY;d.Ga(a.G.aY);b.zy(g)};l.open(h,k,f);f&&(l.timeout=this.Qxb);this.iic(l);h="";null!=this.Oh&&(h=this.Oh.Dq());l.send(h)};r.wia=function(){this.G1!==m&&(this.G1.abort(),this.Gha=a.sJ.Zzb)};r.VT=function(){this.w9b(!1,null)};r.w$=function(){this.w9b(!0,b.vR())};r.iic=function(a){var b=this.tK.mc();if(0!=b)for(var c=0;c<b;c++){var e=this.tK.mr(c);a.setRequestHeader(e.hka(),e.Ka())}};e.jb(c.G0b,"PRIM_WEB","HttpRequest",{Oa:{Url:{a:r.JA,
g:function(a){this.o3c(e.ma(a))}},Method:{a:function(){return e.ta(this.CYa,a.FG.v)},g:function(b){this.e1c(e.ra(b,a.FG.v))}},Content:{a:r.rb},Response:{a:r.UCc},Headers:{a:r.k7a},Status:{a:function(){return e.ta(this.Gha,a.sJ.v)}},Timeout:{a:r.sEc,g:function(a){this.Z2c(e.K(a))}}},jc:{Cancel:r.wia,Execute:r.VT,ExecuteAsync:r.w$}});c.ugb=function(a){k.w.call(this);this.G1=a;this.tK=new c.sOa;this.Oh=null;this.ENc(a.getAllResponseHeaders())};var k=c.u(c.ugb,c.wd);k.U=function(){this.G1=null;this.Oh&&
(this.Oh.xb(),this.Oh=null);k.j.U.call(this)};k.rb=function(){null==this.Oh&&(this.Oh=e.St(new c.zOa(this.G1.responseText)),this.Oh.Ca());return this.Oh};k.MDc=function(){return this.G1.status};k.NDc=function(){return this.G1.statusText};k.k7a=function(){return this.tK};k.ENc=function(a){for(var b=0,c="",e="";""!=a;){b=a.indexOf(":");if(-1==b)break;c=a.substring(0,b);a=a.slice(b+2);b=a.indexOf("\r\n");e=a.substring(0,b);a=a.slice(b+2);this.tK.ph(c,e)}};e.jb(c.ugb,"PRIM_WEB","HttpResponse",{Oa:{Content:{a:k.rb},
StatusCode:{a:k.MDc},StatusText:{a:k.NDc},Headers:{a:k.k7a}}});c.zOa=function(a){s.w.call(this);this.Fg=a};var s=c.u(c.zOa,c.wd);s.Dq=function(){return this.Fg};s.dN=function(a){this.Fg=a};e.jb(c.zOa,"PRIM_WEB","HttpContent",{Oa:{Text:{a:s.Dq,g:function(a){this.dN(e.ma(a))}}},lg:{gg:"Text"}})});
