window.LANSA.addSrc("wdgt",function(e,c,a,b,m){var p={};c.f1b=function(a){h.w.call(this);this.BEa=a;this.YVa=function(){};this.OW=this.Tvb=!1;this.pwb=[];this.owb=[];this.kwb=[];this.jwb=[];this.mwb=[]};var h=c.u(c.f1b,c.ze);h.tQ=function(){return this.Tvb};h.dh=function(){return this.BEa.nm};h.dDc=function(){return this.BEa.js||[]};h.PDc=function(){return this.BEa.st||[]};h.Byc=function(){return this.BEa.fn};h.uzc=function(){return this.BEa.fe};h.kY=function(){return this.YVa};h.JTc=function(){function a(){if(k<
m.length){var c=m[k],e=document.createElement("script");e.type="text/javascript";e.onload=function(){e.onload=null;e.onerror=null;k++;a()};e.onerror=function(){e.onload=null;e.onerror=null;throw"Error defining Widget "+d+", failed to load script: "+c;};document.body.appendChild(e);e.src=c}else b()}function b(){function a(){if(!c.Tvb){for(c.Tvb=!0;0<c.jwb.length;){var b=c.jwb.shift();c.wab(b)}for(;0<c.owb.length;)b=c.owb.shift(),c.yab(b.tsb,b.Wfd,b.value);for(;0<c.mwb.length;)b=c.mwb.shift(),c.jPb(b.tsb,
b.parent);for(;0<c.pwb.length;)b=c.pwb.shift(),c.zab(b);for(;0<c.kwb.length;)b=c.kwb.shift(),c.xab(b)}}var d=c.Byc(),f=c.YVa.prototype;e&&e(f);var g={Loading:{},Completed:{},Finalize:function(){a()}};d(f,g)!==g.Loading&&a()}var c=this,d=c.dh(),e=c.uzc();p[d]=c;for(var f=c.PDc(),g=0;g<f.length;g++){var l=f[g],h=document.createElement("link");h.type="text/css";h.rel="stylesheet";h.href=l;document.body.appendChild(h)}var k=0,m=c.dDc();a()};h.yab=function(a,b,c){if(this.tQ()){var d=a["set"+b];if(!d)throw e.zUc("set"+
b);d&&d.call(a,c)}else this.owb.push({tsb:a,Wfd:b,value:c})};h.xab=function(a){this.tQ()?a.tJa():this.kwb.push(a)};h.wab=function(a){if(this.tQ()){var b=a.onCreateInstance;b&&b.call(a)}else this.jwb.push(a)};h.jPb=function(a,b){if(this.tQ()){var c=a.onRealizeControl;if(!c)throw e.yUc();c.call(a,b)}else this.mwb.push({tsb:a,parent:b})};h.zab=function(a){if(this.tQ()){var b=a.onSizeChanged;b&&b.call(a)}else this.pwb.push(a)};c.Yfb=function(){r.w.call(this)};var r=c.u(c.Yfb,c.jn);r.Wx=function(){return this.Qa()&&
this.Qa().nGc()?this:null};r[a.$.Rv]=function(b){var c=!1;this.Qa()&&(c=b.Mc!==m?b.Mc:a.Z.wJ,c=c==a.Z.wJ||c==a.Z.hx||c==a.Z.OC?this.Qa().ZIb(null):this.Qa().$Ib(null));c||r.j.kL.call(this,b)};r[a.$.eya]=function(b){var c=!1;this.Qa()&&(c=(b.Mc!==m?b.Mc:a.Z.wJ)==a.Z.wJ?this.Qa().ZIb(document.activeElement):this.Qa().$Ib(document.activeElement));c||r.j.E3a.call(this,b)};c.$_b=function(){k.w.call(this)};var k=c.u(c.$_b,c.wd);e.kd(c.$_b,"PRIM_WDGT",{});c.b0b=function(){s.w.call(this);var a=this.YJa(),
a=this.fT=p[a],b=this.KH=new (a.kY());b.LANSA_Component=this;b.LANSA_Class=a;a.wab(b)};var s=c.u(c.b0b,c.wd);s.vab=function(a,b){if(this.fT.tQ()){var c=this.KH[a];if(!c)throw e.h5b(a);return c.apply(this.KH,b)}throw e.uQa();};s.owa=function(a){if(this.fT.tQ()){var b=this.KH["get"+a];if(!b)throw e.g5b("get"+a);return b.call(this.KH)}throw e.uQa();};s.hBa=function(a,b){this.fT.yab(this.KH,a,b)};s.v4=function(){g.j.v4.call();var a=this;setTimeout(function(){a.fT.xab(a)},5)};s.tJa=function(){this.Ga(a.G.cZ)};
e.jb(c.b0b,"PRIM_WDGT","Object",{});var f=s;f.get=f.owa;f.set=f.hBa;f.invoke=f.vab;c.a0b=function(){g.w.call(this);var b=this.YJa(),b=this.fT=p[b],c=this.KH=new (b.kY());c.LANSA_Component=this;c.LANSA_Class=b;b.wab(c);this.ug&=~a.Xg.zQ;this.ug&=~a.Xg.lZ};var g=c.u(c.a0b,c.Yfb);g.fh=function(){return c.e1b};g.Ld=function(a,c,d){g.j.Ld.call(this,a,c,d);a=this.Qa().ib();b.Od[a].ANc(this.KH)};g.vab=function(a,b){if(this.fT.tQ()){var c=this.KH[a];if(!c)throw e.h5b(a);return c.apply(this.KH,b)}throw e.uQa();
};g.owa=function(a){if(this.fT.tQ()){var b=this.KH["get"+a];if(!b)throw e.g5b("get"+a);return b.call(this.KH)}throw e.uQa();};g.hBa=function(a,b){this.fT.yab(this.KH,a,b)};g.bFd=function(){this.tJa()};g[a.$.Jba]=function(){this.fT.xab(this)};g[a.$.HG]=function(){this.Qb()&&this.fT.zab(this.KH)};g.Yca=function(){g.j.Yca.call(this);this.Qb()&&this.fT.zab(this.KH)};e.jb(c.a0b,"PRIM_WDGT","Control",{});f=g;f.get=f.owa;f.set=f.hBa;f.invoke=f.vab;c.V_b=function(){d.w.call(this);this.nd=b.Ad(0,0,100,100);
this.cEa=this.GEa=""};var d=c.u(c.V_b,c.Yfb);d.fh=function(){return c.F0b};d.kAc=function(){return this.GEa};d.v0c=function(b){this.GEa!=b&&(this.GEa=b,this.ca(a.f.h),this.Jd())};d.eU=function(){return this.cEa};d.Wkb=function(a){this.cEa=a};d.KC=function(a){var d=this.Ap(),e=this.tr();if(d||e){var f=new c.ga,g=[];g[0]=d;g[1]=e;g[2]=a;g[3]=0;g[4]=0;var l=this.ib();g[3]=0;g[4]=0;null!=l&&b.Od[l].ucd(g);f.Ra(g[3]);f.Ha(g[4]);d&&a.Ra(a.Q()+this.ea.oj()+f.aa()+this.ea.Ik());e&&a.Ha(a.O()+this.ea.Jk()+
f.ba()+this.ea.wm())}};e.jb(c.V_b,"PRIM_WEB","HtmlContainer",{Oa:{Html:{a:d.kAc,g:function(a){this.v0c(e.ma(a))}},Description:{a:d.eU,g:function(a){this.Wkb(e.ma(a))}}},lg:{gg:"Html"}});c.mgb=function(a){l.w.call(this,a)};var l=c.u(c.mgb,c.kn);l.SLa=function(){return!1};l.VLa=function(){return this.pa.fs()||this.pa.GK?!1:!0};l.nGc=function(){return 0<this.B1a().length};l.DM=function(a){l.j.DM.call(this,a);return!1};l.ZIb=function(a){var b=this.B1a();for(a=a?b.indexOf(a)+1:0;0<=a&&a<b.length;){var c=
b[a];if(c&&(c.focus(),c==document.activeElement))return!0;a++}return!1};l.$Ib=function(a){var b=this.B1a();for(a=a?b.indexOf(a)-1:b.length-1;0<=a;){var c=b[a];if(c&&(c.focus(),c==document.activeElement))return!0;a--}return!1};l.B1a=function(){var a=[],b=[];this.q3b(this.H,b);for(var c=1;c<b.length;c++)a=a.concat(b[c]||[]);return a=a.concat(b[0]||[])};l.q3b=function(a,b){var c=a.tabIndex;0<=c&&(b[c]===m&&(b[c]=[]),b[c].push(a));for(var c=a.childNodes,d=0;d<c.length;d++)a=c[d],this.q3b(a,b)};l.r3=l[a.Ma.pN]=
function(b){b.Ue=a.Ma.Ria|a.Ma.PHa};c.e1b=function(a){u.w.call(this,a);this.eb=null};var u=c.u(c.e1b,c.mgb);u.lf=function(a,b){this.H=document.createElement("div");this.H.setAttribute("id",a+this.gc);this.H.setAttribute("LANSAHandle",this.gc);return u.j.lf.call(this,a,b)};u.ANc=function(a){null==this.eb&&(this.eb=document.createElement("div"),this.eb.style.left="0px",this.eb.style.top="0px",this.eb.style.width="100%",this.eb.style.height="100%",a.LANSA_Class.jPb(a,this.eb),this.H.appendChild(this.eb))};
c.F0b=function(a){z.w.call(this,a);this.eb=null};var z=c.u(c.F0b,c.mgb);z.iz=function(){z.j.iz.call(this);this.H.style.whiteSpace="normal"};z.lf=function(a,b){this.H=document.createElement("div");this.H.setAttribute("id",a+this.gc);this.H.setAttribute("LANSAHandle",this.gc);this.eb=document.createElement("div");this.eb.style.left="0px";this.eb.style.top="0px";this.eb.style.width="100%";this.eb.style.height="100%";this.eb.innerHTML=this.pa.GEa;this.H.appendChild(this.eb);return z.j.lf.call(this,a,
b)};z.hcd=function(){var a=this.pa.Ap(),b=this.pa.tr();this.eb.style.width=a?"":"100%";this.eb.style.height=b?"":"100%";this.eb.innerHTML=this.pa.GEa};z.Ld=function(){z.j.Ld.call(this);this.hcd()};z.ucd=function(a){var b=a[0],c=a[2],d=this.eb.style.width;a[1]&&!b&&(this.eb.style.width=c.aa()+"px");a[3]=this.eb.clientWidth;a[4]=this.eb.clientHeight;this.eb.style.width=d}});
