window.LANSA.addSrc("labl",function(e,c,a,b){a.asb={JQd:0,esb:16};a.rZ={vNc:1,idb:1,hdb:2,cTb:240};a.edb={COa:0,p1b:1};c.Ws=function(){m.w.call(this);this.Ds=a.xo.s$;this.xS=a.rZ.vNc;this.Oga=a.edb.COa;this.pB=this.BB=this.xB=this.IB=0;this.Bk=null;this.QN=a.ak.UQ;this.Ia=null;this.vv=0;this.NW=a.je.lH;this.I1=new c.ga;this.VH=new c.ga;this.Qc=this.Qc|a.ac.Gba|a.ac.Txa|a.ac.hcb|a.ac.zE|a.ac.RU|a.ac.icb|a.ac.yE;this.ug=this.ug|a.Xg.Ila|a.Xg.zQ|a.Xg.lZ;this.Df(!1);this.noa(!1)};var m=c.u(c.Ws,c.Vs);
m.U=function(){this.Bk&&(this.Bk.Da(this,this.x3a),this.Bk=null);m.j.U.call(this);this.$c(null)};m.fh=function(){return c.vgb};m.YA=function(c){this.Bk!=c&&(this.Bk&&this.Bk.Da(this,this.x3a),this.Bk=c,null==this.Bk?this.noa(!1):(this.noa(!0),this.Bk.Ea(this,this.x3a)),this.l(a.f.h),b.cb().Cd(this,!1))};m.bE=function(){return this.Bk};m.Nd=function(){return 0!=(this.xS&a.rZ.idb)?!0:!1};m.Rw=function(){return!this.Ap()&&this.Nd()};m.Re=function(c){c=this.xS&~a.rZ.idb|(c?a.rZ.idb:0);this.xS!=c&&(this.xS=
c,this.Jd(),b.cb().Cd(this,!1),this.ca(a.f.h))};m.hLa=function(){return 0!=(this.xS&a.rZ.hdb)?!0:!1};m.r8b=function(b){b=this.xS&~a.rZ.hdb|(b?a.rZ.hdb:0);this.xS!=b&&(this.xS=b,this.ih(),this.ca(a.f.h))};m.ZMd=function(c){this.HLa()!=c&&(this.xS=this.xS&~a.rZ.cTb|c,this.Jd(),b.cb().Cd(this,!1),this.ca(a.f.h))};m.HLa=function(){return this.xS&a.rZ.cTb};m.Gf=function(c){this.Ds!=c&&(this.Ds=c,b.cb().Cd(this,!1),this.ca(a.f.h))};m.We=function(){return this.Ds};m.Xe=function(){return this.IB};m.Ge=function(c){this.IB!=
c&&(this.IB=c,this.Jd(),b.cb().Cd(this,!1),this.ca(a.f.h))};m.bf=function(){return this.xB};m.re=function(c){this.xB!=c&&(this.xB=c,this.Jd(),b.cb().Cd(this,!1),this.ca(a.f.h))};m.Sf=function(){return this.BB};m.Ud=function(c){this.BB!=c&&(this.BB=c,this.Jd(),b.cb().Cd(this,!1),this.ca(a.f.h))};m.kg=function(){return this.pB};m.Se=function(c){this.pB!=c&&(this.pB=c,this.Jd(),b.cb().Cd(this,!1),this.ca(a.f.h))};m.rs=function(c){this.QN!=c&&(this.QN=c,b.cb().Cd(this),this.l(a.f.h))};m.Hc=function(){return this.Ia};
m.$c=function(c){this.Ia!=c&&(null!=this.Ia&&(this.Ia.Da(this,this.Tm),this.Ia.xb()),this.Ia=c,null!=this.Ia&&(this.Ia.Ca(),this.Ia.Ea(this,this.Tm)),this.Jd(),b.cb().Cd(this),this.l(a.f.h))};m.Lu=function(){return this.QN};m.Lw=function(){return this.vv};m.Wu=function(c){c!=this.vv&&(this.vv=c,this.Jd(),this.ca(a.f.h),b.cb().Cd(this))};m.HL=function(){return this.NW};m.HJ=function(b){this.NW!=b&&(this.NW=b,this.Jd(),this.l(a.f.h))};m.zm=function(){var b=a.he.EE;switch(this.Rf()){case a.Ng.sA:switch(this.zU()){case a.Vg.qq:b=
a.he.EE;break;case a.Vg.lN:b=a.he.qPa;break;default:b=a.he.sPa}break;case a.Ng.dI:switch(this.zU()){case a.Vg.qq:b=a.he.rPa;break;case a.Vg.lN:b=a.he.$2b;break;default:b=a.he.b3b}break;default:switch(this.zU()){case a.Vg.qq:b=a.he.QZ;break;case a.Vg.lN:b=a.he.Z2b;break;default:b=a.he.QQ}}return b};m.wC=function(){return 0!=(this.Oga&a.edb.p1b)};m.MAd=function(a){this.Oga|=a};m.zKc=function(a){this.Oga&=~a};m.NAd=function(a,b){this.Oga=this.Oga&~a|(b?a:0)};m.Ld=function(a,b,c){m.j.Ld.call(this,a,b,
c);this.Kq(!1)};m.D5=function(a){m.j.D5.call(this,a);this.Kq(a)};m.Kq=function(a){m.j.Kq.call(this,a);a=this.Oe();this.FFb(a,!1)};m.Fj=function(){m.j.Fj.call(this);this.xd(a.$.PA);this.xd(a.$.bya)};m.Zc=function(){this.YH(a.ac.fM,this.bM());m.j.Zc.call(this)};m.Hq=function(a){null!=this.Bk?this.Bk.ef():m.j.Hq.call(this,a)};m.zg=function(){this.UZ();b.cb().PB(this)};m.IC=function(){this.kT()};m.GE=function(a){var b=!1,b=a.ee().hQa(this,this.ea.$h,this.Ibb(),this.Kbb(),this.Jbb(),a);!1==b&&m.j.GE.call(this,
a)};m.te=function(b){""==b[1]&&(b[1]=a.qSb);m.j.te.call(this,b)};m.FFb=function(a,e){var k=b.Cc(a),m=b.Cc(k),f=null,g=0<this.vv?this.vv:-1;this.Ia&&(f=this.Ia.TAb(k.ba()-4,k.ba()-4));k.Ua(k.O()+this.IB);k.Ta(k.Q()+this.xB);k.Ra(k.va-this.BB);k.Ha(k.ua-this.pB);var d=this.kb(),l=new c.ga,u=new c.ga,z=[],t="";z[0]=l;z[1]=m;z[2]=u;z[3]=g;z[4]=g;z[5]=0;this.wAa(null,f,d,this.me(),k,z);l=z[0];m=z[1];k=z[5];this.Ia&&this.Ia instanceof c.lM&&(t=this.Ia.zh());this.I1=l;this.VH=m;e||(f=this.Qa().ib(),g=this.Rw(),
b.Od[f].Ug(f,m,t,l,g,this.hLa(),k))};m.wAa=function(e,m,k,s,f,g){e=g[0];var d=g[1],l=g[2],u=g[3],z=g[4],t=g[5],d=b.Cc(f);if(null!=m&&this.Dd()){var p=a.Hf.PBa;this.bE()||(p|=a.Hf.gTa);t=p;if(this.Rw())switch(this.HLa()){case a.asb.esb:p|=a.Hf.dB;break;default:p|=a.Hf.dB,t|=a.Hf.dB}else t|=this.Ds;switch(this.Rf()){case a.Ng.sA:t|=a.Hf.eea;break;case a.Ng.dI:t|=a.Hf.RBa;break;default:t|=a.Hf.Sob}b.Wla(m,k,s,f,0,this.zm(),this.zm(),this.Lu(),e,d,l,0,this.Dd()?0:2,u,z,p)}else if(t=this.Yzb(d),0<k.length){d.aa()>
f.aa()&&(this.Rw()?this.HLa()==a.asb.esb&&(d=new c.ga(0,0,f.aa(),d.ba())):d=new c.ga(0,0,f.aa(),d.ba()));switch(this.Rf()){case a.Ng.sA:d=new c.ga(f.Q()+(f.aa()-d.aa())/2,1,d.aa(),d.ba());t|=a.Hf.eea;break;case a.Ng.dI:d=new c.ga(f.va-d.aa(),1,d.aa(),d.ba());t|=a.Hf.RBa;break;default:d=new c.ga(f.Q(),1,d.aa()+1,d.ba()),t|=a.Hf.Sob}switch(this.zU()){case a.Vg.qq:d=new c.ga(d.Q(),f.O()+(f.ba()-d.ba())/2,d.aa(),d.ba());break;case a.Vg.lN:d=new c.ga(d.Q(),f.ua-1-d.ba(),d.aa(),d.ba())}}g[0]=e;g[1]=d;g[2]=
l;g[3]=u;g[4]=z;g[5]=t};m.Yzb=function(c){var e=this.me(),k=a.Hf.PBa,m=this.kb();if(0<m.length)if(this.bE()||(k|=a.Hf.gTa),this.Uz=b.CM(m,e,this.Rw(),c.aa(),c.ba()),this.Rw())switch(this.HLa()){case a.asb.esb:b.AC(m,c,k|a.Hf.dB,e);break;default:b.AC(m,c,k|a.Hf.dB,e),k|=a.Hf.dB}else b.AC(m,c,k,e),k|=this.Ds;return k};m.Slc=function(){var a=b.EQ();this.$j(!1,!0);this.Yzb(a);this.Yb(a.aa())};m.JC=function(c){if(this.hLa())switch(b.xr(c)){case a.Z.NQa:case a.Z.d6b:case a.Z.k6b:case a.Z.gda:case a.Z.l6b:case a.Z.nWc:case a.Z.SXc:case a.Z.g6b:case a.Z.ZXc:case a.Z.PQa:c.il(!0);
return}m.j.JC.call(this)};m.KC=function(a){var b=this.Ap(),c=this.tr();(b||c)&&this.b4b(a,b,c)};m.b4b=function(a,e,k){var m=new c.ga,f=new c.ga(0,0,1E4,1E4);this.Rw()&&f.Ra(f.Q()+a.aa()-(this.ea.oj()+this.ea.Ik()));this.FFb(f,!0);""==this.kb()&&this.I1.ag()||(""==this.kb()?m=this.I1:(m=b.Cc(this.VH),m.Ha(m.ua+(0<this.VH.ba()?1:0)),m=m.B0(this.I1)));e&&a.Ra(a.Q()+this.ea.oj()+this.xB+m.aa()+this.BB+this.ea.Ik());k&&a.Ha(a.O()+this.ea.Jk()+this.IB+m.ba()+this.pB+this.ea.wm())};m.Nca=function(a,b,c){m.j.Nca(a,
b,c);c[0]&&this.hLa()&&(c[0]=!1)};m.Af=function(a){b.dfb();return m.j.Af.call(this,a)};m.Tm=function(c,e){switch(e.Ya){case a.f.sb:case a.f.Ob:e.Ii==this.Ia&&this.$c(null);break;case a.f.h:e.Ii==this.Ia&&(b.cb().Cd(this),this.Jd())}};m.x3a=function(b,c){c.Ya==a.f.Ob&&this.YA(null)};m.Gu=m[a.$.HG]=function(a){m.j.Gu.call(this,a);b.cb().Cd(this,!1)};m.Akd=m[a.$.bya]=function(){b.cb().Cd(this,!1)};m.mL=m[a.$.PA]=function(){b.cb().Cd(this,!1)};m.kja=m[a.$.lya]=function(a){this.Bz()?this.Df(!1):m.j.kja.call(this,
a)};m.lL=m[a.$.cJ]=function(){this.Bk&&this.Bk.ef()};m.oz=m[a.$.OA]=function(b){this.wC()&&(this.Oo(),this.zKc(a.edb.p1b));m.j.oz.call(this,b)};e.kd(c.Ws,"PRIM_LABL",{Oa:{Ellipses:{a:function(){return e.ta(this.We(),a.xo.v)},g:function(b){this.Gf(e.ra(b,a.xo.v))}},Caption:{a:m.kb,g:function(a){this.Ab(e.ma(a))}},Alignment:{a:function(){return e.ta(this.Rf(),a.Ng.v)},g:function(b){this.yb(e.ra(b,a.Ng.v))}},VerticalAlignment:{a:function(){return e.ta(this.zU(),a.Vg.v)},g:function(b){this.Ln(e.ra(b,
a.Vg.v))}},FocusControl:{a:m.bE,g:m.YA},WordWrap:{a:m.Nd,g:function(a){this.Re(e.za(a))}},Selectable:{a:m.hLa,g:function(a){this.r8b(e.za(a))}},MarginLeft:{a:m.bf,g:function(a){this.re(e.K(a))}},MarginTop:{a:m.Xe,g:function(a){this.Ge(e.K(a))}},MarginBottom:{a:m.kg,g:function(a){this.Se(e.K(a))}},MarginRight:{a:m.Sf,g:function(a){this.Ud(e.K(a))}},Image:{a:m.Hc,g:m.$c},ImagePosition:{a:function(){return e.ta(this.Lu(),a.ak.v)},g:function(b){this.rs(e.ra(b,a.ak.v))}},ImageHeight:{a:m.Lw,g:function(a){this.Wu(e.K(a))}},
ImageSizing:{a:function(){return e.ta(this.HL(),a.je.v)},g:function(b){this.HJ(e.ra(b,a.je.v))}}},lg:{gg:"Caption"}});c.vgb=function(a){p.w.call(this,a);this.ZVa=this.vv=this.KEa=this.ovb=this.nvb=this.Ia=this.RF=this.Nha=this.CD=this.Lxb=this.Kxb=this.Jxb=this.nb=null};var p=c.u(c.vgb,c.kn);p.kb=function(){return this.nb.textContent};p.Ab=function(a){this.nb.textContent=a};p.R3=function(){return this.nb};p.FL=function(){return this.nb};p.Ug=function(b,c,k,m,f,g,d){null==this.Ia.parentElement&&this.H.appendChild(this.Ia);
if(null==this.ZVa||this.ZVa!=g)this.ZVa=g,this.nb.spellcheck=!1,this.nb.setAttribute("contenteditable",g);this.Ia.style.backgroundImage=e.Fu(k);switch(this.pa.HL()){case a.je.lH:this.Ia.style.backgroundSize="contain";break;case a.je.HBa:this.Ia.style.backgroundSize="cover";break;case a.je.Lf:this.Ia.style.backgroundSize="100% 100%";break;case a.je.Wd:this.Ia.style.backgroundSize="auto"}if(null==this.RF||this.RF!=f)this.RF=f,this.nb.style.whiteSpace=f?"pre-wrap":"pre";if(null==this.Nha||this.Nha!=
d)this.Nha=d,this.nb.style.textAlign=0!=(d&a.Hf.RBa)?"right":0!=(d&a.Hf.eea)?"center":"",0!=(d&a.Hf.OBa)||0!=(d&a.Hf.QBa)||0!=(d&a.Hf.SBa)?(this.nb.style.textOverflow="ellipsis",this.nb.style.overflow="hidden"):(this.nb.style.textOverflow="clip",this.nb.style.overflow="visible");if(null==this.Jxb||this.Jxb!=c.Q())this.Jxb=c.Q(),this.nb.style.left=c.Q()+"px";if(null==this.Kxb||this.Kxb!=c.O())this.Kxb=c.O(),this.nb.style.top=c.O()+"px";if(null==this.CD||this.CD!=c.ba())this.CD=c.ba(),this.nb.style.height=
c.ba()+"px";if(null==this.Lxb||this.Lxb!=c.aa())this.Lxb=c.aa(),this.nb.style.width=c.aa()+"px";if(null==this.nvb||this.nvb!=m.Q())this.nvb=m.Q(),this.Ia.style.left=m.Q()+"px";if(null==this.ovb||this.ovb!=m.O())this.ovb=m.O(),this.Ia.style.top=m.O()+"px";if(null==this.vv||this.vv!=m.ba())this.vv=m.ba(),this.Ia.style.height=m.ba()+"px";if(null==this.KEa||this.KEa!=m.aa())this.KEa=m.aa(),this.Ia.style.width=m.aa()+"px"};p.lf=function(a,b){this.H=document.createElement("div");this.H.setAttribute("LANSAHandle",
this.gc);this.nb=document.createElement("div");var c=this.nb.style;c.position="absolute";c.outline="none";c.overflowX="hidden";c.overflowY="hidden";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";c.borderStyle="solid";c.borderLeftWidth="0px";c.borderTopWidth="0px";c.borderRightWidth="0px";c.borderBottomWidth="0px";c.cursor="inherit";c.textDecoration="inherit";this.Ia=document.createElement("div");c=this.Ia.style;c.position="absolute";c.backgroundSize="contain";
c.backgroundPosition="center center";c.backgroundRepeat="no-repeat";this.H.appendChild(this.nb);this.H.appendChild(this.Ia);return p.j.lf.call(this,a,b)};p.IX=function(){var a=this;this.L2();a.nb.addEventListener("paste",function(b){a.Jca(b);b.preventDefault()},!1)};p.mrb=function(){var a="";p.j.mrb.call(this);"rgba(0,0,0,0)"==this.yVa&&""!=this.H.style.boxShadow&&(a=this.H.style.boxShadow);this.nb.style.textShadow=a};p.DM=function(a){p.j.DM.call(this,a);return!this.ZVa};p.Jca=function(){}});
