window.LANSA.addSrc("video",function(e,c,a,b,m){var p,h;p={ALL:0,METADATA:1,NONE:2};h={auto:0,metadata:1,none:2};c.LNa=function(a){r.w.call(this);this.A1=this.Es="";this.Ffa=a};var r=c.u(c.LNa,c.wd);r.U=function(){r.j.U.call(this)};r.zh=function(){return this.Es};r.gw=function(a){this.Es=a};r.pY=function(){return this.A1==m?"":this.A1};r.n_=function(a){this.A1=a};r.fr=function(){for(var a=0;a<this.Ffa.mc();a++)this.Ffa.mr(a)===this&&this.Ffa.zr(a)};e.jb(c.LNa,"PRIM_VDEO","File",{Oa:{FileName:{a:r.zh,
g:function(a){this.gw(e.ma(a))}},FileExtension:{a:r.pY,g:function(a){this.n_(e.ma(a))}}},jc:{Delete:r.fr},lg:{gg:"FileExtension"}});c.Leb=function(a){k.w.call(this);this.vhc=a;this.ab=[]};var k=c.u(c.Leb,c.wd);k.mc=function(){return this.ab.length};k.Sd=function(a){return this.mr(a)};k.mr=function(a){if(0>a||a>=this.ab.length)throw e.IE(a,this.ab.length);return this.ab[a]};k.ph=function(a,b){var e=new c.LNa(this);e.gw(a);e.n_(b);this.ab.push(e);(e=this.vhc.Qa())&&e.Jr()};k.Mva=function(){0==this.mc()&&
this.ab.push(new c.LNa(this));return this.mr(0)};k.bk=function(){this.ab=[];var a=this.vhc.Qa();a&&a.Jr()};k.zr=function(a){if(null==this.mr(a))throw e.IE(a,this.ab.length);this.ab.splice(a,1)};k.QTc=function(a){for(var b=!1,c=0;c<this.mc()&&!(b=this.mr(c).zh()==a);c++);b&&this.zr(c)};e.jb(c.Leb,"PRIM_VDEO","Files",{Oa:{Item:{a:function(a){return this.mr(e.K(a)-1)}}},jc:{Add:k.ph,RemoveAll:k.bk,Remove:function(a){return this.zr(e.K(a)-1)}},gq:{Bp:function(a){return this.mr(e.K(a)-1)},Qv:function(){return this.mc()}},
lg:{gg:"Item"}});c.L_b=function(){s.w.call(this);this.a1=0;this.O0=this.m2=!0;this.NS=1;this.vw=new c.Leb(this);this.Ph=-1;this.sS=this.Jga=this.Lga=!1;this.JB=50};var s=c.u(c.L_b,c.Vs);s.fh=function(){return c.d1b};s.U=function(){s.j.U.call(this)};s.zh=function(){return 0<this.vw.mc()?this.vw.mr(0).zh():""};s.gw=function(b){this.vw.bk();var c=this.vw.Mva();c.zh()!=b&&(c.gw(b),(b=this.Qa())&&b.Jr(),this.l(a.f.h))};s.pY=function(){return 0<this.vw.mc()?this.vw.mr(0).pY():""};s.n_=function(b){var c=
this.vw.Mva();c.pY()!=b&&(c.n_(b),(b=this.Qa())&&b.Jr(),this.l(a.f.h))};s.Izc=function(){return this.vw};s.K6a=function(){return this.a1};s.Tkb=function(b){this.a1!=b&&(this.a1=b,(b=this.Qa())&&b.Jr(),this.l(a.f.h))};s.s7a=function(){return this.sS};s.i8a=function(){return this.m2};s.mmb=function(b){this.m2!=b&&(this.m2=b,(b=this.Qa())&&b.Jr(),this.l(a.f.h))};s.d6a=function(){return this.O0};s.wkb=function(b){this.O0!=b&&(this.O0=b,(b=this.Qa())&&b.Jr(),this.l(a.f.h))};s.J3=function(){return this.Ph};
s.t7a=function(){return this.Lga};s.r7a=function(){return this.Jga};s.k9a=function(){return this.JB};s.zBa=function(c){c=b.Pg(c,0,100);this.JB!=c&&(this.JB=c,this.sS=0==this.JB,(c=this.Qa())&&c.Jr(),this.l(a.f.h))};s.uCc=function(){return this.NS};s.dmb=function(b){this.NS!=b&&(this.NS=b,(b=this.Qa())&&b.Jr(),this.l(a.f.h))};s.Play=function(){this.Qa()&&this.Qa().Play()};s.Xh=function(){this.Qa()&&this.Qa().Xh()};s.Hhb=function(){this.zBa(0)};s.Vvc=function(){if(this.Qa()){var a=this.Qa().H;a.currentTime=
Math.min(a.duration,a.currentTime+5)}};s.Uvc=function(){if(this.Qa()){var a=this.Qa().H;0<a.currentTime&&(a.currentTime-=5)}};e.kd(c.L_b,"PRIM_VDEO",{Oa:{FileName:{a:s.zh,g:function(a){this.gw(e.ma(a))}},CycleToStart:{a:s.K6a,g:function(a){this.Tkb(e.za(a))}},ShowControls:{a:s.i8a,g:function(a){this.mmb(e.za(a))}},Autoplay:{a:s.d6a,g:function(a){this.wkb(e.za(a))}},Preload:{a:function(){return e.ta(this.NS,p)},g:function(a){this.dmb(e.ra(a,p))}},Duration:{a:s.J3},IsMuted:{a:s.s7a},IsPlaying:{a:s.t7a},
IsEnded:{a:s.r7a},Volume:{a:s.k9a,g:function(a){this.zBa(e.K(a))}}},jc:{Play:s.Play,Stop:s.Xh,Mute:s.Hhb,FrameForward:s.Vvc,FrameBackward:s.Uvc}});c.d1b=function(a){f.w.call(this,a)};var f=c.u(c.d1b,c.kn);f.lf=function(b,c){this.H=document.createElement("video");this.EDa=b+this.gc;this.H.setAttribute("id",this.EDa);this.H.setAttribute("LANSAHandle",this.gc);this.H.style.position="absolute";this.H.style.overflow="hidden";this.H.style.whiteSpace="nowrap";this.Jr();var e=this.H,h=this;e.addEventListener("loadedmetadata",
function(){h.pa.Ph=e.duration;h.pa.Ga(a.G.jTb)},!1);e.addEventListener("loadeddata",function(){h.pa.Ga(a.G.iTb)},!1);e.addEventListener("play",function(){h.pa.Lga=!0;h.pa.Jga=!1;h.pa.Ga(a.G.f3b)},!1);e.addEventListener("pause",function(){h.pa.Lga=!1;h.pa.Ga(a.G.u9b)},!1);e.addEventListener("ended",function(){h.H.pause();h.H.paused=!0;h.pa.Jga=!0;h.pa.Ga(a.G.Vx)},!1);e.addEventListener("volumechange",function(){e.muted||0==e.volume?(h.H.muted=!0,h.pa.sS=!0,h.pa.JB=0,h.pa.Ga(a.G.d2b)):(h.pa.sS=!1,h.pa.JB=
Math.round(100*e.volume))},!1);return f.j.lf.call(this,b,c)};f.Jr=function(){this.boa("controls",this.pa.m2);this.boa("autoplay",this.pa.O0);this.boa("loop",this.pa.a1);this.H.setAttribute("preload",e.ta(this.pa.NS,h));this.H.volume=0<this.pa.JB?this.pa.JB/100:0;this.H.muted=this.pa.sS;this.trb()};f.trb=function(){this.Bjb();var a=this.pa.vw.mc();if(0!=a)for(var b=0;b<a;b++){var c=this.pa.vw.mr(b);this.tic(this.H,c.Es,c.A1)}};f.tic=function(a,b,c){var e=document.createElement("source");e.src=b;c&&
(e.type="video/"+c);a.appendChild(e)};f.Bjb=function(){var a=document.getElementById(this.EDa);if(a&&(a=a.childNodes)){var b,c,e=[];for(c=0;c<a.length;c++)b=a[c],"SOURCE"==b.nodeName&&e.push(b);for(c=0;c<e.length;c++)b=e[c],b.parentNode.removeChild(b)}};f.DM=function(){return!1};f.LOa=function(){};f.Play=function(){this.H.play!==m&&this.H.play()};f.Xh=function(){this.H.pause!==m&&this.H.pause()}});
