window.LANSA.addSrc("wdgt",function(d,c,a,b,p){var u={};c.l5b=function(a){t.H.call(this);this.yHa=a;this.rZa=function(){};this.zP=this.Bzb=!1;this.Yzb=[];this.Xzb=[];this.Tzb=[];this.Szb=[];this.Vzb=[]};var t=c.q(c.l5b,c.Ie);t.kS=function(){return this.Bzb};t.zh=function(){return this.yHa.nm};t.FHc=function(){return this.yHa.js||[]};t.pIc=function(){return this.yHa.st||[]};t.hDc=function(){return this.yHa.fn};t.aEc=function(){return this.yHa.fe};t.OZ=function(){return this.rZa};t.vYc=function(){function a(){if(q<
m.length){var c=m[q],e=document.createElement("script");e.type="text/javascript";e.onload=function(){e.onload=null;e.onerror=null;q++;a()};e.onerror=function(){e.onload=null;e.onerror=null;throw"Error defining Widget "+d+", failed to load script: "+c;};document.body.appendChild(e);e.src=c}else b()}function b(){function a(){if(!c.Bzb){for(c.Bzb=!0;0<c.Szb.length;){var b=c.Szb.shift();c.Xdb(b)}for(;0<c.Xzb.length;)b=c.Xzb.shift(),c.Zdb(b.$vb,b.Gkd,b.value);for(;0<c.Vzb.length;)b=c.Vzb.shift(),c.lTb(b.$vb,
b.parent);for(;0<c.Yzb.length;)b=c.Yzb.shift(),c.$db(b);for(;0<c.Tzb.length;)b=c.Tzb.shift(),c.Ydb(b)}}var d=c.hDc(),g=c.rZa.prototype;e&&e(g);var f={Loading:{},Completed:{},Finalize:function(){a()}};d(g,f)!==f.Loading&&a()}var c=this,d=c.zh(),e=c.aEc();u[d]=c;for(var g=c.pIc(),f=0;f<g.length;f++){var h=g[f],k=document.createElement("link");k.type="text/css";k.rel="stylesheet";k.href=h;document.body.appendChild(k)}var q=0,m=c.FHc();a()};t.Zdb=function(a,b,c){if(this.kS()){var e=a["set"+b];if(!e)throw d.lZc("set"+
b);e&&e.call(a,c)}else this.Xzb.push({$vb:a,Gkd:b,value:c})};t.Ydb=function(a){this.kS()?a.YLa():this.Tzb.push(a)};t.Xdb=function(a){if(this.kS()){var b=a.onCreateInstance;b&&b.call(a)}else this.Szb.push(a)};t.lTb=function(a,b){if(this.kS()){var c=a.onRealizeControl;if(!c)throw d.kZc();c.call(a,b)}else this.Vzb.push({$vb:a,parent:b})};t.$db=function(a){if(this.kS()){var b=a.onSizeChanged;b&&b.call(a)}else this.Yzb.push(a)};c.yjb=function(){r.H.call(this)};var r=c.q(c.yjb,c.qo);r.Ly=function(){return this.Sa()&&
this.Sa().RKc()?this:null};r[a.Z.Pw]=function(b){var c=!1;this.Sa()&&(c=b.Qc!==p?b.Qc:a.W.ZK,c=c==a.W.ZK||c==a.W.ay||c==a.W.LD?this.Sa().OMb(null):this.Sa().PMb(null));c||r.j.UM.call(this,b)};r[a.Z.cBa]=function(b){var c=!1;this.Sa()&&(c=(b.Qc!==p?b.Qc:a.W.ZK)==a.W.ZK?this.Sa().OMb(document.activeElement):this.Sa().PMb(document.activeElement));c||r.j.u7a.call(this,b)};c.e4b=function(){m.H.call(this)};var m=c.q(c.e4b,c.Gd);d.wd(c.e4b,"PRIM_WDGT",{});c.g4b=function(){k.H.call(this);var a=this.EMa(),
a=this.TU=u[a],b=this.eJ=new (a.OZ());b.LANSA_Component=this;b.LANSA_Class=a;a.Xdb(b)};var k=c.q(c.g4b,c.Gd);k.Wdb=function(a,b){if(this.TU.kS()){var c=this.eJ[a];if(!c)throw d.t9b(a);return c.apply(this.eJ,b)}throw d.kTa();};k.nza=function(a){if(this.TU.kS()){var b=this.eJ["get"+a];if(!b)throw d.s9b("get"+a);return b.call(this.eJ)}throw d.kTa();};k.mEa=function(a,b){this.TU.Zdb(this.eJ,a,b)};k.E_=function(){f.j.E_.call();var a=this;setTimeout(function(){a.TU.Ydb(a)},5)};k.YLa=function(){this.Ca(a.w.T5)};
d.mb(c.g4b,"PRIM_WDGT","Object",{});var h=k;h.get=h.nza;h.set=h.mEa;h.invoke=h.Wdb;c.f4b=function(){f.H.call(this);var b=this.EMa(),b=this.TU=u[b],c=this.eJ=new (b.OZ());c.LANSA_Component=this;c.LANSA_Class=b;b.Xdb(c);this.Jg&=~a.qh.pS;this.Jg&=~a.qh.P_};var f=c.q(c.f4b,c.yjb);f.hh=function(){return c.k5b};f.Pd=function(a,c,d){f.j.Pd.call(this,a,c,d);a=this.Sa().fb();b.Xd[a].jSc(this.eJ)};f.Wdb=function(a,b){if(this.TU.kS()){var c=this.eJ[a];if(!c)throw d.t9b(a);return c.apply(this.eJ,b)}throw d.kTa();
};f.nza=function(a){if(this.TU.kS()){var b=this.eJ["get"+a];if(!b)throw d.s9b("get"+a);return b.call(this.eJ)}throw d.kTa();};f.mEa=function(a,b){this.TU.Zdb(this.eJ,a,b)};f.bKd=function(){this.YLa()};f[a.Z.qda]=function(){this.TU.Ydb(this)};f[a.Z.WH]=function(){this.Ub()&&this.TU.$db(this.eJ)};f.Fea=function(){f.j.Fea.call(this);this.Ub()&&this.TU.$db(this.eJ)};d.mb(c.f4b,"PRIM_WDGT","Control",{});h=f;h.get=h.nza;h.set=h.mEa;h.invoke=h.Wdb;c.$3b=function(){e.H.call(this);this.Mb=b.Hg(0,0,100,100);
this.YGa=this.DHa=""};var e=c.q(c.$3b,c.yjb);e.hh=function(){return c.K4b};e.LEc=function(){return this.DHa};e.r5c=function(b){this.DHa!=b&&(this.DHa=b,this.ea(a.g.h),this.yd())};e.QV=function(){return this.YGa};e.Aob=function(a){this.YGa=a};e.CA=function(a){var d=this.mo(),e=this.iq();if(d||e){var g=new c.fa;new c.fa(0,0,1E4,1E4);var f=[];f[0]=d;f[1]=e;f[2]=a;f[3]=0;f[4]=0;var h=this.fb();f[3]=0;f[4]=0;null!=h&&b.Xd[h].lhd(f);g.Ra(f[3]);g.Ga(f[4]);d&&a.Ra(a.O()+this.ca.pj()+g.aa()+this.ca.Dk());
e&&a.Ga(a.M()+this.ca.Ek()+g.ba()+this.ca.fm())}};d.mb(c.$3b,"PRIM_WEB","HtmlContainer",{Pa:{Html:{a:e.LEc,f:function(a){this.r5c(d.ja(a))}},Description:{a:e.QV,f:function(a){this.Aob(d.ja(a))}}},Bg:{wg:"Html"}});c.Njb=function(a){q.H.call(this,a)};var q=c.q(c.Njb,c.kn);q.DOa=function(){return!1};q.FOa=function(){return this.pa.Ps()||this.pa.nM?!1:!0};q.RKc=function(){return 0<this.n5a().length};q.gO=function(a){q.j.gO.call(this,a);return!1};q.OMb=function(a){var b=this.n5a();for(a=a?b.indexOf(a)+
1:0;0<=a&&a<b.length;){var c=b[a];if(c&&(c.focus(),c==document.activeElement))return!0;a++}return!1};q.PMb=function(a){var b=this.n5a();for(a=a?b.indexOf(a)-1:b.length-1;0<=a;){var c=b[a];if(c&&(c.focus(),c==document.activeElement))return!0;a--}return!1};q.n5a=function(){var a=[],b=[];this.C7b(this.G,b);for(var c=1;c<b.length;c++)a=a.concat(b[c]||[]);return a=a.concat(b[0]||[])};q.C7b=function(a,b){var c=a.tabIndex;0<=c&&(b[c]===p&&(b[c]=[]),b[c].push(a));for(var c=a.childNodes,d=0;d<c.length;d++)a=
c[d],this.C7b(a,b)};q.L4=q[a.Ma.XO]=function(b){b.jf=a.Ma.Fka|a.Ma.xKa};c.k5b=function(a){g.H.call(this,a);this.Ya=null};var g=c.q(c.k5b,c.Njb);g.cf=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.jc);this.G.setAttribute("LANSAHandle",this.jc);return g.j.cf.call(this,a,b)};g.jSc=function(a){null==this.Ya&&(this.Ya=document.createElement("div"),this.Ya.style.left="0px",this.Ya.style.top="0px",this.Ya.style.width="100%",this.Ya.style.height="100%",a.LANSA_Class.lTb(a,
this.Ya),this.G.appendChild(this.Ya))};c.K4b=function(a){B.H.call(this,a);this.Ya=null};var B=c.q(c.K4b,c.Njb);B.dA=function(){B.j.dA.call(this);this.G.style.whiteSpace="normal"};B.cf=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.jc);this.G.setAttribute("LANSAHandle",this.jc);this.Ya=document.createElement("div");this.Ya.style.left="0px";this.Ya.style.top="0px";this.Ya.style.width="100%";this.Ya.style.height="100%";this.Ya.innerHTML=this.pa.DHa;this.G.appendChild(this.Ya);
return B.j.cf.call(this,a,b)};B.Zgd=function(){var a=this.pa.mo(),b=this.pa.iq();this.Ya.style.width=a?"":"100%";this.Ya.style.height=b?"":"100%";this.Ya.innerHTML=this.pa.DHa};B.Pd=function(){B.j.Pd.call(this);this.Zgd()};B.lhd=function(a){var b=a[0],c=a[2],d=this.Ya.style.width;a[1]&&!b&&(this.Ya.style.width=c.aa()+"px");a[3]=this.Ya.clientWidth;a[4]=this.Ya.clientHeight;this.Ya.style.width=d}});
