window.LANSA.addSrc("sound",function(d,c,a,b,p){var u,t;u={ALL:0,METADATA:1,NONE:2};t={auto:0,metadata:1,none:2};c.sQa=function(a){r.H.call(this);this.Y2=this.xt="";this.mha=a};var r=c.q(c.sQa,c.Gd);r.R=function(){r.j.R.call(this)};r.Yg=function(){return this.xt};r.Ys=function(a){this.xt=a};r.VZ=function(){return this.Y2==p?"":this.Y2};r.Q0=function(a){this.Y2=a};r.Mr=function(){for(var a=0;a<this.mha.yc();a++)this.mha.Ur(a)===this&&this.mha.es(a)};d.mb(c.sQa,"PRIM_SOND","File",{Pa:{FileName:{a:r.Yg,
f:function(a){this.Ys(d.ja(a))}},FileExtension:{a:r.VZ,f:function(a){this.Q0(d.ja(a))}}},pc:{Delete:r.Mr},Bg:{wg:"FileExtension"}});c.fib=function(a){m.H.call(this);this.zkc=a;this.cb=[]};var m=c.q(c.fib,c.Gd);m.yc=function(){return this.cb.length};m.ae=function(a){return this.Ur(a)};m.Ur=function(a){if(0>a||a>=this.cb.length)throw d.SF(a,this.cb.length);return this.cb[a]};m.Jh=function(a,b){var d=new c.sQa(this);d.Ys(a);d.Q0(b);this.cb.push(d);(d=this.zkc.Sa())&&d.ss()};m.Jya=function(){0==this.yc()&&
this.cb.push(new c.sQa(this));return this.Ur(0)};m.Ok=function(){this.cb=[];var a=this.zkc.Sa();a&&a.ss()};m.es=function(a){if(null==this.Ur(a))throw d.SF(a,this.cb.length);this.cb.splice(a,1)};m.CYc=function(a){for(var b=!1,c=0;c<this.yc()&&!(b=this.Ur(c).Yg()==a);c++);b&&this.es(c)};d.mb(c.fib,"PRIM_SOND","Files",{Pa:{Item:{a:function(a){return this.Ur(d.v(a)-1)}}},pc:{Add:m.Jh,RemoveAll:m.Ok,Remove:function(a){return this.es(d.v(a)-1)}},Nq:{jq:function(a){return this.Ur(d.v(a)-1)},Ow:function(){return this.yc()}},
Bg:{wg:"Item"}});c.N2b=function(){k.H.call(this);this.y2=0;this.l2=this.J3=!0;this.zU=1;this.jx=new c.fib(this);this.bi=-1;this.via=this.xia=this.dU=!1;this.QC=50};var k=c.q(c.N2b,c.Tt);k.hh=function(){return c.b5b};k.R=function(){k.j.R.call(this)};k.Yg=function(){return 0<this.jx.yc()?this.jx.Ur(0).Yg():""};k.Ys=function(b){this.jx.Ok();var c=this.jx.Jya();c.Yg()!=b&&(c.Ys(b),(b=this.Sa())&&b.ss(),this.k(a.g.h))};k.VZ=function(){return 0<this.jx.yc()?this.jx.Ur(0).VZ():""};k.Q0=function(b){var c=
this.jx.Jya();c.VZ()!=b&&(c.Q0(b),(b=this.Sa())&&b.ss(),this.k(a.g.h))};k.jEc=function(){return this.jx};k.z$a=function(){return this.y2};k.xob=function(b){this.y2!=b&&(this.y2=b,(b=this.Sa())&&b.ss(),this.k(a.g.h))};k.gab=function(){return this.dU};k.fbb=function(){return this.J3};k.Rpb=function(b){this.J3!=b&&(this.J3=b,(b=this.Sa())&&b.ss(),this.k(a.g.h))};k.V9a=function(){return this.l2};k.$nb=function(b){this.l2!=b&&(this.l2=b,(b=this.Sa())&&b.ss(),this.k(a.g.h))};k.c5=function(){return this.bi};
k.hab=function(){return this.xia};k.fab=function(){return this.via};k.Lbb=function(){return this.QC};k.FEa=function(c){c=b.lf(c,0,100);this.QC!=c&&(this.QC=c,this.dU=0==this.QC,(c=this.Sa())&&c.ss(),this.k(a.g.h))};k.WGc=function(){return this.zU};k.Hpb=function(b){this.zU!=b&&(this.zU=b,(b=this.Sa())&&b.ss(),this.k(a.g.h))};k.Play=function(){this.Sa()&&this.Sa().Play()};k.uh=function(){this.Sa()&&this.Sa().uh()};k.jlb=function(){this.FEa(0)};d.wd(c.N2b,"PRIM_SOND",{Pa:{FileName:{a:k.Yg,f:function(a){this.Ys(d.ja(a))}},
CycleToStart:{a:k.z$a,f:function(a){this.xob(d.wa(a))}},ShowControls:{a:k.fbb,f:function(a){this.Rpb(d.wa(a))}},Autoplay:{a:k.V9a,f:function(a){this.$nb(d.wa(a))}},Preload:{a:function(){return d.sa(this.zU,u)},f:function(a){this.Hpb(d.qa(a,u))}},Duration:{a:k.c5},IsMuted:{a:k.gab},IsPlaying:{a:k.hab},IsEnded:{a:k.fab},Volume:{a:k.Lbb,f:function(a){this.FEa(d.v(a))}}},pc:{Play:k.Play,Stop:k.uh,Mute:k.jlb}});c.b5b=function(a){h.H.call(this,a)};var h=c.q(c.b5b,c.kn);h.cf=function(b,c){this.G=document.createElement("audio");
this.G.setAttribute("LANSAHandle",this.jc);this.G.style.position="absolute";this.G.style.overflow="hidden";this.G.style.whiteSpace="nowrap";this.ss();var d=this.G,g=this;d.addEventListener("loadedmetadata",function(){g.pa.bi=d.duration;g.pa.Ca(a.w.jXb)},!1);d.addEventListener("loadeddata",function(){g.pa.Ca(a.w.iXb)},!1);d.addEventListener("play",function(){g.pa.xia=!0;g.pa.via=!1;g.pa.Ca(a.w.m7b)},!1);d.addEventListener("pause",function(){g.pa.xia=!1;g.pa.Ca(a.w.Lcc)},!1);d.addEventListener("ended",
function(){g.G.pause();g.G.paused=!0;g.pa.via=!0;g.pa.Ca(a.w.Gw)},!1);d.addEventListener("volumechange",function(){d.muted||0==d.volume?(g.G.muted=!0,g.pa.dU=!0,g.pa.QC=0,g.pa.Ca(a.w.i6b)):(g.pa.dU=!1,g.pa.QC=Math.round(100*d.volume))},!1);return h.j.cf.call(this,b,c)};h.ss=function(){this.vqa("controls",this.pa.J3);this.vqa("autoplay",this.pa.l2);this.vqa("loop",this.pa.y2);this.G.setAttribute("preload",d.sa(this.pa.zU,t));this.G.volume=0<this.pa.QC?this.pa.QC/100:0;this.G.muted=this.pa.dU;this.cvb()};
h.cvb=function(){this.cnb();var a=this.pa.jx.yc();if(0!=a)for(var b=0;b<a;b++){var c=this.pa.jx.Ur(b);this.Dmc(this.G,c.xt,c.Y2)}};h.Dmc=function(a,b,c){var d=document.createElement("source");d.src=b;c&&(d.type="audio/"+c);a.appendChild(d)};h.cnb=function(){var a=this.G;if(a&&(a=a.childNodes)){var b,c,d=[];for(c=0;c<a.length;c++)b=a[c],"SOURCE"==b.nodeName&&d.push(b);for(c=0;c<d.length;c++)b=d[c],b.parentNode.removeChild(b)}};h.gO=function(){return!1};h.zRa=function(){};h.Play=function(){this.G.play!==
p&&this.G.play()};h.uh=function(){this.G.pause!==p&&this.G.pause()}});
