window.LANSA.addSrc("tile",function(d,c,a,b,p){d.Db("PRIM_UDC");c.hhb=function(){u.H.call(this);this.Mb=b.Hg(10,10,280,120);this.Pi=new c.fYb(this);this.Wi=new c.VXb(this);this.uo(this.Wi);this.EI(!0);this.jX(!0);this.Bqa(a.eo.xx);this.Yf().hpb();var d=new c.qBa,d=new c.gYb(this,d);this.NLa(d)};var u=c.q(c.hhb,c.ioa);u.R=function(){u.j.R.call(this);b.$(this.Wi);this.Wi=null};u.X$a=function(){return this.Wi};u.GQb=function(){return this.Gu()};u.jN=function(){return this.Wi.jN()};u.fL=function(b){this.Wi.jN()!=
b&&(this.Wi.fL(b),this.ea(a.g.h))};u.Sya=function(){return this.Wi.Sya()};u.sUa=function(b){this.Wi.Sya()!=b&&(this.Wi.sUa(b),this.ea(a.g.h))};u.E5=function(){return this.Wi.E5()};u.Tpb=function(b){this.Wi.E5()!=b&&(this.Wi.Tpb(b),this.ea(a.g.h))};u.Nya=function(){return this.Wi.Nya()};u.kUa=function(b){this.Wi.Nya()!=b&&(this.Wi.kUa(b),this.k(a.g.h))};u.WZ=function(){return this.Wi.WZ()};u.lUa=function(b){this.Wi.WZ()!=b&&(this.Wi.lUa(b),this.k(a.g.h))};u.XZ=function(){return this.Wi.XZ()};u.mUa=
function(b){this.Wi.XZ()!=b&&(this.Wi.mUa(b),this.k(a.g.h))};u.wma=function(){return this.Wi.wma()};u.XUa=function(b){this.Wi.wma()!=b&&(this.Wi.XUa(b),this.k(a.g.h))};u.xma=function(){return this.Wi.xma()};u.YUa=function(b){this.Wi.xma()!=b&&(this.Wi.YUa(b),this.k(a.g.h))};u.Dza=function(){return this.Wi.Dza()};u.ZUa=function(b){this.Wi.Dza()!=b&&(this.Wi.ZUa(b),this.ea(a.g.h))};u.Eza=function(){return this.Wi.Eza()};u.$Ua=function(b){this.Wi.Eza()!=b&&(this.Wi.$Ua(b),this.ea(a.g.h))};u.cza=function(){return this.Wi.cza()};
u.BUa=function(b){this.Wi.cza()!=b&&(this.Wi.BUa(b),this.ea(a.g.h))};u.$ya=function(){return this.Wi.$ya()};u.wUa=function(b){this.Wi.$ya()!=b&&(this.Wi.wUa(b),this.ea(a.g.h))};u.bza=function(){return this.Wi.bza()};u.AUa=function(b){this.Wi.bza()!=b&&(this.Wi.AUa(b),this.ea(a.g.h))};u.Zya=function(){return this.Wi.Zya()};u.vUa=function(b){this.Wi.Zya()!=b&&(this.Wi.vUa(b),this.ea(a.g.h))};u.MV=function(){return"PRIM_TILE<"+this.iN()+">"};u.hLc=function(){return!0};u.tSb=function(){return!0};u.FZ=
function(b){0==(this.pp()&a.Ln.Qu)&&this.uj(!0);if(this.yA(a.w.uK)&&(this.bd(b),!this.nd())){var c=d.Yb();c.bc("ITEM",b);this.Ca(a.w.uK,c);c.Ac()}};u.GZ=function(b){0==(this.pp()&a.Ln.Qu)&&this.uj(!0);if(this.yA(a.w.wK)&&(this.bd(b),!this.nd())){var c=d.Yb();c.bc("ITEM",b);this.Ca(a.w.wK,c);c.Ac()}};u.Q4=function(b){0==(this.pp()&a.Ln.Qu)&&this.uj(!0);if(this.yA(a.w.vK)&&(this.bd(b),!this.nd())){var c=d.Yb();c.bc("ITEM",b);this.Ca(a.w.vK,c);c.Ac()}};u.CB=function(b,c){this.bd(b);c=b.CB(c);if(!c&&
!this.nd()){var g=d.Yb();g.bc("ITEM",b);g.Gf("CONTINUE",!0);this.Ca(a.w.tK,g);c=!g.zg("CONTINUE");g.Ac()}return c};u.lba=function(b,c){this.bd(b);if(!c&&!this.nd()){var g=d.Yb();g.bc("ITEM",b);g.Gf("CONTINUE",!0);this.Ca(a.w.b6,g);c=!g.zg("CONTINUE");g.Ac()}return c};u.VE=function(b){var c=this.yA(a.w.CD);c&&this.bd(b);b.VE();c&&!this.nd()&&(c=d.Yb(),c.bc("ITEM",b),this.Ca(a.w.CD,c),c.Ac())};u.TE=function(b){0==(this.pp()&a.Ln.Qu)&&this.uj(!0);this.bd(b);b.TE();if(!this.nd()){var c=d.Yb();c.bc("ITEM",
b);this.Ca(a.w.AF,c);c.Ac()}};u.UE=function(b){0==(this.pp()&a.Ln.Qu)&&this.uj(!0);this.bd(b);b.UE();if(!this.nd()){var c=d.Yb();c.bc("ITEM",b);this.Ca(a.w.KN,c);c.Ac()}};u.vR=function(b){0==(this.pp()&a.Ln.Uda)&&this.uj(!0);this.bd(b);b.vR();if(!this.nd()){var c=d.Yb();c.bc("ITEM",b);this.Ca(a.w.DW,c);c.Ac()}};u.wR=function(b){0==(this.pp()&a.Ln.Uda)&&this.uj(!0);this.bd(b);b.wR();if(!this.nd()){var c=d.Yb();c.bc("ITEM",b);this.Ca(a.w.EW,c);c.Ac()}};u.Jh=function(a){var b=null;return b=this.Pi.Wg(a,
!0,-1,!1)};u.Wg=function(){this.Pi.Wg(this.iN(),!0,-1,!0)};u.Ph=function(a){return this.Pi.Ph(!1,a)?"OK":"NR"};u.jp=function(){return this.Pi.HMa()};u.Bk=function(){this.Pi.Bk()};u.Cn=function(a){this.Pi.Cn(a==p?!0:!1,a)};u.Vl=function(){this.Pi.Vl()};u.po=function(a,b,c){return this.Pi.po(a,b,c)};u.hr=function(a){this.Bk();for(var b=0;b<a;b++)this.Wg()};u.Jpa=function(a){this.FZ(a)};u.Lpa=function(a){this.GZ(a)};u.Kpa=function(a){this.Q4(a)};u.Epa=function(a,b){return this.CB(a,b)};u.Fpa=function(a,
b){return this.lba(a,b)};u.Bea=function(a){this.VE(a)};u.Aea=function(a){this.TE(a)};u.Ipa=function(a){this.UE(a)};u.Gpa=function(a){this.vR(a)};u.YCa=function(a){this.wR(a)};u.z0=function(a){u.j.z0.call(this,a);a.ST.td(a.d7());a.ST.Ae(a.cqa());a.ST.Zd(a.wTa());a.ST.Dd(a.znb())};u.NDa=function(b){null!=b&&null!=b.ac&&(this.VXa(b.ac,a.tz.c2),this.xna(b.ac,a.UH.ada))};u.ue=function(b){""==b[1]&&(b[1]=a.zWb);u.j.ue.call(this,b)};d.wd(c.hhb,"PRIM_TILE",{nO:a.ux.SXa,IE:"PRIM_CPST",Pa:{CurrentItem:{a:u.Kd},
SelectionStyle:{a:function(){return d.sa(this.Pt(),a.Sh.cec)},f:function(b){this.Qpb(d.qa(b,a.Sh.cec))}},Direction:{a:function(){return d.sa(this.jN(),a.Kq.u)},f:function(b){this.fL(d.qa(b,a.Kq.u))}},ItemsPerDivision:{a:u.Sya,f:function(a){this.sUa(d.v(a))}},ShowPartialItem:{a:u.E5,f:function(a){this.Tpb(d.wa(a))}},Spacing:{a:u.Dza,f:function(a){this.ZUa(d.v(a))}},SpacingItems:{a:u.Eza,f:function(a){this.$Ua(d.v(a))}},FlowOperation:{a:function(){return d.sa(this.Nya(),a.Eg.u)},f:function(b){this.kUa(d.qa(b,
a.Eg.u))}},FlowOperationVer:{a:function(){return d.sa(this.XZ(),a.Eg.u)},f:function(b){this.mUa(d.qa(b,a.Eg.u))}},FlowOperationHor:{a:function(){return d.sa(this.WZ(),a.Eg.u)},f:function(b){this.lUa(d.qa(b,a.Eg.u))}},SizingRuleVer:{a:function(){return d.sa(this.xma(),a.jG.u)},f:function(b){this.YUa(d.qa(b,a.jG.u))}},SizingRuleHor:{a:function(){return d.sa(this.wma(),a.jG.u)},f:function(b){this.XUa(d.qa(b,a.jG.u))}},MinRows:{a:u.cza,f:function(a){this.BUa(d.v(a))}},MaxRows:{a:u.$ya,f:function(a){this.wUa(d.v(a))}},
MinColumns:{a:u.bza,f:function(a){this.AUa(d.v(a))}},MaxColumns:{a:u.Zya,f:function(a){this.vUa(d.v(a))}},FocusItem:{a:u.Tc}},pc:{Add:u.Jh,Sort:u.U7,FindItem:u.Jd,DeleteAll:u.PE,FindReference:u.uR},cz:{Wg:u.Wg,Ph:function(a){return this.Ph(d.v(a)-1)},hr:u.hr,Bk:u.Bk,jp:u.jp,Cn:function(a){return this.Cn(a?d.v(a)-1:p)},Vl:u.Vl,po:u.po,Xs:u.Xs}});c.gYb=function(a,b){t.H.call(this,a,b)};var t=c.q(c.gYb,c.sBa);t.R=function(){t.j.R.call(this)};t.kCd=function(){return this.er.za()};t.xaa=function(a,b){var c=
null,f=null,h=null,k=null;null!=a&&(f=k=d.pd(a),null!=f&&(f.Gb(!1),h=f,null!=h&&(c=d.pd("PRIM_TILE","TileItem"),c.Ha())));b[0]=k;b[1]=c;b[2]=f;b[3]=h};t.UQ=function(a,b,c,d){this.xaa(a,b);null!=b[1]&&this.Nx(b[1],b[2],d)};t.Upa=function(a){return a};c.fYb=function(a){r.H.call(this,a)};var r=c.q(c.fYb,c.rBa);r.Wg=function(b,c,d,f){var h=this.za(),k=null,k=null,k=[];c?h.GQb().UQ(b,k,-1,f):h.GQb().UQ(b,k,d,f);k=k[1];h.LQ(!0);h.xd(a.yb.Fe);return k};c.eYb=function(){m.H.call(this);this.izb=a.AWb};var m=
c.q(c.eYb,c.joa);m.R=function(){m.j.R.call(this)};m.Oa=function(a){this.L()!=a&&this.Ag()&&(null==a||a.Ag()&&a.za()==this.za())&&this!=a&&(a=null!=a?a:null,this.L()!=a&&this.KXa(a,-1))};m.CB=function(c){if(!this.nd()){var f=d.Yb();f.bc("ITEM",this);f.Gf("CONTINUE",!0);this.Ca(a.w.tK,f);c=!f.zg("CONTINUE");f.Ac()}f=this.Sr();null!=f&&b.Pl(f,this,"ONITEMCLICK");return c};m.VE=function(){if(!this.nd()){var c=d.Yb();c.bc("ITEM",this);this.Ca(a.w.CD,c);c.Ac()}c=this.Sr();null!=c&&b.Pl(c,this,"ONITEMREALIZING")};
m.TE=function(){if(!this.nd()){var c=d.Yb();c.bc("ITEM",this);this.Ca(a.w.AF,c);c.Ac()}c=this.Sr();null!=c&&(b.Pl(c,this,"ONITEMGOTFOCUS"),null!=this.ac&&this.ac.ca.Dqa(!0))};m.UE=function(){if(!this.nd()){var c=d.Yb();c.bc("ITEM",this);this.Ca(a.w.KN,c);c.Ac()}c=this.Sr();null!=c&&(b.Pl(c,this,"ONITEMLOSTFOCUS"),null!=this.ac&&this.ac.ca.Dqa(!1))};m.vR=function(){if(!this.nd()){var c=d.Yb();c.bc("ITEM",this);this.Ca(a.w.DW,c);c.Ac()}c=this.Sr();null!=c&&(b.Pl(c,this,"ONITEMGOTSELECTION"),null!=this.ac&&
this.ac.ca.Wu(!0))};m.wR=function(){if(!this.nd()){var c=d.Yb();c.bc("ITEM",this);this.Ca(a.w.EW,c);c.Ac()}c=this.Sr();null!=c&&(b.Pl(c,this,"ONITEMLOSTSELECTION"),null!=this.ac&&this.ac.ca.Wu(!1))};d.mb(c.eYb,"PRIM_TILE","TileItem",{Pa:{Design:{a:m.NMa},Tile:{a:m.za},Focus:{a:m.zf,f:m.df},Selected:{a:m.rj,f:function(a){this.Wu(d.wa(a))}},Expanded:{a:m.lk,f:function(a){this.zI(d.wa(a))}},Position:{a:m.yca},Entry:{a:m.Ph},Visible:{a:m.sb,f:function(a){this.Gb(d.wa(a))}},RelatedReference:{a:m.j_,f:m.YS},
MarginTop:{a:m.He,f:function(a){this.td(d.v(a))}},MarginBottom:{a:m.Zf,f:function(a){this.Ae(d.v(a))}},MarginLeft:{a:m.Qe,f:function(a){this.Zd(d.v(a))}},MarginRight:{a:m.Pf,f:function(a){this.Dd(d.v(a))}},Style:{a:m.Gg,f:m.vb},ParentItem:{a:m.L,f:m.Oa},MouseOverStyle:{a:m.Fn,f:m.Nn},SelectedStyle:{a:m.vA,f:m.DI},FocusedStyle:{a:m.Py,f:m.ND},SelectedInactiveStyle:{a:m.pD,f:m.GO},FocusedInactiveStyle:{a:m.jD,f:m.uO},Styles:{a:m.Jk},MouseOverStyles:{a:m.Kw},SelectedStyles:{a:m.dW},FocusedStyles:{a:m.i5},
SelectedInactiveStyles:{a:m.C5},FocusedInactiveStyles:{a:m.g5},ItemCount:{a:m.yc},Items:{a:m.qA},ParentItems:{a:m.Hab}},pc:{Add:m.Jh,Expand:m.CV,Delete:m.Mr,Collapse:m.E4,DeleteAll:m.PE}});c.dYb=function(){k.H.call(this)};var k=c.q(c.dYb,c.hhb);k.apa=function(a){a.J5b(this.L())};k.Qda=function(a){a.$oa(this.L());k.j.Qda.call(this,a)};c.cYb=function(){h.H.call(this);this.Mb=b.Hg(10,10,280,400);this.ml=null;this.plc=!1;this.ic=this.ml=new c.dYb;this.ml.Ha();this.ml.tb(this);this.ml.udcDesign="PRIM_TILE_DESIGN";
this.ml.Ke(!1);this.ml.ta(this,a.w.ph,this.Gwc);this.ml.ta(this,a.w.eX,this.Rwc);this.ml.ta(this,a.w.uK,this.Nwc);this.ml.ta(this,a.w.wK,this.Pwc);this.ml.ta(this,a.w.vK,this.Owc);this.ml.ta(this,a.w.tK,this.Hwc);this.ml.ta(this,a.w.b6,this.Iwc);this.ml.ta(this,a.w.CD,this.Qwc);this.ml.ta(this,a.w.AF,this.Jwc);this.ml.ta(this,a.w.KN,this.Lwc);this.ml.ta(this,a.w.DW,this.Kwc);this.ml.ta(this,a.w.EW,this.Mwc)};var h=c.q(c.cYb,c.$r);h.R=function(){h.j.R.call(this)};h.Kd=function(){return this.ml.Kd()};
h.Tc=function(){return this.ml.Tc()};h.qA=function(){return this.ml.qA()};b.UHd=function(a){var b=null;a&&a.ac&&a.ac instanceof c.ihb&&(b=a.ac);return b};h.zwa=function(a){a.kb(new c.fa(a.Od(),a.he(),this.JGa,this.Et))};h.Zx=function(a,b){h.j.Zx.call(this,a,b);this.plc!=this.ml.Zca()&&(this.plc=this.ml.Zca(),this.ob())};h.gf=function(a){h.j.gf.call(this,a)};h.Xs=function(){return this.ml.Xs()};h.Wg=function(){var a=this.ml.Wg();this.zwa(a.ac)};h.Ph=function(a){return this.ml.Ph(a)};h.jp=function(){return this.ml.jp()};
h.Bk=function(){this.ml.Bk()};h.Cn=function(a){this.ml.Cn(a)};h.Vl=function(){this.ml.Vl()};h.po=function(a,b,d){var f=this.ml;if(f)for(var h=0;h<f.Aq.length;h++){var k=f.zF(h);if(k&&(k=k.ac)){for(var m={},r=null,t=this.ym,p=0;p<t.length&&null!=(r=t[p]);p++){var u=null,J=null,G=null,W=null;r instanceof c.Foa?u=r:r instanceof c.Doa?J=r:r instanceof c.Hoa||r instanceof c.Coa||r instanceof c.Eoa||r instanceof c.Goa||(r instanceof c.Boa?G=r:r instanceof c.Ioa&&(W=r));if(J||u||G||W)J=k.vc[r],u=r.mf,J&&
(J=J.Mc.fc().Da(),u&&(u=u.nA())&&(m[u.zh()]=J))}if(a(m))return a=f.BDa(),null!=b&&b.set(h+1),a&&(d&&a.Ph(!1,h),a.qy=f.zF(h)),"OK"}}return"NR"};h.hr=function(a){this.ml.hr(a)};h.Gwc=function(b,c){this.Ca(a.w.ph,c)};h.Rwc=function(b,c){this.Ca(a.w.eX,c)};h.Nwc=function(b,c){this.Ca(a.w.uK,c)};h.Pwc=function(b,c){this.Ca(a.w.wK,c)};h.Owc=function(b,c){this.Ca(a.w.vK,c)};h.Hwc=function(b,c){this.Ca(a.w.tK,c)};h.Iwc=function(b,c){this.Ca(a.w.b6,c)};h.Qwc=function(b,c){this.Ca(a.w.CD,c)};h.Jwc=function(b,
c){this.Ca(a.w.AF,c)};h.Lwc=function(b,c){this.Ca(a.w.KN,c)};h.Kwc=function(b,c){this.Ca(a.w.DW,c)};h.Mwc=function(b,c){this.Ca(a.w.EW,c)};d.mb(c.cYb,"PRIM_MD","Tile",{IE:"PRIM_CPST",Pa:{CurrentItem:{a:h.Kd},FocusItem:{a:h.Tc},Items:{a:h.qA},RowHeight:{a:h.A5,f:function(a){this.pL(d.v(a))}},ColWidth:{a:h.gCc,f:function(a){this.b4c(d.v(a))}},CardType:{a:function(){return d.sa(this.Ny(),a.ol.u)},f:function(b){this.p7(d.qa(b,a.ol.u))}},LogicalHeight:{a:function(){return this.ml.XOb()}},LogicalWidth:{a:function(){return this.ml.yab()}},
ViewportHeight:{a:function(){return this.ml.SQb()}},ViewportWidth:{a:function(){return this.ml.TQb()}},VerticalScrollPos:{a:function(){return this.ml.Um},f:function(a){this.ml.iG(d.v(a))}},HorizontalScrollPos:{a:function(){return this.ml.Rm},f:function(a){this.ml.$Da(d.v(a))}}},pc:{DeleteAll:h.PE,FindReference:h.uR},cz:{Wg:h.Wg,Ph:function(a){return this.Ph(d.v(a)-1)},hr:h.hr,Bk:h.Bk,jp:h.jp,Cn:function(a){return this.Cn(a?d.v(a)-1:p)},Vl:h.Vl,po:h.po,Xs:h.Xs}});c.ihb=function(){f.H.call(this);this.wpb();
this.Qb(a.Dgb)};var f=c.q(c.ihb,c.j6);f.R=function(){f.j.R.call(this)};f.lCd=function(){return this.tv};f.Dwa=function(a){f.j.Dwa.call(this,a)};f.ue=function(a){""==a[0]&&(a[0]="");f.j.ue.call(this,a)};d.wd(c.ihb,"PRIM_TILE_DESIGN",{Pa:{},pc:{}})},{rp:["PRIM_UDC"]});
