window.LANSA.addSrc("menu",function(d,c,a,b,p){d.Db("PRIM_TBLO");d.Db("PRIM_PPNL");d.Db("PRIM_IMAG");d.Db("PRIM_SPBN");a.yRa={o0:16,Zkb:16};a.QW={sCa:0,elb:1,flb:2,$kb:4};a.IK={M5b:0,ykb:1,xkb:2};a.IK.u={NONE:a.IK.M5b,BREAK:a.IK.ykb,BARBREAK:a.IK.xkb};a.JK={n0:25,Pkb:1,Nkb:2,IId:4,Qkb:8,Okb:16};a.IK={PTc:0};a.mId=3;a.lId=2;a.nId=255;a.ATc=768;a.y5b=256;a.x5b=512;a.sRa=65536;a.tRa=131072;a.mkb=262144;a.okb=524288;a.nkb=1048576;a.uSd=2;a.tSd=2;c.YBa=function(){u.H.call(this);this.NG=null;this.hM=a.yRa.o0;
this.GP=a.QW.sCa;this.Un=null;this.Pb=[];this.iJ=new c.Tx;this.Zia=new c.pb;this.Uh=new c.Ux;this.kkd=new c.Lda;this.jkd=new c.v6;this.kkd.tr(this.Uh);this.jkd.tr(this.Uh);this.iJ.uo(this.Uh);this.Zia.Ti(b.J(255,255,255));this.Zia.ui(b.bb().Ho(a.l.Bj));this.Zia.Uo(1);this.Zia.Bp(1);this.Zia.on(1);this.Zia.pn(1);this.iJ.ta(this,a.w.Ww,this.Tvc);this.iJ.vb(this.Zia)};var u=c.q(c.YBa,c.Sx);u.nb=function(){this.Pb=null;u.j.nb.call(this)};u.R=function(){null!=this.NG&&this.HX();for(var a=null;null!=(a=
this.Pb[0]);)a.Oa(null);b.gTc(this);u.j.R.call(this)};u.Syd=function(){return this.NG};u.Vyd=function(){return this.Pb};u.fGc=function(){return this.Pb.length};u.qca=function(){return this};u.rOc=function(){return 0!=(this.GP&a.QW.flb)};u.iNc=function(){return 0!=(this.GP&a.QW.$kb)};u.Xyd=function(){return 0!=(this.GP&a.QW.elb)};u.$5c=function(){var b=this.GP&~a.QW.elb|a.QW.elb;this.GP!=b&&(this.GP=b,this.ea(a.g.h))};u.zab=function(){return 0!=(this.hM&a.yRa.Zkb)};u.yQd=function(b){b=this.hM&~a.yRa.Zkb|
(b?a.yRa.Zkb:0);this.hM!=b&&(this.hM=b,this.ea(a.g.h))};u.Yea=function(a){this.Un!=a&&(this.Un=a,this.lTa())};u.ACc=function(){return this.Un};u.qA=function(){return this.Pb};u.gda=function(){return null!=this.NG||null!=this.gg};u.SDd=function(){for(var a,b=this.Pb,c=0;c<b.length&&null!=(a=b[c]);c++)if(!0==a.sb())return!0;return!1};u.ko=function(){null==this.gg&&this.Vu(b.gb().qB(this));return this.gg};u.oba=function(b){var c=d.Yb();c.bc("CONTEXT",b);this.Ca(a.w.Ww,c);c.Ac()};u.Nx=function(b){this.gda()&&
this.HX();b.Xb=this;this.HXa(b);b.Fa(this,this.rxa);this.ea(a.g.h)};u.BMc=function(b){this.gda()&&this.HX();b.Xb=this;this.HXa(b);b.Fa(this,this.rxa);this.ea(a.g.h)};u.B0=function(b){this.gda()&&this.HX();b.Xb=null;b.Ba(this,this.rxa);this.HXa(b);this.ea(a.g.h)};u.hAa=function(){b.U();this.HX()};u.Y8b=function(a){if(null==this.NG){if(null!=this.gg)this.NG=this.gg;else{var c=b.U().Uua;this.NG=this.f5a();null!=this.NG&&(c[this.NG]=this)}this.kSa(null,a)}};u.HX=function(){if(null!=this.NG){for(var a,
c=this.Pb,d=0;d<c.length&&null!=(a=c[d]);d++){var k=a.ru;a.Vu(null);a.GYc();k&&k.HX()}null!=this.NG&&(null!=this.gg?(this.Vu(null),this.NG=null):(a=b.U().Uua,null!=this.NG&&delete a[this.NG]));this.NG=null;this.Vu(null);b.U().Ht(this.iJ,!1)}};u.tWc=function(){};u.Wlb=function(){};u.kSa=function(a,b){this.iJ.kb(new c.fa(0,0,0,5));for(var d,k=0,g=this.Pb,m=0;m<g.length&&null!=(d=g[m]);m++)k=this.dka(a,b,d,k)};u.dka=function(a,b,c,d,g){return c.dka(a,b,this,d,g)};u.uEb=function(a){for(var b=!1,c,d=this.Pb,
g=0;g<d.length&&null!=(c=d[g]);g++)if(c==a||null!=c.ru&&c.ru.uEb(a)){b=!0;break}return b};u.bKc=function(b){for(var c=!1,d=null,k=this.Pb,g=0;g<k.length&&null!=(d=k[g]);g++)if(d.Ub()&&d.te()){var m=d.ru;if(null!=m&&m.bKc(b)){c=!0;break}if(d.vva!=a.W.LDa&&d.vva==b){d.Nf();c=!0;break}}return c};u.xrd=function(){for(var a=this.Pb,b=null,c=null,d=0;d<a.length&&null!=(c=a[d]);d++)if(c.Y4()){b=c;break}return b};u.HXa=function(a){var c=this.Pb.indexOf(a);-1!=c&&this.Pb.splice(c,1);c+=1;if(a.Xb==this){0==
a.pg()&&(a.eh=this.Pb.length+1);var d=a.pg(),k=0;0<c&&d>c&&d++;for(var g,c=this.Pb,m=0;m<c.length&&null!=(g=c[m])&&!(g.pg()>=d);m++)k++;this.Pb.splice(k,0,a)}b.eTc(this)};u.WCa=function(b){b==a.DV&&(this.gda()&&this.HX(),this.C6(),this.ea(a.g.h))};u.C6=function(){for(var b,c=this.Pb,d=0;d<c.length&&null!=(b=c[d]);d++)b.eh=1,b.ea(a.g.h)};u.DId=function(a){var c=b.U();return null!=c.Uua?c.Uua[a]:null};u.lTa=function(){};u.FSa=function(){b.U().Ht(this.iJ,!1)};u.Wlb=function(){};u.Xw=function(a){this.GP|=
a};u.jz=function(a){this.GP&=~a};u.$x=function(a,b){this.GP=this.GP&~a|(b?a:0)};u.aHb=function(b,c){switch(c.Za){case a.g.wb:this.Yea(null)}};u.rxa=function(){this.rOc()?this.Xw(a.QW.$kb):this.gda()&&(this.HX(),this.ea(a.g.h))};u.Tvc=function(){this.Wlb(null,this.iJ)};d.wd(c.YBa,"PRIM_MENU",{Pa:{}});c.ejb=function(){t.H.call(this);this.Rz=null};var t=c.q(c.ejb,c.YBa);t.nb=function(){t.j.nb.call(this)};t.R=function(){this.jfa(null);t.j.R.call(this)};t.aPb=function(){return this.Rz};t.jfa=function(b){this.Rz!=
b&&(this.Rz&&this.Rz.OLd(this),b&&b.AEd(this),this.ea(a.g.h))};t.tWc=function(){this.oba(null)};t.kSa=function(a,b){this.iJ.kb(new c.fa(0,0,0,5));for(var d,k=0,g=this.Pb,m=0;m<g.length&&null!=(d=g[m]);m++)k=this.dka(a,b,d,k,!0)};t.f5a=function(){throw 0;};d.wd(c.ejb,"PRIM_MBAR",{Pa:{}});c.gjb=function(){r.H.call(this);this.Ysa=null;this.lwb=0};var r=c.q(c.gjb,c.YBa);r.nb=function(){r.j.nb.call(this)};r.R=function(){this.lTa();r.j.R.call(this)};r.zPd=function(b){b!=this.lwb&&(this.lwb=b,this.lTa(),
this.ea(a.g.h))};r.Lsd=function(){return this.lwb};r.PAc=function(){null==this.Ysa&&(this.Ysa=[]);return this.Ysa};r.kSa=function(a,b){this.iJ.kb(new c.fa(0,0,0,5));for(var d,k=0,g=this.PAc(),m=0;m<g.length&&null!=(d=g[m]);m++)k=this.dka(a,b,d,k);g=this.Pb;for(m=0;m<g.length&&null!=(d=g[m]);m++)k=this.dka(a,b,d,k)};r.f5a=function(){return b.dza()};r.Tqa=function(a,b){a===p&&(a=0);b===p&&(b=0);this.D7b(new c.qd(a,b),null,!0,null)};r.D7b=function(c,d){var e=b.U(),k=!1,k=e.xj,g=b.U().lw;this.oba(d,c);
b.ZQa(a.DV);this.Yea(d);k&&this.Wt(k,a.Ma.hic);null!=g&&g.K_()&&g.PQ();this.Y8b(this.iJ);0<this.iJ.Ia()&&(k=e.LCb(!0),this.iJ.T7(c.Hb(),c.Lb(),a.Xh.Xx,p,null),e.LCb(k))};r.lTa=function(){this.HX();if(this.Ysa){for(var a;null!=(a=this.Ysa[0]);)b.$(a);this.Ysa=null}};r.yod=function(a,b){var c=b.jma();c&&c.$Jd(b.$i.wM)};d.wd(c.gjb,"PRIM_PMNU",{Pa:{},pc:{Show:r.Tqa}});c.S2b=function(){m.H.call(this);this.Rz=null};var m=c.q(c.S2b,c.YBa);m.nb=function(){m.j.nb.call(this)};m.R=function(){this.Rz&&this.Rz.Xpb(null);
m.j.R.call(this)};m.aPb=function(){return this.Rz};m.jfa=function(b){if(this.Rz!=b&&!this.uEb(b)){var c=this.Rz;this.Rz=b;c&&c.jDb(null);this.Rz&&this.Rz.jDb(this);this.ea(a.g.h,a.Je.GPa)}};m.zab=function(){var a=m.j.zab.call(this);a&&(a=this.Rz.EOc());return a};m.qca=function(){var a=null;this.Rz&&(a=this.Rz.qca());return a};m.FSa=function(){m.j.FSa.call(this);this.Rz.L().FSa()};m.f5a=function(){return b.dza()};m.Egd=function(){if(null!=this.NG)for(var a,b=this.Pb,c=0;c<b.length&&null!=(a=b[c]);c++){var d=
a.ru;d&&d.HX()}};m.Wlb=function(b,c){this.Xw(a.QW.flb);this.oba(null);this.Xw(a.QW.flb);this.gda()&&this.iNc()&&(this.Egd(),this.kSa(b,c));this.Xw(a.QW.$kb)};d.wd(c.S2b,"PRIM_SMNU",{Pa:{Parent:{a:m.aPb,f:m.jfa}}});c.m2b=function(){k.H.call(this);this.Xb=null;this.nf=a.JK.n0;this.jb=a.IK.PTc;this.tf=a.sRa|a.tRa;this.vva=a.W.LDa;this.Ojc=this.eh=this.zt=this.Alc=this.wM=0;this.e3=this.Ka=this.ru=this.Xb=null;this.qb=this.E2a="";this.MT=new c.qo;this.bHa=new c.Ut;this.G2=new c.pb;this.VL=new c.FK;this.w9=
b.oc(null,this.MT,null,null,1,1);this.cHa=b.oc(null,this.VL,null,null,1,1);this.eua=b.oc(null,this.bHa,null,null,1,1);this.bHa.vb(this.G2);this.bHa.Oa(this.MT);this.VL.Oa(this.MT);this.MT.ta(this,a.w.Vb,this.Cuc);this.Fmc()};var k=c.q(c.m2b,c.Sx);k.nb=function(){this.Msc();k.j.nb.call(this)};k.R=function(){this.Xpb(null);this.Oa(null);k.j.R.call(this);this.od(null);this.t5c()};k.Uvd=function(){var a="";this.eOc()||null!=this.qca()&&this.qca()instanceof c.gjb?a=this.eb():this.JBc();return a};k.eb=
function(){return this.qb};k.io=function(){return this.eb().gr()};k.JBc=function(){this.eb()};k.qud=function(){return this.uxb};k.iCd=function(){return!0};k.EAd=function(){return!0};k.Izd=function(){return!0};k.Cpb=function(){var a=this.qca();a&&a.$5c()};k.Fg=function(){return 0!=(this.tf&a.mkb)?!0:!1};k.Y4=function(){return 0!=(this.tf&a.nkb)?!0:!1};k.yPd=function(b){b!=this.eeb()&&(this.nf=this.nf&~a.JK.Nkb|(b?a.JK.Nkb:0),this.ea(a.g.h))};k.eF=function(){return this.zt};k.AEc=function(){return this.Ojc};
k.eGc=function(){var b=a.IK.M5b;0!=(this.tf&a.y5b)?b=a.IK.ykb:0!=(this.tf&a.x5b)&&(b=a.IK.xkb);return b};k.L=function(){return this.Xb};k.qca=function(){var a=null;this.Xb&&(a=this.Xb.qca());return a};k.Dca=function(){return 0!=(this.tf&a.okb)?!0:!1};k.rBd=function(){return this.vva};k.sBd=function(){return""};k.sIc=function(){return this.ru};k.qbb=function(){return this.wM};k.OCd=function(){return this.Alc};k.sb=function(){return 0!=(this.tf&a.tRa)?!0:!1};k.ub=function(a){this.qb!=a&&(this.qb=a,
this.v0())};k.mk=function(a){this.eb().IO(a)};k.$h=function(b){var c=this.eF();if(b&&0!=c&&null!=this.L())for(var d,k=this.L().Pb,g=0;g<k.length&&null!=(d=k[g]);g++)d!=this&&d.eF()==c&&d.$h(!1);b=b?this.tf|a.mkb:this.tf&~a.mkb;b!=this.tf&&(this.tf=b,this.ea(a.g.h))};k.ZTa=function(b){b=b?this.tf|a.nkb:this.tf&~a.nkb;b!=this.tf&&(this.tf=b,this.ea(a.g.h))};k.pg=function(){return this.eh};k.Td=function(b){this.eeb()||(null!=this.Xb?(this.eh=b,this.Xb.HXa(this)):this.eh!=b&&(this.eh=b,this.ea(a.g.h)))};
k.te=function(){return 0!=(this.tf&a.sRa)?!0:!1};k.kg=function(b){b=b?this.tf|a.sRa:this.tf&~a.sRa;b!=this.tf&&(this.tf=b,this.ea(a.g.h))};k.R0=function(b){this.zt!=b&&(this.zt=b,this.ea(a.g.h))};k.j5c=function(b){this.Ojc=b;this.ea(a.g.h)};k.Z5c=function(b){var c=this.tf&~a.ATc;switch(b){case a.IK.ykb:c|=a.y5b;break;case a.IK.xkb:c|=a.x5b}c!=this.tf&&(this.tf=c,this.ea(a.g.h))};k.Oa=function(b){this.Xb!=b&&(this.Xb&&this.Xb.B0(this),b&&(this.eeb()?b.BMc(this):b.Nx(this)),null!=this.Ka&&this.Cpb(),
this.ea(a.g.h,a.Je.GPa))};k.nEa=function(b){b=b?this.tf|a.okb:this.tf&~a.okb;b!=this.tf&&(this.tf=b,this.ea(a.g.h))};k.Y6c=function(b){this.vva!=b&&(this.vva=b,this.ea(a.g.h))};k.Xpb=function(a){this.ru!=a&&(this.ru&&this.ru.jfa(null),a&&a.jfa(this))};k.eVa=function(b){this.wM!=b&&(this.wM=b,this.ea(a.g.h))};k.QRd=function(a){this.Alc=a};k.Nc=function(){return this.Ka};k.od=function(b){this.Ka!=b&&(null!=this.Ka&&(this.Ka.Ba(this,this.Dn),this.Ka.Cb()),this.Ka=b,null!=this.Ka&&(this.Ka.Ha(),this.Ka.Fa(this,
this.Dn)),this.Cpb(),this.ea(a.g.h))};k.t5c=function(){null!=this.e3&&(null!=this.e3&&(this.e3.Ba(this,this.PHb),this.e3.Cb()),this.e3=null,null!=this.e3&&(this.e3.Ha(),this.e3.Fa(this,this.PHb)),this.Cpb(),this.ea(a.g.h))};k.Xxd=function(){return this.e3};k.UIc=function(){return this.E2a};k.a8c=function(b){this.E2a!=b&&(this.E2a=b,this.ea(a.g.h,a.Je.uPc))};k.kOa=function(){return 0!=(this.nf&a.JK.Pkb)?!0:!1};k.b8c=function(b){b!=this.kOa()&&(this.nf=this.nf&~a.JK.Pkb|(b?a.JK.Pkb:0),this.ea(a.g.h))};
k.zbb=function(){return 0!=(this.nf&a.JK.Qkb)?!0:!1};k.c8c=function(b){b!=this.zbb()&&(this.nf=this.nf&~a.JK.Qkb|(b?a.JK.Qkb:0),this.ea(a.g.h))};k.lBd=function(){return!0};k.Fla=function(){return 0!=(this.nf&a.JK.Okb)?!0:!1};k.pac=function(b){b!=this.Fla()&&(this.nf=this.nf&~a.JK.Okb|(b?a.JK.Okb:0),this.ea(a.g.h))};k.Gb=function(b){b=b?this.tf|a.tRa:this.tf&~a.tRa;b!=this.tf&&(this.tf=b,this.ea(a.g.h))};k.yPb=function(){return this.Mb};k.ko=function(){null==this.gg&&this.Vu(b.gb().qB(this));return this.gg};
k.Ub=function(){return null!=this.Xb&&this.Xb.gda()?!0:!1};k.tFd=function(){return"-"==this.eb()?!0:!1};k.eeb=function(){return 0!=(this.nf&a.JK.Nkb)?!0:!1};k.EOc=function(){var a=this.kOa();if(a&&this.zbb()){var b=this.L();b&&(a=b.zab())}return a};k.eOc=function(){return null!=this.L()&&this.L()instanceof c.ejb};k.Nf=function(b){b===p&&(b=null);var c=d.Yb();c.bc("CONTEXT",b);this.Ca(a.w.Vb,c);c.Ac()};k.YTd=function(){if(this.ru)for(var a,b=this.ru.Pb,c=0;c<b.length&&null!=(a=b[c]);c++)a.$h(!1)};
k.jDb=function(b){this.ru!=b&&(this.ru&&(this.ru.Rz==this?this.ru.jfa(null):(this.ea(a.g.nUc),this.ru.Ba(this,this.PIb),this.ru=null)),b&&(b.Rz!=this?b.jfa(this):(this.ru=b,this.ru.Fa(this,this.PIb))),this.ea(a.g.h))};k.FId=function(a){return b.U().ZHa[a]};k.Fmc=function(){this.uxb=b.U().HCb();b.U().ZHa[this.uxb]=this};k.dka=function(a,b,c,d){return this.Ymc(b,d)};k.GYc=function(){this.MT.Oa(null)};k.Ymc=function(b,d){if(this.sb()){var e=b.ej(),k=null;this.G2.Ap(a.l.$d);this.G2.Ti(a.l.$d);this.G2.Uo(1);
this.G2.Bp(1);this.G2.on(1);this.G2.pn(1);this.Fg()&&(k=this.Dca()?a.$b.Y5b:a.$b.X5b,this.G2.Ap(a.l.OO),this.G2.Ti(a.l.b8));this.Nc()&&(k=this.Nc());this.w9.Oa(e);this.w9.wm(e.hc(0));this.w9.Tl(e.nc(0));this.w9.Cf(a.ya.dj);this.w9.rb(a.ma.Ks);this.w9.Bb(a.ka.vg);this.w9.Zd(4);this.w9.Dd(2);this.eua.Oa(e);this.eua.wm(e.hc(0));this.eua.Tl(e.nc(0));this.eua.Bb(a.ka.Wd);this.eua.rb(a.ma.al);this.eua.Zd(2);this.cHa.Oa(e);this.cHa.wm(e.hc(0));this.cHa.Tl(e.nc(0));this.cHa.Bb(a.ka.eg);this.cHa.Zd(22);this.MT.Oa(b);
this.MT.uo(e);this.MT.Td(d+1);this.MT.jL(this.kOa()?this.E2a:"");this.VL.qO(!1);this.VL.ls(a.be.t0);this.VL.zUa(a.LF.nCa);this.VL.uI(a.Yu.JM);this.VL.ub(this.eb());this.VL.qn(a.dh.Wq);this.VL.V0(this.ru?this.ru.iJ:null);this.bHa.Si(k);this.VL.Zj(!1,!0);e=60+this.VL.HR();k=10+this.VL.Cla();this.MT.kc(k);this.bHa.kb(new c.fa(2,2,18,18));this.VL.kb(new c.fa(22,2,e,18));b.Wb(Math.max(b.Qa(),e));b.kc(b.Ia()+this.MT.Ia());null!=this.ru&&this.ru.Y8b(this.ru.iJ);d++}return d};k.Msc=function(){delete b.U().ZHa[this.uxb];
b.U()};k.eUd=function(a){this.Td(a);null!=this.Xb&&this.Xb.C6()};k.v0=function(){this.ea(a.g.h,a.Je.ZVb)};k.Cuc=function(a,b){this.eF()&&this.$h(!0);this.Nf();this.L()&&this.L().FSa();b.HANDLED.set(!0)};k.PIb=function(){this.Ub()&&this.ea(a.g.h)};k.Dn=function(b,c){switch(c.Za){case a.g.wb:case a.g.Tb:this.od(null)}};k.PHb=function(b,c){switch(c.Za){case a.g.wb:case a.g.Tb:this.od(null)}};d.wd(c.m2b,"PRIM_MITM",{Pa:{Parent:{a:k.L,f:k.Oa},Caption:{a:k.eb,f:function(a){this.ub(d.ja(a))}},Checked:{a:k.Fg,
f:function(a){this.$h(d.wa(a))}},Default:{a:k.Y4,f:function(a){this.ZTa(d.wa(a))}},GroupIndex:{a:k.eF,f:function(a){this.R0(d.v(a))}},HelpContext:{a:k.AEc,f:function(a){this.j5c(d.v(a))}},MenuBreak:{a:function(){return d.sa(this.eGc(),a.IK.u)},f:function(b){this.Z5c(d.qa(b,a.IK.u))}},RadioItem:{a:k.Dca,f:function(a){this.nEa(d.wa(a))}},SubMenu:{a:k.sIc,f:k.Xpb},ShortCut:{a:function(){return d.sa(this.vva,a.W.u)},f:function(b){this.Y6c(d.qa(b,a.W.u))}},Tag:{a:k.qbb,f:function(a){this.eVa(d.v(a))}},
Tip:{a:k.UIc,f:function(a){this.a8c(d.ja(a))}},TipShow:{a:k.kOa,f:function(a){this.b8c(d.wa(a))}},TipShowOfParent:{a:k.zbb,f:function(a){this.c8c(d.wa(a))}},Enabled:{a:k.te,f:function(a){this.kg(d.wa(a))}},Visible:{a:k.sb,f:function(a){this.Gb(d.wa(a))}},DisplayPosition:{a:k.pg,f:function(a){this.Td(d.v(a))}},Image:{a:k.Nc,f:k.od}}})},{rp:["PRIM_TBLO","PRIM_PPNL","PRIM_IMAG","PRIM_SPBN"]});
