window.LANSA.addSrc("labl",function(d,c,a,b){a.Ivb={GVd:0,Mvb:16};a.V_={eSc:1,Mgb:1,Lgb:2,cXb:240};a.Jgb={qRa:0,v5b:1};c.Vt=function(){p.H.call(this);this.Ke(!1);this.Iqa(!1)};var p=c.q(c.Vt,c.Tt);p.vt=a.ip.cba;p.iU=a.V_.eSc;p.Bia=a.Jgb.qRa;p.PC=0;p.BC=0;p.EC=0;p.uC=0;p.kl=null;p.xP=a.Nk.LS;p.Ka=null;p.rw=0;p.mY=a.Qd.GI;p.f3=new c.WN(0,0,0,0);p.xM=new c.WN(0,0,0,0);p.Vc=p.Vc|a.cc.nda|a.cc.SAa|a.cc.Mfb|a.cc.DF|a.cc.FW|a.cc.Nfb|a.cc.CF;p.Jg=p.Jg|a.qh.Wna|a.qh.pS|a.qh.P_;p.R=function(){this.kl&&(this.kl.Ba(this,
this.l7a),this.kl=null);p.j.R.call(this);this.od(null)};p.hh=function(){return c.Wjb};p.bC=function(c){this.kl!=c&&(this.kl&&this.kl.Ba(this,this.l7a),this.kl=c,null==this.kl?this.Iqa(!1):(this.Iqa(!0),this.kl.Fa(this,this.l7a)),this.k(a.g.h),b.gb().Id(this,!1))};p.dF=function(){return this.kl};p.Rd=function(){return 0!=(this.iU&a.V_.Mgb)?!0:!1};p.Kx=function(){return!this.mo()&&this.Rd()};p.Se=function(c){c=this.iU&~a.V_.Mgb|(c?a.V_.Mgb:0);this.iU!=c&&(this.iU=c,this.yd(),b.gb().Id(this,!1),this.ea(a.g.h))};
p.TNa=function(){return 0!=(this.iU&a.V_.Lgb)?!0:!1};p.Hbc=function(b){b=this.iU&~a.V_.Lgb|(b?a.V_.Lgb:0);this.iU!=b&&(this.iU=b,this.Ch(),this.ea(a.g.h))};p.URd=function(c){this.sOa()!=c&&(this.iU=this.iU&~a.V_.cXb|c,this.yd(),b.gb().Id(this,!1),this.ea(a.g.h))};p.sOa=function(){return this.iU&a.V_.cXb};p.Uf=function(c){this.vt!=c&&(this.vt=c,b.gb().Id(this,!1),this.ea(a.g.h))};p.$e=function(){return this.vt};p.He=function(){return this.PC};p.td=function(c){this.PC!=c&&(this.PC=c,this.yd(),b.gb().Id(this,
!1),this.ea(a.g.h))};p.Qe=function(){return this.BC};p.Zd=function(c){this.BC!=c&&(this.BC=c,this.yd(),b.gb().Id(this,!1),this.ea(a.g.h))};p.Pf=function(){return this.EC};p.Dd=function(c){this.EC!=c&&(this.EC=c,this.yd(),b.gb().Id(this,!1),this.ea(a.g.h))};p.Zf=function(){return this.uC};p.Ae=function(c){this.uC!=c&&(this.uC=c,this.yd(),b.gb().Id(this,!1),this.ea(a.g.h))};p.$s=function(c){this.xP!=c&&(this.xP=c,b.gb().Id(this),this.k(a.g.h))};p.Nc=function(){return this.Ka};p.od=function(c){this.Ka!=
c&&(null!=this.Ka&&(this.Ka.Ba(this,this.Dn),this.Ka.Cb()),this.Ka=c,null!=this.Ka&&(this.Ka.Ha(),this.Ka.Fa(this,this.Dn)),this.yd(),b.gb().Id(this),this.k(a.g.h))};p.Hv=function(){return this.xP};p.Ot=function(){return this.rw};p.gs=function(c){c!=this.rw&&(this.rw=c,this.yd(),this.ea(a.g.h),b.gb().Id(this))};p.mD=function(){return this.mY};p.fC=function(b){this.mY!=b&&(this.mY=b,this.yd(),this.k(a.g.h))};p.Zm=function(){var b=a.be.GD;switch(this.hg()){case a.fh.nB:switch(this.kW()){case a.dh.Wq:b=
a.be.GD;break;case a.dh.SO:b=a.be.dSa;break;default:b=a.be.fSa}break;case a.fh.wJ:switch(this.kW()){case a.dh.Wq:b=a.be.eSa;break;case a.dh.SO:b=a.be.g7b;break;default:b=a.be.i7b}break;default:switch(this.kW()){case a.dh.Wq:b=a.be.t0;break;case a.dh.SO:b=a.be.f7b;break;default:b=a.be.IS}}return b};p.yD=function(){return 0!=(this.Bia&a.Jgb.v5b)};p.OFd=function(a){this.Bia|=a};p.bPc=function(a){this.Bia&=~a};p.PFd=function(a,b){this.Bia=this.Bia&~a|(b?a:0)};p.Pd=function(a,b,c){p.j.Pd.call(this,a,b,
c);this.lr(!1)};p.a7=function(a){p.j.a7.call(this,a);this.lr(a)};p.lr=function(a){p.j.lr.call(this,a);a=this.Ue();this.uJb(a,!1)};p.Cj=function(){p.j.Cj.call(this);this.Fd(a.Z.PB);this.Fd(a.Z.$Aa)};p.ad=function(){this.rJ(a.cc.LN,this.HN());p.j.ad.call(this)};p.kr=function(a){null!=this.kl?this.kl.df():p.j.kr.call(this,a)};p.ag=function(){this.w0();b.gb().YC(this)};p.ID=function(){this.YU()};p.QF=function(a){var b=!1,b=a.Cd().XSa(this,this.ca.Kh,this.lfb(),this.nfb(),this.mfb(),a);!1==b&&p.j.QF.call(this,
a)};p.ue=function(b){""==b[1]&&(b[1]=a.sWb);p.j.ue.call(this,b)};p.uJb=function(a,d){var m=b.uc(a),k=b.uc(m),h=null,f=0<this.rw?this.rw:-1;this.Ka&&(h=this.Ka.IEb(m.ba()-4,m.ba()-4));m.Ta(m.M()+this.PC);m.Va(m.O()+this.BC);m.Ra(m.va-this.EC);m.Ga(m.ua-this.uC);var e=this.eb(),q=new c.fa,g=new c.fa,B=[],v="";B[0]=q;B[1]=k;B[2]=g;B[3]=f;B[4]=f;B[5]=0;this.ADa(null,h,e,this.qe(),m,B);q=B[0];k=B[1];m=B[5];this.Ka&&this.Ka instanceof c.RN&&(v=this.Ka.Yg());this.f3=q;this.xM=k;d||(h=this.Sa().fb(),f=this.Kx(),
b.Xd[h].nh(h,k,v,q,f,this.TNa(),m))};p.ADa=function(d,r,m,k,h,f){d=f[0];var e=f[1],q=f[2],g=f[3],B=f[4],v=f[5],e=b.uc(h);if(null!=r&&this.Ld()){var p=a.cg.XEa;this.dF()||(p|=a.cg.$Va);v=p;if(this.Kx())switch(this.sOa()){case a.Ivb.Mvb:p|=a.cg.hC;break;default:p|=a.cg.hC,v|=a.cg.hC}else v|=this.vt;switch(this.hg()){case a.fh.nB:v|=a.cg.Lfa;break;case a.fh.wJ:v|=a.cg.ZEa;break;default:v|=a.cg.xsb}b.koa(r,m,k,h,0,this.Zm(),this.Zm(),this.Hv(),d,e,q,0,this.Ld()?0:2,g,B,p)}else if(v=this.MDb(e),0<m.length){e.aa()>
h.aa()&&(this.Kx()?this.sOa()==a.Ivb.Mvb&&(e=new c.fa(0,0,h.aa(),e.ba())):e=new c.fa(0,0,h.aa(),e.ba()));switch(this.hg()){case a.fh.nB:e=new c.fa(h.O()+(h.aa()-e.aa())/2,1,e.aa(),e.ba());v|=a.cg.Lfa;break;case a.fh.wJ:e=new c.fa(h.va-e.aa(),1,e.aa(),e.ba());v|=a.cg.ZEa;break;default:e=new c.fa(h.O(),1,e.aa()+1,e.ba()),v|=a.cg.xsb}switch(this.kW()){case a.dh.Wq:e=new c.fa(e.O(),h.M()+(h.ba()-e.ba())/2,e.aa(),e.ba());break;case a.dh.SO:e=new c.fa(e.O(),h.ua-1-e.ba(),e.aa(),e.ba())}}f[0]=d;f[1]=e;f[2]=
q;f[3]=g;f[4]=B;f[5]=v};p.MDb=function(c){var d=this.qe(),m=a.cg.XEa,k=this.eb();if(0<k.length)if(this.dF()||(m|=a.cg.$Va),this.QA=b.fO(k,d,this.Kx(),c.aa(),c.ba()),this.Kx())switch(this.sOa()){case a.Ivb.Mvb:b.DD(k,c,m|a.cg.hC,d);break;default:b.DD(k,c,m|a.cg.hC,d),m|=a.cg.hC}else b.DD(k,c,m,d),m|=this.vt;return m};p.gqc=function(){var a=b.wS();this.Zj(!1,!0);this.MDb(a);this.Wb(a.aa())};p.JD=function(c){if(this.TNa())switch(b.bs(c)){case a.W.DTa:case a.W.q$b:case a.W.x$b:case a.W.E0:case a.W.y$b:case a.W.b0c:case a.W.G1c:case a.W.t$b:case a.W.N1c:case a.W.FTa:c.Bl(!0);
return}p.j.JD.call(this)};p.CA=function(a){var b=this.mo(),c=this.iq();(b||c)&&this.l8b(a,b,c)};p.l8b=function(a,d,m){var k=new c.fa,h=new c.fa(0,0,1E4,1E4);this.Kx()&&h.Ra(h.O()+a.aa()-(this.ca.pj()+this.ca.Dk()));this.uJb(h,!0);""==this.eb()&&this.f3.qg()||(""==this.eb()?k=this.f3:(k=b.uc(this.xM),k.Ga(k.ua+(0<this.xM.ba()?1:0)),k=k.Y1(this.f3)));d&&a.Ra(a.O()+this.ca.pj()+this.BC+k.aa()+this.EC+this.ca.Dk());m&&a.Ga(a.M()+this.ca.Ek()+this.PC+k.ba()+this.uC+this.ca.fm())};p.uea=function(a,b,c){p.j.uea(a,
b,c);c[0]&&this.TNa()&&(c[0]=!1)};p.Nf=function(a){b.Fib();return p.j.Nf.call(this,a)};p.Dn=function(c,d){switch(d.Za){case a.g.wb:case a.g.Tb:d.$i==this.Ka&&this.od(null);break;case a.g.h:d.$i==this.Ka&&(b.gb().Id(this),this.yd())}};p.l7a=function(b,c){c.Za==a.g.Tb&&this.bC(null)};p.yv=p[a.Z.WH]=function(a){p.j.yv.call(this,a);b.gb().Id(this,!1)};p.rpd=p[a.Z.$Aa]=function(){b.gb().Id(this,!1)};p.WM=p[a.Z.PB]=function(){b.gb().Id(this,!1)};p.$ka=p[a.Z.jBa]=function(a){this.Uy()?this.Ke(!1):p.j.$ka.call(this,
a)};p.VM=p[a.Z.yK]=function(){this.kl&&this.kl.df()};p.yx=p[a.Z.bz]=function(b){this.yD()&&(this.qq(),this.bPc(a.Jgb.v5b));p.j.yx.call(this,b)};d.wd(c.Vt,"PRIM_LABL",{Pa:{Ellipses:{a:function(){return d.sa(this.$e(),a.ip.u)},f:function(b){this.Uf(d.qa(b,a.ip.u))}},Caption:{a:p.eb,f:function(a){this.ub(d.ja(a))}},Alignment:{a:function(){return d.sa(this.hg(),a.fh.u)},f:function(b){this.rb(d.qa(b,a.fh.u))}},VerticalAlignment:{a:function(){return d.sa(this.kW(),a.dh.u)},f:function(b){this.qn(d.qa(b,
a.dh.u))}},FocusControl:{a:p.dF,f:p.bC},WordWrap:{a:p.Rd,f:function(a){this.Se(d.wa(a))}},Selectable:{a:p.TNa,f:function(a){this.Hbc(d.wa(a))}},MarginLeft:{a:p.Qe,f:function(a){this.Zd(d.v(a))}},MarginTop:{a:p.He,f:function(a){this.td(d.v(a))}},MarginBottom:{a:p.Zf,f:function(a){this.Ae(d.v(a))}},MarginRight:{a:p.Pf,f:function(a){this.Dd(d.v(a))}},Image:{a:p.Nc,f:p.od},ImagePosition:{a:function(){return d.sa(this.Hv(),a.Nk.u)},f:function(b){this.$s(d.qa(b,a.Nk.u))}},ImageHeight:{a:p.Ot,f:function(a){this.gs(d.v(a))}},
ImageSizing:{a:function(){return d.sa(this.mD(),a.Qd.u)},f:function(b){this.fC(d.qa(b,a.Qd.u))}}},Bg:{wg:"Caption"}});c.Wjb=function(a){u.H.call(this,a);this.sZa=this.rw=this.GHa=this.Zyb=this.Yyb=this.Ka=this.cH=this.zja=this.CE=this.yBb=this.xBb=this.wBb=this.qb=null};var u=c.q(c.Wjb,c.kn);u.eb=function(){return this.qb.textContent};u.ub=function(a){this.qb.textContent=a};u.l5=function(){return this.qb};u.lN=function(){return this.qb};u.nh=function(b,c,m,k,h,f,e){null==this.Ka.parentElement&&this.G.appendChild(this.Ka);
if(null==this.sZa||this.sZa!=f)this.sZa=f,this.qb.spellcheck=!1,this.qb.setAttribute("contenteditable",f);this.Ka.style.backgroundImage=d.xv(m);switch(this.pa.mD()){case a.Qd.GI:this.Ka.style.backgroundSize="contain";break;case a.Qd.OEa:this.Ka.style.backgroundSize="cover";break;case a.Qd.eg:this.Ka.style.backgroundSize="100% 100%";break;case a.Qd.Wd:this.Ka.style.backgroundSize="auto"}if(null==this.cH||this.cH!=h)this.cH=h,this.qb.style.whiteSpace=h?"pre-wrap":"pre";if(null==this.zja||this.zja!=
e)this.zja=e,this.qb.style.textAlign=0!=(e&a.cg.ZEa)?"right":0!=(e&a.cg.Lfa)?"center":"",0!=(e&a.cg.WEa)||0!=(e&a.cg.YEa)||0!=(e&a.cg.$Ea)?(this.qb.style.textOverflow="ellipsis",this.qb.style.overflow="hidden"):(this.qb.style.textOverflow="clip",this.qb.style.overflow="visible");if(null==this.wBb||this.wBb!=c.O())this.wBb=c.O(),this.qb.style.left=c.O()+"px";if(null==this.xBb||this.xBb!=c.M())this.xBb=c.M(),this.qb.style.top=c.M()+"px";if(null==this.CE||this.CE!=c.ba())this.CE=c.ba(),this.qb.style.height=
c.ba()+"px";if(null==this.yBb||this.yBb!=c.aa())this.yBb=c.aa(),this.qb.style.width=c.aa()+"px";if(null==this.Yyb||this.Yyb!=k.O())this.Yyb=k.O(),this.Ka.style.left=k.O()+"px";if(null==this.Zyb||this.Zyb!=k.M())this.Zyb=k.M(),this.Ka.style.top=k.M()+"px";if(null==this.rw||this.rw!=k.ba())this.rw=k.ba(),this.Ka.style.height=k.ba()+"px";if(null==this.GHa||this.GHa!=k.aa())this.GHa=k.aa(),this.Ka.style.width=k.aa()+"px"};u.cf=function(a,b){this.G=document.createElement("div");this.G.setAttribute("LANSAHandle",
this.jc);this.qb=document.createElement("div");var c=this.qb.style;c.position="absolute";c.outline="none";c.overflowX="hidden";c.overflowY="hidden";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";c.borderStyle="solid";c.borderLeftWidth="0px";c.borderTopWidth="0px";c.borderRightWidth="0px";c.borderBottomWidth="0px";c.cursor="inherit";c.textDecoration="inherit";this.Ka=document.createElement("div");c=this.Ka.style;c.position="absolute";c.backgroundSize="contain";
c.backgroundPosition="center center";c.backgroundRepeat="no-repeat";this.G.appendChild(this.qb);this.G.appendChild(this.Ka);return u.j.cf.call(this,a,b)};u.gZ=function(){var a=this;this.e4();a.qb.addEventListener("paste",function(b){a.qea(b);b.preventDefault()},!1)};u.Xub=function(){var a="";u.j.Xub.call(this);"rgba(0,0,0,0)"==this.tYa&&""!=this.G.style.boxShadow&&(a=this.G.style.boxShadow);this.qb.style.textShadow=a};u.gO=function(a){u.j.gO.call(this,a);return!this.sZa};u.qea=function(){}});
