window.LANSA.addSrc("ver",function(d,c,a,b,p){c.pXb=function(){u.H.call(this);this.Wf=new c.qd;this.Fua=this.Ya=null};var u=c.q(c.pXb,c.Gd);u.yEc=function(){return document.hasFocus()};u.y9c=function(a,r,m){var k=d.pd("PRIM_VS","Style"),h=null,f=null;r===p&&(r=0);m===p&&(m=0);if(a){if(0==r&&0==m)a.Zj(!0),h=a.ca;else if(0!=r){var e=a.ZC(new c.fa,null);r=a.Eia.Pb[r-1];a.Yf().Sa().Blb(e,r,a.Dia,null,null,r.fb());h=r.Eu();if(0!=m&&(m=a.V6a(m-1)))for(var q in r.fb().vv)if(f=r.fb().vv[q],f.zo.Na==m){a.Yf().Sa().zlb(e,
f.zo,f.zo.Fca(),f.zo.Jc.PNa(),f.zo.Na.u5(),null);h=f.zo.Fca();break}b.$(e)}h&&(k.Ti(h.Kh),k.Ap(h.fN()),k.Qg(h.iu),k.dy(h.iF()),k.ui(h.fq()),k.jd(h.Ns()),k.tg(h.Cx()),k.Ep(h.Ev()),k.Rv(h.Cv()),k.Sv(h.Dv()),k.Pv(h.Av()),k.Qv(h.Bv()),k.Uo(h.pj()),k.Bp(h.Ek()),k.on(h.fm()),k.pn(h.Dk()),k.sO(h.qe().Oy()),k.Zs(h.qe().Ia()),k.lz(h.qe().gj()),k.YF(h.qe().My()),k.zO(h.qe().Ry()),k.$S(h.qe().LH()),k.dT(h.qe().NH()));f&&(a.Yf().Sa().Df.Np&&k.ui(a.Yf().Sa().Df.Np),a.Yf().Sa().Df.Qj&&k.jd(a.Yf().Sa().Df.Qj))}return k};
u.Ifd=function(a,b){var c=[[],null,null];a.j9a(b,c);return c[1]};u.orc=function(){null.Upd()};u.oqc=function(a,d,m){var k;m===p&&(m=1);k===p&&(k=!0);a=new c.qd(a,d);if((d=b.yS(a))&&d.te()){var h=d.ti(a),f=new c.Ou(d,h,a,1),e=new c.Ou(d,h,a,1),q=new c.Ou(d,h,a,2);b.WD(a.Hb(),a.Lb(),h.Hb(),h.Lb());k?(k=b.U(),d.jj(f),null==k.xj?d.nn(e):(k=k.xj.fb(),b.Uvb(null,k,h.Hb(),h.Lb(),a.Hb(),a.Lb())),2==m&&(q=new c.Ou(d,h,a,2),d.jj(q))):(d.VW(f),d.Npa(e));b.$(f);b.$(q);b.$(e)}};u.egd=function(a,d){var m=new c.qd(a,
d),k=b.yS(m);if(k&&k.te()){var h=k.ti(m),f=new c.Ou(k,h,m,1),e=new c.Ou(k,h,m,1),q=new c.Ou(k,h,m,1),g=!1;b.WD(m.Hb(),m.Lb(),h.Hb(),h.Lb());k.cDa(h,k,!1);k.Gea(q);g=q.oh;g||(k.jj(f),k.nn(e));b.$(f);b.$(e);b.$(q)}};u.tLc=function(a,d){var m=new c.qd(a,d),k=b.yS(m);if(k&&k.te()){var h=k.ti(m);for(b.WD(m.Hb(),m.Lb(),h.Hb(),h.Lb());k;)h=k.ti(m),b.Iic(null,k.fb(),h.Hb(),h.Lb(),m.Hb(),m.Lb()),k=k.L()}};u.y4c=function(a,d){var m=new c.qd(a,d),k=b.yS(m);k&&k.te()&&(k=k.ti(m),b.WD(m.Hb(),m.Lb(),k.Hb(),k.Lb()))};
u.e5c=function(a,d){(this.Fua=b.yS(new c.qd(a,d)))&&document.hasFocus()&&(b.Rvb(this.Fua.fb()),this.Fua=null)};u.ROc=function(a,c){if(""!=a||0!=c){var d=0==c?a.charCodeAt(0):c,k;if(document.hasFocus())k=b.Svb();else if(this.Fua)k=this.Fua.fb();else return;b.Fic(null,k,d);""!=a&&b.Gic(null,k,a,a.charCodeAt(0));b.Hic(null,k,d)}};u.QTc=function(a,d){this.Wf=new c.qd(this.Wf.Hb()+(0<a?1:0==a?0:-1),this.Wf.Lb()+(0<d?1:0==d?0:-1));if(this.Ya){var m=this.Ya.ti(this.Wf);b.WD(this.Wf.Hb(),this.Wf.Lb(),m.Hb(),
m.Lb());b.J2b(this.Ya,m,this.Wf)}};u.gSc=function(a,d,m){m===p&&(m=1);this.Wf=new c.qd(a,d);if(this.Ya=b.yS(this.Wf))a=!1,d=this.Ya.ti(this.Wf),this.Ya.gg.$l&&(new c.fa(this.Ya.gg.$l.yf,this.Ya.gg.$l.Xf,this.Ya.gg.$l.Zc,this.Ya.gg.$l.kd)).xe(d)&&(this.Ya.gg.$l.$Ca(null),a=this.Ya.gg.$l.XG),a||(b.WD(this.Wf.Hb(),this.Wf.Lb(),d.Hb(),d.Lb()),b.H2b(this.Ya,d,this.Wf,m))};u.hSc=function(){if(this.Ya){var a=!1,d=this.Ya.ti(this.Wf);this.Ya.gg.$l&&(new c.fa(this.Ya.gg.$l.yf,this.Ya.gg.$l.Xf,this.Ya.gg.$l.Zc,
this.Ya.gg.$l.kd)).xe(d)&&(this.Ya.gg.$l.aDa(null),a=this.Ya.gg.$l.XG);a||(b.WD(this.Wf.Hb(),this.Wf.Lb(),d.Hb(),d.Lb()),b.I2b(this.Ya,d,this.Wf,1));this.Ya=null}};u.J_c=function(a,d){this.Wf=new c.qd(a,d);if(this.Ya=b.yS(this.Wf)){var m=this.Ya.ti(this.Wf);b.WD(this.Wf.Hb(),this.Wf.Lb(),m.Hb(),m.Lb());b.K2b(this.Ya,m,this.Wf,1)}};u.K_c=function(){if(this.Ya){var a=this.Ya.ti(this.Wf);b.WD(this.Wf.Hb(),this.Wf.Lb(),a.Hb(),a.Lb());b.L2b(this.Ya,a,this.Wf,1);this.Ya=null}};d.mb(c.pXb,"PRIM_VER","Debugger",
{Pa:{HasFocus:{a:u.yEc}},pc:{Crash:function(){this.orc()},Click:function(a,b,c){this.oqc(d.v(a),d.v(b),c===p?1:d.v(c))},Touch:function(a,b){this.egd(d.v(a),d.v(b))},Hover:function(a,b){this.tLc(d.v(a),d.v(b))},SetCursorPos:function(a,b){this.y4c(d.v(a),d.v(b))},SetFocus:function(a,b){this.e5c(a,b)},KeyPress:function(a,b){this.ROc(d.ja(a),b===p?0:d.v(b))},MouseMove:function(a,b){this.QTc(a,b)},LeftMouseDown:function(a,b,c){this.gSc(d.v(a),d.v(b),c===p?1:d.v(c))},LeftMouseUp:function(){this.hSc()},
RightMouseDown:function(a,b){this.J_c(a,b)},RightMouseUp:function(){this.K_c()},StyleSnapshot:function(a,b,c){return this.y9c(a,b===p?0:d.v(b),c===p?0:d.v(c))},ThemeDrawStyle:function(a,b){return this.Ifd(a,d.ja(b))}}})});
