window.LANSA.addSrc("video",function(e,c,a,b,m){var p,l;p={ALL:0,METADATA:1,NONE:2};l={auto:0,metadata:1,none:2};c.HNa=function(a){s.w.call(this);this.x1=this.Es="";this.Efa=a};var s=c.u(c.HNa,c.wd);s.U=function(){s.j.U.call(this)};s.zh=function(){return this.Es};s.fw=function(a){this.Es=a};s.lY=function(){return this.x1==m?"":this.x1};s.k_=function(a){this.x1=a};s.fr=function(){for(var a=0;a<this.Efa.mc();a++)this.Efa.mr(a)===this&&this.Efa.zr(a)};e.jb(c.HNa,"PRIM_VDEO","File",{Oa:{FileName:{a:s.zh,
g:function(a){this.fw(e.ma(a))}},FileExtension:{a:s.lY,g:function(a){this.k_(e.ma(a))}}},jc:{Delete:s.fr},lg:{hg:"FileExtension"}});c.Eeb=function(a){g.w.call(this);this.nhc=a;this.ab=[]};var g=c.u(c.Eeb,c.wd);g.mc=function(){return this.ab.length};g.Td=function(a){return this.mr(a)};g.mr=function(a){if(0>a||a>=this.ab.length)throw e.FE(a,this.ab.length);return this.ab[a]};g.oh=function(a,b){var e=new c.HNa(this);e.fw(a);e.k_(b);this.ab.push(e);(e=this.nhc.Pa())&&e.Jr()};g.Iva=function(){0==this.mc()&&
this.ab.push(new c.HNa(this));return this.mr(0)};g.bk=function(){this.ab=[];var a=this.nhc.Pa();a&&a.Jr()};g.zr=function(a){if(null==this.mr(a))throw e.FE(a,this.ab.length);this.ab.splice(a,1)};g.ITc=function(a){for(var b=!1,c=0;c<this.mc()&&!(b=this.mr(c).zh()==a);c++);b&&this.zr(c)};e.jb(c.Eeb,"PRIM_VDEO","Files",{Oa:{Item:{a:function(a){return this.mr(e.K(a)-1)}}},jc:{Add:g.oh,RemoveAll:g.bk,Remove:function(a){return this.zr(e.K(a)-1)}},gq:{Bp:function(a){return this.mr(e.K(a)-1)},Qv:function(){return this.mc()}},
lg:{hg:"Item"}});c.E_b=function(){q.w.call(this);this.Y0=0;this.L0=this.j2=!0;this.JS=1;this.tw=new c.Eeb(this);this.Nh=-1;this.oS=this.Hga=this.Jga=!1;this.HB=50};var q=c.u(c.E_b,c.Vs);q.eh=function(){return c.X0b};q.U=function(){q.j.U.call(this)};q.zh=function(){return 0<this.tw.mc()?this.tw.mr(0).zh():""};q.fw=function(b){this.tw.bk();var c=this.tw.Iva();c.zh()!=b&&(c.fw(b),(b=this.Pa())&&b.Jr(),this.l(a.f.h))};q.lY=function(){return 0<this.tw.mc()?this.tw.mr(0).lY():""};q.k_=function(b){var c=
this.tw.Iva();c.lY()!=b&&(c.k_(b),(b=this.Pa())&&b.Jr(),this.l(a.f.h))};q.Azc=function(){return this.tw};q.F6a=function(){return this.Y0};q.Kkb=function(b){this.Y0!=b&&(this.Y0=b,(b=this.Pa())&&b.Jr(),this.l(a.f.h))};q.l7a=function(){return this.oS};q.b8a=function(){return this.j2};q.emb=function(b){this.j2!=b&&(this.j2=b,(b=this.Pa())&&b.Jr(),this.l(a.f.h))};q.Z5a=function(){return this.L0};q.okb=function(b){this.L0!=b&&(this.L0=b,(b=this.Pa())&&b.Jr(),this.l(a.f.h))};q.G3=function(){return this.Nh};
q.m7a=function(){return this.Jga};q.k7a=function(){return this.Hga};q.c9a=function(){return this.HB};q.xBa=function(c){c=b.Pg(c,0,100);this.HB!=c&&(this.HB=c,this.oS=0==this.HB,(c=this.Pa())&&c.Jr(),this.l(a.f.h))};q.nCc=function(){return this.JS};q.Wlb=function(b){this.JS!=b&&(this.JS=b,(b=this.Pa())&&b.Jr(),this.l(a.f.h))};q.Play=function(){this.Pa()&&this.Pa().Play()};q.Wh=function(){this.Pa()&&this.Pa().Wh()};q.zhb=function(){this.xBa(0)};q.Mvc=function(){if(this.Pa()){var a=this.Pa().J;a.currentTime=
Math.min(a.duration,a.currentTime+5)}};q.Lvc=function(){if(this.Pa()){var a=this.Pa().J;0<a.currentTime&&(a.currentTime-=5)}};e.kd(c.E_b,"PRIM_VDEO",{Oa:{FileName:{a:q.zh,g:function(a){this.fw(e.ma(a))}},CycleToStart:{a:q.F6a,g:function(a){this.Kkb(e.za(a))}},ShowControls:{a:q.b8a,g:function(a){this.emb(e.za(a))}},Autoplay:{a:q.Z5a,g:function(a){this.okb(e.za(a))}},Preload:{a:function(){return e.ta(this.JS,p)},g:function(a){this.Wlb(e.ra(a,p))}},Duration:{a:q.G3},IsMuted:{a:q.l7a},IsPlaying:{a:q.m7a},
IsEnded:{a:q.k7a},Volume:{a:q.c9a,g:function(a){this.xBa(e.K(a))}}},jc:{Play:q.Play,Stop:q.Wh,Mute:q.zhb,FrameForward:q.Mvc,FrameBackward:q.Lvc}});c.X0b=function(a){f.w.call(this,a)};var f=c.u(c.X0b,c.kn);f.lf=function(b,c){this.J=document.createElement("video");this.CDa=b+this.gc;this.J.setAttribute("id",this.CDa);this.J.setAttribute("LANSAHandle",this.gc);this.J.style.position="absolute";this.J.style.overflow="hidden";this.J.style.whiteSpace="nowrap";this.Jr();var e=this.J,g=this;e.addEventListener("loadedmetadata",
function(){g.pa.Nh=e.duration;g.pa.Ga(a.G.bTb)},!1);e.addEventListener("loadeddata",function(){g.pa.Ga(a.G.aTb)},!1);e.addEventListener("play",function(){g.pa.Jga=!0;g.pa.Hga=!1;g.pa.Ga(a.G.Y2b)},!1);e.addEventListener("pause",function(){g.pa.Jga=!1;g.pa.Ga(a.G.o9b)},!1);e.addEventListener("ended",function(){g.J.pause();g.J.paused=!0;g.pa.Hga=!0;g.pa.Ga(a.G.Tx)},!1);e.addEventListener("volumechange",function(){e.muted||0==e.volume?(g.J.muted=!0,g.pa.oS=!0,g.pa.HB=0,g.pa.Ga(a.G.X1b)):(g.pa.oS=!1,g.pa.HB=
Math.round(100*e.volume))},!1);return f.j.lf.call(this,b,c)};f.Jr=function(){this.boa("controls",this.pa.j2);this.boa("autoplay",this.pa.L0);this.boa("loop",this.pa.Y0);this.J.setAttribute("preload",e.ta(this.pa.JS,l));this.J.volume=0<this.pa.HB?this.pa.HB/100:0;this.J.muted=this.pa.oS;this.mrb()};f.mrb=function(){this.ujb();var a=this.pa.tw.mc();if(0!=a)for(var b=0;b<a;b++){var c=this.pa.tw.mr(b);this.lic(this.J,c.Es,c.x1)}};f.lic=function(a,b,c){var e=document.createElement("source");e.src=b;c&&
(e.type="video/"+c);a.appendChild(e)};f.ujb=function(){var a=document.getElementById(this.CDa);if(a&&(a=a.childNodes)){var b,c,e=[];for(c=0;c<a.length;c++)b=a[c],"SOURCE"==b.nodeName&&e.push(b);for(c=0;c<e.length;c++)b=e[c],b.parentNode.removeChild(b)}};f.zM=function(){return!1};f.HOa=function(){};f.Play=function(){this.J.play!==m&&this.J.play()};f.Wh=function(){this.J.pause!==m&&this.J.pause()}});
