window.LANSA.addSrc("gpbx",function(e,c,a,b){a.Utc={EQd:0,DQd:9,hed:6,FQd:5,GQd:10};a.WEc={Yvc:0};c.gYb=function(){m.w.call(this);this.wub=a.Utc.hed;this.GH=a.WEc.Yvc;this.VH=new c.ga;this.Qc=this.Qc|a.ac.Dba|a.ac.Qxa|a.ac.acb|a.ac.vE|a.ac.OU|a.ac.uE;this.ug=this.ug|a.Xg.vQ|a.Xg.iZ;this.Ef(!1)};var m=c.u(c.gYb,c.qM);m.eh=function(){return c.x0b};m.IKd=function(b){this.wub!=b&&(this.wub=b,this.l(a.f.h),this.Pv())};m.Trd=function(){return this.wub};m.Jq=function(a){m.j.Jq.call(this,a);this.qQc()};m.Qqb=
function(){if(this.Pb()){var a=this.me(),a=Math.abs(a.Qa()),c=this.Oe();this.Cd();this.Cd();c.Ta(c.Q()+a);""==this.ob()?(c.Ra(c.Q()),c.Ha(a)):(this.ob(),c.Ra(c.Q()+this.XT()),c.Ha(this.Hja()),c.Ra(c.va+a));b.ao(this.VH,c)||(this.VH=c,this.nb());this.Jq(!0)}};m.Ze=function(a){a.Ua(a.O()+this.VH.ba());a.Ta(a.Q()+4);a.Ra(a.va-4);a.Ha(a.ua-4);m.j.Ze.call(this,a)};m.iTc=function(a,b,c){a.Ua(a.O()+this.VH.ba());a.Ta(a.Q()+4);a.Ra(a.va-4);a.Ha(a.ua-4);m.j.iTc.call(this,a,b,c)};m.Dj=function(){m.j.Dj.call(this);
this.Dd(a.$.Dz)};m.Zc=function(){var b=this.XL()||this.gl()&&(this.hZ()||this.tQ());this.YH(a.ac.aM,b);m.j.Zc.call(this)};m.DE=function(a){var b=!1,b=a.he().$Pa(this,this.ea.Zh,this.hZ(),this.tQ(),a);!1==b&&m.j.DE.call(this,a)};m.jV=function(a){var b=!1;null!=a.he()&&a.ha().gl()&&(b=a.he().aQa(this,this.ea.Zh,a,this.hZ(),this.tQ()));!1==b&&m.j.jV.call(this,a)};m.se=function(b){""==b[1]&&(b[1]=a.gSb);m.j.se.call(this,b)};m.qQc=function(){var a=this.Oe(),a=this.OB(a,null),c=this.Oe();c.Ua(c.O()+this.VH.ba()/
2+1);c.Ta(c.Q()+2);c.Ra(c.va-2);c.Ha(c.ua-2);var e=this.Pa().ib(),q=this.ob();b.Pd[e].Ug(q,c,this.VH);b.la(a)};m.ds=m[a.$.FG]=function(a){this.Qqb();m.j.ds.call(this,a)};m.Gu=m[a.$.EG]=function(){m.j.Gu.call(this);this.Qqb()};m.eG=m[a.$.Dz]=function(){this.Qqb();this.Pv()};m.Erc=m[a.$.Fcb]=function(){this.hh()};e.kd(c.gYb,"PRIM_GPBX",{Oa:{Caption:{a:m.ob,g:function(a){this.Ab(e.ma(a))}},ThemeStyle:{a:function(){return e.ta(this.OL(),a.gv.v)},g:function(b){this.sBa(e.ra(b,a.gv.v))}}}});c.x0b=function(a){p.w.call(this,
a);this.mb=this.uVa=this.mDa=this.be=this.Kc=null};var p=c.u(c.x0b,c.X4);p.lf=function(a,b){var c=null;p.j.lf.call(this,a,b);this.uVa=4;this.Kc=document.createElement("div");this.be=document.createElement("div");this.mDa=document.createElement("div");this.mb=document.createElement("span");this.J.appendChild(this.Kc);this.J.appendChild(this.be);this.J.appendChild(this.mDa);this.J.appendChild(this.mb);this.W$a(this.Kc,this.uVa);this.W$a(this.be,0);this.W$a(this.mDa,0);c=this.Kc.style;c.borderTopWidth=
"0px";c=this.be.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.mDa.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.mb.style;c.position="absolute";c.whiteSpace="nowrap";c.cursor="inherit";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";return this.J};p.W$a=function(a,b){var c=a.style;c.position="absolute";c.overflowX="hidden";c.overflowY=
"hidden";c.whiteSpace="nowrap";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";c.borderStyle="solid";c.outline="none";c.background="rgba(0,0,0,0)";c.borderTopWidth="1px";c.borderBottomWidth="1px";c.borderLeftWidth="1px";c.borderRightWidth="1px";c.borderTopLeftRadius=b+"px";c.webkitBorderTopLeftRadius=b+"px";c.borderTopRightRadius=b+"px";c.webkitBorderTopRightRadius=b+"px";c.borderBottomLeftRadius=b+"px";c.webkitBorderBottomLeftRadius=b+"px";c.borderBottomRightRadius=
b+"px";c.webkitBorderBottomRightRadius=b+"px"};p.Ug=function(a,b,c){var e=this.Kc.style;e.left=b.Q()+"px";e.top=b.O()+"px";e.width=b.aa()+"px";e.height=b.ba()+"px";e.borderColor=this.El();e=this.be.style;e.left=b.Q()+this.uVa-1+"px";e.top=b.O()+"px";e.width=c.Q()-b.Q()+"px";e.height="1px";e.borderColor=this.El();e=this.mDa.style;e.left=c.va+2+"px";e.top=b.O()+"px";e.width=b.va-this.uVa-c.va+"px";e.height="1px";e.borderColor=this.El();e=this.mb.style;e.left=c.Q()+7+"px";e.top=c.O()+2+"px";e.height=
c.ba()+"px";e.width=c.aa()+"px";this.mb.textContent=a}});
