window.LANSA.addSrc("imag",function(d,c,a,b){c.Xt=function(){p.H.call(this);this.yt="";this.gc=this.ib=this.zz=this.NZa=this.NT=this.Pe=this.of=null;this.oY=a.Sd.aFa;this.wC=this.HC=this.EC=this.SC=0;this.Xc|=a.cc.aBa;this.wia=new c.so;this.wia.Le(!1);this.wia.Oa(this);this.Pe=new c.CS;this.of=new c.pb;this.of.kd(this.Pe);this.wia.ufa(this.of);this.Le(!1)};var p=c.q(c.Xt,c.so);p.nb=function(){b.$(this.wia);this.wia=null;b.$(this.Pe);this.Pe=null;b.$(this.of);this.of=null;p.j.nb.call(this)};p.R=function(){p.j.R.call(this);
this.Iqa(null);this.NZa=null;this.Ti(null);this.Zo(null)};p.Yg=function(){return this.yt};p.$s=function(c){b.yA(this.yt,c)||(this.yt=c,this.Iqa(b.Voa(this.yt)),this.k(a.g.h))};p.uvd=function(){return this.NT};p.Iqa=function(b){this.NT!=b&&(this.Ti(null),null!=this.NT&&this.NT.Ba(this,this.vHb),this.NT=b,null!=this.NT&&this.NT.Fa(this,this.vHb),this.DL(),this.ob(),this.k(a.g.h))};p.LZ=function(){return this.zz};p.Ti=function(b){this.zz!=b&&(this.Iqa(null),null!=this.zz&&(this.zz.Ba(this,this.Gn),this.zz.Cb()),
this.zz=b,null!=this.zz&&(this.zz.Ha(),this.zz.Fa(this,this.Gn)),this.DL(),this.ob(),this.zd(),this.k(a.g.h))};p.OR=function(){return this.Pe.sl()};p.BO=function(b){this.Pe.sl()!=b&&(this.Pe.cg(b),this.k(a.g.h))};p.UJ=function(){return this.Pe.Qd()};p.kL=function(b){this.Pe.Qd()!=b&&(this.Pe.Va(b),this.k(a.g.h))};p.WJ=function(){return this.Pe.ie()};p.lL=function(b){this.Pe.ie()!=b&&(this.Pe.Ua(b),this.k(a.g.h))};p.IH=function(){return this.Pe.Qa()};p.SD=function(b){this.Pe.Qa()!=b&&(this.Pe.Wb(b),
this.k(a.g.h))};p.Rt=function(){return this.Pe.Ia()};p.hs=function(b){this.Pe.Ia()!=b&&(this.Pe.lc(b),this.k(a.g.h))};p.pD=function(){return this.oY};p.gC=function(b){this.oY!=b&&(this.oY=b,this.Pe.Bb(b),this.ob(),this.zd(),this.k(a.g.h))};p.VJ=function(){return this.Pe.iW()};p.hG=function(b){this.Pe.iW()!=b&&(this.Pe.Y7(b),this.k(a.g.h))};p.XJ=function(){return this.Pe.ij()};p.mL=function(b){this.Pe.ij()!=b&&(this.Pe.tk(b),this.k(a.g.h))};p.nA=function(){return this.Pe.ig()};p.kz=function(b){this.Pe.ig()!=
b&&(this.Pe.rb(b),this.k(a.g.h))};p.Qg=function(b){this.ib!=b&&(this.Zo(b),this.k(a.g.h))};p.hb=function(){var a=null;return a=this.ib};p.fc=function(){return this.gc};p.Ie=function(){return this.SC};p.ud=function(c){this.SC!=c&&(this.SC=c,this.ob(),this.zd(),b.gb().Jd(this,!1),this.ea(a.g.h))};p.Re=function(){return this.EC};p.$d=function(c){this.EC!=c&&(this.EC=c,this.ob(),this.zd(),b.gb().Jd(this,!1),this.ea(a.g.h))};p.Sf=function(){return this.HC};p.Fd=function(c){this.HC!=c&&(this.HC=c,this.ob(),
this.zd(),b.gb().Jd(this,!1),this.ea(a.g.h))};p.$f=function(){return this.wC};p.Be=function(c){this.wC!=c&&(this.wC=c,this.ob(),this.zd(),b.gb().Jd(this,!1),this.ea(a.g.h))};p.Em=function(a,b,c,d,k){return k};p.HM=function(){var a=this.gc.Jj();""!=a?this.NT&&this.NT.Yg()==a||this.Iqa(b.Voa(a)):this.Iqa(this.gc.jna());this.ib.BV(this.fc())};p.Zo=function(a){var c=null;a&&(c=a.wx(),this.ib==a?c.Xm(this.gc):a.dA(c));this.ib&&(this.ib.Ba(this),this.gc.Ba(this),b.$(this.gc),this.gc=null);if(this.ib=a)this.ib.Fa(this,
this.io),this.gc=c,this.gc.Fa(this,this.Iw);this.Dh()};p.DL=function(){null==this.zz?this.Pe.pd(this.NT):this.NZa&&0<this.NZa.Yg().length?this.Pe.pd(this.NZa):this.Pe.pd(this.zz)};p.hf=function(b){var d=new c.ga(0,0,b.aa(),b.ba());p.j.hf.call(this,b);d.Ua(d.M()+this.SC);d.Va(d.O()+this.EC);d.Ra(d.va-this.HC);d.Ga(d.ua-this.wC);this.wia.tb(this);this.wia.kb(d);this.pD()==a.Sd.aFa&&this.Pe.Oc()&&(this.Pe.Oc().Ia()>d.ba()||this.Pe.Oc().Qa()>d.aa()?this.Pe.Bb(a.Sd.HI):this.Pe.Bb(a.Sd.Xd))};p.AA=function(b){var d=
this.po(),r=this.jq();if(0!=this.WJ()||0!=this.UJ()||100!=this.IH()||100!=this.Rt()||this.VJ()!=a.Lr.n8||this.XJ()!=a.Dw.E8||this.Pe.sh()==a.Sd.$Ea)r=d=!1;if(d||r){var n=new c.ga;if(this.Pe.Oc())switch(n.Ra(this.Pe.Oc().Qa()),n.Ga(this.Pe.Oc().Ia()),this.Pe.sh()){case a.Sd.HI:if(r&&!d&&0<b.aa()&&0<n.aa()){var k=b.aa()/n.aa();n.Ga(n.M()+n.ba()*k)}}d&&b.Ra(b.O()+this.ca.rj()+this.EC+n.aa()+this.HC+this.ca.Fk());r&&b.Ga(b.M()+this.ca.Gk()+this.SC+n.ba()+this.wC+this.ca.km())}};p.Qf=function(a){b.Tib();
return p.j.Qf.call(this,a)};p.Gn=function(b,c){switch(c.Za){case a.g.wb:case a.g.Tb:this.Ti(null);break;case a.g.h:this.ob(),this.zd()}};p.vHb=function(b,c){switch(c.Za){case a.g.wb:case a.g.Tb:this.Iqa(null);break;case a.g.h:this.ob()}};p.io=function(b,c){c.Za==a.g.h?c.Dt==a.Ke.Rx?this.ib.dA(this.fc()):this.Zo(this.ib):c.Za==a.g.wb&&this.Qg(null)};p.Iw=function(b,c){c.Za==a.g.h&&c.Dt==a.Ke.Rx&&this.HM()};d.xd(c.Xt,"PRIM_IMAG",{Pa:{FileName:{a:p.Yg,f:function(a){this.$s(d.ja(a))}},Image:{a:p.LZ,f:function(a){this.Ti(a)}},
ImageTile:{a:function(){return d.sa(this.VJ(),a.Lr.u)},f:function(b){this.hG(d.qa(b,a.Lr.u))}},ImageUnits:{a:function(){return d.sa(this.XJ(),a.Dw.u)},f:function(b){this.mL(d.qa(b,a.Dw.u))}},ImageSizing:{a:function(){return d.sa(this.pD(),a.Sd.u)},f:function(b){this.gC(d.qa(b,a.Sd.u))}},ImageOpacity:{a:p.OR,f:function(a){this.BO(d.v(a))}},ImageLeft:{a:p.UJ,f:function(a){this.kL(d.v(a))}},ImageTop:{a:p.WJ,f:function(a){this.lL(d.v(a))}},ImageWidth:{a:p.IH,f:function(a){this.SD(d.v(a))}},ImageHeight:{a:p.Rt,
f:function(a){this.hs(d.v(a))}},ImageAlignment:{a:function(){return d.sa(this.nA(),a.ce.u)},f:function(b){this.kz(d.qa(b,a.ce.u))}},DataClass:{a:p.hb,f:p.Qg},MarginLeft:{a:p.Re,f:function(a){this.$d(d.v(a))}},MarginTop:{a:p.Ie,f:function(a){this.ud(d.v(a))}},MarginBottom:{a:p.$f,f:function(a){this.Be(d.v(a))}},MarginRight:{a:p.Sf,f:function(a){this.Fd(d.v(a))}}}})});
