window.LANSA.addSrc("tile",function(d,c,a,b,p){d.Db("PRIM_UDC");c.vhb=function(){u.H.call(this);this.Mb=b.Ig(10,10,280,120);this.Qi=new c.qYb(this);this.Xi=new c.fYb(this);this.xo(this.Xi);this.GI(!0);this.lX(!0);this.Jqa(a.ho.yx);this.Zf().upb();var d=new c.BBa,d=new c.rYb(this,d);this.ZLa(d)};var u=c.q(c.vhb,c.qoa);u.R=function(){u.j.R.call(this);b.$(this.Xi);this.Xi=null};u.mab=function(){return this.Xi};u.QQb=function(){return this.Iu()};u.lN=function(){return this.Xi.lN()};u.fL=function(b){this.Xi.lN()!=
b&&(this.Xi.fL(b),this.ea(a.g.h))};u.bza=function(){return this.Xi.bza()};u.GUa=function(b){this.Xi.bza()!=b&&(this.Xi.GUa(b),this.ea(a.g.h))};u.O5=function(){return this.Xi.O5()};u.eqb=function(b){this.Xi.O5()!=b&&(this.Xi.eqb(b),this.ea(a.g.h))};u.Xya=function(){return this.Xi.Xya()};u.xUa=function(b){this.Xi.Xya()!=b&&(this.Xi.xUa(b),this.k(a.g.h))};u.ZZ=function(){return this.Xi.ZZ()};u.yUa=function(b){this.Xi.ZZ()!=b&&(this.Xi.yUa(b),this.k(a.g.h))};u.$Z=function(){return this.Xi.$Z()};u.zUa=
function(b){this.Xi.$Z()!=b&&(this.Xi.zUa(b),this.k(a.g.h))};u.Dma=function(){return this.Xi.Dma()};u.lVa=function(b){this.Xi.Dma()!=b&&(this.Xi.lVa(b),this.k(a.g.h))};u.Ema=function(){return this.Xi.Ema()};u.mVa=function(b){this.Xi.Ema()!=b&&(this.Xi.mVa(b),this.k(a.g.h))};u.Mza=function(){return this.Xi.Mza()};u.nVa=function(b){this.Xi.Mza()!=b&&(this.Xi.nVa(b),this.ea(a.g.h))};u.Nza=function(){return this.Xi.Nza()};u.oVa=function(b){this.Xi.Nza()!=b&&(this.Xi.oVa(b),this.ea(a.g.h))};u.mza=function(){return this.Xi.mza()};
u.QUa=function(b){this.Xi.mza()!=b&&(this.Xi.QUa(b),this.ea(a.g.h))};u.jza=function(){return this.Xi.jza()};u.LUa=function(b){this.Xi.jza()!=b&&(this.Xi.LUa(b),this.ea(a.g.h))};u.lza=function(){return this.Xi.lza()};u.PUa=function(b){this.Xi.lza()!=b&&(this.Xi.PUa(b),this.ea(a.g.h))};u.iza=function(){return this.Xi.iza()};u.KUa=function(b){this.Xi.iza()!=b&&(this.Xi.KUa(b),this.ea(a.g.h))};u.OV=function(){return"PRIM_TILE<"+this.kN()+">"};u.xLc=function(){return!0};u.CSb=function(){return!0};u.HZ=
function(b){0==(this.qp()&a.Nn.Su)&&this.wj(!0);if(this.wA(a.w.uK)&&(this.ed(b),!this.od())){var c=d.Yb();c.bc("ITEM",b);this.Ca(a.w.uK,c);c.Bc()}};u.IZ=function(b){0==(this.qp()&a.Nn.Su)&&this.wj(!0);if(this.wA(a.w.wK)&&(this.ed(b),!this.od())){var c=d.Yb();c.bc("ITEM",b);this.Ca(a.w.wK,c);c.Bc()}};u.Z4=function(b){0==(this.qp()&a.Nn.Su)&&this.wj(!0);if(this.wA(a.w.vK)&&(this.ed(b),!this.od())){var c=d.Yb();c.bc("ITEM",b);this.Ca(a.w.vK,c);c.Bc()}};u.CB=function(b,c){this.ed(b);c=b.CB(c);if(!c&&
!this.od()){var g=d.Yb();g.bc("ITEM",b);g.Jf("CONTINUE",!0);this.Ca(a.w.tK,g);c=!g.zg("CONTINUE");g.Bc()}return c};u.rba=function(b,c){this.ed(b);if(!c&&!this.od()){var g=d.Yb();g.bc("ITEM",b);g.Jf("CONTINUE",!0);this.Ca(a.w.l6,g);c=!g.zg("CONTINUE");g.Bc()}return c};u.XE=function(b){var c=this.wA(a.w.FD);c&&this.ed(b);b.XE();c&&!this.od()&&(c=d.Yb(),c.bc("ITEM",b),this.Ca(a.w.FD,c),c.Bc())};u.VE=function(b){0==(this.qp()&a.Nn.Su)&&this.wj(!0);this.ed(b);b.VE();if(!this.od()){var c=d.Yb();c.bc("ITEM",
b);this.Ca(a.w.DF,c);c.Bc()}};u.WE=function(b){0==(this.qp()&a.Nn.Su)&&this.wj(!0);this.ed(b);b.WE();if(!this.od()){var c=d.Yb();c.bc("ITEM",b);this.Ca(a.w.NN,c);c.Bc()}};u.zR=function(b){0==(this.qp()&a.Nn.Xda)&&this.wj(!0);this.ed(b);b.zR();if(!this.od()){var c=d.Yb();c.bc("ITEM",b);this.Ca(a.w.FW,c);c.Bc()}};u.AR=function(b){0==(this.qp()&a.Nn.Xda)&&this.wj(!0);this.ed(b);b.AR();if(!this.od()){var c=d.Yb();c.bc("ITEM",b);this.Ca(a.w.GW,c);c.Bc()}};u.Kh=function(a){var b=null;return b=this.Qi.Wg(a,
!0,-1,!1)};u.Wg=function(){this.Qi.Wg(this.kN(),!0,-1,!0)};u.Qh=function(a){return this.Qi.Qh(!1,a)?"OK":"NR"};u.kp=function(){return this.Qi.TMa()};u.Dk=function(){this.Qi.Dk()};u.Fn=function(a){this.Qi.Fn(a==p?!0:!1,a)};u.Wl=function(){this.Qi.Wl()};u.ro=function(a,b,c){return this.Qi.ro(a,b,c)};u.ir=function(a){this.Dk();for(var b=0;b<a;b++)this.Wg()};u.Rpa=function(a){this.HZ(a)};u.Tpa=function(a){this.IZ(a)};u.Spa=function(a){this.Z4(a)};u.Mpa=function(a,b){return this.CB(a,b)};u.Npa=function(a,
b){return this.rba(a,b)};u.Fea=function(a){this.XE(a)};u.Eea=function(a){this.VE(a)};u.Qpa=function(a){this.WE(a)};u.Opa=function(a){this.zR(a)};u.iDa=function(a){this.AR(a)};u.F0=function(a){u.j.F0.call(this,a);a.VT.ud(a.k7());a.VT.Be(a.kqa());a.VT.$d(a.JTa());a.VT.Fd(a.Nnb())};u.YDa=function(b){null!=b&&null!=b.ac&&(this.iYa(b.ac,a.rz.k2),this.Fna(b.ac,a.zF.c6))};u.ve=function(b){""==b[1]&&(b[1]=a.KWb);u.j.ve.call(this,b)};d.xd(c.vhb,"PRIM_TILE",{sO:a.Fw.fYa,KE:"PRIM_CPST",Pa:{CurrentItem:{a:u.Ld},
SelectionStyle:{a:function(){return d.sa(this.St(),a.Th.sec)},f:function(b){this.bqb(d.qa(b,a.Th.sec))}},Direction:{a:function(){return d.sa(this.lN(),a.Lq.u)},f:function(b){this.fL(d.qa(b,a.Lq.u))}},ItemsPerDivision:{a:u.bza,f:function(a){this.GUa(d.v(a))}},ShowPartialItem:{a:u.O5,f:function(a){this.eqb(d.wa(a))}},Spacing:{a:u.Mza,f:function(a){this.nVa(d.v(a))}},SpacingItems:{a:u.Nza,f:function(a){this.oVa(d.v(a))}},FlowOperation:{a:function(){return d.sa(this.Xya(),a.Fg.u)},f:function(b){this.xUa(d.qa(b,
a.Fg.u))}},FlowOperationVer:{a:function(){return d.sa(this.$Z(),a.Fg.u)},f:function(b){this.zUa(d.qa(b,a.Fg.u))}},FlowOperationHor:{a:function(){return d.sa(this.ZZ(),a.Fg.u)},f:function(b){this.yUa(d.qa(b,a.Fg.u))}},SizingRuleVer:{a:function(){return d.sa(this.Ema(),a.mG.u)},f:function(b){this.mVa(d.qa(b,a.mG.u))}},SizingRuleHor:{a:function(){return d.sa(this.Dma(),a.mG.u)},f:function(b){this.lVa(d.qa(b,a.mG.u))}},MinRows:{a:u.mza,f:function(a){this.QUa(d.v(a))}},MaxRows:{a:u.jza,f:function(a){this.LUa(d.v(a))}},
MinColumns:{a:u.lza,f:function(a){this.PUa(d.v(a))}},MaxColumns:{a:u.iza,f:function(a){this.KUa(d.v(a))}},FocusItem:{a:u.Vc}},qc:{Add:u.Kh,Sort:u.b8,FindItem:u.Kd,DeleteAll:u.RE,FindReference:u.yR},bz:{Wg:u.Wg,Qh:function(a){return this.Qh(d.v(a)-1)},ir:u.ir,Dk:u.Dk,kp:u.kp,Fn:function(a){return this.Fn(a?d.v(a)-1:p)},Wl:u.Wl,ro:u.ro,Zs:u.Zs}});c.rYb=function(a,b){t.H.call(this,a,b)};var t=c.q(c.rYb,c.DBa);t.R=function(){t.j.R.call(this)};t.vCd=function(){return this.fr.za()};t.Eaa=function(a,b){var c=
null,f=null,h=null,k=null;null!=a&&(f=k=d.qd(a),null!=f&&(f.Gb(!1),h=f,null!=h&&(c=d.qd("PRIM_TILE","TileItem"),c.Ha())));b[0]=k;b[1]=c;b[2]=f;b[3]=h};t.YQ=function(a,b,c,d){this.Eaa(a,b);null!=b[1]&&this.Ox(b[1],b[2],d)};t.bqa=function(a){return a};c.qYb=function(a){r.H.call(this,a)};var r=c.q(c.qYb,c.CBa);r.Wg=function(b,c,d,f){var h=this.za(),k=null,k=null,k=[];c?h.QQb().YQ(b,k,-1,f):h.QQb().YQ(b,k,d,f);k=k[1];h.PQ(!0);h.yd(a.yb.Ge);return k};c.pYb=function(){n.H.call(this);this.tzb=a.LWb};var n=
c.q(c.pYb,c.roa);n.R=function(){n.j.R.call(this)};n.Oa=function(a){this.K()!=a&&this.Ag()&&(null==a||a.Ag()&&a.za()==this.za())&&this!=a&&(a=null!=a?a:null,this.K()!=a&&this.YXa(a,-1))};n.CB=function(c){if(!this.od()){var f=d.Yb();f.bc("ITEM",this);f.Jf("CONTINUE",!0);this.Ca(a.w.tK,f);c=!f.zg("CONTINUE");f.Bc()}f=this.Tr();null!=f&&b.Rl(f,this,"ONITEMCLICK");return c};n.XE=function(){if(!this.od()){var c=d.Yb();c.bc("ITEM",this);this.Ca(a.w.FD,c);c.Bc()}c=this.Tr();null!=c&&b.Rl(c,this,"ONITEMREALIZING")};
n.VE=function(){if(!this.od()){var c=d.Yb();c.bc("ITEM",this);this.Ca(a.w.DF,c);c.Bc()}c=this.Tr();null!=c&&(b.Rl(c,this,"ONITEMGOTFOCUS"),null!=this.ac&&this.ac.ca.Lqa(!0))};n.WE=function(){if(!this.od()){var c=d.Yb();c.bc("ITEM",this);this.Ca(a.w.NN,c);c.Bc()}c=this.Tr();null!=c&&(b.Rl(c,this,"ONITEMLOSTFOCUS"),null!=this.ac&&this.ac.ca.Lqa(!1))};n.zR=function(){if(!this.od()){var c=d.Yb();c.bc("ITEM",this);this.Ca(a.w.FW,c);c.Bc()}c=this.Tr();null!=c&&(b.Rl(c,this,"ONITEMGOTSELECTION"),null!=this.ac&&
this.ac.ca.Xu(!0))};n.AR=function(){if(!this.od()){var c=d.Yb();c.bc("ITEM",this);this.Ca(a.w.GW,c);c.Bc()}c=this.Tr();null!=c&&(b.Rl(c,this,"ONITEMLOSTSELECTION"),null!=this.ac&&this.ac.ca.Xu(!1))};d.mb(c.pYb,"PRIM_TILE","TileItem",{Pa:{Design:{a:n.ZMa},Tile:{a:n.za},Focus:{a:n.Af,f:n.ef},Selected:{a:n.tj,f:function(a){this.Xu(d.wa(a))}},Expanded:{a:n.Vj,f:function(a){this.BI(d.wa(a))}},Position:{a:n.Dca},Entry:{a:n.Qh},Visible:{a:n.sb,f:function(a){this.Gb(d.wa(a))}},RelatedReference:{a:n.n_,f:n.aT},
MarginTop:{a:n.Ie,f:function(a){this.ud(d.v(a))}},MarginBottom:{a:n.$f,f:function(a){this.Be(d.v(a))}},MarginLeft:{a:n.Re,f:function(a){this.$d(d.v(a))}},MarginRight:{a:n.Sf,f:function(a){this.Fd(d.v(a))}},Style:{a:n.Hg,f:n.vb},ParentItem:{a:n.K,f:n.Oa},MouseOverStyle:{a:n.In,f:n.Pn},SelectedStyle:{a:n.tA,f:n.FI},FocusedStyle:{a:n.Py,f:n.QD},SelectedInactiveStyle:{a:n.sD,f:n.KO},FocusedInactiveStyle:{a:n.mD,f:n.yO},Styles:{a:n.Lk},MouseOverStyles:{a:n.Nw},SelectedStyles:{a:n.fW},FocusedStyles:{a:n.s5},
SelectedInactiveStyles:{a:n.M5},FocusedInactiveStyles:{a:n.q5},ItemCount:{a:n.zc},Items:{a:n.oA},ParentItems:{a:n.Yab}},qc:{Add:n.Kh,Expand:n.DV,Delete:n.Pr,Collapse:n.N4,DeleteAll:n.RE}});c.oYb=function(){k.H.call(this)};var k=c.q(c.oYb,c.vhb);k.ipa=function(a){a.V5b(this.K())};k.Tda=function(a){a.hpa(this.K());k.j.Tda.call(this,a)};c.nYb=function(){h.H.call(this);this.Mb=b.Ig(10,10,280,400);this.ml=null;this.Elc=!1;this.jc=this.ml=new c.oYb;this.ml.Ha();this.ml.tb(this);this.ml.udcDesign="PRIM_TILE_DESIGN";
this.ml.Le(!1);this.ml.ta(this,a.w.qh,this.Wwc);this.ml.ta(this,a.w.gX,this.gxc);this.ml.ta(this,a.w.uK,this.cxc);this.ml.ta(this,a.w.wK,this.exc);this.ml.ta(this,a.w.vK,this.dxc);this.ml.ta(this,a.w.tK,this.Xwc);this.ml.ta(this,a.w.l6,this.Ywc);this.ml.ta(this,a.w.FD,this.fxc);this.ml.ta(this,a.w.DF,this.Zwc);this.ml.ta(this,a.w.NN,this.axc);this.ml.ta(this,a.w.FW,this.$wc);this.ml.ta(this,a.w.GW,this.bxc)};var h=c.q(c.nYb,c.as);h.R=function(){h.j.R.call(this)};h.Ld=function(){return this.ml.Ld()};
h.Vc=function(){return this.ml.Vc()};h.oA=function(){return this.ml.oA()};b.fId=function(a){var b=null;a&&a.ac&&a.ac instanceof c.whb&&(b=a.ac);return b};h.Kwa=function(a){a.kb(new c.ga(a.Qd(),a.ie(),this.VGa,this.Gt))};h.$x=function(a,b){h.j.$x.call(this,a,b);this.Elc!=this.ml.dda()&&(this.Elc=this.ml.dda(),this.ob())};h.hf=function(a){h.j.hf.call(this,a)};h.Zs=function(){return this.ml.Zs()};h.Wg=function(){var a=this.ml.Wg();this.Kwa(a.ac)};h.Qh=function(a){return this.ml.Qh(a)};h.kp=function(){return this.ml.kp()};
h.Dk=function(){this.ml.Dk()};h.Fn=function(a){this.ml.Fn(a)};h.Wl=function(){this.ml.Wl()};h.ro=function(a,b,d){var f=this.ml;if(f)for(var h=0;h<f.Bq.length;h++){var k=f.CF(h);if(k&&(k=k.ac)){for(var n={},r=null,t=this.Cm,p=0;p<t.length&&null!=(r=t[p]);p++){var u=null,J=null,G=null,R=null;r instanceof c.Noa?u=r:r instanceof c.Loa?J=r:r instanceof c.Poa||r instanceof c.Koa||r instanceof c.Moa||r instanceof c.Ooa||(r instanceof c.Joa?G=r:r instanceof c.Qoa&&(R=r));if(J||u||G||R)J=k.wc[r],u=r.nf,J&&
(J=J.Nc.fc().Da(),u&&(u=u.lA())&&(n[u.Ah()]=J))}if(a(n))return a=f.MDa(),null!=b&&b.set(h+1),a&&(d&&a.Qh(!1,h),a.qy=f.CF(h)),"OK"}}return"NR"};h.ir=function(a){this.ml.ir(a)};h.Wwc=function(b,c){this.Ca(a.w.qh,c)};h.gxc=function(b,c){this.Ca(a.w.gX,c)};h.cxc=function(b,c){this.Ca(a.w.uK,c)};h.exc=function(b,c){this.Ca(a.w.wK,c)};h.dxc=function(b,c){this.Ca(a.w.vK,c)};h.Xwc=function(b,c){this.Ca(a.w.tK,c)};h.Ywc=function(b,c){this.Ca(a.w.l6,c)};h.fxc=function(b,c){this.Ca(a.w.FD,c)};h.Zwc=function(b,
c){this.Ca(a.w.DF,c)};h.axc=function(b,c){this.Ca(a.w.NN,c)};h.$wc=function(b,c){this.Ca(a.w.FW,c)};h.bxc=function(b,c){this.Ca(a.w.GW,c)};d.mb(c.nYb,"PRIM_MD","Tile",{KE:"PRIM_CPST",Pa:{CurrentItem:{a:h.Ld},FocusItem:{a:h.Vc},Items:{a:h.oA},RowHeight:{a:h.K5,f:function(a){this.pL(d.v(a))}},ColWidth:{a:h.wCc,f:function(a){this.o4c(d.v(a))}},CardType:{a:function(){return d.sa(this.Ny(),a.ol.u)},f:function(b){this.w7(d.qa(b,a.ol.u))}},LogicalHeight:{a:function(){return this.ml.hPb()}},LogicalWidth:{a:function(){return this.ml.Oab()}},
ViewportHeight:{a:function(){return this.ml.bRb()}},ViewportWidth:{a:function(){return this.ml.cRb()}},VerticalScrollPos:{a:function(){return this.ml.em},f:function(a){this.ml.lG(d.v(a))}},HorizontalScrollPos:{a:function(){return this.ml.cm},f:function(a){this.ml.lEa(d.v(a))}}},qc:{DeleteAll:h.RE,FindReference:h.yR},bz:{Wg:h.Wg,Qh:function(a){return this.Qh(d.v(a)-1)},ir:h.ir,Dk:h.Dk,kp:h.kp,Fn:function(a){return this.Fn(a?d.v(a)-1:p)},Wl:h.Wl,ro:h.ro,Zs:h.Zs}});c.whb=function(){f.H.call(this);this.Ipb();
this.Rb(a.Qgb)};var f=c.q(c.whb,c.t6);f.R=function(){f.j.R.call(this)};f.wCd=function(){return this.uv};f.Owa=function(a){f.j.Owa.call(this,a)};f.ve=function(a){""==a[0]&&(a[0]="");f.j.ve.call(this,a)};d.xd(c.whb,"PRIM_TILE_DESIGN",{Pa:{},qc:{}})},{rp:["PRIM_UDC"]});
