window.LANSA.addSrc("video",function(d,c,a,b,p){var u,t;u={ALL:0,METADATA:1,NONE:2};t={auto:0,metadata:1,none:2};c.MQa=function(a){r.H.call(this);this.f3=this.yt="";this.sha=a};var r=c.q(c.MQa,c.Hd);r.R=function(){r.j.R.call(this)};r.Yg=function(){return this.yt};r.$s=function(a){this.yt=a};r.YZ=function(){return this.f3==p?"":this.f3};r.W0=function(a){this.f3=a};r.Pr=function(){for(var a=0;a<this.sha.zc();a++)this.sha.Vr(a)===this&&this.sha.fs(a)};d.mb(c.MQa,"PRIM_VDEO","File",{Pa:{FileName:{a:r.Yg,
f:function(a){this.$s(d.ja(a))}},FileExtension:{a:r.YZ,f:function(a){this.W0(d.ja(a))}}},qc:{Delete:r.Pr},Bg:{wg:"FileExtension"}});c.Bib=function(a){n.H.call(this);this.Tlc=a;this.cb=[]};var n=c.q(c.Bib,c.Hd);n.zc=function(){return this.cb.length};n.be=function(a){return this.Vr(a)};n.Vr=function(a){if(0>a||a>=this.cb.length)throw d.VF(a,this.cb.length);return this.cb[a]};n.Kh=function(a,b){var d=new c.MQa(this);d.$s(a);d.W0(b);this.cb.push(d);(d=this.Tlc.Sa())&&d.ts()};n.Tya=function(){0==this.zc()&&
this.cb.push(new c.MQa(this));return this.Vr(0)};n.nk=function(){this.cb=[];var a=this.Tlc.Sa();a&&a.ts()};n.fs=function(a){if(null==this.Vr(a))throw d.VF(a,this.cb.length);this.cb.splice(a,1)};n.SYc=function(a){for(var b=!1,c=0;c<this.zc()&&!(b=this.Vr(c).Yg()==a);c++);b&&this.fs(c)};d.mb(c.Bib,"PRIM_VDEO","Files",{Pa:{Item:{a:function(a){return this.Vr(d.v(a)-1)}}},qc:{Add:n.Kh,RemoveAll:n.nk,Remove:function(a){return this.fs(d.v(a)-1)}},Oq:{kq:function(a){return this.Vr(d.v(a)-1)},Rw:function(){return this.zc()}},
Bg:{wg:"Item"}});c.b4b=function(){k.H.call(this);this.G2=0;this.s2=this.Q3=!0;this.BU=1;this.lx=new c.Bib(this);this.ci=-1;this.fU=this.Aia=this.Cia=!1;this.TC=50};var k=c.q(c.b4b,c.Wt);k.hh=function(){return c.v5b};k.R=function(){k.j.R.call(this)};k.Yg=function(){return 0<this.lx.zc()?this.lx.Vr(0).Yg():""};k.$s=function(b){this.lx.nk();var c=this.lx.Tya();c.Yg()!=b&&(c.$s(b),(b=this.Sa())&&b.ts(),this.k(a.g.h))};k.YZ=function(){return 0<this.lx.zc()?this.lx.Vr(0).YZ():""};k.W0=function(b){var c=
this.lx.Tya();c.YZ()!=b&&(c.W0(b),(b=this.Sa())&&b.ts(),this.k(a.g.h))};k.zEc=function(){return this.lx};k.Q$a=function(){return this.G2};k.Lob=function(b){this.G2!=b&&(this.G2=b,(b=this.Sa())&&b.ts(),this.k(a.g.h))};k.xab=function(){return this.fU};k.vbb=function(){return this.Q3};k.cqb=function(b){this.Q3!=b&&(this.Q3=b,(b=this.Sa())&&b.ts(),this.k(a.g.h))};k.l$a=function(){return this.s2};k.nob=function(b){this.s2!=b&&(this.s2=b,(b=this.Sa())&&b.ts(),this.k(a.g.h))};k.l5=function(){return this.ci};
k.yab=function(){return this.Cia};k.wab=function(){return this.Aia};k.$bb=function(){return this.TC};k.REa=function(c){c=b.mf(c,0,100);this.TC!=c&&(this.TC=c,this.fU=0==this.TC,(c=this.Sa())&&c.ts(),this.k(a.g.h))};k.lHc=function(){return this.BU};k.Tpb=function(b){this.BU!=b&&(this.BU=b,(b=this.Sa())&&b.ts(),this.k(a.g.h))};k.Play=function(){this.Sa()&&this.Sa().Play()};k.vh=function(){this.Sa()&&this.Sa().vh()};k.xlb=function(){this.REa(0)};k.RAc=function(){if(this.Sa()){var a=this.Sa().G;a.currentTime=
Math.min(a.duration,a.currentTime+5)}};k.QAc=function(){if(this.Sa()){var a=this.Sa().G;0<a.currentTime&&(a.currentTime-=5)}};d.xd(c.b4b,"PRIM_VDEO",{Pa:{FileName:{a:k.Yg,f:function(a){this.$s(d.ja(a))}},CycleToStart:{a:k.Q$a,f:function(a){this.Lob(d.wa(a))}},ShowControls:{a:k.vbb,f:function(a){this.cqb(d.wa(a))}},Autoplay:{a:k.l$a,f:function(a){this.nob(d.wa(a))}},Preload:{a:function(){return d.sa(this.BU,u)},f:function(a){this.Tpb(d.qa(a,u))}},Duration:{a:k.l5},IsMuted:{a:k.xab},IsPlaying:{a:k.yab},
IsEnded:{a:k.wab},Volume:{a:k.$bb,f:function(a){this.REa(d.v(a))}}},qc:{Play:k.Play,Stop:k.vh,Mute:k.xlb,FrameForward:k.RAc,FrameBackward:k.QAc}});c.v5b=function(a){h.H.call(this,a)};var h=c.q(c.v5b,c.on);h.df=function(b,c){this.G=document.createElement("video");this.G.setAttribute("LANSAHandle",this.kc);this.G.style.position="absolute";this.G.style.overflow="hidden";this.G.style.whiteSpace="nowrap";this.ts();var d=this.G,g=this;d.addEventListener("loadedmetadata",function(){g.na.ci=d.duration;g.na.Ca(a.w.uXb)},
!1);d.addEventListener("loadeddata",function(){g.na.Ca(a.w.tXb)},!1);d.addEventListener("play",function(){g.na.Cia=!0;g.na.Aia=!1;g.na.Ca(a.w.y7b)},!1);d.addEventListener("pause",function(){g.na.Cia=!1;g.na.Ca(a.w.adc)},!1);d.addEventListener("ended",function(){g.G.pause();g.G.paused=!0;g.na.Aia=!0;g.na.Ca(a.w.Jw)},!1);d.addEventListener("volumechange",function(){d.muted||0==d.volume?(g.G.muted=!0,g.na.fU=!0,g.na.TC=0,g.na.Ca(a.w.u6b)):(g.na.fU=!1,g.na.TC=Math.round(100*d.volume))},!1);return h.j.df.call(this,
b,c)};h.ts=function(){this.Dqa("controls",this.na.Q3);this.Dqa("autoplay",this.na.s2);this.Dqa("loop",this.na.G2);this.G.setAttribute("preload",d.sa(this.na.BU,t));this.G.volume=0<this.na.TC?this.na.TC/100:0;this.G.muted=this.na.fU;this.mvb()};h.mvb=function(){this.qnb();var a=this.na.lx.zc();if(0!=a)for(var b=0;b<a;b++){var c=this.na.lx.Vr(b);this.Tmc(this.G,c.yt,c.f3)}};h.Tmc=function(a,b,c){var d=document.createElement("source");d.src=b;c&&(d.type="video/"+c);a.appendChild(d)};h.qnb=function(){var a=
this.G;if(a&&(a=a.childNodes)){var b,c,d=[];for(c=0;c<a.length;c++)b=a[c],"SOURCE"==b.nodeName&&d.push(b);for(c=0;c<d.length;c++)b=d[c],b.parentNode.removeChild(b)}};h.lO=function(){return!1};h.MRa=function(){};h.Play=function(){this.G.play!==p&&this.G.play()};h.vh=function(){this.G.pause!==p&&this.G.pause()}});
