window.LANSA.addSrc("caro",function(d,c,a,b,p){d.Db("PRIM_UDC");d.Db("PRIM_IMAG");a.B8={F6b:1,EUc:0,E6b:1};a.B8.u={DEFAULT:a.B8.F6b,NONE:a.B8.EUc,BUTTONS:a.B8.E6b};a.KA={PE:0,wsc:0,Ynd:1,Xnd:2,Wnd:3,UM:4};a.KA.u={PAGE:a.KA.UM};a.aGa={a7b:0,pVc:0,qVc:1};a.aGa.u={DEFAULT:a.aGa.a7b,HORIZONTAL:a.aGa.pVc,VERTICAL:a.aGa.qVc};a.bGa={fec:0,Mfd:0,Nfd:1};a.bGa.u={DEFAULT:a.bGa.fec,ANTICLOCKWISE:a.bGa.Mfd,CLOCKWISE:a.bGa.Nfd};c.CXb=function(a){u.H.call(this);this.AG=a;this.x2=new c.ga;this.Q2=1};var u=c.q(c.CXb,
c.Vx);u.R=function(){u.j.R.call(this)};u.hf=function(b,c){u.j.hf.call(this,b,c);this.AG.Kx()==a.ho.yx&&this.AG.Zf().Sh()};u.Msa=function(b,c){u.j.Msa.call(this,b,c);if(this.AG.Kx()==a.ho.yx){var d=[];d[0]=this.Q2;d[1]=this.x2;this.AG.Ppa(b,c,d);this.Q2=d[0];this.x2=d[1]}};u.ZC=function(b,c,d){c=[];this.AG.Kx()==a.ho.yx&&this.AG.Zf().UAa()?(this.x2=this.AG.Kya(),this.Q2=1,c=this.AG.ZC(c)):c=u.j.ZC.call(this,b,c,d);return c};c.aYb=function(a){t.H.call(this);this.AG=a;this.n3a=!1;this.cwa=0};var t=c.q(c.aYb,
c.uhb);t.LFd=function(){return this.n3a};t.nDa=function(a,b,c){t.j.nDa.call(this,a,b,c);this.cwa=this.Qd()};t.Kea=function(a){var b=this.AG.Qa()/this.AG.m$;a.Cl(this.cwa!=this.Qd());t.j.Kea.call(this,a);0<b&&this.cwa!=this.Qd()&&(this.cwa>this.Qd()?(a=this.cwa-b*this.AG.l$,a<this.Qd()||(a=this.Qd()-(b+this.Qd()%b))):(a=this.cwa+b*this.AG.l$,a>this.Qd()||(a=this.Qd()-(b+this.Qd()%b),a+=b)),this.Fb(a,0,500));this.AG.ob()};t.$pa=function(a,c,d,g,h,k,n,r,p){if(0!=a){var u=b.mf(this.Qd()+a,-(this.Qa()-
this.AG.Qa()),0);this.n3a=!0;this.Va(u);this.n3a=!1;p[0]=!0}t.j.$pa.call(this,a,c,d,g,h,k,n,r,p)};c.BXb=function(){r.H.call(this);this.Mb=b.Ig(10,10,400,400);this.Qi=new c.EXb(this);this.pIa=a.B8.F6b;this.SGa=a.KA.PE;this.hJ=a.aGa.a7b;this.X9=this.uzb=0;this.szb=75;this.oyb=50;this.nyb=20;this.ci=500;this.iCb=a.bGa.fec;this.m$=3;this.l$=1;var d=this.TP=this.SP=this.wU=this.xU=this.ov=this.Yia=this.Zia=this.D3=this.xh=null,d=d=null;this.xh=new c.Vx;d=b.Ro(this.xh);d.tk(a.Mf.qz);d.lc(1);d=b.nn(this.xh);
d.tk(a.Mf.qz);d.Wb(1);this.D3=new c.CXb(this);this.Zia=b.Ro(this.D3);this.Zia.tk(a.Mf.qz);this.Zia.lc(1);this.Yia=b.nn(this.D3);this.Yia.tk(a.Mf.qz);this.Yia.Wb(1);this.Zia.wr(this.D3);this.Yia.wr(this.D3);this.ov=new c.aYb(this);this.ov.kb(new c.ga);this.ov.uc=this;this.ov.xo(this.D3);this.ov.GI(!1);this.ov.lX(!1);this.ov.Le(!1);this.ov.Wo(!1);this.ov.ta(this,a.w.gX,this.w7a);this.ov.ta(this,a.w.N3a,this.Ruc);this.ov.wcc(a.ly.Ktb);this.xU=new c.Xt;this.xU.kb(new c.ga(0,0,20,90));this.xU.Ti(a.$b.oqc);
this.xU.ta(this,a.w.Vb,this.Yvc);this.wU=new c.Xt;this.wU.kb(new c.ga(0,0,20,90));this.wU.Ti(a.$b.pqc);this.wU.ta(this,a.w.Vb,this.Xvc);this.SP=new c.Xt;this.SP.kb(new c.ga(0,0,20,20));this.SP.Ti(a.$b.mqc);this.SP.cg(0);this.SP.ta(this,a.w.Vb,this.Vvc);this.TP=new c.Xt;this.TP.kb(new c.ga(0,0,20,20));this.TP.Ti(a.$b.nqc);this.TP.cg(0);this.TP.ta(this,a.w.Vb,this.Wvc);b.U().BJa(this.wU);b.U().CJa(this.wU);b.U().BJa(this.xU);b.U().CJa(this.xU);b.U().BJa(this.SP);b.U().CJa(this.SP);b.U().BJa(this.TP);
b.U().CJa(this.TP);d=b.pc(this.xh,this.xU,this.xh.hc(0),this.xh.oc(0),1,1);d.rb(a.ma.bl);d.Bb(a.ka.Xd);d=b.pc(this.xh,this.wU,this.xh.hc(0),this.xh.oc(0),1,1);d.rb(a.ma.wu);d.Bb(a.ka.Xd);d=b.pc(this.xh,this.SP,this.xh.hc(0),this.xh.oc(0),1,1);d.rb(a.ma.OQ);d.Bb(a.ka.Xd);d=b.pc(this.xh,this.TP,this.xh.hc(0),this.xh.oc(0),1,1);d.rb(a.ma.uJ);d.Bb(a.ka.Xd);this.Jqa(a.ho.Maa);d=new c.BBa;d=new c.FXb(this,d);this.ZLa(d)};var r=c.q(c.BXb,c.qoa);r.nb=function(){b.$(this.ov);b.$(this.xU);b.$(this.wU);b.$(this.SP);
b.$(this.TP);r.j.nb.call(this)};r.R=function(){b.$(this.D3);this.D3=null;b.$(this.Zia);this.Zia=null;b.$(this.Yia);this.Yia=null;r.j.R.call(this)};r.gr=function(){return this.D3};r.Kx=function(){var b=a.ho.Maa;switch(this.XR()){case a.KA.UM:b=a.ho.yx;break;default:b=this.YMa()}return b};r.Zf=function(){var b=null;switch(this.XR()){case a.KA.UM:b=this.ov;break;default:b=r.j.Zf.call(this)}return b};r.dma=function(){var b=null;switch(this.XR()){case a.KA.UM:b=-this.ov.Qd();break;default:b=r.j.dma.call(this)}return b};
r.f_=function(){var b=null;switch(this.XR()){case a.KA.UM:b=-this.ov.ie();break;default:b=r.j.f_.call(this)}return b};r.cHc=function(){return this.m$};r.C6c=function(b){b=Math.max(b,1);this.m$!=b&&(this.m$=b,this.pz(),this.ea(a.g.h))};r.bHc=function(){return this.l$};r.B6c=function(b){b=Math.max(b,1);this.l$!=b&&(this.l$=b,this.pz(),this.ea(a.g.h))};r.Jzd=function(){return this.pIa};r.XR=function(){var b=this.SGa;b==a.KA.wsc&&this.Ub()&&d.qa("LINEAR",a.KA.u);return b};r.Std=function(){return this.SGa};
r.Ix=function(){return this.hJ};r.wyd=function(){return this.uzb};r.syd=function(){return this.X9};r.uyd=function(){return this.szb};r.jwd=function(){return this.oyb};r.iwd=function(){return this.nyb};r.l5=function(){return this.ci};r.TCd=function(){return this.iCb};r.v6c=function(b){this.pIa!=b&&(this.pIa=b,this.ea(a.g.h))};r.Q3c=function(b){this.SGa!=b&&(this.SGa=b,this.Dh(),this.ea(a.g.h))};r.pX=function(b){this.hJ!=b&&(this.hJ=b,this.ea(a.g.h))};r.CQd=function(b){this.uzb!=b&&(this.uzb=b,this.ea(a.g.h))};
r.AQd=function(b){this.X9!=b&&(this.X9=b,this.ea(a.g.h))};r.BQd=function(c){c=b.mf(c,1,89);this.szb!=c&&(this.szb=c,this.ea(a.g.h))};r.bQd=function(b){this.oyb!=b&&(this.oyb=b,this.ea(a.g.h))};r.aQd=function(b){this.nyb!=b&&(this.nyb=b,this.ea(a.g.h))};r.CA=function(b){this.ci!=b&&(this.ci=b,this.ea(a.g.h))};r.bSd=function(b){this.iCb!=b&&(this.iCb=b,this.ea(a.g.h))};r.JNb=function(){return this.Iu()};r.Jca=function(){return b.gb()};r.OV=function(){return"PRIM_CARO<"+this.kN()+">"};r.HZ=function(b){0==
(this.qp()&a.Nn.Su)&&this.wj(!0);if(this.wA(a.w.uK)&&(this.ed(b),!this.od())){var c=d.Yb();c.bc("ITEM",b);this.Ca(a.w.uK,c);c.Bc()}};r.IZ=function(b){0==(this.qp()&a.Nn.Su)&&this.wj(!0);if(this.wA(a.w.wK)&&(this.ed(b),!this.od())){var c=d.Yb();c.bc("ITEM",b);this.Ca(a.w.wK,c);c.Bc()}};r.Z4=function(b){0==(this.qp()&a.Nn.Su)&&this.wj(!0);if(this.wA(a.w.vK)&&(this.ed(b),!this.od())){var c=d.Yb();c.bc("ITEM",b);this.Ca(a.w.vK,c);c.Bc()}};r.CB=function(b,c){this.ed(b);b.CB(c);if(!c&&!this.od()){var h=
d.Yb();h.bc("ITEM",b);h.Jf("CONTINUE",!0);this.Ca(a.w.tK,h);h.zg("CONTINUE");h.Bc()}};r.rba=function(b,c){this.ed(b);if(!c&&!this.od()){var h=d.Yb();h.bc("ITEM",b);h.Jf("CONTINUE",!0);this.Ca(a.w.l6,h);c=!h.zg("CONTINUE");h.Bc()}return c};r.XE=function(b){var c=this.wA(a.w.FD);c&&this.ed(b);b.XE();c&&!this.od()&&(c=d.Yb(),c.bc("ITEM",b),this.Ca(a.w.FD,c),c.Bc())};r.VE=function(b){0==(this.qp()&a.Nn.Su)&&this.wj(!0);this.ed(b);b.VE();if(!this.od()){var c=d.Yb();c.bc("ITEM",b);this.Ca(a.w.DF,c);c.Bc()}};
r.WE=function(b){0==(this.qp()&a.Nn.Su)&&this.wj(!0);this.ed(b);b.WE();if(!this.od()){var c=d.Yb();c.bc("ITEM",b);this.Ca(a.w.NN,c);c.Bc()}};r.YDa=function(b){null!=b&&null!=b.ac&&this.Zf().Fna(b.ac,a.zF.c6)};r.F0=function(b){if(this.gr())switch(this.XR()){case a.KA.UM:switch(this.pIa){case a.B8.E6b:this.xU.Oa(this),this.xU.Ud(1),this.wU.Oa(this),this.wU.Ud(2),this.SP.Oa(this),this.SP.Ud(3),this.TP.Oa(this),this.TP.Ud(4)}this.ov.Oa(this);this.ov.Ud(99);this.ov.z5c(this.Ve().aa()/this.l$);this.Ub()&&
this.Sh();this.xo(this.xh);b.Pw().uj(b.ac);b.Pw().Oa(this.gr());b.Pw().ud(b.k7());b.Pw().$d(b.JTa());b.Pw().Fd(b.Nnb());b.Pw().Be(0);b.Pw().Bb(a.ka.xj);b.Pw().Df(a.ya.qj);b.Pw().rb(a.ma.vJ);b.Pw().Am(this.Zia);b.Pw().Ul(this.Yia);break;default:this.ov.Oa(null),this.xU.Oa(null),this.wU.Oa(null),this.SP.Oa(null),this.TP.Oa(null),this.xo(null)}r.j.F0.call(this,b)};r.oUc=function(a){this.l6b(a)};r.pUc=function(a){this.m6b(a)};r.kUc=function(a){this.glb(a)};r.nUc=function(a){this.hlb(a)};r.mUc=function(a,
b){this.lUc(a-1,b)};r.l6b=function(c){switch(this.XR()){case a.KA.UM:if(this.Zf().Qd()==-(this.Zf().Qa()-this.Qa()))this.glb(c);else{var d=this.Qa()/this.m$,d=this.Zf().Qd()-d*this.l$,d=b.mf(d,-(this.Zf().Qa()-this.Qa()),0);c?this.Zf().Fb(d,0,1E3):this.Zf().Va(d)}}};r.m6b=function(c){switch(this.XR()){case a.KA.UM:if(0==this.Zf().Qd())this.hlb(c);else{var d=this.Qa()/this.m$,d=this.Zf().Qd()+d*this.l$,d=b.mf(d,-(this.Zf().Qa()-this.Qa()),0);c?this.Zf().Fb(d,0,1E3):this.Zf().Va(d)}}};r.glb=function(b){switch(this.XR()){case a.KA.UM:b?
this.Zf().Fb(0,0,1E3):this.Zf().Va(0)}};r.hlb=function(b){switch(this.XR()){case a.KA.UM:var c=-(this.Zf().Qa()-this.Qa());b?this.Zf().Fb(c,0,1E3):this.Zf().Va(c)}};r.lUc=function(c,d){switch(this.XR()){case a.KA.UM:c-=c%this.m$;var h=this.n6(c);h&&h.ac&&(h=-h.ac.Qd(),h=b.mf(h,-(this.Zf().Qa()-this.Qa()),0),d?this.Zf().Fb(h,0,1E3):this.Zf().Va(h))}};r.Rpa=function(a){this.HZ(a)};r.Tpa=function(a){this.IZ(a)};r.Spa=function(a){this.Z4(a)};r.Mpa=function(a,b){this.CB(a,b)};r.Npa=function(a,b){return this.rba(a,
b)};r.Fea=function(a){this.XE(a)};r.Eea=function(b){this.VE(b);this.ea(a.g.h)};r.Qpa=function(a){this.WE(a)};r.ED=function(b){var c=null;switch(this.XR()){case a.KA.UM:c=r.j.ED.call(this,b)}return c};r.hf=function(a){r.j.hf.call(this,a);if(!this.ov.n3a&&!this.ov.Vt()){var d=b.KF(this,null),h=d.Pb,g=null,k=a.aa()/this.m$,n=this.ov.Qd(),p=this.ED(new c.sd(Math.abs(n)+10,10));if(0<h.length){for(var t=0;t<h.length&&null!=(g=h[t]);t++)g.ac&&g.ac.Wb(k);g=-(k*h.length-a.Qa());0>n&&p&&(n=-(k*p.Hj()));this.ov.kb(new c.ga(b.mf(n,
g,0),0,k*h.length,a.ba()))}b.$(d)}};r.dj=function(){r.j.dj.call(this);this.yd(a.yb.FXa)};r.Kh=function(a){var b=null;return b=this.Qi.Wg(a,!0,-1,!1)};r.Wg=function(){this.Qi.Wg(this.kN(),!0,-1,!0)};r.Qh=function(a){return this.Qi.Qh(!1,a)?"OK":"NR"};r.kp=function(){return this.Qi.TMa()};r.Dk=function(){this.Qi.Dk()};r.Fn=function(a){this.Qi.Fn(a==p?!0:!1,a)};r.Wl=function(){this.Qi.Wl()};r.ro=function(a,b,c){return this.Qi.ro(a,b,c)};r.ir=function(a){this.Dk();for(var b=0;b<a;b++)this.Wg()};r.Yvc=
function(){this.m6b(!0)};r.Xvc=function(){this.l6b(!0)};r.Vvc=function(){this.glb(!0)};r.Wvc=function(){this.hlb(!0)};r.Ruc=function(){};r.w7a=function(a,b){this.O9a(b.qF("ORIENTATION"))};r.fA=r[a.Z.QN]=function(a){var b=this.Ri(a.Rc);b&&!b.Af()&&b.zB(!0,!1,!0);r.j.fA.call(this,a)};d.xd(c.BXb,"PRIM_CARO",{sO:a.Fw.fYa,KE:"PRIM_CPST",Pa:{CurrentItem:{a:r.Ld},FocusItem:{a:r.Vc},PageSize:{a:r.cHc,f:function(a){this.C6c(d.v(a))}},PageScroll:{a:r.bHc,f:function(a){this.B6c(d.v(a))}},CarouselStyle:{a:function(){return d.sa(this.SGa,
a.KA.u)},f:function(b){this.Q3c(d.qa(b,a.KA.u))}},NavigationStyle:{a:function(){return d.sa(this.pIa,a.B8.u)},f:function(b){this.v6c(d.qa(b,a.B8.u))}}},qc:{Add:r.Kh,Sort:r.b8,FindItem:r.Kd,DeleteAll:r.RE,FindReference:r.yR,NextItem:r.oUc,PrevItem:r.pUc,FirstItem:r.kUc,LastItem:r.nUc,MoveToItem:r.mUc},bz:{Wg:r.Wg,Qh:function(a){return this.Qh(d.v(a)-1)},ir:r.ir,Dk:r.Dk,kp:r.kp,Fn:function(a){return this.Fn(a?d.v(a)-1:p)},Wl:r.Wl,ro:r.ro,Zs:r.Zs}});c.FXb=function(a,b){n.H.call(this,a,b)};var n=c.q(c.FXb,
c.DBa);n.R=function(){n.j.R.call(this)};n.Rtd=function(){return this.fr.za()};n.Eaa=function(a,b){var c=null,g=null,h=null,k=null;null!=a&&(g=k=d.qd(a),null!=g&&(g.Gb(!1),h=g,null!=h&&(c=d.qd("PRIM_CARO","CarouselItem"),c.Ha())));b[0]=k;b[1]=c;b[2]=g;b[3]=h};n.YQ=function(a,b,c,d){this.Eaa(a,b);null!=b[1]&&this.Ox(b[1],b[2],d)};n.bqa=function(a){return a};c.EXb=function(a){k.H.call(this,a)};var k=c.q(c.EXb,c.CBa);k.Wg=function(a,b,c,d){var h=this.za(),k=null,k=[];b?h.JNb().YQ(a,k,-1,d):h.JNb().YQ(a,
k,c,d);return k=k[1]};c.DXb=function(){h.H.call(this)};var h=c.q(c.DXb,c.roa);h.R=function(){h.j.R.call(this)};h.Kh=function(a){var b=null,c=this.za();c&&(b=c.Kh(a),b.Oa(this));return b};h.CB=function(c){if(!this.od()){var e=d.Yb();e.bc("ITEM",this);e.Jf("CONTINUE",!0);this.Ca(a.w.tK,e);c=!e.zg("CONTINUE");e.Bc()}e=this.Tr();null!=e&&b.Rl(e,this,"ONITEMCLICK");return c};h.XE=function(){if(!this.od()){var c=d.Yb();c.bc("ITEM",this);this.Ca(a.w.FD,c);c.Bc()}c=this.Tr();null!=c&&b.Rl(c,this,"ONITEMREALIZING")};
h.VE=function(){if(!this.od()){var c=d.Yb();c.bc("ITEM",this);this.Ca(a.w.DF,c);c.Bc()}c=this.Tr();null!=c&&b.Rl(c,this,"ONITEMGOTFOCUS")};h.WE=function(){if(!this.od()){var c=d.Yb();c.bc("ITEM",this);this.Ca(a.w.NN,c);c.Bc()}c=this.Tr();null!=c&&b.Rl(c,this,"ONITEMLOSTFOCUS")};d.mb(c.DXb,"PRIM_CARO","CarouselItem",{Pa:{Design:{a:h.ZMa},Carousel:{a:h.za},Focus:{a:h.Af,f:h.ef},Position:{a:h.Dca},Entry:{a:h.Qh},Selected:{a:h.tj,f:function(a){this.Xu(d.wa(a))}},RelatedReference:{a:h.n_,f:h.aT},Visible:{a:h.sb,
f:function(a){this.Gb(d.wa(a))}}},qc:{Delete:h.Pr}})},{rp:["PRIM_UDC","PRIM_IMAG"]});
