window.LANSA.addSrc("labl",function(d,c,a,b){a.Svb={SVd:0,Wvb:16};a.Z_={vSc:1,Zgb:1,Ygb:2,nXb:240};a.Wgb={DRa:0,H5b:1};c.Yt=function(){p.H.call(this);this.Le(!1);this.Qqa(!1)};var p=c.q(c.Yt,c.Wt);p.xt=a.jp.iba;p.kU=a.Z_.vSc;p.Gia=a.Wgb.DRa;p.SC=0;p.EC=0;p.HC=0;p.wC=0;p.kl=null;p.CP=a.Pk.NS;p.Ka=null;p.tw=0;p.oY=a.Sd.HI;p.n3=new c.ZN(0,0,0,0);p.yM=new c.ZN(0,0,0,0);p.Xc=p.Xc|a.cc.rda|a.cc.cBa|a.cc.Zfb|a.cc.GF|a.cc.HW|a.cc.$fb|a.cc.FF;p.Kg=p.Kg|a.rh.doa|a.rh.sS|a.rh.T_;p.R=function(){this.kl&&(this.kl.Ba(this,
this.B7a),this.kl=null);p.j.R.call(this);this.pd(null)};p.hh=function(){return c.jkb};p.dC=function(c){this.kl!=c&&(this.kl&&this.kl.Ba(this,this.B7a),this.kl=c,null==this.kl?this.Qqa(!1):(this.Qqa(!0),this.kl.Fa(this,this.B7a)),this.k(a.g.h),b.gb().Jd(this,!1))};p.fF=function(){return this.kl};p.Td=function(){return 0!=(this.kU&a.Z_.Zgb)?!0:!1};p.Lx=function(){return!this.po()&&this.Td()};p.Te=function(c){c=this.kU&~a.Z_.Zgb|(c?a.Z_.Zgb:0);this.kU!=c&&(this.kU=c,this.zd(),b.gb().Jd(this,!1),this.ea(a.g.h))};
p.eOa=function(){return 0!=(this.kU&a.Z_.Ygb)?!0:!1};p.Xbc=function(b){b=this.kU&~a.Z_.Ygb|(b?a.Z_.Ygb:0);this.kU!=b&&(this.kU=b,this.Dh(),this.ea(a.g.h))};p.gSd=function(c){this.GOa()!=c&&(this.kU=this.kU&~a.Z_.nXb|c,this.zd(),b.gb().Jd(this,!1),this.ea(a.g.h))};p.GOa=function(){return this.kU&a.Z_.nXb};p.Vf=function(c){this.xt!=c&&(this.xt=c,b.gb().Jd(this,!1),this.ea(a.g.h))};p.af=function(){return this.xt};p.Ie=function(){return this.SC};p.ud=function(c){this.SC!=c&&(this.SC=c,this.zd(),b.gb().Jd(this,
!1),this.ea(a.g.h))};p.Re=function(){return this.EC};p.$d=function(c){this.EC!=c&&(this.EC=c,this.zd(),b.gb().Jd(this,!1),this.ea(a.g.h))};p.Sf=function(){return this.HC};p.Fd=function(c){this.HC!=c&&(this.HC=c,this.zd(),b.gb().Jd(this,!1),this.ea(a.g.h))};p.$f=function(){return this.wC};p.Be=function(c){this.wC!=c&&(this.wC=c,this.zd(),b.gb().Jd(this,!1),this.ea(a.g.h))};p.bt=function(c){this.CP!=c&&(this.CP=c,b.gb().Jd(this),this.k(a.g.h))};p.Oc=function(){return this.Ka};p.pd=function(c){this.Ka!=
c&&(null!=this.Ka&&(this.Ka.Ba(this,this.Gn),this.Ka.Cb()),this.Ka=c,null!=this.Ka&&(this.Ka.Ha(),this.Ka.Fa(this,this.Gn)),this.zd(),b.gb().Jd(this),this.k(a.g.h))};p.Iv=function(){return this.CP};p.Rt=function(){return this.tw};p.hs=function(c){c!=this.tw&&(this.tw=c,this.zd(),this.ea(a.g.h),b.gb().Jd(this))};p.pD=function(){return this.oY};p.gC=function(b){this.oY!=b&&(this.oY=b,this.zd(),this.k(a.g.h))};p.bn=function(){var b=a.ce.JD;switch(this.ig()){case a.fh.nB:switch(this.mW()){case a.dh.Xq:b=
a.ce.JD;break;case a.dh.WO:b=a.ce.qSa;break;default:b=a.ce.sSa}break;case a.fh.wJ:switch(this.mW()){case a.dh.Xq:b=a.ce.rSa;break;case a.dh.WO:b=a.ce.s7b;break;default:b=a.ce.u7b}break;default:switch(this.mW()){case a.dh.Xq:b=a.ce.z0;break;case a.dh.WO:b=a.ce.r7b;break;default:b=a.ce.KS}}return b};p.BD=function(){return 0!=(this.Gia&a.Wgb.H5b)};p.$Fd=function(a){this.Gia|=a};p.tPc=function(a){this.Gia&=~a};p.aGd=function(a,b){this.Gia=this.Gia&~a|(b?a:0)};p.Rd=function(a,b,c){p.j.Rd.call(this,a,b,
c);this.nr(!1)};p.h7=function(a){p.j.h7.call(this,a);this.nr(a)};p.nr=function(a){p.j.nr.call(this,a);a=this.Ve();this.EJb(a,!1)};p.dj=function(){p.j.dj.call(this);this.Ed(a.Z.QB);this.Ed(a.Z.kBa)};p.dd=function(){this.rJ(a.cc.ON,this.KN());p.j.dd.call(this)};p.mr=function(a){null!=this.kl?this.kl.ef():p.j.mr.call(this,a)};p.bg=function(){this.C0();b.gb().bD(this)};p.LD=function(){this.ZU()};p.TF=function(a){var b=!1,b=a.Dd().jTa(this,this.ca.Lh,this.yfb(),this.Afb(),this.zfb(),a);!1==b&&p.j.TF.call(this,
a)};p.ve=function(b){""==b[1]&&(b[1]=a.DWb);p.j.ve.call(this,b)};p.EJb=function(a,d){var n=b.vc(a),k=b.vc(n),h=null,f=0<this.tw?this.tw:-1;this.Ka&&(h=this.Ka.SEb(n.ba()-4,n.ba()-4));n.Ua(n.M()+this.SC);n.Va(n.O()+this.EC);n.Ra(n.va-this.HC);n.Ga(n.ua-this.wC);var e=this.eb(),q=new c.ga,g=new c.ga,B=[],v="";B[0]=q;B[1]=k;B[2]=g;B[3]=f;B[4]=f;B[5]=0;this.LDa(null,h,e,this.se(),n,B);q=B[0];k=B[1];n=B[5];this.Ka&&this.Ka instanceof c.UN&&(v=this.Ka.Yg());this.n3=q;this.yM=k;d||(h=this.Sa().fb(),f=this.Lx(),
b.Yd[h].oh(h,k,v,q,f,this.eOa(),n))};p.LDa=function(d,r,n,k,h,f){d=f[0];var e=f[1],q=f[2],g=f[3],B=f[4],v=f[5],e=b.vc(h);if(null!=r&&this.Md()){var p=a.dg.jFa;this.fF()||(p|=a.dg.nWa);v=p;if(this.Lx())switch(this.GOa()){case a.Svb.Wvb:p|=a.dg.jC;break;default:p|=a.dg.jC,v|=a.dg.jC}else v|=this.xt;switch(this.ig()){case a.fh.nB:v|=a.dg.Rfa;break;case a.fh.wJ:v|=a.dg.lFa;break;default:v|=a.dg.Hsb}b.soa(r,n,k,h,0,this.bn(),this.bn(),this.Iv(),d,e,q,0,this.Md()?0:2,g,B,p)}else if(v=this.WDb(e),0<n.length){e.aa()>
h.aa()&&(this.Lx()?this.GOa()==a.Svb.Wvb&&(e=new c.ga(0,0,h.aa(),e.ba())):e=new c.ga(0,0,h.aa(),e.ba()));switch(this.ig()){case a.fh.nB:e=new c.ga(h.O()+(h.aa()-e.aa())/2,1,e.aa(),e.ba());v|=a.dg.Rfa;break;case a.fh.wJ:e=new c.ga(h.va-e.aa(),1,e.aa(),e.ba());v|=a.dg.lFa;break;default:e=new c.ga(h.O(),1,e.aa()+1,e.ba()),v|=a.dg.Hsb}switch(this.mW()){case a.dh.Xq:e=new c.ga(e.O(),h.M()+(h.ba()-e.ba())/2,e.aa(),e.ba());break;case a.dh.WO:e=new c.ga(e.O(),h.ua-1-e.ba(),e.aa(),e.ba())}}f[0]=d;f[1]=e;f[2]=
q;f[3]=g;f[4]=B;f[5]=v};p.WDb=function(c){var d=this.se(),n=a.dg.jFa,k=this.eb();if(0<k.length)if(this.fF()||(n|=a.dg.nWa),this.QA=b.kO(k,d,this.Lx(),c.aa(),c.ba()),this.Lx())switch(this.GOa()){case a.Svb.Wvb:b.GD(k,c,n|a.dg.jC,d);break;default:b.GD(k,c,n|a.dg.jC,d),n|=a.dg.jC}else b.GD(k,c,n,d),n|=this.xt;return n};p.vqc=function(){var a=b.zS();this.ak(!1,!0);this.WDb(a);this.Wb(a.aa())};p.MD=function(c){if(this.eOa())switch(b.ds(c)){case a.W.QTa:case a.W.D$b:case a.W.K$b:case a.W.K0:case a.W.L$b:case a.W.q0c:case a.W.V1c:case a.W.G$b:case a.W.b2c:case a.W.STa:c.Cl(!0);
return}p.j.MD.call(this)};p.AA=function(a){var b=this.po(),c=this.jq();(b||c)&&this.x8b(a,b,c)};p.x8b=function(a,d,n){var k=new c.ga,h=new c.ga(0,0,1E4,1E4);this.Lx()&&h.Ra(h.O()+a.aa()-(this.ca.rj()+this.ca.Fk()));this.EJb(h,!0);""==this.eb()&&this.n3.kg()||(""==this.eb()?k=this.n3:(k=b.vc(this.yM),k.Ga(k.ua+(0<this.yM.ba()?1:0)),k=k.f2(this.n3)));d&&a.Ra(a.O()+this.ca.rj()+this.EC+k.aa()+this.HC+this.ca.Fk());n&&a.Ga(a.M()+this.ca.Gk()+this.SC+k.ba()+this.wC+this.ca.km())};p.yea=function(a,b,c){p.j.yea(a,
b,c);c[0]&&this.eOa()&&(c[0]=!1)};p.Qf=function(a){b.Tib();return p.j.Qf.call(this,a)};p.Gn=function(c,d){switch(d.Za){case a.g.wb:case a.g.Tb:d.aj==this.Ka&&this.pd(null);break;case a.g.h:d.aj==this.Ka&&(b.gb().Jd(this),this.zd())}};p.B7a=function(b,c){c.Za==a.g.Tb&&this.dC(null)};p.zv=p[a.Z.ZH]=function(a){p.j.zv.call(this,a);b.gb().Jd(this,!1)};p.Dpd=p[a.Z.kBa]=function(){b.gb().Jd(this,!1)};p.YM=p[a.Z.QB]=function(){b.gb().Jd(this,!1)};p.ela=p[a.Z.uBa]=function(a){this.Uy()?this.Le(!1):p.j.ela.call(this,
a)};p.XM=p[a.Z.yK]=function(){this.kl&&this.kl.ef()};p.zx=p[a.Z.az]=function(b){this.BD()&&(this.rq(),this.tPc(a.Wgb.H5b));p.j.zx.call(this,b)};d.xd(c.Yt,"PRIM_LABL",{Pa:{Ellipses:{a:function(){return d.sa(this.af(),a.jp.u)},f:function(b){this.Vf(d.qa(b,a.jp.u))}},Caption:{a:p.eb,f:function(a){this.ub(d.ja(a))}},Alignment:{a:function(){return d.sa(this.ig(),a.fh.u)},f:function(b){this.rb(d.qa(b,a.fh.u))}},VerticalAlignment:{a:function(){return d.sa(this.mW(),a.dh.u)},f:function(b){this.tn(d.qa(b,
a.dh.u))}},FocusControl:{a:p.fF,f:p.dC},WordWrap:{a:p.Td,f:function(a){this.Te(d.wa(a))}},Selectable:{a:p.eOa,f:function(a){this.Xbc(d.wa(a))}},MarginLeft:{a:p.Re,f:function(a){this.$d(d.v(a))}},MarginTop:{a:p.Ie,f:function(a){this.ud(d.v(a))}},MarginBottom:{a:p.$f,f:function(a){this.Be(d.v(a))}},MarginRight:{a:p.Sf,f:function(a){this.Fd(d.v(a))}},Image:{a:p.Oc,f:p.pd},ImagePosition:{a:function(){return d.sa(this.Iv(),a.Pk.u)},f:function(b){this.bt(d.qa(b,a.Pk.u))}},ImageHeight:{a:p.Rt,f:function(a){this.hs(d.v(a))}},
ImageSizing:{a:function(){return d.sa(this.pD(),a.Sd.u)},f:function(b){this.gC(d.qa(b,a.Sd.u))}}},Bg:{wg:"Caption"}});c.jkb=function(a){u.H.call(this,a);this.HZa=this.tw=this.RHa=this.jzb=this.izb=this.Ka=this.gH=this.Eja=this.EE=this.JBb=this.IBb=this.HBb=this.qb=null};var u=c.q(c.jkb,c.on);u.eb=function(){return this.qb.textContent};u.ub=function(a){this.qb.textContent=a};u.u5=function(){return this.qb};u.nN=function(){return this.qb};u.oh=function(b,c,n,k,h,f,e){null==this.Ka.parentElement&&this.G.appendChild(this.Ka);
if(null==this.HZa||this.HZa!=f)this.HZa=f,this.qb.spellcheck=!1,this.qb.setAttribute("contenteditable",f);this.Ka.style.backgroundImage=d.yv(n);switch(this.na.pD()){case a.Sd.HI:this.Ka.style.backgroundSize="contain";break;case a.Sd.$Ea:this.Ka.style.backgroundSize="cover";break;case a.Sd.fg:this.Ka.style.backgroundSize="100% 100%";break;case a.Sd.Xd:this.Ka.style.backgroundSize="auto"}if(null==this.gH||this.gH!=h)this.gH=h,this.qb.style.whiteSpace=h?"pre-wrap":"pre";if(null==this.Eja||this.Eja!=
e)this.Eja=e,this.qb.style.textAlign=0!=(e&a.dg.lFa)?"right":0!=(e&a.dg.Rfa)?"center":"",0!=(e&a.dg.iFa)||0!=(e&a.dg.kFa)||0!=(e&a.dg.mFa)?(this.qb.style.textOverflow="ellipsis",this.qb.style.overflow="hidden"):(this.qb.style.textOverflow="clip",this.qb.style.overflow="visible");if(null==this.HBb||this.HBb!=c.O())this.HBb=c.O(),this.qb.style.left=c.O()+"px";if(null==this.IBb||this.IBb!=c.M())this.IBb=c.M(),this.qb.style.top=c.M()+"px";if(null==this.EE||this.EE!=c.ba())this.EE=c.ba(),this.qb.style.height=
c.ba()+"px";if(null==this.JBb||this.JBb!=c.aa())this.JBb=c.aa(),this.qb.style.width=c.aa()+"px";if(null==this.izb||this.izb!=k.O())this.izb=k.O(),this.Ka.style.left=k.O()+"px";if(null==this.jzb||this.jzb!=k.M())this.jzb=k.M(),this.Ka.style.top=k.M()+"px";if(null==this.tw||this.tw!=k.ba())this.tw=k.ba(),this.Ka.style.height=k.ba()+"px";if(null==this.RHa||this.RHa!=k.aa())this.RHa=k.aa(),this.Ka.style.width=k.aa()+"px"};u.df=function(a,b){this.G=document.createElement("div");this.G.setAttribute("LANSAHandle",
this.kc);this.qb=document.createElement("div");var c=this.qb.style;c.position="absolute";c.outline="none";c.overflowX="hidden";c.overflowY="hidden";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";c.borderStyle="solid";c.borderLeftWidth="0px";c.borderTopWidth="0px";c.borderRightWidth="0px";c.borderBottomWidth="0px";c.cursor="inherit";c.textDecoration="inherit";this.Ka=document.createElement("div");c=this.Ka.style;c.position="absolute";c.backgroundSize="contain";
c.backgroundPosition="center center";c.backgroundRepeat="no-repeat";this.G.appendChild(this.qb);this.G.appendChild(this.Ka);return u.j.df.call(this,a,b)};u.iZ=function(){var a=this;this.l4();a.qb.addEventListener("paste",function(b){a.tea(b);b.preventDefault()},!1)};u.gvb=function(){var a="";u.j.gvb.call(this);"rgba(0,0,0,0)"==this.HYa&&""!=this.G.style.boxShadow&&(a=this.G.style.boxShadow);this.qb.style.textShadow=a};u.lO=function(a){u.j.lO.call(this,a);return!this.HZa};u.tea=function(){}});
