window.LANSA.addSrc("imag",function(d,c,a,b){c.Yt=function(){p.J.call(this);this.rr="";this.vc=this.ob=this.IB=this.L$a=this.vY=this.lf=this.sf=null;this.c3=a.Zd.fAa;this.bga=null;this.BJ=this.aK=this.UJ=this.sK=0;this.Cd|=a.sc.eKa;this.lf=new c.UW;this.sf=new c.xb;this.sf.Jd(this.lf);this.Ne(!1)};var p=c.q(c.Yt,c.Xl);p.cZ="";p.kb=function(){b.fa(this.bga);this.bga=null;b.fa(this.lf);this.lf=null;b.fa(this.sf);this.sf=null;p.j.kb.call(this)};p.Q=function(){p.j.Q.call(this);this.zza(null);this.L$a=
null;this.Jj(null);this.vq(null)};p.ze=function(){return this.Bw()?c.Qjc:p.j.ze.call(this)};p.Jg=function(){return this.rr};p.Ru=function(c){b.bA(this.rr,c)||(this.rr=c,this.zza(b.zxa(this.rr)),this.l(a.g.i))};p.aUd=function(){return this.vY};p.zza=function(b){this.vY!=b&&(this.Jj(null),null!=this.vY&&this.vY.Ga(this,this.YVb),this.vY=b,null!=this.vY&&this.vY.Ha(this,this.YVb),this.oP(),this.wb(),this.l(a.g.i))};p.NK=function(){return this.IB};p.Jj=function(b){this.IB!=b&&(this.zza(null),null!=this.IB&&
(this.IB.Ga(this,this.ip),this.IB.ub()),this.IB=b,null!=this.IB&&(this.IB.Aa(),this.IB.Ha(this,this.ip)),this.oP(),this.wb(),this.Gd(),this.l(a.g.i))};p.bW=function(){return this.lf.Om()};p.WS=function(b){this.lf.Om()!=b&&(this.lf.Ng(b),this.l(a.g.i))};p.sN=function(){return this.lf.te()};p.$O=function(b){this.lf.te()!=b&&(this.lf.Ya(b),this.l(a.g.i))};p.vN=function(){return this.lf.Qe()};p.aP=function(b){this.lf.Qe()!=b&&(this.lf.Wa(b),this.l(a.g.i))};p.TK=function(){return this.lf.Ta()};p.NG=function(b){this.lf.Ta()!=
b&&(this.lf.oc(b),this.l(a.g.i))};p.Iv=function(){return this.lf.Ma()};p.cu=function(b){this.lf.Ma()!=b&&(this.lf.wc(b),this.l(a.g.i))};p.nE=function(){return this.c3};p.QE=function(b){this.c3!=b&&(this.c3=b,this.lf.bc(b),this.wb(),this.Gd(),this.l(a.g.i))};p.uN=function(){return this.lf.e0()};p.nJ=function(b){this.lf.e0()!=b&&(this.lf.dea(b),this.l(a.g.i))};p.wN=function(){return this.lf.sj()};p.bP=function(b){this.lf.sj()!=b&&(this.lf.Jk(b),this.l(a.g.i))};p.WA=function(){return this.lf.hi()};p.uB=
function(b){this.lf.hi()!=b&&(this.lf.Vb(b),this.l(a.g.i))};p.Fh=function(b){this.ob!=b&&(this.vq(b),this.l(a.g.i))};p.qb=function(){var a=null;return a=this.ob};p.mc=function(){return this.vc};p.Hf=function(){return this.sK};p.Cf=function(c){this.sK!=c&&(this.sK=c,this.wb(),this.Gd(),b.pb().be(this,!1),this.na(a.g.i))};p.Pf=function(){return this.UJ};p.zf=function(c){this.UJ!=c&&(this.UJ=c,this.wb(),this.Gd(),b.pb().be(this,!1),this.na(a.g.i))};p.Tg=function(){return this.aK};p.ue=function(c){this.aK!=
c&&(this.aK=c,this.wb(),this.Gd(),b.pb().be(this,!1),this.na(a.g.i))};p.Xg=function(){return this.BJ};p.hg=function(c){this.BJ!=c&&(this.BJ=c,this.wb(),this.Gd(),b.pb().be(this,!1),this.na(a.g.i))};p.Op=function(){return this.cZ};p.y7=function(b){this.cZ!=b&&(this.cZ=b,this.Zh(),this.na(a.g.i))};p.fp=function(a,b,c,d,e){return e};p.LQ=function(){var a=this.vc.lk();""!=a?this.vY&&this.vY.Jg()==a||this.zza(b.zxa(a)):this.zza(this.vc.dJa());this.ob.A_(this.mc())};p.vq=function(a){var c=null;a&&(c=a.Bz(),
this.ob==a?c.Jn(this.vc):a.wC(c));this.ob&&(this.ob.Ga(this),this.vc.Ga(this),b.fa(this.vc),this.vc=null);if(this.ob=a)this.ob.Ha(this,this.Lp),this.vc=c,this.vc.Ha(this,this.Dy);this.Zh()};p.oP=function(){null==this.IB?this.lf.yd(this.vY):this.L$a&&0<this.L$a.Jg().length?this.lf.yd(this.L$a):this.lf.yd(this.IB)};p.hf=function(b){p.j.hf.call(this,b);this.Bw()||(b=new c.pa(0,0,b.ha(),b.ka()),this.bga||(this.bga=new c.Xl,this.bga.Ne(!1)),this.bga.Pza(this.sf),b.Wa(b.Z()+this.Hf()),b.Ya(b.$()+this.Pf()),
b.Ua(b.Ja()-this.Tg()),b.Ia(b.Da()-this.Xg()),this.bga.Hb(this),this.bga.rb(b),this.nE()==a.Zd.fAa&&this.lf.Xc()&&(this.lf.Xc().Ma()>b.ka()||this.lf.Xc().Ta()>b.ha()?this.lf.bc(a.Zd.UL):this.lf.bc(a.Zd.rf)))};p.XC=function(b){var d=this.Ho(),s=this.mq();if(0!=this.vN()||0!=this.sN()||100!=this.TK()||100!=this.Iv()||this.uN()!=a.Et.wea||this.wN()!=a.zy.Hea||this.lf.si()==a.Zd.y6a)s=d=!1;if(d||s){var k=new c.pa;if(this.lf.Xc())switch(k.Ua(this.lf.Xc().Ta()),k.Ia(this.lf.Xc().Ma()),this.lf.si()){case a.Zd.UL:if(s&&
!d&&0<b.ha()&&0<k.ha()){var e=b.ha()/k.ha();k.Ia(k.Z()+k.ka()*e)}}d&&b.Ua(b.$()+this.ga.$i()+this.Pf()+k.ha()+this.Tg()+this.ga.ek());s&&b.Ia(b.Z()+this.ga.fk()+this.Hf()+k.ka()+this.Xg()+this.ga.Dl())}};p.of=function(a){b.f1a();a=p.j.of.call(this,a);if(!a){var c=this.Op();if(b.uwa(c)){var d=b.aa().An;d&&d.pma(b.qaa(c),!0,!0)}}return a};p.ip=function(b,c){switch(c.cb){case a.g.Bb:case a.g.Ub:this.Jj(null);break;case a.g.i:this.wb(),this.Gd()}};p.YVb=function(b,c){switch(c.cb){case a.g.Bb:case a.g.Ub:this.zza(null);
break;case a.g.i:this.wb()}};p.Lp=function(b,c){c.cb==a.g.i?c.su==a.Ie.Xz?this.ob.wC(this.mc()):this.vq(this.ob):c.cb==a.g.Bb&&this.Fh(null)};p.Dy=function(b,c){c.cb==a.g.i&&c.su==a.Ie.Xz&&this.LQ()};d.Kd(c.Yt,"PRIM_IMAG",{za:{FileName:{a:p.Jg,f:function(a){this.Ru(d.ja(a))}},Image:{a:p.NK,f:function(a){this.Jj(a)}},ImageTile:{a:function(){return d.va(this.uN(),a.Et.v)},f:function(b){this.nJ(d.ua(b,a.Et.v))}},ImageUnits:{a:function(){return d.va(this.wN(),a.zy.v)},f:function(b){this.bP(d.ua(b,a.zy.v))}},
ImageSizing:{a:function(){return d.va(this.nE(),a.Zd.v)},f:function(b){this.QE(d.ua(b,a.Zd.v))}},ImageOpacity:{a:p.bW,f:function(a){this.WS(d.L(a))}},ImageLeft:{a:p.sN,f:function(a){this.$O(d.L(a))}},ImageTop:{a:p.vN,f:function(a){this.aP(d.L(a))}},ImageWidth:{a:p.TK,f:function(a){this.NG(d.L(a))}},ImageHeight:{a:p.Iv,f:function(a){this.cu(d.L(a))}},ImageAlignment:{a:function(){return d.va(this.WA(),a.Gc.v)},f:function(b){this.uB(d.ua(b,a.Gc.v))}},DataClass:{a:p.qb,f:p.Fh},MarginLeft:{a:p.Pf,f:function(a){this.zf(d.L(a))}},
MarginTop:{a:p.Hf,f:function(a){this.Cf(d.L(a))}},MarginBottom:{a:p.Xg,f:function(a){this.hg(d.L(a))}},MarginRight:{a:p.Tg,f:function(a){this.ue(d.L(a))}},Link:{a:p.Op,f:function(a){this.y7(d.ja(a))}}}});c.Qjc=function(a){t.J.call(this,a)};var t=c.q(c.Qjc,c.tL);t.Tra=null;t.RCc="";t.vQb=null;t.vpb=function(){return!1};t.bJb=function(a){this.vQb&&(a="0");t.j.bJb.call(this,a)};t.Cza=function(){this.vQb=!0;this.Hc()};t.Hc=function(){var c=this.K.lf.Xc()?this.K.lf.Xc().Jg():this.K.Jg(),p=this.K.nE();
p==a.Zd.fAa&&(p=a.Zd.Og);t.j.Hc.call(this);""!=this.K.Op()&&(this.u.href=b.qaa(this.K.Op()));this.RCc!=c&&(this.RCc=c,this.vQb=!1,this.Tra.src=c);this.WCb(this.Tra,d.va(this.K.WA(),a.Gc.v),d.va(p,a.Zd.Yl))};t.Fd=function(){""!=this.K.Op()?(this.u=document.createElement("a"),this.u.setAttribute("LANSAHandle",this.gc),this.Tra=document.createElement("img"),this.Tra.style.width="100%",this.u.appendChild(this.Tra)):(this.u=document.createElement("img"),this.u.setAttribute("LANSAHandle",this.gc),this.Tra=
this.u);var a=this;a.Tra.addEventListener("error",function(){a.K&&a.Cza()},!1);return this.u}});
