window.LANSA.addSrc("ppnl",function(d,c,a,b,p){d.Ob("PRIM_PHBN");d.Ob("PRIM_IMAG");d.Ob("PRIM_TBLO");a.Wxb={LLa:0,Elc:3};a.zO={Uca:0,Vxa:1,Alc:2};a.zO.v={NONE:a.zO.Uca,POPUP:a.zO.Vxa};a.Zl={sma:8321,z3a:1,Xzb:2,bAb:8,Yzb:16,$zb:32,aAb:64,dAb:128,gAb:256,Zzb:512,fAb:1024,t$d:2048,eAb:4096,Boc:8192,cAb:16384};a.zla={O6:0,ZW:1,$W:2};a.x9d={Coc:0};a.UQ={ihb:0,ehb:268435456,khb:536870912};a.UQ.v={HIDDEN:a.UQ.ihb,ALL:a.UQ.ehb,NONE:a.UQ.khb};a.qya={Afd:0,lzb:1,Zmc:805306368};a.Vg={f2:0,CBa:1,i8a:3,j8a:4,
oIb:5,txc:6,pIb:7,lxc:8,mxc:9,pxc:10,vxc:11,qxc:12,nxc:13,oxc:14,rxc:15,sxc:16,uxc:17};a.Vg.v={NONE:a.Vg.f2,FADEINANDSCALE:a.Vg.CBa,SLIDEINLEFT:a.Vg.i8a,SLIDEINRIGHT:a.Vg.j8a,SLIDEINBOTTOM:a.Vg.oIb,NEWSPAPER:a.Vg.txc,SLIDEINTOP:a.Vg.pIb,"3DFLIPHORIZONTAL":a.Vg.lxc,"3DFLIPVERTICAL":a.Vg.mxc,"3DSIGN":a.Vg.pxc,SUPERSCALED:a.Vg.vxc,"3DSLIT":a.Vg.qxc,"3DROTATEBOTTOM":a.Vg.nxc,"3DROTATEINLEFT":a.Vg.oxc,LETMEIN:a.Vg.rxc,MAKEWAY:a.Vg.sxc,SLIPFROMTOP:a.Vg.uxc};a.Vg.uLa={NONE:a.Vg.f2,FADEINANDSCALE:a.Vg.CBa};
a.Vg.p7d={NONE:a.Vg.f2,FADEIN:a.Vg.CBa,SLIDEINLEFT:a.Vg.i8a,SLIDEINRIGHT:a.Vg.j8a,SLIDEINTOP:a.Vg.pIb,SLIDEINBOTTOM:a.Vg.oIb};a.Vg.YZb={"":a.Vg.f2,"md-effect-1":a.Vg.CBa,"md-effect-21":a.Vg.i8a,"md-effect-2":a.Vg.j8a,"md-effect-3":a.Vg.oIb,"md-effect-4":a.Vg.txc,"md-effect-7":a.Vg.pIb,"md-effect-8":a.Vg.lxc,"md-effect-9":a.Vg.mxc,"md-effect-10":a.Vg.pxc,"md-effect-11":a.Vg.vxc,"md-effect-13":a.Vg.qxc,"md-effect-14":a.Vg.nxc,"md-effect-15":a.Vg.oxc,"md-effect-17":a.Vg.rxc,"md-effect-18":a.Vg.sxc,"md-effect-19":a.Vg.uxc};
c.jhc=function(a){t.J.call(this,a);this.Fc=a};var t=c.q(c.jhc,c.u6);t.kb=function(){t.j.kb.call(this)};t.Q=function(){this.hb.f7();t.j.Q.call(this)};t.la=function(){return this.Fc.Gb()};t.Sa=function(){return null};t.cka=function(){return!0};t.Sda=function(){};t.fna=function(){};t.ena=function(){};t.kA=function(){};t.Sx=function(){};t.Yua=function(){return null};t.eL=function(){return!1};t.Xd=function(){return!0};t.YN=function(){return!0};t.MN=function(){return!1};t.t0=function(){return!1};t.Me=function(b){b[0]=
a.i0a;b[1]=a.g0a};t.VJd=function(){};t.SZ=function(a){t.j.SZ.call(this,a)};t.bFc=function(){return!1};t.$la=function(){};t.Lg=function(){};t.ida=function(){};t.Px=function(){};t.lda=function(){};t.HE=function(){};c.Kx=function(){d.Ob("PRIM_IMAG");d.Ob("PRIM_TBLO");d.Ob("PRIM_LABL");l.J.call(this);this.Mb=b.Kf(10,10,280,120);this.wg=a.Zl.sma;this.Km=this.me=this.eY=this.Dp=null;this.MA=a.Vg.f2;this.EM=a.nh.Nx;this.TSa=this.t3=this.uU=null;this.Dg=new c.od(0,0);this.gdb=this.Iga=this.ap=this.PD=this.AF=
this.kC=this.Ls=this.QU=this.Cp=null;this.HTa="";this.mTa=12;this.Hga=a.m.Rb;b.aa().E6c(this);this.DEc();b.aa().tSc();var e=null;this.Qs();this.Ls=new c.Xl;this.Ls.rb(new c.pa(0,0,0,30));this.Ls.Ne(!1);this.Ls.sq(!1);this.Ls.Wp(this.Mc);this.Ls.gna(!1);this.kC=new c.Yt;this.kC.Ne(!1);this.kC.QE(a.Zd.UL);this.kC.Na(this.Ls);this.kC.uB(a.Gc.dA);this.AF=new c.Yt;this.AF.QE(a.Zd.fAa);this.AF.Na(this.Ls);this.AF.Ne(!1);this.AF.ya(this,a.O.qc,this.$Mc);this.AF.ya(this,a.O.yG,this.aNc);this.AF.ya(this,a.O.zG,
this.bNc);this.PD=new c.Kw;this.PD.Na(this.Ls);this.PD.Ne(!1);this.PD.Oo(a.bh.wq);this.PD.Df(!1);this.PD.tg(a.Mp.ZZb);b.Oc(this.Mc,this.Ls,null,null,1,1);e=b.Oc(this.Mc,this.kC,this.Mc.Cc(0),this.Mc.Lc(0),1,1);e.Vb(a.ma.Iq);e.bc(a.sa.Kk);e.zf(2);e=b.Oc(this.Mc,this.AF,this.Mc.Cc(0),this.Mc.Lc(0),1,1);e.Vb(a.ma.qC);e.bc(a.sa.rf);e.ue(2);e=b.Oc(this.Mc,this.PD,this.Mc.Cc(0),this.Mc.Lc(0),1,1);e.Vb(a.ma.pe);e.bc(a.sa.Kk);this.Ne(!1)};var l=c.q(c.Kx,c.Xl);l.kb=function(){b.fa(this.CId);this.CId=null;
b.fa(this.Ls);this.Ls=null;b.fa(this.kC);this.kC=null;b.fa(this.AF);this.AF=null;b.fa(this.PD);this.PD=null;l.j.kb.call(this)};l.Q=function(){b.fa(this.ap);this.ap=null;l.j.Q.call(this);this.Pma(null);this.s4a(null);this.w5a(null);this.x5a(null);this.Nma(null);this.UDb(null);b.aa().Tid(this);b.fa(this.Km);this.Km=null;b.fa(this.TSa);this.TSa=null};l.ze=function(){var a=c.tL;this.$R()&&(a=c.mkc);return a};l.CZd=function(){return this.EM};l.Kua=function(){if(null==this.TSa){var a=new c.jhc(this);this.TSa=
b.Aca(a);this.Ha(this,this.oPc)}return this.TSa};l.Pma=function(b){this.Dp!=b&&(this.Dp&&this.Dp.Ga(this),(this.Dp=b)&&this.Dp.Ha(this,this.NVb),this.l(a.g.i))};l.wWc=function(){return this.Dp};l.lja=function(){var a=null;this.Dp&&this.Dp instanceof c.Jx&&(a=this.Dp);return a};l.s4a=function(b){this.eY!=b&&(this.eY&&this.eY.Ga(this),(this.eY=b)&&this.eY.Ha(this,this.BMc),this.l(a.g.i))};l.$Qd=function(){return this.eY};l.w5a=function(b){this.uU!=b&&(this.uU&&this.uU.Ga(this),(this.uU=b)&&this.uU.Ha(this,
this.mPc),this.l(a.g.i))};l.AZd=function(){return this.uU};l.x5a=function(b){this.t3!=b&&(this.t3&&this.t3.Ga(this),(this.t3=b)&&this.t3.Ha(this,this.nPc),this.l(a.g.i))};l.BZd=function(){return this.t3};l.Gb=function(){var a=this.me;!this.me||this.me instanceof c.Kx||(a=this.me);!a&&this.Xrb()&&(a=this);return a};l.oTd=function(){return this.me};l.LR=function(){null==this.Km&&(this.Km=new c.kla,this.Km.msc(),this.Km.$Na(a.Zx.d8a));return this.Km};l.W_c=function(){return this.Km};l.T_d=function(){return this.Dg};
l.Pp=function(){this.gh();return this.Ag};l.Fda=function(b){b=this.wg&~a.Zl.Xzb|(b?a.Zl.Xzb:0);this.wg!=b&&(this.wg=b,this.l(a.g.i))};l.Ima=function(b){b=this.wg&~a.Zl.z3a|(b?a.Zl.z3a:0);this.wg!=b&&(this.wg=b,this.l(a.g.i))};l.BHa=function(){return 0!=(this.wg&a.Zl.z3a)};l.NBb=function(b){b=this.wg&~a.Zl.Yzb|(b?a.Zl.Yzb:0);this.wg!=b&&(this.wg=b,this.l(a.g.i))};l.Pta=function(){return 0!=(this.wg&a.Zl.Yzb)};l.TDb=function(b){b=this.wg&~a.Zl.gAb|(b?a.Zl.gAb:0);this.wg!=b&&(this.wg=b,this.YX(this.uf()),
this.l(a.g.i))};l.wob=function(){return 0!=(this.wg&a.Zl.gAb)};l.k1c=function(){return this.mTa};l.Hsc=function(b){b!=this.mTa&&(this.mTa=b,this.wb(),this.na(a.g.i))};l.U_d=function(){return this.Hga};l.TNa=function(b){if(this.bsb()||this.Hga!=b)this.Hga=b,this.l(a.g.i)};l.etd=function(){!1==this.bsb()&&(this.Hga=a.m.Rb,this.l(a.g.i))};l.brc=function(b){b=this.wg&~a.Zl.Zzb|(b?a.Zl.Zzb:0);this.wg!=b&&(this.wg=b,this.YX(this.uf()),this.l(a.g.i))};l.PXa=function(){return 0!=(this.wg&a.Zl.Zzb)};l.Mee=
function(b){b=this.wg&~a.Zl.eAb|(b?a.Zl.eAb:0);this.wg!=b&&(this.wg=b,this.l(a.g.i))};l.u0c=function(){return 0!=(this.wg&a.Zl.eAb)};l.Jrc=function(){var b=this.wg&~a.Zl.cAb|a.Zl.cAb;this.wg!=b&&(this.wg=b,this.l(a.g.i))};l.F2b=function(){return 0!=(this.wg&a.Zl.cAb)};l.$sd=function(){var b=this.wg&~a.Zl.Boc|0;this.wg!=b&&(this.wg=b,this.l(a.g.i))};l.j1c=function(){return 0!=(this.wg&a.Zl.Boc)};l.MG=function(b){b=this.wg&~a.Zl.bAb|(b?a.Zl.bAb:0);this.wg!=b&&(this.wg=b,this.l(a.g.i))};l.Sqd=function(b){b=
this.wg&~a.Zl.aAb|(b?a.Zl.aAb:0);this.wg!=b&&(this.wg=b,this.l(a.g.i))};l.Dee=function(b){b=this.wg&~a.Zl.dAb|(b?a.Zl.dAb:0);this.wg!=b&&(this.wg=b,this.l(a.g.i))};l.Ida=function(b){b=this.wg&~a.Zl.$zb|(b?a.Zl.$zb:0);this.wg!=b&&(this.wg=b,this.l(a.g.i))};l.C1b=function(){return 0!=(this.wg&a.Zl.$zb)};l.B1b=function(){return this.Cp};l.Nma=function(b){this.Cp!=b&&(null!=this.Cp&&(this.Cp.Ga(this,this.Eib),this.Cp.ub()),this.Cp=b,null!=this.Cp&&(this.Cp.Aa(),this.Cp.Ha(this,this.Eib)),this.YX(this.uf()),
this.na(a.g.i))};l.h2c=function(){return this.QU};l.UDb=function(b){this.QU!=b&&(null!=this.QU&&(this.QU.Ga(this,this.MXb),this.QU.ub()),this.QU=b,null!=this.QU&&(this.QU.Aa(),this.QU.Ha(this,this.MXb)),this.YX(this.uf()),this.na(a.g.i))};l.l1c=function(){return this.Kua().Ch()};l.Isc=function(b){this.Kua().Ch()!=b&&(this.Kua().Ib(b),this.l(a.g.i))};l.m1c=function(){return this.Kua().Vk()};l.Za=function(){var a=null;null!=this.Sa()&&(a=this.Sa().Za());return a};l.HUc=function(){var a=!1;if(this.$R()||
!this.Xrb())a=!0;return a};l.g2c=function(){return this.HTa};l.fud=function(b){this.HTa!=b&&(this.HTa=b,this.wb(),this.na(a.g.i))};l.Lh=function(){var a=!1;null!=this.Sa()&&(a=this.Sa().Za(),a=b.ke[a].URa);return a};l.brb=function(){return 0!=(this.wg&a.Zl.Xzb)};l.NJa=function(){return 0!=(this.wg&a.Zl.z3a)};l.Irb=function(){return 0!=(this.wg&a.Zl.bAb)};l.S3d=function(){return 0!=(this.wg&a.Zl.aAb)};l.Xrb=function(){return 0!=(this.wg&a.Zl.dAb)};l.$R=function(){return 0!=(this.wg&a.Zl.fAb)};l.xrb=
function(){return!1};l.bsb=function(){return!1==this.O5b()};l.O5b=function(){return this.Hga!=a.m.Rb};l.s0=function(){var a=!1;this.Gb()==this&&this.Gb().U()&&this.Gb().U()!=this.Km&&(a=!0);return a};l.N4c=function(){var a=this.s0();a&&!this.U().y_a()&&(a=!1);return a};l.q1=function(){if(null!=this.Sa()){var a=this.Uja()?this.Uja().Kh():"DEFAULT";b.h9a(this.Sa().Za(),a,this.ga.k9)}};l.phd=function(a){var c=!1;this.Lh()&&this.NJa()&&this.lja()&&null!=a&&b.aa().GE(this.lja())==a&&(c=!0);return c};l.qhd=
function(a){var c=!1;if(this.Lh()&&this.NJa()&&!this.xrb())if(null==a)c=!0;else for(var d=b.aa().GE(a),c=!0;null!=a&&null!=d;)d==this?(c=!1,a=null):null!=d&&(d.lja()?(d=d.lja(),a=a!=d?d:null):a=null),d=b.aa().GE(a);return c};l.YX=function(d,e){e===p&&(e=!1);if(!b.aa().v0())if(this.wob()){var f=new c.pa(0,0,d.ha(),30),g=d.ha()-4;this.PXa()&&(g-=f.ka());this.QU&&(g-=f.ka());this.PD.sb(this.$a());this.PD.oc(Math.min(g,this.PD.uZa(this.PD.$a(),this.PD.lp().length)+10));this.Ls.Hb(this);this.Ls.rb(f);
this.Ls.Pb(""==this.HTa?a.pca:this.HTa);this.kC.zb(this.PXa());this.kC.oc(f.ka());this.kC.zb(null!=this.QU);this.kC.yd(this.QU);this.kC.rb(new c.pa(this.kC.te(),this.kC.Qe(),Math.min(this.kC.Xc()?this.kC.Xc().Ta():this.Ls.Ma(),this.Ls.Ma()-4),Math.min(this.kC.Xc()?this.kC.Xc().Ma():this.Ls.Ma(),this.Ls.Ma()-4)));this.AF.zb(this.PXa());this.AF.rb(new c.pa(this.AF.te(),this.AF.Qe(),30,29));this.AF.Jj(this.Cp?this.Cp:a.nc.GGd);e?b.aa().sEc(this.AF):b.aa().ajd(this.AF);this.Ls.U()&&d.Wa(d.Z()+f.ka())}else this.Ls.Na(null)};
l.hf=function(a){this.YX(a);l.j.hf.call(this,a)};l.gh=function(){this.s0()||this.Na(this.LR());this.Jpd(this.$R());this.HUc()&&l.j.gh.call(this)};l.Rk=function(){l.j.Rk.call(this);this.YX(this.uf())};l.Szb=function(b,c,d){l.j.Szb(b,c,d);d[0]&&this.uW()!=a.$x.yBa&&this.wob()&&(d[0]=this.Ls==c||this.PD==c)};l.Me=function(b){""==b[0]&&(b[0]=a.i0a);""==b[1]&&(b[1]=a.g0a);l.j.Me.call(this,b)};l.mda=function(a){return this.yia(this.Dp,a)};l.s3a=function(){this.Pta()&&this.MA==a.Vg.f2&&this.Gb().Rf(!0);
this.z0b()};l.$nc=function(){if(this.Pta()){var a=b.pO();a&&a.Ts(this)||this.Gb().Rf(!0)}};l.ohd=function(a){return this.lHa(a)};l.Hya=function(){null!=this.Km&&(null!=this.Gb()&&this.Tv(this.Gb(),a.ca.b0a),this.Pma(null),this.Irb()||null==this.eY||this.BHa()||b.jxa()!=this.eY||this.eY.OE(this.eY.gI()),this.s4a(null),this.w5a(null),this.x5a(null));this.brb()&&this.is()};l.xMa=function(){};l.WMa=function(){this.Dg.un(this.te());this.Dg.Xm(this.Qe());this.Lh()&&this.oD(this.EM,this.uU,this.Dg,this.Dp,
this.t3,this.MA)};l.fea=function(d,e,f,g,k){var l=b.Un();this.s0()&&(l.un(this.te()),l.Xm(this.Qe()));d==p&&(d=l.Nb());e==p&&(e=l.Tb());f==p&&(f=a.nh.Nx);g==p&&(g=a.Vg.f2);this.oD(f,null,new c.od(d,e),k,null,g)};l.oD=function(d,e,f,g,k,l){this.xf()&&d==a.nh.Yla&&null==e&&g&&g.xf()&&(e=g);this.N4c()||this.Na(this.LR());d==p&&(d=a.nh.Nx);e==p&&(e=null);f==p&&(f=b.Un());g==p&&(g=null);k==p&&(k=null);l==p&&(l=a.Vg.f2);if(this.Lh()&&this.Xrb()){if(this.uU==e&&this.t3==k&&this.Dp==g&&this.EM==d&&this.MA==
l){d=b.Qi(f.Nb(),f.Tb(),this.Gb().Ta(),this.Gb().Ma());this.Gya(d);this.LR().rb(new c.pa(0,0,d.ha(),d.ka()));f.un(d.$());f.Xm(d.Z());this.Gb().rb(d);this.utc(this.Kua().uI());this.Dg=f;return}var q=this.brb();this.Fda(!1);this.Bo();this.Hya();this.Fda(q)}this.EM!=a.nh.Nx&&this.U()!=this.Km&&this.Na(null);this.wg|=a.Zl.fAb;this.zsc(!1);null!=this.Pp()&&(this.Pma(g),this.LR(),this.F2b()&&this.LR().ga.lD(this.lja()?this.lja().ga:null),this.u0c()&&this.Tv(this.LR(),a.ca.a0a),this.s4a(b.jxa()),this.EM=
d,this.MA=l,this.YX(this.uf()),this.w5a(e),this.x5a(k),this.Gfd(f,this.Irb()),this.U()==this.LR()?this.Tv(this.LR(),a.ca.Pka):this.Tv(this,a.ca.Pka),this.s3a())};l.Bo=function(){if(this.Lh()){var c=b.aa().Mk;c&&c.Ts(this)&&this.Tv(c,a.ca.Wz);b.aa().rJc(this);null!=this.Sa()&&(c=this.Sa().Za(),b.ke[c].$Fa());this.Vkb();this.Hya()}else b.aa().u$&&(c=b.aa().u$,c.Sa()&&c.Sa().URa&&c==this.Dp&&b.aa().Cu(c,!1))};l.cFc=function(a){for(var b=this.ga.uI(),c=null,d=b.length-1;null!=b&&0<=d&&null!=(c=b[d]);d--)a.splice(0,
0,c)};l.Gfd=function(a,c){this.Sa()&&(c||(b.aa().my&&b.aa().my.D6b(),b.aa().Ay(this.lja(),!1,this)),this.Hfd(a))};l.Hfd=function(c){if(this.mda(c)&&this.Gb()){this.Gb().gh();this.F2b()&&this.LR().uE(!0);c=this.Km;c.KW()||c.Q2a();c=this.Sa().Za();a.hCa+=2;b.ke[c].lEa=a.hCa;b.RJb(c,b.ke[c].Zg());b.ke[c].Zza();var d=b.ke[c].K.ap?b.ke[c].K.ap.Sa():null;d&&d.u.parentElement!=document.body&&(null!=d.u.parentElement&&d.u.parentElement.removeChild(d.u),d.Xzc=!1,d.u.style.zIndex=b.ke[c].lEa-1,document.body.appendChild(d.u))}};
l.Gya=function(a){b.scd(this,a)};b.scd=function(d,e){switch(d.EM){case a.nh.R2a:var f=b.CE(),f=new c.pa(f.te()-d.ga.$i(),f.Qe()-d.ga.fk(),f.Ta()+(d.ga.$i()+d.ga.ek()),f.Ma()+(d.ga.fk()+d.ga.Dl()));e.PA(f);break;case a.nh.XI:var f=b.CE(),g=0,k=0,g=(f.ha()-e.Ta())/2,k=(f.ka()-e.Ma())/2;e.Qb(g,k);d.s0()&&e.PA(d.U().Ada(e));break;case a.nh.Yla:f=b.CE();g=(f.ha()-e.Ta())/2;k=f.Da()-e.Ma();e.Qb(g,k);d.s0()&&e.PA(d.U().Ada(e));break;case a.nh.zfd:f=b.CE();g=(f.ha()-e.Ta())/2;e.Qb(g,0);d.s0()&&e.PA(d.U().Ada(e));
break;case a.nh.Ymc:f=b.CE();k=(f.ka()-e.Ma())/2;g=f.Ja()-e.Ta();e.Qb(g,k);d.s0()&&e.PA(d.U().Ada(e));break;case a.nh.Wmc:f=b.CE();k=(f.ka()-e.Ma())/2;e.Qb(0,k);d.s0()&&e.PA(d.U().Ada(e));break;default:b.h1a(e)}};l.Vcd=function(){b.aa();this.ap=new c.Xl;this.ap.ya(this,a.O.Ueb,this.MPc);this.ap.ya(this,a.O.qc,this.NPc);this.xf()&&(this.ap.Z_().cg("positioning:flex; alignitems-center; justify-content:center;"),this.ap.Pz().cg("position:fixed; top:0px; right:0px; left:0px;"),this.ap.PR().cg("height:100vh;"));
this.ap.Td(1);this.ap.Ya(0);this.ap.mna(1);this.ap.Wa(0);this.ap.zb(!1);this.ap.Ne(!1);this.gdb=new c.Wf;this.Iga=new c.xb;this.Iga.Jd(this.gdb)};l.utc=function(a){var d=b.aa().An;this.ap||this.Vcd();if(!this.ap.Wb()){if(this.xf()){var e=b.FL(this.xc(),this.Hga,this.mTa/100,[]);this.ap.jE().cg("class:drawer-shroud;");this.ap.nn().cg("background-color:"+e+";")}this.gdb.Pd(this.Hga);this.gdb.Ng(this.mTa);this.ap.Ib(this.O5b()?this.Iga:null);for(e=0;e<a.length;e++)this.ap.Sn(a[e]);null==this.ap.Ch()?
this.ap.Na(null):(this.ap.Hb(d),this.ap.Td(1),this.ap.HV())}this.ap.rb(new c.pa(0,0,d.Ta(),d.Ma()))};l.W4c=function(){this.ap&&this.ap.yb()&&this.ap.Kr()};l.Ij=function(c){if(this.j1c()){var d=this.Sa().Za();a.hCa+=2;b.ke[d].lEa=a.hCa;b.RJb(d,b.ke[d].Zg())}l.j.Ij.call(this,c)};l.yia=function(b,e){var f=!0,g=d.fc(),k=this.Gb().Ta(),l=this.Gb().Ma();g.jc("CONTEXT",b);g.FF("LEFT",e.Nb());g.FF("TOP",e.Tb());g.FF("WIDTH",k);g.FF("HEIGHT",l);g.JQ("TRANSITION",this.MA,a.Vg.v);g.og("CONTINUE",!0);this.Fa(a.O.Yy,
g);e.un(g.tua("LEFT"));e.Xm(g.tua("TOP"));f=g.dh("CONTINUE");k=k==g.tua("WIDTH")?this.Gb().Ta():g.tua("WIDTH");l=l==g.tua("HEIGHT")?this.Gb().Ma():g.tua("HEIGHT");k=new c.pa(e.Nb(),e.Tb(),k,l);this.Gya(k);this.LR().rb(new c.pa(0,0,k.ha(),k.ka()));e.un(k.$());e.Xm(k.Z());this.Gb().rb(k);this.MA=g.Imb("TRANSITION",a.Vg.v);g.Kc();this.Dg=e;return f};l.lHa=function(b){var c=!1,c=d.fc();c.og("CLOSEPOPUP",!0);this.Fa(a.O.TQ,c);return c=b?!0:c.dh("CLOSEPOPUP")};l.Vkb=function(){this.Fa(a.O.tV);this.wg&=
~a.Zl.fAb;this.zsc(!0);this.s0()&&this.U().wb()};l.z0b=function(){this.Fa(a.O.Jyb)};l.MPc=function(){this.ap.yb()||(this.ap.Na(null),this.xMa())};l.NPc=function(){this.xrb()&&this.NJa()&&b.aa().Cu(this,!1)};l.aNc=function(){this.YX(this.uf(),!0)};l.bNc=function(){this.YX(this.uf())};l.$Mc=function(a,c){b.aa().Cu(this,!1);c.qk("HANDLED",!0)};l.oPc=function(){};l.NVb=function(b,c){switch(c.cb){case a.g.Bb:this.Pma(null)}};l.mPc=function(b,c){switch(c.cb){case a.g.Bb:this.w5a(null)}};l.nPc=function(b,
c){switch(c.cb){case a.g.Bb:this.x5a(null)}};l.BMc=function(b,c){switch(c.cb){case a.g.Bb:this.s4a(null)}};l.Eib=function(b,c){switch(c.cb){case a.g.Bb:case a.g.Ub:this.Nma(null)}};l.MXb=function(b,c){switch(c.cb){case a.g.Bb:case a.g.Ub:this.UDb(null)}};l.EGa=l[a.ca.Gwa]=function(){this.$R()&&this.WMa()};l.hR=l[a.ca.wE]=function(a){l.j.hR.call(this,a);this.YX(this.uf())};l.Ev=l[a.ca.kL]=function(a){l.j.Ev.call(this,a);this.YX(this.uf())};d.Kd(c.Kx,"PRIM_PPNL",{za:{CloseOnClick:{a:l.C1b,f:function(a){this.Ida(d.Ba(a))}},
AutoClose:{a:l.BHa,f:function(a){this.Ima(d.Ba(a))}},AutoFocus:{a:l.Pta,f:function(a){this.NBb(d.Ba(a))}},TitleBar:{a:l.wob,f:function(a){this.TDb(d.Ba(a))}},ShroudColor:{a:function(){return this.bsb()?d.ed:b.sg(this.Hga)},f:function(a){a===d.ed?this.etd():this.TNa(b.Vf(d.ja(a)))}},ShroudOpacity:{a:l.k1c,f:function(a){this.Hsc(d.L(a))}},CloseButton:{a:l.PXa,f:function(a){this.brc(d.Ba(a))}},CloseImage:{a:l.B1b,f:l.Nma},TitleImage:{a:l.h2c,f:l.UDb},ShroudStyle:{a:l.l1c,f:l.Isc},ShroudStyles:{a:l.m1c},
TitleBarThemeDrawStyle:{a:l.g2c,f:function(a){this.fud(d.ja(a))}},IsOpen:{a:l.Lh}},hc:{ShowPopup:function(b,c,e,f,g){this.fea(b===p?p:d.L(b),c===p?p:d.L(c),e===p||""==e?p:d.ua(e,a.nh.tcd),f===p||""==f?p:d.ua(f,a.Vg.v),g)},ClosePopup:l.Bo}});c.jwb=function(d){q.J.call(this,d);this.Mb=b.Kf(0,0,300,30);this.mEa=a.qya.Afd;this.sSa=new c.Lw;this.v9=this.OP=this.NP=null;this.mY=[];this.kcb=null;b.ko(this.sSa);b.jo(this.sSa);this.Wp(this.sSa);this.Ne(!1);this.v9=new c.v1a;this.v9.DNa(a.zO.Alc);this.v9.ya(this,
a.O.Yy,this.fNc);this.NP=new c.Yt;this.NP.Na(this);this.NP.rb(new c.pa);this.NP.ya(this,a.O.qc,this.gNc);this.NP.BX();this.kcb=new c.ghc(this)};var q=c.q(c.jwb,c.Xl);q.kb=function(){q.j.kb.call(this)};q.Q=function(){q.j.Q.call(this);b.fa(this.kcb);this.kcb=null};q.cWc=function(){return this.OP};q.crc=function(b){this.OP!=b&&(null!=this.OP&&(this.OP.Ga(this,this.IVb),this.OP.ub()),this.OP=b,null!=this.OP&&(this.OP.Aa(),this.OP.Ha(this,this.IVb)),this.wb(),this.l(a.g.i))};q.Zsd=function(b){b=this.wg&
~a.qya.lzb|(b?a.qya.lzb:0);this.mEa!=b&&(this.mEa=b,this.l(a.g.i))};q.fob=function(){return 0!=(this.mEa&a.qya.lzb)};q.spd=function(b){this.QXa()!=b&&(this.mEa=this.mEa&~a.qya.Zmc|b,this.wb(),this.uE(),this.Bnc(this.uf()),this.na(a.g.i))};q.QXa=function(){return this.mEa&a.qya.Zmc};q.mmb=function(){var b=null;switch(this.QXa()){case a.UQ.khb:case a.UQ.ihb:b=q.j.mmb.call(this);break;case a.UQ.ehb:d.Ob("PRIM_PCOL"),b=new c.Mvb(this.v9),b=new c.t6(b)}return b};q.Me=function(b){""==b[0]&&(b[0]=a.eac);
""==b[1]&&(b[1]=a.p$c);q.j.Me.call(this,b)};q.Mzb=function(){this.Wp(this.sSa)};q.Ox=function(c,d){q.j.Ox.call(this,c,d);this.Mzb();b.hhc(this,this.sSa,a.Ka.Sk,a.ma.VD,a.sa.Kk,this.Dib)};q.hf=function(a){q.j.hf.call(this,a);this.Bnc(a)};q.Bnc=function(d){switch(this.QXa()){case a.UQ.khb:for(this.NP.zb(!1);0<this.mY.length;)this.mY[0].is();break;case a.UQ.ihb:for(var e=this.mY.length,f=0,g=null,k=this.Fs,l=k.length-1;0<=l&&null!=(g=k[l]);l--)f=Math.max(f,g.Mb.Ja()),g.Rt()>d.Ja()&&(b.fhc(this,g),e++);
k=this.mY;for(l=0;l<k.length&&null!=(g=k[l]);l++)f+g.fb.Ta()<d.Ja()?(g.is(),l--,e--):g.la().Td(l+1);if(0<e)this.NP.Jj(this.OP?this.OP:a.nc.Vxb),this.NP.rb(new c.pa(d.Ja()-(d.ka()+2),0,d.ka(),d.ka())),this.NP.zb(!0),this.v9.o3a();else for(this.NP.zb(!1);0<this.mY.length;)this.mY[0].is();break;case a.UQ.ehb:for(;0<this.Fs.length;)b.fhc(this,this.Fs[this.Fs.length-1]);this.NP.Jj(this.OP?this.OP:a.nc.Vxb);this.NP.rb(new c.pa(d.Ja()-(d.ka()+2),0,d.ka(),d.ka()));this.NP.zb(!0);this.v9.o3a()}this.Wb()&&
this.gh()};b.hhc=function(c,d,e,f,g,k){for(var l=null,p=c.Fs,q=1,s=0;s<p.length&&null!=(l=p[s]);s++,q++){var v=d.Hg(l);v||(v=b.Oc(d,l,d.Cc(0),d.Lc(0),1,1),l.ya(c,a.O.UI,k));v.li(e);v.Vb(f);v.bc(g)}};q.IVb=function(b,c){switch(c.cb){case a.g.Bb:case a.g.Ub:this.crc(null);break;case a.g.i:this.wb()}};q.fNc=function(b,c){this.Fa(a.O.Yy,c)};q.gNc=function(b,d){this.v9.oD(a.nh.Nx,this,new c.od(this.St()+this.Ta()-this.v9.Ta(),this.Tt()+this.Ma()),this);d.qk("HANDLED",!0)};q.Dib=function(a){this.fob()&&
(a=a instanceof c.pla?a:null)&&a.HC()&&!a.HC().Lh()&&(a.hu(),this.kcb.Th())};d.Ra(c.jwb,"PRIM_PPNL","MenuBar",{za:{CollapsedMenuImage:{a:q.cWc,f:q.crc},ShowOnHover:{a:q.fob,f:function(a){this.Zsd(d.Ba(a))}},CollapseStyle:{a:function(){return d.va(this.QXa(),a.UQ.v)},f:function(b){this.spd(d.ua(b,a.UQ.v))}}}});c.ghc=function(a){s.J.call(this,500);this.gZ=a};var s=c.q(c.ghc,c.d1);s.H_=function(){if(this.gZ.fob()){var a=!1,c=!1,d=b.aa().mzb(b.Un());d?a=!0:(d=b.TW(b.Un()))&&(d==this.gZ||d.Ts(this.gZ))&&
(a=!0);!a&&(d=b.aa().GE(b.pO()))&&(c=a=!0);a||(this.gZ.Ay(),c=!0);c&&this.mi()}return!1};c.v1a=function(){k.J.call(this);this.Mb=b.Kf(0,0,150,150);this.Bi=new c.Lw;this.pz=a.Wxb.LLa;b.ko(this.Bi);b.jo(this.Bi);this.Wp(this.Bi)};var k=c.q(c.v1a,c.Kx);k.kb=function(){k.j.kb.call(this)};k.Q=function(){k.j.Q.call(this)};k.DNa=function(b){this.oIa()!=b&&(this.pz=this.pz&~a.Wxb.Elc|b,this.wb(),this.na(a.g.i))};k.oIa=function(){return this.pz&a.Wxb.Elc};k.Me=function(b){""==b[0]&&(b[0]=a.gac);""==b[1]&&
(b[1]=a.q$c);k.j.Me.call(this,b)};k.Mzb=function(){this.Wp(this.Bi);this.Ida(!0)};k.Ox=function(c,d){k.j.Ox.call(this,c,d);this.Mzb();b.hhc(this,this.Bi,a.Ka.Rj,a.ma.gp,a.sa.bi,this.Dib)};k.o3a=function(){if(this.oIa()!=a.zO.Uca){for(var b=null,d=this.Fs,e=[!0,2,2,0,0],f=0;f<d.length&&null!=(b=d[f]);f++){var g=b instanceof c.pla?b:null;switch(this.oIa()){case a.zO.Vxa:g?g.Rnc(e):e[2]+=b.yb()?b.Ma():0;break;case a.zO.Alc:e[1]=Math.max(e[1],b.Ta()),e[2]+=b.yb()?b.Ma():0}}for(f=0;f<d.length&&null!=(b=
d[f]);f++)switch(this.oIa()){case a.zO.Vxa:(g=b instanceof c.pla?b:null)&&g.oc(e[1])}this.oc(e[1]);this.wc(e[2])}};k.mda=function(a){this.o3a();return k.j.mda.call(this,a)};k.hf=function(a){k.j.hf.call(this,a)};k.PVb=k[a.ca.Wsb]=function(a){k.j.PVb.call(this,a);this.o3a()};k.Dib=function(a){(a=a instanceof c.pla?a:null)&&a.hu()};d.Ra(c.v1a,"PRIM_PPNL","Menu",{za:{MenuSizing:{a:function(){return d.va(this.oIa(),a.zO.v)},f:function(b){this.DNa(d.ua(b,a.zO.v))}}}});c.ihc=function(a){e.J.call(this);this.r$=
a};var e=c.q(c.ihc,c.tO);e.t9b=function(){return!0};e.ngb=function(a,b){return e.j.ngb.call(this,a,b,this.r$)};e.Me=function(){};c.pla=function(){g.J.call(this);this.Mb=b.Kf(0,0,100,25);this.ega=a.zla.O6;this.rv=0;this.Lbb=this.oNb=this.Yo=this.dU=this.l$=this.UY=this.yQ=null;this.m$=new c.Lw;this.ny=0;this.NM=a.Gc.TC;b.ko(this.m$);b.jo(this.m$);this.Wp(this.m$);this.wNa(!0);this.dU=new c.xb;this.dU.cr(a.m.xe);this.dU.Uj(a.m.xe);this.dU.rq(1);this.dU.dr(1);this.dU.Lo(1);this.dU.Mo(1);this.l$=new c.Yt;
this.l$.Na(this);this.l$.rb(new c.pa(0,0,18,18));this.l$.Ib(this.dU);this.Yo=new c.ihc(this);this.Yo.Na(this);this.Yo.zf(2);this.Yo.ue(2);this.oNb=b.Oc(this.m$,this.Yo,this.m$.Cc(0),this.m$.Lc(0),1,1);this.Lbb=b.Oc(this.m$,this.l$,this.m$.Cc(0),this.m$.Lc(0),1,1)};var g=c.q(c.pla,c.Xl);g.kb=function(){g.j.kb.call(this)};g.Q=function(){g.j.Q.call(this);this.c5a(null)};g.HC=function(){return this.Yo.HC()};g.z7=function(b){this.HC()!=b&&(this.Yo.HC()&&this.Yo.HC().Up(this,a.O.Yy,this.EWb),this.Yo.z7(b),
this.Yo.HC()&&this.Yo.HC().ya(this,a.O.Yy,this.EWb),this.l(a.g.i))};g.wba=function(){return this.Yo.wba()};g.YYc=function(){return this.UY};g.c5a=function(b){this.UY!=b&&(null!=this.UY&&(this.UY.Ga(this,this.DWb),this.UY.ub()),this.UY=b,null!=this.UY&&(this.UY.Aa(),this.UY.Ha(this,this.DWb)),this.Eu(),this.l(a.g.i))};g.Iv=function(){return this.ny};g.cu=function(b){b!=this.ny&&(this.ny=b,this.Eu(),this.na(a.g.i))};g.fu=function(b){this.NM!=b&&(this.NM=b,this.Eu(),this.na(a.g.i))};g.Hf=function(){return this.Yo.Hf()};
g.Cf=function(b){this.Hf()!=b&&(this.Yo.Cf(b),this.l(a.g.i))};g.Pf=function(){return this.Yo.Pf()};g.zf=function(b){this.Pf()!=b&&(this.Yo.zf(b),this.l(a.g.i))};g.Tg=function(){return this.Yo.Tg()};g.ue=function(b){this.Tg()!=b&&(this.Yo.ue(b),this.l(a.g.i))};g.Xg=function(){return this.Yo.Xg()};g.hg=function(b){this.Xg()!=b&&(this.Yo.hg(b),this.l(a.g.i))};g.ym=function(){return this.NM};g.Sja=function(){return 0!=(this.ega&a.zla.$W)?!0:!1};g.MNa=function(b){b=this.ega&~a.zla.$W|(b?a.zla.$W:0);this.ega!=
b&&(this.ega=b,this.Eu(),this.na(a.g.i))};g.Yg=function(){return 0!=(this.ega&a.zla.ZW)?!0:!1};g.Ci=function(b){var d=this.jI();if(b&&0!=d&&null!=this.U())for(var e=null,f=this.U().mg,g=0;g<f.length&&null!=(e=f[g]);g++)if(e instanceof c.pla){var k=e;k!=this&&k.jI()==d&&k.Ci(!1)}b=this.ega&~a.zla.ZW|(b?a.zla.ZW:0);this.ega!=b&&(this.ega=b,this.Eu(),this.na(a.g.i))};g.jI=function(){return this.rv};g.u7=function(b){this.rv!=b&&(this.rv=b,this.Eu(),this.na(a.g.i))};g.nob=function(){return this.yQ};g.X5a=
function(a){this.yQ!=a&&(this.yQ=a)};g.Me=function(b){""==b[0]&&(b[0]=a.dac);g.j.Me.call(this,b)};g.hu=function(){var a=b.aa().GE(this);(null==a||a.Lh())&&this.HC()&&!this.HC().Lh()&&this.Yo.jHb(!0)};g.rJa=function(){var a=b.aa().GE(this);(null==a||a.Lh())&&this.HC()&&this.HC().Lh()&&this.Yo.jHb(!0)};g.Rnc=function(b){var d=null,e=this.cc&&this.cc instanceof c.jwb?this.cc:null,f=this.ny;this.Yg()?(d=this.Sja()?a.nc.vlc:a.nc.ulc,this.dU.cr(a.m.nT),this.dU.Uj(a.m.rea)):(this.dU.cr(a.m.xe),this.dU.Uj(a.m.xe));
this.UY&&(d=this.UY);d&&0==f&&(f=Math.min(this.Ma(),d.Ma()));this.Yo.Pb(a.U$c);this.Yo.OS(!1);this.Yo.fu(this.ym());this.Yo.p5a(e?a.TI.FLa:a.TI.GLa);this.Yo.cDb(e?a.oq.Uca:a.oq.Wxa);this.Yo.HL(a.Vw.PQ);this.Yo.Jza(!1);this.Yo.sb(this.$a());this.Yo.Oo(a.bh.wq);this.l$.Jj(d);this.l$.rb(new c.pa(this.l$.te(),this.l$.Qe(),f,f));this.oNb.bc(a.sa.Og);this.oNb.zf(e?0:f+2);this.Lbb.bc(a.sa.rf);this.Lbb.Vb(a.ma.Iq);this.Lbb.zf(e?0:2);this.Yo.pk(!1,!0);var g=this.Yo.kN(),k=this.Yo.gja();e?(g+=f+4,d&&(g+=f+
4)):(g+=60,k+=10);!0==b[0]&&(this.wc(k),b[1]=Math.max(b[1],g),b[2]+=this.yb()?k:0,b[3]+=g,b[4]+=k)};g.Ox=function(a,b){g.j.Ox.call(this,a,b);this.Rnc([!1,0,0])};g.of=function(a){var d=!1;this.jI()&&this.Ci(!0);d=g.j.of.call(this,a);if(!d){a=b.aa().qz;for(var e=null,f=0;f<a.length&&null!=(e=a[f]);f++)e instanceof c.v1a&&b.aa().Cu(e,!1)}return d};g.EWb=function(a,b){b.Bsd(this)};g.DWb=function(b,c){switch(c.cb){case a.g.Bb:case a.g.Ub:this.c5a(null);break;case a.g.i:this.Eu()}};d.Ra(c.pla,"PRIM_PPNL",
"MenuItem",{za:{Checked:{a:g.Yg,f:function(a){this.Ci(d.Ba(a))}},MenuPopup:{a:g.HC,f:g.z7},RadioItem:{a:g.Sja,f:function(a){this.MNa(d.Ba(a))}},GroupIndex:{a:g.jI,f:function(a){this.u7(d.L(a))}},Image:{a:g.YYc,f:g.c5a},ImageHeight:{a:g.Iv,f:function(a){this.cu(d.L(a))}},MarginLeft:{a:g.Pf,f:function(a){this.zf(d.L(a))}},MarginTop:{a:g.Hf,f:function(a){this.Cf(d.L(a))}},MarginBottom:{a:g.Xg,f:function(a){this.hg(d.L(a))}},MarginRight:{a:g.Tg,f:function(a){this.ue(d.L(a))}},Alignment:{a:function(){return d.va(this.ym(),
a.Gc.QQ)},f:function(b){this.fu(d.ua(b,a.Gc.QQ))}}},hc:{ShowMenu:g.hu,HideMenu:g.rJa}});c.ehc=function(a,b,c){f.J.call(this);this.gZ=a;this.fb=b;this.GHd=b.qg();-1==c&&(c=this.gZ.mY.length);this.gZ.mY.splice(c,0,this);this.fb.Ha(this,this.Cv);this.fb.Na(a.v9)};var f=c.q(c.ehc,c.Ad);f.Q=function(){var a=this.gZ.Fs.length+1;this.fb.Ga(this,this.Cv);this.gZ.mY.splice(this.gZ.mY.indexOf(this),1);this.fb.Hb(this.gZ);this.fb.Td(a);this.fb.rb(this.GHd);f.j.Q.call(this)};f.la=function(){return this.fb};b.fhc=
function(a,b){-1==a.mY.indexOf(b)&&new c.ehc(a,b,0)};f.ip=function(b,c){switch(c.cb){case a.g.Bb:this.is()}};c.mkc=function(a){v.J.call(this,a);this.URa=!1;this.nC=null;this.wA="";this.lEa=null;this.Yga=0};var v=c.q(c.mkc,c.tL);v.j4c=function(){var b=!1,c=d.va(this.K.MA,a.Vg.YZb);if("md-effect-17"==c||"md-effect-18"==c||"md-effect-19"==c)b=!0;return b};v.Fd=function(a){var c=this;this.u=document.createElement("div");this.u.setAttribute("id",a+this.gc);this.u.setAttribute("LANSAHandle",this.gc);this.nC=
document.createElement("div");this.nC.setAttribute("LANSAHandle",this.gc);c.nC.addEventListener("click",function(a){a=b.Xt(b.rba(a.target||a.srcElement));c.K&&a.opb()&&c.K.NJa()&&b.aa().Cu(c.K,!1)},!1);return this.u};v.Eea=function(){this.$Fa()};v.JIb=function(b){this.wA=d.va(this.K.MA,a.Vg.YZb);null!=this.lEa&&(b=this.lEa);9999<b&&(""==this.wA?v.j.JIb.call(this,b):this.nC.style.zIndex=b)};v.Zm=function(a,c,d,e){a=b.Qi(a,c,d,e);this.K.s0()&&a.PA(this.K.U().YSb(a));v.j.Zm.call(this,a.$(),a.Z(),a.ha(),
a.ka())};v.Zza=function(){var d=this;this.K.utc(this.K.Kua().uI());if(""!=this.wA||this.K.xf()){if(1==this.Yga&&this.R3a(),0==this.Yga){this.Yga=2;b.aa().An.Sa().u.classList.add("container");if(this.K.xf())if(this.nC.style.left="0px",this.nC.style.right="0px",this.nC.style.height="100vh",this.nC.style.display="flex",this.nC.style.alignItems="center",this.nC.style.justifyContent="center",this.nC.style.zIndex=this.lEa,null!=this.K.uU&&this.K.EM==a.nh.Yla){var e=[];b.$E(this.K.uU.Za(),e);this.u.style.position=
"absolute";this.u.style.left=e[0]+"px";this.u.style.top=Number(e[1])+Number(e[3])+"px"}else this.K.EM==a.nh.Nx?(this.u.style.position="absolute",this.u.style.left=this.K.te()+"px",this.u.style.top=this.K.Qe()+"px"):(this.u.style.position="",this.u.style.left="",this.u.style.top="");this.nC.setAttribute("class","md-modal "+this.wA);e=b.ke[this.K.Gb().Sa().Za()];e.u.style.opacity="";e.u.setAttribute("class","md-content vl-control vl-popup");this.nC.appendChild(this.u);document.body.insertBefore(this.nC,
b.aa().An.Sa().u);this.K.xf()&&"absolute"==this.u.style.position&&(e=[],b.$E(this.K.Za(),e),0!=e[2]&&0!=e[3]&&(e=new c.pa(e[0],e[1],e[2],e[3]),b.h1a(e),this.u.style.left=e.$()+"px",this.u.style.top=e.Z()+"px"));this.j4c()&&setTimeout(function(){document.documentElement.classList.add("md-perspective")},25);setTimeout(function(){d.nC.classList.add("md-show");setTimeout(function(){d.K&&d.K.$nc()},300)},100)}}else 2==this.Yga&&this.R3a(),0==this.Yga&&(this.Yga=1,document.body.appendChild(this.u));this.URa=
!0};v.$Fa=function(){this.URa&&(this.URa=!1,this.nC.classList.contains("md-show")?this.Yoc():this.R3a(),this.K.W4c())};v.R3a=function(){document.documentElement.classList.contains("md-perspective")&&document.documentElement.classList.remove("md-perspective");switch(this.Yga){case 1:this.K.xf()?this.K.ap.removeChild(this.u):document.body.removeChild(this.u);break;case 2:document.body.removeChild(this.nC),this.nC.removeChild(this.u),b.aa().An.Sa().u.classList.remove("container")}this.Yga=0};v.Yoc=function(){var a=
this;this.nC.classList.remove("md-show");setTimeout(function(){a.R3a()},500)};v.$$d=function(){this.Yoc()}},{rp:["PRIM_PHBN","PRIM_IMAG","PRIM_TBLO"]});
