window.LANSA.addSrc("wrtn",function(d,c,a,b,p){function t(a){return null===a?d.ed:"object"==typeof a?a.mimetype&&a.data&&a.filename?new c.NI(a):"":a}function l(a){if(a===d.ed)return null;switch(typeof a){case "object":if(a instanceof c.mk)return a.toString();if(c.Wq&&a instanceof c.Wq)return a.Zvc();if(a instanceof c.NI)return a.GDa}return a}function q(b,c,d){var e=document.createElement("form");e.setAttribute("method","post");e.setAttribute("action",b);d==a.q2.Cuc&&e.setAttribute("target","_blank");
for(var f in c)c.hasOwnProperty(f)&&(b=document.createElement("input"),b.setAttribute("type","hidden"),b.setAttribute("name",f),b.setAttribute("value",c[f]),e.appendChild(b));document.body.appendChild(e);e.submit()}function s(a){return(a=a.sm)&&"M"==a}function k(a,b){v&&b.append("_SESSIONKEY",v);var e=a.FLD;if(e!==p)for(var f in e){var g=e[f];if(g===d.ed)return!1;g instanceof c.NI?b.append(f,g.vua(),g.Jg()):b.append(f,l(g))}e=a.LIST;if(e!==p)for(var n in e){for(var k=e[n],r=k.Yp={},q=k.entryCount(),
s=1;s<=q;s++)for(f in k.getEntry(s),1==s&&b.append(n+"..",1),r){g=s.toString();4>g.length&&(g="000"+g,g=g.substr(g.length-4));var t=n+"."+g+"."+f,g=r[f];if(g===d.ed)return delete k.Yp,!1;g instanceof c.NI?b.append(t,g.vua(),g.Jg()):b.append(t,l(g))}delete k.Yp}return!0}function e(a,b){var c=b.webroutine={},d=c.context={};v&&(d["session-key"]=v);B&&(d["session-key-name"]=B);n&&(d["session-key-method"]=n);d=a.FLD;if(d!==p){var e=c.fields={},f;for(f in d)(e[f]={}).value=l(d[f])}d=a.LIST;if(d!==p){var c=
c.lists={},g;for(g in d){for(var k=c[g]={},e=k.header=[],k=k.entries=[],r=d[g],q=r.Yp={},s=r.entryCount(),t=1;t<=s;t++){r.getEntry(t);if(1==t)for(f in q){var E={};e.push(E);E.name=f}E=[];k.push(E);for(f in q)E.push(l(q[f]))}delete r.Yp}}}function g(a){if(a=a.context){var b=a["session-key"];b!=p&&""!=b&&b!=v&&b!=r&&(r=v,v=b,B=a["session-key-name"],n=a["session-key-method"])}}function f(a,b,c){function e(a){if(a!=p){var b=a.FLD;f(a.LIST);f(b)}}function f(b){if(b!=p)for(var c in b)if(null===b[c])throw d.qjd(c,
a.tEa,a.sEa);}e(b);e(c)}var v=p,B=p,n="hidden",r=p;a.q2={cGb:0,Cuc:1};a.q2.v={CURRENT:a.q2.cGb,NEW:a.q2.Cuc};d.Kd(function(){},"PRIM_WRTN",{});c.Yic=function(){E.J.call(this)};var E=c.q(c.Yic,c.Ad);E.l5=function(){return v!==p?v:""};E.g5a=function(a){v=a;r=p};E.wBb=function(){var a=b.Hl().BYa();if(a.Rta()){var c="lansa-session-"+b.EYa(),d=JSON.stringify({key:this.l5()});if(a.ri(c,d))return!0}return!1};E.gBb=function(){var a=b.Hl().BYa();if(a.Rta()&&(a=a.lI("lansa-session-"+b.EYa()))){var c=null;try{c=
JSON.parse(a.jb())}catch(d){c=null}if(c)return this.g5a(c.key),!0}return!1};E.Tl=function(){var a=b.Hl().BYa();a.Rta()&&a.Qu("lansa-session-"+b.EYa());n=B=v=p};d.Ra(c.Yic,"PRIM_WEB","Session",{za:{Key:{a:E.l5}},hc:{Save:E.wBb,Restore:E.gBb,Clear:E.Tl}});c.CLa=function(a,b){C.J.call(this);this.tEa=a;this.sEa=b;this.bOb=this.eNb=""};var C=c.q(c.CLa,c.Ad);C.XWd=function(){return this.eNb};C.ree=function(a){this.eNb=a};C.oZd=function(){return this.bOb};C.Fee=function(a){this.bOb=a};C.e1c=function(){return this.tEa};
C.M0c=function(){return this.sEa};C.Sz=function(){return b.ZKc(this.eNb,b.NHa(),this.tEa,this.sEa,this.z0c())};C.z0c=function(){var a=this.bOb;""==a&&(a=b.YXa());return a};d.Ra(c.CLa,"PRIM_WEB","ServerRequest",{za:{ServerModule:{a:C.e1c},Routine:{a:C.M0c}}});c.lxa=function(a,b){x.J.call(this,a,b)};var x=c.q(c.lxa,c.CLa);x.G_=function(a,b){this.N_b(a,b,!1,null)};x.D4=function(a,c){this.N_b(a,c,!0,b.LX())};x.N_b=function(c,l,r,q){function E(c){var e=null;try{e=JSON.parse(c)}catch(f){e=null}if(e){if(c=
e.webroutine)if(c=c.messages)for(var k=d.n_c(),r=0;r<c.length;r++)k.ri(c[r],null);if(c=e["vlweb-error"]){var s=a.dY.oXa;switch(c["message-id"]){case "HM42":case "HM43":s=a.dY.Q0b;n=B=v=p;break;case "HM05":s=a.dY.P0b}s=I.nHa(s);if(!s&&c.message!==p)throw d.QAb(I.tEa,I.sEa,c.message);}else{k=l;if(e=e.webroutine){r=k.FLD;if(r!==p){var x=e.fields;if(x)for(var C in r)c=x[C],c!==p&&(c=t(c.value),r[C].set(c))}C=k.LIST;if(C!==p&&(k=e.lists))for(s in C)if(r=C[s],r.Pj(),c=k[s])for(var x=c.header,y=c.entries,
z=0;z<y.length;z++){for(var D=r.Yp={},K=y[z],L=0;L<K.length;L++)c=t(K[L]),D[x[L].name]=c;r.Rg();delete r.Yp}g(e)}I.I4()}}else if(s=I.nHa(a.dY.oXa),!s)throw d.QAb(I.tEa,I.sEa,"Invalid JSON");b.wB(q)}function x(c){if(!I.nHa(a.dY.oXa))throw d.QAb(I.tEa,I.sEa,"response code "+c);b.wB(q)}function C(a){a.lengthComputable&&I.$Tc(a.loaded,a.total,d.L(a.loaded/a.total*100))}function K(a){if(a.lengthComputable){var b=a.loaded/a.total*100;I.s0b(a.loaded,a.total,d.L(b))}else I.s0b(a.loaded,-1,-1)}var I=this;
f(I,c,l);if(s(c)){var L=new FormData;if(k(c,L)){b.bgd(this.Sz(),L,E,x,C,K,r);return}}L={};e(c,L);b.onc(this.Sz(),L,E,x,C,K,r)};x.nHa=function(c){var e=!1,e=d.fc();e.JQ("REASON",c,a.dY.v);e.og("HANDLED",!1);this.Fa(a.O.H4,e);(e=e.dh("HANDLED"))||(e=b.Hl().STc(this,c));return e};x.I4=function(){this.Fa(a.O.laa)};x.$Tc=function(b,c,e){var f=d.fc();f.FF("LOADED",b);f.FF("TOTAL",c);f.FF("PROGRESS",e);this.Fa(a.O.vFd,f)};x.s0b=function(b,c,e){var f=d.fc();f.FF("LOADED",b);f.FF("TOTAL",c);f.FF("PROGRESS",
e);this.Fa(a.O.pRc,f)};d.Ra(c.lxa,"PRIM_WEB","DataRequest",{hc:{Execute:x.G_,ExecuteAsync:x.D4}});c.Gxa=function(b,c){K.J.call(this,b,c);this.Fn=a.q2.cGb};var K=c.q(c.Gxa,c.CLa);K.N1c=function(){return this.Fn};K.SDb=function(a){this.Fn=a};K.G_=function(a,b){f(this,a,b);var c={};v&&(c._SESSIONKEY=v);var d=a.FLD;if(d!==p)for(var e in d)c[e]=l(d[e]);d=a.LIST;if(d!==p)for(var g in d){for(var n=d[g],k=n.Yp={},r=n.entryCount(),s=1;s<=r;s++)for(e in n.getEntry(s),1==s&&(c[g+".."]=1),k){var t=s.toString();
4>t.length&&(t="000"+t,t=t.substr(t.length-4));c[g+"."+t+"."+e]=l(k[e])}delete n.Yp}q(this.Sz(),c,this.Fn)};d.Ra(c.Gxa,"PRIM_WEB","WebPageRequest",{za:{Target:{a:function(){return d.va(this.Fn,a.q2.v)},f:function(b){this.SDb(d.ua(b,a.q2.v))}}},hc:{Execute:K.G_}});c.yxa=function(b,c){I.J.call(this,b,c);this.Fn=a.q2.cGb};var I=c.q(c.yxa,c.CLa);I.N1c=function(){return this.Fn};I.SDb=function(a){this.Fn=a};I.G_=function(a,b){f(this,a,b);var c={};v&&(c._SESSIONKEY=v);var d=a.FLD;if(d!==p)for(var e in d)c[e]=
l(d[e]);d=a.LIST;if(d!==p)for(var g in d){for(var n=d[g],k=n.Yp={},r=n.entryCount(),s=1;s<=r;s++)for(e in n.getEntry(s),1==s&&(c[g+".."]=1),k){var t=s.toString();4>t.length&&(t="000"+t,t=t.substr(t.length-4));c[g+"."+t+"."+e]=l(k[e])}delete n.Yp}q(this.Sz(),c,this.Fn)};d.Ra(c.yxa,"PRIM_WEB","ResourceRequest",{za:{Target:{a:function(){return d.va(this.Fn,a.q2.v)},f:function(b){this.SDb(d.ua(b,a.q2.v))}}},hc:{Execute:I.G_}});b.MSc=function(b,c){var d=c.webroutine;if(d){var e=b.nz.iIa(),f=d.fields;if(f){var g=
b.bNa(e),n;for(n in f){var k=null,l=b.dm[n];l&&(k=l.WZ());if(!k&&g)for(var p in g)if(l=g[p],l.Kh()==n){k=l;break}k&&(l=t(f[n].value),k.set(l))}}if(d=d.lists){var e=b.Bkd(e),r;for(r in d){f=null;if(l=b.dm[r])switch(l.$ta()){case a.By.czc:case a.By.Q8a:case a.By.Agb:f=l}!f&&e&&(f=e[r]);if(f)for(l=d[r],g=l.header,n=l.entries,k=0;k<n.length;k++){p=f.Yp={};for(var q=n[k],s=0;s<q.length;s++)l=t(q[s]),p[g[s].name]=l;f.Rg();delete f.Yp}}}}};b.LSc=function(a){(a=a.webroutine)&&g(a)}});
