window.LANSA.addSrc("coll",function(d,c,a,b,p){a.L_a={AJc:0,Lkb:1};var t=0;c.Xwa=function(){l.J.call(this)};var l=c.q(c.Xwa,c.Ad);l.qRb=function(){return!1};l.s8b=function(){return!1};l.Jc=function(){return 0};l.$g=function(){return 0==this.Jc()};l.e4=function(a){a&&(a.Aa(),a.ZDc(this))};l.v4=function(a){a&&(a.ub(),a.Nid(this))};l.Z6=function(a,b){this.e3a(b);null!=this.oz&&this.oz.Z6(a,b)};l.jda=function(a,b){this.f3a(b);null!=this.oz&&this.oz.jda(a,b)};d.Kd(c.Xwa,"PRIM_COLL",{za:{AllowsDuplicates:{a:function(){return this.qRb()}},
IsEmpty:{a:function(){return this.$g()}},IsOrdered:{a:function(){return this.s8b()}},ItemCount:{a:function(){return this.Jc()}}}});c.M0a=function(){q.J.call(this);this.mb=[];this.oz=null};var q=c.q(c.M0a,c.Xwa);q.Q=function(){this.Il();q.j.Q.call(this)};q.qRb=function(){return!0};q.s8b=function(){return!0};q.Jc=function(){return this.mb.length};q.se=function(a){if(0>a||a>=this.mb.length)throw d.fD(a,this.mb.length);return this.mb[a]};q.Kl=function(a,b){if(0>a||a>this.mb.length)throw d.fD(a,this.mb.length);
a==this.mb.length?this.qs(b):this.MAb(b,a)};q.Ymb=function(a,b){return b===p?this.mb.indexOf(a):this.mb.indexOf(a,b)};q.R2b=function(a){return this.mb.lastIndexOf(a)+1};q.Omb=function(){return 0<this.mb.length?this.mb[0]:null};q.jnb=function(){return 0<this.mb.length?this.mb[this.mb.length-1]:null};q.USd=function(){return this.hpa};q.q7=function(a){this.hpa=a};q.DUa=function(a){this.q7(a.Hoc())};q.Ve=function(a){return-1!=this.mb.indexOf(a)};q.qs=q.l7b=function(a){this.e4(a);this.mb.push(a);this.Z6(a,
this.Jc()-1)};q.k7b=function(a){this.e4(a);this.mb.unshift(a);this.Z6(a,0)};q.j7b=function(a,b){if(0>b||b>=this.mb.length)throw d.fD(b,this.mb.length);this.e4(a);this.mb.splice(b+1,0,a);this.Z6(a,b+1)};q.Hqb=function(a,b){if(0>b||b>=this.mb.length)throw d.fD(b,this.mb.length);this.e4(a);this.mb.splice(b,0,a);this.Z6(a,b)};q.Qu=function(a){a=this.mb.indexOf(a);if(-1==a)throw d.ljd();return this.vs(a)};q.vs=function(a){if(0>a||a>=this.mb.length)throw d.fD(a,this.mb.length);var b=this.mb[a];this.mb.splice(a,
1);d.ssa(b);this.v4(b);this.jda(b,a);return b};q.FAb=function(){return this.vs(0)};q.HAb=function(){return this.vs(this.mb.length-1)};q.Il=function(){for(var a=0;a<this.mb.length;a++)this.v4(this.mb[a]);this.mb=[];this.bma()};q.Eyb=function(a){for(var b=0,c=0;c<this.mb.length;c++)this.mb[c]===a&&b++;return b};q.MAb=function(a,b){if(0>b||b>=this.mb.length)throw d.fD(b,this.mb.length);var c=this.mb[b];d.ssa(c);this.v4(c);this.mb[b]=a;this.e4(a);return c};q.Rg=function(){var a=d.lib(this.hpa);if(a=d.Bc(a.J2a,
a.XX))this.Qxa(a),this.qs(a)};q.Pj=function(){this.Il()};q.Bh=function(a){if(0<=a&&a<this.Jc()){var b=this.se(a);b&&this.xla(b);this.Bn=a;return"OK"}this.Bn=-1;return"NR"};q.jp=function(){return this.Jc()};q.Mm=function(a){a===p&&(a=this.Bn);0<=a&&a<this.Jc()&&this.vs(a)};q.ul=function(){var a=this.Bn;0<=a&&a<this.Jc()&&(a=this.se(a))&&this.Qxa(a)};q.pn=function(a,b,c){for(var d=0;d<this.Jc();d++){var e=this.se(d);if(e&&(e=e.J5())){var f={},g;for(g in e)f[g]=e[g].get();if(a(f))return null!=b&&b.set(d+
1),c&&this.Bh(d),this.Bn=d,"OK"}}return"NR"};q.Tq=function(a){this.Il();for(var b=0;b<a;b++)this.Rg()};q.ys=function(){return new c.R0a(this)};q.Yya=function(){null==this.oz&&(this.oz=new c.pec);return this.oz};c.pec=function(){s.J.call(this)};var s=c.q(c.pec,c.S0a);c.kec=function(){k.J.call(this);this.Bn=-1};var k=c.q(c.kec,c.M0a);k.Q_=function(){return"PRIM_LCOL<"+this.hpa+">"};k.ZEc=function(a){for(var b=0;b<a.Jc();b++)this.qs(a.se(b))};k.MJc=function(a){for(var b=d.Bc("PRIM_LCOL"),c=0;c<this.Jc();c++)b.qs(this.se(c));
for(c=0;c<a.Jc();c++)b.qs(a.se(c));d.ssa(b);return b};d.Kd(c.kec,"PRIM_LCOL",{LS:a.By.Agb,za:{First:{a:function(){return this.Omb()}},Last:{a:function(){return this.jnb()}},Item:{a:function(a){return this.se(d.L(a)-1)},f:function(a,b){this.Kl(d.L(a)-1,b)}},IndexOf:{a:function(a,b){return this.Ymb(a,b===p?p:d.L(b)-1)+1}},LastIndexOf:{a:k.R2b},Collects:{f:k.q7}},hc:{Append:k.ZEc,Concatenate:k.MJc,Contains:k.Ve,Insert:k.qs,InsertFirst:k.k7b,InsertLast:k.l7b,InsertAfter:function(a,b){return this.j7b(a,
d.L(b)-1)},InsertBefore:function(a,b){return this.Hqb(a,d.L(b)-1)},Remove:k.Qu,RemoveAt:function(a){return this.vs(d.L(a)-1)},RemoveFirst:k.FAb,RemoveLast:k.HAb,RemoveAll:k.Il,OccurrencesOf:k.Eyb,ReplaceAt:function(a,b){return this.MAb(a,d.L(b)-1)}},cf:{af:"Item"},ts:{Fka:function(a){var b=d.Bc("PRIM_NMBR");b.set(a);return b},Qr:function(a){return this.se(d.L(a)-1)},Qy:function(){return this.Jc()}},Zz:{Rg:k.Rg,Bh:function(a){return this.Bh(d.L(a)-1)},Tq:k.Tq,Pj:k.Pj,jp:k.jp,Mm:function(a){this.Mm(a?
d.L(a)-1:p)},ul:k.ul,pn:k.pn,ys:k.ys}});c.Dac=function(){e.J.call(this)};var e=c.q(c.Dac,c.M0a);e.Q_=function(){return"PRIM_ACOL<"+this.hpa+">"};d.Kd(c.Dac,"PRIM_ACOL",{LS:a.By.Agb,za:{First:{a:function(){return this.Omb()}},Last:{a:function(){return this.jnb()}},Item:{a:function(a){return this.se(d.L(a)-1)},f:function(a,b){this.Kl(d.L(a)-1,b)}},IndexOf:{a:function(a,b){return this.Ymb(a,b===p?p:d.L(b)-1)+1}},LastIndexOf:{a:e.R2b},Collects:{f:e.q7}},hc:{Contains:e.Ve,Insert:e.qs,InsertFirst:e.k7b,
InsertLast:e.l7b,InsertAfter:function(a,b){return this.j7b(a,d.L(b)-1)},InsertBefore:function(a,b){return this.Hqb(a,d.L(b)-1)},Remove:e.Qu,RemoveAt:function(a){return this.vs(d.L(a)-1)},RemoveFirst:e.FAb,RemoveLast:e.HAb,RemoveAll:e.Il,OccurrencesOf:e.Eyb,ReplaceAt:function(a,b){return this.MAb(a,d.L(b)-1)}},cf:{af:"Item"},ts:{Fka:function(a){var b=d.Bc("PRIM_NMBR");b.set(a);return b},Qr:function(a){return this.se(d.L(a)-1)},Qy:function(){return this.Jc()}},Zz:{Rg:e.Rg,Bh:function(a){return this.Bh(d.L(a)-
1)},Tq:e.Tq,Pj:e.Pj,jp:e.jp,Mm:function(a){this.Mm(a?d.L(a)-1:p)},ul:e.ul,pn:e.pn,ys:e.ys}});c.vec=function(){g.J.call(this)};var g=c.q(c.vec,c.M0a);g.qs=function(b){this.e4(b);for(var c=0,d=this.mb.length-1;c<=d;){var e=Math.floor((c+d)/2);this.ATc(b,this.mb[e])==a.wd.Zn?d=e-1:c=e+1}this.mb.splice(c,0,b)};g.ATc=function(b,c){var e=a.wd.jm,f=d.fc();f.jc("SUBJECT",b);f.jc("OBJECT",c);f.JQ("RESULT",e,a.wd.v);this.Fa(a.O.iVa,f);e=f.Imb("RESULT",a.wd.v);f.Kc();return e};d.Kd(c.vec,"PRIM_SACO",{za:{First:{a:function(){return this.Omb()}},
Last:{a:function(){return this.jnb()}},Item:{a:function(a){return this.se(d.L(a)-1)},f:function(a,b){this.Kl(d.L(a)-1,b)}},IndexOf:{a:function(a,b){return this.Ymb(a,b===p?p:d.L(b)-1)+1}},Collects:{f:g.q7}},hc:{Remove:g.Qu,RemoveAt:function(a){return this.vs(d.L(a)-1)},RemoveAll:g.Il,RemoveLast:g.HAb,RemoveFirst:g.FAb,Contains:g.Ve,OccurrencesOf:g.Eyb,Insert:g.qs},cf:{af:"Item"},ts:{Fka:function(a){var b=d.Bc("PRIM_NMBR");b.set(a);return b},Qr:function(a){return this.se(d.L(a)-1)},Qy:function(){return this.Jc()}}});
c.t6=function(a){f.J.call(this);this.JBc=a};var f=c.q(c.t6,c.Xwa);f.se=function(a){if(0>a||a>=this.Jc())throw d.fD(a,this.Jc());return this.Mz(a)};f.Jc=function(){return this.JBc.Jc()};f.Mz=function(a){return this.JBc.Mz(a)};d.Kd(c.t6,"PRIM_PCOL",{za:{Item:{a:function(a){return this.se(d.L(a)-1)},f:function(a,b){this.Kl(d.L(a)-1,b)}}},cf:{af:"Item"},ts:{Qr:function(a){return this.Mz(d.L(a)-1)},Qy:function(){return this.Jc()}}});c.jec=function(){v.J.call(this);this.mb={};this.XY=null;this.sf=a.L_a.Lkb};
var v=c.q(c.jec,c.Xwa);v.Q=function(){this.Il();v.j.Q.call(this)};v.Q_=function(){return"PRIM_KCOL<"+this.t$a+" "+this.jZc()+">"};v.Ch=function(){return this.sf};v.Ib=function(a){this.sf=a};v.Jc=function(){return this.Fla().length};v.se=function(b){b=this.Ugb(b);if(this.mb[b]===p&&this.sf==a.L_a.Lkb){var c=null;this.yLb?c=new this.yLb:this.t$a&&(c=d.lib(this.t$a),c=d.Bc(c.J2a,c.XX));c&&(this.mb[b]=c,this.e4(c),this.DL())}return this.mb[b]};v.Kl=function(a,b){a=this.Ugb(a);var c=a.toString();this.mb[c]===
p?this.DL():this.v4(this.mb[c]);this.e4(b);this.mb[c]=b};v.Mz=function(a){a=this.Fla()[a];return this.mb[a]};v.fnb=function(a){a=this.Fla()[a];this.XY.set(a);return this.XY};v.gnb=function(a){for(var b in this.mb)if(this.mb[b]===a)return this.Xgb(b);return this.XY.H_c()};v.q7=function(a,b){"string"!==typeof a?this.yLb=a:(this.t$a=a,this.yLb=b)};v.h5a=function(a){this.XY=new a;this.XY.Aa()};v.VSd=function(){return this.t$a};v.jZc=function(){var a="";this.XY&&(a=this.XY.MHa());return a};v.DUa=function(a){this.q7(a.Hoc(),
a.nTb(0));this.h5a(a.nTb(1))};v.Ugb=function(a){this.XY.set(a);a=this.XY.get();return a.toString()};v.Xgb=function(a){this.XY.set(a);return this.XY.get()};v.Qu=function(a){a=this.Ugb(a);var b=null;this.mb[a]!==p&&(b=this.mb[a],d.ssa(b),this.v4(b),delete this.mb[a],this.DL(),this.jda(b,0));return b};v.Il=function(){for(var a in this.mb)this.v4(this.mb[a]);this.mb={};this.DL();this.bma()};v.DL=function(){delete this.PJ};v.Fla=function(){var a=this;if(this.PJ===p){this.PJ=[];for(var b in this.mb)this.PJ.push(b);
this.PJ.sort(function(b,c){b=a.Xgb(b);c=a.Xgb(c);return d.cmp(b,c)})}return this.PJ};var B={COLLECTION:a.L_a.AJc,FACTORY:a.L_a.Lkb};d.Kd(c.jec,"PRIM_KCOL",{za:{Style:{a:function(){return d.va(this.Ch(),B)},f:function(a){this.Ib(d.ua(a,B))}},Item:{a:function(a){return this.se(a)},f:function(a,b){this.Kl(a,b)},Cz:"na"},Collects:{f:v.q7},KeyedBy:{f:v.h5a},KeyOf:{a:function(a){return this.gnb(a)},Cz:"na"}},hc:{Remove:v.Qu,RemoveAll:v.Il},cf:{af:"Item"},ts:{Fka:function(a){return this.fnb(d.L(a)-1)},Qr:function(a){return this.Mz(d.L(a)-
1)},Qy:function(){return this.Jc()}}});c.Adc=function(){n.J.call(this);this.MY=(t++).toString();this.yM=[];this.hpa=this.lBc=""};var n=c.q(c.Adc,c.Xwa);n.Q=function(){this.Il();n.j.Q.call(this)};n.Q_=function(){return"PRIM_DCOL<"+this.hpa+" "+this.lBc+">"};n.Jc=function(){return this.yM.length};n.Mz=function(a){return this.yM[a].iM[this.MY]};n.se=function(a){return a.iM===p||a.iM[this.MY]===p?null:a.iM[this.MY]};n.Kl=function(a,b){a.iM===p&&(a.iM={});var c=a.iM[this.MY];c===p?(this.yM.push(a),a.Aa()):
this.v4(c);a.iM[this.MY]=b;this.e4(b)};n.fnb=function(a){return this.yM[a]};n.q7=function(a){this.hpa=a};n.h5a=function(a){this.lBc=a};n.gnb=function(a,b){for(var c=b;c<this.yM.length;c++){var d=this.yM[c];if(d.iM[this.MY]===a)return d}return null};n.fTc=function(a){return this.se(a)};n.Ve=function(a){return-1!=this.yM.indexOf(a)};n.RJc=function(a){for(var b=0;b<this.yM.length;b++)if(this.yM[b].iM[this.MY]===a)return!0;return!1};n.qs=function(a,b){var c=this.se(b);this.Kl(b,a);return c};n.Qu=function(a){if(a.iM!==
p){var b=a.iM[this.MY];if(b!==p)return delete a.iM[this.MY],this.yM.splice(this.yM.indexOf(a),1),d.ssa(b),this.v4(b),a.ub(),this.jda(b,0),b}return null};n.Il=function(){for(var a=0;a<this.yM.length;a++){var b=this.yM[a],c=b.iM[this.MY];c!==p&&(delete b.iM[this.MY],this.v4(c));b.ub()}this.yM=[];this.bma()};d.Kd(c.Adc,"PRIM_DCOL",{za:{Item:{a:function(a){return this.se(a)},f:function(a,b){this.Kl(a,b)},Cz:"na"},Collects:{f:n.q7,Cz:"na"},KeyedBy:{f:n.h5a,Cz:"na"},KeyOf:{a:function(a,b){return this.gnb(a,
b!==p?d.L(b)-1:0)},Cz:"na"}},hc:{Contains:n.Ve,ContainsItem:n.RJc,Insert:n.qs,Remove:n.Qu,RemoveAll:n.Il,Find:n.fTc},cf:{af:"Item"},ts:{Fka:function(a){return this.fnb(d.L(a)-1)},Qr:function(a){return this.Mz(d.L(a)-1)},Qy:function(){return this.Jc()}}})});
