window.LANSA.addSrc("web",function(d,c,a,b,p){d.Ob("PRIM_LABL");var t=localStorage,l=sessionStorage;a.PO={uBb:0,$pc:1,aqc:2,Zpc:3};a.PO.v={INLINE:a.PO.uBb,LEFT:a.PO.$pc,RIGHT:a.PO.aqc,CENTER:a.PO.Zpc};a.MI={RWa:0,PZb:1,TZb:2,UZb:3,WZb:4,hkb:5};a.MI.v={NONE:a.MI.RWa,NOTLOADED:a.MI.PZb,PERMISSIONDENIED:a.MI.TZb,POSITIONUNAVAILABLE:a.MI.UZb,TIMEOUT:a.MI.WZb,UNKNOWNERROR:a.MI.hkb};a.k_={PSb:0,NSb:1,QSb:2,OSb:4};a.k_.v={NONE:a.k_.PSb,ERROR:a.k_.NSb,WARNING:a.k_.QSb,INFORMATION:a.k_.OSb};c.Owb=function(){q.J.call(this);
this.mb=[]};var q=c.q(c.Owb,c.Ad);q.Q=function(){q.j.Q.call(this)};q.Jc=function(){return this.mb.length};q.se=function(a){return this.mb[a-1]};q.lI=function(a){for(var c=null,d=0;d<this.mb.length;d++){var e=this.mb[d];if(b.bA(e.dq,a)){c=e;break}}return c};d.Ra(c.Owb,"PRIM_WEB","URLParameters",{za:{Item:{a:function(a){return this.lI(d.ja(a))},Cz:"na"},ItemCount:{a:q.Jc}},cf:{af:"Item"},ts:{Qr:function(a){return this.se(d.L(a))},Qy:q.Jc}});b.Kcd=function(a,b,d){a.mb.push(new c.M1a(b,d))};b.Jcd=function(a,
d){b.Hl().S4b().mb.unshift(new c.M1a(a,d))};c.M1a=function(a,b){s.J.call(this);this.dq=a;this.bb=b};var s=c.q(c.M1a,c.Ad);s.Kh=function(){return this.dq.toUpperCase()};s.jb=function(){return this.bb};d.Ra(c.M1a,"PRIM_WEB","URLParameter",{za:{Name:{a:s.Kh},Value:{a:s.jb}}});c.Mwb=function(){k.J.call(this);this.Eq=null;this.m9=p};var k=c.q(c.Mwb,c.Ad);k.Q=function(){k.j.Q.call(this)};k.Rta=function(){if(this.m9===p&&(this.m9=!1,t))try{var a,c=b.Hl().m4b();t.setItem(c,c);a=t.getItem(c)==c;t.removeItem(c);
a&&(this.m9=!0)}catch(d){}return this.m9};k.Jc=function(){return this.cW().length};k.se=function(a){return this.cW()[a-1]};k.lI=function(a){for(var b=null,c=this.cW(),d=0;d<c.length;d++){var e=c[d];if(e.dq==a){b=e;break}}return b};k.cW=function(){if(null==this.Eq&&(this.Eq=[],t))for(var a=0;a<t.length;a++){var b=t.key(a);""!=b&&t[b]!=p&&this.Eq.push(new c.K1a(b))}return this.Eq};k.TMa=function(){this.Eq=null};k.ri=function(a,b){var d=this.cW(),e=this.lI(a);null==e&&(e=new c.K1a(a),d.push(e));e.nb(b)||
d.splice(d.indexOf(e),1)};k.Qu=function(c){var d=this.cW(),e=this.lI(c);null!=e&&(t.removeItem(c),d.splice(d.indexOf(e),1),b.Hl().zia(a.qJ.aAa))};k.Tl=function(){t&&(t.clear(),this.TMa(),b.Hl().zia(a.qJ.aAa))};d.Ra(c.Mwb,"PRIM_WEB","LocalStorage",{za:{Available:{a:k.Rta},Item:{a:function(a){return this.lI(d.ja(a))},Cz:"na"},ItemCount:{a:k.Jc}},hc:{Add:k.ri,Remove:k.Qu,Clear:k.Tl},cf:{af:"Item"},ts:{Qr:function(a){return this.se(d.L(a))},Qy:k.Jc}});c.K1a=function(a){e.J.call(this);this.dq=a};var e=
c.q(c.K1a,c.Ad);e.Kh=function(){return this.dq};e.jb=function(){var a="";t&&(a=t[this.dq],a===p&&(a=""));return a};e.nb=function(c){var d=!0;try{t[this.dq]=c,b.Hl().zia(a.qJ.aAa)}catch(e){b.Hl().D0b(a.qJ.aAa),d=!1}return d};d.Ra(c.K1a,"PRIM_WEB","LocalStorageItem",{za:{Name:{a:e.Kh},Value:{a:e.jb,f:function(a){this.nb(d.ja(a))}}},cf:{af:"Value"}});c.Nwb=function(){g.J.call(this);this.Eq=null;this.m9=p};var g=c.q(c.Nwb,c.Ad);g.Q=function(){g.j.Q.call(this)};g.Rta=function(){if(this.m9===p&&(this.m9=
!1,l))try{var a,c=b.Hl().m4b();l.setItem(c,c);a=l.getItem(c)==c;l.removeItem(c);a&&(this.m9=!0)}catch(d){}return this.m9};g.Jc=function(){return this.cW().length};g.se=function(a){return this.cW()[a-1]};g.lI=function(a){for(var b=null,c=this.cW(),d=0;d<c.length;d++){var e=c[d];if(e.dq==a){b=e;break}}return b};g.cW=function(){if(null==this.Eq&&(this.Eq=[],l))for(var a=0;a<l.length;a++){var b=l.key(a);""!=b&&l[b]!=p&&this.Eq.push(new c.L1a(b))}return this.Eq};g.TMa=function(){this.Eq=null};g.ri=function(a,
b){var d=this.cW(),e=this.lI(a);null==e&&(e=new c.L1a(a),d.push(e));return e.nb(b)?!0:(d.splice(d.indexOf(e),1),!1)};g.Qu=function(c){var d=this.cW(),e=this.lI(c);null!=e&&(l.removeItem(c),d.splice(d.indexOf(e),1),b.Hl().zia(a.qJ.bAa))};g.Tl=function(){l&&(l.clear(),this.TMa(),b.Hl().zia(a.qJ.bAa))};d.Ra(c.Nwb,"PRIM_WEB","SessionStorage",{za:{Available:{a:g.Rta},Item:{a:function(a){return this.lI(d.ja(a))},Cz:"na"},ItemCount:{a:g.Jc}},hc:{Add:g.ri,Remove:g.Qu,Clear:g.Tl},cf:{af:"Item"},ts:{Qr:function(a){return this.se(d.L(a))},
Qy:g.Jc}});c.L1a=function(a){f.J.call(this);this.dq=a};var f=c.q(c.L1a,c.Ad);f.Kh=function(){return this.dq};f.jb=function(){var a="";l&&(a=l[this.dq],a===p&&(a=""));return a};f.nb=function(c){var d=!0;try{l[this.dq]=c,b.Hl().zia(a.qJ.bAa)}catch(e){b.Hl().D0b(a.qJ.bAa),d=!1}return d};d.Ra(c.L1a,"PRIM_WEB","SessionStorageItem",{za:{Name:{a:f.Kh},Value:{a:f.jb,f:function(a){this.nb(d.ja(a))}}},cf:{af:"Value"}});c.Lwb=function(){v.J.call(this)};var v=c.q(c.Lwb,c.Ad);v.Q=function(){v.j.Q.call(this)};
v.T2c=function(a){0<a&&window.history.go(0-a)};v.U2c=function(a){0<a&&window.history.go(a)};v.ri=function(a,c){var d=window.location.protocol+"//"+window.location.host+window.location.pathname;0<a.length&&(d+="?"+a);window.history.pushState(null,"",d);b.Hl().$Ab();c&&b.Hl().jXa()};v.LAb=function(a,c){var d=window.location.protocol+"//"+window.location.host+window.location.pathname;0<a.length&&(d+="?"+a);window.history.replaceState(null,"",d);b.Hl().$Ab();c&&b.Hl().jXa()};d.Ra(c.Lwb,"PRIM_WEB","History",
{hc:{Add:function(a,b){this.ri(d.ja(a),b===p?!0:d.Ba(b))},Replace:function(a,b){this.LAb(d.ja(a),b===p?!0:d.Ba(b))},GoBack:function(a){this.T2c(a===p?1:d.L(a))},GoForward:function(a){this.U2c(a===p?1:d.L(a))}}});c.wic=function(){B.J.call(this);this.Mb=b.Kf(0,0,400,400);this.K9=this.Ue="";this.Rc&=~a.Vd.fS;this.Rc&=~a.Vd.R0};var B=c.q(c.wic,c.Xl);B.ze=function(){return c.ijc};B.$A=function(){return this.Ue};B.sl=function(b){this.Ue!=b&&(this.Ue=b,this.na(a.g.i))};B.DC=function(){return this.K9};B.Rma=
function(a){this.K9=a};B.Hc=function(a,c,d){B.j.Hc.call(this,a,c,d);a=this.Sa().Za();b.ke[a].sl(this.Ue)};B.KTc=function(){this.Fa(a.O.yac)};d.Ra(c.wic,"PRIM_WEB","Page",{za:{Source:{a:B.$A,f:function(a){this.sl(d.ja(a))}},Description:{a:B.DC,f:function(a){this.Rma(d.ja(a))}}}});c.Hxa=function(){n.J.call(this)};var n=c.q(c.Hxa,c.Xl);n.Wnb=function(){for(var a=null,b=this;b;){if(b instanceof c.Vwb){a=b;break}b=b.cc}return a};n.a7=function(){n.j.a7.call(this);var a=this.Wnb();a&&a.M4(this)};n.iX=function(){n.j.iX.call(this);
var a=this.Wnb();a&&a.N4(this)};n.of=function(a){n.j.of.call(this,a);var b=this.Wnb();b==this&&b.iE(a,!1)};d.Ra(c.Hxa,"PRIM_WEB","RichTextItem",{});c.Zwb=function(){r.J.call(this)};var r=c.q(c.Zwb,c.Hxa);r.ze=function(){return c.rkc};d.Ra(c.Zwb,"PRIM_WEB","RichTextLine",{});c.Wwb=function(){E.J.call(this)};var E=c.q(c.Wwb,c.Hxa);E.ze=function(){return c.pkc};d.Ra(c.Wwb,"PRIM_WEB","RichTextBreak",{});c.Xwb=function(){C.J.call(this);this.v3=null;this.dTa=a.PO.uBb;this.Ucb=this.Vcb=0};var C=c.q(c.Xwb,
c.Hxa);C.Q=function(){C.j.Q.call(this);this.H5a(null)};C.ze=function(){return c.qkc};C.H0c=function(){return this.v3};C.H5a=function(b){this.v3!=b&&(null!=this.v3&&(this.v3.Ga(this,this.kXb),this.v3.ub()),this.v3=b,null!=this.v3&&(this.v3.Aa(),this.v3.Ha(this,this.kXb)),this.na(a.g.i))};C.g_d=function(){return this.dTa};C.ssc=function(b){this.dTa!=b&&(this.dTa=b,this.na(a.g.i))};C.I0c=function(){return this.Vcb};C.usc=function(b){this.Vcb!=b&&(this.Vcb=b,this.na(a.g.i))};C.G0c=function(){return this.Ucb};
C.tsc=function(b){this.Ucb!=b&&(this.Ucb=b,this.na(a.g.i))};C.Hc=function(a,c,d){C.j.Hc.call(this,a,c,d);a=this.Sa().Za();b.ke[a].di(this.dTa,this.Vcb,this.Ucb)};C.KAb=function(){var a=this.v3,c=this.Sa().Za(),a=a?a.Jg():"";b.ke[c].yd(a)};C.kXb=function(b,c){switch(c.cb){case a.g.Bb:case a.g.Ub:this.H5a(null);break;case a.g.i:this.na(a.g.i)}};d.Ra(c.Xwb,"PRIM_WEB","RichTextImage",{za:{Image:{a:C.H0c,f:function(a){this.H5a(a)}},Width:{a:C.I0c,f:function(a){this.usc(d.L(a))}},Height:{a:C.G0c,f:function(a){this.tsc(d.L(a))}},
Alignment:{a:function(){return d.va(this.dTa,a.PO.v)},f:function(b){this.ssc(d.ua(b,a.PO.v))}}}});c.N1a=function(){x.J.call(this);this.zA=null};var x=c.q(c.N1a,c.Hxa);x.ze=function(){return c.skc};x.Iy=function(){null==this.zA&&(this.zA=new c.Ywb(this));return this.zA};d.Ra(c.N1a,"PRIM_WEB","RichTextParagraph",{za:{Items:{a:x.Iy}}});c.Vwb=function(){K.J.call(this);this.Mb=b.Kf(0,0,100,100)};var K=c.q(c.Vwb,c.N1a);K.ze=function(){return c.okc};K.M4=function(b){if(!this.Nd()){var c=d.fc();c.jc("ITEM",
b);this.Fa(a.O.eO,c);c.Kc()}};K.N4=function(b){if(!this.Nd()){var c=d.fc();c.jc("ITEM",b);this.Fa(a.O.gO,c);c.Kc()}};K.Qaa=function(b){if(!this.Nd()){var c=d.fc();c.jc("ITEM",b);this.Fa(a.O.fO,c);c.Kc()}};K.iE=function(b,c){if(!c&&!this.Nd()){var e=d.fc();e.jc("ITEM",b);e.og("CONTINUE",!0);this.Fa(a.O.dO,e);c=!e.dh("CONTINUE");e.Kc()}return c};d.Ra(c.Vwb,"PRIM_WEB","RichText",{});c.Ywb=function(a){I.J.call(this);this.mb=[];this.SD=a};var I=c.q(c.Ywb,c.Ad);I.Q=function(){I.j.Q.call(this)};I.Jc=function(){return this.mb.length};
I.se=function(a){return this.mb[a-1]};I.ri=function(b,d,e,f){var g=new c.Zwb;g.Aa();g.sb(b);d!=p&&g.Ib(d);e!=p&&g.xp(e);f!=p&&g.gr(f);g.Na(this.SD);this.mb[this.mb.length]=g;this.SD.na(a.g.i);this.SD.Wb()&&this.SD.gh();return g};I.TDc=function(){var b=new c.Wwb;b.Aa();b.Na(this.SD);this.mb[this.mb.length]=b;this.SD.na(a.g.i);this.SD.Wb()&&this.SD.gh();return b};I.cEc=function(b,d,e,f,g,n,k){var l=new c.Xwb;l.Aa();l.H5a(b);d!=p&&l.ssc(d);e!=p&&l.usc(e);f!=p&&l.tsc(f);g!=p&&l.Ib(g);n!=p&&l.xp(n);k!=
p&&l.gr(k);l.Na(this.SD);this.mb[this.mb.length]=l;this.SD.na(a.g.i);this.SD.Wb()&&this.SD.gh();return l};I.hEc=function(b,d,e,f){var g=new c.N1a;g.Aa();b!=p&&g.sb(b);d!=p&&g.Ib(d);e!=p&&g.xp(e);f!=p&&g.gr(f);g.Na(this.SD);this.mb[this.mb.length]=g;this.SD.na(a.g.i);this.SD.Wb()&&this.SD.gh();return g};I.Qu=function(b){this.mb.splice(this.mb.indexOf(b),1);b.Na(null);b.ub();this.SD.na(a.g.i)};I.Il=function(){for(;0<this.mb.length;)this.Qu(this.mb[0]);this.SD.na(a.g.i)};d.Ra(c.Ywb,"PRIM_WEB","RichTextItems",
{za:{Item:{a:function(a){return this.se(d.L(a))},Cz:"na"},ItemCount:{a:I.Jc}},hc:{Add:I.ri,AddBreak:I.TDc,AddImage:function(b,c,e,f,g,n,k){return this.cEc(b,d.ua(c,a.PO.v),e,f,g,n,k)},AddParagraph:I.hEc,Remove:I.Qu,RemoveAll:I.Il},cf:{af:"Item"},ts:{Qr:function(a){return this.se(d.L(a))},Qy:I.Jc}});c.Eic=function(){D.J.call(this);this.Mb=b.Kf(0,0,100,100)};var D=c.q(c.Eic,c.Xl);D.ze=function(){return c.Cjc};D.Hc=function(a,b,c){D.j.Hc.call(this,a,b,c)};D.fg=function(a){this.HG();a&&this.pMa();b.pb().LF(this)};
D.FG=function(){this.ga.X3()};d.Ra(c.Eic,"PRIM_WEB","Camera",{});c.djc=function(){M.J.call(this);this.Mb=b.Kf(0,0,100,100);this.yJ=null;this.qVa("")};var M=c.q(c.djc,c.Xl);M.Q=function(){this.yJ=null;M.j.Q.call(this)};M.ze=function(){return c.tkc};M.EHa=function(){this.Sa()&&this.qVa(this.Sa().hVc());return this.yJ};M.qVa=function(a){this.yJ=new c.NI({data:a,mimetype:"image/png",filename:"signature.png"})};M.Tl=function(){if(this.Sa()){var a=this.Sa().Za();b.ke[a].Tl();this.Ce()}};M.Hc=function(a,
b,c){M.j.Hc.call(this,a,b,c)};M.fg=function(a){this.HG();a&&this.pMa();b.pb().LF(this)};M.FG=function(){this.ga.X3()};M.Ce=function(){this.Fa(a.O.zh)};d.Ra(c.djc,"PRIM_WEB","Signature",{za:{Blob:{a:M.EHa}},hc:{Clear:M.Tl}});c.Qic=function(){ca.J.call(this);this.aPb=this.aNb=this.oKb=this.nKb=this.iKb=this.Ubb=this.KNb=0;this.Qfa=a.MI.PZb};var ca=c.q(c.Qic,c.Ad);ca.b_c=function(){return this.KNb};ca.oZc=function(){return this.Ubb};ca.yUc=function(){return this.iKb};ca.NUc=function(){return this.nKb};
ca.OUc=function(){return this.oKb};ca.CYc=function(){return this.aNb};ca.r1c=function(){return this.aPb};ca.aWd=function(){return this.Qfa};ca.lid=function(){var b=this;navigator.geolocation&&navigator.geolocation.getCurrentPosition(function(d){b.KNb=d.coords.longitude;b.Ubb=d.coords.latitude;b.iKb=d.coords.accuracy;b.nKb=d.coords.altitude?d.coords.altitude:0;b.oKb=d.coords.altitudeAccuracy?d.coords.altitudeAccuracy:0;b.aNb=d.coords.heading?d.coords.heading:0;b.aPb=d.coords.speed?d.coords.speed:0;
b.Qfa=a.MI.RWa;b.Fa(a.O.Noc,new c.exa)},function(d){b.KNb=0;b.Ubb=0;b.iKb=0;b.nKb=0;b.oKb=0;b.aNb=0;b.aPb=0;b.Qfa=a.MI.hkb;switch(d.code){case d.PERMISSION_DENIED:b.Qfa=a.MI.TZb;break;case d.POSITION_UNAVAILABLE:b.Qfa=a.MI.UZb;break;case d.TIMEOUT:b.Qfa=a.MI.WZb;break;case d.UNKNOWN_ERROR:b.Qfa=a.MI.hkb}b.Fa(a.O.Noc,new c.exa)});return this.Ubb};d.Ra(c.Qic,"PRIM_WEB","Geolocation",{za:{Longitude:{a:ca.b_c},Latitude:{a:ca.oZc},Accuracy:{a:ca.yUc},Altitude:{a:ca.NUc},AltitudeAccuracy:{a:ca.OUc},Heading:{a:ca.CYc},
Speed:{a:ca.r1c},ErrorCode:{a:function(){return d.va(this.Qfa,a.MI.v)}}},hc:{Refresh:ca.lid}});c.Mic=function(){F.J.call(this)};var F=c.q(c.Mic,c.Ad);F.Cbd=function(b,c){if("undefined"!==typeof console)switch(c){case a.k_.NSb:console.error(b);break;case a.k_.QSb:console.warn(b);break;case a.k_.OSb:console.info(b);break;default:console.log(b)}};d.Ra(c.Mic,"PRIM_WEB","Console",{za:{},hc:{Log:function(b,c){return this.Cbd(d.ja(b),c?d.ua(c,a.k_.v):a.k_.PSb)}}});c.Pic=function(){z.J.call(this);this.vc=
this.ob=null;this.tM=this.rr="";this.Oqa=!1};var z=c.q(c.Pic,c.Kw);z.Q=function(){z.j.Q.call(this);this.vq(null)};z.ze=function(){return c.Ljc};z.Jg=function(){return this.rr};z.Mmb=function(){return this.tM};z.Fh=function(b){this.ob!=b&&(this.vq(b),this.l(a.g.i))};z.qb=function(){var a=null;return a=this.ob};z.mc=function(){return this.vc};z.Gja=function(){return this.Oqa};z.s5a=function(b){this.Oqa!=b&&(this.Oqa=b,this.na(a.g.i))};z.Ce=function(){this.Fa(a.O.zh)};z.Dta=function(b,c){var e=d.fc();
e.jc("FILE",b);e.jc("FILES",c);this.Fa(a.O.Nkb,e);e.Kc()};z.LQ=function(){this.vY=b.zxa(this.vc.lk());this.ob.A_(this.mc())};z.vq=function(a){var c=null;a&&(c=a.Bz(),this.ob==a?c.Jn(this.vc):a.wC(c));this.ob&&(this.ob.Ga(this),this.vc.Ga(this),b.fa(this.vc),this.vc=null);if(this.ob=a)this.ob.Ha(this,this.Lp),this.vc=c,this.vc.Ha(this,this.Dy);this.Zh()};z.wEd=function(){};z.Lp=function(b,c){c.cb==a.g.i?c.su==a.Ie.Xz?this.ob.wC(this.mc()):this.vq(this.ob):c.cb==a.g.Bb&&this.Fh(null)};z.Dy=function(b,
c){c.cb==a.g.i&&c.su==a.Ie.Xz&&this.LQ()};d.Ra(c.Pic,"PRIM_WEB","FilePicker",{za:{MultiSelect:{a:z.Gja,f:function(a){this.s5a(d.Ba(a))}}}});c.zLa=function(a){W.J.call(this);this.Pbb=a;this.oU=this.yJ=null};var W=c.q(c.zLa,c.Ad);W.Q=function(){null!=this.yJ&&(this.yJ=null);null!=this.oU&&(b.GUb(this.oU),this.oU=null);W.j.Q.call(this)};W.Kh=function(){return this.Pbb.name};W.EHa=function(){null==this.yJ&&(this.yJ=new c.dec(this.Pbb));return this.yJ};W.hob=function(){return this.Pbb.size};W.r_c=function(){return this.Pbb.type};
d.Ra(c.zLa,"PRIM_WEB","File",{za:{Name:{a:W.Kh},Blob:{a:W.EHa},FileSize:{a:W.hob},MimeType:{a:W.r_c}}});c.Kwb=function(){y.J.call(this);this.mb=[]};var y=c.q(c.Kwb,c.Ad);y.Q=function(){for(var a=0;a<this.mb.length;a++)this.mb[a].ub();this.mb=[];y.j.Q.call(this)};y.Jc=function(){return this.mb.length};y.se=function(a){return this.mb[a-1]};y.qs=function(a){this.mb.push(a);a.Aa()};d.Ra(c.Kwb,"PRIM_WEB","Files",{za:{Item:{a:function(a){return this.se(d.L(a))},Cz:"na"},ItemCount:{a:y.Jc}},cf:{af:"Item"},
ts:{Qr:function(a){return this.se(d.L(a))},Qy:y.Jc}});c.Lic=function(){ea.J.call(this)};var ea=c.q(c.Lic,c.Ad);ea.xAb=function(a){var d=this;if(window.FileReader&&a instanceof c.NI){if(a=a.vua()){var e=b.LX(),f=new FileReader;f.onload=function(a){d.I4(a.target.result);b.wB(e)};f.readAsText(a)}}else d.I4("")};ea.I4=function(b){var c=d.fc();c.UD("DATA",b);this.Fa(a.O.laa,c)};d.Ra(c.Lic,"PRIM_WEB","ClobReader",{hc:{Read:ea.xAb}});c.zic=function(){Z.J.call(this)};var Z=c.q(c.zic,c.Ad);Z.xAb=function(a){var d=
this;if(window.FileReader&&a instanceof c.NI){if(a=a.vua()){var e=b.LX(),f=new FileReader;f.onload=function(a){d.I4(b.Q_b(a.target.result));b.wB(e)};f.readAsDataURL(a)}}else d.I4("","")};Z.I4=function(b){var c=d.fc();c.UD("DATA",b);this.Fa(a.O.laa,c)};d.Ra(c.zic,"PRIM_WEB","BlobReader",{hc:{Read:Z.xAb}});c.okc=function(a){L.J.call(this,a)};var L=c.q(c.okc,c.lo);L.sb=function(a){this.u.textContent=a};L.zz=function(){L.j.zz.call(this);this.u.style.whiteSpace="normal";this.u.style.overflowX="auto";this.u.style.overflowY=
"auto"};L.Fd=function(a,b){this.u=document.createElement("div");this.u.setAttribute("id",a+this.gc);this.u.setAttribute("LANSAHandle",this.gc);return L.j.Fd.call(this,a,b)};c.skc=function(a){S.J.call(this,a)};var S=c.q(c.skc,c.lo);S.sb=function(a){this.u.textContent=a};S.jJa=function(){return!1};S.Goa=function(){};S.zz=function(){};S.Fd=function(a,b){this.u=document.createElement("p");this.u.setAttribute("id",a+this.gc);this.u.setAttribute("LANSAHandle",this.gc);return S.j.Fd.call(this,a,b)};c.pkc=
function(a){G.J.call(this,a)};var G=c.q(c.pkc,c.lo);G.jJa=function(){return!1};G.Goa=function(){};G.zz=function(){};G.Fd=function(a,b){this.u=document.createElement("br");this.u.setAttribute("id",a+this.gc);this.u.setAttribute("LANSAHandle",this.gc);return G.j.Fd.call(this,a,b)};c.qkc=function(a){H.J.call(this,a)};var H=c.q(c.qkc,c.lo);H.yd=function(a){this.u.src=a};H.jJa=function(){return!1};H.di=function(b,c,d){this.u.style.width=0==c?"auto":c+"px";this.u.style.height=0==d?"auto":d+"px";switch(b){case a.PO.uBb:this.u.style.marginLeft=
"initial";this.u.style.marginRight="initial";this.u.style.display="inline";this.u.style.cssFloat="none";break;case a.PO.$pc:this.u.style.marginLeft="initial";this.u.style.marginRight="initial";this.u.style.display="inline";this.u.style.cssFloat="left";break;case a.PO.aqc:this.u.style.marginLeft="initial";this.u.style.marginRight="initial";this.u.style.display="inline";this.u.style.cssFloat="right";break;case a.PO.Zpc:this.u.style.marginLeft="auto",this.u.style.marginRight="auto",this.u.style.display=
"block",this.u.style.cssFloat="none"}};H.Goa=function(){};H.zz=function(){this.u.style.borderStyle="solid"};H.Fd=function(a,b){this.u=document.createElement("img");this.u.setAttribute("id",a+this.gc);this.u.setAttribute("LANSAHandle",this.gc);return H.j.Fd.call(this,a,b)};c.rkc=function(a){V.J.call(this,a)};var V=c.q(c.rkc,c.lo);V.sb=function(a){this.u.textContent=a};V.jJa=function(){return!1};V.Goa=function(){};V.zz=function(){};V.Fd=function(a,b){this.u=document.createElement("span");this.u.setAttribute("id",
a+this.gc);this.u.setAttribute("LANSAHandle",this.gc);return V.j.Fd.call(this,a,b)};c.Cjc=function(a){qa.J.call(this,a)};var qa=c.q(c.Cjc,c.lo);qa.Fd=function(a,b){this.u=document.createElement("div");this.u.setAttribute("id",a+this.gc);this.u.setAttribute("LANSAHandle",this.gc);return qa.j.Fd.call(this,a,b)};c.tkc=function(a){ha.J.call(this,a);this.hv=this.Dp=null;this.yAc=this.qQb=!1;this.jNb=null};var ha=c.q(c.tkc,c.lo);ha.z6b=function(){return!0};ha.Fd=function(a,b){this.u=document.createElement("div");
this.u.setAttribute("id",a+this.gc);this.u.setAttribute("LANSAHandle",this.gc);this.u.style.msTouchAction="none";this.hv=document.createElement("canvas");this.hv.style.touchAction="none";this.u.appendChild(this.hv);this.Dp=this.hv.getContext("2d");this.DUb();return ha.j.Fd.call(this,a,b)};ha.qq=function(a,b,c,d){ha.j.qq.call(this,a,b,c,d);if(c>this.hv.width||d>this.hv.height)a=this.Dp.getImageData(0,0,this.hv.width-1,this.hv.height-1),this.hv.width=this.Hd,this.hv.height=this.Od,this.Dp.putImageData(a,
0,0)};ha.BS=function(a){this.xEb(a);return!0};ha.dyb=function(a){this.xtc(a);return!0};ha.d2a=function(a){this.wEb(a);return!0};ha.yG=function(a){a.buttons&&this.xEb(a);return ha.j.yG.call(this,a)};ha.zG=function(a){this.wEb(a);return ha.j.zG.call(this,a)};ha.ABa=function(a){this.xEb(a);return!0};ha.$x=function(a){this.xtc(a);return!0};ha.Aoa=function(a){this.wEb(a);return!0};ha.s7b=function(a){this.u.onpointerdown===p&&a.touches!==p?(a.ZJb=a.touches[0].pageX-this.K.St(),a.$Jb=a.touches[0].pageY-
this.K.Tt()):(a.ZJb=a.clientX-this.K.St(),a.$Jb=a.clientY-this.K.Tt());this.K.Ce()};ha.DUb=function(){this.vgb(!0);this.jNb=new Image;this.jNb.onload=function(){throw 0;};this.jNb.src=null};ha.vgb=function(a){(this.yAc||a)&&this.Dp.clearRect(0,0,this.Dp.canvas.width,this.Dp.canvas.height);this.yAc=!1};ha.hVc=function(){var a=this.hv.toDataURL("image/png");return b.Q_b(a)};ha.Tl=function(){this.DUb()};ha.xEb=function(a){a.preventDefault();this.vgb(!1);this.Dp.beginPath();this.s7b(a);this.Dp.moveTo(a.ZJb,
a.$Jb);this.qQb=!0};ha.wEb=function(a){a.preventDefault();this.qQb=!1};ha.Ufe=function(a){this.$x(a)};ha.xtc=function(a){this.qQb&&(a.preventDefault(),this.vgb(!1),this.Dp.strokeStyle="rgb(0,0,0)",this.Dp.lineWidth=1,this.s7b(a),this.Dp.lineTo(a.ZJb,a.$Jb),this.Dp.stroke())};c.ijc=function(a){ka.J.call(this,a);this.bsa=this.fb=null};var ka=c.q(c.ijc,c.lo);ka.sl=function(a){this.bsa.src=a};ka.Fd=function(a,b){this.u=document.createElement("div");this.u.setAttribute("id",a+this.gc);this.u.setAttribute("LANSAHandle",
this.gc);this.bsa=document.createElement("iframe");this.UZ(this.bsa);this.bsa.style.width="100%";this.bsa.style.height="100%";this.u.appendChild(this.bsa);return ka.j.Fd.call(this,a,b)};ka.yy=function(){var a=this;ka.j.yy.call(this);a.bsa.addEventListener("load",function(){a.K&&a.K.KTc()},!1)};ka.UZ=function(a){ka.j.UZ.call(this,a);this.u.style.overflowX="auto";this.u.style.overflowY="auto"};c.Ljc=function(a){sa.J.call(this,a);this.sr=null};var sa=c.q(c.Ljc,c.hxb);sa.Fd=function(a,b){var c=sa.j.Fd.call(this,
a,b);this.sr=document.createElement("input");this.sr.type="File";this.sr.title="";var d=this.sr.style;this.eb.style.zIndex=1;d.opacity=0;d.position="absolute";d.zIndex=99998;d.background="rgb( 255, 0, 0 )";c.appendChild(this.sr);return c};sa.Hc=function(){sa.j.Hc.call(this);this.MPa()};sa.qq=function(a,b,c,d){sa.j.qq.call(this,a,b,c,d);this.sr.style.left="0px";this.sr.style.top="0px";this.sr.style.width=c+"px";this.sr.style.height=d+"px"};sa.yy=function(){var a=this;this.$Z();a.sr.addEventListener("change",
function(b){a.K&&(a.VFa(b),a.sr.value="")},!1)};sa.MPa=function(){this.sr.multiple=this.K.Gja()};sa.VFa=function(a){a=a.target.files||a.dataTransfer.files;for(var b=null,d=new c.Kwb,e=0,f;f=a[e];e++)f=new c.zLa(f),null==b&&(b=f),d.qs(f);b&&this.K.Dta(b,d)}},{rp:["PRIM_LABL"]});
