window.LANSA.addSrc("msg",function(d,c,a,b,p){d.Ob("PRIM_PPNL");a.Xxa={Uca:0,Kdd:1,Ldd:2,Hdd:4,Idd:8};a.Xxa.v={NONE:a.Xxa.Uca,TEXT:a.Xxa.Kdd,WARNING:a.Xxa.Ldd,ERROR:a.Xxa.Hdd,FATAL:a.Xxa.Idd};a.M6={klc:1,mlc:2,llc:4};a.M6.v={ERROR:a.M6.klc,QUESTION:a.M6.mlc,INFORMATION:a.M6.llc};a.Er={xKd:16,Nfb:1,PUa:16,MUa:32,RUa:64,OUa:128,QUa:256,NUa:512};a.Er.v={NONE:a.Er.Nfb,OK:a.Er.PUa,CANCEL:a.Er.MUa,YES:a.Er.RUa,NO:a.Er.OUa,RETRY:a.Er.QUa,IGNORE:a.Er.NUa};a.uL={Mxb:16,olc:48,plc:192,qlc:224,nlc:768};a.uL.v=
{OK:a.uL.Mxb,OKCANCEL:a.uL.olc,YESNO:a.uL.plc,YESNOCANCEL:a.uL.qlc,IGNORERETRY:a.uL.nlc};c.mec=function(){t.J.call(this)};var t=c.q(c.mec,c.Ad);d.Kd(c.mec,"PRIM_MSG",{});c.Bub=function(){l.J.call(this);this.nH=[]};var l=c.q(c.Bub,c.Ad);l.p_c=function(){d.Ob("PRIM_PCOL");var a=new c.ncc(this);return new c.t6(a)};l.ri=function(a,b){var d=new c.Cub(this,a);this.nH.push(d);d.tk(b);this.MTc(d);return d};l.Tl=function(a){if(a)for(var b=0;b<this.nH.length;b++){var c=this.nH[b];c.la()==a&&(this.y0b(c),this.nH.splice(b--,
1),c.YVa())}};l.lJc=function(){for(;0<this.nH.length;){var a=this.nH.shift();this.y0b(a);a.YVa()}};l.MTc=function(b){var c=d.fc();c.jc("MESSAGE",b);this.Fa(a.O.ndd,c);c.Kc()};l.y0b=function(b){var c=d.fc();c.jc("MESSAGE",b);this.Fa(a.O.odd,c);c.Kc()};d.Kd(c.Bub,"PRIM_MSGQ",{za:{Messages:{a:l.p_c}},hc:{Add:function(a,b){return this.ri(d.ja(a),b===p?null:b)},Clear:function(a){return this.Tl(a===p?null:a)},ClearAll:function(){return this.lJc()}}});c.ncc=function(a){q.J.call(this);this.wSa=a};var q=c.q(c.ncc,
c.dla);q.Jc=function(){return this.wSa.nH.length};q.Mz=function(a){return this.wSa.nH[a]};c.Cub=function(a,b){s.J.call(this);this.wSa=a;this.wh=b;this.fb=null};var s=c.q(c.Cub,c.Ad);s.ye=function(){return this.wh};s.la=function(){return this.fb};s.tk=function(a){this.lg()&&this.fb!=a&&(null!=this.fb&&(this.fb.IS(this),this.fb.Ga(this,this.Cv)),this.fb=a)&&(a.KQ(this),a.Ha(this,this.Cv))};s.lg=function(){return null!==this.wSa};s.YVa=function(){this.tk(null);this.wh="";this.wSa=null};s.Cv=function(b,
c){switch(c.cb){case a.g.Bb:this.tk(null)}};d.Ra(c.Cub,"PRIM_MSGQ","Message",{za:{Text:{a:s.ye},Control:{a:s.la,f:s.tk}}});c.Wic=function(){k.J.call(this);this.JCa=[]};var k=c.q(c.Wic,c.Ad);k.Q=function(){this.Il();k.j.Q.call(this)};k.se=function(a){return this.JCa[a]};k.Jc=function(){return this.JCa.length};k.ri=function(b){this.JCa.push(b);this.l(a.g.i)};k.Il=function(){this.JCa=[];this.l(a.g.i)};k.a_c=function(){for(var a="",b=0;b<this.JCa.length;b++){var c=this.JCa[b];c.length>a.length&&(a=c)}return a};
d.Ra(c.Wic,"PRIM_WEB","MessageBoxCaptions",{hc:{Add:k.ri,RemoveAll:k.Il}});c.Vic=function(){e.J.call(this);d.Ob("PRIM_PHBN");d.Ob("PRIM_LABL");this.nTa=this.Iga=this.Wra=null;this.vSa=a.M6.llc;this.hF=a.uL.Mxb;this.Sf=a.Er.Nfb;this.Y9a=[];this.uY=null;this.Qdb=new c.Kw;this.Pdb=new c.sO;this.zH=new c.Xl;this.oM=d.Bc("PRIM_WEB","MessageBoxCaptions");this.oM.Aa();this.oM.Ha(this,this.GVb);this.ug=new c.Vvb;this.Bp=new c.sO;this.Dn=new c.sO;this.HQ=new c.sO;this.nU=new c.sO;this.AU=new c.sO;this.cQ=
new c.sO;this.Dn.ya(this,a.O.qc,this.TOc);this.Bp.ya(this,a.O.qc,this.PMc);this.HQ.ya(this,a.O.qc,this.QQc);this.nU.ya(this,a.O.qc,this.ROc);this.AU.ya(this,a.O.qc,this.yPc);this.cQ.ya(this,a.O.qc,this.nOc);this.zH.Na(this);this.ug.Na(this);this.Bp.Na(this);this.Dn.Na(this);this.HQ.Na(this);this.nU.Na(this);this.AU.Na(this);this.cQ.Na(this);this.Iga=new c.xb;this.nTa=new c.Wf;this.Iga.Jd(this.nTa);this.nTa.Pd(a.m.QX);this.nTa.Ng(9);this.Isc(this.Iga);this.Iga.Aa();this.nTa.Aa();this.zH.Ya(90);this.zH.Ne(!1);
this.zH.Wa(57);this.zH.zb(!0);this.zH.SL(!0);this.zH.P1(!0);this.ug.Td(6);this.ug.uB(a.bh.wq);this.ug.Ya(20);this.ug.Wa(57);this.ug.cu(64);this.ug.NG(64);this.ug.wc(64);this.ug.oc(64);this.ug.Ne(!1);this.Dn.sb(b.Uk().ok||"OK");this.nU.sb(b.Uk().no||"No");this.HQ.sb(b.Uk().yes||"Yes");this.AU.sb(b.Uk().retry||"Retry");this.Bp.sb(b.Uk().cancel||"Cancel");this.cQ.sb(b.Uk().ignore||"Ignore");this.Uqc(this.hF);this.Ima(!1);this.TDb(!0)};var e=c.q(c.Vic,c.Kx);e.Q=function(){this.oM.Ga(this,this.GVb);this.oM.ub();
this.oM=null;this.HUb();e.j.Q.call(this)};e.Rod=function(a){this.Qdb.Ib(a)};e.BVc=function(){return this.Qdb.Ch()};e.CVc=function(){return this.Qdb.Vk()};e.Vta=function(){return this.Pdb.Ch()};e.HL=function(a){this.Pdb.Ib(a)};e.tVc=function(){return this.Pdb.Vk()};e.ona=function(b){b!=this.yI()&&(this.sb(b),this.G8a(),this.l(a.g.i))};e.yI=function(){return this.$a()};e.Lrd=function(b){this.oM.Il();b!=this.f3b()&&(this.oM.ri(b),this.l(a.g.i))};e.EVc=function(){return this.oM};e.f3b=function(){return 0<
this.oM.Jc()?this.oM.se(0):""};e.jrc=function(b){this.uY!==b&&(null!=this.uY&&(this.uY.Ga(this,this.WVb),this.uY.ub()),this.uY=b,null!==this.uY&&(this.uY.Aa(),this.uY.Ha(this,this.WVb)),this.G8a(),this.l(a.g.i))};e.BWc=function(){return this.uY};e.Mrd=function(b){this.vSa!=b&&(this.vSa=b,this.G8a(),this.l(a.g.i))};e.mYd=function(){return this.vSa};e.Uqc=function(b){this.hF=b;this.Dn.zb(0!=(this.hF&a.Er.PUa));this.Bp.zb(0!=(this.hF&a.Er.MUa));this.HQ.zb(0!=(this.hF&a.Er.RUa));this.nU.zb(0!=(this.hF&
a.Er.OUa));this.cQ.zb(0!=(this.hF&a.Er.NUa));this.AU.zb(0!=(this.hF&a.Er.QUa))};e.rSd=function(){return this.hF};e.Oee=function(a){this.Sf=a};e.f_d=function(){return this.Sf};e.PKc=function(b,d,e){var g=new c.Kw;g.Na(this.zH);g.Ya(0);g.Ne(!1);g.Wa(d);g.Oo(a.bh.wq);g.oc(e.Ta());g.wc(e.Ma());g.Df(!1);g.sb(b);return g};e.Btc=function(a,d){var e=b.$z(0,0),g=new c.pa(0,0,0,0);b.wG(a,g,0,d);e.oc(g.ha()+2);e.wc(g.ka()+2);return e};e.x0c=function(){if(null!=this.uY)return this.uY;var d="";switch(this.vSa){case a.M6.klc:d=
"lansa_error.png";break;case a.M6.mlc:d="lansa_question.png";break;default:d="lansa_information.png"}var e=new c.kO;e.Ru(b.Pc(d));return e};e.eFc=function(){var a=this.Pdb.Vk().hb.uI(),b=null;this.Dn.Vk().Il();this.Bp.Vk().Il();this.HQ.Vk().Il();this.nU.Vk().Il();this.AU.Vk().Il();this.cQ.Vk().Il();for(var c=0;null!=a&&c<a.length&&null!=(b=a[c]);c++)this.Dn.Vk().ri(b),this.Bp.Vk().ri(b),this.HQ.Vk().ri(b),this.nU.Vk().ri(b),this.AU.Vk().ri(b),this.cQ.Vk().ri(b);this.Dn.pk(!1,!0);this.Bp.pk(!1,!0);
this.HQ.pk(!1,!0);this.nU.pk(!1,!0);this.AU.pk(!1,!0);this.cQ.pk(!1,!0)};e.kFc=function(){var a=this.Qdb.Vk().hb.uI(),b=null;this.zH.Vk().Il();for(var c=0;null!=a&&c<a.length&&null!=(b=a[c]);c++)this.zH.Vk().ri(b);this.zH.pk(!1,!0)};e.Zza=function(){this.Wra=b.LX();this.Sf=a.Er.Nfb;this.LTb();var c=b.Un();this.oD(a.nh.XI,null,c,null);this.Spd()};e.G8a=function(){this.$R()&&(this.LTb(),this.gh())};e.LTb=function(){var a;this.HUb();this.ug.yd(this.x0c());this.eFc();this.kFc();a=this.nRb();this.Ffd(a)};
e.WMa=function(){this.nRb();e.j.WMa.call(this)};e.nRb=function(){var a=this.YD(),b=this.GIc(),c=this.MIc(),c=this.LIc(c),d=this.IIc(a),e=this.HIc(b),g=this.PIc(c,d,e);this.dkd(g,b,d);this.tEc(b,c,e,g);return a};e.dkd=function(a,b,c){this.oc(a.Ta());this.wc(a.Ma());a=b.Ta();b=b.Ma();this.Bp.oc(a);this.Dn.oc(a);this.HQ.oc(a);this.nU.oc(a);this.AU.oc(a);this.cQ.oc(a);this.Bp.wc(b);this.Dn.wc(b);this.HQ.wc(b);this.nU.wc(b);this.AU.wc(b);this.cQ.wc(b);this.zH.oc(c.Ta());this.zH.wc(c.Ma())};e.tEc=function(a,
b,c,d){this.Pod(a);a=d.Ma()-c.Ma();this.Bp.Wa(a);this.Dn.Wa(a);this.HQ.Wa(a);this.nU.Wa(a);this.AU.Wa(a);this.cQ.Wa(a);this.ug.Ya(20);this.ug.Wa(this.Ls.Ma()+20);this.zH.Ya(40+b.Ta());this.zH.Wa(this.Ls.Ma()+20)};e.PIc=function(a,c,d){var e=b.CE(),g=b.$z(0,0);a=this.KIc(a,c);c=this.PD.uZa(this.PD.$a(),this.PD.lp().length)+10;g.oc(Math.max(a.Ta(),c,d.Ta())+60);g.wc(this.Ls.Ma()+a.Ma()+d.Ma()+40);g.oc(Math.min(e.ha()-40,g.Ta()));g.wc(Math.min(e.ka()-40,g.Ma()));return g};e.yua=function(a,b){var c=a;
b.length>a.length&&(c=b);return c};e.$Zc=function(){var a="",a=this.yua(this.Dn.$a(),a),a=this.yua(this.Bp.$a(),a),a=this.yua(this.HQ.$a(),a),a=this.yua(this.nU.$a(),a),a=this.yua(this.AU.$a(),a),a=this.yua(this.cQ.$a(),a);return" "+a+" "};e.GIc=function(){var a=this.$Zc(),c=b.$z(0,0),c=this.Dn.we();return c=this.Btc(a,c)};e.YD=function(){var a=this.oM.a_c(),c=b.$z(0,0),c=this.zH.we();return c=this.Btc(a,c)};e.MIc=function(){var a=b.$z(0,0);a.oc(this.ug.Ta());a.wc(this.ug.Ma());return a};e.IIc=function(a){var c=
b.$z(0,0),d=a.Ta()+4;a=this.oM.Jc()*(a.Ma()+4);d+=20;a+=20;d=170>d?170:d;a=70>a?70:a;a=630<a?630:a;c.oc(630<d?630:d);c.wc(a);return c};e.LIc=function(a){var c=b.$z(0,0);c.wc(a.Ma()+16);c.oc(a.Ta()+8);return c};e.KIc=function(a,c){var d=b.$z(0,0);d.wc(Math.max(a.Ma(),c.Ma()));d.oc(2+a.Ta()+2+c.Ta()+2);return d};e.HIc=function(a){var c=b.$z(0,0),d=66>a.Ta()?66:a.Ta(),e=25>a.Ma()?25:a.Ma();a.oc(d);a.wc(e);c.wc(a.Ma()+24);c.oc(3*a.Ta()+8);return c};e.Pod=function(b){b=b.Ta()+20;var c=1;this.hF&a.Er.QUa&&
(this.AU.Ya(this.Ta()-c*b),++c);this.hF&a.Er.NUa&&(this.cQ.Ya(this.Ta()-c*b),++c);this.hF&a.Er.MUa&&(this.Bp.Ya(this.Ta()-c*b),++c);this.hF&a.Er.PUa&&(this.Dn.Ya(this.Ta()-c*b),++c);this.hF&a.Er.OUa&&(this.nU.Ya(this.Ta()-c*b),++c);this.hF&a.Er.RUa&&this.HQ.Ya(this.Ta()-c*b)};e.Ffd=function(a){for(var b=0,c=a.Ma(),d=0;d<this.oM.Jc();d++)this.Y9a.push(this.PKc(this.oM.se(d),b,a)),b+=c};e.Spd=function(){switch(this.hF){case a.uL.Mxb:case a.uL.olc:this.Dn.Rf(!0,!0);break;case a.uL.plc:case a.uL.qlc:this.HQ.Rf(!0,
!0);break;case a.uL.nlc:this.cQ.Rf(!0,!0)}};e.Rva=function(a){this.Sf=a;this.Bo();b.wB(this.Wra);this.Wra=null};e.HUb=function(){for(var a=0;a<this.Y9a.length;++a)this.Y9a[a].Na(null);this.Y9a=[]};e.GVb=function(){this.G8a()};e.TOc=function(){this.Rva(a.Er.PUa)};e.PMc=function(){this.Rva(a.Er.MUa)};e.QQc=function(){this.Rva(a.Er.RUa)};e.ROc=function(){this.Rva(a.Er.OUa)};e.yPc=function(){this.Rva(a.Er.QUa)};e.nOc=function(){this.Rva(a.Er.NUa)};e.WVb=function(b,c){switch(c.cb){case a.g.Bb:case a.g.Ub:this.jrc(null);
break;case a.g.i:this.l(a.g.i)}};d.Ra(c.Vic,"PRIM_WEB","MessageBox",{za:{Title:{a:e.yI,f:function(a){this.ona(d.ja(a))}},Caption:{a:e.f3b,f:function(a){this.Lrd(d.ja(a))}},Text:{a:e.ye,f:function(a){this.oe(d.ja(a))}},Captions:{a:e.EVc},Image:{a:function(){return d.va(this.vSa,a.M6.v)},f:function(b){this.Mrd(d.ua(b,a.M6.v))}},CustomImage:{a:e.BWc,f:function(a){this.jrc(a)}},Result:{a:function(){return d.va(this.Sf,a.Er.v)}},Buttons:{a:function(){return d.va(this.hF,a.uL.v)},f:function(b){this.Uqc(d.ua(b,
a.uL.v))}},CaptionStyle:{a:e.BVc,f:function(a){this.Rod(a)}},CaptionStyles:{a:e.CVc},ButtonStyle:{a:e.Vta,f:function(a){this.HL(a)}},ButtonStyles:{a:e.tVc}},hc:{Show:e.Zza}});c.Nvb=function(b){this.Tbb=[];this.nH=[];this.fb=b;this.Fc=new c.Kx;this.Fc.ya(this,a.O.Yy,this.cia);this.Fc.ya(this,a.O.tV,this.Uib);this.bra=new c.Xl;this.bra.rb(new c.pa(0,0,100,25));this.bra.Na(this.Fc);this.bra.Ne(!1);this.bra.Pb(a.U$b)};var g=c.q(c.Nvb,c.Am);g.xw=function(){return this.Fc};g.$g=function(){return 0==this.nH.length};
g.KQ=function(a){this.nH.push(a)};g.IS=function(a){this.nH.splice(this.nH.indexOf(a),1);this.$g()&&this.Fc.Bo()};g.cia=function(){d.Ob("PRIM_LABL");for(var b=0,e=6,g=100;b<this.nH.length;b++){var n=this.Tbb[b],k=this.nH[b];n||(n=new c.Kw,n.Ya(5),n.Ne(!1),n.Wa(e),n.Oo(a.bh.wq),n.oc(320),n.wc(20),n.Df(!1),this.Tbb.push(n));n.Na(this.bra);n.sb(k.ye());n.eJc();g<n.Ta()+15&&(g=n.Ta()+15);e+=25}for(;b<this.Tbb.length;b++)n=this.Tbb[b],n.Na(null);this.bra.wc(e+6);this.bra.oc(g);this.Fc.wc(e+6);this.Fc.oc(g)};
g.Uib=function(){this.fb.pk(!0)}},{rp:["PRIM_PPNL"]});
