window.LANSA.addSrc("labl",function(d,c,a,b){a.aLb={gme:0,eLb:16};a.L6={jdd:1,$ub:1,Zub:2,Ubc:240};a.Xub={L2a:0,smc:1};c.Pw=function(){p.K.call(this);this.Pe(!1);this.kAa(!1)};var p=c.u(c.Pw,c.Sx);p.rv=a.Rp.Nia;p.rZ=a.L6.jdd;p.bra=a.Xub.L2a;p.CK=0;p.dK=0;p.kK=0;p.LJ=0;p.Hm=null;p.pU=a.ni.NL;p.Da=null;p.zy=0;p.x3=a.ae.gM;p.C$=b.zO();p.QQ=b.zO();p.Fd=p.Fd|a.uc.ela|a.uc.UKa|a.uc.Ytb|a.uc.SI|a.uc.k1|a.uc.Ztb|a.uc.RI;p.Tc=p.Tc|a.Xd.dla|a.Xd.uS|a.Xd.j1;p.R=function(){this.Hm&&(this.Hm.Ha(this,this.Tjb),
this.Hm=null);p.k.R.call(this);this.Bd(null)};p.Be=function(){return c.wyb};p.VE=function(c){this.Hm!=c&&(this.Hm&&this.Hm.Ha(this,this.Tjb),this.Hm=c,null==this.Hm?this.kAa(!1):(this.kAa(!0),this.Hm.Ia(this,this.Tjb)),this.m(a.g.j),b.qb().ee(this,!1))};p.rI=function(){return this.Hm};p.ud=function(){return 0!=(this.rZ&a.L6.$ub)?!0:!1};p.Kx=function(){return!this.Mo()&&this.ud()};p.Ff=function(c){c=this.rZ&~a.L6.$ub|(c?a.L6.$ub:0);this.rZ!=c&&(this.rZ=c,this.Id(),b.qb().ee(this,!1),this.pa(a.g.j))};
p.UZa=function(){return 0!=(this.rZ&a.L6.Zub)?!0:!1};p.luc=function(b){b=this.rZ&~a.L6.Zub|(b?a.L6.Zub:0);this.rZ!=b&&(this.rZ=b,this.ci(),this.pa(a.g.j))};p.iie=function(c){this.u_a()!=c&&(this.rZ=this.rZ&~a.L6.Ubc|c,this.Id(),b.qb().ee(this,!1),this.pa(a.g.j))};p.u_a=function(){return this.rZ&a.L6.Ubc};p.vg=function(c){this.rv!=c&&(this.rv=c,b.qb().ee(this,!1),this.pa(a.g.j))};p.Se=function(){return this.rv};p.Jf=function(){return this.CK};p.Ef=function(c){this.CK!=c&&(this.CK=c,this.Id(),b.qb().ee(this,
!1),this.pa(a.g.j))};p.Sf=function(){return this.dK};p.Bf=function(c){this.dK!=c&&(this.dK=c,this.Id(),b.qb().ee(this,!1),this.pa(a.g.j))};p.Wg=function(){return this.kK};p.we=function(c){this.kK!=c&&(this.kK=c,this.Id(),b.qb().ee(this,!1),this.pa(a.g.j))};p.$g=function(){return this.LJ};p.jg=function(c){this.LJ!=c&&(this.LJ=c,this.Id(),b.qb().ee(this,!1),this.pa(a.g.j))};p.Vu=function(c){this.pU!=c&&(this.pU=c,b.qb().ee(this),this.m(a.g.j))};p.Zc=function(){return this.Da};p.Bd=function(c){this.Da!=
c&&(null!=this.Da&&(this.Da.Ha(this,this.lp),this.Da.ub()),this.Da=c,null!=this.Da&&(this.Da.Ba(),this.Da.Ia(this,this.lp)),this.Id(),b.qb().ee(this),this.m(a.g.j))};p.Ku=function(){return this.pU};p.Mv=function(){return this.zy};p.gu=function(c){c!=this.zy&&(this.zy=c,this.Id(),this.pa(a.g.j),b.qb().ee(this))};p.vE=function(){return this.x3};p.XE=function(b){this.x3!=b&&(this.x3=b,this.Id(),this.m(a.g.j))};p.Am=function(){var b=a.Jc.jA;switch(this.li()){case a.Bh.BC:switch(this.TN()){case a.gh.Bq:b=
a.Jc.jA;break;case a.gh.qM:b=a.Jc.RO;break;default:b=a.Jc.SS}break;case a.Bh.GK:switch(this.TN()){case a.gh.Bq:b=a.Jc.SO;break;case a.gh.qM:b=a.Jc.C3a;break;default:b=a.Jc.D3a}break;default:switch(this.TN()){case a.gh.Bq:b=a.Jc.dD;break;case a.gh.qM:b=a.Jc.B3a;break;default:b=a.Jc.TO}}return b};p.AG=function(){return 0!=(this.bra&a.Xub.smc)};p.f7d=function(a){this.bra|=a};p.X$c=function(a){this.bra&=~a};p.g7d=function(a,b){this.bra=this.bra&~a|(b?a:0)};p.Lc=function(a,b,c){p.k.Lc.call(this,a,b,c);
this.ct(!1)};p.Mda=function(a){p.k.Mda.call(this,a);this.ct(a)};p.ct=function(a){p.k.ct.call(this,a);a=this.xf();this.JZb(a,!1)};p.Vk=function(){p.k.Vk.call(this);this.Dd(a.ea.DE);this.Dd(a.ea.bLa)};p.Ed=function(){this.cN(a.uc.vS,this.oS());p.k.Ed.call(this)};p.$s=function(a){null!=this.Hm?this.Hm.Tf():p.k.$s.call(this,a)};p.hg=function(){this.u7();b.qb().SF(this)};p.PG=function(){this.o_()};p.hJ=function(a){var b=!1,b=a.zc().x4a(this,this.ha.sh,this.rtb(),this.ttb(),this.stb(),a);!1==b&&p.k.hJ.call(this,
a)};p.Oe=function(b){""==b[1]&&(b[1]=a.fbc);p.k.Oe.call(this,b)};p.JZb=function(a,d){var s=b.Gc(a),k=b.Gc(s),e=null,h=0<this.zy?this.zy:-1;this.Da&&(e=this.Da.dVb(s.la()-4,s.la()-4));s.Xa(s.$()+this.CK);s.Za(s.aa()+this.dK);s.Va(s.Ka()-this.kK);s.Ja(s.Fa()-this.LJ);var f=this.ab(),t=new c.qa,p=new c.qa,l=[],r="";l[0]=t;l[1]=k;l[2]=p;l[3]=h;l[4]=h;l[5]=0;this.MNa(null,e,f,this.ye(),s,l);t=l[0];k=l[1];s=l[5];this.Da&&this.Da instanceof c.xO&&(r=this.Da.Ng());this.C$=t;this.QQ=k;d||(e=this.Ta().$a(),
h=this.Kx(),b.pe[e].hi(e,k,r,t,h,this.UZa(),s))};p.MNa=function(d,q,s,k,e,h){d=h[0];var f=h[1],t=h[2],p=h[3],l=h[4],r=h[5],f=b.Gc(e);if(null!=q&&this.Zd()){var D=a.Tg.kPa;this.rI()||(D|=a.Tg.W7a);r=D;if(this.Kx())switch(this.u_a()){case a.aLb.eLb:D|=a.Tg.ZE;break;default:D|=a.Tg.ZE,r|=a.Tg.ZE}else r|=this.rv;switch(this.li()){case a.Bh.BC:r|=a.Tg.boa;break;case a.Bh.GK:r|=a.Tg.mPa;break;default:r|=a.Tg.FHb}b.xxa(q,s,k,e,0,this.Am(),this.Am(),this.Ku(),d,f,t,0,this.Zd()?0:2,p,l,D)}else if(r=this.cUb(f),
0<s.length){f.ja()>e.ja()&&(this.Kx()?this.u_a()==a.aLb.eLb&&(f=new c.qa(0,0,e.ja(),f.la())):f=new c.qa(0,0,e.ja(),f.la()));switch(this.li()){case a.Bh.BC:f=new c.qa(e.aa()+(e.ja()-f.ja())/2,1,f.ja(),f.la());r|=a.Tg.boa;break;case a.Bh.GK:f=new c.qa(e.Ka()-f.ja(),1,f.ja(),f.la());r|=a.Tg.mPa;break;default:f=new c.qa(e.aa(),1,f.ja()+1,f.la()),r|=a.Tg.FHb}switch(this.TN()){case a.gh.Bq:f=new c.qa(f.aa(),e.$()+(e.la()-f.la())/2,f.ja(),f.la());break;case a.gh.qM:f=new c.qa(f.aa(),e.Fa()-1-f.la(),f.ja(),
f.la())}}h[0]=d;h[1]=f;h[2]=t;h[3]=p;h[4]=l;h[5]=r};p.cUb=function(c){var d=this.ye(),s=a.Tg.kPa,k=this.ab();if(0<k.length)if(this.rI()||(s|=a.Tg.W7a),this.pF=b.qX(k,d,this.Kx(),c.ja(),c.la()),this.Kx())switch(this.u_a()){case a.aLb.eLb:b.FG(k,c,s|a.Tg.ZE,d);break;default:b.FG(k,c,s|a.Tg.ZE,d),s|=a.Tg.ZE}else b.FG(k,c,s,d),s|=this.rv;return s};p.VKc=function(){var a=b.ES();this.tk(!1,!0);this.cUb(a);this.qc(a.ja())};p.fD=function(c){if(this.UZa())switch(b.Xs(c)){case a.fa.e5a:case a.fa.Rrc:case a.fa.Yrc:case a.fa.G7:case a.fa.Zrc:case a.fa.ond:case a.fa.Vod:case a.fa.Urc:case a.fa.bpd:case a.fa.g5a:c.Dm(!0);
return}p.k.fD.call(this)};p.gD=function(a){var b=this.Mo(),c=this.qq();(b||c)&&this.vpc(a,b,c)};p.vpc=function(a,d,s){var k=new c.qa,e=new c.qa(0,0,1E4,1E4);this.Kx()&&e.Va(e.aa()+a.ja()-(this.ha.Mi()+this.ha.Hj()));this.JZb(e,!0);""==this.ab()&&this.C$.eh()||(""==this.ab()?k=this.C$:(k=b.Gc(this.QQ),k.Ja(k.Fa()+(0<this.QQ.la()?1:0)),k=k.o9(this.C$)));d&&a.Va(a.aa()+this.ha.Mi()+this.dK+k.ja()+this.kK+this.ha.Hj());s&&a.Ja(a.$()+this.ha.Vj()+this.CK+k.la()+this.LJ+this.ha.kl())};p.yma=function(a,
b,c){p.k.yma(a,b,c);c[0]&&this.UZa()&&(c[0]=!1)};p.hf=function(a){b.U1a();return p.k.hf.call(this,a)};p.lp=function(c,d){switch(d.eb){case a.g.Bb:case a.g.Ub:d.Ej==this.Da&&this.Bd(null);break;case a.g.j:d.Ej==this.Da&&(b.qb().ee(this),this.Id())}};p.Tjb=function(b,c){c.eb==a.g.Ub&&this.VE(null)};p.Hv=p[a.ea.TI]=function(a){p.k.Hv.call(this,a);b.qb().ee(this,!1)};p.gQd=p[a.ea.bLa]=function(){b.qb().ee(this,!1)};p.AR=p[a.ea.DE]=function(){b.qb().ee(this,!1)};p.Mta=p[a.ea.lLa]=function(a){this.kB()?
this.Pe(!1):p.k.Mta.call(this,a)};p.zR=p[a.ea.vO]=function(){this.Hm&&this.Hm.Tf()};p.Ex=p[a.ea.eA]=function(b){this.AG()&&(this.fr(),this.X$c(a.Xub.smc));p.k.Ex.call(this,b)};d.Md(c.Pw,"PRIM_LABL",{Aa:{Ellipses:{a:function(){return d.va(this.Se(),a.Rp.v)},f:function(b){this.vg(d.wa(b,a.Rp.v))}},Caption:{a:p.ab,f:function(a){this.tb(d.ka(a))}},Alignment:{a:function(){return d.va(this.li(),a.Bh.v)},f:function(b){this.Wb(d.wa(b,a.Bh.v))}},VerticalAlignment:{a:function(){return d.va(this.TN(),a.gh.v)},
f:function(b){this.Ro(d.wa(b,a.gh.v))}},FocusControl:{a:p.rI,f:p.VE},WordWrap:{a:p.ud,f:function(a){this.Ff(d.Ca(a))}},Selectable:{a:p.UZa,f:function(a){this.luc(d.Ca(a))}},MarginLeft:{a:p.Sf,f:function(a){this.Bf(d.O(a))}},MarginTop:{a:p.Jf,f:function(a){this.Ef(d.O(a))}},MarginBottom:{a:p.$g,f:function(a){this.jg(d.O(a))}},MarginRight:{a:p.Wg,f:function(a){this.we(d.O(a))}},Image:{a:p.Zc,f:p.Bd},ImagePosition:{a:function(){return d.va(this.Ku(),a.ni.v)},f:function(b){this.Vu(d.wa(b,a.ni.v))}},ImageHeight:{a:p.Mv,
f:function(a){this.gu(d.O(a))}},ImageSizing:{a:function(){return d.va(this.vE(),a.ae.v)},f:function(b){this.XE(d.wa(b,a.ae.v))}}},Ue:{Re:"Caption"}});c.wyb=function(a){u.K.call(this,a);this.Aab=this.zy=this.ESa=this.DOb=this.COb=this.Da=this.sC=this.bsa=this.JH=this.oRb=this.nRb=this.mRb=this.fb=null};var u=c.u(c.wyb,c.mo);u.ab=function(){return this.fb.textContent};u.tb=function(a){this.fb.textContent=a};u.L5=function(){return this.fb};u.sI=function(){return this.fb};u.hi=function(b,c,s,k,e,h,f){null==
this.Da.parentElement&&this.G.appendChild(this.Da);if(null==this.Aab||this.Aab!=h)this.Aab=h,this.fb.spellcheck=!1,this.fb.setAttribute("contenteditable",h);this.Da.style.backgroundImage=d.Bx(s);switch(this.L.vE()){case a.ae.gM:this.Da.style.backgroundSize="contain";break;case a.ae.r7a:this.Da.style.backgroundSize="cover";break;case a.ae.Sg:this.Da.style.backgroundSize="100% 100%";break;case a.ae.tf:this.Da.style.backgroundSize="auto"}if(null==this.sC||this.sC!=e)this.sC=e,this.fb.style.whiteSpace=
e?"pre-wrap":"pre";if(null==this.bsa||this.bsa!=f)this.bsa=f,this.fb.style.textAlign=0!=(f&a.Tg.mPa)?"right":0!=(f&a.Tg.boa)?"center":"",0!=(f&a.Tg.jPa)||0!=(f&a.Tg.lPa)||0!=(f&a.Tg.nPa)?(this.fb.style.textOverflow="ellipsis",this.fb.style.overflow="hidden"):(this.fb.style.textOverflow="clip",this.fb.style.overflow="visible");if(null==this.mRb||this.mRb!=c.aa())this.mRb=c.aa(),this.fb.style.left=c.aa()+"px";if(null==this.nRb||this.nRb!=c.$())this.nRb=c.$(),this.fb.style.top=c.$()+"px";if(null==this.JH||
this.JH!=c.la())this.JH=c.la(),this.fb.style.height=c.la()+"px";if(null==this.oRb||this.oRb!=c.ja())this.oRb=c.ja(),this.fb.style.width=c.ja()+"px";if(null==this.COb||this.COb!=k.aa())this.COb=k.aa(),this.Da.style.left=k.aa()+"px";if(null==this.DOb||this.DOb!=k.$())this.DOb=k.$(),this.Da.style.top=k.$()+"px";if(null==this.zy||this.zy!=k.la())this.zy=k.la(),this.Da.style.height=k.la()+"px";if(null==this.ESa||this.ESa!=k.ja())this.ESa=k.ja(),this.Da.style.width=k.ja()+"px"};u.Hd=function(a,b){this.G=
document.createElement("div");this.G.setAttribute("LANSAHandle",this.hc);this.fb=document.createElement("div");var c=this.fb.style;c.position="absolute";c.outline="none";c.overflowX="hidden";c.overflowY="hidden";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";c.borderStyle="solid";c.borderLeftWidth="0px";c.borderTopWidth="0px";c.borderRightWidth="0px";c.borderBottomWidth="0px";c.cursor="inherit";c.textDecoration="inherit";this.Da=document.createElement("div");c=
this.Da.style;c.position="absolute";c.backgroundSize="contain";c.backgroundPosition="center center";c.backgroundRepeat="no-repeat";this.G.appendChild(this.fb);this.G.appendChild(this.Da);return u.k.Hd.call(this,a,b)};u.Ky=function(){var a=this;this.t_();a.fb.addEventListener("paste",function(b){a.sma(b);b.preventDefault()},!1)};u.gKb=function(a){var b="";u.k.gKb.call(this,a);"rgba(0,0,0,0)"==this.u$a&&""!=this.G.style.boxShadow&&(b=this.G.style.boxShadow);this.fb.style.textShadow=b};u.PS=function(a){u.k.PS.call(this,
a);return!this.Aab&&!b.aX()};u.sma=function(){}});
