window.LANSA.addSrc("evp",function(d,c,a,b){var p=a.Nm.nN,u=a.Qn.Jia,m=a.cg.Fv,q=a.yp.oda,s=null;a.Mw={Fxa:0,Sca:16,Dla:32,Cla:64,pla:128};a.Mw.v={NONE:a.Mw.Fxa,LEFT:a.Mw.Sca,TOP:a.Mw.Dla,RIGHT:a.Mw.Cla,BOTTOM:a.Mw.pla};a.n1={Dka:256,C_a:512,B_a:1024};a.n1.v={LEFT:a.n1.Dka,RIGHT:a.n1.C_a,CENTER:a.n1.B_a};a.o1={vCa:4096,M9a:8192,LKb:16384};a.o1.v={TOP:a.o1.vCa,BOTTOM:a.o1.M9a,CENTER:a.o1.LKb};a.Hlb={Jke:0,KKb:65536};a.VK={M0b:15,U0b:240,S0b:3840,$0b:61440,$Rd:983040,N0b:15728640,Q0b:251658240,T0b:4026531840};
a.hD={gid:0,M3a:256,N3a:512,aNa:1024,L3a:2048};a.tj={zlb:1,tlb:2,IXa:4,Clb:8,Dlb:16,ylb:32,Blb:64,KXa:128,JXa:65536,Y0b:131072,Elb:262144,xlb:524288,X0b:3840,V0b:61440,Xta:4026531840};c.Nca=function(b){k.K.call(this);this.Iqa=b;this.xq(!1);this.ltc(p);this.bl(u);this.Pj(m);this.qo(q);this.jOa(!0);this.Tc&=~a.Xd.uS;this.Tc&=~a.Xd.j1};var k=c.u(c.Nca,c.$l);k.Nb=b.zO();k.oh=0;k.nh=150;k.oj=0;k.nj=0;k.kDa=150;k.jDa=0;k.pb=null;k.IKd=null;k.RZ=null;k.yu=null;k.xC=null;k.rv=a.Rp.Nia;k.ce=null;k.uo=0;k.gg=
0;k.UNb=null;k.TNb=null;k.SNb=null;k.QOb=null;k.POb=null;k.AQ="";k.VDa="";k.mEa="";k.mQ=null;k.Fd=k.Fd|a.uc.SKa|a.uc.fxa|a.uc.l1|a.uc.ela|a.uc.UKa;k.uo=a.Nm.UF|a.Mw.Sca|a.n1.Dka|a.o1.LKb;k.gg=a.tj.IXa|a.tj.KXa|a.hD.aNa|a.tj.JXa;k.nb=function(){b.ga(this.ce);k.k.nb.call(this)};k.R=function(){k.k.R.call(this);this.SOa(null);this.Sma();this.IKd=null;this.sea(null);b.ga(this.RZ);this.RZ=null;b.ga(this.mQ);this.mQ=null};k.Aw=function(){return this.Iqa.Aw()};k.n4b=function(){return this.uo&a.VK.S0b};k.uW=
function(){return this.uo&a.VK.U0b};k.iL=function(){return this.gg&a.tj.X0b};k.o4b=function(){return this.uo&a.VK.$0b};k.nea=function(b){this.AQ!=b&&(this.AQ=b,this.ci(),this.pa(a.g.j))};k.AZa=function(){return this.AQ};k.Aua=function(){var a=[""],b=this.nc();b&&b.X4a(a);return a[0]};k.vtd=function(b){b|=this.uo&~a.VK.S0b;this.uo!=b&&(this.uo=b,this.xb(),this.pa(a.g.j),this.Ig())};k.Ytc=function(b){b|=this.gg&~a.tj.X0b;this.gg!=b&&(this.gg=b,this.xb(),this.pa(a.g.j),this.uKb(),this.Ig())};k.wtd=function(b){b|=
this.uo&~a.VK.U0b;this.uo!=b&&(this.uo=b,this.xb(),this.pa(a.g.j),this.Ig())};k.Jmd=function(){var b=new c.qa(0,0,0,0);if(this.uW()!=a.Mw.Fxa){for(var b=this.xf(),d=b.Ka(),e=b.Fa(),k=0,l=0,m,p=this.pg,q=0;q<p.length&&null!=(m=p[q]);q++)if(m!=this.jf())var s=m.Xl(),d=Math.min(d,s.aa()),e=Math.min(e,s.$()),k=Math.max(k,s.Ka()),l=Math.max(l,s.Fa());switch(this.uW()){case a.Mw.Fxa:b.Vh(d,b.la());break;case a.Mw.Sca:b.Vh(d,b.la());break;case a.Mw.Dla:b.Vh(b.ja(),e);break;case a.Mw.Cla:b.h5a(k,0);break;
case a.Mw.pla:b.h5a(0,l)}}return b};k.aob=function(){return(this.uo&a.VK.T0b)>>28};k.ltc=function(b){b=this.uo&~a.VK.T0b|b<<28;this.uo!=b&&(this.uo=b,this.xb(),this.pa(a.g.j),this.Ig())};k.oob=function(){return this.uo&a.VK.M0b};k.ztd=function(b){b|=this.uo&~a.VK.M0b;this.uo!=b&&(this.uo=b,this.xb(),this.Id(),this.pa(a.g.j),this.Ig())};k.SIa=function(){var b;switch(this.oob()){case a.Nm.UF:case a.Nm.N4:case a.Nm.UGa:b=this.rb().Nda(this.oob(),a.p6.R_a);break;case a.Nm.nN:b=this.ab()}return b};k.Atd=
function(b){b|=this.uo&~a.VK.$0b;this.uo!=b&&(this.uo=b,this.xb(),this.Id(),this.pa(a.g.j),this.Ig())};k.Y0c=function(){return this.nj};k.Jtd=function(b){this.nj!=b&&(this.nj=b,this.zCa(32767,32767),b=0,this.uW()==a.Mw.pla&&(this.e1()&&this.iL()==a.hD.L3a&&(b=17),this.jDa=this.nj,this.jDa+=b),this.xb(!0),this.Ig(),this.pa(a.g.j))};k.Z0c=function(){return this.nh};k.Etc=function(b){this.nh!=b&&(this.nh=b,this.zCa(32767,32767),b=0,this.uW()==a.Mw.Sca&&(this.e1()&&this.iL()==a.hD.M3a&&(b=17),this.kDa=
this.nh,this.kDa+=b),this.xb(!0),this.Ig(),this.pa(a.g.j))};k.$0c=function(){return this.oj};k.Mtd=function(b){this.oj!=b&&(this.oj=b,this.zCa(32767,32767),b=0,this.uW()==a.Mw.Cla&&(this.e1()&&this.iL()==a.hD.aNa&&(b=17),this.kDa=this.oj,this.kDa+=b),this.xb(!0),this.Ig(),this.pa(a.g.j))};k.a1c=function(){return this.oh};k.Otd=function(b){this.oh!=b&&(this.oh=b,this.zCa(32767,32767),b=0,this.uW()==a.Mw.Dla&&(this.e1()&&this.iL()==a.hD.N3a&&(b=17),this.jDa=this.oh,this.jDa+=b),this.xb(!0),this.Ig(),
this.pa(a.g.j))};k.$g=function(){var b=0,b=this.nj;this.e1()&&this.iL()==a.hD.L3a&&(b+=17);return b};k.Sf=function(){var b=0,b=this.nh;this.e1()&&this.iL()==a.hD.M3a&&(b+=17);return b};k.Wg=function(){var b=0,b=this.oj;this.e1()&&this.iL()==a.hD.aNa&&(b+=17);return b};k.Jf=function(){var b=0,b=this.oh;this.e1()&&this.iL()==a.hD.N3a&&(b+=17);return b};k.Af=function(){return 0!=(this.gg&a.tj.zlb)?!0:!1};k.di=function(b){b=this.gg&~a.tj.zlb|(b?a.tj.zlb:0);this.gg!=b&&(this.gg=b,this.Dd(a.ea.hLa),this.pa(a.g.j))};
k.b2c=function(){return 0!=(this.gg&a.tj.ylb)?!0:!1};k.bhe=function(b){b=this.gg&~a.tj.ylb|(b?a.tj.ylb:0);this.gg!=b&&(this.gg=b)};k.l1d=function(){return 17};k.oka=function(){return this};k.c2c=function(){var e=null;if(this.e1()){var f=this.oka();null==f.gG()&&(null==this.mQ&&(d.Ob("PRIM_PPNL"),this.mQ=new c.Tx),f.oA(this.mQ),f.gG().za(this,a.Q.Yx,this.PPc),this.trc());e=this.RZ}else f=this.oka(),null!=f.gG()&&(f.gG().za(this,a.Q.Yx,null),f.oA(null)),b.ga(this.RZ),this.RZ=null;return e};k.rb=function(){if(null==
this.pb){var b=this.Iqa;this.rU||0!=(this.gg&a.tj.Y0b)?(b.T5a(!1),this.yCa(b),b.l8(this.PJa()),b.T5a(!this.PJa())):b.T5a(!0);this.BJ(this.pb,b);this.pb=b}return this.pb};k.Gx=function(){return null};k.TR=function(){var a=null;this.jf()&&(a=this.jf().ha);return a};k.Aba=function(){var a=null;this.Gx()&&(a=this.Gx().Gh());return a};k.sna=function(b){this.Gx()&&this.Gx().Gh()!=b&&(this.Gx().Jb(b),this.m(a.g.j))};k.Mba=function(){var a=null;this.TR()&&(a=this.TR().Gh());return a};k.wna=function(b){this.TR()&&
this.TR().Gh()!=b&&(this.TR().Jb(b),this.m(a.g.j))};k.SYa=function(){var a=null;this.Gx()&&(a=this.Gx().pp());return a};k.J5a=function(b){this.Gx()&&this.Gx().pp()!=b&&(this.Gx().Bp(b),this.m(a.g.j))};k.QYa=function(){var a=null;this.Gx()&&(a=this.Gx().bB());return a};k.I5a=function(b){this.Gx()&&this.Gx().bB()!=b&&(this.Gx().UG(b),this.m(a.g.j))};k.eZa=function(){var a=null;this.TR()&&(a=this.TR().pp());return a};k.a6a=function(b){this.TR()&&this.TR().pp()!=b&&(this.TR().Bp(b),this.m(a.g.j))};k.Iua=
function(){null==this.UNb&&(this.UNb=new c.Ow(this.Gx(),a.fh.J1));return this.UNb};k.TYa=function(){null==this.TNb&&(this.TNb=new c.Ow(this.Gx(),a.fh.I1));return this.TNb};k.RYa=function(){null==this.SNb&&(this.SNb=new c.Ow(this.Gx(),a.fh.uda));return this.SNb};k.gZa=function(){null==this.QOb&&(this.QOb=new c.Ow(this.TR(),a.fh.J1));return this.QOb};k.fZa=function(){null==this.POb&&(this.POb=new c.Ow(this.TR(),a.fh.I1));return this.POb};k.JZc=function(){return this.VDa};k.vsd=function(b){this.VDa!=
b&&(this.VDa=b,this.yQa(),this.pa(a.g.j))};k.g0c=function(){return this.mEa};k.ytd=function(b){this.mEa!=b&&(this.mEa=b,this.yQa(),this.pa(a.g.j))};k.Nu=function(){return this.Af()};k.z6d=function(){return this.Zd()};k.e1=function(){return this.eca()?this.p0a()?!0:this.b2c():!1};k.p0a=function(){return!1};k.A6d=function(){var b=!1;this.uW()==a.Mw.Sca&&this.iL()==a.hD.M3a?b=!0:this.uW()==a.Mw.Cla&&this.iL()==a.hD.aNa&&(b=!0);return b};k.B6d=function(){var b=!1;this.uW()==a.Mw.Dla&&this.iL()==a.hD.N3a?
b=!0:this.uW()==a.Mw.pla&&this.iL()==a.hD.L3a&&(b=!0);return b};k.d0=function(){return 0!=(this.gg&a.tj.tlb)?!0:!1};k.aea=function(b){b=this.gg&~a.tj.tlb|(b?a.tj.tlb:0);this.gg!=b&&(this.gg=b,this.ci(),this.pa(a.g.j))};k.qm=function(){return 0!=(this.gg&a.tj.IXa)?!0:!1};k.po=function(b){b=this.gg&~a.tj.IXa|(b?a.tj.IXa:0);this.gg!=b&&(this.gg=b,this.ci(),this.pa(a.g.j))};k.Xj=function(){return 0!=(this.gg&a.tj.Clb)?!0:!1};k.Ym=function(b){b=this.gg&~a.tj.Clb|(b?a.tj.Clb:0);this.gg!=b&&(this.gg=b,this.ci(),
this.pa(a.g.j))};k.Mx=function(){return 0!=(this.gg&a.tj.Dlb)?!0:!1};k.Yu=function(b){b=this.gg&~a.tj.Dlb|(b?a.tj.Dlb:0);this.gg!=b&&(this.gg=b,this.ci(),this.pa(a.g.j))};k.ud=function(){return 0!=(this.gg&a.tj.Elb)?!0:!1};k.Ff=function(b){b=this.gg&~a.tj.Elb|(b?a.tj.Elb:0);this.gg!=b&&(this.gg=b,this.ci(),this.pa(a.g.j))};k.eca=function(){return 0!=(this.gg&a.tj.Blb)?!0:!1};k.uAa=function(b){b=this.gg&~a.tj.Blb|(b?a.tj.Blb:0);this.gg!=b&&(this.gg=b,this.ci(),this.pa(a.g.j))};k.f0c=function(){return 0!=
(this.gg&a.tj.xlb)?!0:!1};k.xtd=function(b){var c=this.gg&~a.tj.xlb|(b?a.tj.xlb:0);this.gg!=c&&(this.gg=c,this.jf().luc(b),this.pa(a.g.j))};k.mJa=function(){return 0!=(this.gg&a.tj.JXa)?!0:!1};k.REb=function(b){b=this.gg&~a.tj.JXa|(b?a.tj.JXa:0);this.gg!=b&&(this.gg=b,this.eHd(),this.pa(a.g.j))};k.PJa=function(){return 0!=(this.gg&a.tj.KXa)?!0:!1};k.Iwd=function(b){if(this.PJa()!=b){var c=null!=this.pb;this.l8(b);this.Sma();c&&this.rb();this.ci();this.pa(a.g.j)}};k.l8=function(b){b=this.gg&~a.tj.KXa|
(b?a.tj.KXa:0);this.gg!=b&&(this.gg=b,this.pa(a.g.j))};k.ej=function(){return(this.uo&a.VK.Q0b)>>24};k.bl=function(b){b=this.uo&~a.VK.Q0b|b<<24;this.uo!=b&&(this.uo=b,this.ci(),this.pa(a.g.j))};k.Vg=function(){return(this.uo&a.VK.N0b)>>20};k.Pj=function(b){b=this.uo&~a.VK.N0b|b<<20;this.uo!=b&&(this.uo=b,this.ci(),this.pa(a.g.j))};k.um=function(){return(this.gg&a.tj.V0b)>>12};k.qo=function(b){b=this.gg&~a.tj.V0b|b<<12;this.gg!=b&&(this.gg=b,this.ci(),this.pa(a.g.j))};k.eG=function(){return b.ES()};
k.IZa=function(){return this.yu};k.sea=function(b){this.yu!=b&&(null!=this.yu&&(this.yu.ub(),this.yu.Ha(this)),this.yu=b,null!=this.yu&&(this.yu.Ba(),this.yu.Ia(this,this.cXa)),this.trc(),this.Ig(),this.pa(a.g.j))};k.SOa=function(b){this.xC!=b&&(null!=this.xC&&this.xC.Ha(this),this.xC.vk(b),null!=this.xC&&this.xC.Ia(this,this.wSc),this.tk(!0),this.pa(a.g.j))};k.Npb=function(){return this.xC};k.vg=function(b){this.rv!=b&&(this.rv=b,this.jf()&&this.jf().vg(b),this.Ig(),this.pa(a.g.j))};k.Se=function(){return this.rv};
k.kb=function(){return this.rb().kb()};k.ob=function(a){this.rb().ob(a)};k.Ee=function(){this.Ga(a.Q.Dh)};k.wSd=function(){};k.X0=function(){this.Xv(this,a.ea.Jub)};k.qUb=function(){this.Iua().bt(s)};k.qtc=function(){null==s&&(s=new c.yb,s.hr(a.o.jJ),s.ir(2),s.wq(2),s.Oo(2),s.Po(2));this.Iua().Zh(s)};k.p_=function(){return this};k.eHd=function(){this.RZ&&this.RZ.Pe(this.mJa())};k.trc=function(){var a=this.yu;null==a&&(a=b.ba().ova());this.RZ&&this.RZ.Bd(a);this.oka().sJ(a)};k.lf=function(){var a=
this.c2c();if(a){var b=this.bgd();a.sb(b)}this.jf()&&(a=this.Jmd(),this.BQa(),this.jf().sb(a))};k.BQa=function(){var b=this.SIa(),c=this.jf();if(c){c.tb(b);c.Qg(this.te());switch(this.n4b()){case a.n1.Dka:c.Wb(a.Bh.qaa);break;case a.n1.C_a:c.Wb(a.Bh.GK);break;case a.n1.B_a:c.Wb(a.Bh.BC)}switch(this.o4b()){case a.o1.vCa:c.Ro(a.gh.sY);break;case a.o1.M9a:c.Ro(a.gh.qM);break;case a.o1.LKb:c.Ro(a.gh.Bq)}}};k.jf=function(){null==this.ce&&this.Zd()&&(d.Ob("PRIM_LABL"),this.ce=new c.Pw,this.ce.Oa(this),
this.ce.Ff(!1),this.ce.Pe(!1),this.ce.xq(!1),this.ce.vg(this.Se()),this.ce.we(5),this.Xb()&&this.ce.jh());return this.ce};k.Bua=function(){return b.ES()};k.bgd=function(){var b=this.Bua(),d;switch(this.iL()){case a.hD.gid:d=new c.qa(b.aa(),b.$(),0,0);break;case a.hD.M3a:d=new c.qa(b.aa()-17,b.$(),17,b.la());break;case a.hD.aNa:d=new c.qa(b.Ka(),b.$(),17,b.la());break;case a.hD.N3a:d=new c.qa(b.aa(),b.$()-17,b.ja(),17);break;case a.hD.L3a:d=new c.qa(b.aa(),b.Fa(),b.ja(),17)}return d};k.Sma=function(){var a=
this.pb;this.pb=null;this.BJ(a,null)};k.yCa=function(a){this.PJa()&&null==a.ez()&&this.l8(!1)};k.BJ=function(){};k.ip=function(b,c,d,e,l){if(d==a.Q.nB||d==a.Q.rB||d==a.Q.HG||d==a.Q.IG||d==a.Q.bJ||this.Zd()&&d==a.Q.Oq)return l;b==this.RZ&&d==a.Q.tc&&(this.xe().rI()!=this.RZ||this.mJa()||this.xe().VE(this),this.bxd(),l=!0);return k.k.ip.call(this,b,c,d,e,l)};k.Qz=function(){var a=null;this.kB()&&this.jO()&&(a=this);return a};k.zCa=function(a,c){this.nh=b.Mf(this.nh,-a,a);a=0<=this.nh?a-this.nh:a+this.nh;
this.oj=b.Mf(this.oj,-a,a);this.oh=b.Mf(this.oh,-c,c);c=0<=this.oh?c-this.oh:c+this.oh;this.nj=b.Mf(this.nj,-c,c)};k.Ema=function(){this.BQa();k.k.Ema.call(this)};k.Ama=function(){this.BQa();k.k.Ama.call(this)};k.hta=function(){var a=this.Aw();return a&&(a=a.uv)?new c.Axa(a):null};k.Ed=function(){this.cN(a.uc.vS,this.oS());k.k.Ed.call(this)};k.yQa=function(){};k.PPc=function(a,b){this.YXa();b.uk("CONTINUE",!1)};k.wSc=function(b,c){c.eb==a.g.Ub?this.SOa(null):c.eb==a.g.j&&this.tk(!0)};k.cXa=function(b,
c){switch(c.eb){case a.g.Bb:case a.g.Ub:c.Ej==this.yu&&this.sea(null);break;case a.g.j:c.Ej==this.yu&&this.Ig()}};k.ckb=k[a.ea.hLa]=function(){this.ci()};k.OYb=k[a.ea.Jub]=function(){var a=null!=this.pb;this.Sma();a&&this.rb();this.ci()};k.FC=k[a.ea.wS]=function(a){this.Vn()||this.ZHa();k.k.FC.call(this,a)};k.GC=k[a.ea.xS]=function(a){var b=a.ad;this.Tia();b.ng()&&k.k.GC.call(this,a)};k.ZQc=k[a.ea.Jac]=function(a){this.e1()&&(this.bxd(),a.Uf=!0)};k.AR=k[a.ea.DE]=function(){this.xb();this.Ig()};k.pHa=
k[a.ea.kLa]=function(b){var c=!1,d="";switch(this.aob()){case a.Nm.UF:case a.Nm.N4:case a.Nm.UGa:this.rb().Nda(this.aob(),a.p6.$qb,d);break;case a.Nm.nN:d=this.bL()}""!=d&&(b.pd.fb=d,c=!0);c||k.k.pHa.call(this,b)};d.Md(c.Nca,"PRIM_EVP",{eE:"PRIM_CTRL",Aa:{Placeholder:{a:k.AZa,f:function(a){this.nea(d.ka(a))}},UsePicklist:{a:k.PJa,f:function(a){this.Iwd(d.Ca(a))}},LabelSelectable:{a:k.f0c,f:function(a){this.xtd(d.Ca(a))}},MarginLeft:{a:k.Z0c,f:function(a){this.Etc(d.O(a))}},MarginTop:{a:k.a1c,f:function(a){this.Otd(d.O(a))}},
MarginBottom:{a:k.Y0c,f:function(a){this.Jtd(d.O(a))}},MarginRight:{a:k.$0c,f:function(a){this.Mtd(d.O(a))}},Caption:{a:k.ab,f:function(a){this.tb(d.ka(a))}},HintType:{a:k.aob,f:k.ltc},LabelType:{a:function(){return d.va(this.oob(),a.Nm.v)},f:function(b){this.ztd(d.wa(b,a.Nm.v))}},LabelText:{a:k.SIa},LabelPosition:{a:function(){return d.va(this.uW(),a.Mw.v)},f:function(b){this.wtd(d.wa(b,a.Mw.v))}},LabelHorAlignment:{a:function(){return d.va(this.n4b(),a.n1.v)},f:function(b){this.vtd(d.wa(b,a.n1.v))}},
LabelVerAlignment:{a:function(){return d.va(this.o4b(),a.o1.v)},f:function(b){this.Atd(d.wa(b,a.o1.v))}},ReadOnly:{a:k.Af,f:function(a){this.di(d.Ca(a))}},Ellipses:{a:k.Se,f:k.vg},EditThemeDrawStyle:{a:k.JZc,f:function(a){this.vsd(d.ka(a))}},LabelThemeDrawStyle:{a:k.g0c,f:function(a){this.ytd(d.ka(a))}}}});var e=k;e.aD=e.applyDefault=function(){this.rb().raa()}});
