window.LANSA.addSrc("atlm",function(d,c,a,b,p){d.Ob("PRIM_CPST");a.Tha={jHc:0,mTb:1,iHc:2,lTb:4,kHc:8,tMd:15};a.CX={jBb:0,Ypc:1,Xpc:2,Kjd:3};a.CX.v={VERTICAL:a.CX.jBb,HORIZONTAL:a.CX.Ypc,DISPLAYPOSITION:a.CX.Xpc,EO:a.CX.Kjd};a.nLa={MJd:0,zLb:1,KJd:2,OJd:3,LJd:4,NJd:5,Lme:6};a.q9d={L2a:0,M2a:1};a.Hhb={nub:32};c.mgc=function(b,c,d){u.K.call(this);this.Tb=[];this.Tb=c;this.Dj=this.ek=d;this.dEa=this.XFa=0;this.zY=a.Tha.jHc};var u=c.u(c.mgc,c.kf);u.R=function(){u.k.R.call(this)};c.HLa=function(){m.K.call(this);
this.KTa=a.CX.jBb};d.Ob("PRIM_TBLO");var m=c.u(c.HLa,c.VLa);m.R=function(){m.k.R.call(this)};m.j1d=function(){return this.KTa};m.Eud=function(b){this.KTa!=b&&(this.KTa=b,this.m(a.g.j))};m.Zda=function(a,b){var c=this.Fya(a);c.Zda(b);return c};m.jW=function(a){return this.Lg(a).jW()};m.NTd=function(a){return this.Lg(a)};m.sob=function(){return a.nLa.zLb};m.Mo=function(b,c){var d=m.k.Mo.call(this,b,c);if(d){var e=this.Lg(b);!e||e.jW()!=a.bj.Uha&&e.jW()!=a.bj.Rha||(d=!1)}return d};m.qq=function(b,c){var d=
m.k.qq.call(this,b,c);if(d){var e=this.Lg(b);!e||e.jW()!=a.bj.xaa&&e.jW()!=a.bj.Sha||(d=!1)}return d};m.NWc=function(a){return this.Lg(a)};m.lN=function(a,b,c,e){e===p&&(e=!0);a=d.Bc("PRIM_ATLI");a.wk(b);e&&a.Oa(this);return a};m.vfd=function(a,b){return b=this.lf(a,void 0)};m.fVb=function(a){var b=new c.M1a;b.wk(a);return b};m.lf=function(b,d){for(var k=this.hE(b,!0);;){var e=new c.mgc(0,k,d);e.Dj.Xa(e.Dj.Te()+this.oh);e.Dj.Za(e.Dj.ve()+this.nh);e.Dj.Va(e.Dj.Vt()-this.oj);e.Dj.Ja(e.Dj.yN()-this.nj);
switch(this.KTa){case a.CX.jBb:this.PV(e,a.bj.Uha);this.PV(e,a.bj.Rha);this.PV(e,a.bj.xaa);this.PV(e,a.bj.Sha);this.PV(e,a.bj.IK);break;case a.CX.Ypc:this.PV(e,a.bj.xaa);this.PV(e,a.bj.Sha);this.PV(e,a.bj.Uha);this.PV(e,a.bj.Rha);this.PV(e,a.bj.IK);break;case a.CX.Xpc:for(var h=null,f=k,m=0;m<f.length&&null!=(h=f[m]);m++){var p=h;p.jfa!=a.bj.IK&&0==(h.ma().vb&a.Hhb.nub)&&this.Kgb(e,p)}this.PV(e,a.bj.IK)}if(0==e.XFa&&0==e.dEa)break;d.n8(e.XFa,e.dEa)}return new c.AO(d.ja(),d.la())};m.PV=function(b,
c){var d=null,e=b.Tb;switch(c){case a.bj.Uha:case a.bj.xaa:case a.bj.IK:for(var h=0;h<e.length&&null!=(d=e[h]);h++){var f=d;if(f.jfa==c){var m=d.ma();0==(m.vb&a.Hhb.nub)&&this.Kgb(b,f)}}break;case a.bj.Rha:case a.bj.Sha:for(h=e.length-1;0<=h&&null!=(d=e[h]);h--)f=d,f.jfa==c&&(m=d.ma(),0==(m.vb&a.Hhb.nub)&&this.Kgb(b,f))}};m.Kgb=function(b,c){var d=c.p3b(),e,h;switch(c.jfa){case a.bj.Uha:h=0;b.zY|=a.Tha.mTb;0!=c.JZ&&d.Vh(d.ja(),b.ek.la()*c.JZ/100);d.Rb(b.Dj.aa()+c.Sf(),b.Dj.$()+c.Jf());b.Dj.h5a(b.Dj.aa(),
b.Dj.$()+d.la()+c.Jf()+c.$g());e=b.Dj.ja()-(c.Sf()+c.Wg());d.Vh(Math.max(e,0),d.la());this.Qsa(c,d);0<h&&(h>b.Dj.la()&&(d=h-b.Dj.la(),d>b.dEa&&(b.dEa=d)),b.Dj.dsc(0,h));break;case a.bj.Rha:h=0;b.zY|=a.Tha.iHc;0!=c.JZ&&d.Vh(d.ja(),b.ek.la()*c.JZ/100);e=b.Dj.la()-(d.la()+c.Jf()+c.$g());0!=(b.zY&a.Tha.mTb)&&(e=Math.max(e,0));b.Dj.Vh(b.Dj.ja(),e);d.Rb(b.Dj.aa()+c.Sf(),b.Dj.Fa()+c.Jf());e=b.Dj.ja()-(c.Sf()+c.Wg());d.Vh(Math.max(e,0),d.la());this.Qsa(c,d);0<h&&(h>b.Dj.la()&&(d=h-b.Dj.la(),d>b.dEa&&(b.dEa=
d)),b.Dj.n8(0,-h));break;case a.bj.xaa:h=0;b.zY|=a.Tha.lTb;0!=c.JZ&&d.Vh(b.ek.ja()*c.JZ/100,d.la());d.Rb(b.Dj.aa()+c.Sf(),b.Dj.$()+c.Jf());e=b.Dj.aa()+d.ja()+c.Sf()+c.Wg();b.Dj.h5a(Math.max(e,b.ek.aa()),b.Dj.$());e=b.Dj.la()-(c.Jf()+c.$g());d.Vh(d.ja(),Math.max(e,0));this.Qsa(c,d);0<h&&(h>b.Dj.ja()&&(d=h-b.Dj.ja(),d>b.XFa&&(b.XFa=d)),b.Dj.dsc(h,0));break;case a.bj.Sha:h=0;b.zY|=a.Tha.kHc;0!=c.JZ&&d.Vh(b.ek.ja()*c.JZ/100,d.la());e=b.Dj.ja()-(d.ja()+c.Sf()+c.Wg());0!=(b.zY&a.Tha.lTb)&&(e=Math.max(e,
0));b.Dj.Vh(e,b.Dj.la());d.Rb(b.Dj.Ka()+c.Sf(),b.Dj.$()+c.Jf());e=b.Dj.la()-(c.Jf()+c.$g());d.Vh(d.ja(),Math.max(e,0));this.Qsa(c,d);0<h&&(h>b.Dj.ja()&&(d=h-b.Dj.ja(),d>b.XFa&&(b.XFa=d)),b.Dj.n8(-h,0));break;case a.bj.IK:d.Rb(b.Dj.aa()+c.Sf(),b.Dj.$()+c.Jf()),e=b.Dj.ja()-(c.Sf()+c.Wg()),h=b.Dj.la()-(c.Jf()+c.$g()),d.Vh(Math.max(e,0),Math.max(h,0)),this.Qsa(c,d)}};m.BBb=function(b,c){var d=this.NWc(b);if(d){if(d.jW()==a.bj.Uha||d.jW()==a.bj.Rha)c[0]=!0;if(d.jW()==a.bj.xaa||d.jW()==a.bj.Sha)c[1]=!0}};
d.Md(c.HLa,"PRIM_ATLM",{Aa:{MarginTop:{a:m.Jf,f:function(a){this.Ef(d.O(a))}},MarginBottom:{a:m.$g,f:function(a){this.jg(d.O(a))}},MarginLeft:{a:m.Sf,f:function(a){this.Bf(d.O(a))}},MarginRight:{a:m.Wg,f:function(a){this.we(d.O(a))}},MaxHeight:{a:m.qZa,f:function(a){this.iAa(d.O(a))}},MaxWidth:{a:m.rZa,f:function(a){this.hea(d.O(a))}},MinHeight:{a:m.tZa,f:function(a){this.jAa(d.O(a))}},MinWidth:{a:m.uZa,f:function(a){this.jea(d.O(a))}},ProcessingOrder:{a:function(){return d.va(this.KTa,a.CX.v)},f:function(b){this.Eud(d.wa(b,
a.CX.v))}}}})});window.LANSA.addSrc("atli",function(d,c,a,b){a.bj={wTb:0,Uha:1,Rha:2,xaa:3,Sha:4,IK:5,VIc:6};a.bj.v={NONE:a.bj.wTb,TOP:a.bj.Uha,BOTTOM:a.bj.Rha,LEFT:a.bj.xaa,RIGHT:a.bj.Sha,CENTER:a.bj.IK,EO:a.bj.VIc};a.XIc={Psa:0};c.M1a=function(){p.K.call(this);this.JZ=0;this.jfa=a.bj.wTb;this.zY=a.XIc.Psa};var p=c.u(c.M1a,c.WLa);b.N1a=function(a,b,d){var p=new c.M1a;p.Oa(a);p.wk(b);p.Zda(d);return p};p.R=function(){p.k.R.call(this)};p.sob=function(){return a.nLa.zLb};p.jW=function(){return this.jfa};p.Zda=function(b){this.jfa!=
b&&(this.jfa=b,this.m(a.g.j))};p.O0d=function(){return this.JZ};p.$ge=function(b){0>b?b=0:100<b&&(b=100);this.JZ!=b&&(this.JZ=b,this.m(a.g.j))};p.fsb=function(b){var c=!1;if(null!=this.gb&&this.gb.W()===b)if(this.gb.Zd()){if(this.gb.up()||this.jfa==a.bj.IK)c=!0}else this.gb.up()&&(c=!0);return c};p.G8b=function(a,b,c){this.Oa(a);this.wk(b);this.Zda(c)};d.Md(c.M1a,"PRIM_ATLI",{Aa:{MarginTop:{a:p.Jf,f:function(a){this.Ef(d.O(a))}},MarginBottom:{a:p.$g,f:function(a){this.jg(d.O(a))}},MarginLeft:{a:p.Sf,
f:function(a){this.Bf(d.O(a))}},MarginRight:{a:p.Wg,f:function(a){this.we(d.O(a))}},MaxHeight:{a:p.qZa,f:function(a){this.iAa(d.O(a))}},MaxWidth:{a:p.rZa,f:function(a){this.hea(d.O(a))}},MinHeight:{a:p.tZa,f:function(a){this.jAa(d.O(a))}},MinWidth:{a:p.uZa,f:function(a){this.jea(d.O(a))}},Manage:{a:p.ma,f:p.wk},Parent:{a:p.W,f:p.Oa},Attachment:{a:function(){return d.va(this.jW(),a.bj.v)},f:function(b){this.Zda(d.wa(b,a.bj.v))}}}})});
