window.LANSA.addSrc("wdgt",function(d,c,a,b,p){var u={};c.fmc=function(a){m.K.call(this);this.mSa=a;this.yab=function(){};this.rU=this.fPb=!1;this.FPb=[];this.EPb=[];this.APb=[];this.zPb=[];this.CPb=[]};var m=c.u(c.fmc,c.kf);m.dX=function(){return this.fPb};m.wh=function(){return this.mSa.nm};m.O2c=function(){return this.mSa.js||[]};m.E3c=function(){return this.mSa.st||[]};m.ZYc=function(){return this.mSa.fn};m.UZc=function(){return this.mSa.fe};m.r5=function(){return this.yab};m.Ekd=function(){function a(){if(m<
p.length){var c=p[m],e=document.createElement("script");e.type="text/javascript";e.onload=function(){e.onload=null;e.onerror=null;m++;a()};e.onerror=function(){e.onload=null;e.onerror=null;throw"Error defining Widget "+d+", failed to load script: "+c;};document.body.appendChild(e);e.src=c}else b()}function b(){function a(){if(!c.fPb){for(c.fPb=!0;0<c.zPb.length;){var b=c.zPb.shift();c.asb(b)}for(;0<c.EPb.length;)b=c.EPb.shift(),c.csb(b.vLb,b.eLd,b.value);for(;0<c.CPb.length;)b=c.CPb.shift(),c.T8b(b.vLb,
b.parent);for(;0<c.FPb.length;)b=c.FPb.shift(),c.dsb(b);for(;0<c.APb.length;)b=c.APb.shift(),c.bsb(b)}}var d=c.ZYc(),f=c.yab.prototype;e&&e(f);var l={Loading:{},Completed:{},Finalize:function(){a()}};d(f,l)!==l.Loading&&a()}var c=this,d=c.wh(),e=c.UZc();u[d]=c;for(var f=c.E3c(),l=0;l<f.length;l++){var h=f[l],k=document.createElement("link");k.type="text/css";k.rel="stylesheet";k.href=h;document.body.appendChild(k)}var m=0,p=c.O2c();a()};m.csb=function(a,b,c){if(this.dX()){var e=a["set"+b];if(!e)throw d.uld("set"+
b);e&&e.call(a,c)}else this.EPb.push({vLb:a,eLd:b,value:c})};m.bsb=function(a){this.dX()?a.XXa():this.APb.push(a)};m.asb=function(a){if(this.dX()){var b=a.onCreateInstance;b&&b.call(a)}else this.zPb.push(a)};m.T8b=function(a,b){if(this.dX()){var c=a.onRealizeControl;if(!c)throw d.tld();c.call(a,b)}else this.CPb.push({vLb:a,parent:b})};m.dsb=function(a){if(this.dX()){var b=a.onSizeChanged;b&&b.call(a)}else this.FPb.push(a)};c.q2a=function(){q.K.call(this)};var q=c.u(c.q2a,c.$l);q.Tc|=a.Xd.RKa;q.Qz=
function(){return this.Ta()&&this.Ta().t6c()?this:null};q[a.ea.az]=function(b){var c=!1;this.Ta()&&(c=b.ad!==p?b.ad:a.fa.gP,c=c==a.fa.gP||c==a.fa.lA||c==a.fa.TE?this.Ta().d2b(null):this.Ta().e2b(null));c||q.k.yR.call(this,b)};q[a.ea.eLa]=function(b){var c=!1;this.Ta()&&(c=(b.ad!==p?b.ad:a.fa.gP)==a.fa.gP?this.Ta().d2b(document.activeElement):this.Ta().e2b(document.activeElement));c||q.k.bkb.call(this,b)};c.Gkc=function(){s.K.call(this)};var s=c.u(c.Gkc,c.qd);d.Md(c.Gkc,"PRIM_WDGT",{});c.Ikc=function(){k.K.call(this);
var a=this.JYa(),a=this.i_=u[a],b=this.KM=new (a.r5());b.LANSA_Component=this;b.LANSA_Class=a;a.asb(b)};var k=c.u(c.Ikc,c.qd);k.$rb=function(a,b){if(this.i_.dX()){var c=this.KM[a];if(!c)throw d.Mqc(a);return c.apply(this.KM,b)}throw d.J4a();};k.nJa=function(a){if(this.i_.dX()){var b=this.KM["get"+a];if(!b)throw d.Kqc("get"+a);return b.call(this.KM)}throw d.J4a();};k.yOa=function(a,b){this.i_.csb(this.KM,a,b)};k.X0=function(){var a=this;setTimeout(function(){a.i_.bsb(a)},5)};k.XXa=function(){this.Ga(a.Q.xca)};
d.Sa(c.Ikc,"PRIM_WDGT","Object",{});var e=k;e.get=e.nJa;e.set=e.yOa;e.invoke=e.$rb;c.Hkc=function(){h.K.call(this);var b=this.JYa(),b=this.i_=u[b],c=this.KM=new (b.r5());c.LANSA_Component=this;c.LANSA_Class=b;b.asb(c);this.Tc&=~a.Xd.uS;this.Tc&=~a.Xd.j1};var h=c.u(c.Hkc,c.q2a);h.Be=function(){return c.emc};h.Lc=function(a,c,d){h.k.Lc.call(this,a,c,d);a=this.Ta().$a();b.pe[a].tdd(this.KM)};h.$rb=function(a,b){if(this.i_.dX()){var c=this.KM[a];if(!c)throw d.Mqc(a);return c.apply(this.KM,b)}throw d.J4a();
};h.nJa=function(a){if(this.i_.dX()){var b=this.KM["get"+a];if(!b)throw d.Kqc("get"+a);return b.call(this.KM)}throw d.J4a();};h.yOa=function(a,b){this.i_.csb(this.KM,a,b)};h.Eae=function(){this.XXa()};h[a.ea.kla]=function(){this.i_.bsb(this)};h[a.ea.TI]=function(){this.Xb()&&this.i_.dsb(this.KM)};h.Nma=function(){h.k.Nma.call(this);this.Xb()&&this.i_.dsb(this.KM)};d.Sa(c.Hkc,"PRIM_WDGT","Control",{});e=h;e.get=e.nJa;e.set=e.yOa;e.invoke=e.$rb;c.rkc=function(){f.K.call(this);this.Nb=b.Nf(0,0,100,100);
this.f$=this.ASa=""};var f=c.u(c.rkc,c.q2a);f.Be=function(){return c.olc};f.L_c=function(){return this.ASa};f.etd=function(b){this.ASa!=b&&(this.ASa=b,this.pa(a.g.j),this.Id())};f.LC=function(){return this.f$};f.mna=function(a){this.f$=a};f.gD=function(a){var d=this.Mo(),e=this.qq();if(d||e){var f=new c.qa;new c.qa(0,0,1E4,1E4);var l=[];l[0]=d;l[1]=e;l[2]=a;l[3]=0;l[4]=0;var h=this.$a();l[3]=0;l[4]=0;null!=h&&b.pe[h].Vzc(l);f.Va(l[3]);f.Ja(l[4]);d&&a.Va(a.aa()+this.ha.Mi()+f.ja()+this.ha.Hj());e&&
a.Ja(a.$()+this.ha.Vj()+f.la()+this.ha.kl())}};d.Sa(c.rkc,"PRIM_WEB","HtmlContainer",{Aa:{Html:{a:f.L_c,f:function(a){this.etd(d.ka(a))}},Description:{a:f.LC,f:function(a){this.mna(d.ka(a))}}},Ue:{Re:"Html"}});c.E2a=function(a){t.K.call(this,a)};var t=c.u(c.E2a,c.mo);t.$Ja=function(){return!1};t.t6c=function(){return 0<this.eib().length};t.PS=function(a){t.k.PS.call(this,a);return!1};t.d2b=function(a){var b=this.eib();for(a=a?b.indexOf(a)+1:0;0<=a&&a<b.length;){var c=b[a];if(c&&(c.focus(),c==document.activeElement))return!0;
a++}return!1};t.e2b=function(a){var b=this.eib();for(a=a?b.indexOf(a)-1:b.length-1;0<=a;){var c=b[a];if(c&&(c.focus(),c==document.activeElement))return!0;a--}return!1};t.eib=function(){var a=[],b=[];this.Loc(this.G,b);for(var c=1;c<b.length;c++)a=a.concat(b[c]||[]);return a=a.concat(b[0]||[])};t.Loc=function(a,b){var c=a.tabIndex;0<=c&&(b[c]===p&&(b[c]=[]),b[c].push(a));for(var c=a.childNodes,d=0;d<c.length;d++)a=c[d],this.Loc(a,b)};t.eba=t[a.Ra.MT]=function(b){b.Uf=a.Ra.mia|a.Ra.uWa};c.emc=function(a){A.K.call(this,
a);this.gb=null};var A=c.u(c.emc,c.E2a);A.Hd=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.hc);this.G.setAttribute("LANSAHandle",this.hc);return A.k.Hd.call(this,a,b)};A.tdd=function(a){null==this.gb&&(this.gb=document.createElement("div"),this.gb.style.left="0px",this.gb.style.top="0px",this.gb.style.width="100%",this.gb.style.height="100%",a.LANSA_Class.T8b(a,this.gb),this.G.appendChild(this.gb))};c.olc=function(a){l.K.call(this,a);this.gb=null};var l=c.u(c.olc,
c.E2a);l.Iz=function(){l.k.Iz.call(this);this.G.style.whiteSpace="normal"};l.Hd=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.hc);this.G.setAttribute("LANSAHandle",this.hc);this.gb=document.createElement("div");this.gb.style.left="0px";this.gb.style.top="0px";this.gb.style.width="100%";this.gb.style.height="100%";this.gb.innerHTML=this.L.ASa;this.G.appendChild(this.gb);return l.k.Hd.call(this,a,b)};l.RGd=function(){var a=this.L.Mo(),b=this.L.qq();this.gb.style.width=
a?"":"100%";this.gb.style.height=b?"":"100%";this.gb.innerHTML=this.L.ASa};l.Lc=function(){l.k.Lc.call(this);this.RGd()};l.Vzc=function(a){var b=a[0],c=a[2],d=this.gb.style.width;a[1]&&!b&&(this.gb.style.width=c.ja()+"px");a[3]=this.gb.clientWidth;a[4]=this.gb.clientHeight;this.gb.style.width=d}});
