window.LANSA.addSrc("ppnl",function(e,c,a,b,m){e.Gb("PRIM_PHBN");e.Gb("PRIM_IMAG");e.Gb("PRIM_TBLO");a.Aqa=9999;a.Zgb={oza:0,U1b:3};a.jJ={c5:0,Pma:1,Q1b:2};a.jJ.v={NONE:a.jJ.c5,POPUP:a.jJ.Pma};a.Zj={Rib:8321,WPa:1,Nib:2,Yib:4,Tib:8,Oib:16,Qib:32,Sib:64,Uib:128,Xib:256,Pib:512,Wib:1024,bGd:2048,Vib:4096,w4b:8192};a.jca={IZ:0,HQ:1,IQ:2};a.cFd={x4b:0};a.dL={G1a:0,C1a:268435456,I1a:536870912};a.dL.v={HIDDEN:a.dL.G1a,ALL:a.dL.C1a,NONE:a.dL.I1a};a.hna={NQc:0,fib:1,d3b:805306368};a.Nf={XV:0,$pa:1,oUa:3,
pUa:4,Gqb:5,Kbc:6,Hqb:7,Cbc:8,Dbc:9,Gbc:10,Mbc:11,Hbc:12,Ebc:13,Fbc:14,Ibc:15,Jbc:16,Lbc:17};a.Nf.v={NONE:a.Nf.XV,FADEINANDSCALE:a.Nf.$pa,SLIDEINLEFT:a.Nf.oUa,SLIDEINRIGHT:a.Nf.pUa,SLIDEINBOTTOM:a.Nf.Gqb,NEWSPAPER:a.Nf.Kbc,SLIDEINTOP:a.Nf.Hqb,"3DFLIPHORIZONTAL":a.Nf.Cbc,"3DFLIPVERTICAL":a.Nf.Dbc,"3DSIGN":a.Nf.Gbc,SUPERSCALED:a.Nf.Mbc,"3DSLIT":a.Nf.Hbc,"3DROTATEBOTTOM":a.Nf.Ebc,"3DROTATEINLEFT":a.Nf.Fbc,LETMEIN:a.Nf.Ibc,MAKEWAY:a.Nf.Jbc,SLIPFROMTOP:a.Nf.Lbc};a.Nf.$ya={NONE:a.Nf.XV,FADEINANDSCALE:a.Nf.$pa};
a.Nf.TCd={NONE:a.Nf.XV,FADEIN:a.Nf.$pa,SLIDEINLEFT:a.Nf.oUa,SLIDEINRIGHT:a.Nf.pUa,SLIDEINTOP:a.Nf.Hqb,SLIDEINBOTTOM:a.Nf.Gqb};a.Nf.oHb={"":a.Nf.XV,"md-effect-1":a.Nf.$pa,"md-effect-21":a.Nf.oUa,"md-effect-2":a.Nf.pUa,"md-effect-3":a.Nf.Gqb,"md-effect-4":a.Nf.Kbc,"md-effect-7":a.Nf.Hqb,"md-effect-8":a.Nf.Cbc,"md-effect-9":a.Nf.Dbc,"md-effect-10":a.Nf.Gbc,"md-effect-11":a.Nf.Mbc,"md-effect-13":a.Nf.Hbc,"md-effect-14":a.Nf.Ebc,"md-effect-15":a.Nf.Fbc,"md-effect-17":a.Nf.Ibc,"md-effect-18":a.Nf.Jbc,"md-effect-19":a.Nf.Lbc};
c.qZb=function(a){p.w.call(this,a);this.Gc=a};var p=c.u(c.qZb,c.S4);p.vb=function(){p.j.vb.call(this)};p.U=function(){this.$a.YZ();p.j.U.call(this)};p.ha=function(){return this.Gc.rb()};p.Pa=function(){return null};p.eba=function(){return!0};p.b6=function(){};p.Cda=function(){};p.Bda=function(){};p.ix=function(){};p.Yu=function(){};p.Aka=function(){return null};p.yG=function(){return!1};p.Cd=function(){return!0};p.oQ=function(){return!0};p.xG=function(){return!1};p.xU=function(){return!1};p.se=function(b){b[0]=
a.ZMa;b[1]=a.XMa};p.vgd=function(){};p.gT=function(a){p.j.gT.call(this,a)};p.Hic=function(){return!1};p.Jca=function(){};p.Gf=function(){};p.q5=function(){};p.Tu=function(){};p.t5=function(){};p.UA=function(){};c.Zw=function(){e.Gb("PRIM_IMAG");e.Gb("PRIM_TBLO");e.Gb("PRIM_LABL");l.w.call(this);this.nd=b.zd(10,10,280,120);this.of=a.Zj.Rib;this.Wl=this.Oh=this.GR=this.sn=null;this.Lx=a.Nf.XV;this.fX=a.Ci.bx;this.uFa=this.eX=this.dX=null;this.Ff=new c.ld(0,0);this.nZa=this.S8=this.xt=this.nA=this.FB=
this.az=this.sa=this.cr=this.zO=this.rn=null;this.hGa="";this.mZa=12;this.Bha=a.m.Ub;b.W().eIc(this);this.zic();b.W().duc();var d=null;this.sa=new c.Vv;b.Ho(this.sa);b.eo(this.sa);this.cr=new c.jn;this.cr.kb(new c.ga(0,0,0,30));this.cr.Ef(!1);this.cr.et(!1);this.cr.gm(this.sa);this.cr.Dda();this.az=new c.Yt;this.az.Ef(!1);this.az.FJ(a.je.jH);this.az.Na(this.cr);this.az.PE(a.ie.BE);this.FB=new c.Yt;this.FB.FJ(a.je.ESa);this.FB.Na(this.cr);this.FB.Ef(!1);this.FB.wa(this,a.G.$b,this.fpc);this.FB.wa(this,
a.G.AM,this.gpc);this.FB.wa(this,a.G.BM,this.hpc);this.nA=new c.Ws;this.nA.Na(this.cr);this.nA.Ef(!1);this.nA.Kn(a.Vg.oq);this.nA.Re(!1);this.nA.Hf(a.xo.pHb);b.Ic(this.sa,this.cr,null,null,1,1);d=b.Ic(this.sa,this.az,this.sa.wc(0),this.sa.zc(0),1,1);d.yb(a.qa.Ek);d.Qb(a.ja.Xi);d.re(2);d=b.Ic(this.sa,this.FB,this.sa.wc(0),this.sa.zc(0),1,1);d.yb(a.qa.Bw);d.Qb(a.ja.Xd);d.Ud(2);d=b.Ic(this.sa,this.nA,this.sa.wc(0),this.sa.zc(0),1,1);d.yb(a.qa.Ve);d.Qb(a.ja.Xi);this.Ef(!1);this.Chb(c.MNa)};var l=c.u(c.Zw,
c.jn);l.vb=function(){b.la(this.wfd);this.wfd=null;b.la(this.cr);this.cr=null;b.la(this.az);this.az=null;b.la(this.FB);this.FB=null;b.la(this.nA);this.nA=null;l.j.vb.call(this)};l.U=function(){l.j.U.call(this);this.oda(null);this.PQa(null);this.JRa(null);this.KRa(null);this.nda(null);this.rmb(null);b.W().WTc(this);b.la(this.Wl);this.Wl=null;b.la(this.uFa);this.uFa=null};l.eh=function(){var a=c.X4;this.YL()&&(a=c.H0b);return a};l.Yud=function(){return this.fX};l.tka=function(){if(null==this.uFa){var a=
new c.qZb(this);this.uFa=b.Xba(a);this.Ea(this,this.krc)}return this.uFa};l.oda=function(b){this.sn!=b&&(this.sn&&this.sn.Da(this),(this.sn=b)&&this.sn.Ea(this,this.eDb),this.l(a.f.h))};l.Mxc=function(){return this.sn};l.paa=function(){var a=null;this.sn&&this.sn instanceof c.Vs&&(a=this.sn);return a};l.PQa=function(b){this.GR!=b&&(this.GR&&this.GR.Da(this),(this.GR=b)&&this.GR.Ea(this,this.Loc),this.l(a.f.h))};l.snd=function(){return this.GR};l.JRa=function(b){this.dX!=b&&(this.dX&&this.dX.Da(this),
(this.dX=b)&&this.dX.Ea(this,this.irc),this.l(a.f.h))};l.Wud=function(){return this.dX};l.KRa=function(b){this.eX!=b&&(this.eX&&this.eX.Da(this),(this.eX=b)&&this.eX.Ea(this,this.jrc),this.l(a.f.h))};l.Xud=function(){return this.eX};l.rb=function(){var a=this.Oh;!this.Oh||this.Oh instanceof c.Zw||(a=this.Oh);!a&&this.pbb()&&(a=this);return a};l.rpd=function(){return this.Oh};l.IY=function(){null==this.Wl&&(this.Wl=new c.$ba,this.Wl.V7b(),this.Wl.sBa(a.gv.jUa));return this.Wl};l.kCc=function(){return this.Wl};
l.kwd=function(){return this.Ff};l.Zn=function(){this.gh();return this.gg};l.N5=function(b){b=this.of&~a.Zj.Nib|(b?a.Zj.Nib:0);this.of!=b&&(this.of=b,this.l(a.f.h))};l.Zna=function(b){b=this.of&~a.Zj.WPa|(b?a.Zj.WPa:0);this.of!=b&&(this.of=b,this.l(a.f.h))};l.DJa=function(){return 0!=(this.of&a.Zj.WPa)};l.v6b=function(b){b=this.of&~a.Zj.Oib|(b?a.Zj.Oib:0);this.of!=b&&(this.of=b,this.l(a.f.h))};l.Y5a=function(){return 0!=(this.of&a.Zj.Oib)};l.qmb=function(b){b=this.of&~a.Zj.Xib|(b?a.Zj.Xib:0);this.of!=
b&&(this.of=b,this.AR(this.Oe()),this.l(a.f.h))};l.T8a=function(){return 0!=(this.of&a.Zj.Xib)};l.nDc=function(){return this.mZa};l.n8b=function(b){b!=this.mZa&&(this.mZa=b,this.nb(),this.ca(a.f.h))};l.lwd=function(){return this.Bha};l.nBa=function(b){if(this.ubb()||this.Bha!=b)this.Bha=b,this.l(a.f.h)};l.$1c=function(){!1==this.ubb()&&(this.Bha=a.m.Ub,this.l(a.f.h))};l.O6b=function(b){b=this.of&~a.Zj.Pib|(b?a.Zj.Pib:0);this.of!=b&&(this.of=b,this.AR(this.Oe()),this.l(a.f.h))};l.TJa=function(){return 0!=
(this.of&a.Zj.Pib)};l.DLd=function(b){b=this.of&~a.Zj.Vib|(b?a.Zj.Vib:0);this.of!=b&&(this.of=b,this.l(a.f.h))};l.CCc=function(){return 0!=(this.of&a.Zj.Vib)};l.W1c=function(){var b=this.of&~a.Zj.w4b|0;this.of!=b&&(this.of=b,this.l(a.f.h))};l.kDc=function(){return 0!=(this.of&a.Zj.w4b)};l.OC=function(b){b=this.of&~a.Zj.Tib|(b?a.Zj.Tib:0);this.of!=b&&(this.of=b,this.l(a.f.h))};l.j0c=function(b){b=this.of&~a.Zj.Sib|(b?a.Zj.Sib:0);this.of!=b&&(this.of=b,this.l(a.f.h))};l.uLd=function(b){b=this.of&~a.Zj.Uib|
(b?a.Zj.Uib:0);this.of!=b&&(this.of=b,this.l(a.f.h))};l.R5=function(b){b=this.of&~a.Zj.Qib|(b?a.Zj.Qib:0);this.of!=b&&(this.of=b,this.l(a.f.h))};l.JJb=function(){return 0!=(this.of&a.Zj.Qib)};l.IJb=function(){return this.rn};l.nda=function(b){this.rn!=b&&(null!=this.rn&&(this.rn.Da(this,this.h3a),this.rn.xb()),this.rn=b,null!=this.rn&&(this.rn.Ba(),this.rn.Ea(this,this.h3a)),this.AR(this.Oe()),this.ca(a.f.h))};l.oEc=function(){return this.zO};l.rmb=function(b){this.zO!=b&&(null!=this.zO&&(this.zO.Da(this,
this.$Eb),this.zO.xb()),this.zO=b,null!=this.zO&&(this.zO.Ba(),this.zO.Ea(this,this.$Eb)),this.AR(this.Oe()),this.ca(a.f.h))};l.oDc=function(){return this.tka().rg()};l.o8b=function(b){this.tka().rg()!=b&&(this.tka().tb(b),this.l(a.f.h))};l.pDc=function(){return this.tka().Vj()};l.ib=function(){var a=null;null!=this.Pa()&&(a=this.Pa().ib());return a};l.gwc=function(){var a=!1;if(this.YL()||!this.pbb())a=!0;return a};l.nEc=function(){return this.hGa};l.U2c=function(b){this.hGa!=b&&(this.hGa=b,this.nb(),
this.ca(a.f.h))};l.tBc=function(){return this.sa};l.kva=function(){return this.sa};l.rh=function(){var a=!1;null!=this.Pa()&&(a=this.Pa().ib(),a=b.Pd[a].FR);return a};l.xab=function(){return 0!=(this.of&a.Zj.Nib)};l.qMa=function(){return 0!=(this.of&a.Zj.WPa)};l.dbb=function(){return 0!=(this.of&a.Zj.Tib)};l.Pzd=function(){return 0!=(this.of&a.Zj.Sib)};l.pbb=function(){return 0!=(this.of&a.Zj.Uib)};l.Dla=function(){return 0!=(this.of&a.Zj.Yib)};l.YL=function(){return 0!=(this.of&a.Zj.Wib)};l.Uab=
function(){return!1};l.ubb=function(){return!1==this.DNb()};l.DNb=function(){return this.Bha!=a.m.Ub};l.XY=function(){var a=!1;this.rb()==this&&this.rb().M()&&this.rb().M()!=this.Wl&&(a=!0);return a};l.iV=function(){if(null!=this.Pa()){var a=this.Waa()?this.Waa().qh():"DEFAULT";b.fVa(this.Pa().ib(),a)}};l.CSc=function(a){var c=!1;this.rh()&&this.qMa()&&!this.Dla()&&this.paa()&&null!=a&&b.W().EC(this.paa())==a&&(c=!0);return c};l.DSc=function(a){var c=!1;if(this.rh()&&this.qMa()&&!this.Uab()&&!this.Dla())if(null==
a)c=!0;else for(var d=b.W().EC(a),c=!0;null!=a&&null!=d;)d==this?(c=!1,a=null):null!=d&&(d.paa()?(d=d.paa(),a=a!=d?d:null):a=null),d=b.W().EC(a);return c};l.AR=function(d,e){e===m&&(e=!1);if(!b.W().YY()){var f=new c.ga(0,0,d.aa(),30),h=d.aa()-4;this.TJa()&&(h-=f.ba());this.zO&&(h-=f.ba());this.nA.Ab(this.ob());this.nA.Yb(Math.min(h,this.nA.sLa(this.nA.ob(),this.nA.An().length)+10));this.cr.Na(this.T8a()?this:null);this.cr.kb(f);this.cr.Wb(""==this.hGa?a.Jba:this.hGa);this.az.Ib(this.TJa());this.az.Yb(f.ba());
this.az.Ib(null!=this.zO);this.az.$c(this.zO);this.az.kb(new c.ga(this.az.Vd(),this.az.ve(),Math.min(this.az.Hc()?this.az.Hc().Xa():this.cr.Qa(),this.cr.Qa()-4),Math.min(this.az.Hc()?this.az.Hc().Qa():this.cr.Qa(),this.cr.Qa()-4)));this.FB.Ib(this.TJa());this.FB.kb(new c.ga(this.FB.Vd(),this.FB.ve(),30,29));this.FB.vj(this.rn?this.rn:a.Vb.Udd);e?b.W().pic(this.FB):b.W().dUc(this.FB);this.cr.M()&&d.Ua(d.O()+f.ba());this.Pb()&&this.gh()}};l.Ze=function(a){this.AR(a);l.j.Ze.call(this,a)};l.gh=function(){this.XY()||
this.Na(this.IY());this.r_c(this.YL());this.gwc()&&l.j.gh.call(this)};l.Dj=function(){l.j.Dj.call(this);this.AR(this.Oe())};l.Jib=function(b,c,d){l.j.Jib(b,c,d);d[0]&&this.eQ()!=a.kw.Wpa&&this.T8a()&&(d[0]=this.cr==c||this.nA==c)};l.se=function(b){""==b[0]&&(b[0]=a.ZMa);""==b[1]&&(b[1]=a.XMa);l.j.se.call(this,b)};l.u5=function(a){return this.D$(this.sn,a)};l.Dib=function(a){return this.Vua(a)};l.PPa=function(){null!=this.Wl&&(null!=this.rb()&&this.Xs(this.rb(),a.$.SMa),this.oda(null),this.dbb()||
null==this.GR||this.DJa()||b.hma()!=this.GR||this.GR.XA(this.GR.XD()),this.PQa(null),this.JRa(null),this.KRa(null));this.xab()&&this.Xp()};l.Vza=function(){};l.pAa=function(){this.Ff.nl(this.Vd());this.Ff.Sk(this.ve());this.rh()&&this.Jz(this.fX,this.dX,this.Ff,this.sn,this.eX,this.Lx)};l.s6=function(d,e,f,h,k){var g=b.zm();this.XY()&&(g.nl(this.Vd()),g.Sk(this.ve()));d==m&&(d=g.Db());e==m&&(e=g.Eb());f==m&&(f=a.Ci.bx);h==m&&(h=a.Nf.XV);this.Jz(f,null,new c.ld(d,e),k,null,h)};l.Jz=function(d,e,f,
h,k,g){d==m&&(d=a.Ci.bx);e==m&&(e=null);f==m&&(f=b.zm());h==m&&(h=null);k==m&&(k=null);g==m&&(g=a.Nf.XV);if(this.rh()&&this.pbb()){if(this.dX==e&&this.eX==k&&this.sn==h&&this.fX==d&&this.Lx==g){d=b.zd(f.Db(),f.Eb(),this.rb().Xa(),this.rb().Qa());b.rZb(this,d);this.IY().kb(new c.ga(0,0,d.aa(),d.ba()));f.nl(d.Q());f.Sk(d.O());this.rb().kb(d);this.Z8b(this.tka().iE());this.Ff=f;return}var l=this.xab();this.N5(!1);this.Al();this.PPa();this.N5(l)}this.fX!=a.Ci.bx&&this.M()!=this.Wl&&this.Na(null);this.of|=
a.Zj.Wib;this.h8b(!1);null!=this.Zn()&&(this.oda(h),this.ea.cBa(this.paa()?this.paa().ea:null),this.IY(),this.CCc()&&this.Xs(this.IY(),a.$.RMa),this.PQa(b.hma()),this.fX=d,this.Lx=g,this.AR(this.Oe()),this.SQc(f,this.dbb()),this.M()==this.IY()?this.Xs(this.IY(),a.$.Iba):this.Xs(this,a.$.Iba),this.JRa(e),this.KRa(k),this.Y5a()&&this.Lx==a.Nf.XV&&this.rb().$e(!0),this.uvc())};l.Al=function(){if(this.rh()){var c=b.W().Kj;c&&c.dq(this)&&this.Xs(c,a.$.OA);b.W().Wlc(this);null!=this.Pa()&&(c=this.Pa().ib(),
b.Pd[c].Gta());this.r5a();this.PPa()}else b.W().R1&&(c=b.W().R1,c.Pa()&&c.Pa().FR&&c==this.sn&&b.W().Et(c,!1))};l.Iic=function(a){for(var b=this.ea.iE(),c=null,d=b.length-1;null!=b&&0<=d&&null!=(c=b[d]);d--)a.splice(0,0,c)};l.SQc=function(a,c){this.Pa()&&(c||(b.W().tv&&b.W().tv.pOb(),b.W().Cw(this.paa(),!1,this)),this.TQc(a))};l.TQc=function(c){if(this.u5(c)&&this.rb()){this.rb().gh();this.rb().MA(!0);c=this.Wl;c.nQ()||c.sPa();c=this.Pa().ib();a.Aqa+=2;b.Pd[c].vFa=a.Aqa;b.csb(c,b.Pd[c].jg());b.Pd[c].yoa();
var d=b.Pd[c].pa.xt?b.Pd[c].pa.xt.Pa():null;d&&d.J.parentElement!=document.body&&(null!=d.J.parentElement&&d.J.parentElement.removeChild(d.J),d.J.style.zIndex=b.Pd[c].vFa-1,document.body.appendChild(d.J))}};b.rZb=function(d,e){switch(d.fX){case a.Ci.tPa:var f=b.yE(),f=new c.ga(f.Vd()-d.ea.nj(),f.ve()-d.ea.Jk(),f.Xa()+(d.ea.nj()+d.ea.Ik()),f.Qa()+(d.ea.Jk()+d.ea.vm()));e.zq(f);break;case a.Ci.OZ:var f=b.yE(),h=0,k=0,h=(f.aa()-e.Xa())/2,k=(f.ba()-e.Qa())/2;e.Cb(h,k);d.XY()&&e.zq(d.M().FAa(e));break;
case a.Ci.a3b:f=b.yE();h=(f.aa()-e.Xa())/2;k=f.ua-e.Qa();e.Cb(h,k);d.XY()&&e.zq(d.M().FAa(e));break;case a.Ci.MQc:f=b.yE();h=(f.aa()-e.Xa())/2;e.Cb(h,0);d.XY()&&e.zq(d.M().FAa(e));break;case a.Ci.c3b:f=b.yE();k=(f.ba()-e.Qa())/2;h=f.va-e.Xa();e.Cb(h,k);d.XY()&&e.zq(d.M().FAa(e));break;case a.Ci.b3b:f=b.yE();k=(f.ba()-e.Qa())/2;e.Cb(0,k);d.XY()&&e.zq(d.M().FAa(e));break;default:f=b.yE(),e.va>f.va&&e.Cb(Math.max(0,f.va-e.aa()),e.O()),e.ua>f.ua&&e.Cb(e.Q(),Math.max(0,f.ua-e.ba())),e.Q()<f.Q()&&e.Cb(0,
e.O()),e.O()<f.O()&&e.Cb(e.Q(),0)}};l.IOc=function(){b.W();this.xt=new c.jn;this.xt.wa(this,a.G.E_a,this.Crc);this.xt.wa(this,a.G.$b,this.Drc);this.xt.Fe(1);this.xt.Ta(0);this.xt.Jda(1);this.xt.Ua(0);this.xt.Ib(!1);this.nZa=new c.yg;this.S8=new c.pb;this.S8.xd(this.nZa)};l.Z8b=function(a){var d=b.W().zs;this.xt||this.IOc();if(!this.xt.Pb()){this.nZa.Ed(this.Bha);this.nZa.tg(this.mZa);this.xt.tb(this.DNb()?this.S8:null);for(var e=0;e<a.length;e++)this.xt.En(a[e]);null==this.xt.rg()?this.xt.Na(null):
(this.xt.oc(d),this.xt.Fe(1),this.xt.AP())}this.xt.kb(new c.ga(0,0,d.Xa(),d.Qa()))};l.GGc=function(){this.xt.qb()&&this.xt.qp()};l.xk=function(c){if(this.kDc()){var d=this.Pa().ib();a.Aqa+=2;b.Pd[d].vFa=a.Aqa;b.csb(d,b.Pd[d].jg())}l.j.xk.call(this,c)};l.D$=function(d,f){var h=!0,k=e.Tb(),g=this.rb().Xa(),l=this.rb().Qa();k.Zb("CONTEXT",d);k.JB("LEFT",f.Db());k.JB("TOP",f.Eb());k.JB("WIDTH",g);k.JB("HEIGHT",l);k.SO("TRANSITION",this.Lx,a.Nf.v);k.rf("CONTINUE",!0);this.Ga(a.G.Zv,k);f.nl(k.dka("LEFT"));
f.Sk(k.dka("TOP"));h=k.og("CONTINUE");g=g==k.dka("WIDTH")?this.rb().Xa():k.dka("WIDTH");l=l==k.dka("HEIGHT")?this.rb().Qa():k.dka("HEIGHT");g=new c.ga(f.Db(),f.Eb(),g,l);b.rZb(this,g);this.IY().kb(new c.ga(0,0,g.aa(),g.ba()));f.nl(g.Q());f.Sk(g.O());this.rb().kb(g);this.Lx=k.X6a("TRANSITION",a.Nf.v);k.sc();this.Ff=f;return h};l.Vua=function(b){var c=!1,c=e.Tb();c.rf("IMMEDIATE",b);c.rf("CLOSEPOPUP",!0);this.Ga(a.G.lI,c);b||this.Lx!=a.Nf.XV?c=!0:(c=c.og("CLOSEPOPUP"),c||(this.of|=a.Zj.Yib));return c};
l.r5a=function(){this.Ga(a.G.fP);this.of&=~a.Zj.Yib;this.of&=~a.Zj.Wib;this.h8b(!0);this.XY()&&this.M().nb()};l.uvc=function(){this.Ga(a.G.gPa)};l.Crc=function(){this.xt.qb()||(this.xt.Na(null),this.Vza())};l.Drc=function(){this.Uab()&&this.qMa()&&this.Al()};l.gpc=function(){this.AR(this.Oe(),!0)};l.hpc=function(){this.AR(this.Oe())};l.fpc=function(a,c){b.W().Et(this,!1);c.yk("HANDLED",!0)};l.krc=function(){};l.eDb=function(b,c){switch(c.Ya){case a.f.sb:this.oda(null)}};l.irc=function(b,c){switch(c.Ya){case a.f.sb:this.JRa(null)}};
l.jrc=function(b,c){switch(c.Ya){case a.f.sb:this.KRa(null)}};l.Loc=function(b,c){switch(c.Ya){case a.f.sb:this.PQa(null)}};l.h3a=function(b,c){switch(c.Ya){case a.f.sb:case a.f.Ob:this.nda(null)}};l.$Eb=function(b,c){switch(c.Ya){case a.f.sb:case a.f.Ob:this.rmb(null)}};l.nua=l[a.$.Lla]=function(){this.YL()&&this.pAa()};l.eG=l[a.$.Dz]=function(a){l.j.eG.call(this,a);this.AR(this.Oe())};l.ds=l[a.$.FG]=function(a){l.j.ds.call(this,a);this.AR(this.Oe())};e.kd(c.Zw,"PRIM_PPNL",{Oa:{CloseOnClick:{a:l.JJb,
g:function(a){this.R5(e.za(a))}},AutoClose:{a:l.DJa,g:function(a){this.Zna(e.za(a))}},AutoFocus:{a:l.Y5a,g:function(a){this.v6b(e.za(a))}},TitleBar:{a:l.T8a,g:function(a){this.qmb(e.za(a))}},ShroudColor:{a:function(){return this.ubb()?e.Gd:b.eg(this.Bha)},g:function(a){a===e.Gd?this.$1c():this.nBa(b.dg(e.ma(a)))}},ShroudOpacity:{a:l.nDc,g:function(a){this.n8b(e.K(a))}},CloseButton:{a:l.TJa,g:function(a){this.O6b(e.za(a))}},CloseImage:{a:l.IJb,g:l.nda},TitleImage:{a:l.oEc,g:l.rmb},ShroudStyle:{a:l.oDc,
g:l.o8b},ShroudStyles:{a:l.pDc},TitleBarThemeDrawStyle:{a:l.nEc,g:function(a){this.U2c(e.ma(a))}},IsOpen:{a:l.rh}},jc:{ShowPopup:function(b,c,d,f,h){this.s6(b,c,d?e.ra(d,a.Ci.qOc):d,f?e.ra(f,a.Nf.v):f,h)},ClosePopup:l.Al}});c.Afb=function(d){s.w.call(this,d);this.nd=new c.ga(0,0,300,30);this.rsa=a.hna.NQc;this.cFa=new c.Vv;this.S0=this.fK=this.eK=null;this.OR=[];this.vYa=null;b.Ho(this.cFa);b.eo(this.cFa);this.gm(this.cFa);this.Ef(!1);this.S0=new c.jOa;this.S0.VAa(a.jJ.Q1b);this.S0.wa(this,a.G.Zv,
this.lpc);this.eK=new c.Yt;this.eK.Na(this);this.eK.kb(new c.ga);this.eK.wa(this,a.G.$b,this.mpc);this.eK.y_();this.vYa=new c.nZb(this)};var s=c.u(c.Afb,c.jn);s.vb=function(){s.j.vb.call(this)};s.U=function(){s.j.U.call(this);b.la(this.vYa);this.vYa=null};s.sxc=function(){return this.fK};s.Q6b=function(b){this.fK!=b&&(null!=this.fK&&(this.fK.Da(this,this.aDb),this.fK.xb()),this.fK=b,null!=this.fK&&(this.fK.Ba(),this.fK.Ea(this,this.aDb)),this.nb(),this.l(a.f.h))};s.V1c=function(b){b=this.of&~a.hna.fib|
(b?a.hna.fib:0);this.rsa!=b&&(this.rsa=b,this.l(a.f.h))};s.e8a=function(){return 0!=(this.rsa&a.hna.fib)};s.a_c=function(b){this.UJa()!=b&&(this.rsa=this.rsa&~a.hna.d3b|b,this.nb(),this.MA(),this.D3b(this.Oe()),this.ca(a.f.h))};s.UJa=function(){return this.rsa&a.hna.d3b};s.E6a=function(){var b=null;switch(this.UJa()){case a.dL.I1a:case a.dL.G1a:b=s.j.E6a.call(this);break;case a.dL.C1a:e.Gb("PRIM_PCOL"),b=new c.Ueb(this.S0),b=new c.xZ(b)}return b};s.se=function(b){""==b[0]&&(b[0]=a.KSb);""==b[1]&&
(b[1]=a.KLc);s.j.se.call(this,b)};s.Eib=function(){this.gm(this.cFa)};s.dx=function(c,d){s.j.dx.call(this,c,d);this.Eib();b.oZb(this,this.cFa,a.xa.Ui,a.qa.YF,a.ja.Xi,this.g3a)};s.Ze=function(a){s.j.Ze.call(this,a);this.D3b(a)};s.D3b=function(d){switch(this.UJa()){case a.dL.I1a:for(this.eK.Ib(!1);0<this.OR.length;)this.OR[0].Xp();break;case a.dL.G1a:for(var e=this.OR.length,f=0,h=null,k=this.uo,g=k.length-1;0<=g&&null!=(h=k[g]);g--)f=Math.max(f,h.Cc().va),h.Nt()>d.va&&(b.mZb(this,h),e++);k=this.OR;
for(g=0;g<k.length&&null!=(h=k[g]);g++)f+h.eb.Xa()<d.va?(h.Xp(),g--,e--):h.ha().Fe(g+1);if(0<e)this.eK.vj(this.fK?this.fK:a.Vb.Ygb),this.eK.kb(new c.ga(d.va-(d.ba()+2),0,d.ba(),d.ba())),this.eK.Ib(!0),this.S0.MPa();else for(this.eK.Ib(!1);0<this.OR.length;)this.OR[0].Xp();break;case a.dL.C1a:for(;0<this.uo.length;)b.mZb(this,this.uo[this.uo.length-1]);this.eK.vj(this.fK?this.fK:a.Vb.Ygb);this.eK.kb(new c.ga(d.va-(d.ba()+2),0,d.ba(),d.ba()));this.eK.Ib(!0);this.S0.MPa()}this.Pb()&&this.gh()};b.oZb=
function(c,d,e,f,h,k){for(var g=null,l=c.uo,m=1,q=0;q<l.length&&null!=(g=l[q]);q++,m++){var s=d.Be(g);s||(s=b.Ic(d,g,d.wc(0),d.zc(0),1,1),g.wa(c,a.G.JQ,k));s.Lf(e);s.yb(f);s.Qb(h)}};s.aDb=function(b,c){switch(c.Ya){case a.f.sb:case a.f.Ob:this.Q6b(null);break;case a.f.h:this.nb()}};s.lpc=function(b,c){this.Ga(a.G.Zv,c)};s.mpc=function(b,d){this.S0.Jz(a.Ci.bx,this,new c.ld(this.gs()+this.Xa()-this.S0.Xa(),this.hs()+this.Qa()),this);d.yk("HANDLED",!0)};s.g3a=function(a){this.e8a()&&(a=a instanceof c.bca?
a:null)&&a.fC()&&!a.fC().rh()&&(a.Gr(),this.vYa.sh())};e.jb(c.Afb,"PRIM_PPNL","MenuBar",{Oa:{CollapsedMenuImage:{a:s.sxc,g:s.Q6b},ShowOnHover:{a:s.e8a,g:function(a){this.V1c(e.za(a))}},CollapseStyle:{a:function(){return e.ta(this.UJa(),a.dL.v)},g:function(b){this.a_c(e.ra(b,a.dL.v))}}}});c.nZb=function(a){g.w.call(this,500);this.AS=a};var g=c.u(c.nZb,c.CZ);g.ST=function(){if(this.AS.e8a()){var a=!1,c=!1,d=b.W().gib(b.zm());d?a=!0:(d=b.WU(b.zm()))&&(d==this.AS||d.dq(this.AS))&&(a=!0);!a&&(d=b.W().EC(b.DQ()))&&
(c=a=!0);a||(this.AS.Cw(),c=!0);c&&this.Xh()}return!1};c.jOa=function(){q.w.call(this);this.nd=new c.ga(0,0,150,150);this.Gh=new c.Vv;this.zK=a.Zgb.oza;b.Ho(this.Gh);b.eo(this.Gh);this.gm(this.Gh)};var q=c.u(c.jOa,c.Zw);q.vb=function(){q.j.vb.call(this)};q.U=function(){q.j.U.call(this)};q.VAa=function(b){this.Zva()!=b&&(this.zK=this.zK&~a.Zgb.U1b|b,this.nb(),this.ca(a.f.h))};q.Zva=function(){return this.zK&a.Zgb.U1b};q.se=function(b){""==b[0]&&(b[0]=a.MSb);""==b[1]&&(b[1]=a.LLc);q.j.se.call(this,
b)};q.Eib=function(){this.gm(this.Gh);this.R5(!0)};q.dx=function(c,d){q.j.dx.call(this,c,d);this.Eib();b.oZb(this,this.Gh,a.xa.mj,a.qa.gz,a.ja.Yh,this.g3a)};q.MPa=function(){if(this.Zva()!=a.jJ.c5){for(var b=null,d=this.uo,e=[!0,2,2,0,0],f=0;f<d.length&&null!=(b=d[f]);f++){var h=b instanceof c.bca?b:null;switch(this.Zva()){case a.jJ.Pma:h?h.S3b(e):e[2]+=b.qb()?b.Qa():0;break;case a.jJ.Q1b:e[1]=Math.max(e[1],b.Xa()),e[2]+=b.qb()?b.Qa():0}}for(f=0;f<d.length&&null!=(b=d[f]);f++)switch(this.Zva()){case a.jJ.Pma:(h=
b instanceof c.bca?b:null)&&h.Yb(e[1])}this.Yb(e[1]);this.xc(e[2])}};q.u5=function(a){this.MPa();return q.j.u5.call(this,a)};q.Ze=function(a){q.j.Ze.call(this,a)};q.gDb=q[a.$.hcb]=function(a){q.j.gDb.call(this,a);this.MPa()};q.g3a=function(a){(a=a instanceof c.bca?a:null)&&a.Gr()};e.jb(c.jOa,"PRIM_PPNL","Menu",{Oa:{MenuSizing:{a:function(){return e.ta(this.Zva(),a.jJ.v)},g:function(b){this.VAa(e.ra(b,a.jJ.v))}}}});c.pZb=function(){f.w.call(this)};var f=c.u(c.pZb,c.fJ);f.YQb=function(){return!0};f.se=
function(){};c.bca=function(){k.w.call(this);this.nd=new c.ga(0,0,100,25);this.o8=a.jca.IZ;this.Gs=0;this.bYa=this.pvb=this.vn=this.PN=this.K1=this.pS=this.NK=null;this.L1=new c.Vv;this.vv=0;this.UH=a.ie.NZ;b.Ho(this.L1);b.eo(this.L1);this.gm(this.L1);this.lRa(!0);this.PN=new c.pb;this.PN.Qo(a.m.Rd);this.PN.ek(a.m.Rd);this.PN.jo(1);this.PN.Ro(1);this.PN.Cm(1);this.PN.Dm(1);this.K1=new c.Yt;this.K1.Na(this);this.K1.kb(new c.ga(0,0,18,18));this.K1.tb(this.PN);this.vn=new c.pZb;this.vn.Na(this);this.vn.re(2);
this.vn.Ud(2);this.pvb=b.Ic(this.L1,this.vn,this.L1.wc(0),this.L1.zc(0),1,1);this.bYa=b.Ic(this.L1,this.K1,this.L1.wc(0),this.L1.zc(0),1,1)};var k=c.u(c.bca,c.jn);k.vb=function(){k.j.vb.call(this)};k.U=function(){k.j.U.call(this);this.uRa(null)};k.fC=function(){return this.vn.fC()};k.v_=function(b){this.fC()!=b&&(this.vn.fC()&&this.vn.fC().Oo(this,a.G.Zv,this.VDb),this.vn.v_(b),this.vn.fC()&&this.vn.fC().wa(this,a.G.Zv,this.VDb),this.l(a.f.h))};k.S3=function(){return this.vn.S3()};k.iAc=function(){return this.pS};
k.uRa=function(b){this.pS!=b&&(null!=this.pS&&(this.pS.Da(this,this.UDb),this.pS.xb()),this.pS=b,null!=this.pS&&(this.pS.Ba(),this.pS.Ea(this,this.UDb)),this.Ns(),this.l(a.f.h))};k.Jw=function(){return this.vv};k.Wu=function(b){b!=this.vv&&(this.vv=b,this.Ns(),this.ca(a.f.h))};k.Er=function(b){this.UH!=b&&(this.UH=b,this.Ns(),this.ca(a.f.h))};k.Xe=function(){return this.vn.Xe()};k.Ge=function(b){this.Xe()!=b&&(this.vn.Ge(b),this.l(a.f.h))};k.cf=function(){return this.vn.cf()};k.re=function(b){this.cf()!=
b&&(this.vn.re(b),this.l(a.f.h))};k.Tf=function(){return this.vn.Tf()};k.Ud=function(b){this.Tf()!=b&&(this.vn.Ud(b),this.l(a.f.h))};k.kg=function(){return this.vn.kg()};k.Se=function(b){this.kg()!=b&&(this.vn.Se(b),this.l(a.f.h))};k.xm=function(){return this.UH};k.Taa=function(){return 0!=(this.o8&a.jca.IQ)?!0:!1};k.gBa=function(b){b=this.o8&~a.jca.IQ|(b?a.jca.IQ:0);this.o8!=b&&(this.o8=b,this.Ns(),this.ca(a.f.h))};k.pg=function(){return 0!=(this.o8&a.jca.HQ)?!0:!1};k.Mh=function(b){var d=this.YD();
if(b&&0!=d&&null!=this.M())for(var e=null,f=this.M().Nh,h=0;h<f.length&&null!=(e=f[h]);h++)if(e instanceof c.bca){var k=e;k!=this&&k.YD()==d&&k.Mh(!1)}b=this.o8&~a.jca.HQ|(b?a.jca.HQ:0);this.o8!=b&&(this.o8=b,this.Ns(),this.ca(a.f.h))};k.YD=function(){return this.Gs};k.m_=function(b){this.Gs!=b&&(this.Gs=b,this.Ns(),this.ca(a.f.h))};k.n8a=function(){return this.NK};k.gSa=function(a){this.NK!=a&&(this.NK=a)};k.se=function(b){""==b[0]&&(b[0]=a.JSb);k.j.se.call(this,b)};k.Gr=function(){var a=b.W().EC(this);
(null==a||a.rh())&&this.fC()&&!this.fC().rh()&&this.vn.rac(!0)};k.hxa=function(){};k.S3b=function(b){var d=null,e=this.Rb&&this.Rb instanceof c.Afb?this.Rb:null,f=this.vv;this.pg()?(d=this.Taa()?a.Vb.L1b:a.Vb.K1b,this.PN.Qo(a.m.fN),this.PN.ek(a.m.A6)):(this.PN.Qo(a.m.Rd),this.PN.ek(a.m.Rd));this.pS&&(d=this.pS);d&&0==f&&(f=Math.min(this.Qa(),d.Qa()));this.vn.Wb(a.mMc);this.vn.LM(!1);this.vn.Er(this.xm());this.vn.DRa(e?a.zE.jza:a.zE.kza);this.vn.ylb(e?a.ho.c5:a.ho.Qma);this.vn.ZG(a.iu.ZK);this.vn.noa(!1);
this.vn.Ab(this.ob());this.vn.Kn(a.Vg.oq);this.K1.vj(d);this.K1.kb(new c.ga(this.K1.Vd(),this.K1.ve(),f,f));this.pvb.Qb(a.ja.Mf);this.pvb.re(e?0:f+2);this.bYa.Qb(a.ja.Xd);this.bYa.yb(a.qa.Ek);this.bYa.re(e?0:2);this.vn.$j(!1,!0);var h=this.vn.XT(),k=this.vn.Hja();e?(h+=f+4,d&&(h+=f+4)):(h+=60,k+=10);!0==b[0]&&(this.xc(k),b[1]=Math.max(b[1],h),b[2]+=this.qb()?k:0,b[3]+=h,b[4]+=k)};k.dx=function(a,b){k.j.dx.call(this,a,b);this.S3b([!1,0,0])};k.Bf=function(a){var d=!1;this.YD()&&this.Mh(!0);d=k.j.Bf.call(this,
a);if(!d){a=b.W().Fx;for(var e=null,f=0;f<a.length&&null!=(e=a[f]);f++)e instanceof c.jOa&&b.W().Et(e,!1)}return d};k.VDb=function(a,b){b.z1c(this)};k.UDb=function(b,c){switch(c.Ya){case a.f.sb:case a.f.Ob:this.uRa(null);break;case a.f.h:this.Ns()}};e.jb(c.bca,"PRIM_PPNL","MenuItem",{Oa:{Checked:{a:k.pg,g:function(a){this.Mh(e.za(a))}},MenuPopup:{a:k.fC,g:k.v_},RadioItem:{a:k.Taa,g:function(a){this.gBa(e.za(a))}},GroupIndex:{a:k.YD,g:function(a){this.m_(e.K(a))}},Image:{a:k.iAc,g:k.uRa},ImageHeight:{a:k.Jw,
g:function(a){this.Wu(e.K(a))}},MarginLeft:{a:k.cf,g:function(a){this.re(e.K(a))}},MarginTop:{a:k.Xe,g:function(a){this.Ge(e.K(a))}},MarginBottom:{a:k.kg,g:function(a){this.Se(e.K(a))}},MarginRight:{a:k.Tf,g:function(a){this.Ud(e.K(a))}},Alignment:{a:function(){return e.ta(this.xm(),a.ie.$K)},g:function(b){this.Er(e.ra(b,a.ie.$K))}}},jc:{ShowMenu:k.Gr,HideMenu:k.hxa}});c.lZb=function(a,b,c){d.w.call(this);this.AS=a;this.eb=b;this.Jed=b.Cc();-1==c&&(c=this.AS.OR.length);this.AS.OR.splice(c,0,this);
this.eb.Ea(this,this.Os);this.eb.Na(a.S0)};var d=c.u(c.lZb,c.wd);d.U=function(){var a=this.AS.uo.length+1;this.eb.Da(this,this.Os);this.AS.OR.splice(this.AS.OR.indexOf(this),1);this.eb.oc(this.AS);this.eb.Fe(a);this.eb.kb(this.Jed);d.j.U.call(this)};d.ha=function(){return this.eb};b.mZb=function(a,b){-1==a.OR.indexOf(b)&&new c.lZb(a,b,0)};d.Sm=function(b,c){switch(c.Ya){case a.f.sb:this.Xp()}};c.H0b=function(a){h.w.call(this,a);this.FR=!1;this.qX=null;this.sw="";this.vFa=null};var h=c.u(c.H0b,c.X4);
h.yNb=function(){var b=!1,c=e.ta(this.pa.Lx,a.Nf.oHb);if("md-effect-17"==c||"md-effect-18"==c||"md-effect-19"==c)b=!0;return b};h.lf=function(a){this.J=document.createElement("div");this.J.setAttribute("id",a+this.gc);this.J.setAttribute("LANSAHandle",this.gc);this.qX=document.createElement("div");this.qX.setAttribute("LANSAHandle",this.gc);return this.J};h.dqa=function(){this.Gta()};h.$qb=function(b){this.sw=e.ta(this.pa.Lx,a.Nf.oHb);null!=this.vFa&&(b=this.vFa);9999<b&&(""==this.sw?h.j.$qb.call(this,
b):this.qX.style.zIndex=b)};h.lo=function(a,c,d,e){a=b.zd(a,c,d,e);this.pa.XY()&&a.zq(this.pa.M().gAb(a));h.j.lo.call(this,a.Q(),a.O(),a.aa(),a.ba())};h.yoa=function(){var a=this,c=this.FR;this.pa.Z8b(this.pa.tka().iE());""==this.sw?(this.FR=!0,c||document.body.appendChild(this.J)):this.FR||(b.W().zs.Pa().J.classList.add("container"),this.qX.setAttribute("class","md-modal "+this.sw),c=b.Pd[this.pa.rb().Pa().ib()],c.J.style.opacity="",c.J.setAttribute("class","md-content"),this.qX.appendChild(this.J),
document.body.insertBefore(this.qX,b.W().zs.Pa().J),this.yNb()&&setTimeout(function(){document.documentElement.classList.add("md-perspective")},25),setTimeout(function(){a.qX.classList.add("md-show");setTimeout(function(){if(a.pa.Y5a()){var c=b.DQ();c&&c.dq(a.pa)||a.pa.rb().$e(!0)}},300)},100),this.FR=!0)};h.Gta=function(){this.FR&&(this.qX.classList.contains("md-show")?this.R4b():(this.FR=!1,this.yNb()&&document.documentElement.classList.remove("md-perspective"),""==this.sw?document.body.removeChild(this.J):
(document.body.removeChild(this.qX),b.W().zs.Pa().J.classList.remove("container"))),this.pa.GGc())};h.R4b=function(){var a=this;this.qX.classList.remove("md-show");setTimeout(function(){a.pa.Al()},500)};h.CGd=function(){this.R4b()}},{rp:["PRIM_PHBN","PRIM_IMAG","PRIM_TBLO"]});
