window.LANSA.addSrc("wdgt",function(e,c,a,b,m){var p={};c.Z0b=function(a){l.w.call(this);this.zEa=a;this.SVa=function(){};this.LW=this.Mvb=!1;this.iwb=[];this.hwb=[];this.dwb=[];this.cwb=[];this.fwb=[]};var l=c.u(c.Z0b,c.ze);l.qQ=function(){return this.Mvb};l.qh=function(){return this.zEa.nm};l.XCc=function(){return this.zEa.js||[]};l.IDc=function(){return this.zEa.st||[]};l.tyc=function(){return this.zEa.fn};l.mzc=function(){return this.zEa.fe};l.iY=function(){return this.SVa};l.BTc=function(){function a(){if(l<
m.length){var c=m[l],e=document.createElement("script");e.type="text/javascript";e.onload=function(){e.onload=null;e.onerror=null;l++;a()};e.onerror=function(){e.onload=null;e.onerror=null;throw"Error defining Widget "+d+", failed to load script: "+c;};document.body.appendChild(e);e.src=c}else b()}function b(){function a(){if(!c.Mvb){for(c.Mvb=!0;0<c.cwb.length;){var b=c.cwb.shift();c.oab(b)}for(;0<c.hwb.length;)b=c.hwb.shift(),c.qab(b.nsb,b.Lfd,b.value);for(;0<c.fwb.length;)b=c.fwb.shift(),c.aPb(b.nsb,
b.parent);for(;0<c.iwb.length;)b=c.iwb.shift(),c.rab(b);for(;0<c.dwb.length;)b=c.dwb.shift(),c.pab(b)}}var d=c.tyc(),f=c.SVa.prototype;e&&e(f);var h={Loading:{},Completed:{},Finalize:function(){a()}};d(f,h)!==h.Loading&&a()}var c=this,d=c.qh(),e=c.mzc();p[d]=c;for(var f=c.IDc(),h=0;h<f.length;h++){var k=f[h],g=document.createElement("link");g.type="text/css";g.rel="stylesheet";g.href=k;document.body.appendChild(g)}var l=0,m=c.XCc();a()};l.qab=function(a,b,c){if(this.qQ()){var d=a["set"+b];if(!d)throw e.rUc("set"+
b);d&&d.call(a,c)}else this.hwb.push({nsb:a,Lfd:b,value:c})};l.pab=function(a){this.qQ()?a.rJa():this.dwb.push(a)};l.oab=function(a){if(this.qQ()){var b=a.onCreateInstance;b&&b.call(a)}else this.cwb.push(a)};l.aPb=function(a,b){if(this.qQ()){var c=a.onRealizeControl;if(!c)throw e.qUc();c.call(a,b)}else this.fwb.push({nsb:a,parent:b})};l.rab=function(a){if(this.qQ()){var b=a.onSizeChanged;b&&b.call(a)}else this.iwb.push(a)};c.Qfb=function(){s.w.call(this)};var s=c.u(c.Qfb,c.jn);s.Ux=function(){return this.Pa()&&
this.Pa().gGc()?this:null};s[a.$.ny]=function(b){var c=!1;this.Pa()&&(c=b.Oc!==m?b.Oc:a.Z.uJ,c=c==a.Z.uJ||c==a.Z.ex||c==a.Z.LC?this.Pa().SIb(null):this.Pa().TIb(null));c||s.j.MT.call(this,b)};s[a.$.bya]=function(b){var c=!1;this.Pa()&&(c=(b.Oc!==m?b.Oc:a.Z.uJ)==a.Z.uJ?this.Pa().SIb(document.activeElement):this.Pa().TIb(document.activeElement));c||s.j.z3a.call(this,b)};c.T_b=function(){g.w.call(this)};var g=c.u(c.T_b,c.wd);e.kd(c.T_b,"PRIM_WDGT",{});c.V_b=function(){q.w.call(this);var a=this.WJa(),
a=this.cT=p[a],b=this.JH=new (a.iY());b.LANSA_Component=this;b.LANSA_Class=a;a.oab(b)};var q=c.u(c.V_b,c.wd);q.nab=function(a,b){if(this.cT.qQ()){var c=this.JH[a];if(!c)throw e.Z4b(a);return c.apply(this.JH,b)}throw e.qQa();};q.lwa=function(a){if(this.cT.qQ()){var b=this.JH["get"+a];if(!b)throw e.Y4b("get"+a);return b.call(this.JH)}throw e.qQa();};q.fBa=function(a,b){this.cT.qab(this.JH,a,b)};q.s4=function(){k.j.s4.call();var a=this;setTimeout(function(){a.cT.pab(a)},5)};q.rJa=function(){this.Ga(a.G.bZ)};
e.jb(c.V_b,"PRIM_WDGT","Object",{});var f=q;f.get=f.lwa;f.set=f.fBa;f.invoke=f.nab;c.U_b=function(){k.w.call(this);var b=this.WJa(),b=this.cT=p[b],c=this.JH=new (b.iY());c.LANSA_Component=this;c.LANSA_Class=b;b.oab(c);this.ug&=~a.Xg.vQ;this.ug&=~a.Xg.kZ};var k=c.u(c.U_b,c.Qfb);k.eh=function(){return c.Y0b};k.Md=function(a,c,d){k.j.Md.call(this,a,c,d);a=this.Pa().ib();b.Pd[a].tNc(this.JH)};k.nab=function(a,b){if(this.cT.qQ()){var c=this.JH[a];if(!c)throw e.Z4b(a);return c.apply(this.JH,b)}throw e.qQa();
};k.lwa=function(a){if(this.cT.qQ()){var b=this.JH["get"+a];if(!b)throw e.Y4b("get"+a);return b.call(this.JH)}throw e.qQa();};k.fBa=function(a,b){this.cT.qab(this.JH,a,b)};k.QEd=function(){this.rJa()};k[a.$.Gba]=function(){this.cT.pab(this)};k[a.$.EG]=function(){this.Pb()&&this.cT.rab(this.JH)};k.Vca=function(){k.j.Vca.call(this);this.Pb()&&this.cT.rab(this.JH)};e.jb(c.U_b,"PRIM_WDGT","Control",{});f=k;f.get=f.lwa;f.set=f.fBa;f.invoke=f.nab;c.O_b=function(){d.w.call(this);this.nd=b.zd(0,0,100,100);
this.aEa=this.EEa=""};var d=c.u(c.O_b,c.Qfb);d.eh=function(){return c.y0b};d.cAc=function(){return this.EEa};d.m0c=function(b){this.EEa!=b&&(this.EEa=b,this.ca(a.f.h),this.Kd())};d.aU=function(){return this.aEa};d.Nkb=function(a){this.aEa=a};d.IC=function(a){var d=this.Ap(),e=this.tr();if(d||e){var f=new c.ga,h=[];h[0]=d;h[1]=e;h[2]=a;h[3]=0;h[4]=0;var k=this.ib();h[3]=0;h[4]=0;null!=k&&b.Pd[k].jcd(h);f.Ra(h[3]);f.Ha(h[4]);d&&a.Ra(a.Q()+this.ea.nj()+f.aa()+this.ea.Ik());e&&a.Ha(a.O()+this.ea.Jk()+
f.ba()+this.ea.vm())}};e.jb(c.O_b,"PRIM_WEB","HtmlContainer",{Oa:{Html:{a:d.cAc,g:function(a){this.m0c(e.ma(a))}},Description:{a:d.aU,g:function(a){this.Nkb(e.ma(a))}}},lg:{hg:"Html"}});c.egb=function(a){h.w.call(this,a)};var h=c.u(c.egb,c.kn);h.PLa=function(){return!1};h.SLa=function(){return this.pa.fs()||this.pa.FK?!1:!0};h.gGc=function(){return 0<this.w1a().length};h.zM=function(a){h.j.zM.call(this,a);return!1};h.SIb=function(a){var b=this.w1a();for(a=a?b.indexOf(a)+1:0;0<=a&&a<b.length;){var c=
b[a];if(c&&(c.focus(),c==document.activeElement))return!0;a++}return!1};h.TIb=function(a){var b=this.w1a();for(a=a?b.indexOf(a)-1:b.length-1;0<=a;){var c=b[a];if(c&&(c.focus(),c==document.activeElement))return!0;a--}return!1};h.w1a=function(){var a=[],b=[];this.i3b(this.J,b);for(var c=1;c<b.length;c++)a=a.concat(b[c]||[]);return a=a.concat(b[0]||[])};h.i3b=function(a,b){var c=a.tabIndex;0<=c&&(b[c]===m&&(b[c]=[]),b[c].push(a));for(var c=a.childNodes,d=0;d<c.length;d++)a=c[d],this.i3b(a,b)};h.o3=h[a.Ma.mN]=
function(b){b.Ue=a.Ma.Qia|a.Ma.NHa};c.Y0b=function(a){w.w.call(this,a);this.eb=null};var w=c.u(c.Y0b,c.egb);w.lf=function(a,b){this.J=document.createElement("div");this.J.setAttribute("id",a+this.gc);this.J.setAttribute("LANSAHandle",this.gc);return w.j.lf.call(this,a,b)};w.tNc=function(a){null==this.eb&&(this.eb=document.createElement("div"),this.eb.style.left="0px",this.eb.style.top="0px",this.eb.style.width="100%",this.eb.style.height="100%",a.LANSA_Class.aPb(a,this.eb),this.J.appendChild(this.eb))};
c.y0b=function(a){D.w.call(this,a);this.eb=null};var D=c.u(c.y0b,c.egb);D.hz=function(){D.j.hz.call(this);this.J.style.whiteSpace="normal"};D.lf=function(a,b){this.J=document.createElement("div");this.J.setAttribute("id",a+this.gc);this.J.setAttribute("LANSAHandle",this.gc);this.eb=document.createElement("div");this.eb.style.left="0px";this.eb.style.top="0px";this.eb.style.width="100%";this.eb.style.height="100%";this.eb.innerHTML=this.pa.EEa;this.J.appendChild(this.eb);return D.j.lf.call(this,a,
b)};D.Xbd=function(){var a=this.pa.Ap(),b=this.pa.tr();this.eb.style.width=a?"":"100%";this.eb.style.height=b?"":"100%";this.eb.innerHTML=this.pa.EEa};D.Md=function(){D.j.Md.call(this);this.Xbd()};D.jcd=function(a){var b=a[0],c=a[2],d=this.eb.style.width;a[1]&&!b&&(this.eb.style.width=c.aa()+"px");a[3]=this.eb.clientWidth;a[4]=this.eb.clientHeight;this.eb.style.width=d}});
