window.LANSA.addSrc("coll",function(e,c,a,b,m){a.DMa={cmc:0,i5a:1};var p=0;c.Xla=function(){l.w.call(this)};var l=c.u(c.Xla,c.wd);l.Nyb=function(){return!1};l.YPb=function(){return!1};l.mc=function(){return 0};l.bg=function(){return 0==this.mc()};l.FX=function(a){a&&(a.Ba(),a.Yhc(this))};l.UX=function(a){a&&(a.xb(),a.QTc(this))};l.SZ=function(a,b){this.DPa(b);null!=this.yS&&this.yS.SZ(a,b)};l.r5=function(a,b){this.EPa(b);null!=this.yS&&this.yS.r5(a,b)};e.kd(c.Xla,"PRIM_COLL",{Oa:{AllowsDuplicates:{a:function(){return this.Nyb()}},
IsEmpty:{a:function(){return this.bg()}},IsOrdered:{a:function(){return this.YPb()}},ItemCount:{a:function(){return this.mc()}}}});c.BNa=function(){s.w.call(this);this.ab=[];this.yS=null};var s=c.u(c.BNa,c.Xla);s.U=function(){this.bk();s.j.U.call(this)};s.Nyb=function(){return!0};s.YPb=function(){return!0};s.mc=function(){return this.ab.length};s.Td=function(a){if(0>a||a>=this.ab.length)throw e.FE(a,this.ab.length);return this.ab[a]};s.ll=function(a,b){if(0>a||a>this.ab.length)throw e.FE(a,this.ab.length);
a==this.ab.length?this.ls(b):this.wjb(b,a)};s.h7a=function(a,b){return b===m?this.ab.indexOf(a):this.ab.indexOf(a,b)};s.OKb=function(a){return this.ab.lastIndexOf(a)+1};s.$6a=function(){return 0<this.ab.length?this.ab[0]:null};s.t7a=function(){return 0<this.ab.length?this.ab[this.ab.length-1]:null};s.apd=function(){return this.Ffa};s.h_=function(a){this.Ffa=a};s.PGa=function(a){this.h_(a.z4b())};s.pe=function(a){return-1!=this.ab.indexOf(a)};s.ls=s.VOb=function(a){this.FX(a);this.ab.push(a);this.SZ(a,
this.mc()-1)};s.UOb=function(a){this.FX(a);this.ab.unshift(a);this.SZ(a,0)};s.TOb=function(a,b){if(0>b||b>=this.ab.length)throw e.FE(b,this.ab.length);this.FX(a);this.ab.splice(b+1,0,a);this.SZ(a,b+1)};s.aab=function(a,b){if(0>b||b>=this.ab.length)throw e.FE(b,this.ab.length);this.FX(a);this.ab.splice(b,0,a);this.SZ(a,b)};s.Zs=function(a){a=this.ab.indexOf(a);if(-1==a)throw e.pUc();return this.zr(a)};s.zr=function(a){if(0>a||a>=this.ab.length)throw e.FE(a,this.ab.length);var b=this.ab[a];this.ab.splice(a,
1);e.ria(b);this.UX(b);this.r5(b,a);return b};s.qjb=function(){return this.zr(0)};s.sjb=function(){return this.zr(this.ab.length-1)};s.bk=function(){for(var a=0;a<this.ab.length;a++)this.UX(this.ab[a]);this.ab=[];this.Lca()};s.Ghb=function(a){for(var b=0,c=0;c<this.ab.length;c++)this.ab[c]===a&&b++;return b};s.wjb=function(a,b){if(0>b||b>=this.ab.length)throw e.FE(b,this.ab.length);var c=this.ab[b];e.ria(c);this.UX(c);this.ab[b]=a;this.FX(a);return c};s.Fg=function(){var a=e.J2a(this.Ffa);if(a=e.Xc(a.lPa,
a.Mqb))this.Kma(a),this.ls(a)};s.Sj=function(){this.bk()};s.Th=function(a){if(0<=a&&a<this.mc()){var b=this.Td(a);b&&this.hca(b);this.rl=a;return"OK"}this.rl=-1;return"NR"};s.yo=function(){return this.mc()};s.Rm=function(a){a===m&&(a=this.rl);0<=a&&a<this.mc()&&this.zr(a)};s.ol=function(){var a=this.rl;0<=a&&a<this.mc()&&(a=this.Td(a))&&this.Kma(a)};s.Gn=function(a,b,c){for(var d=0;d<this.mc();d++){var e=this.Td(d);if(e&&(e=e.RY())){var f={},h;for(h in e)f[h]=e[h].get();if(a(f))return null!=b&&b.set(d+
1),c&&this.Th(d),this.rl=d,"OK"}}return"NR"};s.Dq=function(a){this.bk();for(var b=0;b<a;b++)this.Fg()};s.qs=function(){return new c.Aeb(this)};s.uAa=function(){null==this.yS&&(this.yS=new c.SWb);return this.yS};c.SWb=function(){g.w.call(this)};var g=c.u(c.SWb,c.Beb);c.NWb=function(){q.w.call(this);this.rl=-1};var q=c.u(c.NWb,c.BNa);q.YT=function(){return"PRIM_LCOL<"+this.Ffa+">"};q.Eic=function(a){for(var b=0;b<a.mc();b++)this.ls(a.Td(b))};q.pmc=function(a){for(var b=e.Xc("PRIM_LCOL"),c=0;c<this.mc();c++)b.ls(this.Td(c));
for(c=0;c<a.mc();c++)b.ls(a.Td(c));e.ria(b);return b};e.kd(c.NWb,"PRIM_LCOL",{tJ:a.Ev.W0a,Oa:{First:{a:function(){return this.$6a()}},Last:{a:function(){return this.t7a()}},Item:{a:function(a){return this.Td(e.K(a)-1)},g:function(a,b){this.ll(e.K(a)-1,b)}},IndexOf:{a:function(a,b){return this.h7a(a,b===m?m:e.K(b)-1)+1}},LastIndexOf:{a:q.OKb},Collects:{g:q.h_}},jc:{Append:q.Eic,Concatenate:q.pmc,Contains:q.pe,Insert:q.ls,InsertFirst:q.UOb,InsertLast:q.VOb,InsertAfter:function(a,b){return this.TOb(a,
e.K(b)-1)},InsertBefore:function(a,b){return this.aab(a,e.K(b)-1)},Remove:q.Zs,RemoveAt:function(a){return this.zr(e.K(a)-1)},RemoveFirst:q.qjb,RemoveLast:q.sjb,RemoveAll:q.bk,OccurrencesOf:q.Ghb,ReplaceAt:function(a,b){return this.wjb(a,e.K(b)-1)}},lg:{hg:"Item"},fq:{Cba:function(a){var b=e.Xc("PRIM_NMBR");b.set(a);return b},Bp:function(a){return this.Td(e.K(a)-1)},Qv:function(){return this.mc()}},py:{Fg:q.Fg,Th:function(a){return this.Th(e.K(a)-1)},Dq:q.Dq,Sj:q.Sj,yo:q.yo,Rm:function(a){return this.Rm(a?
e.K(a)-1:m)},ol:q.ol,Gn:q.Gn,qs:q.qs}});c.dTb=function(){f.w.call(this)};var f=c.u(c.dTb,c.BNa);f.YT=function(){return"PRIM_ACOL<"+this.Ffa+">"};e.kd(c.dTb,"PRIM_ACOL",{tJ:a.Ev.W0a,Oa:{First:{a:function(){return this.$6a()}},Last:{a:function(){return this.t7a()}},Item:{a:function(a){return this.Td(e.K(a)-1)},g:function(a,b){this.ll(e.K(a)-1,b)}},IndexOf:{a:function(a,b){return this.h7a(a,b===m?m:e.K(b)-1)+1}},LastIndexOf:{a:f.OKb},Collects:{g:f.h_}},jc:{Contains:f.pe,Insert:f.ls,InsertFirst:f.UOb,
InsertLast:f.VOb,InsertAfter:function(a,b){return this.TOb(a,e.K(b)-1)},InsertBefore:function(a,b){return this.aab(a,e.K(b)-1)},Remove:f.Zs,RemoveAt:function(a){return this.zr(e.K(a)-1)},RemoveFirst:f.qjb,RemoveLast:f.sjb,RemoveAll:f.bk,OccurrencesOf:f.Ghb,ReplaceAt:function(a,b){return this.wjb(a,e.K(b)-1)}},lg:{hg:"Item"},fq:{Cba:function(a){var b=e.Xc("PRIM_NMBR");b.set(a);return b},Bp:function(a){return this.Td(e.K(a)-1)},Qv:function(){return this.mc()}},py:{Fg:f.Fg,Th:function(a){return this.Th(e.K(a)-
1)},Dq:f.Dq,Sj:f.Sj,yo:f.yo,Rm:function(a){return this.Rm(a?e.K(a)-1:m)},ol:f.ol,Gn:f.Gn,qs:f.qs}});c.ZWb=function(){k.w.call(this)};var k=c.u(c.ZWb,c.BNa);k.ls=function(b){this.FX(b);for(var c=0,d=this.ab.length-1;c<=d;){var e=Math.floor((c+d)/2);this.dvc(b,this.ab[e])==a.Pc.Xk?d=e-1:c=e+1}this.ab.splice(c,0,b)};k.dvc=function(b,c){var d=a.Pc.nk,f=e.Tb();f.Zb("SUBJECT",b);f.Zb("OBJECT",c);f.SO("RESULT",d,a.Pc.v);this.Ga(a.G.qHa,f);d=f.X6a("RESULT",a.Pc.v);f.sc();return d};e.kd(c.ZWb,"PRIM_SACO",
{Oa:{First:{a:function(){return this.$6a()}},Last:{a:function(){return this.t7a()}},Item:{a:function(a){return this.Td(e.K(a)-1)},g:function(a,b){this.ll(e.K(a)-1,b)}},IndexOf:{a:function(a,b){return this.h7a(a,b===m?m:e.K(b)-1)+1}},Collects:{g:k.h_}},jc:{Remove:k.Zs,RemoveAt:function(a){return this.zr(e.K(a)-1)},RemoveAll:k.bk,RemoveLast:k.sjb,RemoveFirst:k.qjb,Contains:k.pe,OccurrencesOf:k.Ghb,Insert:k.ls},lg:{hg:"Item"},fq:{Cba:function(a){var b=e.Xc("PRIM_NMBR");b.set(a);return b},Bp:function(a){return this.Td(e.K(a)-
1)},Qv:function(){return this.mc()}}});c.xZ=function(a){d.w.call(this);this.Vfc=a};var d=c.u(c.xZ,c.Xla);d.Td=function(a){if(0>a||a>=this.mc())throw e.FE(a,this.mc());return this.Kw(a)};d.mc=function(){return this.Vfc.mc()};d.Kw=function(a){return this.Vfc.Kw(a)};e.kd(c.xZ,"PRIM_PCOL",{Oa:{Item:{a:function(a){return this.Td(e.K(a)-1)},g:function(a,b){this.ll(e.K(a)-1,b)}}},lg:{hg:"Item"},fq:{Bp:function(a){return this.Kw(e.K(a)-1)},Qv:function(){return this.mc()}}});c.MWb=function(){h.w.call(this);
this.ab={};this.rS=null;this.bf=a.DMa.i5a};var h=c.u(c.MWb,c.Xla);h.U=function(){this.bk();h.j.U.call(this)};h.YT=function(){return"PRIM_KCOL<"+this.JVa+" "+this.tAc()+">"};h.rg=function(){return this.bf};h.tb=function(a){this.bf=a};h.mc=function(){return this.sca().length};h.Td=function(b){b=this.p1a(b);if(this.ab[b]===m&&this.bf==a.DMa.i5a){var c=null;this.ztb?c=new this.ztb:this.JVa&&(c=e.J2a(this.JVa),c=e.Xc(c.lPa,c.Mqb));c&&(this.ab[b]=c,this.FX(c),this.UG())}return this.ab[b]};h.ll=function(a,
b){a=this.p1a(a);var c=a.toString();this.ab[c]===m?this.UG():this.UX(this.ab[c]);this.FX(b);this.ab[c]=b};h.Kw=function(a){a=this.sca()[a];return this.ab[a]};h.p7a=function(a){a=this.sca()[a];this.rS.set(a);return this.rS};h.q7a=function(a){for(var b in this.ab)if(this.ab[b]===a)return this.s1a(b);return this.rS.XBc()};h.h_=function(a,b){"string"!==typeof a?this.ztb=a:(this.JVa=a,this.ztb=b)};h.xRa=function(a){this.rS=new a;this.rS.Ba()};h.bpd=function(){return this.JVa};h.tAc=function(){var a="";
this.rS&&(a=this.rS.xva());return a};h.PGa=function(a){this.h_(a.z4b(),a.wAb(0));this.xRa(a.wAb(1))};h.p1a=function(a){this.rS.set(a);a=this.rS.get();return a.toString()};h.s1a=function(a){this.rS.set(a);return this.rS.get()};h.Zs=function(a){a=this.p1a(a);var b=null;this.ab[a]!==m&&(b=this.ab[a],e.ria(b),this.UX(b),delete this.ab[a],this.UG(),this.r5(b,0));return b};h.bk=function(){for(var a in this.ab)this.UX(this.ab[a]);this.ab={};this.UG();this.Lca()};h.UG=function(){delete this.xF};h.sca=function(){var a=
this;if(this.xF===m){this.xF=[];for(var b in this.ab)this.xF.push(b);this.xF.sort(function(b,c){b=a.s1a(b);c=a.s1a(c);return e.cmp(b,c)})}return this.xF};var w={COLLECTION:a.DMa.cmc,FACTORY:a.DMa.i5a};e.kd(c.MWb,"PRIM_KCOL",{Oa:{Style:{a:function(){return e.ta(this.rg(),w)},g:function(a){this.tb(e.ra(a,w))}},Item:{a:function(a){return this.Td(a)},g:function(a,b){this.ll(a,b)},Ew:"na"},Collects:{g:h.h_},KeyedBy:{g:h.xRa},KeyOf:{a:function(a){return this.q7a(a)},Ew:"na"}},jc:{Remove:h.Zs,RemoveAll:h.bk},
lg:{hg:"Item"},fq:{Cba:function(a){return this.p7a(e.K(a)-1)},Bp:function(a){return this.Kw(e.K(a)-1)},Qv:function(){return this.mc()}}});c.dWb=function(){D.w.call(this);this.kS=(p++).toString();this.KH=[];this.Ffa=this.Efc=""};var D=c.u(c.dWb,c.Xla);D.YT=function(){return"PRIM_DCOL<"+this.Ffa+" "+this.Efc+">"};D.mc=function(){return this.KH.length};D.Kw=function(a){return this.KH[a].vH[this.kS]};D.Td=function(a){return a.vH===m||a.vH[this.kS]===m?null:a.vH[this.kS]};D.ll=function(a,b){a.vH===m&&
(a.vH={});var c=a.vH[this.kS];c===m?(this.KH.push(a),a.Ba()):this.UX(c);a.vH[this.kS]=b;this.FX(b)};D.p7a=function(a){return this.KH[a]};D.h_=function(a){this.Ffa=a};D.xRa=function(a){this.Efc=a};D.q7a=function(a,b){for(var c=b;c<this.KH.length;c++){var d=this.KH[c];if(d.vH[this.kS]===a)return d}return null};D.Luc=function(a){return this.Td(a)};D.pe=function(a){return-1!=this.KH.indexOf(a)};D.umc=function(a){for(var b=0;b<this.KH.length;b++)if(this.KH[b].vH[this.kS]===a)return!0;return!1};D.ls=function(a,
b){var c=this.Td(b);this.ll(b,a);return c};D.Zs=function(a){if(a.vH!==m){var b=a.vH[this.kS];if(b!==m)return delete a.vH[this.kS],this.KH.splice(this.KH.indexOf(a),1),e.ria(b),this.UX(b),a.xb(),this.r5(b,0),b}return null};D.bk=function(){for(var a=0;a<this.KH.length;a++){var b=this.KH[a],c=b.vH[this.kS];c!==m&&(delete b.vH[this.kS],this.UX(c))}this.KH=[];this.Lca()};e.kd(c.dWb,"PRIM_DCOL",{Oa:{Item:{a:function(a){return this.Td(a)},g:function(a,b){this.ll(a,b)},Ew:"na"},Collects:{g:D.h_,Ew:"na"},
KeyedBy:{g:D.xRa,Ew:"na"},KeyOf:{a:function(a,b){return this.q7a(a,b!==m?e.K(b)-1:0)},Ew:"na"}},jc:{Contains:D.pe,ContainsItem:D.umc,Insert:D.ls,Remove:D.Zs,RemoveAll:D.bk,Find:D.Luc},lg:{hg:"Item"},fq:{Cba:function(a){return this.p7a(e.K(a)-1)},Bp:function(a){return this.Kw(e.K(a)-1)},Qv:function(){return this.mc()}}})});
