(function(d){var c=c||{},a="Page ",b="",n=d.jsPDF;c.Gc={pO:4112,mS:4096,o1a:4097,KC:16,Rz:0,oO:1,m1a:272,nO:256,n1a:257,lxb:65536};c.di={oS:0,z6:1,y6:2,nL:3};n.fontAlias={FontAwesome:"FontAwesome","font-awesome":"FontAwesome",NotoSans:"Noto Sans",notosans:"Noto Sans",Roboto:"Roboto",roboto:"Roboto",Verdana:"Verdana",verdana:"Verdana"};n.fontFiles={FontAwesome:{fontFamily:"FontAwesome",vfs:"fontawesome-webfont-vfs.js",fonts:[{ttf:"fontawesome-webfont.ttf",style:"normal"}]},"Material Icons":{fontFamily:"Material Icons",
vfs:"MaterialIcons-Regular-vfs.js",fonts:[{ttf:"MaterialIcons-Regular.ttf",style:"normal"}]},"Noto Sans":{fontFamily:"Noto Sans",vfs:"NotoSans-vfs.js",fonts:[{ttf:"NotoSans-Regular.ttf",style:"normal"},{ttf:"NotoSans-Italic.ttf",style:"italic"},{ttf:"NotoSans-Bold.ttf",style:"bold"},{ttf:"NotoSans-BoldItalic.ttf",style:"bolditalic"}]},"Noto Sans CJK jp":{fontFamily:"Noto Sans CJK jp",vfs:"NotoSansCJKjp-vfs.js",fonts:[{ttf:"NotoSansCJKjp-Regular.min.ttf",style:"normal"},{ttf:"NotoSansCJKjp-Bold.min.ttf",
style:"bold"}]},Verdana:{fontFamily:"Verdana",vfs:"verdana-vfs.js",fonts:[{ttf:"verdana.ttf",style:"normal"},{ttf:"verdanai.ttf",style:"italic"},{ttf:"verdanab.ttf",style:"bold"},{ttf:"verdanabi.ttf",style:"bolditalic"}]},Roboto:{fontFamily:"Roboto",uniqueId:"Roboto",vfs:"Roboto-vfs.js",fonts:[{ttf:"Roboto-Bold-webfont.ttf",style:"bold"},{ttf:"Roboto-BoldItalic-webfont.ttf",style:"bolditalic"},{ttf:"Roboto-Italic-webfont.ttf",style:"italic"},{ttf:"Roboto-Regular-webfont.ttf",style:"normal"}]}};n.YDd=
function(a){var b=n.fontFiles,c=b[a];c||(a=n.fontAlias[a])&&(c=b[a]);return c?c.fontFamily:null};n.addFont=function(a){if(a){var b=n.instance,c=a.fontFamily;a=a.fonts;for(var d=0;d<a.length;d++){var k=a[d];b.addFont(k.ttf,c,k.style)}}};n.textEx=function(a,b,c,d,k){var g=/\r\n|\r|\n/g,f=this.internal.getFontSize()/this.internal.scaleFactor,e=null,n=1;if("middle"===k||"bottom"===k||"center"===d||"right"===d)e="string"===typeof a?a.split(g):a,n=e.length||1;c+=f*(2-1.15);"middle"===k?c-=n/2*f:"bottom"===
k&&(c-=n*f);if("center"===d||"right"===d){k=f;"center"===d&&(k*=0.5);if(1<n){for(a=0;a<e.length;a++)this.text(e[a],b-this.getStringUnitWidth(e[a])*k,c),c+=f;return this}b-=this.getStringUnitWidth(a)*k}this.text(a,b,c);return this};n.TDd=function(a){if("head"===a.section){var b=a.cell.styles,c=b[a.column.dataKey];Object.keys(c||{}).forEach(function(a){b[a]=c[a]})}};n.RDd=function(a){var b=a.doc,d=a.section,p=a.cell,k=p.raw,g=k?k._widget:null;if(g&&"body"===d){var f=a.settings.userData.images,e=p.width,
n=p.height,C=p.x,m=p.y;switch(g.type){case "image":var s=g.url,D=f[s];if(f=D?D.base64:null)D=D.ext,a=p.contentHeight-0.2,b.addImage(f,D,C+0.5*(e-a),m+0.1,a,a,s);break;case "button":d=g.caption;a=d.content;var d=d.align,k=g.image,B=g.borders,D=B?B.width:null,y=B?B.color:null,s=g.radius,K=g.fillColor||(B?[247,247,247]:[238,238,238]),H=p.styles,E=H?H.cellPadding?H.cellPadding:0:0,p=C+0.05*e,m=m+0.1*n,J=0.9*e,g=0.5*J,ba=0.8*n,n=0.5*ba,U=p+J,w=m+ba,V=B?"FD":"F",z=B=0,ea=b.getTextDimensions(a),ca=ea.w,
O=0.5*ca,ea=ea.h,S=0.5*ea,F=null;50<J&&(J=50,g=0.5*J,p=C+(e-J)/2,U=p+J);b.setFillColor(K[0],K[1],K[2]);D&&(e=y?y:H.textColor)&&b.setDrawColor(e[0],e[1],e[2]);s?b.roundedRect(p,m,J,ba,n,n,V):b.rect(p,m,J,ba,V);if(k){if(s=k.url,f=(D=f[s])?D.base64:null){D=D.ext;e=0.35*ba;C=0.5*e;y=ba=0;switch(k.align){case c.di.oS:switch(d){case c.Gc.KC:B=p+1;ba=B+O-C;y=m+1;z=y+e+1+S;F=["left","middle"];break;case c.Gc.oO:B=U-1;z=m+n;F=["right","middle"];ba=B-O-C;y=z-S-e-1;y<m&&(y=m+1,z=y+e+S+1);break;case c.Gc.nO:B=
p+g;z=w-1;F=["center","bottom"];ba=B-C;y=z-ea-e-1;break;default:B=p+g,ba=B-C,y=m+1,z=y+e+S+2,F=["center","middle"]}break;case c.di.z6:switch(d){case c.Gc.mS:B=p+g;z=m+1;F=["center","top"];ba=B-C;y=z+ea+1;break;case c.Gc.KC:y=w-e-1;z=y-S-1;B=p+1;ba=B+O-C;F=["left","middle"];break;case c.Gc.oO:B=U-1;z=m+n;F=["right","middle"];ba=B-O-C;y=z+S+1;y+e>w&&(y=w-e-1,z=y-S-1);break;case c.Gc.nO:B=p+g;ba=B-C;y=w-e-1;z=y-S-1;F=["center","middle"];break;default:B=p+g,z=m+n,F=["center","middle"],ba=B-C,y=z+S+1,
y+e>w&&(y=w-e-1,z=y-S-1)}break;case c.di.y6:switch(d){case c.Gc.mS:B=p+g;z=m+1;F=["center","top"];ba=B+O+1;y=z;break;case c.Gc.KC:B=p+1;z=m+n;F=["left","middle"];ba=B+ca+1;y=z-C;break;case c.Gc.oO:ba=U-e-1;B=ba-1;z=m+n;y=z-C;F=["right","middle"];break;case c.Gc.nO:B=p+g;z=w-1;F=["center","bottom"];ba=B+O+1;y=w-e-1;break;default:B=p+g,z=m+n,F=["center","middle"],ba=B+O+1,y=z-C}break;default:switch(d){case c.Gc.mS:B=p+g;z=m+1;y=m+1;ba=B-O-e-1;F=["center","top"];break;case c.Gc.KC:ba=p+1;B=ba+e+1;z=
m+n;F=["left","middle"];y=z-C;break;case c.Gc.oO:B=U-1;z=m+n;ba=B-ca-e-1;y=z-C;F=["right","middle"];break;case c.Gc.nO:B=p+g;z=w-1;F=["center","bottom"];ba=B-O-e-1;y=w-e-1;break;default:B=p+g,z=m+n,F=["center","middle"],ba=B-O-e-1,y=z-C}}b.addImage(f,D,ba,y,e,e,s)}}else switch(d){case c.Gc.mS:B=p+g;z=m+1;F=["center","top"];break;case c.Gc.KC:B=p+E;z=m+n;F=["left","middle"];break;case c.Gc.oO:B=p+(J-1);z=m+n;F=["right","middle"];break;case c.Gc.nO:B=p+g;z=w-1;F=["center","bottom"];break;default:B=
p+g,z=m+n,F=["center","middle"]}b.textEx(a,B,z,F[0],F[1])}}};n.SDd=function(c){var d=c.doc,n=d.internal,p=c.settings;c=a+n.getNumberOfPages().toString();n=n.pageSize;n=n.height?n.height:n.getHeight();p=p.margin.left;b&&d.setFont(b,"normal");d.setFontSize(9);d.setTextColor(76,76,76);d.text(c,p,n-9)};n.AFd=function(c){a=c.pageFooter;b=c.ovrFont};window.jsPDF.API.textEx=n.textEx;window.LANSA.jsPDF.getFontFamily=n.YDd;window.LANSA.jsPDF.addFont=n.addFont;window.LANSA.jsPDF.didParseCell=n.TDd;window.LANSA.jsPDF.didDrawCell=
n.RDd;window.LANSA.jsPDF.didDrawPage=n.SDd;window.LANSA.jsPDF.setLanguageInfo=n.AFd})(window.LANSA);
