(function(d){d.jsPDF=d.jsPDF||{instance:null};var c=c||{},a="Page ",b="",p=d.jsPDF;c.Gc={DO:4112,ES:4096,N2a:4097,TC:16,dA:0,CO:1,L2a:272,BO:256,M2a:257,bzb:65536};c.ji={GS:0,d7:1,c7:2,AL:3};p.imageDataUrl={};p.jsPDF_fontList=[];p.ovrFont=null;p.vfsFontQueue=[];p.vfsNode=document.createElement("div");p.vfsNode.setAttribute("id","jsPDF-VFSFiles");document.body.appendChild(p.vfsNode);p.fontAlias={FontAwesome:"FontAwesome","font-awesome":"FontAwesome","Noto Sans":"Noto Sans","noto sans":"Noto Sans",
NotoSans:"Noto Sans",notosans:"Noto Sans","Noto Sans CJK jp":"Noto Sans CJK jp","noto sans cjk jp":"Noto Sans CJK jp","NotoSans CJK jp":"Noto Sans CJK jp","notosans cjk jp":"Noto Sans CJK jp",Roboto:"Roboto",roboto:"Roboto",Verdana:"Verdana",verdana:"Verdana"};p.fontFiles={FontAwesome:{fontFamily:"FontAwesome",vfs:"fontawesome-webfont-vfs.js",fonts:[{ttf:"fontawesome-webfont.ttf",style:"normal"}]},"Material Icons":{fontFamily:"Material Icons",vfs:"MaterialIcons-Regular-vfs.js",fonts:[{ttf:"MaterialIcons-Regular.ttf",
style:"normal"}]},"Noto Sans":{fontFamily:"Noto Sans",vfs:"NotoSans-vfs.js",fonts:[{ttf:"NotoSans-Regular.ttf",style:"normal"},{ttf:"NotoSans-Italic.ttf",style:"italic"},{ttf:"NotoSans-Bold.ttf",style:"bold"},{ttf:"NotoSans-BoldItalic.ttf",style:"bolditalic"}]},"Noto Sans CJK jp":{fontFamily:"Noto Sans CJK jp",vfs:"NotoSansCJKjp-vfs.js",fonts:[{ttf:"NotoSansCJKjp-Regular.min.ttf",style:"normal"},{ttf:"NotoSansCJKjp-Bold.min.ttf",style:"bold"}]},Verdana:{fontFamily:"Verdana",vfs:"verdana-vfs.js",fonts:[{ttf:"verdana.ttf",
style:"normal"},{ttf:"verdanai.ttf",style:"italic"},{ttf:"verdanab.ttf",style:"bold"},{ttf:"verdanabi.ttf",style:"bolditalic"}]},Roboto:{fontFamily:"Roboto",uniqueId:"Roboto",vfs:"Roboto-vfs.js",fonts:[{ttf:"Roboto-Bold-webfont.ttf",style:"bold"},{ttf:"Roboto-BoldItalic-webfont.ttf",style:"bolditalic"},{ttf:"Roboto-Italic-webfont.ttf",style:"italic"},{ttf:"Roboto-Regular-webfont.ttf",style:"normal"}]}};p.createDocument=function(a,b,c){this.instance=a=new jsPDF({orientation:a,unit:b,format:c});this.jsPDF_fontList=
Object.keys(a.getFontList());return a};p.reset=function(){for(var a=this.vfsNode;a.firstChild;)a.removeChild(a.firstChild);delete this.imageDataUrl;this.imageDataUrl={};delete this.jsPDF_fontList;this.jsPDF_fontList=[];delete p.instance;this.instance=null};p.kHd=function(a){var b=p.fontFiles,c=b[a];c||(a=p.fontAlias[a])&&(c=b[a]);return c?c.fontFamily:null};p.addFont=function(a){if(a){var b=p.instance,c=a.fontFamily;a=a.fonts;for(var d=0;d<a.length;d++){var k=a[d];b.addFont(k.ttf,c,k.style)}}};p.textEx=
function(a,b,c,d,k){var e=/\r\n|\r|\n/g,g=this.internal.getFontSize()/this.internal.scaleFactor,f=null,p=1;if("middle"===k||"bottom"===k||"center"===d||"right"===d)f="string"===typeof a?a.split(e):a,p=f.length||1;c+=g*(2-1.15);"middle"===k?c-=p/2*g:"bottom"===k&&(c-=p*g);if("center"===d||"right"===d){k=g;"center"===d&&(k*=0.5);if(1<p){for(a=0;a<f.length;a++)this.text(f[a],b-this.getStringUnitWidth(f[a])*k,c),c+=g;return this}b-=this.getStringUnitWidth(a)*k}this.text(a,b,c);return this};p.dHd=function(a){if("head"===
a.section){var b=a.cell.styles,c=b[a.column.dataKey];Object.keys(c||{}).forEach(function(a){b[a]=c[a]})}};p.bHd=function(a){function b(a,c,d,e,f){var g=0;switch(f){case "left":g=a+e;break;case "right":g=a+c-d-e;break;default:g=a+0.5*(c-d)}return g}function d(a,b,c,e,f){var g=0;switch(f){case "top":g=a+e;break;case "bottom":g=a+b-c-e;break;default:g=a+0.5*(b-c)}return g}var p=a.doc,k=a.section,e=a.cell,g=e.styles,f=e.raw,v=f?f._widget:null;if(v&&"body"===k){var B=a.settings.userData.images;a=e.width;
var n=e.height,k=e.x,r=e.y;switch(v.type){case "image":var E=v.url,C=B[E];if(B=C?C.base64:null){var C=v.format||C.ext,f=v.height||e.contentHeight-0.2,x=v.width||f,e=v.height?g.cellPadding:0.1;p.addImage(B,C,b(k,a,x,e,g.halign||"center"),d(r,n,f,e,g.valign||"middle"),x,f,E,v.compression||"NONE",v.rotation||0)}break;case "button":var f=v.caption,g=f.content,f=f.align,x=v.image,K=v.borders,C=K?K.width:null,I=K?K.color:null,E=v.radius,D=v.fillColor||(K?[247,247,247]:[238,238,238]),M=e.styles,ca=M?M.cellPadding?
M.cellPadding:0:0,v=k+0.05*a,r=r+0.1*n,F=0.9*a,e=0.5*F,z=0.8*n,n=0.5*z,W=v+F,y=r+z,ea=K?"FD":"F",Z=K=0,L=p.getTextDimensions(g),S=L.w,G=0.5*S,L=L.h,H=0.5*L,V=null;50<F&&(F=50,e=0.5*F,v=k+(a-F)/2,W=v+F);p.setFillColor(D[0],D[1],D[2]);C&&(a=I?I:M.textColor)&&p.setDrawColor(a[0],a[1],a[2]);E?p.roundedRect(v,r,F,z,n,n,ea):p.rect(v,r,F,z,ea);if(x){if(E=x.url,B=(C=B[E])?C.base64:null){C=C.ext;a=0.35*z;k=0.5*a;I=z=0;switch(x.align){case c.ji.GS:switch(f){case c.Gc.TC:K=v+1;z=K+G-k;I=r+1;Z=I+a+1+H;V=["left",
"middle"];break;case c.Gc.CO:K=W-1;Z=r+n;V=["right","middle"];z=K-G-k;I=Z-H-a-1;I<r&&(I=r+1,Z=I+a+H+1);break;case c.Gc.BO:K=v+e;Z=y-1;V=["center","bottom"];z=K-k;I=Z-L-a-1;break;default:K=v+e,z=K-k,I=r+1,Z=I+a+H+2,V=["center","middle"]}break;case c.ji.d7:switch(f){case c.Gc.ES:K=v+e;Z=r+1;V=["center","top"];z=K-k;I=Z+L+1;break;case c.Gc.TC:I=y-a-1;Z=I-H-1;K=v+1;z=K+G-k;V=["left","middle"];break;case c.Gc.CO:K=W-1;Z=r+n;V=["right","middle"];z=K-G-k;I=Z+H+1;I+a>y&&(I=y-a-1,Z=I-H-1);break;case c.Gc.BO:K=
v+e;z=K-k;I=y-a-1;Z=I-H-1;V=["center","middle"];break;default:K=v+e,Z=r+n,V=["center","middle"],z=K-k,I=Z+H+1,I+a>y&&(I=y-a-1,Z=I-H-1)}break;case c.ji.c7:switch(f){case c.Gc.ES:K=v+e;Z=r+1;V=["center","top"];z=K+G+1;I=Z;break;case c.Gc.TC:K=v+1;Z=r+n;V=["left","middle"];z=K+S+1;I=Z-k;break;case c.Gc.CO:z=W-a-1;K=z-1;Z=r+n;I=Z-k;V=["right","middle"];break;case c.Gc.BO:K=v+e;Z=y-1;V=["center","bottom"];z=K+G+1;I=y-a-1;break;default:K=v+e,Z=r+n,V=["center","middle"],z=K+G+1,I=Z-k}break;default:switch(f){case c.Gc.ES:K=
v+e;Z=r+1;I=r+1;z=K-G-a-1;V=["center","top"];break;case c.Gc.TC:z=v+1;K=z+a+1;Z=r+n;V=["left","middle"];I=Z-k;break;case c.Gc.CO:K=W-1;Z=r+n;z=K-S-a-1;I=Z-k;V=["right","middle"];break;case c.Gc.BO:K=v+e;Z=y-1;V=["center","bottom"];z=K-G-a-1;I=y-a-1;break;default:K=v+e,Z=r+n,V=["center","middle"],z=K-G-a-1,I=Z-k}}p.addImage(B,C,z,I,a,a,E)}}else switch(f){case c.Gc.ES:K=v+e;Z=r+1;V=["center","top"];break;case c.Gc.TC:K=v+ca;Z=r+n;V=["left","middle"];break;case c.Gc.CO:K=v+(F-1);Z=r+n;V=["right","middle"];
break;case c.Gc.BO:K=v+e;Z=y-1;V=["center","bottom"];break;default:K=v+e,Z=r+n,V=["center","middle"]}p.textEx(g,K,Z,V[0],V[1])}}};p.cHd=function(c){var d=c.doc,p=d.internal,s=c.settings;c=a+p.getNumberOfPages().toString();p=p.pageSize;p=p.height?p.height:p.getHeight();s=s.margin.left;b&&d.setFont(b,"normal");d.setFontSize(9);d.setTextColor(76,76,76);d.text(c,s,p-9)};p.VGd=function(a,b){for(var c=0;c<b.length;c++){var d=b[c],k=this[d];k&&(a[d]=k)}};p.VId=function(c){a=c.pageFooter;this.ovrFont=b=c.ovrFont};
window.jsPDF.API.textEx=p.textEx;window.LANSA.jsPDF.createDocument=p.createDocument;window.LANSA.jsPDF.reset=p.reset;window.LANSA.jsPDF.getFontFamily=p.kHd;window.LANSA.jsPDF.addFont=p.addFont;window.LANSA.jsPDF.didParseCell=p.dHd;window.LANSA.jsPDF.didDrawCell=p.bHd;window.LANSA.jsPDF.didDrawPage=p.cHd;window.LANSA.jsPDF.addHooks=p.VGd;window.LANSA.jsPDF.setLanguageInfo=p.VId})(window.LANSA);
