window.LANSA.addSrc("json",function(d,c,a,b,r){function t(a,b,e){var f=null;if(null===e)f=d.Wu(new c.QCa(a,b));else switch(typeof e){case "object":f=Array.isArray(e)?d.Wu(new c.rpa(a,b)):d.Wu(new c.spa(a,b));f.CFb(e);break;case "number":f=d.Wu(new c.RCa(a,b,e));break;case "string":f=d.Wu(new c.SCa(a,b,e));break;case "boolean":f=d.Wu(new c.PCa(a,b,e))}return f}d.Db("PRIM_PCOL");a.MF={S9a:0,JMb:1,GMb:2,KMb:3,IMb:4,HMb:5};a.MF.u={NULL:a.MF.S9a,OBJECT:a.MF.JMb,ARRAY:a.MF.GMb,STRING:a.MF.KMb,NUMBER:a.MF.IMb,
BOOLEAN:a.MF.HMb};c.S4b=function(){s.H.call(this);this.yg="";this.tJa=null;this.WCb=!1};var s=c.q(c.S4b,c.Hd);s.Q=function(){this.RVa(null);s.j.Q.call(this)};s.xIc=function(){return this.tJa};s.RVa=function(a){this.tJa=a};s.mKc=function(){return this.WCb};s.hWa=function(a){this.WCb=a};s.is=function(){return this.WCb?JSON.stringify(this.tJa.DN()):this.yg};s.YO=function(a){this.yg=a;var b=null,c=null;try{b=JSON.parse(a)}catch(d){}b?(c=t(this,null,b),this.hWa(!0)):this.hWa(!1);this.RVa(c)};s.Psc=function(){this.RVa(d.Wu(new c.rpa(this,
null)));this.hWa(!0);return this.tJa};s.Qsc=function(){this.RVa(d.Wu(new c.spa(this,null)));this.hWa(!0);return this.tJa};d.mb(c.S4b,"PRIM_WEB","Json",{Oa:{Text:{a:s.is,f:function(a){this.YO(d.ha(a))}},IsValid:{a:s.mKc},RootItem:{a:s.xIc}},qc:{CreateRootArray:s.Psc,CreateRootObject:s.Qsc},Fg:{zg:"Text"}});c.Q6=function(a,b){q.H.call(this);this.RG=a;this.pB=b};var q=c.q(c.Q6,c.Hd);q.xca=function(){return a.MF.S9a};q.DN=function(){return null};q.Ac=function(){return 0};q.ie=function(){return null};
q.Px=function(){return null};q.yxd=function(){return this.RG};q.Ebb=function(){return this.pB};q.wma=function(){return this.pB?this.pB.BPb(this):""};q.BPb=function(){return""};q.Oj=function(){return this.pB?this.pB.dbb(this):-1};q.dbb=function(){return-1};q.paa=function(){throw d.j_c(JSON.stringify(this.DN()));};q.J4a=function(){throw d.cEa(JSON.stringify(this.DN()));};q.z4a=function(){throw d.cob(JSON.stringify(this.DN()));};q.ou=function(){return null};q.Ak=function(){};d.mb(c.Q6,"PRIM_WEB","JsonElement",
{Oa:{Key:{a:q.wma},Index:{a:function(){return this.Oj()+1}},Type:{a:function(){return d.ta(this.xca(),a.MF.u)}},Item:{a:function(a){return this.ie(d.ha(a))}},ItemAt:{a:function(a){return this.Px(d.v(a)-1)}},ItemCount:{a:function(){return this.Ac()}},ParentItem:{a:q.Ebb}},qc:{AsString:function(){return this.paa()},AsNumber:function(){return d.Cq(this.J4a())},AsBoolean:function(){return this.z4a()},Remove:function(a){return this.ou(d.ha(a))},RemoveAt:function(a){return this.us(d.v(a)-1)},RemoveAll:function(){this.Ak()}},
Fg:{zg:"Item"},Tq:{pq:function(a){return this.Px(d.v(a)-1)},bx:function(){return this.Ac()}}});c.rpa=function(a,b){n.H.call(this,a,b);this.eb=[]};var n=c.q(c.rpa,c.Q6);n.xca=function(){return a.MF.GMb};n.DN=function(){for(var a=[],b=0;b<this.eb.length;b++)a.push(this.eb[b].DN());return a};n.Px=function(a){return 0<=a&&a<this.eb.length?this.eb[a]:null};n.Ac=function(){return this.eb.length};n.dbb=function(a){for(var b=0;b<this.eb.length;b++)if(this.eb[b]===a)return b;return-1};n.CFb=function(a){for(var b=
0;b<a.length;b++){var c=t(this.RG,this,a[b]);c&&this.eb.push(c)}};n.Feb=function(){var a=d.Wu(new c.rpa(this.RG,this));this.eb.push(a);return a};n.Neb=function(){var a=d.Wu(new c.spa(this.RG,this));this.eb.push(a);return a};n.Qeb=function(a){a=d.Wu(new c.SCa(this.RG,this,a));this.eb.push(a);return a};n.Meb=function(a){a=d.Wu(new c.RCa(this.RG,this,a));this.eb.push(a);return a};n.Ieb=function(a){a=d.Wu(new c.PCa(this.RG,this,a));this.eb.push(a);return a};n.Leb=function(){var a=d.Wu(new c.QCa(this.RG,
this));this.eb.push(a);return a};n.us=function(a){var b=null;0<=a&&a<this.eb.length&&(b=this.eb[a],this.eb.splice(a,1));return b};n.Ak=function(){this.eb=[]};d.mb(c.rpa,"PRIM_WEB","JsonArray",{qc:{InsertArray:n.Feb,InsertObject:n.Neb,InsertNumber:function(a){return this.Meb(d.$q(a))},InsertString:function(a){return this.Qeb(d.ha(a))},InsertBoolean:function(a){return this.Ieb(d.xa(a))},InsertNull:n.Leb}});c.spa=function(a,b){k.H.call(this,a,b);this.eb={}};var k=c.q(c.spa,c.Q6);k.xca=function(){return a.MF.JMb};
k.DN=function(){var a={},b;for(b in this.eb)a[b]=this.eb[b].DN();return a};k.ie=function(a){a=this.eb[a];return a===r?null:a};k.Px=function(a){var b=this.nea();return 0<=a&&a<b.length?this.eb[b[a]]:null};k.Ac=function(){return this.nea().length};k.BPb=function(a){for(var b in this.eb)if(this.eb[b]===a)return b};k.dbb=function(a){var b=-1,c;for(c in this.eb)if(b++,this.eb[c]===a)break;return b};k.CFb=function(a){for(var b in a){var c=t(this.RG,this,a[b]);c&&(this.eb[b]=c)}this.BI()};k.BI=function(){delete this.VG};
k.nea=function(){if(this.VG===r){this.VG=[];for(var a in this.eb)this.VG.push(a)}return this.VG};k.Feb=function(a){var b=d.Wu(new c.rpa(this.RG,this));this.eb[a]=b;this.BI();return b};k.Neb=function(a){var b=d.Wu(new c.spa(this.RG,this));this.eb[a]=b;this.BI();return b};k.Qeb=function(a,b){var e=d.Wu(new c.SCa(this.RG,this,b));this.eb[a]=e;this.BI();return e};k.Ieb=function(a,b){var e=d.Wu(new c.PCa(this.RG,this,b));this.eb[a]=e;this.BI();return e};k.Leb=function(a){var b=d.Wu(new c.QCa(this.RG,this));
this.eb[a]=b;this.BI();return b};k.Meb=function(a,b){var e=d.Wu(new c.RCa(this.RG,this,b));this.eb[a]=e;this.BI();return e};k.ou=function(a){var b=null;this.eb[a]!==r&&(b=this.eb[a],delete this.eb[a],this.BI());return b};k.us=function(a){var b=this.nea();return 0<=a&&a<b.length?this.ou(b[a]):null};k.Ak=function(){this.eb={};this.BI()};d.mb(c.spa,"PRIM_WEB","JsonObject",{qc:{InsertArray:function(a){return this.Feb(d.ha(a))},InsertObject:function(a){return this.Neb(d.ha(a))},InsertNumber:function(a,
b){return this.Meb(d.ha(a),d.$q(b))},InsertString:function(a,b){return this.Qeb(d.ha(a),d.ha(b))},InsertBoolean:function(a,b){return this.Ieb(d.ha(a),d.xa(b))},InsertNull:function(a){return this.Leb(d.ha(a))}}});c.RCa=function(a,b,c){h.H.call(this,a,b);this.ab=c};var h=c.q(c.RCa,c.Q6);h.xca=function(){return a.MF.IMb};h.DN=function(){return this.ab};h.J4a=function(){return this.ab};h.paa=function(){return this.ab.toString()};d.mb(c.RCa,"PRIM_WEB","JsonNumber",{});c.SCa=function(a,b,c){f.H.call(this,
a,b);this.ab=c};var f=c.q(c.SCa,c.Q6);f.xca=function(){return a.MF.KMb};f.DN=function(){return this.ab};f.paa=function(){return this.ab};f.J4a=function(){if(isNaN(Number(this.ab)))throw d.cEa(this.ab);return new c.Rj(this.ab)};f.z4a=function(){if("TRUE"==this.ab.toUpperCase())return!0;if("FALSE"==this.ab.toUpperCase())return!1;throw d.cob(this.ab);};d.mb(c.SCa,"PRIM_WEB","JsonString",{});c.PCa=function(a,b,c){e.H.call(this,a,b);this.ab=c};var e=c.q(c.PCa,c.Q6);e.xca=function(){return a.MF.HMb};e.DN=
function(){return this.ab};e.z4a=function(){return this.ab};e.paa=function(){return this.ab?"true":"false"};d.mb(c.PCa,"PRIM_WEB","JsonBoolean",{});c.QCa=function(a,b){p.H.call(this,a,b)};var p=c.q(c.QCa,c.Q6);p.xca=function(){return a.MF.S9a};p.DN=function(){return null};d.mb(c.QCa,"PRIM_WEB","JsonNull",{})},{rp:["PRIM_PCOL"]});
