window.LANSA.addSrc("gpbx",function(d,c,a,b){a.Fzc={JWd:0,IWd:9,ikd:6,KWd:5,LWd:10};a.BKc={KBc:0};c.e2b=function(){r.H.call(this);this.fzb=a.Fzc.ikd;this.nJ=a.BKc.KBc;this.LM=new c.ga;new c.ga;this.Zc=this.Zc|a.fc.yda|a.fc.CBa|a.fc.Ggb|a.fc.OF|a.fc.TW|a.fc.NF;this.Pg=this.Pg|a.vh.DS|a.vh.c0;this.Qe(!1)};var r=c.q(c.e2b,c.QK);r.gh=function(){return c.A5b};r.SQd=function(b){this.fzb!=b&&(this.fzb=b,this.k(a.g.h),this.ax())};r.Yxd=function(){return this.fzb};r.ur=function(a){r.j.ur.call(this,a);this.gWc()};
r.xvb=function(){if(this.Ub()){var a=this.ke(),a=Math.abs(a.Ja()),d=this.Ne();this.Rd();this.Rd();d.Va(d.O()+a);new c.ga;""==this.bb()?(d.Ra(d.O()),d.Ia(a)):(this.bb(),d.Ra(d.O()+this.SR()),d.Ia(this.Wla()),d.Ra(d.wa+a));b.El(this.LM,d)||(this.LM=d,this.ob());this.ur(!0)}};r.mf=function(a){a.Ua(a.M()+this.LM.ca());a.Va(a.O()+4);a.Ra(a.wa-4);a.Ia(a.va-4);r.j.mf.call(this,a)};r.dZc=function(a,b,c){a.Ua(a.M()+this.LM.ca());a.Va(a.O()+4);a.Ra(a.wa-4);a.Ia(a.va-4);r.j.dZc.call(this,a,b,c)};r.hj=function(){r.j.hj.call(this);
this.Fd(a.Z.ZB)};r.gd=function(){var b=this.UN()||this.Xl()&&(this.b0()||this.CS());this.CJ(a.fc.ZN,b);r.j.gd.call(this)};r.bG=function(a){var b=!1,b=a.Wc().RTa(this,this.ba.Qg,this.b0(),this.CS(),a);!1==b&&r.j.bG.call(this,a)};r.jX=function(a){var b=!1;null!=a.Wc()&&a.fa().Xl()&&(b=a.Wc().STa(this,this.ba.Qg,a,this.b0(),this.CS()));!1==b&&r.j.jX.call(this,a)};r.we=function(b){""==b[1]&&(b[1]=a.fXb);r.j.we.call(this,b)};r.gWc=function(){var a=this.Ne(),a=this.mD(a,null),c=this.Ne();c.Ua(c.M()+this.LM.ca()/
2+1);c.Va(c.O()+2);c.Ra(c.wa-2);c.Ia(c.va-2);var d=this.Sa().fb(),k=this.bb();b.be[d].sh(k,c,this.LM);b.$(a)};r.$t=r[a.Z.hI]=function(a){this.xvb();r.j.$t.call(this,a)};r.Zt=r[a.Z.PF]=function(){r.j.Zt.call(this);this.xvb()};r.kN=r[a.Z.ZB]=function(){this.xvb();this.ax()};r.oxc=r[a.Z.khb]=function(){this.Fh()};d.Ad(c.e2b,"PRIM_GPBX",{Oa:{Caption:{a:r.bb,f:function(a){this.tb(d.ha(a))}},ThemeStyle:{a:function(){return d.ta(this.NN(),a.nw.u)},f:function(b){this.oFa(d.qa(b,a.nw.u))}}}});c.A5b=function(a){t.H.call(this,
a);this.qb=this.vZa=this.jHa=this.te=this.Rc=null};var t=c.q(c.A5b,c.x0);t.Xe=function(a,b){var c=null;t.j.Xe.call(this,a,b);this.vZa=4;this.Rc=document.createElement("div");this.te=document.createElement("div");this.jHa=document.createElement("div");this.qb=document.createElement("span");this.G.appendChild(this.Rc);this.G.appendChild(this.te);this.G.appendChild(this.jHa);this.G.appendChild(this.qb);this.Ceb(this.Rc,this.vZa);this.Ceb(this.te,0);this.Ceb(this.jHa,0);c=this.Rc.style;c.borderTopWidth=
"0px";c=this.te.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.jHa.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.qb.style;c.position="absolute";c.whiteSpace="nowrap";c.cursor="inherit";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";return this.G};t.Ceb=function(a,b){var c=a.style;c.position="absolute";c.overflowX="hidden";c.overflowY=
"hidden";c.whiteSpace="nowrap";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";c.borderStyle="solid";c.outline="none";c.background="rgba(0,0,0,0)";c.borderTopWidth="1px";c.borderBottomWidth="1px";c.borderLeftWidth="1px";c.borderRightWidth="1px";c.borderTopLeftRadius=b+"px";c.webkitBorderTopLeftRadius=b+"px";c.borderTopRightRadius=b+"px";c.webkitBorderTopRightRadius=b+"px";c.borderBottomLeftRadius=b+"px";c.webkitBorderBottomLeftRadius=b+"px";c.borderBottomRightRadius=
b+"px";c.webkitBorderBottomRightRadius=b+"px"};t.sh=function(a,b,c){var d=this.Rc.style;d.left=b.O()+"px";d.top=b.M()+"px";d.width=b.aa()+"px";d.height=b.ca()+"px";d.borderColor=this.zm();d=this.te.style;d.left=b.O()+this.vZa-1+"px";d.top=b.M()+"px";d.width=c.O()-b.O()+"px";d.height="1px";d.borderColor=this.zm();d=this.jHa.style;d.left=c.wa+2+"px";d.top=b.M()+"px";d.width=b.wa-this.vZa-c.wa+"px";d.height="1px";d.borderColor=this.zm();d=this.qb.style;d.left=c.O()+7+"px";d.top=c.M()+2+"px";d.height=
c.ca()+"px";d.width=c.aa()+"px";this.qb.textContent=a}});
