window.LANSA.addSrc("wdgt",function(d,c,a,b,r){var t={};c.d6b=function(a){s.H.call(this);this.oIa=a;this.r_a=function(){};this.NP=this.sAb=!1;this.OAb=[];this.NAb=[];this.JAb=[];this.IAb=[];this.LAb=[]};var s=c.q(c.d6b,c.Pe);s.zS=function(){return this.sAb};s.Ch=function(){return this.oIa.nm};s.BIc=function(){return this.oIa.js||[]};s.lJc=function(){return this.oIa.st||[]};s.dEc=function(){return this.oIa.fn};s.XEc=function(){return this.oIa.fe};s.c_=function(){return this.r_a};s.wZc=function(){function a(){if(p<
q.length){var c=q[p],e=document.createElement("script");e.type="text/javascript";e.onload=function(){e.onload=null;e.onerror=null;p++;a()};e.onerror=function(){e.onload=null;e.onerror=null;throw"Error defining Widget "+d+", failed to load script: "+c;};document.body.appendChild(e);e.src=c}else b()}function b(){function a(){if(!c.sAb){for(c.sAb=!0;0<c.IAb.length;){var b=c.IAb.shift();c.Ueb(b)}for(;0<c.NAb.length;)b=c.NAb.shift(),c.Web(b.Qwb,b.Eld,b.value);for(;0<c.LAb.length;)b=c.LAb.shift(),c.ZTb(b.Qwb,
b.parent);for(;0<c.OAb.length;)b=c.OAb.shift(),c.Xeb(b);for(;0<c.JAb.length;)b=c.JAb.shift(),c.Veb(b)}}var d=c.dEc(),g=c.r_a.prototype;e&&e(g);var f={Loading:{},Completed:{},Finalize:function(){a()}};d(g,f)!==f.Loading&&a()}var c=this,d=c.Ch(),e=c.XEc();t[d]=c;for(var g=c.lJc(),f=0;f<g.length;f++){var h=g[f],k=document.createElement("link");k.type="text/css";k.rel="stylesheet";k.href=h;document.body.appendChild(k)}var p=0,q=c.BIc();a()};s.Web=function(a,b,c){if(this.zS()){var e=a["set"+b];if(!e)throw d.m_c("set"+
b);e&&e.call(a,c)}else this.NAb.push({Qwb:a,Eld:b,value:c})};s.Veb=function(a){this.zS()?a.RMa():this.JAb.push(a)};s.Ueb=function(a){if(this.zS()){var b=a.onCreateInstance;b&&b.call(a)}else this.IAb.push(a)};s.ZTb=function(a,b){if(this.zS()){var c=a.onRealizeControl;if(!c)throw d.l_c();c.call(a,b)}else this.LAb.push({Qwb:a,parent:b})};s.Xeb=function(a){if(this.zS()){var b=a.onSizeChanged;b&&b.call(a)}else this.OAb.push(a)};c.vkb=function(){q.H.call(this)};var q=c.q(c.vkb,c.yo);q.Vy=function(){return this.Sa()&&
this.Sa().NLc()?this:null};q[a.Z.dx]=function(b){var c=!1;this.Sa()&&(c=b.Sc!==r?b.Sc:a.W.oL,c=c==a.W.oL||c==a.W.iy||c==a.W.WD?this.Sa().FNb(null):this.Sa().GNb(null));c||q.j.iN.call(this,b)};q[a.Z.NBa]=function(b){var c=!1;this.Sa()&&(c=(b.Sc!==r?b.Sc:a.W.oL)==a.W.oL?this.Sa().FNb(document.activeElement):this.Sa().GNb(document.activeElement));c||q.j.p8a.call(this,b)};c.W4b=function(){n.H.call(this)};var n=c.q(c.W4b,c.Hd);d.Ad(c.W4b,"PRIM_WDGT",{});c.Y4b=function(){k.H.call(this);var a=this.wNa(),
a=this.dV=t[a],b=this.pJ=new (a.c_());b.LANSA_Component=this;b.LANSA_Class=a;a.Ueb(b)};var k=c.q(c.Y4b,c.Hd);k.Teb=function(a,b){if(this.dV.zS()){var c=this.pJ[a];if(!c)throw d.k$b(a);return c.apply(this.pJ,b)}throw d.gUa();};k.Wza=function(a){if(this.dV.zS()){var b=this.pJ["get"+a];if(!b)throw d.j$b("get"+a);return b.call(this.pJ)}throw d.gUa();};k.$Ea=function(a,b){this.dV.Web(this.pJ,a,b)};k.JW=function(){f.j.JW.call();var a=this;setTimeout(function(){a.dV.Veb(a)},5)};k.RMa=function(){this.Ca(a.w.o6)};
d.mb(c.Y4b,"PRIM_WDGT","Object",{});var h=k;h.get=h.Wza;h.set=h.$Ea;h.invoke=h.Teb;c.X4b=function(){f.H.call(this);var b=this.wNa(),b=this.dV=t[b],c=this.pJ=new (b.c_());c.LANSA_Component=this;c.LANSA_Class=b;b.Ueb(c);this.Pg&=~a.vh.DS;this.Pg&=~a.vh.c0};var f=c.q(c.X4b,c.vkb);f.gh=function(){return c.c6b};f.Sd=function(a,c,d){f.j.Sd.call(this,a,c,d);a=this.Sa().fb();b.be[a].fTc(this.pJ)};f.Teb=function(a,b){if(this.dV.zS()){var c=this.pJ[a];if(!c)throw d.k$b(a);return c.apply(this.pJ,b)}throw d.gUa();
};f.Wza=function(a){if(this.dV.zS()){var b=this.pJ["get"+a];if(!b)throw d.j$b("get"+a);return b.call(this.pJ)}throw d.gUa();};f.$Ea=function(a,b){this.dV.Web(this.pJ,a,b)};f.$Kd=function(){this.RMa()};f[a.Z.Bda]=function(){this.dV.Veb(this)};f[a.Z.PF]=function(){this.Ub()&&this.dV.Xeb(this.pJ)};f.Sea=function(){f.j.Sea.call(this);this.Ub()&&this.dV.Xeb(this.pJ)};d.mb(c.X4b,"PRIM_WDGT","Control",{});h=f;h.get=h.Wza;h.set=h.$Ea;h.invoke=h.Teb;c.R4b=function(){e.H.call(this);this.Jb=b.Mg(0,0,100,100);
this.NHa=this.tIa=""};var e=c.q(c.R4b,c.vkb);e.gh=function(){return c.B5b};e.HFc=function(){return this.tIa};e.m6c=function(b){this.tIa!=b&&(this.tIa=b,this.ea(a.g.h),this.Bd())};e.dW=function(){return this.NHa};e.wpb=function(a){this.NHa=a};e.MA=function(a){var d=this.uo(),e=this.oq();if(d||e){var g=new c.ga;new c.ga(0,0,1E4,1E4);var f=[];f[0]=d;f[1]=e;f[2]=a;f[3]=0;f[4]=0;var h=this.fb();f[3]=0;f[4]=0;null!=h&&b.be[h].iid(f);g.Ra(f[3]);g.Ia(f[4]);d&&a.Ra(a.O()+this.ba.Wi()+g.aa()+this.ba.$j());
e&&a.Ia(a.M()+this.ba.ak()+g.ca()+this.ba.xl())}};d.mb(c.R4b,"PRIM_WEB","HtmlContainer",{Oa:{Html:{a:e.HFc,f:function(a){this.m6c(d.ha(a))}},Description:{a:e.dW,f:function(a){this.wpb(d.ha(a))}}},Fg:{zg:"Html"}});c.Ikb=function(a){p.H.call(this,a)};var p=c.q(c.Ikb,c.qn);p.zPa=function(){return!1};p.BPa=function(){return this.na.bt()||this.na.BM?!1:!0};p.NLc=function(){return 0<this.i6a().length};p.vO=function(a){p.j.vO.call(this,a);return!1};p.FNb=function(a){var b=this.i6a();for(a=a?b.indexOf(a)+
1:0;0<=a&&a<b.length;){var c=b[a];if(c&&(c.focus(),c==document.activeElement))return!0;a++}return!1};p.GNb=function(a){var b=this.i6a();for(a=a?b.indexOf(a)-1:b.length-1;0<=a;){var c=b[a];if(c&&(c.focus(),c==document.activeElement))return!0;a--}return!1};p.i6a=function(){var a=[],b=[];this.u8b(this.G,b);for(var c=1;c<b.length;c++)a=a.concat(b[c]||[]);return a=a.concat(b[0]||[])};p.u8b=function(a,b){var c=a.tabIndex;0<=c&&(b[c]===r&&(b[c]=[]),b[c].push(a));for(var c=a.childNodes,d=0;d<c.length;d++)a=
c[d],this.u8b(a,b)};p.e5=p[a.Na.lP]=function(b){b.of=a.Na.Yka|a.Na.pLa};c.c6b=function(a){g.H.call(this,a);this.Ya=null};var g=c.q(c.c6b,c.Ikb);g.Xe=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.lc);this.G.setAttribute("LANSAHandle",this.lc);return g.j.Xe.call(this,a,b)};g.fTc=function(a){null==this.Ya&&(this.Ya=document.createElement("div"),this.Ya.style.left="0px",this.Ya.style.top="0px",this.Ya.style.width="100%",this.Ya.style.height="100%",a.LANSA_Class.ZTb(a,
this.Ya),this.G.appendChild(this.Ya))};c.B5b=function(a){z.H.call(this,a);this.Ya=null};var z=c.q(c.B5b,c.Ikb);z.kA=function(){z.j.kA.call(this);this.G.style.whiteSpace="normal"};z.Xe=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.lc);this.G.setAttribute("LANSAHandle",this.lc);this.Ya=document.createElement("div");this.Ya.style.left="0px";this.Ya.style.top="0px";this.Ya.style.width="100%";this.Ya.style.height="100%";this.Ya.innerHTML=this.na.tIa;this.G.appendChild(this.Ya);
return z.j.Xe.call(this,a,b)};z.Whd=function(){var a=this.na.uo(),b=this.na.oq();this.Ya.style.width=a?"":"100%";this.Ya.style.height=b?"":"100%";this.Ya.innerHTML=this.na.tIa};z.Sd=function(){z.j.Sd.call(this);this.Whd()};z.iid=function(a){var b=a[0],c=a[2],d=this.Ya.style.width;a[1]&&!b&&(this.Ya.style.width=c.aa()+"px");a[3]=this.Ya.clientWidth;a[4]=this.Ya.clientHeight;this.Ya.style.width=d}});
