window.LANSA.addSrc("hint",function(d,c,a,b,r){function t(b){this.Aw=b;this.Uva=b.Eo;this.lld=a.ci.EWc;this.Okd=!1;this.Jkc=new c.ga(0,0,0,0)}function s(a){this.Aw=a;this.z3a=this.qb="";this.zc=null}d.Db("PRIM_PPNL");d.Ad(function(){},"PRIM_HINT",{});c.Z4b=function(a){q.H.call(this);this.Aw=a;this.sIa=this.AU=this.Y9=this.Av=this.Gq=this.rJ=null;a=b.HS();d.Db("PRIM_PANL");d.Db("PRIM_LABL");this.rJ=new c.yo;this.rJ.Pa(this);this.rJ.kb(new c.ga(0,0,0,0));this.Gq=new c.lu;this.Av=new c.lu;this.Gq.Pa(this.rJ);
this.Av.Pa(this.rJ);this.sIa=new c.pb;this.sIa.iG(!0);this.Y9=new c.pb;this.AU=new c.pb;this.AU.od(b.U().C2);this.AU.Jp(0);this.AU.ap(0);this.AU.tn(0);this.AU.un(0);this.AU.qu(a);this.rJ.nn(this.AU);this.Av.nn(this.sIa)};var q=c.q(c.Z4b,c.by);q.tPb=function(){b.Qda().gk()?(this.rJ.xq(this.AU),this.Av.xq(this.sIa),this.Y9.Yi(b.J(114,114,114)),this.Y9.Hh(a.l.ol),this.Y9.Aq(null),this.Y9.zq(2),this.Y9.wr(0),this.nn(this.Y9)):(this.rJ.nn(this.AU),this.Av.nn(this.sIa),this.xq(this.Y9),this.AU.od(b.U().C2));
this.rJ.Ub()||this.rJ.sj(!0,!0);return this.rJ.ke()};q.kWa=function(c,d,f){var e=b.Qda();c.O();c.M();this.rJ.Wb(c.aa());this.rJ.mc(c.ca());this.Av.Wb(c.aa());this.Av.mc(c.ca());this.Gq.Wb(c.aa());this.Gq.mc(c.ca());this.Av.tb(this.Aw.gU);this.Gq.tb(this.Aw.Gq);e.gk()?(this.Wb(c.aa()),this.mc(c.ca()),0==this.Av.bb().length?(this.Gq.Ua(0),this.Gq.Va(6),this.Av.Wb(c.aa()-10),this.Gq.Wb(c.aa()-10),this.Gq.vn(a.Og.Dq)):(this.Av.Ua(4),this.Av.Va(6),this.Gq.Ua(d.ca()),this.Gq.Va(12),this.Gq.vn(a.Og.ET))):
(this.Wb(c.aa()+4),this.mc(c.ca()+4),0==this.Av.bb().length?(this.Gq.Ua(1),this.Gq.Va(4),this.Gq.vn(a.Og.Dq)):(this.Av.Ua(2),this.Av.Va(4),this.Gq.Ua(d.ca()),this.Gq.Va(10),this.Gq.vn(a.Og.ET)));this.j6c(f.Okd);this.j8(c.O(),c.M(),r,r,null)};q.l7=function(a){this.rJ.bg(100);return q.j.l7.call(this,a)};c.f2b=function(){this.L2a=7;this.YY=this.W9=0;this.Eo=this.Eta=this.Fta=null;this.yAb=3;this.UT=this.Y2=this.X9=null;this.IP=0;this.oZa=b.Mda(-1,-1);this.Y2=new c.Z4b(this);b.rO().Bna().ua(this,a.w.W1,
this.eba)};var n=c.q(c.f2b,c.Dl);n.nb=function(){b.rO().Bna().Gp(this,a.w.W1);n.j.nb.call(this)};n.Q=function(){this.Eta=this.Fta=null;this.J7(null);this.iob();b.$(this.Y2);this.Y2=null;n.j.Q.call(this)};n.Mcb=function(a){this.IP|=a};n.h6=function(a){this.IP&=~a};n.pEd=function(a,b){this.IP=this.IP&~a|(b?a:0)};n.Dvd=function(){return this.UT};n.J7=function(c){if(this.UT!=c){this.UT&&(b.U().Ut(this.UT,!1),this.UT.Ea(this,this.aIb));if(this.UT=c)this.UT.Ga(this,this.aIb),this.UT.$D(!0);this.k(a.g.h)}};
n.otd=function(){return this.Eo};n.qtd=function(){return this.Fta};n.mtd=function(){return this.Eta};n.Oyd=function(){null==this.X9&&(this.X9=[]);return this.X9};n.Evd=function(){return this.Gq};n.Fvd=function(){return this.gU};n.Bma=function(){return b.tq().Hta/200};n.hud=function(){return 1};n.yCd=function(){return 2};n.iud=function(){return 1};n.zCd=function(){return 1};n.vRb=function(){var a=6,c=b.Qda();c&&c.gk()&&(a+=8);return a};n.xRb=function(){var a=4,c=b.Qda();c&&c.gk()&&(a+=4);return a};
n.tLc=function(){return 0!=(this.IP&1)};n.Rd=function(){return 0!=(this.IP&8)};n.GUb=function(){return 0!=(this.IP&16)};n.$Tb=function(){return 0!=(this.IP&32)};n.FUb=function(a){var c=!1;a=b.U().jC(a);null!=a&&a.Ifb()&&(c=!0);return c};n.iob=function(){if(this.X9){for(;0<this.X9.Qq();){var a=this.X9.us(0);b.$(a)}delete this.X9;this.X9=null}};n.Hka=function(b){this.FUb(b)||(this.N8b(b),this.Eo==b&&null==this.Fta&&null==this.Eta)||(this.jTb(),this.Eo=b,this.Eta=this.Fta=null,this.gU=this.Gq="",this.YY=
0,this.W9=a.x2?this.Bma():0,this.l9b(),null!=this.Eo&&null!=this.Eo.fb()&&this.Eo.ls(),this.MGa())};n.iod=function(b,c,d,e){this.FUb(b)||(this.N8b(b),this.Eo==b&&this.Fta==c&&this.Eta==e)||(this.Eo=b,this.Fta=c,this.Eta=e,this.gU=this.Gq="",this.YY=0,this.W9=a.x2?this.Bma():0,this.l9b(),this.MGa())};n.N8b=function(a){this.Eo!=a&&(null!=this.Eo&&this.Eo.Ea(this,this.FHb),null!=a&&a.Ga(this,this.FHb))};n.Uvb=function(a){this.Eo==a&&this.MGa()};n.PEb=function(c){var d,f=null;d=b.on();var e=b.RTc(d),
p=b.U().Mmb(d);if(null==p||p!=this.UT)null==e||e.dPc()||(e=null),null!=e&&(f=e.$d()),null!=e&&e.Rd()&&null!=f&&(null==this.Eo||this.Eo.$d()!=f)&&(f=e.$d().Qrc(d,a.zya.VMb))&&(f.Fd(a.Z.SBa),this.Eo==f&&(e=f)),this.Eo!=e&&this.Hka(null),this.GUb()?b.$ib(this.oZa,d)?++this.W9>=this.Bma()&&(this.W9=this.Bma(),this.J7(null),this.h6(16),this.YY=0,this.gU=this.Gq=""):(this.oZa=d,this.W9=0,this.Eo&&this.Eo.lQb()&&(this.gU=this.Gq="",this.YY=0,this.J7(null),this.h6(16))):(null!=this.Eo&&(e=!1,b.$ib(this.oZa,
d)||(this.oZa=d,this.Eo&&this.Eo.lQb()&&(this.W9=this.YY=0),e=!1,this.YY<this.L2a&&this.W9<this.Bma()?this.YY=0:c=!1),++this.YY>=this.L2a&&!e&&(this.YY=this.L2a,this.W9<this.Bma()?this.kWa():c=!1)),c&&3<=++this.yAb&&(this.yAb=3)),null==b.oO()&&this.iob()};n.npd=function(){return!1};n.kpd=function(){return!1};n.xUd=function(){};n.NLd=function(){};n.LXc=function(){this.tLc()||this.iob();this.h6(1);this.Hka(null)};n.KXc=function(a){b.U().roa()||(this.Mcb(32),this.Uvb(a),this.h6(32))};n.MXc=function(){(0>
b.Li(a.Na.ZGa)||0>b.Li(a.Na.ota)||0>b.Li(a.Na.UYa))&&this.Hka(null)};n.VSd=function(){};n.MGa=function(){null!=this.Eo?this.GUb()?this.kWa():this.$Tb()&&(this.YY=this.L2a,this.PEb(!1)):(this.J7(null),this.h6(16))};n.kWa=function(){var b,c,d=new t(this),e=null;this.Eo&&(c=new s(this),this.Eo.Fd(a.Z.TBa,c,null),e=c.zc,b=c.qb,c=c.z3a,this.Eo.Fd(a.Z.thb,this.Eo,d));0==b.length&&null===e?(this.Gq=b,this.gU=c,this.J7(null),this.h6(16)):(this.z9c(e,b,c,d),this.yAb=0)};n.jTb=function(){this.J7(null);this.h6(16)};
n.z9c=function(a,d,f,e){null==a&&(a=this.Y2);if(a!=this.Y2||this.$Tb()||0<d.length&&this.Gq!=d){var p=b.$x(0,0),g=b.$x(0,0),q=new c.ga(0,0,0,0);this.Gq=d;this.gU=f;this.h6(2);g=this.tdc(this.Gq);this.Rd()&&0<this.gU.length&&(p=this.tdc(this.gU),0==p.ca()&&(p=this.vdc(this.gU)));0==g.ca()&&(g=this.vdc(this.Gq),0<this.gU.length&&g.Wb(g.aa()+10));q=b.Qda();d=b.Mda(e.Jkc.O(),e.Jkc.M());q&&q.gk()&&null!=e.Uva?(q=this.lOb(d,g,p),d.cm(parseInt(e.Uva.ct(),10)),d.Il(parseInt(e.Uva.et()+e.Uva.Ja()+14,10)),
d.cm(parseInt(d.Hb()+(e.Uva.Qa()-q.aa())/2,10))):b.$ib(d,b.Mda(0,0))&&(d=b.on(),d.Il(d.Ib()+15));q=this.lOb(d,g,p);this.Rd()&&(this.J7(a),a==this.Y2?this.Y2.kWa(q,p,e):(e=b.Mda(q.O(),q.M()),a==this.UT&&a.hh()&&a.l7(e),a.j8(e.Hb(),e.Ib(),r,r,null)));this.Mcb(16)}};n.vdc=function(a){var d=b.$x(0,0),f=this.Y2.tPb(),e=new c.ga(0,0,0,0);b.PD(a,e,0,f);d.Wb(e.aa()+this.vRb());d.mc(e.ca()+this.xRb());return d};n.tdc=function(a){for(var d=b.$x(0,0),f=String.fromCharCode(13),e=this.Y2.tPb(),p=a.indexOf(f),
g=0;;)if(0<=p){var q;0!=p&&(q=a.substr(0,p));a=a.substr(p+1);0<q.length&&(p=new c.ga(0,0,0,0),b.PD(q,p,0,e),d.Wb(Math.max(d.aa(),p.aa())));g++;p=a.indexOf(f)}else{0<a.length&&(p=new c.ga(0,0,0,0),b.PD(a,p,0,e),d.Wb(Math.max(d.aa(),p.aa())),g++);break}1<g&&(this.Mcb(2),p=new c.ga(0,0,0,0),b.PD("W",p,0,e),d.Wb(d.aa()+this.vRb()),d.mc(p.ca()*g+this.xRb()));return d};n.lOb=function(a,d,f){var e=b.gC(),p=new c.ga(0,0,0,0),g=e.aa()-1,q=e.ca()-1,e=new c.ga(e.O()+1,e.M()+1,g,q),q=e.MW(e),e=q.aa();q.ca();
if(d.aa()<e){var n=a.Hb();n+d.aa()>e&&a.cm(q.wa-d.aa());p.Gb(a.Hb(),a.Ib());p.jh(d.aa(),d.ca());0<f.ca()&&p.A1(0,f.ca());f.aa()>p.aa()&&p.A1(f.aa()-p.aa(),0);0<f.aa()&&d.aa()+10>f.aa()&&p.A1(10,0);return p}if(d.aa()<g)return n=a.Hb(),n+d.aa()>g&&(n=g-d.aa()),p.Gb(n,a.Ib()),p.jh(d.aa(),d.ca()),p.A1(0,f.ca()),p;p=this.qCc(d,q,a);p.A1(0,f.ca());return p};n.qCc=function(a,d,f){var e=b.gC(),p=e.aa()-2,g=e.ca()-2,g=new c.ga(e.O()+1,e.M()+1,p,g),e=[b.JS(),b.JS(),b.JS(),b.JS()],p=[];p.push(3);p.push(2);p.push(1);
p.push(0);var q,n,r,s,g=d.MW(g);g.aa();g.ca();d=a.aa()*a.ca();q=g.O();n=g.M();e[0].Gb(q,n);e[0].jh(f.Hb()-q,f.Ib()-n);e[1].Gb(f.Hb(),n);e[1].jh(g.wa-f.Hb(),f.Ib()-n);e[2].Gb(q,f.Ib());e[2].jh(f.Hb()-q,g.va-f.Ib());e[3].Gb(f.Hb(),f.Ib());e[3].jh(g.wa-f.Hb(),g.va-f.Ib());for(n=g=r=0;4>n;n++){q=p[n];s=e[q].aa()*e[q].ca();r=Math.max(r,s);if(d<s){g=q;break}r==s&&(g=q)}e=e[g];p=a.ca();a=Math.min(a.aa(),e.aa());d=(d/a+p-1)/p*p;switch(g){case 0:e.Gb(f.Hb()-a,f.Ib()-d);e.jh(a,d);break;case 1:e.Gb(f.Hb(),f.Ib()-
d);e.jh(a,d);break;case 2:e.Gb(f.Hb()-a,f.Ib());e.jh(a,d);break;case 3:e.Gb(f.Hb(),f.Ib()),e.jh(a,d)}return e};n.l9b=function(){this.Rd();var a=null!=this.Eo&&null!=this.Eo.Sa()&&this.Eo.Sa().xS()&&this.Eo.Rd();this.IP=this.IP&-9|(a?8:0)};n.aIb=function(b,c){switch(c.Za){case a.g.xb:case a.g.Tb:this.J7(null)}};n.eba=function(){b.U().YPa()||b.U().roa()||this.PEb(!0)};n.FHb=function(b,c){switch(c.Za){case a.g.xb:case a.g.Tb:this.Hka(null)}}},{rp:["PRIM_PPNL"]});
