window.LANSA.addSrc("msg",function(d,c,a,b,r){d.Db("PRIM_PPNL");a.Gpa={U6:0,aVc:1,cVc:2,YUc:4,ZUc:8};a.Gpa.u={NONE:a.Gpa.U6,TEXT:a.Gpa.aVc,WARNING:a.Gpa.cVc,ERROR:a.Gpa.YUc,FATAL:a.Gpa.ZUc};a.B0={F6b:1,H6b:2,G6b:4};a.B0.u={ERROR:a.B0.F6b,QUESTION:a.B0.H6b,INFORMATION:a.B0.G6b};a.cq={Tmd:16,f5a:1,AKa:16,xKa:32,CKa:64,zKa:128,BKa:256,yKa:512};a.cq.u={NONE:a.cq.f5a,OK:a.cq.AKa,CANCEL:a.cq.xKa,YES:a.cq.CKa,NO:a.cq.zKa,RETRY:a.cq.BKa,IGNORE:a.cq.yKa};a.qI={tlb:16,J6b:48,K6b:192,L6b:224,I6b:768};a.qI.u=
{OK:a.qI.tlb,OKCANCEL:a.qI.J6b,YESNO:a.qI.K6b,YESNOCANCEL:a.qI.L6b,IGNORERETRY:a.qI.I6b};c.M0b=function(){t.H.call(this)};var t=c.q(c.M0b,c.Hd);d.Ad(c.M0b,"PRIM_MSG",{});c.oib=function(){s.H.call(this);this.EE=[]};var s=c.q(c.oib,c.Hd);s.mHc=function(){d.Db("PRIM_PCOL");var a=new c.QZb(this);return new c.p0(a)};s.Ph=function(a,b){var d=new c.pib(this,a);this.EE.push(d);d.Bj(b);this.dBc(d);return d};s.fq=function(a){if(a)for(var b=0;b<this.EE.length;b++){var c=this.EE[b];c.fa()==a&&(this.xNb(c),this.EE.splice(b--,
1),c.cHb())}};s.grc=function(){for(;0<this.EE.length;){var a=this.EE.shift();this.xNb(a);a.cHb()}};s.dBc=function(b){var c=d.Zb();c.ac("MESSAGE",b);this.Ca(a.w.IUc,c);c.Bc()};s.xNb=function(b){var c=d.Zb();c.ac("MESSAGE",b);this.Ca(a.w.JUc,c);c.Bc()};d.Ad(c.oib,"PRIM_MSGQ",{Oa:{Messages:{a:s.mHc}},qc:{Add:function(a,b){return this.Ph(d.ha(a),b===r?null:b)},Clear:function(a){return this.fq(a===r?null:a)},ClearAll:function(){return this.grc()}}});c.QZb=function(a){q.H.call(this);this.SIa=a};var q=c.q(c.QZb,
c.Nda);q.Ac=function(){return this.SIa.EE.length};q.Px=function(a){return this.SIa.EE[a]};c.pib=function(a,b){n.H.call(this);this.SIa=a;this.yg=b;this.Ya=null};var n=c.q(c.pib,c.Hd);n.is=function(){return this.yg};n.fa=function(){return this.Ya};n.Bj=function(a){this.sg()&&this.Ya!=a&&(null!=this.Ya&&(this.Ya.AO(this),this.Ya.Ea(this,this.Yt)),this.Ya=a)&&(a.TM(this),a.Ga(this,this.Yt))};n.sg=function(){return null!==this.SIa};n.cHb=function(){this.Bj(null);this.yg="";this.SIa=null};n.Yt=function(b,
c){switch(c.Za){case a.g.xb:this.Bj(null)}};d.mb(c.pib,"PRIM_MSGQ","Message",{Oa:{Text:{a:n.is},Control:{a:n.fa,f:n.Bj}}});c.U4b=function(){k.H.call(this);this.Zta=[]};var k=c.q(c.U4b,c.Hd);k.Q=function(){this.Ak();k.j.Q.call(this)};k.ie=function(a){return this.Zta[a]};k.Ac=function(){return this.Zta.length};k.Ph=function(b){this.Zta.push(b);this.k(a.g.h)};k.Ak=function(){this.Zta=[];this.k(a.g.h)};k.SGc=function(){for(var a="",b=0;b<this.Zta.length;b++){var c=this.Zta[b];c.length>a.length&&(a=c)}return a};
d.mb(c.U4b,"PRIM_WEB","MessageBoxCaptions",{qc:{Add:k.Ph,RemoveAll:k.Ak}});c.T4b=function(){h.H.call(this);d.Db("PRIM_PHBN");d.Db("PRIM_LABL");this.BJa=this.N$=this.hka=null;this.RIa=a.B0.G6b;this.EC=a.qI.tlb;this.of=a.cq.f5a;this.QZa=[];this.VT=null;this.w3a=new c.lu;this.v3a=new c.PS;this.NE=new c.yo;this.fJ=d.ld("PRIM_WEB","MessageBoxCaptions");this.fJ.Fa();this.fJ.Ga(this,this.NHb);this.Af=new c.Njb;this.jp=new c.PS;this.Ym=new c.PS;this.QM=new c.PS;this.YP=new c.PS;this.kQ=new c.PS;this.qM=new c.PS;
this.Ym.ua(this,a.w.Vb,this.vwc);this.jp.ua(this,a.w.Vb,this.uuc);this.QM.ua(this,a.w.Vb,this.ryc);this.YP.ua(this,a.w.Vb,this.twc);this.kQ.ua(this,a.w.Vb,this.$wc);this.qM.ua(this,a.w.Vb,this.Rvc);this.NE.Pa(this);this.Af.Pa(this);this.jp.Pa(this);this.Ym.Pa(this);this.QM.Pa(this);this.YP.Pa(this);this.kQ.Pa(this);this.qM.Pa(this);this.N$=new c.pb;this.BJa=new c.Rf;this.N$.od(this.BJa);this.BJa.xd(a.l.uT);this.BJa.bg(9);this.Fcc(this.N$);this.N$.Fa();this.BJa.Fa();this.NE.Va(90);this.NE.Qe(!1);this.NE.Ua(57);
this.NE.Eb(!0);this.NE.OI(!0);this.NE.yX(!0);this.Af.Xd(6);this.Af.vz(a.Og.Dq);this.Af.Va(20);this.Af.Ua(57);this.Af.ws(64);this.Af.bE(64);this.Af.mc(64);this.Af.Wb(64);this.Af.Qe(!1);this.Ym.tb(b.yl().ok||"OK");this.YP.tb(b.yl().no||"No");this.QM.tb(b.yl().yes||"Yes");this.kQ.tb(b.yl().retry||"Retry");this.jp.tb(b.yl().cancel||"Cancel");this.qM.tb(b.yl().ignore||"Ignore");this.Uac(this.EC);this.gfa(!1);this.Uqb(!0)};var h=c.q(c.T4b,c.by);h.Q=function(){this.fJ.Ea(this,this.NHb);this.fJ.Ab();this.fJ=
null;this.wGb();h.j.Q.call(this)};h.A4c=function(a){this.w3a.vb(a)};h.ECc=function(){return this.w3a.Lg()};h.FCc=function(){return this.w3a.Tk()};h.Vla=function(){return this.v3a.Lg()};h.EI=function(a){this.v3a.vb(a)};h.yCc=function(){return this.v3a.Tk()};h.pFa=function(b){b!=this.xW()&&(this.tb(b),this.JYa(),this.k(a.g.h))};h.xW=function(){return this.bb()};h.W6c=function(b){this.fJ.Ak();b!=this.SPb()&&(this.fJ.Ph(b),this.k(a.g.h))};h.HCc=function(){return this.fJ};h.SPb=function(){return 0<this.fJ.Ac()?
this.fJ.ie(0):""};h.ibc=function(b){this.VT!==b&&(null!=this.VT&&(this.VT.Ea(this,this.cIb),this.VT.Ab()),this.VT=b,null!==this.VT&&(this.VT.Fa(),this.VT.Ga(this,this.cIb)),this.JYa(),this.k(a.g.h))};h.BDc=function(){return this.VT};h.X6c=function(b){this.RIa!=b&&(this.RIa=b,this.JYa(),this.k(a.g.h))};h.Zzd=function(){return this.RIa};h.Uac=function(b){this.EC=b;this.Ym.Eb(0!=(this.EC&a.cq.AKa));this.jp.Eb(0!=(this.EC&a.cq.xKa));this.QM.Eb(0!=(this.EC&a.cq.CKa));this.YP.Eb(0!=(this.EC&a.cq.zKa));
this.qM.Eb(0!=(this.EC&a.cq.yKa));this.kQ.Eb(0!=(this.EC&a.cq.BKa))};h.xud=function(){return this.EC};h.LRd=function(a){this.of=a};h.KBd=function(){return this.of};h.Jsc=function(b,d,g){var f=new c.lu;f.Pa(this.NE);f.Va(0);f.Qe(!1);f.Ua(d);f.vn(a.Og.Dq);f.Wb(g.Qa());f.mc(g.Ja());f.Ye(!1);f.tb(b);return f};h.wdc=function(a,d){var g=b.$x(0,0),f=new c.ga(0,0,0,0);b.PD(a,f,0,d);g.Wb(f.aa()+2);g.mc(f.ca()+2);return g};h.iIc=function(){if(null!=this.VT)return this.VT;var d="";switch(this.RIa){case a.B0.F6b:d=
"lansa_error.png";break;case a.B0.H6b:d="lansa_question.png";break;default:d="lansa_information.png"}var f=new c.eO;f.rt(b.Ec(d));return f};h.Xnc=function(){var a=this.v3a.Tk().$a.AF(),b=null;this.Ym.Tk().Ak();this.jp.Tk().Ak();this.QM.Tk().Ak();this.YP.Tk().Ak();this.kQ.Tk().Ak();this.qM.Tk().Ak();for(var c=0;null!=a&&c<a.length&&null!=(b=a[c]);c++)this.Ym.Tk().Ph(b),this.jp.Tk().Ph(b),this.QM.Tk().Ph(b),this.YP.Tk().Ph(b),this.kQ.Tk().Ph(b),this.qM.Tk().Ph(b);this.Ym.sj(!1,!0);this.jp.sj(!1,!0);
this.QM.sj(!1,!0);this.YP.sj(!1,!0);this.kQ.sj(!1,!0);this.qM.sj(!1,!0)};h.coc=function(){var a=this.w3a.Tk().$a.AF(),b=null;this.NE.Tk().Ak();for(var c=0;null!=a&&c<a.length&&null!=(b=a[c]);c++)this.NE.Tk().Ph(b);this.NE.sj(!1,!0)};h.wra=function(){this.hka=b.qT();this.of=a.cq.f5a;this.DFb();var c=b.on();this.VA(a.ci.cL,null,c,null);this.z5c()};h.JYa=function(){this.VN()&&(this.DFb(),this.Wh())};h.DFb=function(){var a;this.wGb();this.Af.wd(this.iIc());this.Xnc();this.coc();a=this.vDb();this.KWc(a)};
h.gEa=function(){this.vDb();h.j.gEa.call(this)};h.vDb=function(){var a=this.CB(),b=this.Aqc(),c=this.Gqc(),c=this.Fqc(c),d=this.Cqc(a),f=this.Bqc(b),h=this.Jqc(c,d,f);this.b0c(h,b,d);this.Cnc(b,c,f,h);return a};h.b0c=function(a,b,c){this.Wb(a.Qa());this.mc(a.Ja());a=b.Qa();b=b.Ja();this.jp.Wb(a);this.Ym.Wb(a);this.QM.Wb(a);this.YP.Wb(a);this.kQ.Wb(a);this.qM.Wb(a);this.jp.mc(b);this.Ym.mc(b);this.QM.mc(b);this.YP.mc(b);this.kQ.mc(b);this.qM.mc(b);this.NE.Wb(c.Qa());this.NE.mc(c.Ja())};h.Cnc=function(a,
b,c,d){this.y4c(a);a=d.Ja()-c.Ja();this.jp.Ua(a);this.Ym.Ua(a);this.QM.Ua(a);this.YP.Ua(a);this.kQ.Ua(a);this.qM.Ua(a);this.Af.Va(20);this.Af.Ua(this.ir.Ja()+20);this.NE.Va(40+b.Qa());this.NE.Ua(this.ir.Ja()+20)};h.Jqc=function(a,c,d){var f=b.gC(),h=b.$x(0,0);a=this.Eqc(a,c);c=this.wB.$Oa(this.wB.bb(),this.wB.Mn().length)+10;h.Wb(Math.max(a.Qa(),c,d.Qa())+60);h.mc(this.ir.Ja()+a.Ja()+d.Ja()+40);h.Wb(Math.min(f.aa()-40,h.Qa()));h.mc(Math.min(f.ca()-40,h.Ja()));return h};h.Ama=function(a,b){var c=a;
b.length>a.length&&(c=b);return c};h.RGc=function(){var a="",a=this.Ama(this.Ym.bb(),a),a=this.Ama(this.jp.bb(),a),a=this.Ama(this.QM.bb(),a),a=this.Ama(this.YP.bb(),a),a=this.Ama(this.kQ.bb(),a),a=this.Ama(this.qM.bb(),a);return" "+a+" "};h.Aqc=function(){var a=this.RGc(),c=b.$x(0,0),c=this.Ym.ke();return c=this.wdc(a,c)};h.CB=function(){var a=this.fJ.SGc(),c=b.$x(0,0),c=this.NE.ke();return c=this.wdc(a,c)};h.Gqc=function(){var a=b.$x(0,0);a.Wb(this.Af.Qa());a.mc(this.Af.Ja());return a};h.Cqc=function(a){var c=
b.$x(0,0),d=a.Qa()+4;a=this.fJ.Ac()*(a.Ja()+4);d+=20;a+=20;d=170>d?170:d;a=70>a?70:a;a=630<a?630:a;c.Wb(630<d?630:d);c.mc(a);return c};h.Fqc=function(a){var c=b.$x(0,0);c.mc(a.Ja()+16);c.Wb(a.Qa()+8);return c};h.Eqc=function(a,c){var d=b.$x(0,0);d.mc(Math.max(a.Ja(),c.Ja()));d.Wb(2+a.Qa()+2+c.Qa()+2);return d};h.Bqc=function(a){var c=b.$x(0,0),d=66>a.Qa()?66:a.Qa(),f=25>a.Ja()?25:a.Ja();a.Wb(d);a.mc(f);c.mc(a.Ja()+24);c.Wb(3*a.Qa()+8);return c};h.y4c=function(b){b=b.Qa()+20;var c=1;this.EC&a.cq.BKa&&
(this.kQ.Va(this.Qa()-c*b),++c);this.EC&a.cq.yKa&&(this.qM.Va(this.Qa()-c*b),++c);this.EC&a.cq.xKa&&(this.jp.Va(this.Qa()-c*b),++c);this.EC&a.cq.AKa&&(this.Ym.Va(this.Qa()-c*b),++c);this.EC&a.cq.zKa&&(this.YP.Va(this.Qa()-c*b),++c);this.EC&a.cq.CKa&&this.QM.Va(this.Qa()-c*b)};h.KWc=function(a){for(var b=0,c=a.Ja(),d=0;d<this.fJ.Ac();d++)this.QZa.push(this.Jsc(this.fJ.ie(d),b,a)),b+=c};h.z5c=function(){switch(this.EC){case a.qI.tlb:case a.qI.J6b:this.Ym.jf(!0,!0);break;case a.qI.K6b:case a.qI.L6b:this.QM.jf(!0,
!0);break;case a.qI.I6b:this.qM.jf(!0,!0)}};h.Ena=function(a){this.of=a;this.dn();b.wz(this.hka);this.hka=null};h.wGb=function(){for(var a=0;a<this.QZa.length;++a)this.QZa[a].Pa(null);this.QZa=[]};h.NHb=function(){this.JYa()};h.vwc=function(){this.Ena(a.cq.AKa)};h.uuc=function(){this.Ena(a.cq.xKa)};h.ryc=function(){this.Ena(a.cq.CKa)};h.twc=function(){this.Ena(a.cq.zKa)};h.$wc=function(){this.Ena(a.cq.BKa)};h.Rvc=function(){this.Ena(a.cq.yKa)};h.cIb=function(b,c){switch(c.Za){case a.g.xb:case a.g.Tb:this.ibc(null);
break;case a.g.h:this.k(a.g.h)}};d.mb(c.T4b,"PRIM_WEB","MessageBox",{Oa:{Title:{a:h.xW,f:function(a){this.pFa(d.ha(a))}},Caption:{a:h.SPb,f:function(a){this.W6c(d.ha(a))}},Text:{a:h.is,f:function(a){this.YO(d.ha(a))}},Captions:{a:h.HCc},Image:{a:function(){return d.ta(this.RIa,a.B0.u)},f:function(b){this.X6c(d.qa(b,a.B0.u))}},CustomImage:{a:h.BDc,f:function(a){this.ibc(a)}},Result:{a:function(){return d.ta(this.of,a.cq.u)}},Buttons:{a:function(){return d.ta(this.EC,a.qI.u)},f:function(b){this.Uac(d.qa(b,
a.qI.u))}},CaptionStyle:{a:h.ECc,f:function(a){this.A4c(a)}},CaptionStyles:{a:h.FCc},ButtonStyle:{a:h.Vla,f:function(a){this.EI(a)}},ButtonStyles:{a:h.yCc}},qc:{Show:h.wra}});c.Bjb=function(b){this.D1a=[];this.EE=[];this.Ya=b;this.zc=new c.by;this.zc.ua(this,a.w.jx,this.dba);this.zc.ua(this,a.w.bR,this.m8a);this.qja=new c.yo;this.qja.kb(new c.ga(0,0,100,25));this.qja.Pa(this.zc);this.qja.Qe(!1);this.qja.Nb(a.wXb)};var f=c.q(c.Bjb,c.Dl);f.bt=function(){return this.zc};f.qg=function(){return 0==this.EE.length};
f.TM=function(a){this.EE.push(a)};f.AO=function(a){this.EE.splice(this.EE.indexOf(a),1);this.qg()&&this.zc.dn()};f.dba=function(){d.Db("PRIM_LABL");for(var b=0,f=6,g=100;b<this.EE.length;b++){var h=this.D1a[b],k=this.EE[b];h||(h=new c.lu,h.Va(5),h.Qe(!1),h.Ua(f),h.vn(a.Og.Dq),h.Wb(320),h.mc(20),h.Ye(!1),this.D1a.push(h));h.Pa(this.qja);h.tb(k.is());h.Zqc();g<h.Qa()+15&&(g=h.Qa()+15);f+=25}for(;b<this.D1a.length;b++)h=this.D1a[b],h.Pa(null);this.qja.mc(f+6);this.qja.Wb(g);this.zc.mc(f+6);this.zc.Wb(g)};
f.m8a=function(){this.Ya.sj(!0)}},{rp:["PRIM_PPNL"]});
